### ISSUE TITLE
Support the enrollment of yubikey to encrypt harddisk

### ISSUE THREAD

**Issue by privacyidea** [privacyidea/privacyidea#10]
The yubikey can be used to unlock an LUKS slort for harddisk encryption.
https://github.com/cornelinux/yubikey-luks
Together with privacyIDEA the yubikeys can be enrolled and managed.

**Comment by cornelinux** [comment]
The Machine concept needs to be implemented in version 2.0
This should be done not by defining client machines but by created machine resolvers, that find machines in AD or anywhere else.

**Comment by cornelinux** [comment]
Close this issue, since we opened new #100
