### ISSUE TITLE
Do not store startt_tls if ldaps is set

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1002]
Version: 2.22

By default the LDAP resolver config sets ``START_TLS`` to ``true``.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/config/controllers/configControllers.js#L863

# Observed behaviour

This results in the following effect: 

1. Go to the LDAP resolver config view and directly enter an URL with "ldaps://".
2. Save this resolver.
3. The resolverconfig will be saved with ``start_tls=true``

# Expected behaviour

The start_tls should not be saved as true, but as false in the case of ldaps.

We probably might need a function in configController.js, that monitors the URL input line and sets start_tls to false, if the URL starts with "ldaps"

**Comment by fredreichbier** [comment]
As I wrote above, It seems like ``ldap3`` does not attempt to use STARTTLS if LDAPS is used. Thus, having ``START_TLS`` set to 1 does no harm. We can just keep the current behavior, as it has the advantage that TLS is preserved if the server URI is changed to ``ldap://...``.
