### ISSUE TITLE
HSM CKR_SESSION_HANDLE_INVALID

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1003]
# What did you try to do?

Use privacyIDEA with an HSM (aes module) Luna SA.

# What outcome did you expect?

Should work :-)

# What outcome did you experience?

At some not reproducable points we receive a **CKR_SESSION_HANDLE_INVALID (0x000000B3)**.

This happens here:

    [WARNING][privacyidea.lib.security.aeshsm:200] Decryption failed: CKR_SESSION_HANDLE_INVALID (0x000000B3)   
    [WARNING][privacyidea.lib.crypto:363] ERR707: Failed to decrypt after multiple retries.
 
or here

<pre>
ERROR in app: Exception on /auth [POST]
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python2.7/site-packages/flask/app.py",
line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/lib/python2.7/site-packages/flask/app.py",
line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/privacyidea/lib/python2.7/site-packages/flask/app.py",
line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/privacyidea/lib/python2.7/site-packages/flask/app.py",
line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/privacyidea/lib/python2.7/site-packages/flask/app.py",
line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File
"/opt/privacyidea/lib/python2.7/site-packages/privacyidea/api/lib/postpo
licy.py",
line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File
"/opt/privacyidea/lib/python2.7/site-packages/privacyidea/api/auth.py",
line
265, in get_auth_token
    nonce = geturandom(hex=True)
  File
"/opt/privacyidea/lib/python2.7/site-packages/privacyidea/lib/crypto.py"
,
line 500, in geturandom
    ret = hsm.random(length)
  File
"/opt/privacyidea/lib/python2.7/site-packages/privacyidea/lib/security/a
eshsm.py",
line 164, in random
    r_integers = self.session.generateRandom(length)
  File
"/opt/privacyidea/lib/python2.7/site-packages/PyKCS11/__init__.py",
line 1513, in generateRandom
    raise PyKCS11Error(rv)
PyKCS11Error: CKR_SESSION_HANDLE_INVALID (0x000000B3)
</pre>

# Configuration

* privacyIDEA Version: 2.21.4
* Installation method: RPM repo on RHEL7

## more details: 

* OS: RHEL 7
* Webserver: Apache. (Also only with one wsgi process and 15 threads)

# Todos

We might at least need to catch a pykcs11 error during random generation:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/security/aeshsm.py#L169

**Comment by reinerRubin** [comment]
Hello,
Did it help? We have ecountered the same problem.
