### ISSUE TITLE
Assign a token with an empty serial number

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1011]
# What did you try to do?

Assign a token to a user in the webui.
Got to the user view and click assign token.

# What outcome did you expect?

Receive an error, when the serial number is empty.

# What outcome did you experience?

If the serial number is left blank, i can still press "assign". The token with the lowest database id gets assigned to the user.

# Configuration

* privacyIDEA Version: 2.22

**Comment by cornelinux** [comment]
The line https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/token.py#L418 uses ``getParam`` ``required`` which only checks, if the parameter exists, but not, if the parameter is empty!

In fact we would also need ot check, if the param is empty.
I think we can put this into ``getParam`` using an additional parameter.

We could also disable the "assign" button in the UI, if the serial number is empty.

**Comment by fredreichbier** [comment]
I also reproduced both #1010 and #1011 on Firefox and Chrome, and also with 2.21. Weird! I could have sworn that this issue didn't occur before...?
