### ISSUE TITLE
SQLAlchemy unicode warnings

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1019]
When running privacyIDEA, we get several warnings like:

```
/home/fred/privacyidea/privacyidea/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'OATH0000FAE6'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/home/fred/privacyidea/privacyidea/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'tokenkind'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/home/fred/privacyidea/privacyidea/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'software'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/home/fred/privacyidea/privacyidea/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'hashlib'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
```

These are harmless, but look quite dangerous. We could get rid of them by inserting some ``unicode()`` calls in models.py, see #1000.

**Comment by fredreichbier** [comment]
I believe this will be solved by the migration to Python 3.

**Comment by roelzkie15** [comment]
@fredreichbier Is there anyway to solve this without migrating to Python 3?

**Comment by fredreichbier** [comment]
Hi @roelzkie15, I believe it is safe to ignore the warnings because the incoming strings should only be ASCII anyway -- so they look dangerous but are actually not harmful. Do you just want to avoid cluttering your log with the warnings, or is there some other issue you're experiencing?

**Comment by cornelinux** [comment]
In privacyIDEA 3.0 we tried to convert internally all strings to unicode. So there should be at least be less warnings.
