### ISSUE TITLE
Some time deltas do not support specifying seconds

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1033]
Right now, we have two functions to parse time deltas:

``parse_timedelta`` only parses positive timedeltas, but does not support seconds:
https://github.com/privacyidea/privacyidea/blob/834ff2f77c37863244a94a58ae7b159d70bbc809/privacyidea/lib/utils.py#L385

``parse_time_delta`` supports negative timedeltas and requires "+" and "-" prefixes, and also supports seconds.
https://github.com/privacyidea/privacyidea/blob/834ff2f77c37863244a94a58ae7b159d70bbc809/privacyidea/lib/utils.py#L782

As a result, the auth cache does not support specifying time deltas in seconds, because it uses ``parse_timedelta``. Other features may behave similarly.

We should probably consolidate these methods somehow? But we need to keep in mind that for some cases, specifying negative time deltas might not make sense.

**Comment by cornelinux** [comment]
I would not call this a bug. Everything works as "designed". It is simply a bad design and we have a redundant function...

**Comment by cornelinux** [comment]
I will push a PR in a few seconds
