### ISSUE TITLE
Shorten some audit information so that they fit into the info column

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1037]
I noticed that some actions do not appear in the audit log by default because their ``info`` field is too long. Enabling SQL Truncate would of course be an action, but IMHO we could also shorten some infos.

An example: Successful authentication via the passthru policy is missing from the audit log.
```
[2018-04-27 15:25:07,007][21276][139772704446208][ERROR][privacyidea.lib.auditmodules.sqlaudit:241] DATA: {'info': u"The user authenticated against the RADIUS server alt according to policy 'passthru'.", 'realm': u'ucsrealm', 'tokentype': None, 'success': True, 'privacyidea_server': 'localhost', 'client_user_agent': None, 'client': '::1', 'user': u'fred', 'resolver': u'ucsresolver', 'action_detail': '', 'action': 'POST /validate/check', 'serial': None}
```

The ``info`` column is 50 characters by default, and I guess we could shorten the message ``u"The user authenticated against the RADIUS server alt according to policy 'passthru'."`` (84 chars) a bit.

**Comment by cornelinux** [comment]
We have the setting PI_AUDIT_SQL_TRUNCATE in pi.cfg. 
This should truncate the fields accordingly.

**Comment by fredreichbier** [comment]
I know -- but I think shortening some messages like the above would still be a good idea because:
* PI_AUDIT_SQL_TRUNCATE is False on default Ubuntu installs. So users will not see successful passthru authentications by default.
* Even if SQL truncation is enabled, the truncated info will miss information: The info, truncated to 50 characters, is just ``"The user authenticated against the RADIUS server a"``, which cuts off both the policy name and the RADIUS server.
We could, e.g., shorten the info to ``by RADIUS server X and policy 'Y'.``. Of course, this may still fail if we have long RADIUS server or policy names.

**Comment by cornelinux** [comment]
Right. Sounds good. We also should set TRUNCATE  to true for new installations.
