### ISSUE TITLE
Feature PrivacyIdea as standalone app

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#1043]
Hi, it would be great in today container world if this app is running as standalone process without apache

**Comment by cornelinux** [comment]
Currently the manager-command requires a username and a password at the command line.

https://github.com/privacyidea/privacyidea/blob/master/pi-manage#L488

I would think that we coud do something like this:

    echo "username@realm\npassword" | pi-manage validate

I think the manager_command does not allow in this case to skip the username and password. We might add another command like "pi-manage validate2"... which is a bit nasty, but keeps backward compat.

@fredreichbier what do you think?

**Comment by fredreichbier** [comment]
Accepting username and password via stdin sounds sensible! In terms of implementation, I think we could even go further and move the new functionality to a new script ``privacyidea-standalone``. Then, we wouldn't clutter the ``pi-manage`` interface.
... or we move it to a new subcommand of ``pi-manage``? Like ``pi-manage standalone validate``?

**Comment by cornelinux** [comment]
I think I would prefer a new script. Also already thought about that.

**Comment by p53** [comment]
i meant more something like this: http://flask.pocoo.org/docs/1.0/deploying/wsgi-standalone/

**Comment by cornelinux** [comment]
You can do this already. Either use uWsgi as denoted there or run 

   pi-manage runserver

**Comment by cornelinux** [comment]
We do this in #1093
