### ISSUE TITLE
Allow auth_cache to cache only for a limited number of authentications

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1059]
The ``auth_cache`` is policy in scope=auth.
http://privacyidea.readthedocs.io/en/latest/policies/authentication.html#auth-cache

Currently you can define it like 4h/4m, which would mean cache for 4 hours if every 4 minutes there is a request. 

We need to enhance this login to "cache for 5 seconds, but only allow 2 authentications within this 5 seconds".

This could be specified like "5s/2".

To achieve this, we need to

1. allow seconds in the auth_cache
2. count the authentications performed by the auth_cache. Therefore we need to add a column for counting the auth's https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L2431

**Comment by cornelinux** [comment]
This was e.g. needed for the ldap proxy, if you know, that the same OTP would be used within the next 5 seconds, but only two times.

**Comment by cornelinux** [comment]
Currently the auth_cache allows to specify  2h/5m, which means, that the the user may authenticate for 2h (checked in the column ``first_auth``, if the last authentication happened less then 5 minutes ago (checkd in the column ``last_auth``).

Thus we need the additional column ``auth_count``. That simply records, how often this auth_cache entry was used.
The the setting 10s/2 will mean, check ``first_auth`` to be less than 10s ago and theck ``auth_count`` to be less than 2.
(If it exceeds the auth_cache entry can be deleted again.)

**Comment by plettich** [comment]
Forgot to add the migration script for the database...
