### ISSUE TITLE
privacyidea-token-janitor still uses deprecated flask.ext.script

### ISSUE THREAD

**Issue by stojmir** [privacyidea/privacyidea#1063]
# ./privacyidea-token-janitor 
Traceback (most recent call last):
  File "./privacyidea-token-janitor", line 44, in <module>
    from flask.ext.script.commands import InvalidCommand
ImportError: No module named ext.script.commands

Importing flask.ext.script is deprecated, need to use flask_script instead.

**Comment by cornelinux** [comment]
Other scripts in ``tools/`` do so, too.
We should change all the scripts.
