### ISSUE TITLE
Add Audit Module, that does SQL Audit _and_ Audit to file

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1072]
We need the possiblitiy to run audit logs to sql audit and to a file.

We either could 
* create a new audit module, that does both, inherited from SQLAudit
* enhance the SQLAudit module
* or allow the audit framework to write to multiple audit modules in parallel (sqlaudit and fileaudit)

**Comment by fredreichbier** [comment]
Another idea if we do not want to change the audit API too much: We could also create a new audit class ``ContainerAudit`` that holds a list of ``Audit`` objects (e.g. one SQL and one File Audit object) and just forwards all ``log``, ``finalize_log``, ... calls to all these child audit objects. But then it's the question how we would handle ``search()``. Maybe we would set one of the child audit objects to be the "primary" audit object which is used for searches (this could be the SQL audit object then).

... but maybe this gets a bit too complicated :)

**Comment by cornelinux** [comment]
The problem with a **list** of audit modules is, that one audit module is responsible for returning the data for the view in the UI...

# Requiremets

* the file data does not need to be signed
* there is no special format requirement. We could use csv or json. (I probably would prefer csv for the sake of readability???=

**Comment by cornelinux** [comment]
I also thought that it might be interesting to configure a list of audit modules anyways!

The logfile/Syslog audit module can write a json representation per line. (See internal ticket 342)

**Comment by fredreichbier** [comment]
I agree, having a list of audit modules sure sounds interesting!

We could have one "primary" read-write audit module that is used to display audit data in the UI (i.e. SQLAudit), and multiple write-only audit modules (like writing audit log to CSV or JSON files, or some external monitoring database)

**Comment by cornelinux** [comment]
Currently we have:

    PI_AUDIT_MODULE = 'privacyidea.lib.auditmodules.sqlaudit'

We could enhance this to:

    PI_AUDIT_MODULE = ['privacyidea.lib.auditmodules.sqlaudit','privacyidea.lib.auditmodules.syslog', mymodules.pi_special_audit']

**Comment by plettich** [comment]
To make things even more flexible (and also more complex), we could add the information (*read* and/or *write*) to the audit modules. If there is no audit module with **read** capabilities, we simply cannot display an audit log in the UI.

**Comment by cornelinux** [comment]
The text output should play nice with logstash and splunk.

**Comment by cornelinux** [comment]
We could also use the python logging functionalities, so that the audit information could be sent everyquere.

Maybe the easier approach would be, to actually not create an audit module but rather create a log enty in the SQL Audit Module just where we write the audit data to the database.
In parallel we could simply write a log entry. Then we could have a logging configuration, that simply writes this very log entry to a dedicated audit file.

This way we would only need one or two lines of code. :-)

**Comment by cornelinux** [comment]
misclicked.

**Comment by fredreichbier** [comment]
Idea: We configure a list of audit modules.
An audit module is either read-write or write-only, like @plettich suggested.
Audit log messages are written to *all* audit modules in the list.
For displaying the audit log in the WebUI, we use the *first* audit module in the list with read capability. If there is no audit module with read capability, we do not display any log messages.

**Comment by fredreichbier** [comment]
Todo: Check the accepted log formats of LogStash/Splunk to see what format would make the most sense for audit logs.

**Comment by plettich** [comment]
Since i am reviewing #1537: we need to check if there is a readable audit-log in some cases.
- [ ] [`auth_user_timelimit()`](https://github.com/privacyidea/privacyidea/blob/65b1a9247cef6c2dccb3dee6ea66ab2779f94593/privacyidea/lib/policydecorators.py#L335)

**Comment by cornelinux** [comment]
> Since i am reviewing #1537: we need to check if there is a readable audit-log in some cases.
> 
> * [ ]  [`auth_user_timelimit()`](https://github.com/privacyidea/privacyidea/blob/65b1a9247cef6c2dccb3dee6ea66ab2779f94593/privacyidea/lib/policydecorators.py#L335)

What do you mean by this?

**Comment by cornelinux** [comment]
What I mentioned earlier would be the following:

In the ``sqlaudit.py`` we would add in the method ``finalize_log`` something like this:

~~~~python
            log.debug(u"AUDIT_DATA: {0!s}".format(self.audit_data))
        except Exception as exx:  # pragma: no cover
~~~~

The log line could output the desired logging information.
Then we would configure a logging.cfg, which actually writes this log level from this qualname to a specific file. This would we the only output written to this very file.
See https://privacyidea.readthedocs.io/en/latest/installation/system/logging.html#advanced-logging

The config could look like this:
~~~~
[logger_logstash_audit]
handlers=logstash
qualname=privacyidea.lib.auditmodules.sqlaudit
level=DEBUG


[handler_logstash]
# Rollover the logfile at midnight
class=logging.handlers.RotatingFileHandler
backupCount=14
maxBytes=10000000
formatter=detail
level=DEBUG
args=('/var/log/privacyidea/logstash-audit.log',)
~~~~

**Comment by plettich** [comment]
> > Since i am reviewing #1537: we need to check if there is a readable audit-log in some cases.
> > 
> > * [ ]   [`auth_user_timelimit()`](https://github.com/privacyidea/privacyidea/blob/65b1a9247cef6c2dccb3dee6ea66ab2779f94593/privacyidea/lib/policydecorators.py#L335)
> 
> What do you mean by this?

There are some functions that read the audit log so if there is no readable audit log, we have to make sure that they still work.

**Comment by plettich** [comment]
> The log line could output the desired logging information.
> Then we would configure a logging.cfg, which actually writes this log level from this qualname to a specific file. This would we the only output written to this very file.

i like the idea (and it's simplicity) but it feels a little hacky to put that code in the `sqlaudit` module.

**Comment by cornelinux** [comment]
* In regards to hacky: You are totally right. This would be the very low hanging (hacky) fruit. It would be cooler have this in its own audit module. But as mentioned earlier, we then would have to improve the wrapper code, that can call several audit modules.

* in regards to readable: Basically you are right. But I have been down this road before, when we had a file audit module back in like 2011. I think not every audit module must be readable. As mentioned earlier: We could have a list of audit modules. This first in the list (SQL) is also responsible for reading. Other audit modules could only  write. It might make even a lot of sense to have a **drop-only** audit module.

**Comment by cornelinux** [comment]
Taking a look at the code like in ``before_after`` it is clear that a lot of the usages of the audit class actually expects one audit class.
I we would change ``lib/audit:getAudit`` to return a list of audit classes, then we would have to change a lot of occurrences in the code. So *only* providing a list of audit classes could get very messy with a lot of code changes all over the place.

So I would like to reconsider Friedrichs thought about a [container class](
https://github.com/privacyidea/privacyidea/issues/1072#issuecomment-389981437)

The container class would provide the very same interface of ``search``, ``log`` and ``finalize_log``.
The contained class would know which audit class operates the *search* and would distribute the write operations that happen in *log* and *finalize_log*.

There are different ways to configure such a container class - either implicit or explicit:

**Implicit**

Just having a list of audit classes would indicate, that we have a container class. The first *readable* audit class is the list would be responsible for all *search* operations while all other classes in the list would be used to be written to.

Finally, we could always use the container class, no matter if only one class or a list of class is specified. But in this case we would have an additional layer, even if we only had one class.

**explicit**

We would have to define, that we actually want to use a container class. This would be more flexible since anyone could write its own container class - thus it would be a *normal* audit class again.

~~~~
PI_AUDIT_MODULE = 'privacyidea.lib.auditmodules.containeraudit'
PI_AUDIT_CONTAINER_WRITE = ['privacyidea.lib.auditmodules.sqlaudit','privacyidea.lib.auditmodules.logger']
PI_AUDIT_CONTAINER_READ = 'privacyidea.lib.auditmodules.sqlaudit'
PI_AUDIT_SQL_....
~~~~
In the explicit scenario we would have to write two new audit modules, the *container* and the *file logger*.

I think I would prefer this approach.

**Comment by cornelinux** [comment]
> > > Since i am reviewing #1537: we need to check if there is a readable audit-log in some cases.
> > > 
> > > * [ ]    [`auth_user_timelimit()`](https://github.com/privacyidea/privacyidea/blob/65b1a9247cef6c2dccb3dee6ea66ab2779f94593/privacyidea/lib/policydecorators.py#L335)
> > 
> > 
> > What do you mean by this?
> 
> There are some functions that read the audit log so if there is no readable audit log, we have to make sure that they still work.

I think it is OK, that if there is no readable audit log, the admin decided to have some information not available. If the admin decides for some information to not taken into account, that these functions do not work. (It is enough, to make this clear, where necessary. But at the moment everyone has a readable audit log, so I would see this documentation rather low prio)

**Comment by cornelinux** [comment]
# Todo

* [ ] fix the signature of the audit base class (search: missing paramters, searchorder, page...)
* [ ] in container class: check if READ module is really readable. Otherwise write a log-warning

**Comment by cornelinux** [comment]
Currently the log line look like this:

{'success': True, 'serial': '**', 'user': '**', 'realm': '**', 'resolver': '', 'token_type': '', 'client': '::1', 'client_user_agent': 'chrome', 'privacyidea_server': 'localhost', 'action': 'GET /audit/', 'action_detail': '', 'info': '', 'administrator': 'super', 'policies': 'superuser,superuser', 'timestamp': datetime.datetime(2019, 11, 12, 14, 33, 21, 721556)}

The ``timestamp`` looks a bit unpleasant.
@plettich  I think we should change this to a UTC string representation. What do you think?
