### ISSUE TITLE
User detail information empty for secondary login names attributes

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1082]
Steps to reproduce:
* Use current privacyIDEA master (6f082de)
* Setup LDAP resolver with multiple login name attributes: ``sAMAccountName, surName``
* Authenticate using a secondary login name attribute, e.g. ``friedrich`` (which is the surname)
* Go to the audit log. There is a line corresponding to the authentication attempt with a ``user`` field showing ``friedrich``
* Clicking this link, we get to ``http://localhost:5000/#/user/details/dc/friedrich``

This URL does correctly display the user's token, but does not show any user information. This is because the user detail view does not work for secondary login name attributes. The user details can only be viewed at ``http://localhost:5000/#/user/details/dc/weber`` (which is the sAMAccountName).

**Comment by cornelinux** [comment]
The question is, if we want to allow to address users with different Loginname attributes. After all the "surName" is not the UID but "only" a login attribute?

We would have to adapt ``get_user_from_param`` and other functions, if there is not a unique identifier of the user anymore.

**Comment by fredreichbier** [comment]
I think you're right -- it's probably a better idea to identify users by their UID only in general, not by any of their login name attributes.
Adapting the audit module as you describe sounds like a good fix to me. But I'm not sure if that should be part of the 2.23 milestone?

**Comment by cornelinux** [comment]
I think we remove this from 2.23.
