### ISSUE TITLE
Authz Policy Based on arbitrary tokeninfo

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1102]
We could check regexp in tokeninfo.
This way increase the entanglement of policies and event handler.

**Comment by cornelinux** [comment]
This is already possible with 8.4.3

But we might want to enhance the logic:
Like if the value in the tokeninfo is bigger or smaller than a given value.

**Comment by fredreichbier** [comment]
Ah, we implemented a functionality to compare token info values in the token janitor:
https://github.com/privacyidea/privacyidea/blob/master/tools/privacyidea-token-janitor#L211

Maybe we can reuse some code or move this code to a library function.

**Comment by cornelinux** [comment]
Cool, similar to #1645

**Comment by cornelinux** [comment]
* [ ] We need to pass the token object or the token serial number to the policy handling in ``get_policies`` and ``get_action_values``.

* [ ] We need to add a database field or whatever for the tokeninfo. As the policy might match for several different tokeninfos at the same time, we need to be able to attach several t-infos to a policy. (Obviously we need a condition table).

**Comment by cornelinux** [comment]
I think this will probably blow the effort for the milestone.
We should keep this in the back of our heads that we want to do this while designing #1645 but we do not need to do this in this milestone at every cost!

**Comment by cornelinux** [comment]
This was already done in #1947
