### ISSUE TITLE
Usergroups

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1108]
Should we be able to define User Groups in privacyidea? 
These usergroups could be used in policies.

**Comment by cornelinux** [comment]
We could add to user groups:

* resolvers
* realms
* usernames 

The question is, if the groups should only be used for policies - then the *groups* would be something like *roles* or if the groups should also apply to authentication. (I prefer the first).

A user could be member of several groups.

**Comment by zerealfox** [comment]
I like the idea of groups in policies. I think it can really helps!

**Comment by adam820** [comment]
Ideally you could pull the groups from the realms (LDAP/AD groups); we're demoing privacyIDEA and the fact that you cannot use groups in the policies has effectively killed it, since we need to exempt an entire AD OU (~100 users) from needing tokens.

**Comment by cornelinux** [comment]
There would have been other ways to achieve this. You could have used a positive AD group to define the resolver, you could have used passthru policies...
privacyIDEA can be rather complex, since it does not have a list of well-expected features but a list of very flexible concepts, that can be used to cover most unexpected requirements.

**Comment by cornelinux** [comment]
Here is how you could exclude a group from a resolver:

* BaseDN: ou=frankfurt,dc=testfoo,dc=intranet
* Searchfilter: (!(memberOf=cn=lame users,cn=users,dc=testfoo,dc=intranet))(&(sAMAccountName=*)(objectClass=person))

This will find all users in the OU "frankfurt" but only those, who are not in the security group "lame users" ;-)
Note, that you need to specify the DN of the group.

However, your input is appreciated. 

* How would you be interested in groups
* What do you want to use groups for?

**Comment by adam820** [comment]
From a usability standpoint, writing LDAP filters isn't the most user-friendly. So, thinking about others in our IT team or even Helpdesk folks, there's not a friendly way for them to craft policies (this may actually not be a bad thing).

From looking at other solutions during our demo period, what they typically have is one resolver-per-realm that syncs users and groups. This then allows to set up policies or chains that only apply to, say "MYDOMAIN\IT Admins" or "MYDOMAIN\Shop Users", without having to exclusively filter those things in or out.

**Comment by cornelinux** [comment]
You are right. Policy are never created by helpdesk folks.
Policies are designed during a consulting phase, implemented by the super-token-administrator and then helpdesk users have the right to *use* privacyIDEA, but not change the settings ;-)

I do not know, which other solutions you are talking of. Of course privacyIDEA has another approach. Also privacyIDEA is not married to active directory. So we always find a way, that works in all scenarios.
This is why we did not start to sync AD-groups in the first place. I assume we will never do so.
After all, you can map your AD groups...
I think in that privacyIDEA is the more flexible solution. It might not always be the "better" solution - especially if you are in an all-M$-shop and only have limited requirements, then you might feel more comfortable with other software programs.

We try to continue our philosophy to not add a dedicated feature request like "authenticate users with emails" or "send users an email, if the administrator enrolls a token" or "sync AD groups".
You can do all this, but not with this very name on it. Because this would only work in one certain scenario. We strive to find more generic solutions. So we will *never* have a *sync AD groups* features. Because we are not talking of *AD*. We are talking of user sources. And AD is no other user source then OpenLDAP, a SQL table or a flat file.

So when we talk of groups we will come up with a generic approach that works in all scenarios.
(But as mentioned, to a certain extent we already have one! ;-)

**Comment by cornelinux** [comment]
@zerealfox The original idea of groups was to have groups managed within privacyIDEA!
How did you understand this?

**Comment by adam820** [comment]
@cornelinux Yes, I understand that, and as a fan of FOSS solutions it's much appreciated. I was just speaking to the point of other software we are currently demoing for our particular needs and how they accomplish this task; since they _do_ have this functionality, my expectations on how to achieve group-related scenarios were different from the software's reality. However, based on your examples I am now seeing similar results. Going with as generic an approach as possible to support the widest range of scenarios is probably the correct one, and I applaud your efforts in this regard. Thank you for your time and support!

**Comment by NuvandaPV** [comment]
This is already possible through policies based on user attributes. See: #1436
