### ISSUE TITLE
Flask-Script is deprecated

### ISSUE THREAD

**Issue by globin** [privacyidea/privacyidea#1121]
Per their Readme flask-script has been deprecated, its latest release also doesn't work with the flask > 1.0:
https://github.com/smurfix/flask-script/commit/f141a3382dd49f53e4e86f7fd0fbcc8b5c0447f4

**Comment by cornelinux** [comment]
Thanks a lot for the pointer!

**Comment by cornelinux** [comment]
Honestly I can not wrap my head around this new flask cli thingy. I tried to understand it for #1956, but failed ;-)

**Comment by plettich** [comment]
This is superseded by #2498
