### ISSUE TITLE
Obtain list of available privacyIDEA nodes in a redundant setup

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1126]
We have designed the task runner (#992) such that each periodic task holds a list of nodes on which the task should be run. This is important in a redundant setup because e.g. a token janitor job must be run on *one* of the nodes only.

Each privacyIDEA node knows its name from its pi.cfg, but there is currently no way to know all available nodes. However, this would be nice to have: Then, we could provide a list of nodes in the UI from the administrator could choose.

from #1116:
> I am not sure, if we should save the available nodes in the database - so that all PI nodes have the same node list.
> Or if a PI node should somehow "register" in such database table, so that the PI node can take the information
> * what node am I
> * what nodes are available
> from the database or from pi.cfg. Should a node be renamable?

**Comment by cornelinux** [comment]
Currently we have the ``PI_AUDIT_SERVERNAME`` which could overwrite the hostname in the audit log.

We could use this pi.cfg config variable or be more flexible and add a new one?

    PI_NODE = "node1"
    PI_NODES = ["node1", "node2", "node3"]

**Comment by fredreichbier** [comment]
I think having a config variable would be OK for now (though it's not so elegant).

Hmm, since the periodic tasks are unrelated to the audit log, I guess having a new ``PI_NODE`` variable would make sense? But wouldn't one usually want ``PI_AUDIT_SERVERNAME`` and ``PI_NODE`` to be the same value?

**Comment by cornelinux** [comment]
Yes, usually this probably would be the same value. Look I sent a PR.
