### ISSUE TITLE
privacyidea-pip-update fails if pip 10 is installed

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1128]
Steps to reproduce:

* have privacyIDEA in a virtualenv, with pip 10.0.1
* type ``privacyidea-pip-update``, answer question with ``y``
* error:
```
Traceback (most recent call last):
  File "/home/fred/venv/bin/privacyidea-pip-update", line 71, in <module>
    main()
  File "/home/fred/venv/bin/privacyidea-pip-update", line 64, in main
    update()
  File "/home/fred/venv/bin/privacyidea-pip-update", line 19, in update
    for dist in pip.get_installed_distributions():
AttributeError: 'module' object has no attribute 'get_installed_distributions'
```

Downgrading to pip 9 as described [here](https://github.com/Miserlou/Zappa/issues/1471) solves the issue.

**Comment by fredreichbier** [comment]
We should keep this in mind for our new release because a portion of pip installations won't be able to update using ``privacyidea-pip-update``:

privacyIDEA 2.22 was released on 27 March. On 14 April, pip 10.0.0 was released, which doesn't have the ``get_installed_distributions`` function anymore. So if someone ran ``privacyidea-pip-update`` after 14 April to update privacyIDEA, the locally installed ``pip`` got updated to 10.0.0. If the same user runs ``privacyidea-pip-update`` to update to privacyIDEA 2.23, the above error will occur.

The workaround is to use ``pip install==9.0.3 && privacyidea-pip-update``.

**Comment by plettich** [comment]
Since `pip >= 10.0.0` doesn't provide a module interface (anymore, see [here](https://github.com/pypa/pip/issues/5154#issuecomment-378197307)), maybe we could refrain from using `pip.get_installed_distributions()` and use the subprocess module instead to get the installed modules.
