### ISSUE TITLE
Seed in tokenwizard

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#1131]
We use privacyidea tokenwizard action in webui policy and this wizard doesn't show seed. We need this seed for some users which cannot install google auth on phones (cannot scan QR code). As i checked in token.enroll.html template are conditionals to disable functionality in tokenwizard, so i would suggest enable at least this functionality or have some flag to enable it.

**Comment by cornelinux** [comment]
This will be included in some enrollment enhancements. See the label "enrollment process".
If you want a wizard that even adapts more to your needs, privacyIDEA also allows for easily adding it in your own site:
https://www.privacyidea.org/create-user-portal/
