### ISSUE TITLE
Response when sending SMS fails

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#1136]
We use /validate/check API call and sometimes we receive response that The PIN was correct, but the SMS could not be sent, which comes from this part of code:

https://github.com/privacyidea/privacyidea/blob/5156a46e94b9b7c4a413719e7c887756a4ccf657/privacyidea/lib/tokens/smstoken.py#L306

This call returns 200OK status code, which is not correct and we cannot handle properly this error (except we can parse detail, but this is not correct way of detecting errors)

**Comment by cornelinux** [comment]
Do I understand correctly that you think there should be another HTTP response code?

**Comment by p53** [comment]
yup, correct

**Comment by p53** [comment]
ok, i think that for the time being it would suffice, taking into account that proper fix might be breaking change. If you could also queue it to some milestone to fix it in some breaking changes release. Thanks!

**Comment by cornelinux** [comment]
Hah, to me a "proper fix" sounds presumptuous or at least short sighted. Your scenario is not the only one on the world. This is still a feature request!

**Comment by p53** [comment]
sorry for the vocabulary, i did not mean anything bad with that, we need just way of systematically handling errors
