### ISSUE TITLE
Event handler to remove response parameters to allow enrolling softtokens without seeing the QR Code

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1138]
The helpdesk user or admin could be able to enroll a token for a user, without seeing the qrcode.

The qrcode could be sent to a user via an event handler.
Or the qrcode could be made available in the self service portal of the user, so that the user can "pick up" his token in the selfservice portal.

**Comment by cornelinux** [comment]
This is a similar problem like #1196 

There is some normal data in the response, but we need to remove this data from the response.
In this case it is the seed and the QR code, in the case of #1196 it is the resetted PIN.

We could use a POST handler, that removes arbitrary ``details`` or ``results`` from the response. The helpdesk user in this case also should not see the seed!

In regards to the user "picking up" the QR code, this might mean we need some internal notification. The QR code could be sent via the event handler to the internal notification system. See #614

**Comment by cornelinux** [comment]
This is a similar problem like the resetting of the PIN. #1196 
This could mean that the notification handler could modify an information from the response.
It would somehow redirect the information: Do not send it via response anymore, but send it to an email...

**Comment by fredreichbier** [comment]
The mangle pre-event handler from #1810 modifies the request before it is passed to the privacyIDEA API. This issue would, similarly, implement a post-event handler that modifies the response before it is passed to the webserver. Maybe this could even be the same event handler?

**Comment by cornelinux** [comment]
Such an Event-Handler would only allow the position ``[post]``.

It could modify, add or delete any existing entry in the JSON response.
We need to somehow specify the value in the JSON response. Maybe we simply do this by specifing it from the top like:

* result:value
* detail:message

Or we could specify a complete tree - which would only make sense in the case of ``delete``:

* detail

The different actions would require different attributes:

**delete**

Only requires the key to delete like ``detail`` or ``detail:message``.

**add**

Would require the key and the value:

* key: ``detail:message``
* value: "This is our little secret" (string)

If the key already exists, the existing key would be overwritten.

**modify**

*TBD*

**Comment by fredreichbier** [comment]
We could also check if it makes sense to use a pre-baked solution like [JSON Patch](http://jsonpatch.com/), which seems to have a Python binding.

**Comment by cornelinux** [comment]
Interesting, JSON Pointer (https://tools.ietf.org/html/rfc6901) and JSON Patch (https://tools.ietf.org/html/rfc6902) is specified in RFC. Thanks a lot for this hint! I think it makes sense to adhere to the pointer definition so the previsou example would be ``/detail`` and ``/detail/message``.
I think this is nice.

But I do not think that we should ask the user to really use a JSON patch to add a value. In roughly 99% this would be to overcomplicated for the user.

I would also like to keep it a bit similar to #1810. And in this case JSON patch does not work out.

**Comment by fredreichbier** [comment]
Yes, I guess using JSON Patch would be overkill. But using a notation similar to JSON Pointer, or even the "real" JSON pointer notation, sounds nice. :)

**Comment by cornelinux** [comment]
I also just checked: "pre" and "post" have no influence on the actions of an event handler. Thus we need to have an event handler, that mangels the request parameters (RequestMangler) and a handler that mangles the response (ResponseMangler).

**Comment by cornelinux** [comment]
There is a [jsonpointer module](https://github.com/stefankoegl/python-json-pointer) which could be used to modify the JSON response. But it has some drawbacks:

1. You can not set a key within an non-existing subpath. If you want to set /detail/message, /detail has to exist
2. You can not delete a pointer. You can only set it empty.
3. The implementation was not maintained since 2018.
I think we will do it on our own.
