### ISSUE TITLE
SQL pooling is broken in SQLAudit and SQLIdResolver 

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1140]
As it turns out, the SQL Audit and SQLIdResolver modules create a new SQLAlchemy ``QueuePool`` for each request which is not shared among requests. As a result, they do not benefit from pooling. This may result in too many connections being opened, as well as leftover connections that remain after a request until they are garbage-collected.

This can be checked using a custom ``privacyideaapp.wsgi``:
```python
import sys

from sqlalchemy import event
from sqlalchemy.pool import Pool

@event.listens_for(Pool, 'checkout')
def receive_checkout(dbapi_connection, connection_record, proxy):
    pool = connection_record._ConnectionRecord__pool
    print >>sys.stderr, 'Checkout from pool {!r}'.format(pool)

from privacyidea.app import create_app
# Now we can select the config file:
application = create_app(config_name="production", config_file="/etc/privacyidea/pi.cfg")
```

If we now restart apache and run three `/validate/check`s (against a LDAP resolver), we can see:
```shell
$ grep Checkout /var/log/apache2/error.log  | egrep -ho 'Pool object at [0-9a-fx]+' | uniq
Pool object at 0x7f447e8d7dd0
Pool object at 0x7f447b6707d0
Pool object at 0x7f447e8d7dd0
Pool object at 0x7f447b5e8810
Pool object at 0x7f447e8d7dd0
Pool object at 0x7f447b469d50
```

We can see that the pool at 0x7f447e8d7dd0 is the flask-sqlalchemy pool which is used for connections to the token database. However, an additional new pool is created for each request by the SQL Audit module, which is not used anymore afterwards.

**Comment by cornelinux** [comment]
I am not sure if we should mix this in, here.

As far as the pool is concerned to my understanding the pool is a part of the engine, which is created here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/auditmodules/sqlaudit.py#L96

So we probably should create a singleton, that is shared between the threads and simply contains this engine. This way we will use the same DB connections/pool.

**Comment by fredreichbier** [comment]
I agree that the pool (and thus, probably the engine) should be shared between threads, so that we actually benefit from the pooling feature. However, I think we should take special care when implementing this and follow the [SQLAlchemy guide on thread-local sessions](http://docs.sqlalchemy.org/en/latest/orm/contextual.html). In particular, I think we need to use ``scoped_session`` to ensure we don't run into problems with multiple threads using the same Session concurrently.

But yes, I guess the connection string thing is not directly related. I'll move it to a different issue.

**Comment by cornelinux** [comment]
Look at that. I tried a first idea of not creating new engines 6dc61d8. But still the Pools in the apache error logs "pile up".

**Comment by fredreichbier** [comment]
I've implemented a shared "engine registry" in https://github.com/privacyidea/privacyidea/compare/1140/pooling (with functions similarly to your idea, but has some additional locking). This engine registry is then used by SQLAudit and SQLIdResolver objects.

This is still missing the "session close hook" functionality for the SQLIdResolver we talked about. Consequently, connections aren't returned immediately to the pool. As the default pool size for SQLIdResolvers is only 5, this makes the pool run out of connections pretty quickly. :-)

**Comment by fredreichbier** [comment]
One can monitor the flask-sqlalchemy, audit and resolver pools quite nicely by adding the following to ``before_after.py``:
```python
@token_blueprint.before_app_request
def log_pools():
    from privacyidea.lib.pooling import get_registry
    from privacyidea.models import db
    engines = {"flask-sqlalchemy": db.engine}
    if hasattr(get_registry(), '_engines'):
        engines.update(get_registry()._engines)
    log.info("We have {} engines".format(len(engines)))
    for name, engine in engines.iteritems():
        log.info("engine {}: {}".format(name, engine.pool.status()))
```

**Comment by cornelinux** [comment]
Should we add this to add this in the code - and comment out the decorator, so that we could "switch" on the monitoring in case of support problems?

Should we add this anyways and add a config parameter in pi.cfg?
