### ISSUE TITLE
Optimize Config notes during enrollment

### ISSUE THREAD

**Issue by MaxDiOrio** [privacyidea/privacyidea#1141]
2.22.22

When users go to enroll a new token, they see the following message for email and sms token types.  This should be an admin only message, and I feel shouldn't even show up when they actually have been configured properly.
> For Email tokens to work properly you need to set the Email Token Config!
> For SMS tokens to work properly you need to set the SMS Token Config!

I'd also like the ability to turn off the checkbox below that message:
> Read email address dynamically from user source on each request.
> Read number dynamically from user source on each request.

And for SMS, it would be nice to have the ability to specify a format for the phone number.  For example, Twilio highly recommends using the E.164 format for phone numbers.

**Comment by cornelinux** [comment]
What do you mean with choosing a phone number format? privacyIDEA does not have any logic for formats.
privacyIDEA reads the phone number from the user store. So I do not see that and how we should convert badly managed phone numbers in the user store. This will probably end up nasty.

+1 on the config note.

**Comment by cornelinux** [comment]
If you want to submit a PR.

The config hint is here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.sms.html#L7

You could either check for a configured SMS config or if the user is an admin.
Example for checking that the logged in user is an admin:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.html#L27

**Comment by MaxDiOrio** [comment]
It doesn't have to use the config store.  You can randomly enter a phone number.  In our case, we use Active Directory.  We are offering using the ability to use their cell phone, personal or corporate to receive OTP's via SMS.  

We do not want to maintain personal cell phone numbers in active directory as that information becomes freely available to anyone that can query LDAP.  (Yes I know we can restrict reading fields)

This means that users need to enter their own phone number.  We have our documentation specify what the format should be, but unless they're looking at the How-To document we created, there's no way to specify what format it should be entered in.  We can have users entering +11234567890 and 1234567890 or 567890 or 01144123456789.   It would be nice to have checking to conform to the International standard in cases like this.

**Comment by MaxDiOrio** [comment]
I would submit a PR, but I'm not much of a coder, but one heck of a Sys Admin.  :)

**Comment by plettich** [comment]
Displaying the configure settings is disabled in #1791
