### ISSUE TITLE
Allow token PIN in the token wizard

### ISSUE THREAD

**Issue by TheReal1604** [privacyidea/privacyidea#1144]
# What did you try to do?

The user should be guided to craft his first TOTP token easily - the token wizard is the perfect tool for that.

We set a default 4 digit pin as a requirement - unfortunately the field is not shown in the tokenwizard and the wizard doesnt let the user enroll his first token, in cause of the missing pin.

# What outcome did you expect?

The tokenwizard should display the pin field if we enroll the first token and set the "pin" as required by enrollment.

# What outcome did you experience?

The pin field is missing on the tokenwizard. First-Time Users cant enroll their token via the wizard.

# Configuration

* privacyIDEA Version: 2.22.1-1xenial

* Installation method: ubuntu packages - privacyidea ppa

## more details: 

* OS: ubuntu server 16.04.05 lts

* Webserver: Apache2

* Tokendatabase: MySQL

# Screenshot:

![image](https://user-images.githubusercontent.com/5877910/43448955-84306e04-94af-11e8-89b1-80875bd7b8c1.png)

**Comment by cornelinux** [comment]
The tokenwizard was implemented for the most easy way to enroll a token (without a PIN) but e.g. in use with the pin policy ``otppin=userstore``.
The goal was to give absolutely no choice to the user.

So currently the wizard works as expected.
We will how we can find a sensible way to allow adding the PIN to the wizard.

However, if you want to define your own "workflow", you can very well create your on local enrollment page. See
https://www.privacyidea.org/create-user-portal/

**Comment by TheReal1604** [comment]
@cornelinux thanks for the explanation and suggestions. :+1: We take this into consideration.

**Comment by cornelinux** [comment]
I think we can agree to the logic, that we can display the PIN field in the wizard, if the following policies are set:

* scope=user
* action=["enrollpin", "otp_pin_min_length"]

I assume, that you also have these things set?
In this case it is obvious, that the user is supposed to use a minimal PIN witht he token.
