### ISSUE TITLE
Unable to use Authy to generate TOTP tokens

### ISSUE THREAD

**Issue by MaxDiOrio** [privacyidea/privacyidea#1156]
Set up a new token for my account and added it to the Authy app using the QR code.  Attempted to log in with the token and it fails.  Audit log shows "wrong otp value"

I scanned the exact same QR Code into freeOTP and it works perfectly.

**Comment by MaxDiOrio** [comment]
Nevermind - Authy is unable to use a 60 second interval token.  Changed it to 30 and it's all good.

**Comment by cornelinux** [comment]
Hi @MaxDiOrio, if you want to use a real cool app, try the privacyIDEA Authenticator. ;-)
It can do 30s and 60s, SHA1-SHA512, and even secure 2step enrollment.
https://play.google.com/store/apps/details?id=it.netknights.piauthenticator
Currently it is only available for Android. We hope to have it for iOS by the end of the year.

**Comment by B3DTech** [comment]
Thanks, I'll check it out. Our director wanted to use Authy so that everything gets backed up since he reloads his phone often and has about a dozen otp's, including some that require human interaction when lost.

**Comment by cornelinux** [comment]
@B3DTech Obviously your director does not understand the concept of 2FA! (*reload*)

(*"Oh I lost my password. Who cares. It is a good password - I will continue using it anyways!"*)

**Comment by cornelinux** [comment]
I wouldn't recommend smartphones for nuclear codes! ;-)

OK, I understand your case. Maybe we will do something about this in several month.
We first need to implement our iOS App version and then we will figure out some more great features besides the 2step enrollment for the apps to be integrated with the privacyIDEA server.

**Comment by cornelinux** [comment]
@MaxDiOrio see #1157 - and if you want to contribute some ideas.
