### ISSUE TITLE
Allow setting phonenumber format

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1158]
See #1141 

During enrollment (especially self enrollment of the user), the format of the entered phone number should be restricted, to avoid the user having enter invalid phone numbers.

The phone number should be entered in E.123 international	 (aka DIN 5008 interenation) 

~~~~
   + <countrycode> <area code - without leading zero> <local number>
~~~~

**Comment by plettich** [comment]
Using multiple issues in a `Fixes `-line does not seem to close all issues...
