### ISSUE TITLE
Naming in Periodic Task detail

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1176]
I assume, that "Last Definition Update" actually means, "the last time, this task was run"?
Or is it really the update of the definition?

> #: privacyidea/static/components/config/views/config.periodictasks.details.html:96
> msgid "Last Definition Update"
> msgstr "Letzte Aktualisierung der Definition"

**Comment by cornelinux** [comment]
OK!
We also have:

> #: privacyidea/static/components/config/views/config.periodictasks.details.html:81
> msgid "Recorded Last Runs"
> msgstr "Letzte Ausführung"

But why did we save the "Last Definition Update"? To be able to compare with the last run?

**Comment by fredreichbier** [comment]
This is actually the last update of the definition of the periodic task. We need it as a reference point to calculate the first time to run the task on a node.
e.g. we create the task on Wednesday and define "run on Saturday". Then, privacyidea-cron should not run the task on the next invocation, but wait until Saturday.

**Comment by fredreichbier** [comment]
But thinking about it, I guess we don't necessarily have to display it in the WebUI.

**Comment by cornelinux** [comment]
It is fine. I think we can leave it there as information.
