### ISSUE TITLE
Improve error handling of privacyidea-cron

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1179]
See #992 

Assume a periodic task fails for some reason. The current behavior is that for failing jobs, privacyidea-cron does not write the current timestamp to the ``periodictasklastrun`` table, which causes privacyidea-cron to retry running the task the next time it is invoked, typically 5 minutes later.

It is questionable if this is the behavior we want. In general, retrying is probably fine, but there should be an upper limit on the number of tries.

**Comment by cornelinux** [comment]
The cron runner is located here: https://github.com/privacyidea/privacyidea/blob/master/tools/privacyidea-cron

**Comment by cornelinux** [comment]
We could enhance the table of the task definitipn:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L2714
with an attribute like ``retry_if_failed``, which would be the **default** setting (current behaviour!)

THis needs to configurable in the UI!

The ``privacyidea-cron`` the could check this at this location in the else-branch: https://github.com/privacyidea/privacyidea/blob/master/tools/privacyidea-cron#L95

If retry_inf_failed is false, we simply need to do `` set_periodic_task_last_run``.

**Comment by cornelinux** [comment]
Closed by PR #2730
