### ISSUE TITLE
Write documentation on SimpleStats and EventCounter taskmodules

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1183]
#1182 adds a template for documentation on the SimpleStats and EventCounter taskmodules -- if you want, feel free to add some :-)

**Comment by cornelinux** [comment]
Will do for EventCounter

**Comment by plettich** [comment]
And i am for SimpleStats

**Comment by cornelinux** [comment]
Closes with #1184 and #1186
