### ISSUE TITLE
Allow helpdesk to reset token pin

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1196]
We should allow the helpdesk to reset the PIN of a token, without having to manually read the PIN to the user.

The user calls the helpdesk and asks to reset the PIN.
The helpdesk would reset the PIN, but the helpdesk would not see the PIN and the helpdesk would not read the PIN to the user.

The PIN could be sent to the user's email address.

This could be accomplished using the NotificationHandler or a PINHandlingModule.
We also would need a API call like ``token/resetpin``.

> Currently the helpdesk would enroll a registration token for the user, the user would use this registration token to login once and then the user would have to reset the PIN himself.

**Comment by cornelinux** [comment]
If the NotificationHandler module would be used to send the PIN to the user, then the PIN has to be in the response of the resetpin API request. Then the NotificationHandler can read it and send it to the user.

The problem here is, that currently the NotificationHandler does not change the response. I.e. the helpdesk user could actually see the randomly reset PIN!

Should we enhance the NotificationHandler to be able to alter the response, removing the PIN info?

**Comment by fredreichbier** [comment]
We could extend the ``/token/setpin`` endpoint such that it allows to generate a random pin. One could then use a mangle post-event handler (#1138) to remove the generated PIN from the response.

**Comment by cornelinux** [comment]
I think we should add a new endpoint, since event handler will be more easy to connect to another endpoint like ``/token/setrandompin``.

~~~~json
POST /token/setrandompin

serial=tokenseiral
~~~~
The length of the PIN should be determined by policies.

The response should contain the PIN. The PIN can either be displayed in the UI or could be used by the even handler.

~~~~json
{"detail": {
                "pin": "2890dhlkjh2098"
              }
}
~~~~
