### ISSUE TITLE
passOnNoUser stop to work after upgrade from "2.22.1" to "2.23"

### ISSUE THREAD

**Issue by simvirus** [privacyidea/privacyidea#1206]
I've two Realm:    **a**    and   **b**

**Policies (in this order)**: 

a_authentication | authentication | {   "passthru": "userstore",   "reset_all_user_tokens": true,   "otppin": "tokenpin" } | [   "a" ] | [] | [] | []

b_authentication | authentication | {   "reset_all_user_tokens": true,   "passOnNoUser": true,   "passOnNoToken": true,   "otppin": "none" } | [   "b" ] | [] | [] | []

**Note**: 

Other options as "passOnNoToken" work correctly

**Connection:**
https://192.168.x.x/validate/check?user=xxxx&pass=xxxx&realm=b

**Results**:

detail
message	"The user does not exist, but is accepted due to policy 'b_authentication'."
threadid	140712283485952
versionnumber	"2.22.1"
version	"privacyIDEA 2.22.1"
result	
status	true
value	true
time	1535623419.165142
id	1

detail	null
version	"privacyIDEA 2.23"
result	
status	false
error	
message	"ERR904: The user can not be found in any resolver in this realm!"
code	904
time	1535623524.065644
id	1

Regards

**Comment by cornelinux** [comment]
I created the following unittest, that should simulate your problem:

~~~~python

class AA_Policy_Validate(MyTestCase):
    """
    test the api.validate endpoints
    """

    def test_00_create_realms(self):
        self.setUp_user_realms()
        self.setUp_user_realm2()

    def test_01_passOnNoUser(self):
        set_policy("auth_1", scope=SCOPE.AUTH, realm=self.realm1,
                   action={ACTION.PASSTHRU: "userstore",
                           ACTION.RESETALLTOKENS: True,
                           ACTION.OTPPIN: "tokenpin"}
                   )
        set_policy("auth_2", scope=SCOPE.AUTH, realm=self.realm2,
                   action={ACTION.PASSNOUSER: True,
                           ACTION.PASSNOTOKEN: True,
                           ACTION.RESETALLTOKENS: True,
                           ACTION.OTPPIN: "none"}
                   )
        with self.app.test_request_context('/validate/check',
                                           method='POST',
                                           data={"user": "UNKNOWN_USER_WHICH_WE_WILL_NEVER_CREATE",
                                                 "pass": "PIN",
                                                 "realm": self.realm2}):
            res = self.app.full_dispatch_request()
            self.assertEqual(res.status_code, 200)
            resp = json.loads(res.data)
            self.assertTrue(resp.get("result").get("value"))
            self.assertEqual(resp.get("detail").get("message"),
                             "user does not exist, accepted due to 'auth_2'")

        delete_policy("auth_1")
        delete_policy("auth_2")
~~~~

But it runs as expected. I can not reproduce your problem with your data.
So there is something missing.

What is your default realm?
Can you provide the debug privacyidea.log? (Or take a look at it and provide the corresponding lines)

Can you provide some more information about the realms? Are all users exclusive?

**Comment by simvirus** [comment]
I will send you the log by email.
The "default" realm is "a" (and not this "b" used in this case)

**Comment by cornelinux** [comment]
It looks like it is due to a event handler you specified!

The event handler conditions determine the tokenowner - otherwise in your case the notification email could not be sent.
It bails out here:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/eventhandler/base.py#L302

This would at least solve this issue:

~~~~python
        # conditions can be corresponding to the property conditions
        conditions = e_handler_def.get("conditions")
        content = self._get_response_content(response)
        try:
            user = self._get_tokenowner(request)
        except UserError:
            # There is an error with the user - maybe the user does not exist and we came here
            # due to PassOnNoUser.
            user = User()
~~~~

**Comment by simvirus** [comment]
Tested this:

        # conditions can be corresponding to the property conditions
        conditions = e_handler_def.get("conditions")
        content = self._get_response_content(response)
        try:
            user = self._get_tokenowner(request)
        except UserError:
            # There is an error with the user - maybe the user does not exist and we came here
            # due to PassOnNoUser.
            user = User()

It work correctly but the detail message is:

  **"user does not exist, accepted due to 'b_authentication'"**

instead of:

  **"The user does not exist, but is accepted due to policy 'b_authentication'."**

I just wanted to report it.

Regards
