### ISSUE TITLE
Clicking on List Challenges can eat up CPU

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1225]
When clicking on "List Challenges" in the UI, the request 
GET /token/challenges is issued.
See: 
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/token.py#L317 with ``serial=**`` and an **empty realm**!
However, the prepolicy ``check_base_action`` is called. And within there ``get_realms_of_tokens``.

``get_realms_of_tokens`` leads to problems, if the serial number is a "**".
https://github.com/privacyidea/privacyidea/blob/aded3ad61a281412f761023430219f59debb4c96/privacyidea/lib/token.py#L526

# TODO

We should use some simliar failsafe like this:
https://github.com/privacyidea/privacyidea/blob/aded3ad61a281412f761023430219f59debb4c96/privacyidea/lib/token.py#L457

**Comment by cornelinux** [comment]
There seems to be a generic problem with ``get_tokens``.
In most cases it should only return one token or a few tokens. 
So we might need to redesign this, to get rid of this problem at the root.

**Comment by cornelinux** [comment]
So to make it absolutely clear you are dropping the parameter ``serial`` and add ``serial_exact`` and ``serial_wildcard``.

Sounds intersting to me.

**Comment by fredreichbier** [comment]
In a way -- in the internal function ``_create_token_query``, the parameter ``serial`` is indeed dropped and replaced by ``serial_exact`` and ``serial_wildcard``.

In ``get_tokens``, the parameter ``serial`` is kept (but its meaning is changed), and a parameter ``serial_wildcard`` is added.

**Comment by fredreichbier** [comment]
There are some cases in which I'm not sure if they should match exactly or with a wildcard. We should check them:

 https://github.com/privacyidea/privacyidea/blob/a83394b14f400a4637b81e0145a95d1788d64b98/privacyidea/lib/token.py#L1498
I would say that matching exactly makes the most sense, but the code explicitly loops through all results?

**Comment by cornelinux** [comment]
The library level in fact would allow to set things for more than one token. But actually this was never user on purpose in the API!

So running exact will usually not change anything!

**Comment by fredreichbier** [comment]
Hmm, with the commits in the get_tokens branch, we effectively make it impossible for the library level to set things for more than one token at once, because all ``get_tokens(serial=...)`` calls on the library level  now match the serial number exactly -- do you think this is OK?

**Comment by cornelinux** [comment]
I do not know. THe alternative would be, to do a decorator on the API level. But then we might miss some occurrences. Since sometimes get_tokens is called implicitly. In a decorator. Or an event handler...
We could even make this more clear and rename the function to "get_token" (without an s) ;-)

**Comment by cornelinux** [comment]
Did you use this API call? Not me ;-)

**Comment by cornelinux** [comment]
This was fixed with the get_tokens serials.
