### ISSUE TITLE
Feature Request: Add option to add {googleurl_img} as an email attachement

### ISSUE THREAD

**Issue by speedy01** [privacyidea/privacyidea#1226]
Outlook does not support inline images encoded in base64. This is the current method used for QR code in email  {googleurl_img} and usernotifcation.  Please consider adding the option to include the QR image as an attachment.  Another option may be to use the CID or link to the img (if linking, then img/link should expire)

quick link that goes over CID tags
https://sendgrid.com/blog/embedding-images-emails-facts/

**Comment by cornelinux** [comment]
We would have to add another parameter like ``attachments`` (being a list) to this function 
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/smtpserver.py#L130

We would need an email config in the notification handler, to define if images should be sent inline or as attachment. https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/eventhandler/usernotification.py#L113

Here (https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/eventhandler/usernotification.py#L281) we would need to read this config and call ``send_email_identifier`` (https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/eventhandler/usernotification.py#L334) accordingly.

**Comment by cornelinux** [comment]
Resources:
https://docs.python.org/2/library/email.mime.html
https://stackoverflow.com/questions/3362600/how-to-send-email-attachments

**Comment by cornelinux** [comment]
Here is the explanation how this can be done for outlook.
https://community.privacyidea.org/t/qr-code-via-sms-or-email/793/9

**Comment by plettich** [comment]
It seems, google does not allow inline data URLs in gmail: https://stackoverflow.com/a/42014708/7036742
Adding the QR-Code as an attachment solves this.

**Comment by cornelinux** [comment]
I am looking forward to your pull request ;-)

**Comment by plettich** [comment]
Documentation is done, so i'll close this.
