### ISSUE TITLE
Feature request: allow image in the otpauth url

### ISSUE THREAD

**Issue by stojmir** [privacyidea/privacyidea#1228]
Some 2FA mobile apps such as FreeOTP (https://freeotp.github.io) support reading an optional image URL from the oathurl and then displaying it next to the software token. It would be nice if PrivacyIDEA could provide a way for easily configuring an image that will be included in the oath URL.

Here is an example oath URL that includes an image:
otpauth://hotp/FreeOTP:Fr?secret=fewx46epiyeqlfapjwlleryqi6bdxj36bhlelhjgk6r725ps7qsqbgon&algorithm=SHA1&digits=6&period=30&counter=0&image=https%3A%2F%2Ffreeotp.github.io%2Fimg%2Ffreeotp.svg

**Comment by cornelinux** [comment]
OK, it is an ``image`` parameter. Does it have to be an SVG?

The downside of FreeOTP is, that it still does not support the 2step enrollment of privacyIDEA! ;-)

I think we can easily add this. 
See here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/policy.py#L1520

~~~~python
            ACTION.APPIMAGEURL: {
                'type': 'str',
                'desc': _("This is the URL to the token image for smartphone apps like FreeOTP."),
                'group': GROUP.TOKEN
            },
~~~~
