### ISSUE TITLE
Hide buttons instead of disabling them

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1233]
Open to discussion:

If a user or admin are not allowed to delete or revoke tokens per
policy, maybe we should not display the delete buttons at all. Currently
they are shown as disabled (light color buttons).

**Comment by plettich** [comment]
I think, hiding the buttons is a good idea. It reduces the information overload for users/admins and showing a disabled button does not provide any more information.
Showing disabled buttons may be useful if the user/admin is generally allowed to do this action but not in this special case (not token owner, ...).

**Comment by cornelinux** [comment]
This is an interesting point. And I think this was the reason to disable the buttons in the first place. 
We can not say, if the admin would be allowed e.g. to disable a token in other circumstances. Sometimes the admin would wonder, "where the heck can I disable the a token?".

As he acutally sees the disabled button, he knows, that he is not allowed to disable a token. If the button is hidden, he might think, he does not find the spot, where he can disable the token.

Maybe it would be wise to choose, if buttons should be disabled or hidden. There are good reasons to hide buttons and other good reasons to disable buttons.

**Comment by cornelinux** [comment]
The buttons in the UI are hidden this way:


    ng-disabled="!checkRight('revoke')"


We can add ``ng-show="false"``, to hide the button.
To get the False value, we can add a webui policy like "hide_instead_of_disable" (name to be improved! ;-) 

We either would enhance the function ``checkRight`` - but this is imho a bad idea, since the name implies another outcome - or we add a new function ``hideButton`` or we simply add


    ng-hide="!checkRight('revoke') && checkRight('hide_instead_of_disable')"
