### ISSUE TITLE
A helpdesk user should not be able to read configuration

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1237]
A helpdesk admin who has all resolver related actions disabled, should not see the configuration.

It seems like the helpdesk user is able to click the link "Edit realms" and then access the resolvers.

**Comment by cornelinux** [comment]
Checking for specific policies.

**Comment by quynh-axiadids** [comment]
@cornelinux We also notice that even though without any configuration privileges, users in admin realms can still access the configuration tab through links displayed in token details or user details for realms or resolvers, thus was able to still hit the configuration submenu and navigate around there.

We would like to create a ticket for this. If you would like I can move it to a different issue.

Thank you.

**Comment by cornelinux** [comment]
This might be not that important, if #1271 is fixed.

**Comment by cornelinux** [comment]
This is obsolete since we now have ``read``-policies for configuration.
