### ISSUE TITLE
max_active_token_per_user

### ISSUE THREAD

**Issue by hemantprasad** [privacyidea/privacyidea#1241]
# What did you try to do?
Assign only one (01) active token, while the user has multiple disabled tokens.

Please provide your top level intent!
privacyIDEA provides configuration option to set max_token_per_user, but doesn't allow to set only one (01) active token per user, while old tokens are disabled.

Please provide steps to reproduce!

# What outcome did you expect?

What do you think, how the system should have worked?
Admin can  set max_token_per_user, and while to avoid misuse if admin sets the max_token_per_user = 01, user can generate a token and uses it for a while. But in an event user loses the phone and wants helpdesk/admin to disable old token and wants to enroll a new token, privacyIDEA policy will restrict the user from enrolling the token due to token limit set in policy. Admin doesn't want to delete the disable token to keep the token history and audit log.

Hence there should be an option to set max_active_token_per_user, which means a user can have several disabled tokens and only 01 token can be active at a time. max_active_token_value should be less than max_token_per_user.

Another safety guard should be that once a new token is generated for the user, privacyIDEA must not allow activation of disabled tokens for the same user.

# What outcome did you experience?

What did acutally happen?
Once user's old token is disabled, and while token limit is set to 01 in config, user's can't register a new token.
# Configuration

* privacyIDEA Version:

* Installation method:
  (from source, github, virtualenv, ubuntu packages...)

## more details: 

* OS:

* Webserver:

* Tokendatabase: (like MySQL, PostgreSQL, ...)

# Log file

**Turn on debug level and take a look at the privacyidea.log!**
**If appropriate, attach the log file.**

**Comment by fredreichbier** [comment]
#1649 and #1651 add the ``max_active_token_per_user`` action. Note, however, that it is not properly enforced for administrators (yet), see #1652.
