### ISSUE TITLE
Rethink LDAP resolver caching for scenarios with many users

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1246]
The LDAP resolver implements a process-level caching of user information, which is a good idea to improve performance. However, there are some problems in setup with many users because even expired cache entries are kept in memory until the user authenticates again (and then, they are replaced with more information).
This can get problematic if there is a large number of distinct users, because the cache will then grow and consume a lot of memory. This effect is even bigger in multi-process environments, e.g. nginx+uwsgi.

There are multiple ways to fix this:
* Implement a config option that allows to reduce the cache, e.g., to a request-level cache. But this will negatively impact performance for users that authenticate very often (i.e. every X seconds where X < ``CACHE_TIMEOUT``)
* Revise the implementation such that it actually frees expired cache entries. But this can get complicated because we need to be careful with multi-threaded environments. We could, for example, implement the cache in a way that it only keeps the 100 most recent entries.

**Comment by cornelinux** [comment]
I would avoid a too complicated logic, since this can quickly lead to unexpected behaviours and errors.

I would think either being able to disable it (we also have the generic user cache in SQL) or only keeping a maximum number (like a FIFO). This number might be also configurable. (In this case, setting the number to 0 would acutally disable it)

**Comment by cornelinux** [comment]
Hm, actually we already have a cache_timeout of 120 seconds default.
I do not think that in a large user setup, tens of thousands of users will be read in 120 seconds.

Well, currently we do not delete the timeouted entries, we simply check if the requested value is new enough:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/LDAPIdResolver.py#L203

THis way all resolved users one day exist in the dictionary, even if 38.000 users entries are timed out.
Of course this results in a big cache. Maybe we should simply clean up expired entries!
