### ISSUE TITLE
Check: Can we lower key size?

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1252]
Check if we can lower the keysize here
https://github.com/privacyidea/privacyidea/blob/6b8833c75668827581df24cb3ee7d55b0df2dd99/privacyidea/models.py#L2659

to 255.
This seems to help avoid the 768error of mariadb.

**Comment by fredreichbier** [comment]
I don't recall a reason why I set this to 256 instead of 255. I think 255 should be fine.

We should then probably also change the length of ``node`` in PeriodicTaskLastRun from 256 to 255.

**Comment by fredreichbier** [comment]
Closing this because #1273 is closed as well.
