### ISSUE TITLE
User Agent as condition for event handlers

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1260]
It would be nice to have the user agent from a request in the event handler condition.

I think we do not have access to the header parameters in the event handler library. So maybe we can add the User-Agent from the http header to the ``options`` somehwere earlier in the request, to be able to access them in the event handler.

However, why especially only use the User-Agent? Why not add other headers? Or add a generic solution.

**Comment by cornelinux** [comment]
see #1425

**Comment by cornelinux** [comment]
We will do this in milestone 3.2 when we also do the user attributes in event handlers. #1436

**Comment by fredreichbier** [comment]
Let's add an event handler condition that allows to match one *arbitrary* HTTP request header.
Example:

``User-Agent=/.*Mozilla.*/``

**Comment by cornelinux** [comment]
Closes this due to duplicate.
