### ISSUE TITLE
Versioning in js and css

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1261]
Introduce version numbers for .js and .css files (/file.js?ver1.2.3) so they can be easily incremented after a modification or an update of PrivacyIDEA. This would cause the browser to reload those instead of
reading them from the local cache and will avoid potential issues on the client side.

**Comment by fredreichbier** [comment]
We could use [flask-versioned](https://pythonhosted.org/Flask-Versioned/) for that.
