### ISSUE TITLE
U2F configure

### ISSUE THREAD

**Issue by patricia93sousa** [privacyidea/privacyidea#1267]
I'm trying to configure a U2F with a yubikey. However, how can I define http://127.0.0.1:5000/ttype/u2f this? I'm putting this on the **appid**, to allow to  Enroll Token in a user. When I'm trying to input enroll a new token I get Bad U2F Request / undefined and I can't understand why. I'm lacking some other phase? Thank you.

**Comment by cornelinux** [comment]
U2F should require to use a real FQDN and usually https.
So using an IP address will not work.

**Comment by patricia93sousa** [comment]
Ok , I set a FQDN in the /etc/hosts. But how can I configure in privacyidea the https with self-signed certificates?
