### ISSUE TITLE
Specified key was too long on upgrade

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#1273]
I am upgrading from 2.22 to 2.23

we have mariadb 5.5

What did acutally happen?

```

File "/opt/app/privacyidea/venv/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1071, u'Specified key was too long; max key length is 767 bytes') [SQL: u'\nCREATE TABLE periodictasklastrun (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tperiodictask_id INTEGER, \n\tnode VARCHAR(256) NOT NULL, \n\ttimestamp DATETIME NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ptlrix_1 UNIQUE (periodictask_id, node), \n\tFOREIGN KEY(periodictask_id) REFERENCES periodictask (id)\n)ROW_FORMAT=DYNAMIC\n\n'] (Background on this error at: http://sqlalche.me/e/2j85)

```
# Configuration

* privacyIDEA Version: upgrading from 2.22 to 2.23

* Installation method: pip

see https://wildlyinaccurate.com/mysql-specified-key-was-too-long-max-key-length-is-767-bytes/ for explanation, it affects MYSQL <5.7.7

node column should be smaller

**Comment by cornelinux** [comment]
With newer mariadb versoins you need to set

    innodb_file_format=Barracuda
    innodb_large_prefix=on

in your global server config file.

**Comment by p53** [comment]
@cornelinux  This is quite unfortunate, i cannot force upgrade of mysql, it is galera cluster with many other DB's

**Comment by p53** [comment]
@cornelinux this is quite unfortunate, it would be maybe good to add it as warning to some installation docs to prepare for DB instance upgrade before PI upgrade

**Comment by cornelinux** [comment]
You can reduce the node length to 255.
Do this in the schema in models.py and in the database if necessary.

**Comment by fredreichbier** [comment]
So can we solve this by lowering the length of ``PeriodicTaskOption.key`` and ``PeriodicTaskLastRun.node``? We could even set them to a length smaller than 255.

**Comment by cornelinux** [comment]
@p53 can you please check if 255 works for you by adapting the migration script and the model to the node lenght of 255

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L2703
You might also need to decrease the key:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L2659

Also adapt the lenghts in this migration script:
https://github.com/privacyidea/privacyidea/blob/master/migrations/versions/2c9430cfc66b_.py

**Comment by p53** [comment]
@cornelinux hi, thanks, tested, upgrade successful!

**Comment by cornelinux** [comment]
@fredreichbier in which version should be put this?

**Comment by cornelinux** [comment]
I would recommend a migration script like:

~~~~python
try:
   # create table with short columns
except:
   # This will not work, if the table already exist

try:
   # update table to shorten the column
except:
   # This might fail, if the column is already short
~~~~

So providing two separate actions will cover all cases.
