### ISSUE TITLE
Improve HSM retry mechanism

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1278]
Apparently we have some issues in the HSM retry logic.

* It seems like some PKCS11 modules already perform network communication on module load. Thus, we need to move
https://github.com/privacyidea/privacyidea/blob/7a18294290e25aca98acf59c6e5064fa61c9d85f/privacyidea/lib/security/aeshsm.py#L105
to ``initialize_hsm``.
* The retry mechanism in ``encrypt`` and ``decrypt`` opens a new session and tries to encrypt/decrypt with the new session. However, we pass the key handles of the *old* session to the *new* session, which might cause problems. We should move
https://github.com/privacyidea/privacyidea/blob/7a18294290e25aca98acf59c6e5064fa61c9d85f/privacyidea/lib/security/aeshsm.py#L195
and
https://github.com/privacyidea/privacyidea/blob/7a18294290e25aca98acf59c6e5064fa61c9d85f/privacyidea/lib/security/aeshsm.py#L215 inside the ``try`` block.

**Comment by cornelinux** [comment]
This is an interesting read:
http://docs.oasis-open.org/pkcs11/pkcs11-ug/v2.40/cn01/pkcs11-ug-v2.40-cn01.html#_Toc399411381
