### ISSUE TITLE
Check consistency of HSM configuration

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1279]
Check the consistency of the HSM configuration variables. Apparently we sometimes have 
```
PI_HSM_SLOT = 
PI_HSM_PASSWORD =
```
and sometimes
```
PI_HSM_MODULE_SLOT =
PI_HSM_MODULE_PASSWORD = 
```

**Comment by cornelinux** [comment]
The privacyIDEA server code (aeshsm.py) uses PI_HSM_MODULE_SLOT and PI_HSM_MODULE_PASSWORD.

**Comment by cornelinux** [comment]
pi-manage uses the very same config of PI_HSM_MODULE_SLOT and PI_HSM_MODULE_PASSWORD here: https://github.com/privacyidea/privacyidea/blob/master/pi-manage#L129

So obviously some of my old cofiguration was wrong, which contained PI_HSM_SLOT and got me confused.
