### ISSUE TITLE
Statistics modules should write to time series DB

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1289]
Statistics data are currently written to the database table ``monitoringstats``. This table can get filled up quite quickly.

1. We need a way to rotate this data

2. We should allow stats modules to write to a separated time series database, that can handle this kind of data in a better way.

**Comment by plettich** [comment]
BTW: the tests for `lib/stats.py` didn't really work since no image was generated.

**Comment by cornelinux** [comment]
@fredreichbier To be able to write to different time series database we need the app-configuration in some task modules like in the ``do`` e.g. of the event counter task module:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/task/eventcounter.py#L73

First I thought of passing the app-config in the do-method, but then I thought it might be nicer to pass the app-config in the constructor of the class.

But now I end up with problems passing a parameter to a constructer of the task modules in your nice lamda voodoo of ``TASK_MODULES``...

e.g. here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/periodictask.py#L59

or here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/periodictask.py#L47

It might be also only a problem due to the Mock in the tests. Let's talk.
