### ISSUE TITLE
Devices as Token Container (formerly Nested Tokenclasses)

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1291]
### WebUI
- [x] Container creation page
  - [x] `assignUser` directive asks for PIN, make that configurable?
- [x] Add the owned containers to the user view
- [x] Extend `GET /token` to return the container the token is in and display that info in a new column in the token list
- [x] Create a directive that lets the user select or create a container. Usually, you dont want to create a container and then create a token, but rather create the container on the fly if it does not exist yet. This directive can then be used for:
  - [x] Token enrollment
  - [x] Token info
  - [x] User info page: put all token of user in container (or make a selection)
- [x] Create a container info page, similar to token info
- [x] Create a list view of all containers, similar to the token list. Ideally, the contained token are also directly visible and linked (e.g. by serial)
- [x] Make `GET /container` use pagesize like `GET /token`
- [x] Move the container sections to a different submenu
- [ ] Idea: Icons for each type in the container list behind the serial to see the type directly
- [x] Add `checkRights` to check for authorization policy on container actions

## Model
- [x] Add `last_seen` and/or `last_updated` to container database model. Set the value(s) on the corresponding operations, might require some form of the container saying "im still the same", to just the update the `last_seen`
- [x] Add `container_info` to containers, like `token_info`
- [x] Add a realm to the container, similar to token realm

## API
- [x] Add audit entries
- [x] Check that the authorization works similar to token

## Policies for Containers
- [x] Admin policies

## Everything else

- [x] Documentation
- [x] Tests

# Older content (2023-2024)
## Discussion

We will focus on the smartphone app and yubikey for the first iteration as those are the main use-cases currently.
It should be possible to fit different other types like biometrics (Hand=multiple fingers) in these ideas.

## Containers and Templates
There will be a base class and multiple concrete devices like smartphone and yubikey.
* The base class is a container that is pretty much only used for grouping the token (see operations section)
* The device will specify the **supported token types**. 
* MAYBE specify the capabilities/options that can be modified by a template explicitly, e.g. the derived class returns the template options + some base template options that every device has (e.g. naming)
* The device can have 0 or more owners
* Some devices are capable of using a backchannel (smartphone) while others can not act on their own (yubikey)
    - In case of devices that do not act on their own, there is/will be a program provided by us to execute the operations on the device. It can also check if changes have been made to the device by another program and report the changes.
    - **A backchannel is a must**

Admins should be able to configure *Templates* to modify/control the behavior of devices and the operations done with them. Examples of template options are:
* Which token should be on the device?
* What is the user allowed to do with the token on the device? (Nothing/delete/add...)
     - In case of add: possibly sync token added by the user with privacyidea. This can be interesting for external services that are still used by the organization e.g. UPS, Amazon
* Are token of different users allowed?
* PINs and PIN policies
* Information requested from the device like Yubikey serial, Phone name etc. to make the management easier.
* Naming of the token enrolled

**It should be possible to apply different templates to the same device type**

## Operations on Devices
There are base operations, which are mostly management things:
* Add existing token to device
* Remove
* Remove the whole device (keep/remove children)
* Reassign/remove owner(s)

More advanced operations that might be different for the token and device types involved:
* Init device with new token according to template
* Update of templates applied on the device (template=privacyidea tells the device how it should be)
* Backchannel operations like token removed/added etc. (backchannel=the device reports that something has changed that was not initiated by privacyidea)

## API Perspective
New API endpoints need to be introduced to meet the needs explained in the previous sections. IDEAS:
* /device/init:
    - Establish trust, get the template
    - Does privacyidea start the /token/init here or does the device do it based on the template?
* /device/status
* 
* /device/update

# Oldest content (2023 and earlier)
We want to support smartcards one day.

The interesting thing about smartcards is, that **one** smartcard can contain **many** authentication objects. Authentication objects being x509 certificates, PGP keys or "OTP-Tokens" (e.g. a Yubikey alone can hold x509 certificates, PGP Keys and two OTP tokens).
But the yubikey is one hardware device, one logical unit or container, that is in the possession of one user.

This is why we need to group token by the container that contains them.

# Top level reasons for devices

These reasons or toplevel ideas should also be written to the documentation.

TODO: Add other reasons.

* [ ] A user does not know, what is contained on his e.g. Yubikey. He will call the helpdesk and tell them, he lost his yubikey. He will not tell them, he lost his HOTP-Token, his PGP key, his Webauthn...
* [ ] A user maybe does not know, which tokens are contained on his smartphone. Already today we have users with e.g. TOTP and PUSH. He will call the helpdesk (not with his smartphone) and tell them, he lost his smartphone. The helpdesk will block the smartphone and thus block all contained tokens.
* [ ] Reassign the complete container (like a physical yubikey) to another user.
* [ ] Make some processes for the admin more easy like enrolling via templates (see below)

# Scenarios

TODO: List scenarios and check which have been covered by the implementation

* [ ] A Yubikey can contain certificates
* [ ] A Yubikey can contain an HOTP token or with the YK authenticator several xOTP tokens.
* [ ] A Smartcard can contain certificates
* [ ] An Administrator could for reasons manually put tokens in an arbitrary container?
* [ ] A smartphone could contain an HOTP, TOTP, Push-Token
* [ ] A mobile phone/Smartphone could "contain" an SMS token
* [ ] A Nitrokey could contain several HOTP and TOTP tokens, a certifiacate...
* [ ]  A yubikey or whatever could contain WebAuthn-Token
* [ ] One hand can contain 5 fingerprints
* [ ] One head contains 2 eyes
* [ ] A simple physical **keyring** could contain several HW tokens. All other containers are technically defined and can not easily be altered by a user: A token can not be exported from one phone. A private key can not be moved from a smartcard. But a HW token can be remove from a keyring and passed to another one.

So *containers* can be:

* Yubikey
* Smartcard
* Keyring
* smartphone
* Nitrokey
* A Hand

## Open questions

* [x] One container could have several tokens, that are assigned to different users. An Administrator could have token for his admin account and his user account in the app.
* [x] Should a container be assigned to a user?
* [ ] Do we need nested containers?  **not immediately, but it should be possible to extend the first implementation with this**
   * [ ] a physical keyring can contain several yubikeys, which can contain several tokens
   * [ ] A Smartphone could contain different Apps (privacyIDEA Authenticator, Custom Authenticator) of which each could contain the final auth tokens.

A smartphone could be a *contained* tokenclass, but it contains several *privacyIDEA-Authenticators*. This is helpful, if a users looses the *container* the helpdesk automatically disables all contained tokens.

# Naming

Give some thoughts on the naming.
But "container" sounds too technical. What is a container, is it a "device"?

Today I very much think, that this is a *device*. (2024-2-5)

# DB Schema

A table like ``containercontent`` with the colums:

* ``container``
* ``content``

both containing a a token_id.
Do we need a primary key? Do we need constraints? The constraint would be, that the combination of both columns needs to be unique.

*We should not be sure that a content can only be contained in on container. This is the same simple (wrong) assumption like that a token can only be assigned to one user.*

*So we in fact should allow by design that the same content (like a PGP key or an SSH key) could be contained in several containes (like a smartcard or a computer).*

## A simpler database approach

Assuming that a ``content`` can only be contained in one ``container``, then we could add a *parent* or *container* column to the token database. This way we can also represent a tree.
A container could find all its content by running a sql where statement for the tokens with his id in the *container* column. A token (*content*) will know his parent immediately.

# First Container

The first container could be a yubikey. If we enroll both slots, currently we create two tokenobjects with a suffix ``_1`` and ``_2``.
Actually such a smartcard container could have attributes like ``vendor``, ``serialnumber``, maybe also a list, which tokenclasses can be contained! What is the allowed content.

**Another good first token, also to test the concept and have fun developing it, could be the privacyIDEA Authenticator App.**

First we should prepare the unterlying logic, then we can handle the UI representation.

# Action with a token container

Which actions can be done explicitly on such a nested token or container?

* **token-init**: With a privacyIDEA Authenticator we could intialize a container and thus automatically enroll a PUSH token and an HOTP token, depending on what is configured. The admin can define a **container template**.
* **delete token/disable**: delete or disable all tokens in the container.
* ...other actions?

**Comment by cornelinux** [comment]
What would be a container?
* smartcard
* yubikey
* nitrokey
* mooltipass
what attributes do they have? Do they really need to be a tokenclass again or should they be another entity?

**Comment by cornelinux** [comment]
We should not be sure that a content can only be contained in on container. This is the same simple (wrong) assumption like that a token can only be assigned to one user.

So we in fact should allow by design that the same content (like a PGP key or an SSH key) could be contained in several containes (like a smartcard or a computer).

**Comment by cornelinux** [comment]
Is  a contained a tokenclass or another entity?

* A container is **assigned to a user**
* A container could have a **PIN** or password
* A container can be **locked or disabled**?

But a container usually 
* has **no otpkey**

There are  a lot of same features, but can a tokenobject be a content and a container at the same time?
Should we add a new container class?

**Comment by cornelinux** [comment]
Containers could be:

* SmartcardClass
   * YubikeyClass(ContainerClass)
* SmartphoneClass

But "container" sounds too technical. What is a container, is it a "device"?

**Comment by cornelinux** [comment]
A user actually authenticates with a token, but not with a container / device.
So the question is, if these containers (smartcard, smartphone) actually should be located in the token database table. If the users authenticates with a smartcard, he does it with the certificate, not the smartcard. The user authenticates with an OTP token or Push token, not with the smartphone.

So actually it might make sense, that containers are not contained in the token table!

**Comment by cornelinux** [comment]
2024-01-15 Discuss: Do we need nested containes? See the keyring?

**Comment by nilsbehlen** [comment]
https://github.com/privacyidea/privacyidea/issues/3663
closing that to keep discussion here.

**Comment by nilsbehlen** [comment]
https://github.com/privacyidea/privacyidea/issues/1103

**Comment by nilsbehlen** [comment]
Open Questions:
* Can a container have multiple owners?
* Can a token be in multiple containers?
* Can a token of one owner be in anothers container?
* Can a template be used on multiple containers? (of the same type/generic?)

* Should we duplicate API functionality? E.g. have `container/smartphone/init/` return the combined response of the `/token/init` for each of the token specified by the template OR let the smartphone do the `/token/init`?


* How can a client find the container? Especially like yubikeys where you can not store the container_id on the device. The smartphone can store its container_id.
    -> find by token serials? find by device serial (in description)?
    -> find by owner of the container



* Is there any benefit to using inheritance on the containers as opposed to just the templates?
    -> There is not much that a smartphone, a yubikey and some biorecords of a person have in common, other than the general  management operations
* Should the containers and template be in one class? If separated, the templates to the heavy lifting.
* Should specific container types have the possibility to have extra API endpoints? for the smartphone this would probably be beneficial

* AUTHORIZATION: Some long lived form of authorization would be benefical for at least the smartphone. In that case, the user does not want to login at all/more than once (per month?). OAUTH?
