### ISSUE TITLE
"pi-manage resolver" should be able to dump resolver configuration

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1329]
We should have a function like

    pi-manage resolver r_export <resolvername>

to dump the complete resolver configuration of a resolver including passwords.
The root user of the privacyIDEA system has access to the encryption key and could decrypt the ldap password anyways. This would be a simple but still secure way to check resolvers. (See #1271)

**Comment by laclaro** [comment]
We could even think of a `pi-manage config c_export` which exports the complete config (resolver, realms, event handler, gateways, etc etc). Basically everything except tokens and audit.

This would be very useful for cases where you have non-mysql servers and you would like to copy the cofiguration. Or if you would like to transfer the config from one database type to a different database type.

**Comment by plettich** [comment]
And we can use the `manager.add_command()` to get rid of the stupid `e_export` and `e_import` and just use `export` and `import`

**Comment by cornelinux** [comment]
supperseeded by #2467
