### ISSUE TITLE
Refactor usage of __import__

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1335]
We use ``__import__`` at several places to dynamically import Python modules. Python 2.7 and 3.x come with the [importlib](https://docs.python.org/3/library/importlib.html) module and an ``import_module`` function that should be used instead. We should refactor our code accordingly.

**Comment by cornelinux** [comment]
Could make sense. Lots of the code is back from the time when we have python 2.6 compatibility.

**Comment by fredreichbier** [comment]
Oh, this was actually closed by #1338
