### ISSUE TITLE
Missing documentation for system configuration - "authentication counter per token"

### ISSUE THREAD

**Issue by adam820** [privacyidea/privacyidea#1339]
# What did you try to do?
Looking through the `Config -> System -> System Config` menu, I tried to look up information in the documentation on the option "Do not use authentication counter per token". Couldn't find it using the section or the search function.

A brief guess assumes that the authentication counter is tied to the user as a whole instead of the token(s), but without any documentation, I don't want to assume that.

# What outcome did you expect?
Documentation should present to give some context on what that option does (or what ramifications there are for enabling it).

# What outcome did you experience?
No docs were found.

# Configuration

* privacyIDEA Version: 2.23.3

**Comment by cornelinux** [comment]
Actually it does not write the counter at all.
These are the counters `count_auth` and `count_auth_success`.
These are entries in the table  `tokeninfo`. 
You can *not* use these counters for performance aspects, to simply spare 2 updates to the table `tokeninfo`.
