### ISSUE TITLE
Rework crypto layer

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1340]
During the Tests for #676 it became apparent that we need to rework the crypto layer in privacyIDEA.

In general we want to work with `unicode` strings except for the crypto parts which usually require `byte strings`.

We would rewrite the crypto layer interface to accept unicode strings and return (hexlified) unicode strings.
This will ease up the Python 3 migration as well.

And we could also work on #337 / #1212

**Comment by cornelinux** [comment]
I think this was closed with #1345
