### ISSUE TITLE
Push Token

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1342]
Define the first steps for the push token:

* [x] Define KeyURI
* [x] Define Endpoint Names
* [x] Implement Tokenclass
* [x] Implement Endpoints

![concept-push](https://user-images.githubusercontent.com/1908620/50009917-782bc580-ffb8-11e8-802c-243341682694.jpg)

See this wiki page: https://github.com/privacyidea/privacyidea/wiki/concept%3A-PushToken

**Comment by cornelinux** [comment]
@nilsbehlen look at this: https://github.com/privacyidea/privacyidea/wiki/concept:-PushToken#implementation-idea
I am wondering 
1. if there are different serives besides firebase. But obviously the token type is bound tightly to firebase, so that we do not need to make this configurable?
2. But I think it might be necessary to have more than on firebase app definition in an installation? So we might want to define different firebase config sets.?

**Comment by cornelinux** [comment]
I think it makes sense to store the firebase configuration in a certain config object and not spread the config over a lot of policies.

A good place to do this, might be in an SMS provder. We can create a new SMSProvider Class firebase. This takes the configuration of the firebase setup *and* takes care about sending the data to the firebase server.

A bonus side effect is, that this can immediately be used to send simple "SMS" OTP value to the registered client in a normal, manual challenge response authentication.

**Comment by nilsbehlen** [comment]
Of course there could be multiple firebase projects per privacyIDEA installation, but for what reason?
Anyway storing the setup config seems like a good idea, otherwise it would have to be extracted from the google-services.json again and again, requiring that the file is available every time.
