### ISSUE TITLE
Token type in trigger challenge response

### ISSUE THREAD

**Issue by Mipronimo** [privacyidea/privacyidea#1369]
It would be nice, if the response of a trigger challenge contains the token types.
For some plugins we could hide the otp input, if it is not needed (e.g. a user has only one u2f token).

**Comment by cornelinux** [comment]
This should be possible here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L2029

By simply adding 

~~~~python
challenge_info["tokentype"] = token_obj.token.type
~~~~
