### ISSUE TITLE
 Limit number of token types per user

### ISSUE THREAD

**Issue by blsho** [privacyidea/privacyidea#1375]
Admin can limit count of user tokens only by setting `max_token_per_user` (and `max_token_per_realm`). However, we would like to limit user so they can have only up to one token of each token type.

Possible solution from my point of view:
- Add a single option `max_same_tokentype_per_user` to policy. Value of the option will be integer and it will apply to all token types individually.
  - Benefits: 
    - Simple configuration and Web UI
    - generic approach and easier token type management (this functionality will not increase complexity of implementing new token types)
  - Downsides:
    - Reduced customization per token type
- Add multiple options (e.g. `max_hotp_per_user`, `max_totp_per_user`,  `max_sms_per_user`, `max_u2f_per_user`). Each token type will have its own option.
  - Benefits:
    - Highly customizable
  - Downsides:
    - Complex configuration and Web UI
    - Options and their count are variable a defined by supported token types. Count of options will have to reflect changes in supported token types.

Is such a feature reasonable? Which variant? Thanks.

**Comment by cornelinux** [comment]
Thanks for your interest and suggestion. At first this sounds very specific to me. And specific requirements are always a bit difficult since they can clutter the feature list. I always like to keep things very flexible. So the variant A does not sound nice to me at all.

Variant B would - as you already said - add to many options, which would be probably not used in 99,9999% of the scenarios ;-)

However, what do you want to achieve - from a top level view. Why would every user be allowed to have
* one TOTP token
* one HOTP token
* one U2F token
* one Email Token
* one 4eyes token
* ...
This sounds like a very strange requirements to me.
So what is actually your scenarion.

Maybe we can achieve something with the event handler rather then with a rigid, huge policy list.

**Comment by blsho** [comment]
We have multiple reasons:
- We want to promote U2F as a main token (with possibility of TOTP as a backup token) instead of 2 TOTP tokens (one main and second as a backup)
- Our end-users are used to refer to tokens by its type, so it is easier for operation team to have strong relation 1:0..1 in token_type:token for a given user
- From our experience, when end-users lost their token (e.g. change their phone number or change their phone device without backuping its TOTP) they just enroll the same token type again and don't remove the old one.
- Reduce fees for SMS validation (if user has more SMS tokens)

We were thinking about implementing custom event handler script, but it has one big downside - it can not provide instant feedback to end-user over Web UI.

**Comment by cornelinux** [comment]
Thanks for the input.
In the meantime some hints:

* You probably know, that you can restrict the tokentypes, that a user is allowed to enroll. 
  You can restrict the allowed tokentypes to TOTP, U2F and SMS.
* You can define an event handler, that if the user enrolls an SMS token this token is 
  automatically disabled. Like: ONly after approval of the helpdesk, the user can use an SMS token.
  (makes it less attractive)
* Set max_tokens_per_user to three tokens. If the user uses up his free tokens and still wants to enroll his first u2f token, then he needs to delete one.

Actually your scenario is quite special. Even the fact the end-users "refer to tokens by its type"! Never heard of this before! ;-)

We think about it and wait for a simply solution to pop into our minds.

**Comment by cornelinux** [comment]
We could do this by configuring

    max_tokens_per_user: totp=2 u2f=1

Which would mean, that the user could have 2 totp tokens and one u2f token.

Or do

    max_active_tokens_per_user: totp=2 u2f=1

**Comment by cornelinux** [comment]
I think we need to rethink this an get active with it.
I heard this topic a several times. If a user would be allowed to enroll 2 tokens (max token per user)
Since the user is supposed to have a TOTP and an SMS - the user still might enroll two TOTP.

**Comment by cornelinux** [comment]
We will check, if we can implement this in 3.2

**Comment by cornelinux** [comment]
In ``api/lib/prepolicy.py:check_max_token_user`` we can also add checks for tokentypes.

We might have to determine the tokentype of the token in question like if we only have the serial number in the request:

~~~~python
from privacyidea.lib.token import get_token_type
tokentype = getParam(params, "type")
if not tokentype:
     tokentype = get_token_type(serial)
~~~~

With the tokentype then could check the specific tokentype-policy.

**How would we define the tokentype-specific policy?**
