### ISSUE TITLE
Improve documentation about customization

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1377]
We need to improve the documentation about customization of templates
https://privacyidea.readthedocs.io/en/latest/faq/customization.html#templates

1. Activate ``mod_rewrite``
    
         a2enmod rewrite

2. Adapt apache config like this:

~~~~
<Directory />
    # For Apache 2.4 you need to set this:
    Require all granted
    Options FollowSymLinks
    AllowOverride None

    RewriteEngine On
    RewriteRule /static/components/login/views/login.html  /customize/login/views/login.html
</Directory>

# Customization is contained in /etc/privacyidea/customize/
Alias /customize /etc/privacyidea/customize
~~~~

**Comment by cornelinux** [comment]
Do not forget the customization for the enrollment wizard:
https://privacyidea.readthedocs.io/en/latest/workflows_and_tools/enrollment_wizard/index.html?highlight=wizard#customization

**Comment by Mipronimo** [comment]
We may have to take a look at the last paragraph in token wizard. It should look good, but in readthedocs it is not readable
It should look like

Example
---

Your privacyIDEA system is running in the URL sub path ``/pi``.
The files could be addressed via a path component ``mydesign`` (in this case ``pi/mydesign``).
Thus the WebUI will look for the files in the URL path ``/pi/mydesign/views/includes/``.

So you set in ``pi.cfg``:

    PI_CUSTOMIZATION = "/mydesign"

Your customized files are located in ``/etc/privacyidea/customize/views/includes/``.
In the Apache webserver you need to map ``/pi/mydesign`` to ``/etc/privacyidea/customize``:

    Alias /pi/mydesign /etc/privacyidea/customize


But in fact it looks like 
![bildschirmfoto von 2019-02-06 15-15-45](https://user-images.githubusercontent.com/35998229/52347569-8c24fe00-2a22-11e9-8069-cd37b15b523d.png)
