### ISSUE TITLE
Add angular tests without node

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#139]
We might add some angular tests without node.js

https://groups.google.com/forum/#!topic/angular/-ZS9vje4exY

**Comment by wheldom01** [comment]
Following my updates to the angular code for resolver add user form generation I've been looking into unit testing for angular and have the following suggestion to support this goal:

1. Addition of a testing blueprint that is only imported when running privacyIDEA with a development configuration.
2. Have a seperate static directory for the testing blueprint which will host the angular senario

What are your thoughts?

**Comment by cornelinux** [comment]
I did not investigate into this for about a year. I moved to doing automated UI testing on each git commit using ghostinspector.

You mean the testing blueprint can provide a "url", that runs all the tests in the browser?
It would be a manual process(?), but I think it might be ok, to open the browser and run the test once manually in the browser.

**Comment by cornelinux** [comment]
I am closing this. We will one day move away from angularJS.
