### ISSUE TITLE
Failed token resync appears as succeeded in audit log

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1416]
When a token resync request fails, the entry in the audit log is marked as "succeeded".
According to [`api/token.py`](https://github.com/privacyidea/privacyidea/blob/333d704397623ca20798f505b39f7278ba24416e/privacyidea/api/token.py#L618) the result of the resync is not checked.

**Comment by cornelinux** [comment]
I think marking this as "fail" in the audit log is totally ok.

So it probably would be something like:

~~~~python
res = resync_token(serial, otp1, otp2, user=user)
g.audit_object.log({"success": bool(res)})
return send_result(res)
~~~~

can you please change this and adapt the tests (if needed)?
