### ISSUE TITLE
Honour HTTP_AGENT in policies

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1425]
It could make sense to also make policies dependent on the HTTP-AGENT. This of course is often difficult, since the client can change its HTTP-AGENT, so this could only be possible if the client acutally is a trusted system.

But this way, we would be independent of the client IP.

@fredreichbier @plettich what do you think?

**Comment by plettich** [comment]
How do we trust a client system?

**Comment by cornelinux** [comment]
If the client is a server, this could be trusted. This way on one machine there could be several different applications, that query privacyIDEA with different HTTP_AGENTs.

At the moment there would be no (easy) way for us, to have different policies for different applications originating from the same IP.

**Comment by fredreichbier** [comment]
Ah yeah, I guess matching the HTTP user agent makes sense in order to differentiate applications from the same IP. But this wouldn't work in all cases, would it? e.g. two ownCloud instances at the same IP would still send the same user agent and would be indistinguishable?

Instead of focusing on the user agent, we could also implement matching arbitrary HTTP request headers?

**Comment by cornelinux** [comment]
arbitrary HTTP headers sound nice!

**Comment by cornelinux** [comment]
see #1260

**Comment by cornelinux** [comment]
* [ ] We need to pass the REQUEST information to the policy handling in [get_policies](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/policy.py#L464) and [get_action_values](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/policy.py#L638)

* [ ] We need to add a database field or whatever for the HTTP_Agent. Maybe we should already add a table for conditions?

**Comment by cornelinux** [comment]
I am moving this to a later milestone. In 3.1 we should concentrate on the user attributes!

**Comment by fredreichbier** [comment]
If #1757 gets into 3.2, this could be implemented quite easily for 3.2. Otherwise, we might move this to 3.3.

**Comment by cornelinux** [comment]
Somewhere around the client IP we could add the ``HTTP header``.

![image](https://user-images.githubusercontent.com/1908620/66775629-c6557200-eec4-11e9-9dea-ce06b514f123.png)

We probably want to do some regular expression matching, so that we would match different headers with e.g. different version numbers. However, if we want to allow a **list** of different headers, this may get difficult. One header is simple:

    User-Agent=/Mozilla.*/

matching all mozillas for this policy.

If we want a logical **and**, that this policy does only match for

    User-Agent=/Mozilla.*/  

**and**

    Accept-Language=.*de.*

The parsing logic is a bit difficult, since we would need to determine, where one regexp stops and the next starts.

However, we *could* use the extended matching functionality like with the CONDITION_SECTION.USERINFO and have a CONDITION_SECTION.HTTP_HEADER.
