### ISSUE TITLE
Add audit rotation to base config

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1427]
A fresh installation on privacyIDEA is currently missing a audit rotation cron job.

We should add it to "deploy/crontab/privacyidea" but in comments like:

    #1 2 * * *	privacyidea	pi-manage audit rotate_audit --age 360

This way we can avoid to interfere with already existing configurations.

@plettich @fredreichbier any idea how to handle existing installations?

**Comment by fredreichbier** [comment]
Hm, just an idea: We could also use our "Periodic Task" feature and add a "Audit Rotation" task module.  On fresh installations, we could add a periodic audit rotation task that is inactive by default. By this, we could avoid modifying "deploy/crontab/privacyidea" at all.

**Comment by cornelinux** [comment]
sounds nice!

**Comment by cornelinux** [comment]
@pablo-knight please also add this to CentOS/RHEL.
