### ISSUE TITLE
Fetching SSH-Keys retrieves all keys per machine not per user

### ISSUE THREAD

**Issue by boschkundendienst** [privacyidea/privacyidea#144]
Hi,

While playing arround with a bash script to retrieve SSH keys from the PrivacyId3a server I found out, that a request for /machine/authitem/ssh?hostname=$HOSTNAME retrieves all SSH keys for the hostname and the selection which of the keys will be used for the user who tries to login is made on the client machine.
Also a look at the code in "privacyidea-authorizedkeys" confirms my findings.

So all SSH-Keys per host are transfered over the wire while just a single one is needed.
Depending on the environment this could also result in a security risk.

The API should have an option/parameter to select for which user we want to retrieve the SSH key.

Maybe the API could be extended with an additional parameter or a new API mode should be created?

Kind regards

PCFreak

PS.
This issue is a result of a personal communication with Cornelius. He asked for an issue at Github and here it is :)

**Comment by cornelinux** [comment]
Hi PCFreak,
the API ``/machine/authitem/<apptype>`` is a common API for different application types. Not all application types provide the option "user". Nevertheless, of course the API could allow to also pass other options like

     /machine/authitem/ssh?hostname=XYZ&user=root

This would do the filtering on the server side but which would not restrict from also issuing the call for another user. In fact the host XYZ **must** be able to call ssh keys for all users.

So I do not think, this being a security risk but if you think it is sensible to implement...

Any additional comment?

**Comment by boschkundendienst** [comment]
Hi,

it is not directly a security issue but why sending unnecessary keys 
through the network.
More keys = more information = possible more disclosure

Anyhow if it is easy to implement I would recommend to do it, if not you 
should document that
all of the keys are sent arround.

Kind regards and thanks for the hard work

PCFreak

Am 01.06.2015 um 16:03 schrieb Cornelius Kölbel:

**Comment by cornelinux** [comment]
HI PCFreak,

thanks for the feedback.
Implemented :-)

Kind regards
Cornelius
