### ISSUE TITLE
Auth cache table fills up if the user always provides a fresh PIN+OTP

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1466]
Assume we have set up the auth cache, and assume that some user does not use it, i.e. always authenticates with a fresh PIN+OTP. In that case, the auth cache will grow with each authentication request, because old entries of the user are not deleted. Note that this is not a security problem because old (expired) entries are not taken into account for authentication.

This is because ``delete_auth_cache`` is only called in case the user authenticates with an expired password:
https://github.com/privacyidea/privacyidea/blob/071ed10dc1ace0873a8e5a2eaa25e6f71f71a6df/privacyidea/lib/authcache.py#L102

So we need some way to clean up expired entries. Should we do this similarly to the user cache and provide a ``privacyidea-authcache-cleanup`` script?

**Comment by fredreichbier** [comment]
The most obvious solution is just removing expired entries when authenticating. However, this may be problematic
* because of table locking issues? We had some problems with deletions in the past.
* because the expiration depends on the currently matching policy. Theoretically, there may be multiple ``authcache`` policies with different expiration times, and we might delete entries that are expired according to policy A, but still valid according to policy B! ... but this sounds like an edge case, so we could implement this, but also document it properly.

**Comment by cornelinux** [comment]
And again! **Cache Invalidation** is one of the biggest problems in the IT.
I guess this is the reason we did not do it in the fist place! ;-)

There are also other aspects: Think of not only two different policies but also two different tokens originating for the same user from the same IP.

This could end up in two authcache entries, well with different ``authentication`` hashes. But anyway, how would we know, that these are different tokens, or is it simply the same token with a different OTP value? 
Maybe we should in addition store the maximum validity time, because: At the first authentication, which goes against the token and not the auth_cache, it is defined, what is the maximum validity time
(see https://privacyidea.readthedocs.io/en/latest/policies/authentication.html?highlight=auth_cache#auth-cache) We might still have the problem of conflicting policies, but these occur at the initial authentication where the conflict might be easier to handle.

BUT: In this case we would need to add a column to the database and thus we could not add it to a 2.23.5. So we should find a simple (well documented way) to do this for 2.23.5 and then add the final fix to 3.0.

**Comment by fredreichbier** [comment]
> And again! **Cache Invalidation** is one of the biggest problems in the IT.
> I guess this is the reason we did not do it in the fist place! ;-)

Probably :-)

> Maybe we should in addition store the maximum validity time, because: At the first authentication, which goes against the token and not the auth_cache, it is defined, what is the maximum validity time
> (see https://privacyidea.readthedocs.io/en/latest/policies/authentication.html?highlight=auth_cache#auth-cache) We might still have the problem of conflicting policies, but these occur at the initial authentication where the conflict might be easier to handle.

I like this approach -- then, we can prune all expired entries quite easily. We could resolve conflicts by taking the maximum or minimum validity time in a well-defined way.

Maybe we can even implement the authcache differently and store a ``next_auth`` timestamp which tells us the datetime before the next authentication has to occur, instead of a ``last_auth`` timestamp. Then we can just delete all entries for which ``next_auth`` is in the past.

> BUT: In this case we would need to add a column to the database and thus we could not add it to a 2.23.5. So we should find a simple (well documented way) to do this for 2.23.5 and then add the final fix to 3.0.

True. We could add a small script like
```
privacyidea-authcache-cleanup 1d
```
which would remove all AuthCache entries for which ``last_auth`` is more than one day ago? This would require the user to think of a maximum validity timeframe, but would be simple to implement.

Or, even simpler, we just add a sentence to the documentation like "Currently, the auth cache is never cleaned, so you have to run ``DELETE FROM AuthCache WHERE last_auth < NOW() - INTERVAL 1 DAY``" (haven't tested that though :-))

**Comment by cornelinux** [comment]
> True. We could add a small script like
>~~~~bash
>         privacyidea-authcache-cleanup 1d
>~~~~
> which would remove all AuthCache entries for which last_auth is more than one day ago? This would require the user to think of a maximum validity timeframe, but would be simple to implement.

I like this the most!
This does not break the current code.

So for 2.23.5:

* [ ] lets backport the auth_cache
* [ ] and add this script

For Rel 3

* [ ]  we then change the DB to add ``next_auth`` and something like ``maximu_auth``.
* [ ] We then can delete entries with either ``next_auth`` or ``maximum_auth`` (or latest). Easy cleaning.

**Comment by fredreichbier** [comment]
I was thinking: Implementing this properly will require quite some brainpower, we would need to change the database schema and think about migration issues.
As the auth cache should only be used as a last resort anyway, and because ``pi-manage`` allows to clean up expired auth cache entries, I think this issue is not very critical right now. Maybe we should postpone it to 3.2?

I'm also changing this from a bug to a known issue, because it's more of a performance/database size issue.

**Comment by fredreichbier** [comment]
As explained above, this is not critical. Moving this to 3.2.

**Comment by fredreichbier** [comment]
Check if ``pi-manage authcache cleanup`` is mentioned in the docs. We will ask users to use the cleanup script.
