### ISSUE TITLE
Add information to /auth endpoint why it failed

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1478]
The audit entry in the /auth endpoint currently does not contain any information, why an authentication would fail.
The information could be added to the auditlog.
See https://community.privacyidea.org/t/audit-log-for-auth-requiring-a-challenge/963

**Comment by fredreichbier** [comment]
Hm, does #1197 solve the problem? (at least partially?)

**Comment by cornelinux** [comment]
Hm, I am currently not quite sure. It could be.
Does the error object in case of an AuthError has a message? I am not sure.
The thing is, if the /auth (i.e. login to webui) is a challenge response, the first failing authentication (which triggers the challenge) should contain the information that a challenge was triggered.

**Comment by fredreichbier** [comment]
I think we actually already do something like that: I checked current master (72cab0f9700594b543897bd17abf381e4dea27e7) and enrolled an email token and set a ``login_mode=privacyIDEA`` policy.
* If I enter a wrong OTP PIN, the audit log entry's info field says "Authentication failure. Wrong credentials|wrong otp pin"
* If I enter the correct OTP PIN, the entry's info field says "Authentication failure. Wrong credentials|Enter the OTP from the Email:"
* If I now enter the wrong OTP, it says "Authentication failure. Wrong credentials"

**Comment by cornelinux** [comment]
I add this to milestone 3.6 either to close this issue or to solve it!

**Comment by cornelinux** [comment]
Sounds good to me. I remove this from the milestone to avoid the impression, that s.th. was done in 3.6.
