### ISSUE TITLE
Streamline installation and upgrade by stamping the database upon creation

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1489]
Currently, our installation process runs ``pi-manage createdb`` to create all database tables. This is how the Ubuntu packages do it, and also how the documentation [describes](https://privacyidea.readthedocs.io/en/latest/installation/pip.html) pip installations.

I think it would be nice if we would also stamp the database to the latest revision for fresh installations. We could do that by adding ``pi-manage db stamp head`` to the Ubuntu postinst scripts and to the documentation.

This would make future upgrades smoother:  Currently, for new installations, ``privacyidea-schema-upgrade`` has to stamp the database to the first alembic revision and apply all migration scripts since then. If we initially stamp the database of fresh installations, we could skip this step.

What do you think?

**Comment by cornelinux** [comment]
This makes absolute sense, then we would start a new database with the right alembic version.

**Comment by fredreichbier** [comment]
I added it to the 3.0 milestone because it would be good opportunity to start, hope that's okay.

**Comment by cornelinux** [comment]
I moved this to https://github.com/NetKnights-GmbH/ubuntu/issues/4
and also change the label to documentation.
