### ISSUE TITLE
search_on_enter policy should also apply for audit log searches

### ISSUE THREAD

**Issue by stojmir** [privacyidea/privacyidea#1493]
# What did you try to do?
Enable search_on_enter in the policy.
This successfully disables search-as-you-type for the token and user lists, however not for the audit log search boxes.

# What outcome did you expect?
Intuitively, search_on_enter should apply to all search boxes in the web interface.

**Comment by cornelinux** [comment]
I was never convinced of this search_on_enter thing. The intention for search on enter was to prevent *external* network traffic, e.g. to the external LDAP server.

In case of the audit log all searches are localized on the privacyIDEA server. So I do not see any sense in doing this here.

Maybe we should improve the documentation:
https://privacyidea.readthedocs.io/en/latest/policies/webui.html?highlight=search_on_enter#search-on-enter
