### ISSUE TITLE
Realm-Select box with broken "placeholder"

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1498]
In the login screen there is a realm select box.

The placeholder for the select box does not work:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/login/views/login.html#L63

We could either fix the placeholder or preselect the default realm.

**Comment by aexlz** [comment]
Apart from that:
The logincControllers.js could be edited to the following:
$scope.piRealms = obj.val().mysplit(",").sort();

Sorting the realms alphabetically meets the user's acceptance slightly.
