### ISSUE TITLE
Drop support for ubuntu 14.04 and add upgrade information

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1504]
We will drop support for ubuntu 14.04 with privacyIDEA 3.0.

1. There are new dependencies (like the right version for python-oauth2client) missing.
2. The OS Ubuntu 14.04 does not get a lot of updates anymore. (see https://www.ubuntu.com/about/release-cycle)

The rough upgrade path will be:

* Of course make a backup of the database and encryption keys (/etc/privacyidea)
* Update the installation on ubuntu 14.04 to the latest 2.23.X (currently 2.23.5)
* Run a ``do-release-upgrade`` and update to 16.04.
  * If necessary update privacyIDEA 2.23.5 to 3.0

**Comment by cornelinux** [comment]
Please note:

up to 2.23.5 there were launchpad repositories.
Now there are the lancelot community repos.

A way to upgrade is:

* update to the latest versions in 14.04.
* do-release-upgrade. 
* remove launchapd repos
* add lancelot repos
* reinstall privacyIDEA! (maybe)

**Comment by laclaro** [comment]
Closed by https://github.com/privacyidea/privacyidea/pull/2063
