### ISSUE TITLE
passlib.utils.binary not available on Ubuntu 16.04

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1505]
The SQL Resolver fails to load on ubuntu 16.04, since Ubuntu 16.04 comes with passlib v 1.6.5.

This does not contain ``passlib.utils.binary``. So we can not import ``h64``.
Please check, if we can avoid to use h64.

**Comment by cornelinux** [comment]
I would wait for this.

We have a lot of lot of issues on 16.04 (also #1525 and als RSA-sign/cryptography problems we have not filed, yet)
We should discuss next week, what we do in regards to this.

**Comment by plettich** [comment]
already on it.

**Comment by cornelinux** [comment]
Same problem as in #1525. MAybe get rid of it generically.

**Comment by cornelinux** [comment]
We go for virtualenv!
