### ISSUE TITLE
Add huey to requirements

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1520]
The tests  ``import huey``.
Tests will currently not run in a virtualenv, since the test requirements are missing huey.
We do not requre huey for productive use, but it should be required for testing.

**Comment by fredreichbier** [comment]
Hmm good point! I think ``requirements.txt`` already contains huey:
https://github.com/privacyidea/privacyidea/blob/4fbc4691f61dd96983643ba82d47ad39389ee841/requirements.txt#L24
... but should we add it somewhere else as well?

**Comment by cornelinux** [comment]
OK, then obviously it was only me, who did not update my virtualenv!
I close this.
