### ISSUE TITLE
Revert Command() in pi-manage

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1525]
We need to revert the Command calls in pi-manage, since they are too new.

     ca_manager.add_command('list', Command(list_ca))

**Comment by cornelinux** [comment]
@plettich Does python3 NOT allow to have a function "list()"?

**Comment by plettich** [comment]
Well it does but it isn't 'pythonic' since this overwrites the internal `list`-keyword and might lead to undefined behavior. We can write a Command object which does the required action.

**Comment by cornelinux** [comment]
Basic though:

Moving ubuntu packages into a virtual env.

scripts in the virtualenv already contain the correct python path in the header, that points to the virtual env.
Looks like we could simply add the corresponding PATH to the end of the PATH like

    export PATH=$PATH:/opt/privacyidea/bin

making all scripts including pi-manage available in the system.

On topic to clarify: Dependency updates
* How do we update dependencies?
* How should we reflect dependency updates in package version numbers?

**Comment by cornelinux** [comment]
I think we leave it that way since we go for virtualenv.
