### ISSUE TITLE
Use auth and authz policies also with the /auth endpoint

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1537]
Several auth and authz policies are not used with the webui. 
It is because those policies are decorators to ``/validate/check`` but of course can not easily be decorators to the ``/auth`` endpoint.

We need to investigate, how it is possible to also honour the policies in the web UI **if** ``loginmode=privacyIDEA`` is set.

**Comment by fredreichbier** [comment]
We have the following authorization policies that may be useful for the /auth endpoint:

- [ ] "add_resolver_in_response"
- [ ] "add_user_in_response"
- [ ] "api_key_required"
- [ ] "auth_max_fail"
- [ ] "auth_max_success"
- [ ] "last_auth"
- [ ] "no_detail_on_fail"
- [ ] "no_detail_on_success"
- [ ] "serial"
- [ ] "setrealm"
- [ ] "tokeninfo"
- [ ] "tokentype"
- [ ] "u2f_req"

**Comment by fredreichbier** [comment]
We'll need to clarify which auth/authz policy even make sense for the ``/auth`` endpoint. Moving this to 3.2.

**Comment by cornelinux** [comment]
In case of **auth_max_fail** and **auth_max_success** these values are checked in the decorator ``auth_user_timelimit``.

Currently the ``auth_user_time_limit`` takes the the authentications from the audit log with the action ``/validate/check``. 

The ``auth_user_timelimit`` decorates ``lib/token/check_user_pass``.
``lib/token/check_user_pass`` is also called in case of the webui login with ``loginmode=privacyidea``.
So there would be no need to change any of the decorators. It would already *work* as far as the decorators are concerend.

We only need to change the action-filtering in ``auth_user_timelimit`` in the audit log, which is currently:

~~~~python
fail_c = g.audit_object.get_count({"user": user_object.login,
                                               "realm": user_object.realm,
                                               "action":
                                                   "%/validate/check"},
                                              success=False,
                                              timedelta=tdelta)
~~~~

We would have to filter for /validate/check and /auth (in case the correct loginmode is set)

# Approach A

The /validate/check and the /auth endpoint (in case loginmode=privacyidea) write a common information to the auditlog and we filter for this value.

# Approach B

The /auth endpoint in case of loginmode=privacyidea writes the action 
"POST /auth via /validate/check" to the action. So we would not have to change anything of the existing decorator code.

# Approach C

The /auth endpoint in case of loginmode=privacyidea writes an additional information and the
decorator fetches the occurrances of /validate/check and the occurrences of this /auth and calcuates the sum.
(For clarity in the audit log and backward compatibility I - currently -  would prefer this approach)
Currently the serial number is written to the audit log. Well, if the user authenticates against privacyIDEA and fails all PINs, (failed request, we also have no serial in the audit log).
