### ISSUE TITLE
Vertical center in top bar

### ISSUE THREAD

**Issue by Mipronimo** [privacyidea/privacyidea#1559]
![Bildschirmfoto vom 2019-04-05 10-22-28](https://user-images.githubusercontent.com/35998229/55614316-f8a34b80-578c-11e9-9249-6e5e93bc8cd8.png)
In the attached screenshot, you can see the top bar of privacyIDEA. You see, the logo on the left and the button on the right side. These two objects should be centered vertically, as the other elements do.

**Comment by cornelinux** [comment]
The menu and positioning of the elements is a bit tricky.
Improving quality by at least four eyes - maybe you, @Mipronimo can shet some light.
