### ISSUE TITLE
enrol Nitrokeys for OTP

### ISSUE THREAD

**Issue by jans23** [privacyidea/privacyidea#1564]
I want to enrol several Nitrokey devices for OTP authentication. Similarly to the existing Yubikey enrolment command, several Nitrokeys should be enrolled in a row. libnitrokey exists which theoretically should provide the low-level functionality required. Please describe the technical requirements on such a library in detail or point to a Yubikey-focused example so that we could investigate how libnitrokey could be integrated.

**Comment by cornelinux** [comment]
The Nitrokey is in fact enrollable.
https://netknights.it/en/privacyidea-enrollment-station-for-yubikey-and-nitrokey/

We could add an example here:
https://github.com/privacyidea/privacyidea/tree/4929d4e0a7a11cbc564a88d034f7903665ba8024/doc/configuration/tokens based on the blog post above.

Where did you expect the documentation?
Could you contribute some text?

**Comment by jans23** [comment]
You are right. I was referring to the `nitrokey_mass_enroll` operation which I overlooked. Thanks.
