### ISSUE TITLE
Restrict admin policies in OTP-Length, Hash, Timestep

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1566]
Policies in scope "user" can be restricted in OTP Length, hash and timestep.
Admin-policies should also have this restriction, so that helpdesk users can get a simple view.

**Comment by plettich** [comment]
TODO:
- [ ] improve tests
- [ ] add documentation

**Comment by cornelinux** [comment]
@plettich  Hm, isn't his resolved by the PR?  - or are we missing some docs?

**Comment by plettich** [comment]
Yes, docs are missing, working on it.
