### ISSUE TITLE
Missing html template "enrolled" for certain token types

### ISSUE THREAD

**Issue by ahmedbodi** [privacyidea/privacyidea#1571]
# What did you try to do?

Issue possible?

Trying to solve a different issue, but found this in the console which may/may not be an issue
Searched the issues to see if there was anything similar but didnt find any. 

Error in the browser console:
The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - /static/components/token/views/token.enrolled.yubico.html

* privacyIDEA Version: Latest from PIP

**Comment by cornelinux** [comment]
This is an include file per token type. If it does not exist, it is not displayed.

I ask you to reconsider using yubico mode token, since the otp value is verified with the yubico cloud service.

**Comment by cornelinux** [comment]
@NuvandaPV One day we should think about this. Each token *can* have a file "enrolled", but not each token type defines one.

**Comment by cornelinux** [comment]
It works for me. I do not want to add files, that are not needed.
