### ISSUE TITLE
Creating Yubico Token causes message about setting config

### ISSUE THREAD

**Issue by ahmedbodi** [privacyidea/privacyidea#1572]
I've setup PrivacyIdea from the latest version on PiP.
Encountering the following Issue, i've gone through the setup, configured what i needed. Setup Policies for the things i didnt want users to use. Obtained an API key from the yubico website as instructed. 
The issue im encountering is this. 
When a user (non-admin) is trying to enroll their yubikey. This is the message that is displayed on the page: 

For Yubico tokens to work properly you need to set the Yubico Token Config!

Now the first issue is, the user can successfully add their yubikey which is fine. However that message shouldnt be there. 

The second issue, is a normal user shouldnt be able to click that link and view the settings?

If theres anyway i can help get to the bottom of the issue lmk

**Comment by cornelinux** [comment]
This happens in this template:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.yubico.html#L2

It is actually difficult to verify, if the admin has configured the yubico settings. - I assume roughly ten lines of code.
But we could simply add an ``ng-if`` to display this help block only if the logged in user is of role "admin".

**Comment by cornelinux** [comment]
THis is removed for the role user in release 3.1.
