### ISSUE TITLE
Radius integration appears to be broken in 3.0

### ISSUE THREAD

**Issue by droobah** [privacyidea/privacyidea#1579]
I have a system running 3.0 and the latest perl module for freeRADIUS.  All authentication requests coming via the freeRADIUS plugin are failing.  I believe I have narrowed down the issue to the fact that RADIUS sends in a state variable during authentication and 3.0 appears to handle this differently than 2.23.

In check_token_list, it appears that is_challenge_response is always returning true when the authenticaiton request is coming from freeRADIUS.  This of course fails since there is not a challenge currently in progress for any of the tokens.

**Comment by cornelinux** [comment]
3.0 does not handle authentication requests differently than 2.23.
I could be some interesting side effect. But with this limited information, this does not help.
You need to provide more information about how you are authenticating.

Log files are also good. This is why we have this issue templates. Please use this the next time!

**Comment by droobah** [comment]
My apologies.  I noticed my RADIUS test client had been sending in an invalid state when the authentication began.

So many hours wasted for a simple mistake on my part.
