### ISSUE TITLE
Send info to logstash et.al. via event handlers

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1580]
**Is your feature request related to a problem? Please describe.**

We want to send information about events in the privacyIDEA system to a logging facility like logstash or...

**Describe the solution you'd like**

There is already an issue for this in #1072 to send the audit log to the logging facility. But there might also be another approach by either adding a new event handler or enhancing the notification handler.

This way we could create more specific logging events, since logging events could be related to the set of conditions.

The log-event-handler could read a python logging.conf file. Using the python logging mechanism could help us to have enough flexibility for either writing to a file or to syslog or to email or wherever.

For this we would need to define a new object "logging facility". One class of logging facilities could be the python logging and would require a logging.conf for configuration.
Other logging facilities might be more specific.

The notification handler then would allow notification via

  * email (email server) / already implemented
  * sms (sms gateway) / already implemented
  * logging (logging facility) / implemented with this issue.

There are already a lot of tags for the "message" in the event handler. The message then would simply be the log entry sent to the logging facility.

(To be discussed for 3.1)

**Comment by fredreichbier** [comment]
See #1072

**Comment by cornelinux** [comment]
@plettich please add the splunk HTTP python logging config as an example.

In the file audit module we also used the python logging facility. We should check there how this was done. (As @fredreichbier already linked in #1072 for the FileAudit ;-) )

**Comment by cornelinux** [comment]
We simply create a notification handler that does one call to ``log.info``.
The logging.cfg then can determine, where the information is put.

**Comment by plettich** [comment]
TODO:
- [ ] tests
