### ISSUE TITLE
push token challenge in the database is not marked as successfully answered.

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1584]
# What did you try to do?

I successfully authenticate with a push token. 
The Push Token App also confirms successful authentication.

# What outcome did you expect?

The column otp_valid in the challenge database should be set to one.

# What outcome did you experience?

The column otp_valid was not set to 1. It stayed at 0.

# Configuration

* privacyIDEA Version: 3.0
* Installation method: ubuntu
* mysql database

Obviously the otp_value is not saved to the database.

**Comment by plettich** [comment]
Hmm... somehow github did not close this issue automatically.

**Comment by plettich** [comment]
It was merged into `branch-3.0`, not `master` so github does not automatically closes it... sorry.
