### ISSUE TITLE
Setting and then Clearing 'User Cache expiration in seconds' Breaks Authentication

### ISSUE THREAD

**Issue by droobah** [privacyidea/privacyidea#1596]
# What did you try to do?

Clear/delete value for 'User Cache expiration in seconds' under System Config.

# What outcome did you expect?

Value reset to default of 0.

# What outcome did you experience?

Authentication breaks after value is cleared.  Error is logged to log file.

`
[2019-04-26 14:31:42,511][ERROR][privacyidea.lib.token:493] User information can not be retrieved: invalid literal for int() with base 10: ''
`

Changing UserCacheExpiration back to 0 directly in the config table in the pi database and restarting the Apache2 service resolves the issue.

# Configuration

* privacyIDEA Version: 3.0
* Installation method: ubuntu packages

## more details: 

* OS: Ubuntu 16.04LTS
* Webserver: Apache2
* Tokendatabase: MySQL

**Comment by plettich** [comment]
Thanks for the report.
I could reproduce this behavior, it looks like an incorrect value is written to the db.

**Comment by cornelinux** [comment]
The safest way is to assure, that sensible data is read here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/usercache.py#L73
