### ISSUE TITLE
Message at Token Enrollment>PUSH>successfully enrolled

### ISSUE THREAD

**Issue by tamaro-skaljic** [privacyidea/privacyidea#1598]
The "sucessfully enrolled" message is displayed in german and english instead of only german.
In the english part `{{ enrolledToken.serial }}` must replaced to the tokens serial number.

![Bildschirmfoto von 2019-04-30 16-44-44](https://user-images.githubusercontent.com/49238587/56970413-5c8c1a80-6b67-11e9-9b77-e2b0d7ea19f3.png)

**Comment by cornelinux** [comment]
After all we do not need the english text anyway, since the generic text already has all information!

**Comment by cornelinux** [comment]
Please note, that there is now only the english text. Merging translation into the master branch is not that a lot of fun. If we want to do this, we should do this as last step.
