### ISSUE TITLE
Allow to configure push for iOS

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1608]
We need to be able to configure push for iOS.
We probalby need to add some APP ID and API KEy.

**Comment by nilsbehlen** [comment]
Thats right, the file for iOS is in .plist format which looks like this:
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html

We need the values for the keys "GOOGLE_APP_ID" and "API_KEY".

**Comment by nilsbehlen** [comment]
Yes. I've updated the wiki:
https://github.com/privacyidea/privacyidea/wiki/concept%3A-PushToken#firebaseparameter-appidios
