### ISSUE TITLE
Some tokens will enrolled despite errors

### ISSUE THREAD

**Issue by tamaro-skaljic** [privacyidea/privacyidea#1609]
If you choose following token types and click on "Enroll token" without edit something in the form it will thrown an error but enroll the token nevertheless.

Type: `4Eyes Token: Use tokens of two or more users to authenticate`
Error: `ERR905: Missing parameter: '4eyes'`

Type: `Certificate: Enroll an x509 Certificate Token.`
Error: `ERR905: Missing parameter: 'ca'`

Type: `Questionnaire: Enroll Questions for the user.`
Error: `ERR905: Missing parameter: 'questions'`

Type: `SSH Public Key: The public SSH key.`
Error: `ERR905: Missing parameter: 'sshkey'`

Type: `U2F: Enroll a U2F token.`
Error: `ERR301: You need to define the appId in the token config!`

Think it will be better when we force the missing parameters instead of enroll tokens while thrown errors.

**Comment by cornelinux** [comment]
In some cases it could be that the token object needs to exist, before other actions can be taken.
We would have to check, in which cases it would be possible, that the token does not get created (I think this is possible in none of those cases).

**Comment by cornelinux** [comment]
Some tokens have several enrollment steps, so it is quite "normal" that some tokens could not be readily enrolled during the first step. Some of the points are still valid, some are not.

E.g. Valid:

* a 4eyes token will not work without 4 eyes.

E.g. Invalid

* The U2F token will still work afterwards if the admin defines the appId. So it is totally fine (although not common) to enroll a u2f token this way.

**Comment by cornelinux** [comment]
I think this works as designed on purpose.
We can use event handler to clean up.
