### ISSUE TITLE
Some navigation tabs link to empty sites

### ISSUE THREAD

**Issue by tamaro-skaljic** [privacyidea/privacyidea#1610]
Some navigation tabs link to empty sites if you're already on them.

Example: Click on Audit and then click again on audit. You will see a "empty" site.

Following tabs are affected:

Components ( `/#/component/clienttype` and `/#/component/` )
Audit ( `/#/audit/log` and `/#/audit/` )

Config > Policies ( `/#/config/policies/list` and `/#/config/policies/` )
Config > Events ( `/#/config/events/list` and `/#/config/events/` )
Config > Periodic Tasks ( `/#/config/periodictasks/list` and` /#/config/periodictasks/` )
Config > Machines ( `/#/config/machineresolvers/list` and `/#/config/machineresolvers/` )
Config > Users ( `/#/config/resolvers/list` and `/#/config/resolvers/` )
Config > CAs ( `/#/config/caconnectors/list` and `/#/config/caconnectors/` )

The tabs Tokens, Users/User, Machines, Config, Config > System, Config > Tokens and Config > Realms are not affected.

**Comment by cornelinux** [comment]
That is true. I think this could be due to a local flaw in the routes and corresponding controllers like here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/config/controllers/configControllers.js#L23

We can investigate this and you could fix all occurrences.
