### ISSUE TITLE
Python 3.5 does not work with privacyIDEA

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1616]
Currently privacyIDEA does not work with Python 3.5, which is the default python 3 version in Ubuntu 16.04.
The `json.loads()` function expects a unicode string in python 3.5. In later versions, unicode and byte strings are supported.
The Flask-Response `data`-attribute, which we use to feed `json.loads()`, is unfortunately a byte string.
We could work around this problem by
1. converting all data passed to `json.loads()` to unicode first (which is done in most of the tests) or
2. use the Flask-Response `get_json()` function.

**Comment by XtraLarge** [comment]
It were greate if you can post your changes, because I've the same problem. :)
