### ISSUE TITLE
PIN setting and token assignment during migration

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1619]
When migrating from another old OTP system and using the forwarding policy to another radius server, we could add the following functionality:

# scenario

old hardware tokens are assigned to the user in the old system.
But the hardware tokens are also imported to privacyIDEA and not assigned to any user.

# what (should) happen

The authentication request is already  sent to the old radius server. If the authentication succeeds, then we can do the follow (new) things:

We grab the OTP value from the *pass* forwarded to the remote system.
We try to "find" the unassigned token, that generates this OTP value.
If the token is found, then the token is assigned to the user.
We grab the OTP PIN from the originally entered *pass* and set the OTP PIN for this newly assigned token.

To do this, we need the following additional information:

* how long is the OTP value
* is the OTP PIN prepended or appended.

# Outcome

The administrators only have to import the old otp seeds.
Tokens get assigned automatically and PINs get set automatically.

The user actually does not know or see, that something happens in the backend.

Tokenassignments and PINs are automatically transferred from the old system to privacyIDEA.

**Comment by cornelinux** [comment]
We can implement this as a postpolicy in ``api/lib/postpolicy.py``.

We need the information:

* PIN before OTP or After
* length of the OTP value

The conditions for assignments are:

* user has not PIN
* authentication was successful. This can be checked with result-value==True and with the detail information, "authentication succeeded against..."

The policy can be

* scope: authentication (like passthru itself)
* action: passthru-assign=*prepin:6* or *postpin:8* or something like this, mean pin prepended and otpvalue 6 digits. (could also be pin:6 oder 8:pin) I would prefer to put this into *one* policy and not two policy definitions.

**Comment by plettich** [comment]
Shouldn't we be able to use the configuration from privacyIDEA (If the admin set the correct values)?

**Comment by cornelinux** [comment]
You mean the default OTP length?

The old tokens could be 6 digits, while they decide to roll new tokens with 8 digits.

Also the prepend or append could change. The old system could append the PIN and they would want to prepend it. (This *probably* will not happen, but... - I think especially the OTP length could change, since they might mix an match - they will probalby also change the token vendor... and thus maybe the OTP length)

**Comment by plettich** [comment]
This makes sense.
