### ISSUE TITLE
Howto install latest stable without hurdle's

### ISSUE THREAD

**Issue by ariedeleen** [privacyidea/privacyidea#163]
Try to install the latest stable privacyidea on a basic CentOS 6.6 64bits installation with no GUI

But git and virtualenv etc...  are not recognized in the prompt (logged in via SSH as user root)
So first you have to install these. Which is not mentioned in the setup.

pip install -r requirements.txt after running this there are lots of red lines because
of missing gcc for example. So this also has to be installed, Then OpenSSl is missing and so on.

After finely taking all these hurdle's privacyidea runs at 127.0.0.1:5000

“Additional configuration can be read from the file /etc/privacyidea/pi.cfg” file not found?

How can it run on an outside address, the external IP like aaa.somedomain.org so other people can login and use it.
There is no GUI installed on the CentOS as imho normally is on a server so cannot login to the webpage.

And are httpd(apache) necessary, MySQL(MariaDB) or free- openradius on the server to use privayidea

We finally like to use privacyidea in a production environment

**Comment by cornelinux** [comment]
git is not needed to install privacyidea.
Using virtualenv is a sensible choice. 
There are several packages needed, when installing in virutalenv. These packages are named different on different distributions.

Well, I also planed to improve installation on some CentOS distris... Probably we should upvote #30.

Per default privacyidea searches for additional configuration in /etc/privacyidea/pi.cfg. This file can be changed in an environment variable.

But probably you want to run PI either in nginx or apache2. 
So may setup a file /etc/privacyidea/pi.cfg and use a wsgi script to run it from apache.

You can use Mysql or PostgreSQL as database.
Config File: http://privacyidea.readthedocs.org/en/latest/installation/system/inifile.html
WSGI script: http://privacyidea.readthedocs.org/en/latest/installation/system/wsgiscript.html

To get an idea about how to configure apache take a look here:
https://github.com/privacyidea/privacyidea/tree/master/deploy/apache

My recommendations would be:
1. Create pi.cfg file with database. Create the database:
    pi-manage.py createdb
2. Run with the new pi.cfg and with the database locally:
    pi-manage.py runserver
3. If everything runs fine in this way, add the app to apache.

**Comment by ariedeleen** [comment]
Thanx for the clarifications and recommendations

installed and started mysql(mariadb), http(apache)
Running: pi-manage.py createdb > database is created
But got this message: python2.7/site-packages/sqlalchemy/engine/default.py:436: Warning: Specified key was too long; max key length is 767 bytes
probably due to max index length

Next in the coming days adding the privacyidea to apache

**Comment by cornelinux** [comment]
What are you doing, when this occured?
Was the database created?
Does it work anyway?
Can you provide the complete traceback?

**Comment by ariedeleen** [comment]
Eventually, the database was populated with tables, indexes, etc.

Is it possible to do something 'django' like ./pi-manage.py runserver 10.0.1.88:5000
So pi runs on an outside IP address other then localhost . To connect to it
without Apache, wsgi.

Traceback:
After the first time creating the database named privacyidea, Character set: utf8(UTF8 Unicode, Collation order: utf_general_ci(UTF8 Unicode) Using MariaDB a drop in for MySQL the error occurs.
Dropped the database and made it again with default Character set and Collation order
no errors after that.

./pi-manage.py admin add admin piadmin@aaa.nl
Gives a warning:
/opt/privacyidea/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:201: SAWarning: Unicode type received non-unicode bind param value '$pbkdf2-sha512$10023$z1lL...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
Admin admin was registered successfully.

Not yet familiar with wsgi, installed the apache mod. Trying to get pi running on the outside.
Now, learning about wsgi running a 'hello world app'  ;-)

**Comment by cornelinux** [comment]
Yes, See the help

   pi-manage.py runserver -h

**Comment by ariedeleen** [comment]
yep, saw that, but could not change ip

Installed  the Privacyidea Docker container in about 3 minutes. To show it to the other IT colleagues.

First tried to install pi in a  virtual environment Python version 2.7. Pi runs after installing a lot of dependencies and adjusting settings. But could not get a compatible mod_wsgi compiled, in a timely fashion. Without errors.

Also tried to install using Python version 2.6.6 in a venv, the default CentOS 6.x version, so the Apache wsgi sock is compatible. But  at the end missing Cypher AES, pip install says it is already installed would you like to upgrade?  Yes, visa versa looping.
So stopped for now to figure it all out.

The main goal was to setup an AAA kind of server, and Privacyidea was on the list
After showing it the verdict is that we are very impressed about Privacyidea and its usefulness. Also the elaborated manual ;-)

keep up the good work

**Comment by cornelinux** [comment]
I plan to solve this with issue #30. 
Maybe you are running some other distribution till then?

**Comment by cornelinux** [comment]
An snapshot RPM for CentOS 7 is ready. Would you like to try this (which will not run on 6.6. Working on 6.6, now, which is a bit more complicated ;-)

**Comment by cornelinux** [comment]
We close this, since it is contained in #31 and #30
