### ISSUE TITLE
Failed to enroll U2F token on latest Chrome

### ISSUE THREAD

**Issue by quynh-axiadids** [privacyidea/privacyidea#1636]
# What did you try to do?

Enroll U2F token on Chrome

# What outcome did you expect?

Being able to enroll U2F token on Chrome

# What outcome did you experience?

Failed to enroll U2F token on Chrome

# Configuration

* privacyIDEA Version: 2.23.5

* Installation method: from source

## more details: 

* OS: Amazon LInux

* Webserver: nginx

* Tokendatabase: postgresql

# Log file

U2F recently fails to enroll with error pop up: "Bad U2F Request / challenge must be base64url encoded"

My Chrome version is Version 74.0.3729.157 (Official Build) (64-bit)

I think this maybe related to this change in Chrome Crypto:
https://github.com/chromium/chromium/commit/ceb92979d1f3a77146ed68f8484636ce63073625#diff-bbd4efb6053a9f322d1ba351e036bd71

I am using PrivacyIDEA 2.23.5. Just want to make sure this is already fixed in 3.0?

Thank you and best regards,

Quynh Nguyen

**Comment by cornelinux** [comment]
@Mipronimo Isn't this something you talked about lately?

**Comment by Mipronimo** [comment]
There is a problem with Google Chrome 72+ and u2f.
The login process works fine with Google Chrome. Only the enrollment fails.

To enroll the token, please use Firefox, but you'll need privacyIDEA 3.0 to do so.

**Comment by tony11375** [comment]
Hi,

Since today, we have the same issue

PrivacyIdea Version : 2.23.2
Chrome Version :  74.0.3729.157 and 75.0.3770.80

By running Chrome with --disable-features=WebAuthenticationProxyCryptotoken it's working again but that not really a fix..

**Comment by joyezp** [comment]
I've the same misbehaviour on MacOS 10.14.6 with Chrome 77.0.3865.90 and privacyIDEA 3.0.1

Working fine with Firefox on the same device

**Comment by cornelinux** [comment]
@joyezp This issue was only fixed in privacyIDEA 3.1

**Comment by Mipronimo** [comment]
> or use firefox

So if you do not want to update, you need to use Firefox to enroll the token, but you can use Chrome or any other browser to login.

**Comment by joyezp** [comment]
Thx

**Comment by joyezp** [comment]
privacyIDEA upgraded to 3.1 and now working fine with Chrome...Have a nice week-end
