### ISSUE TITLE
API-Requests for event enpoint don't get logged to Audit Log

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1660]
Due to the fact that [`after_request()`](https://github.com/privacyidea/privacyidea/blob/12cbb8dfbde6f72849cc81daf04fc52004b2f929/privacyidea/api/before_after.py#L221) is not decorated with `eventhandling_blueprint.after_request`, the requests to the event-Endpoint are never logged in the Audit-Log.

**Comment by fredreichbier** [comment]
Just for the record: also, the responses are not signed because ``sign_response`` is never called.

**Comment by cornelinux** [comment]
@plettich I can do this?
