### ISSUE TITLE
4 Eyes Policy

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#167]
A policy that requires 2 OTP token for authentication. 
This could be devided into 

    <otppin1><otpvalue1><otppin2><otpvalue2>

thus special administrative accounts, that require 4 eyes could be protected.

Implementing this as a policy might be a bit difficult with the current code workflow. Maybe this needs to be  a token type.

**Comment by cornelinux** [comment]
A user "root" would get a 4-eyes-token assigned. The rule for this token would be, that two users from another realm need to authenticate.
Thus this token would contain something like a list:

* n users from realm1
* m users from realm2
* x users from realm3

But how would we identify the users/tokens?

**Comment by itd** [comment]
This feels like it might be used to address concepts like the USAF's "two man rule" or Sarbanes-Oxley conflict of interest or separation of duties controls.  If you think you have a demand for this functionality,  consider realms (version 1) or user@realm combinations (version 3), as these seem to me to me more straightforward to manage in account privilege audits. 

Today, implementing this functionality might be overkill for all but the most paranoid environments. I saw that SQRL might be a consideration for development as well. That seems pretty slick and may have more immediate applications if the SQRL app and client developers are moving forward.

**Comment by cornelinux** [comment]
Thanks for the feedback - which in combination with other comments show me to put some effort into SQRL... :-)

**Comment by cornelinux** [comment]
We are implementing version 1, since this is way cooler ;-)

**Comment by cornelinux** [comment]
This seemed rather simple to implement. This was such a low hanging fruit - i could not resist ,-)

**Comment by fnanninga** [comment]
Are 4eyes tokens meant to work in combination with challenge-response-style tokens? I tried 4eyes with a U2F with little success so far. (The error message was roughly "0 tokens matched", even though the pin was correct.)

**Comment by cornelinux** [comment]
Only Pushbuttons will work.
Please use the google group for such kind of questions.
Thx
Cornelius
