### ISSUE TITLE
csv_generator() of SQLAudit does not sort entries

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1670]
The [`csv_generator()`](https://github.com/privacyidea/privacyidea/blob/059e6b3ef10518595cfb5dfbf3918cc205099d79/privacyidea/lib/auditmodules/sqlaudit.py#L352) function does not sort the audit entries. We should at least sort by timestamp/entry id by default.
Also each entry itself is unsorted due to the fact that python dictionaries are unsorted by default.
We should check if we just output a header with the appropriate column name or sort each line according to the audit view output (or both...).

**Comment by plettich** [comment]
Ordering of the audit entry dictionary is fixed in f55b1bd2

**Comment by NNLemling** [comment]
@plettich I've now looked through several logs and everything is sorted perfectly by date and entry ID. Can you possibly test again yourself whether the problem still exists or it may have already been fixed with your change in f55b1bd2?

**Comment by cornelinux** [comment]
The sorting of the columns is fixed.
Probably the rows are still unsorted.
