### ISSUE TITLE
TokenOwner migration fails with MySQL and non-ASCII UIDs

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1677]
Suppose you are on privacyIDEA 2.23.5 with MySQL, have a LDAP resolver with ``uidtype=dn`` and a non-ASCII UID, like ``CN=Cornelius Kölbel,OU=devel,OU=frankfurt,DC=testfoo,DC=intranet``.

Then, the upgrade to 3.0.1 loses all token assignments, because the TokenOwner migration script fails:

```
Failed to migrate token assignment data!
'utf8' codec can't decode byte 0xf6 in position 14: invalid start byte
```

Unfortunately, this error causes the migration to lose *all* token assignments.

The problem is that flask-sqlalchemy implicitly sets ``charset=utf8`` as a connection option in case of mysql: 

https://github.com/pallets/flask-sqlalchemy/blob/419fa5ec65105866d3f0a1cf9ee6205dc69d6768/flask_sqlalchemy/__init__.py#L873

As Flask-Migrate/alembic do not use flask-sqlalchemy to create the SQL connection, the ``charset`` option is not set in case of the migration script, which causes the above error.

**Comment by cornelinux** [comment]
We can solve this be adding ``?charset=utf8`` to the SQLALCHEMY_URI in pi.cfg before running the schema upgrade. But how could we fix this in the migration script without changing the pi.cfg?
