### ISSUE TITLE
pre-auth-event-handler loops over all token

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1686]
Using a pre-eventhandler with the auth-event (as implemented in #1567), the [`check_condition()`](https://github.com/privacyidea/privacyidea/blob/5f282d70e9201f1638ccfa94217c66760dd4fc4a/privacyidea/lib/eventhandler/base.py#L338) function loops over all tokens (and creates them) causing a significant delay if there are a lot of token in the db.
Since we do not have a user object (yet), the SQL-query generated in [`get_tokens()`](https://github.com/privacyidea/privacyidea/blob/5f282d70e9201f1638ccfa94217c66760dd4fc4a/privacyidea/lib/token.py#L378) matches all tokens.
See also  #1436 / #1645

**Comment by cornelinux** [comment]
How is this a bug?

**Comment by fredreichbier** [comment]
This should be fixed if we implement #1810
