### ISSUE TITLE
Add transaction_id to GET token/challenges

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1689]
Certain tokens (like Push, or maybe tiqr) work better, when a service account can fetch the challenges to verify, if the response was answered correctly.

Thus we should add a parameter ``transaction_id`` to the API endpoint.

**Comment by Mipronimo** [comment]
Wouldn't it be nice, if we also add the `transaction_id` to the /auth endpoint?
That could fix #1684 as well

**Comment by cornelinux** [comment]
Hi @Mipronimo Sounds sensible.
I will open another issue for that.
