### ISSUE TITLE
Allow anonymous LDAP bindings

### ISSUE THREAD

**Issue by 0ip** [privacyidea/privacyidea#169]
As it currently seems, privacyIDEA does not support an anonymous LDAP bind.
Is it possible to add this feature?

**Comment by cornelinux** [comment]
At the moment this is a bit tricky. The "Bind type" is used for query the LDAP and for checking the password of a user. 
If the bind for query the LDAP would be set to ANONYMOUS, the bind type for checking the users password (LDAPResolver.checkPass()) should not be ANONYMOUS ;-)

So there are two possibilities:

1. We add a new bind type "ANONYMOUS" for quering the LDAP. In this case we either
  a) need a logic to determine the checkPass-Bind-Type or
  b) need to add a second variable for the checkPass-Bind-Type.
2. We could allow the BindDN and BindPass to be empty. If they are empty the LDAP Resolver will perform an anonymous bind for quering the LDAP.

2 is a kind of hidden feature in the UI, which is not that user friendly

**Comment by 0ip** [comment]
The second way of solving this issue rather appeals to me, since it seems quite intuitive.
From a user perspective, this was actually my initial attempt, trying to leave these fields blank.

To avoid confusion, one could maybe add a label telling the user the consequence of leaving these two fields empty.

**Comment by cornelinux** [comment]
Hm, this would also avoid the necessity to add the second attribute.

**Comment by cornelinux** [comment]
Just implemented this solution running tests...
