### ISSUE TITLE
token-janitor exports each chunk in a seperate file

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1694]
Currently when using the token-janitor to export token to a XML-File, a separate file is created for every chunk (if the `--chunksize` option is given). This also creates a new MAC-key and AES-encryption-key for each file.

**Comment by cornelinux** [comment]
Works for me.

**Comment by cornelinux** [comment]
Sounds like a hidden feature to me.
You are using chunks if you have maybe 50.000 tokens in your database. 
If you in turn want to import an XML file with 50.000 tokens into privacyIDEA, you will most likely end up with problems in your browser, timeout, whatsoever. So having files with only 1000 tokens will come in quite handy.

If you think, that needs to be changed, please make this configurable and label it as enhancement.
Thanks.
