### ISSUE TITLE
otpauth-URI should specify the user selected hash algorithm

### ISSUE THREAD

**Issue by 0ip** [privacyidea/privacyidea#170]
In order for apps like FreeOTP to recognize a hash algorithm that is different from the current default (SHA-1), the algorithm has to be specified explicitly in the otpauth-URI, that is also used for the QR code [0] [1].

[0] https://github.com/google/google-authenticator/wiki/Key-Uri-Format
[1] https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/apps.py#L73

Example: `otpauth://totp/PI-Serial:testuser?secret=JBSWY3&issuer=privacyIDEA&algorithm=SHA512`

**Comment by cornelinux** [comment]
Google Authenticator does not support SHA512.
I.e. the urls 

otpauth://totp/PI-Serial:testuser?secret=JBSWY3&issuer=privacyIDEA&algorithm=SHA512
otpauth://totp/PI-Serial2:testuser2?secret=JBSWY3&issuer=privacyIDEA

produce the same OTP. (At least on my Android).

So we would have to add a warning to the enrollment, that SHA>1 is not supported with GA.
(This could be done via the normal error boxes)

**Comment by cornelinux** [comment]
This is available as 2.5dev2 at ppa:privacyidea/privacyidea-dev

**Comment by 0ip** [comment]
Thanks a lot for implementing this feature.

I agree, showing a warning message to GA users is good behavior.
Since there is no (official) activity regarding the development of GA, users should switch to FreeOTP anyway. ;)
