### ISSUE TITLE
Getting list of users with tokens

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1705]
**Is your feature request related to a problem? Please describe.**

Sometimes customers want to know which users actually use tokens.
This could be needed e.g. for billing processes, if this and that devision is invoiced an amount of money for 65 users using 2FA.

Possible information could be

* username
* given name
* surname
* last authentication (so that you know, that the user is still active)

Optional fields could be:

* the resolver and realm of the user
* an arbitrary LDAP attribute (to understand, which devision the user is in)
* the number auf assigned tokens (or a list of serials)
* the tokenypes (or a list of serials)
* the number of authentication requests since a certain date

**Describe the solution you'd like**

We should have a script, that can output this information into a CSV file. This then can be processed in a calc sheet desktop app.

**Describe alternatives you've considered**

None. Since this is a time consuming task, I would not put this in the UI.
Or - we would have to use the queue mechanism?
Or - this could be a periodic task and the administrator could then later view the generated report

**Comment by fredreichbier** [comment]
With #1710, we can actually use the token janitor to do something similar:
```
$ ./tools/privacyidea-token-janitor find --action listuser 2>/dev/null
'PISP00009577','spass','user666','','User666','81f5b353-6705-4aad-9e7b-f20a4d5c2bfc','ad'
'PIEM000099F3','email','user123','','User123','7cf7f772-d30d-1036-8008-cd5127ce8b3b','ucs'
'OATH0000608A','hotp','user136','','User136','8cc042ea-d30d-1036-803c-cd5127ce8b3b','ucs'
'PIEM00014670','email','user777','','User777','be74c2fe-d310-1036-8a40-cd5127ce8b3b','ucs'
'PIEM00024FB7','email'
```
the fields being serial, type, username, given name, surname, uid, resolver

and
```
$ ./tools/privacyidea-token-janitor find --action listuser --sum 2>/dev/null
user777||User777|be74c2fe-d310-1036-8a40-cd5127ce8b3b|ucs,1
user666||User666|81f5b353-6705-4aad-9e7b-f20a4d5c2bfc|ad,1
N/A,1
user136||User136|8cc042ea-d30d-1036-803c-cd5127ce8b3b|ucs,1
user123||User123|7cf7f772-d30d-1036-8008-cd5127ce8b3b|ucs,1
```
the fields being username, givenname, surname, uid, number of tokens (but hm, we use a comma to separate the last field?)

**Comment by cornelinux** [comment]
Thats right an cool.
We should fix the "|", "," issue in the ``--sum`` output and also add the lastauth to the list. (if not the sum is used, since "lastauth" is a token specific thing. )
Maybe we can simply specifiy which tokeninfo should be printed...

In addition we should be able to print additional user attributes.

**Comment by plettich** [comment]
Since the question came up recently, does it make sense to add a filter for the realm in the token janitor? This way, if privacyIDEA serves several realms, an admin could gather statistics about each realm individually.

**Comment by cornelinux** [comment]
@plettich Or we could at least add the realm to the output. Then the data could be filtered later in the calc sheet (I want to avoid saying E**el)

**Comment by cornelinux** [comment]
So I think we need to do:

* [ ] Fix the ``sum`` issue and
* [ ] add the realm of the user
