### ISSUE TITLE
Comma not allowed in policy action

### ISSUE THREAD

**Issue by tamaro-skaljic** [privacyidea/privacyidea#1716]
Example:
The title and text of the push token are truncated if a comma exists in the pushauth policy. I think that happens with all policies.
```
Input:
- push_title_on_mobile:
This is a privacyIdea Authentication Request, would you authenticate?
- push_text_on_mobile:
Are you the one, who is trying to verify?

Result:
This is a privacyIdea Authentication Request
Are you the one
```

**Comment by cornelinux** [comment]
Policy actions are separated by commas. So using a comma in an action value results in a new unknown action like *"would you authenticate?".

This is due to the design of the policies and can not be fixed.

**Comment by fredreichbier** [comment]
Until the policy redesign, it might be possible to mitigate this by allowing quoted action values, e.g.
```
push_title_on_mobile="This is a privacyIdea Authentication Request, would you authenticate?"
```
For parsing, we could use ``parse_comma_separated_string``:
https://github.com/privacyidea/privacyidea/blob/680771497a1aceb8b56956d3bb808e661e972d52/privacyidea/lib/utils/compare.py#L51

**Comment by cornelinux** [comment]
This can not easily be done by telling the admin to enter action values in paranthes, since:

~~~~python
parse_comma_separated_string('actionA="Value, B", actionB="Value, C"')
['actionA="Value', 'B"', 'actionB="Value', 'C"']
~~~~

This still would split differently.

So we would have to also store the data in a complete new way.

**Comment by tamaro-skaljic** [comment]
Revisited this issue today and thought: Shouldn't the user input be sanitized (even if it comes hopefully from an administrator who's configured the policy)? The input could be url-encoded, which would replace `,` with `%2C`, among other things. But then you would have to check beforehand whether Android and iOS support urlencoded strings in the title and description of notifications. If not, the text would have to be decoded again before it is displayed by the app.

**Comment by jona-samuel** [comment]
I close this because we have a new issue for this. Please lock at #3667
