### ISSUE TITLE
usability adding yubikey tokens: automatically remove spaces?

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#1735]
I'm adding a new yubikey token and use ykpersonalize and privacyidea's webui. In our documentation https://privacyidea.readthedocs.io/en/latest/configuration/tokens/yubikey.html we have:
(Remove possible white spaces!)
That's something a computer can do very easily - we should allow to use cut&paste without manual editing to avoid possible errors.
* privacyIDEA Version: 3.0.1

* Installation method: ubuntu packages

**Comment by fredreichbier** [comment]
I agree, removing whitespace should (hopefully!) be somewhat easy to implement :-) In the case of the yubikey tokenclass, I would probably implement it in the ``update`` method right before passing the otpkey down to ``TokenClass.update``?

https://github.com/privacyidea/privacyidea/blob/b7fe9ae20cdba41d8c4de1259f204fe4c3ae839d/privacyidea/lib/tokens/yubikeytoken.py#L459

And I guess we would also need to adjust the otpkey pattern here:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.yubikey.html#L41
