### ISSUE TITLE
Users cannot enroll RADIUS tokens in the WebUI if a policy with scope=user is defined

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1749]
Steps to reproduce:
* Define a policy with ``scope=user`` and ``action=enrollRADIUS``
* Log in as a user, click "Enroll token", select RADIUS token
* We get an error "User actions are defined, but the action radiusserver_read is not allowed!"
* Even if RADIUS servers are defined, the dropdown list "RADIUS server configuration" presents no choices
* Hence, we cannot select a RADIUS server, and submitting the form says "ERR905: Missing parameter: 'radius.server'"

This is because the WebUI requests ``GET /radiusserver/`` when the user tries to enroll a RADIUS token. As a side effect of #1495, this endpoint is not allowed for users by default anymore: We would need a policy with scope user and action ``radiusserver_read`` to allow users to retrieve the list of RADIUS servers.

However, such a policy cannot be created via the WebUI.

I guess the right way to fix this would be to add a ``radiusserver_read`` action to the ``user`` scope. Maybe we should also automatically create it in the migration script, like we did for admin policies in #1721.

**Comment by fredreichbier** [comment]
The following Flask blueprints are accessible with an access token with role "user":
```python
@token_blueprint.before_request
@audit_blueprint.before_request
@user_blueprint.before_request
@caconnector_blueprint.before_request
@system_blueprint.before_request
@radiusserver_blueprint.before_request
@privacyideaserver_blueprint.before_request
```

``*_read`` policies exist for ``/radiusserver/``, ``/caconnector/`` and ``/privacyideaserver/``.
* For ``/caconnector``, the policy action is not actually enforced because the decorator is commented out:
https://github.com/privacyidea/privacyidea/blob/259e079472dac0f412f7456f6a4ea7f5475a45b4/privacyidea/api/caconnector.py#L48
This was done in 1c3327273c1d53cd8b21f0bf90a67ec37688bc5b, I guess as a hotfix?
* We should add scope=user policy actions for ``/caconnector/``, ``/radiusserver/``, ``/privacyideaserver/``.

**Comment by cornelinux** [comment]
Do not do this in PR #1765 
We should use an extra endpoint like ``radiusserver_list_names_for_other_purposes`` or as abbreviation: rlnfop.

This way we can avoid, thtat the admin has to define *two* policies.
If the user has a policy "enrollRADIUS" he will also be allowed to read the list (only the names) of radius server definitions.
