### ISSUE TITLE
Allow to modify the truncated length of columns of pidea_audit

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1756]
The lengths of the columns of the ``pidea_audit`` table are hardcoded in the ``audit_column_length`` dictionary in ``models.py``:

https://github.com/privacyidea/privacyidea/blob/96b3e18c63814b771242c1e42cd3ff7109e5b9db/privacyidea/models.py#L2555

If users want to increase the column lengths, they can manually alter the SQL table (see #525). However, if ``PI_AUDIT_SQL_TRUNCATE`` is True (as it is in new installations now), the audit class will truncate fields to the lengths specified in ``audit_column_length`` even if the actual column size might be greater. It would be nice if one could increase the truncated size without having to edit ``models.py``.

I think this could be fixed in two ways:
* We could allow users to overwrite parts of ``audit_column_length`` in ``pi.cfg`` and use these settings in ``models.py`` too. Then, if a user writes
  ```
  PI_AUDIT_COLUMN_LENGTHS = {"user": 40}
  ```
  in ``pi.cfg``, a ``pi-manage createdb`` would create an audit table with an enlarged ``user`` column, and also truncate values accordingly. This way might be tricky, because when we create the models, we do not have access to the Flask ``app.config`` because the Flask app doesn't exist yet. But there might be a way to circumvent that :-)
* Alternatively, we could require users to manually alter the column sizes, and only allow them to overwrite the truncated lengths, e.g.
    ```
    PI_AUDIT_SQL_TRUNCATE = True
    PI_AUDIT_SQL_TRUNCATED_LENGTHS = {"user": 40}
    ```
   which would cause the SQL audit module to truncate the ``user`` field to 40 characters, not 20.

**Comment by cornelinux** [comment]
I think we do not need to use the setting PI_AUDIT_COLUMN_LENGHT in ``pi-manage createdb``. Why? The DB is usually already created, when the user wants to enlarge the column.

So I am totally fine with the process of
1. User alters the column length manually.
2. Notifies privacyIDEA about the alternation.

But I am wondering if we can not determine by code within privacyidea, within the SQL Audit module, how long the column actually **is**.

I know that this is (in regards to the models definition) the wrong approach ;-)
We might also recommend to use another than the default table, if the user actually wants to modify the lenght?

**Comment by fredreichbier** [comment]
I think you're right, we don't necessarily have to modify the column lengths already for ``createdb``.

By some quick googling, there doesn't seem to be a way to determine the actual column length without using commands that are database-specific, but I'll recheck.

Using another table would also be an option -- but currently I don't think there is a way to change the audit table name without changing ``models.py``?

**Comment by plettich** [comment]
> But I am wondering if we can not determine by code within privacyidea, within the SQL Audit module, how long the column actually **is**.

We could initialize the table with:
```
Table('pidea_audit', md, autoload=True, autoload_with=conn)
```
(found on [SO](https://stackoverflow.com/questions/38940682/how-can-i-get-column-name-and-type-from-an-existing-table-in-sqlalchemy))
But if we query the column type we get the SQL Type.

**Comment by fredreichbier** [comment]
Ah, you're right, I missed this :)

This actually seems to work pretty nice with MariaDB at least:
```python
from sqlalchemy import create_engine, MetaData, Table, VARCHAR

conn = create_engine('mysql+pymysql://test:test@192.168.33.101/pi')
meta = MetaData(conn)

table = Table('pidea_audit', meta, autoload=True, autoload_with=conn)
for column in table.columns:
    if isinstance(column.type, VARCHAR):
        print(column.name, column.type, column.type.length)
    else:
        print(column.name, column.type)
```
prints:
```
id INTEGER(11)
date DATETIME
signature VARCHAR(620) 620
action VARCHAR(50) 50
success INTEGER(11)
serial VARCHAR(40) 40
token_type VARCHAR(12) 12
user VARCHAR(20) 20
realm VARCHAR(20) 20
resolver VARCHAR(50) 50
administrator VARCHAR(20) 20
action_detail VARCHAR(50) 50
info VARCHAR(50) 50
privacyidea_server VARCHAR(255) 255
client VARCHAR(50) 50
loglevel VARCHAR(12) 12
clearance_level VARCHAR(12) 12
policies VARCHAR(255) 255
```

**Comment by plettich** [comment]
I'll check with postgres

**Comment by plettich** [comment]
Does work the same with postgres.

**Comment by fredreichbier** [comment]
That's nice!

So I guess the way to go would be to keep the field lengths in the model definition in ``models.py`` for table creation, but use the actual field lengths (as determined above) for truncation?

**Comment by cornelinux** [comment]
I think we will go with this suggestion:

PI_AUDIT_SQL_TRUNCATED_LENGTHS
