### ISSUE TITLE
Creating OTP by admin in case of emergency

### ISSUE THREAD

**Issue by tceydeliler** [privacyidea/privacyidea#176]
Sometimes users can lost phone or OTP token device . Then They cannot connect to company.
In this case PI admin can create OTP for this user by using users token showing on PI web UI.
I dont know it is possible or not but it will be very useful.
Bu this way in some urgent cases,  admin can create token and can share with user via phone , mail depending OTP type.
Regards..

**Comment by cornelinux** [comment]
There is the "lost token" functionality, where the admin or help desk employee can mark a token as lost and the user will get a temporary "token". 
http://privacyidea.readthedocs.org/en/latest/tokenview/index.html?highlight=lost#lost-token

When creating a OTP token (HOTP, TOTP), the seed can also be displayed in clear text. Thus the admin could read the seed to the user on the phone. But I am not sure if I would like that.

Is this what you were looking for?

**Comment by cornelinux** [comment]
To my understanding this already works.
So I am closing this issue.
