### ISSUE TITLE
Revoke all token when user changes password

### ISSUE THREAD

**Issue by vuducanha2** [privacyidea/privacyidea#1769]
How can I create an event: "When a user changes  password, all of the user's tokens will be revoked"

And where the user information is stored in the database, I saw the database model but couldn't find it

Thank you !

**Comment by plettich** [comment]
privacyIDEA only supports rudimentary user management functionality. Usually the users are managed somewhere else (AD, LDAP, ...). So generally a "password changed" event would not be received by privacyIDEA.
If the users are managed with privacyIDEA, a "password changed" event could be triggered but it currently isn't implemented.

**Comment by cornelinux** [comment]
There is also no action "revoke all user's tokens". 
But the non-existing event "password-change" could trigger a script handler and the script could revoke all tokens.

**Comment by vuducanha2** [comment]
Currently I use privacyidea to authenticate (specifically authentication for zimbra email system) and load user  from ldap, users can use TOTP code and app passcode to login, but when users changes  password, these codes are still valid, so it is less secure, I want to create an event when the user changes the password, then all the token of that user will be revoked.

Besides, I also want to get a list of users who used tokens
Thanks for your help

**Comment by cornelinux** [comment]
Just to clarify some wording: We use the word **token** for your e.g. your smartphone app.
The  digit code you are using we call **OTP value**.
If you *revoke your token* you would render your complete smartphone app useless!

You are using zimbra. The zimbra integration uses the privacyidea ldap proxy. We do not know zimbra. But I know that much that the privacyIDEA server has no knowledge of you changing the password.

From what you are telling I assume you are experiencing that you can use an **OTP value** more than once?
This is probably a configuration of privacyIDEA set with the zimbra integration that an **OTP value** can be used for a certain period of time. It could also be, that the zimbra integration sets some auth cache in the LDAP proxy. I would recommend you verify this with zimbra.

**Comment by cornelinux** [comment]
It could be the bind cache here https://github.com/privacyidea/privacyidea-ldap-proxy/blob/master/example-proxy.ini#L101

or the auth_cache here:
https://privacyidea.readthedocs.io/en/latest/policies/authentication.html?highlight=cache#auth-cache

But again: I do not know the LDAP code of zimbra and it could be that these settings are necessary to work with zimbra.
