### ISSUE TITLE
Allow authentication with a predefined JWT

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1773]
**Is your feature request related to a problem? Please describe.**

The API should be usable in a user context without the need for the user to authenticate with a password or with an OTP token.

**Describe the solution you'd like**

The system calling the API could have a JWT for this very user. privacyIDEA could trust certain public keys. The JWT is sent to the ``/auth`` endpoint. With the trusted public key we could check the signature in the JWT and authenticate the user, so that we can issue further API requests in the user context.

**Additional context**

There can be bascially two different approaches to configure this.
1. We add a new loginmode "JWT" to "disable, privacyIDEA, userstore" in the policy WebUI.
    Then we can simply check this in the lib/auth.py::check_webui_user
    However, this would mean that from a certain IP address a user could only **either** authenticate with a password/OTP **or** with a JWT.

2. Similar to the **REMOTE_USER** functionality we could have an additional policy and
   check for a valid JWT *before* we check for the user's password/OTP.
   This probably creates more unpleasant code than the first approach. This would roughly be here:
   https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/auth.py#L242
   ~~~~python
   elif is_jwt_user_allowed(request):
       # check the jwt
   ~~~~

3. We could trust the JWT to directly be used as JWT on the API end points. The check with other
    trusted public keys would be directly done in [check_auth_token](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/auth.py#L369) or ``verify_auth_token``.

    The public keys could be trusted like this in PI_CFG:

    ~~~~python
    PI_TRUSTED_JWT = [ {"public_key":b'-----BEGIN PUBLIC KEY-----\nMHYwEAYHKoZIzj0CAQYFK4EEAC...' ,
                                           "JWT_algorithm":  "RS256",
                                           "restricted_IPs": "...from where",
                                           "restricted_roles": ["User"],
                                           "restricted_realms": ["realm1", "realm2"],
                                           "restricted_ users": ["userA", "userB"]},
                                          { }]
   ~~~~
   This way we can very well define, that a certain IP would be allowed to impersante only Users (not admins) in a given realm. Note: In additional of course all policies are checked.

I prefer version 3, since it keeps all other mechanisms intact.

# Todos

* load the trusted JWT from ``pi.cfg``. 
* in ``verify_auth_token`` iterate through the different possible JWTs. 
* check, if the given JWT confirms with the defined restrictions.

**Comment by fredreichbier** [comment]
Sounds interesting! Just to make sure I understand correctly:
* In versions 1 and 2, a user sends an asymmetric JWT to ``/auth``, privacyIDEA checks the JWT signature and issues a symmetric JWT which the users uses to issue API requests afterwards.
* In version 3, a user directly uses an asymmetric JWT to issue API requests.
Right?

Version 3 sounds quite elegant, but it feels like it replicates parts of the policy concepts: "restricted_IPs" kind of corresponds to the "client IP" field of policies, "restricted_realms" to the "realms" field etc.
Just an idea: I was wondering if we could implement the restrictions on top of policy conditions? We could, for example, add a ``jwtauth`` policy conditions section. Then, we could allow to enroll HOTP tokens with an asymmetric JWT by a policy condition ``scope=user, action=enrollHOTP`` and a condition ``section=jwtauth, key=public_key, comparator=equals, value=MHYwEAYHKoZIzj0CAQ...``?

**Comment by cornelinux** [comment]
1. You are right with the difference between version 1 and version 2.

2. Putting this into policies would probably have a code impact, that seems rather vast. You have the policy logic *and* you need to put this policy logic into the /auth endpoint logic. Sounds to me as if there has to break something ;-)

**Comment by fredreichbier** [comment]
regarding point two: I probably haven't fully understood version 3 :-) But in version 3, would we have to touch the ``/auth`` endpoint at all? If I understand correctly, we wouldn't need to issue a new symmetric JWT, but would directly use the asymmetric JWT for all API requests. In this case, we could modify ``check_auth_token`` to also accept asymmetric JWTs signed by a set of predefined public keys (i.e. authenticate the asymmetric JWT), and then we could use the policy decorators to decide which actions are allowed (i.e. authorization).

**Comment by cornelinux** [comment]
In version 3 a client application would not have call the ``/auth`` endpoint. 
The client application would create a JWT out of thin air and sign it with its private key.
Within the JWT the role and the username like "clientapplication2" would be denoted.

Everything else (policies - what is the user be allowed to do) would work as usual.
You are right, we only need to modify ``verify_auth_token``. And this verification should also contain the check, if this public key (JWT) is allowed to impersonate as "clientapplication2".

**Comment by cornelinux** [comment]
@fredreichbier you are right, we do not need the "restricted_ips", since this would be imho checked by policies. We only need to define, which *user/role* this JWT is allowed to impersonate. Everything else will be ruled by the policies.
We can bind the username that is impersonated to the IP using policies.

Thus the config looks like this:

~~~~python
PI_TRUSTED_JWT = [ {"public_key":b'-----BEGIN PUBLIC KEY-----\nMHYwEAYHKoZIzj0CAQYFK4EEAC...' ,
                                       "JWT_algorithm":  "RS256",
                                       "role": "user",
                                       "realm": "realm1",
                                       "user": "userA",
                                       "resolver", "resolverX"},
                                      { }]
~~~~

We also only need to specify *one* user. If this same JWT would be allowed to impersonate as different users, we can simply add another dict to the list.
