### ISSUE TITLE
Restrict authentication to certain token types

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1774]
Should we allow an application to restrict the authentication to certain token types like:

   https://privacyidea/validate/check?user=hans&pass=secret1234546&type=HOTP

so that the application decides that only hotp tokens should login here? If the user had a tan list or a TOTP token, authentication would not be possible, since privacyIDEA would filter the list of the allowed tokens to HOTP.

# Pros

Usually all these policies should be handled by privacyIDEA. But however, in certain cases privacyIDEA might not have enough information.

An application could have an internal access rule, that certain functions might only be available with a more secure tokentype. This way the application could "force" that the authentication is checked for this token type.

# Cons

If the user would try to authenticate with a "weaker" tokentype, then an attacker could fetch this OTP value and use this OTP value to login to a less restricted area. This means - even if there is token tokentype restriction, we should check the OTP against all token types!

The application could simply authenticate the user inially and check the JSON response of ``/validate/check`` if the *details* contain the correct tokentype and do this decision based on this result. So there would not be any need to enhance the API and allow the application (client) to make the tokentype decision.

@fredreichbier @plettich what do you think?

**Comment by fredreichbier** [comment]
Clients can simply check the response of the ``/validate/check`` request and read the token type from here.
