### ISSUE TITLE
Add setup instructions for nose the README

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#1779]
The current README section on running the tests is a stub. It should provide instructions for installing the additional requirements for running the tests.

**Comment by cornelinux** [comment]
@NuvandaPV Could you please point to the location you are talking of? Are you talking about line 140 in toplevel README.rst?
I think we provided the necessary information --- although most of us are now using ``py.test``.

**Comment by fredreichbier** [comment]
Whoops, I think the README is missing the ``pip install -r tests/requirements.txt`` step :)

**Comment by cornelinux** [comment]
and we probably should replace nosetest with py.test?

**Comment by NuvandaPV** [comment]
Added a PR to add the missing instructions. I haven't replaced nose with py.test for now, since that will need to be changed in other places as well. Discussion in #1787

**Comment by fredreichbier** [comment]
fixed by #1786
