### ISSUE TITLE
Replace nose with py.test in the documentation

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#1787]
Most developers on our team use py.test to run the tests these days, however the documentation still references nose.

**Comment by NuvandaPV** [comment]
related #1779

**Comment by NuvandaPV** [comment]
Should we make this change? Is is a problem if our users continue to rely on nose, because that is what is used in the documentation?

**Comment by NuvandaPV** [comment]
paging @cornelinux @fredreichbier

**Comment by NuvandaPV** [comment]
https://www.privacyidea.org/privacyidea-development-howto/ also still references nose.

**Comment by fredreichbier** [comment]
Good point! I think officially switching to pytest would be nice, because we also use it on Travis, and because it has some nice features that we could use in the future.
I don't think this would cause too much trouble for our users, I'm not sure how many people locally run tests anyway :)
