### ISSUE TITLE
Log-in with any, or without, password when Openldap resolver and entryUUID as UID Type

### ISSUE THREAD

**Issue by izav** [privacyidea/privacyidea#179]
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

Ubuntu Privacy Idea packages installed:
ii  privacyidea-apache2                 2.5-1trusty                      all          two-factor authentication system. This is a meta package to install privacyidea with apache2
ii  privacyidea-pam                     2.5-1trusty                      all          PAM module for privacyIDEA, OTP authentication.
ii  privacyidea-radius                  2.5-1trusty                      all          FreeRADIUS module for privacyIDEA, OTP authentication
ii  privacyidea-simplesamlphp           2.5-1trusty                      all          SimpleSAMLphp module for privacyIDEA to do two factor authentication
ii  privacyideaadm                      2.5-1                            all          admin client for privacyIDEA
ii  python-privacyidea                  2.5-1trusty                      all          two-factor authentication system e.g. for OTP devices

Hi,
I was playing with PrivacyIdea and all seems to work pretty well until... i was able to log as any existing user with any (but wrong) passwords or without any at all.
Then i was able to enroll tokens as if i was the real user and heritate his rights with the "spoofed" token.

When searching any clue about this behavior, i saw that the UID type filled was responsible for. Once modified from "entryUUID" to "uid" i was not anymore able to log as any user with any or no characters.
This entryUUID was got by selecting the "Preset Openldap" button.

Looking at tcpdump traces of ldap requests in  simple mode to see content, i saw the right user password (in clear text for my tests) within the bindrequest even if not filled at all when i was logging as any existing user...

Regards

**Comment by cornelinux** [comment]
Hi,
you are talking of the Web UI login?
Is this your default realm?
Are you running openldap in the background?
Do you have any policies set up?

The UID Type is only used for assigning tokens. Logging in to the WebUI does not bother about the UID Type.
So we have to dive into to get to the problem.

THanks and kind regards

**Comment by izav** [comment]
Hi,
Thanks for your quick answer.
Yes i'm talking about the web ui login. It is the default realm yes. Openldap is running and well connected as users are listed as expected. There is some policies i can give tomorrow when back to work if needed. Your comment about uid type is confusing me as it is the only thing that changed when working and not and i can reproduce as i desired.
Yes we have to dive into to identify the problem. Let me know what you need to go ahead.
Kind regards

**Comment by cornelinux** [comment]
Let's start by looking at the policy. 
Then we can increase the debug level in pi.cfg and take a look at privacyidea.log.
http://privacyidea.readthedocs.org/en/latest/installation/system/logging.html

**Comment by izav** [comment]
Hi, 
There is two active policies right now, a UserPolicy that permit to enroll only Htop + pin length and a WebUi Policy that force users to log with ldapresolver userstore password.

About the logs, i got when ok and when ko but they are too verbose to post here...
Let me know how to proceed.

Regards

**Comment by cornelinux** [comment]
You can send the log via the google group https://groups.google.com/forum/#!forum/privacyidea or directly to my email cornelius(at)privacyidea . org.
