### ISSUE TITLE
Allow description or extended notes on policies

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1814]
There can be a lot of policies. And sometimes you are wondering, why there is a policy.

We might allow to add "notes" or "description" to policies. This would be something like an internal documentation:

"This policy adds the user-details to the response. This is needed for the connected benno mailarchive. Otherwise login will not be possible. Do not delete this policy!"

I am not quite sure, if we should do such things, because it is somehow also a documentation. And the system should not be documented within the system itself.

#2146

**Comment by fredreichbier** [comment]
I see your point about not wanting to document the system inside the system, but nevertheless, I feel like a "notes" field for policies might actually be a nice feature!

**Comment by NuvandaPV** [comment]
It might be useful to have a generic system for documenting anything within PrivacyIDEA. However that is a rather large undertaking.

**Comment by cornelinux** [comment]
This is a good idea, I split this.

**Comment by jona-samuel** [comment]
- [ ] New db model
- [ ] Update policy
       - [ ] web UI
       - [ ] set policy
       - [ ] Get policy
-[ ]New docu

**Comment by jona-samuel** [comment]
I will create a new database table with five attributes: object_type, object_id, timestamp, user and text. The database entry will be used like a normal db entry from the policy table.
A new field in the WebUI will be where the user can set the description.
