### ISSUE TITLE
error enrolling token is entryUUID is empty in ldapresolver

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#183]
- UID Type: 389-ds doesn't have entryUUID, so I used DN. According to
  https://bugzilla.redhat.com/show_bug.cgi?id=220222 one might use
  nsUniqueId, but I didn't like seeing 'random numbers' as identifiers.

After that I have my LDAP users available in privacyidea.  Maybe it's
nteresting for other users to have this documented somewhere.

If you try to use UID Type 'entryUUID' with 389-ds a resolver test works
fine (it find's the correct users), but when I try to assign a token I get
"ERR905: The user can not be found in any resolver in this realm!".
It might be useful to have the resolver test warn if all ID fields are
empty.

[I run Ubuntu 14.04 with the packages from
http://ppa.launchpad.net/privacyidea/privacyidea/ubuntu]

**Comment by cornelinux** [comment]
In the LDAP-Resolver we should add the testing of the uidType into::

    @classmethod
    def testconnection(self, param):
