### ISSUE TITLE
How to modify the IP address monitored, can you modify it to 0.0.0.0?

### ISSUE THREAD

**Issue by leehomkey** [privacyidea/privacyidea#1832]
To address general questions about the usage of privacyIDEA, we run a distinct forum, where you can discuss your problems in regards to installation, setup or configuration.
Please go to: https://community.privacyidea.org.

The github issues are not meant for such questions.
If you still think, that you encountered an issue, that needs a fix or change in the code, you are welcome to file an issue!

How to modify the IP address monitored, can you modify it to 0.0.00？
Which configuration file to modify?

**Comment by cornelinux** [comment]
I am sorry, it is not clear what you mean with "monitored".
This is obviously a topic for the forum.
