### ISSUE TITLE
'Pass if user has no token' bug?

### ISSUE THREAD

**Issue by 0ip** [privacyidea/privacyidea#185]
Having set 'Pass, if the user has no token' to true in the settings pane, authentication still fails (SSH/PAM RADIUS module).

The audit log entry ("/validate/check") correctly notes that "The user has no tokens assigned", yet reports success "0".

pI version is 2.6dev0

**Comment by cornelinux** [comment]
So can the user login when he has no token?

Is the the audit entry (success=0) wrong, which should be (success=1)

**Comment by 0ip** [comment]
Since `pam_radius_auth.so` is required in the testing PAM setup, the user cannot login.
I upgraded to version 2.6dev4, but it didn't make a difference.

To avoid confusion, here's a screenshot of the log entry:
![audit_entry](https://cloud.githubusercontent.com/assets/757230/9699461/6db38c60-53e4-11e5-8f39-d6c1b3396073.png)

**Comment by cornelinux** [comment]
What was the expected behaviour?

Which policies do you have defined?
Which resolvers and realms?

Please test also to authenticate via /validate/check?user=...&pass=...

**Comment by 0ip** [comment]
If a user who has no configured tokens yet wants to login via SSH into a machine, it should be possible to do so by only entering the first factor, i.e. the password and leaving the token/second factor prompt blank.

A standard realm with an associated LDAP resolver is defined. However, no polices are specified.

/validate/check response:

```
{
  "detail": {
    "message": "The user has no tokens assigned"
  }, 
  "id": 1, 
  "jsonrpc": "2.0", 
  "result": {
    "status": true, 
    "value": false
  }, 
  "version": "privacyIDEA 2.6.dev4", 
  "versionnumber": "2.6.dev4"
}
```

**Comment by cornelinux** [comment]
You are right. How does the policy look like?

But: if you want the user to authenticate with his ldap password, if he has no token, you should not use "passifnotoken", but rather "passthru".

"PassOnNoToken" would allow access completely independent on the entered password!!!

"passthru" would require the LDAP password, if the user has no token.

**Comment by 0ip** [comment]
I guess in my case, using PAM, "passthru" would only lead to having to enter the password twice.
```
...
auth       substack     password-auth
auth       required     pam_radius_auth.so prompt=Token
...
```

**Comment by cornelinux** [comment]
Right. Then PassOnNoToken is the right choice.

Anyway - how does your policy look like?
Take a look at Configuration->System->System Documentation.

Please paste all your authentication policies.

**Comment by 0ip** [comment]
Thing is, I haven't defined any policy. I thought that setting this option "globally" would work too.

Hence:

```
System Base Configuration
-------------------------
PassOnUserNoToken: **1**
```

If I define a policy, which I just tried, it works. But still, I would expect the same outcome if I set this option globally, in the system config.

**Comment by cornelinux** [comment]
Interesting. PassOnUserNoToken and PassOnUserNotFound is simply not implemented. ;-)
This is a remainder from version 1.5, which was an inaccurate hammer. This is why in version 2.x this functionality went into the policies, where you can define this action per Realm, per client or whatever.

I will remove these config settings from the system config...

**Comment by 0ip** [comment]
I'm glad this is resolved, thanks a lot.
