### ISSUE TITLE
Fix JSON content detection

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1850]
While working on #1616 i broke the [`_get_response_content()`](https://github.com/privacyidea/privacyidea/blob/a128999d61f7d6fed114ed371528ab7d766be4d8/privacyidea/lib/eventhandler/base.py#L303) function in 3fdac34.
In case a response does not contain any JSON data, this would result in an error.
This would happen if a post-event was bound to an endpoint like `/validate/radiuscheck`.

**Comment by plettich** [comment]
This also affects #1844

**Comment by plettich** [comment]
Actually it seems like this never really worked. An event-handler on the `token_list` endpoint will fail in case `outform=csv` is given as a parameter. There will be no JSON-data to parse in the Response object.

**Comment by cornelinux** [comment]
``send_result`` should per default send application/json.
In other cases the mimetype should be set where it is used.
