### ISSUE TITLE
LDAP UserId resolver not being saved

### ISSUE THREAD

**Issue by Puneeth-n** [privacyidea/privacyidea#1857]
Hi,

I am experimenting with LDAP UserID resolver. I have an AWS Microsoft AD running and I after entering the LDAP details, I can see that test passes but when I try to save the resolver, I see that no resolver has been saved.

privacyIDEA version: 3.1

![Screen Shot 2019-09-18 at 3 59 24 PM](https://user-images.githubusercontent.com/5619473/65155701-0a706680-da2e-11e9-8b46-18603195af4b.png)

Best,
Puneeth

**Comment by plettich** [comment]
Hi,
unfortunately we need some more information.
Please have a look at the [bug report issue template](https://github.com/privacyidea/privacyidea/blob/master/.github/ISSUE_TEMPLATE/1-bug_report.md) for more information.
At least the privacyidea log-file with the interesting part ("Save resolver") would be helpful.

**Comment by cornelinux** [comment]
@Puneeth-n How do you know, that the resolver has not been saved? In addition to @plettich comments please also take a look in the audit log. There you should see an  entry like ``POST /resolver``.

Please note: Testing the resolver does not save the resolver. You need to save it explicitly after a successful test!

**Comment by Puneeth-n** [comment]
@cornelinux I clicked on save and when I went to the list of resolvers, it wasn't there. in the network tab, I saw that also in the mysql tables that there were no entries.

The ldap resolver is not saved when it is named "test" for whatever reason. When I give the ldap resolver a different name, it works.

See the screenshots below.

![Screen Shot 2019-09-19 at 11 18 04 AM](https://user-images.githubusercontent.com/5619473/65231146-663efc00-dacf-11e9-94d9-a7db8383cf45.png)

![Screen Shot 2019-09-19 at 11 18 18 AM](https://user-images.githubusercontent.com/5619473/65231177-735beb00-dacf-11e9-9929-80be2041f6f2.png)

**Comment by cornelinux** [comment]
Hi  @Puneeth-n 
The name "test" is a reserved word indeed and you can not create resolvers with the name test.
Sorry for the missing documentation!

**Comment by plettich** [comment]
maybe we should not activate the `save` button if the name is a reserved word.

**Comment by cornelinux** [comment]
In this case this is actually the only possibility to do it in the UI, since 

    POST /resolver/test

is a dedicated endpoint, that tests a resolver while

    POST  /resolver/<name>

creates and saves a resolver. So we do not have the chance to check the reserved word in the backend.

**Comment by plettich** [comment]
Fixed in #1890
