### ISSUE TITLE
Versioning for Angular-Components

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#1871]
It would be nice to have some sort of versioning for the Angular components, to allow for reliable cache invalidation on updates.

**Comment by NuvandaPV** [comment]
Related #1860 #1261

**Comment by NuvandaPV** [comment]
Paging @cornelinux @fredreichbier

**Comment by NuvandaPV** [comment]
Versioning the components will require employing a slightly different approach from the use we use to version our css and js, since the urls to call are generated on the client. If we want to use the same versioning scheme we use for the server-side versioning, we have to send the last modification timestamps for all of Angular's views to the client (possibly as hidden fields in `footer.html`). Alternatively, we could use `privacyideaVersionNumber`, falling back to generating a random string, if the version number is not set, to make sure caches are invalidated every time when a user runs pre-release software.

**Comment by fredreichbier** [comment]
I think some kind of versioning for the Angular templates would be nice, especially for development: I've often had the situation that caches were not properly invalidated.

My 2 cents: I guess using ``privacyideaVersionNumber`` would be pretty easy and this would probably already solve the problem for endusers. But we would still have the same problem during development -- not sure how we should approach that. Maybe we could detect client-side if we're using a ``devX`` version and append a random query string, effectively disabling the cache?

**Comment by cornelinux** [comment]
@NuvandaPV Is this closed by the latest PR?

**Comment by NuvandaPV** [comment]
Yup.
