### ISSUE TITLE
Add package management for the webui

### ISSUE THREAD

**Issue by INuvanda** [privacyidea/privacyidea#1886]
We currently have no package management for modules used in the webui. Because of this, we tend to use older versions of modules and we have no central way of managing the dependencies of the client.

It would be nice to manage the client-side dependencies using npm. This would allow us the centrally manage out dependencies, however an it would add an extra step and extra complexity to the build process. We also have to make sure, that there can be no issues due to the availability of the npm-service.

To ensure the reliability of our productive installations, we should download all required packages as part of the build process and include them in our packages, this way we can use npm to manage our dependencies while maintaining full control of the application we actually ship.

Since we are also considering replacing AngularJS, it could be sensible to do this as part of a larger rewrite of the webui.

**Comment by cornelinux** [comment]
* [ ] Add update script to the Makefile, so that it can be called something like ``make update-contrib``

**Comment by cornelinux** [comment]
@plettich please merge your cool script to update an move the contribs to the corresponding location
