### ISSUE TITLE
Create policy button should be disabled when no scope is selected

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#1888]
Currently the button to create a policy is enabled as soon as the user has given the policy a name. However, if the user clicks the button before selecting a scope, the code will run into an exception. No error message is shown to the user, so from the users perspective, the button will have no function whatsoever. We should make sure the button only gets enabled, when a policy can actually be created.

**Comment by cornelinux** [comment]
Actually, when no scope is selected, we do not have any actions available. So this would not work anyways.

Also: The element we use ``isteven-multi-select`` does not support "require" or form validation out of the box. So we would have to work on this anyways. And I think we should rather put effort in changing the used multi-select or update the underlying angular version or framework, then working around this.

I keep this open, as a reminder for the UI overhaul.
