### ISSUE TITLE
how to use certificate token for authentication?

### ISSUE THREAD

**Issue by yangboyd** [privacyidea/privacyidea#1891]
how to use certificate token for authentication?
After download the certifcate, how to use it for the api /validate/check?
Or web ui login?

**Comment by cornelinux** [comment]
Please note: This would be a perfect question for https://community.privacyidea.org!

You do not use it at all in the normal workflow. You use a client certificate to do a mutual TLS authentication. You usually would use it with another application like your VPN.
If you want to use it on a webserver, you need to consult the webservers documentation to do *mutual TLS auth*.
