### ISSUE TITLE
Improve spellchecking in development process

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1895]
We can improve spellchecking in the development process and use e.g. ``codespell`` for this.

There are typos!

~~~~bash
~/src/privacyidea (git)-[master] % codespell privacyidea/lib/*.py
privacyidea/lib/crypto.py:816: lenght  ==> length
privacyidea/lib/machine.py:199: addtional  ==> additional
privacyidea/lib/policydecorators.py:405: succesful  ==> successful
privacyidea/lib/policydecorators.py:414: succesful  ==> successful
privacyidea/lib/policydecorators.py:418: successfull  ==> successful
privacyidea/lib/radiusserver.py:55: fomr  ==> from, form
privacyidea/lib/resolver.py:315: abreviated  ==> abbreviated
~~~~

We could e.g. add this as a make directive. Or even put this in front of the translate directive.

hm - I am missing an infrastructure label?

**Comment by cornelinux** [comment]
@plettich check if it is possible to add this e.g. as comment in a pull request.

**Comment by plettich** [comment]
Unfortunatly there is not github integration for codespell. We could add it to a travis test or github actions but this would mean either pass or fail. There won't be a comment on the PR-Page.

**Comment by plettich** [comment]
Would this work?
I'm working on a GitHub action using reviewdog: https://github.com/plettich/action-codespell

![Bildschirmfoto von 2020-02-10 13-30-22](https://user-images.githubusercontent.com/37443810/74150215-bbf47c00-4c09-11ea-8bd2-0d3de84ddf14.png)

**Comment by cornelinux** [comment]
Any note about possible typos would totally work for me. Then the commiter or reviewer can decided, if this is legit and action needs to be taken.

**Comment by plettich** [comment]
So i'll go forward with adding this as a github workflow. Still have to figure out how to configure this correctly (avoid spell checking in .po files).

**Comment by cornelinux** [comment]
cool, thanks!
