### ISSUE TITLE
Add some diagrams to the documentation

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#1914]
It would be nice to have a few diagrams in the documentation. Specifically I think a deployment diagram giving an example for the components involved in a typical use of push tokens, as well as sequence diagrams for the three authentication modes would be nice.

**Comment by cornelinux** [comment]
This would be great.

It would be great if we could do a structural apptoach. I think there is a markdown extension to do diagrams.
(To avoid to actually *draw* stuff)

**Comment by plettich** [comment]
Do You mean the readthedocs documentation or the guthub docs?
RTD uses reST and github Markdown.
[PlantUML](http://plantuml.com/) looks promising. It works with [Markdown](https://blog.anoff.io/2018-07-31-diagrams-with-plantuml/) and [RestructuredText](https://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/UsingGraphicsAndDiagramsInSphinx.html).

**Comment by NuvandaPV** [comment]
I was mainly referring to RTD. PlantUML is the approach I am favoring as well. I have written a few diagrams locally. I am not sure on the best way to add the though.
Apparently readthedocs.org has recently gained the ability to render PlantUML, however it is woefully undocumented (see [this issue](https://github.com/readthedocs/readthedocs.org/issues/3885)).

**Comment by NuvandaPV** [comment]
We have decided to have readthedocs render the diagrams through its internal plantuml support. This will require some changes to how readthedocs is configured in our project.

**Comment by NuvandaPV** [comment]
depends #1958
