### ISSUE TITLE
Move to new dependency injection syntax

### ISSUE THREAD

**Issue by INuvanda** [privacyidea/privacyidea#1917]
We should replace Angular's old, deprecated dependency injection syntax with the new one.

**Comment by cornelinux** [comment]
Should we move this to milestone 3.3.?

**Comment by NuvandaPV** [comment]
I had hoped we could get this in now-ish, while there are relatively few PRs in-flight. But I can also wait until after the release, and then rebase my fork on that, if you think that would fit us better.

**Comment by cornelinux** [comment]
I am not quite up-to-speed. I remembered a concept of Paul lately and might be mistaken. Lets talk to assure that/if we put it in 3.2.

**Comment by NuvandaPV** [comment]
Sounds like a plan. Are you there Monday afternoon?

**Comment by cornelinux** [comment]
I think we decided for 3.2, now, right?

**Comment by cornelinux** [comment]
@NuvandaPV I think this would only be done after the first plugin is read for webauthn?

**Comment by NuvandaPV** [comment]
This is actually unrelated to WebAuthn.

**Comment by cornelinux** [comment]
Right. Ack. Just a question of priorities.
