### ISSUE TITLE
Add qr code to enroll privacyIDEA Authenticator

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1919]
In the HOTP, TOTP, PUSH enrollment page we could add a QR code, that links to the Play Store and App Store to install the privacyIDEA Authenticator.

How it would be added is to be discussed.
This should be configurable.

**Comment by cornelinux** [comment]
The link could be customizable to custom apps.

We could also have a QR code to a link of a website, that checks, if this is and iOS or Android device and then sends the phone to the corresponding store.

Todo: Do some concept

**Comment by cornelinux** [comment]
As it is an enrollment page in the UI, we can add webui policies.

* scope: webui
* action:
   * app_url_android: default: https://play.google.com/store/apps/details?id=it.netknights.piauthenticator
   * app_url_ios: default: https://apps.apple.com/de/app/privacyidea-authenticator/id1445401301

If the policy is set and a URL is configured we can add the QR Code of the URL in the rollout page.

**Comment by plettich** [comment]
Should we then display both QR-Codes (along with the Token)? What if people want to use a redirect-page based on the OS (only one URL/QR-Code)? Maybe we (privacyIDEA) can provide a redirect service for our apps.

**Comment by cornelinux** [comment]
Interesting aspect with the redirect.
The question is, if the smartphone can actually the privacyIDEA server. They could be in a different network. -> The smartphone would need to reach a public available redirect service. 

So the simple way could be: provide two QR codes.

The elegant way would be: provide one QR code -> redirect -> go to real app stores.

But after all the elegant way could be different in any situation.
So if s.o. wants to change the default URLs, he could also use the his own redirect service.
Could this mean, that we only need to configure *one* URL, the redirect service?
And if this is not configured, we simply display the two default QR codes. (I would like this, it sounds straightforward and works out of the box. "If you know what you are doing, you can configure your own URL".)

**Comment by plettich** [comment]
Actually i meant our own privacyIDEA webserver for the (default) redirect service :-) The privacyIDEA server should not do this.
Of course customers might want to add links to their version of the (Android/IOS) App.

**Comment by cornelinux** [comment]
Ah, you mean privacyidea.org/redirect-to-app-play-store.html ?

Cool. This would mean so much traffic on our webpage and we would know, how many smartphones are using our app. and where.

Interesting approach - but from a data protection /privacy perspective I would rather not do this. Let's try to avoid running any central service that is need for privacyidea instances to work. Just my personal feeling.

**Comment by plettich** [comment]
I do feel the same :-) And yes, statistics would be great ;-)
Anyway, this would be an additional option. We could provide an apache configuration which does the redirect based on the OS.

**Comment by cornelinux** [comment]
> We could provide an apache configuration which does the redirect based on the OS.

Might be a topic for another issue.

I would like to keep this straightforward. My original goal was to have a possibility to "tell" the users about privacyIDEA Authenticator, which they currently might not be aware of.

So I think we should do something like this:

1. One webui policy with only a checkbox to display the QR code to the *default* privacyIDEA Authenticator for Android with the default URL.
2. One webui policy with only a checkbox to display the QR code to the *default* pI Auth for iOS...

Thus the admin can decide, if the use Android, iOS or both.
And then...

3. one webui policy with the URL(string), where they can give their own URL. Maybe this is a redirector URL, maybe this is a URL to their customized Authenticator, maybe it is a Link to a webpage containing more information for their Authenticator(s). I would not put to much logic in here. Since if they have their own customized Authenticator, customizing the URL is the smallest effort ;-)

I think having these 3 options makes it easy for 90% who are using the normal authenticators and flexible for 10% who might go for customization.

I will implement it this way in scope=webui:

1. action (bool): show_android_privacyidea_authenticator
2. action (bool): show_ios_privacyidea_authenticator
3. action (string): show_custom_url

**Comment by cornelinux** [comment]
The implementation will put the qr codes next to the helptext.

![image](https://user-images.githubusercontent.com/1908620/74603831-01a4bf00-50b8-11ea-9db4-b8bf46763f3f.png)

Depending on how many qr codes are configured, the helptext will span to 1/4, 2/4 or 3/4 of the width.
