### ISSUE TITLE
machineresolverconfig table is not cleaned up

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#1927]
When a MachineResolver is deleted in the webui, the corresponding entries in the machineresolverconfig table are not removed, their resolver_id will be null'd, but the rows themselves are never removed.

**Comment by cornelinux** [comment]
We have the same problem with resolverconfig. And probably a lot of others.

I am wondering if this is due to this change: 60282189525d920cc1c1b4ba3f6fa81c9a12fef1
Where we removed "probably" double relationsships, but these might have been necessary for deleting objects and its *related* entries.

**Comment by cornelinux** [comment]
As I think this affects "all" parameter tables, I changed this to ``Prio:High``

**Comment by cornelinux** [comment]
Hm, it works for *resolverealms*, these are deleted, when the *realm* is deleted.
*tokeninfo* is deleted, when *token* is deleted.

**The *resolverconfig* is also not deleted, when a resolver is deleted!**
so, todo:

* [ ] fix machineresolverconfig
* [ ] fix resolverconfig
