### ISSUE TITLE
No Phone input field in SMS Token enrollment

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1929]
Due to a mixed up element in PR #1791 the input field for the phone number is disabled for users.

**Comment by cornelinux** [comment]
Oh right. This would mean, the user would not be allowed to enter a phone number. 
Who reviewed this one! :-(
So we do this in branch-v3.1

**Comment by cornelinux** [comment]
Todo: Merge the 3.1 branch into master
