### ISSUE TITLE
Set radius timeout/retries

### ISSUE THREAD

**Issue by maxbeth** [privacyidea/privacyidea#1931]
privacyidea didn't set the timeout/retries values to pyrad.
Therefor a user with a lokal TOTP or HOTP and a -offline- external radius can't login.
Same PIN on both Tokens.

**Comment by cornelinux** [comment]
So you mean a user has a RADIUS token and an HOTP token. I *think* the default timeout for the RADIUS would be 30 seconds? So this means it would also take the HOTP value to actually not return earlier than 30 seconds. OK and if the timeout of the application talking to privacyIDEA is less than 30 seconds, then this application will time out *before* privacyIDEA will answer.

Is this the scenario you mean?

Having a RADIUS token **and** and HOTP token is usually a rather uncommon scenario. Why is that with you?

**Comment by cornelinux** [comment]
The RADIUS request is created here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/radiustoken.py#L497

The pyrad code looks like this:
https://pyrad.readthedocs.io/en/latest/_modules/pyrad/client.html#Client

It actually has not interface to set the timeout. So maybe we would need to be hard:
~~~~python
srv = Client(server=r_server,
                         authport=r_authport,
                         secret=to_bytes(radius_secret),
                         dict=Dictionary(radius_dictionary))
srv.timeout =  int(get_from_config("radius.timeout") or 5)
srv.retries = int(get_from_config("radius.retries") or 1)
~~~~
