### ISSUE TITLE
Make remote_user policy aware of split@Sign parameter

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1954]
The [`is_remote_user_allowed()`](https://github.com/privacyidea/privacyidea/blob/eb0000f2c54b37c75b715e536eb23749ac487543/privacyidea/api/lib/prepolicy.py#L1153) policy does not respect the [`split@Sign`](https://privacyidea.readthedocs.io/en/latest/configuration/system_config.html#splitatsign)-configuration. See also #1808

**Comment by cornelinux** [comment]
Check this in 3.4
