### ISSUE TITLE
Allow headers in HTTPSMSProvider / REST API

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1963]
Some SMS gateways nowaday provide a REST API, which e.g. use a bearer token in the HTTP header.
(e.g. See https://docs.spryngsms.com/?version=latest)

Currently the HTTPSMSProvider does not allow to set HTTP headers.
We should be able to also talk to such SMS Gateways either by adding a new SMS Provider or by enhancing the HTTPSMSProvider to allow headers.

**Comment by laclaro** [comment]
One has to wonder, where we would like to store the additional information in the database.
Currently we only have options in the table smsgatewayoption. Two solutions:
1. add a column "type" with values "option" or "header" to table smsgatewayoption
2 create a new table smsgatewayheader

**Comment by cornelinux** [comment]
1. With adding a column "type" we would either have to have a default ("option") or we need a migration script. Sounds good.
2. The new table sounds good. But adds more database structure.
3. We should not do this. Very bad experiences with naming schemes in values!

So we can discuss either 1 or 2. I think solution 1 is more generic, since it can work for all gateways.

**Comment by laclaro** [comment]
Option 1 is indeed more generic. At the moment, the additional options are only used by the http provider.
The parameters in smsgateway.option_dict contain a set of required keys per provider and additional custom keys. If we now put headers and options in this dict, we would have to change this structure e.g. by adding an identifier ("base", "option", "header"), maybe like

`smsgateway.option_dict = {"key1":"value1", "options":{}, "headers":{}}`

Any better way?

Best,

Henning

**Comment by laclaro** [comment]
To get an idea about the "new table" approach: https://github.com/privacyidea/privacyidea/pull/2213
