### ISSUE TITLE
Inconsistency between documentation and implementation for API POST /smsgateway¶

### ISSUE THREAD

**Issue by tatepoon** [privacyidea/privacyidea#1976]
Documentation states that the JSON Parameters includes option**s**.*
https://privacyidea.readthedocs.io/en/latest/modules/api/smsgateway.html

However, the implementation uses option.*
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/smsgateway.py
```python
for k, v in param.items():
        if k.startswith("option."):
            options[k[7:]] = v
```

**Comment by plettich** [comment]
Thanks for the notification, we'll fix this in the next update.
