### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by privacyidea** [privacyidea/privacyidea#2]
The sqlaudit module has a memory leak.

monitoring the process with htop
start paster with mysql database
run 10000 requests with a passwd user with an SPASS token: $ ab -n 10000 -c 2 http://127.0.0.1:5001/validate/check?user=corny\&pass=test

With the sqlaudit module active the consumed memory will increase from 100MB to 1200MB. The memory will not be freed.
Owner
privacyidea commented on 16. Mai

This Problems does not seem to be connected to the sqlaudit module. Even when deactivating the audit and the policies in the validate controller, the memory is leaked.
privacyidea referenced this issue on 16. Mai
Closed
remove dictionaries and __del__ #5
Owner
privacyidea commented on 18. Mai

We change this to be a known issue.
With closing #5, a setup with Apache and MySQL only eats up 23MB when doing 10.000 authentication requests.

We assume this to be tolerable at the moment, especially due to the fact, that the apache will be reloaded once a day for log rotation.

**Comment by cornelinux** [comment]
running with flask

   ./manage runserver

and issuing several requests after each other:

    ab -n 1000 -c 1 http://127.0.0.1:5000/validate/check?user=corny\&pass=test

The memory consumption is fixed at 174MB.
