### ISSUE TITLE
SAWarning: Unicode type received non-unicode bind param value xxxxx

### ISSUE THREAD

**Issue by mfgamma** [privacyidea/privacyidea#200]
hi

after install following github instruction ,running the tests
nosetests -v --with-coverage --cover-package=privacyidea --cover-html

gives a lot of warnings: SAWarning: Unicode type received non-unicode bind param value xxxxx
 see below

is it ok to live with it?

thnaks and best regards

/root/c9sdk/privacyidea/penv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: 
SAWarning: Unicode type received non-unicode bind param value 'testadmin'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/root/c9sdk/privacyidea/penv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '$pbkdf2-sha512$10023$KYWw...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/root/c9sdk/privacyidea/penv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'admin@test.tld'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
test_get_applications (tests.test_api_applications.APIApplicationsResolverTestCase) ... ok
test_00_get_audit (tests.test_api_audit.APIAuditTestCase) ... ok
test_01_get_statistics (tests.test_api_audit.APIAuditTestCase) ... ok
/root/c9sdk/privacyidea/penv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '$pbkdf2-sha512$10023$cS6l...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
test_01_fail_without_auth (tests.test_api_caconnector.CAConnectorTestCase) ... ok
test_02_create_ca_connector (tests.test_api_caconnector.CAConnectorTestCase) ... ok
test_03_update_ca_connector (tests.test_api_caconnector.CAConnectorTestCase) ... /root/c9sdk/privacyidea/penv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'string'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/root/c9sdk/privacyidea/penv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value ''. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
ok
test_04_read_ca_connector (tests.test_api_caconnector.CAConnectorTestCase) ... /root/c9sdk/privacyidea/penv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'local'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
ok
test_05_read_as_user (tests.test_api_caconnector.CAConnectorTestCase) ... /root/c9sdk/privacyidea/penv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'tests/testdata/passwords'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
ok
test_06_delete_caconnector (tests.test_api_caconnector.CAConnectorTestCase) ... ok
test_01_check_tokentype (tests.test_api_lib_policy.PostPolicyDecoratorTestCase) ... /root/c9sdk/privacyidea/penv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'tokentype=spass'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
ok
test_02_check_serial (tests.test_api_lib_policy.PostPolicyDecoratorTestCase) ... /root/c9sdk/privacyidea/penv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'serial=TOTP'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))

**Comment by cornelinux** [comment]
This is a message from SQLAlchemy. 

First: Yes, you can ignore them.

The thing is that the database has a unicode field and some test cases just inserts a simple ascii string. 

You can also run the tests with

    py.test tests/

and you will have much less annoying output ;-)

**Comment by cornelinux** [comment]
I was thinking about marking the strings as unicode ``u"testadmin"``, but then I thought, that someday privacyIDEA should be run on python3 and then all the "u"s will have to be removed again. Also annoying ;-)

**Comment by mfgamma** [comment]
ok thanks for the info, I will try to experiment later this week

**Comment by graingert** [comment]
> all the "u"s will have to be removed again. 

python 3 supports u prefixed str literals
