### ISSUE TITLE
url_decode does padding incorrectly

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#2000]
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/u2f.py#L53 adds padding to a string containing base64. Th padding should get the message length to a multiple of four, however the current implementation will add three bytes of padding where one is required and vice versa. This bug does not cause any issues, since the messages we decode all need two bytes of padding currently.

**Comment by cornelinux** [comment]
So what is your suggestion?
Fix it in which way?
Move the method to lib/utils.py?

**Comment by NuvandaPV** [comment]
Nono, all I am suggesting is we fix this problem. No need to move the function or anything. I just opened this issue so I don't forget.
