### ISSUE TITLE
Update `admin_or_user()` policy matcher

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2024]
The `admin_or_user()` function needs an update to reflect changes from #1867 (Add adminuser and resolver)

**Comment by cornelinux** [comment]
Currently the Match.admin_or_user only matches for the *userrealm* in case the logged_in_user is an admin.
It should now match against the complete user, which is usually contained in request.User.realm.

So we could change the signature of the function to:

~~~~python
def admin_or_user(cls, g, action, user=None)
     user = user or request.user
~~~~

**Comment by cornelinux** [comment]
The policy match contructors ``admin_or_user(cls, g, action, realm)`` and ``admin(cls, g, action, realm)`` should both request a parameter ``user_obj`` instead of the realm parameter.
