### ISSUE TITLE
Fix questionnaire token bug

### ISSUE THREAD

**Issue by darrenche** [privacyidea/privacyidea#2026]
### Top-level intent

What did you try to achieve?

Fix questionnaire bug when creating a challenge on the following line:
https://github.com/privacyidea/privacyidea/blob/b3c981d8ed1a0b2470a7f3f4a1e1efb551737546/privacyidea/lib/tokens/questionnairetoken.py#L210

### Steps to reproduce

1. Create a security question that includes the characters from `.type`

### Expected outcome

What do you think, how the system should have worked?

The security question should not use `.strip` to remove `.type` from the key in **line 210**.

### Actual outcome

What did actually happen?

It should use `.replace`, but, note, if the user has `.type` inside the security question, the token will not be issued successfully.

### Configuration

* **privacyIDEA version**: 2.23
* **Installation method**: (from Ubuntu packages, github, PyPI, ...)
* **Python version**: 2.7
* **Operating system**: Amazon Linux
* **Webserver**:
* **Token database**: (MySQL, PostgreSQL, ...): PostgreSQL

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by darrenche** [comment]
CC: https://github.com/privacyidea/privacyidea/pull/2022

**Comment by cornelinux** [comment]
Thanks for pointing this out.

There are problems with using replace, too as you also pointed out.
As it is already tested, if the questions ends with ".type", the save  behaviour would be

~~~~python
questions.append(question[:-5])
~~~~
