### ISSUE TITLE
Retain the request parameters when doing a trigger challenge

### ISSUE THREAD

**Issue by darrenche** [privacyidea/privacyidea#2027]
**Is your feature request related to a problem? Please describe.**
What are you trying to achieve?

Retain all the request parameters when doing a trigger challenge.

**Describe the solution you'd like**

The `/validate/triggerchallenge` endpoint should retain all parameters similar to the `/validate/check` endpoint.
Refer to: https://github.com/privacyidea/privacyidea/pull/2023 with **lines 528-531**

**Describe alternatives you've considered**

N/A

**Additional context**
Add any other context or screenshots, that might help us to better understand your idea, your need and your circumstances.

Refer to: https://github.com/privacyidea/privacyidea/pull/2023

**Comment by cornelinux** [comment]
see may latest comment. 
Please read the documentation. The triggerchallenge is a totally different endpoint than /validate/check.

**Comment by quynh-axiadids** [comment]
Hi @cornelinux,

I think it will be great if the `/validate/triggerchallenge` can retain the params. One of the useful information this endpoint is missing to pass along is, for example, the `application` param in the request.

Best regards,

Quynh Nguyen

**Comment by cornelinux** [comment]
Hi @quynh-axiadids ,
thank for joining in. I still do not get it.
"retain" parameters to me sounds like there have been parameters before, which are not there anymore. But I don't get which parameters you are talking about.
So can you please explain, what you want to achieve and why, and which parameters are missing and what these parameters should do?
E.g. I have no knowledge of a parameter ``application`` (anymore).
Thanks a lot
Cornelius

**Comment by cornelinux** [comment]
PS: Please only do one issue in one pull request.
