### ISSUE TITLE
Changing user detail in WebUI

### ISSUE THREAD

**Issue by spamik** [privacyidea/privacyidea#203]
In WebUI is missing form for changing user details (like password, etc) by user. User policies have access right for this so it's probably just missing form in UI.

**Comment by cornelinux** [comment]
Right. It is just not implemented, yet. Since I was not sure till now, how and if to do it.

A user should be able to change his password. But nothing else.

**Comment by spamik** [comment]
Yeah I just need changing password for users (using internal SQL resolver) and I found access right in policy setting but no form. Maybe some other tab (like tokens and audit) with form for just typing old/new/confirm passwords?
