### ISSUE TITLE
Authentication process to handle special characters for Questionnaire Token validation

### ISSUE THREAD

**Issue by lavesh-axiadids** [privacyidea/privacyidea#2045]
This Issue is related to Questionnaire Token validation process.

If I enrol a Questionnaire Token with special characters (Chinese, French etc) in Answer, then validation fails.
Even if the user is typing the right answer, but still privacyidea returns False

Let's say for user X, Questionnaire token is enrolled with following Question and Answer
Question: Frènch Cîty
Answer: Pàrïs

During Authentication/Validation, if user X presents **Pàrïs** as the answer, authentication request returns False

**Comment by lavesh-axiadids** [comment]
Pull Request for this issue is created 

https://github.com/privacyidea/privacyidea/pull/2046

**Comment by plettich** [comment]
Can You tell me which version of privacyIDEA You are using as well as the Python/OS/DB version?
I could not recreate this issue with the current master branch and Python 2/3 (mysql/sqlite).

**Comment by lavesh-axiadids** [comment]
Privacyidea: 2.26
Python: 2.7.16
DB: Postgresql

**Comment by plettich** [comment]
Actually the latest privacyIDEA vesion in the 2.x branch is 2.23.5 and we don't plan on developing this branch any further.
Currently the development takes place in the 3.x branch which works with Python 3 (and fixes a lot of failed unicode conversions).

**Comment by cornelinux** [comment]
@plettich Can you please add a short unit test?
@lavesh-axiadids As you can see, this does not seem to apply for our privacyIDEA, so there seems no need to be fixed on our side. Please comment, otherwise we will close the issue soon.

**Comment by cornelinux** [comment]
Now that we have indeed some nice tests, I would close this, not?

**Comment by plettich** [comment]
Since this works with Python 2 and Python 3 i am ok with closing it.
