### ISSUE TITLE
tokentype in /validate/check and triggerchallenge

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2047]
Sometimes an application wants to authenticate the user by a certain tokentype.
Or the application wants the user to choose, which tokentype he uses for authentication. (Please use "Push"-Token and not "SMS"-Token).

While ``/validate/check`` and ``/validate/triggerchallenge`` allow an authentication either based on the user (use *all* his tokens) or on a specific serial number (use only *one* of the user's tokens) we need the authentication to also work on a specific token type. 
This can currently be configured in policies. But then the policy would always require a specific tokentype from a certain IP (have the server choose).

This time, the application should be able to choose the tokentype. And it could be tokentype A in one auth request and tokentype B in another auth request.

# Specification

## Parameters

Add the parameter ``type`` to the validate endpoints ``check``, ``samlcheck`` and ``triggerchallenge``.

Then only tokens of this very type will be searched and included in the tokenlist to be checked.
This happens here:

Either add "tokentype" to the method or add "type" in the options.https://github.com/privacyidea/privacyidea/blob/d536b52b5e25ef2e4225b2bca59b150f367300bc/privacyidea/api/validate.py#L337

Then the "type" is passed to the method ``get_tokens``.
https://github.com/privacyidea/privacyidea/blob/d536b52b5e25ef2e4225b2bca59b150f367300bc/privacyidea/lib/token.py#L1988

## Policies

The problem with this use case arises like this:

A user could use his HOTP token to try to authenticate. User enters HOTP value. 
But the application decides to only search for TOTP tokens. The authentication will fail.
Since the ``get_tokens`` only compiles a list of TOTP tokens, the HOTP otp value is not invalidated!
An attacker could use the HOTP value at another place!

However, since this is also supposed to work for challenge response tokens, we can not get the list of all users tokens. Since then the challenges might actually be triggered (see above - only use "Push" tokens and no "SMS" tokens would still result in an SMS being sent.)

Thus the use of a tokentype parameter introduces a possible attack vector we should make this configurable via an authentication policy:

* scope=authz
* action=application_tokentype:bool
* desc=Allow application to choose the valid tokentype.

**Comment by cornelinux** [comment]
Closes #2028

**Comment by h3ge** [comment]
> This can currently be configured in policies. But then the policy would always require a specific tokentype from a certain IP (have the server choose).

As far as I know currently it can only be configured in the postpolicies - According to this feature request, it would be great if it can be configured in the prepolicies, so that get_tokens only returns a list of specific tokentypens.

**Comment by cornelinux** [comment]
I opened this issue after closing another pull request in regards to tokentypes.
Why? Because we need to have this implemented in a consistaent way. So I do not want to go lightly on that.
The problems with pre- and post-policies in regards to authentication is, that doing such things in pre-policies will open up attack vectors for attackers. If a user fails to use the correct token, the OTP value of this token still needs to be invalididated. This will not happen, when using pre-policies.

**Comment by h3ge** [comment]
I understand these concers, but only partially agree - if the user enters his ATM code instead of the OTP code, I do not block the ATM card just to be on the safe side - I also do not block others users HOTP code just because a user send the right code for another user without knowing it.

From my point of view it is necessary to filter the tokens in the pre policy to achieve the following:

- User A has a Push and a TOTP Token
- User A connects via RD Gateway -> Radius -> PrivacyIdea, according to the policy based only the push auth is possible and so user A gets the notification and can confirm the connection
- User A connects via ADFS -> PrivacyIdea, according to the policy his push token is ignored (and not triggered) and he can only authenticate with his current TOTP Code
- User B connects via RD Gateway -> Radius - PrivacyIdea, according to the policy, currently he has no push token, but an TOTP Token - which is not useable for this combination, so instead of trying the TOTP Token (which will always fail) I can use the "passOnNoToken" setting because we don't have a valid token for the current type of connection.

**Comment by cornelinux** [comment]
You point of view indicated that you do not understand the token verification within privacyIDEA completely.

No token is blocked in the cause of the tokentype policy so far. Let me explain:

* Given the current tokentype policy allows auth with TOTP but not with HOTP.
* User authenticates with HOTP. privacyIDEA validates the HOTP but int he postpolicy it decides, that this is not a valid authentication request.
* => User is not authenticated.

But: The OTP value, from the HOTP token is verified and thus used up. The HOTP token is not blocked. But an attacker can not use the OTP value anywhere else.

Your idea with the passOnNoToken is interesting. We might consider this later.

This issue is not about defining which token type is allowed, but about let the application (i.e. your ADFS or RD Gateway) decide, which tokentype it wants to verify. This is basically only necessary with challenge response tokens. Because in other cases the existing tokentype policy works out perfectly.

**Comment by cornelinux** [comment]
@h3ge  the new PR #2230 that will close this issue, can lay ground for one day also define specific chalresp tokentypes in policies. I am personally still no friend of this. One step after the other.

**Comment by h3ge** [comment]
I don't want to deny that :) - I am only now dealing with privacyIDEA for the third day (in my freetime).

In my tests yesterday (with RD Gateway) the HOTP error counter was increased if the user did not have a pushtoken assigned, also the ADFS triggerchallenge always initiated a new push authentication to the user, even if the policy clearly only has topt and hotp allowed - I will try to verify that at the next chance. 

In any case, I thank you for the last change, it will make the implementation I wish much easier.

**Comment by cornelinux** [comment]
The current ``tokentype`` policy is as I mentioned a postpolicy. Which is checked *after* the authentication occurs. I.e. a challenge response token would be triggered, the challenge was answered, authentication would be denied. Yes, it does not work very well with challenge response.

"The HOTP error counter is increased, if the user has no pushtoken"? This sounds strange - but probably lacks a lot of information. If you are working with triggerchallenge, you probably are aware, that HOTP and TOTP usually are no challenge-response tokens. You need to set a *challenge response* policy, so that HOTP and TOTP act as challenge response.

**Comment by h3ge** [comment]
You were right, if I let HOTP and TOTP act as challenge response, I avoid increasing the error counter when the user does not have a push token, thanks.

Workflow when challenge response is **not** set.:
- User A does not has a push token, but a TOTP and a **disabled** HOTP token assigned
- User A connects via non challenge-response aware radius client (RD Gateway)
- Radius plugin is calling /validate/check with a empty pass variable set
- privacyIDEA tries the empty pass parameter against all user assigned tokens and increase the error counter for both TOTP and the **disabled** HOTP token (audit info: wrong otp value)
- Radius plugin: rlm_perl: return RLM_MODULE_REJECT
- RD Gateway connection failed

Workflow when challenge response is set:
- User A does not has a push token, but a TOTP and a disabled HOTP token assigned
- User A connects via non challenge-response aware radius client (RD Gateway)
- Radius plugin is calling /validate/check with a empty pass variable set
- privacyIDEA returns the info "please enter otp:"
- Radius plugin:    return RLM_MODULE_HANDLED
- RD Gateway connection failed

Workflow with Push Token available
- User A has a push token, a TOTP and a disabled HOTP token assigned
- User A connects via non challenge-response aware radius client (RD Gateway)
- Radius plugin is calling /validate/check with a empty pass variable set
- privacyIDEA send the push token challenge and waits for the response (configured push_wait timeout)
- User A confirm the push notification
- Radius plugin: return RLM_MODULE_OK
- RD Gateway connection OK

**Comment by cornelinux** [comment]
@h3ge I am not sure, what I should make with your comment here. Why are you pasting workflows?
If you trying to report a bug, please open a new issue or a request at the community forum.
I would like to not discuess this in an issue with an already specified behaviour. I think we might otherwise end up turning in circles.

**Comment by h3ge** [comment]
@cornelinux I just wanted to show how it happened that the error counter was increased, and how the handling topt and hotp as challenge-response changes behavior.
But you are right - this issue isn't the right place for it.
