### ISSUE TITLE
Focus in username field

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#205]
In the Web UI login page the username should have the focus.

The username field has the focus when calling _https://yourserver/_.

But it does not have the focus, when calling via _https://yourserver/#/login_, which is accessed via the "login" button  or the "privacyIDEA" button.

**Comment by cornelinux** [comment]
the autofocus does not seem to work all the time.

Here is a directive:
http://www.angulartutorial.net/2014/04/angular-js-auto-focus-for-input-box.html

**Comment by cornelinux** [comment]
Works now...

**Comment by stojmir** [comment]
Autofocus for the username input field does not seem to work under Firefox. It looks good under Chrome though. Not sure if this is a regression of the fix you did or a completely different issue?

**Comment by cornelinux** [comment]
I do not know the cause for this issue.
But it is again an issue.

**Comment by stojmir** [comment]
According to a thread on StackOverflow, autofocus on Firefox does not work properly when the form is loaded using Ajax. Could be the cause of the issue.

https://stackoverflow.com/questions/9955398/autofocus-attribute-of-html5-does-not-work-only-in-firefox-when-forminput-ar

**Comment by cornelinux** [comment]
@stojmir  thx for the inpurt!
