### ISSUE TITLE
ldap resolver

### ISSUE THREAD

**Issue by fraynery** [privacyidea/privacyidea#2050]
Buen día, estamos trabajando con privacyidea en el test ldap resolver me da este error: LDAPStartTLSError('startTLS failed - unavailable',) me pueden decir como solucionarlo o alguna indicación de que se debe hacer? gracias

**Comment by cornelinux** [comment]
No hablamos español. Así que tienes que hablar inglés, por favor. También para permitir que otros participen en la discusión. También, esto parece ser una pregunta en relación con el uso o privacyidea, que debe ser archivada en https://community.privacyidea.org - en inglés.
Gracias. :-)
