### ISSUE TITLE
Python suggests using dictConfig for logging configuration instead of files

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2059]
According to the [Python docs](https://docs.python.org/3/library/logging.config.html#configuration-file-format), the `fileConfig()` API is kind of deprecated and won't be updated in the future.
This already impacts logging configuration files with the [`RotatingFileHandler()`](https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler) which ignores the `maxBytes` and `backupCount` parameter.

**Comment by cornelinux** [comment]
Does this mean we would have to read the config file ourselves, parse it into a dict and then do ``dictConfig``?

**Comment by plettich** [comment]
Yes, this is needed for setting up logging to logstash/splunk (#1580).
With a logging configuration in YAML this will take two lines of code.

**Comment by plettich** [comment]
TODO:
- [ ] update docs
