### ISSUE TITLE
Check if u2f-api.js is needed

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2067]
To me it is not clear, if we still need the u2f-api.js, which was still used in PR #2013 but was removed in 593812b8e220df92c771d16a868b0ab4be3e37b9.
Check and discuss.

**Comment by plettich** [comment]
I've checked u2f and webauthn with current master and without u2f-api.js`. Works here.

**Comment by cornelinux** [comment]
Thanks!!!
