### ISSUE TITLE
add custom text to PUSH token

### ISSUE THREAD

**Issue by MatthiasLaechele** [privacyidea/privacyidea#2070]
One PUSH token per user account is rolled out. PUSH token is used by different services via RADIUS plugin to check the 2nd authentication factor.

Currently, all text in the smartphone are fixed and defined during token enrollment.
It would be nice to add an additional text out of the RADIUS request to the users push notification. For example "Login attempt to SharePoint" or "Login attempt to Remote Desktop Service"

**Comment by cornelinux** [comment]
Cool. Someone is using the push-token! ;-)
If I understand you correctly, this can already be done by using this policy:
https://privacyidea.readthedocs.io/en/latest/policies/authentication.html#push-text-on-mobile

You can define the policy based on an IP-Address. 
Depending on the Client (Application) IP address, you can have different texts.

**Comment by MatthiasLaechele** [comment]
Thanks for your fast reply and yes, the PUSH tokens grants us many more possibilities to secure services/protocols. Many services offer RADIUS features and can therefor be used to check a second factor even if there isn't any form to input a OTP and/or PIN.

Unfortunately in our case, the authentication request to /validate/check are send from privacyIDEA radius perl module. Therefore the client ip is logged as 127.0.0.1 in privacyIDEA backend.
Thus, it is not possible for me to use different authentication policies and 

Is this the desired behaviour?
I saw within the RADIUS debug logs, that the radius client ip is sent to privacyIDEA backend
rlm_perl: client sent to privacyidea: 172.xxx.xxx.xxx
What does privacyIDEA do with this client ip address?

**Comment by cornelinux** [comment]
You can set the Override Authentication Client:
https://privacyidea.readthedocs.io/en/latest/configuration/system_config.html#override-authorization-client

    127.0.0.1, ::1

**Comment by MatthiasLaechele** [comment]
Thanks for the hint :)

**Comment by cornelinux** [comment]
I think this is clear fow now.
