### ISSUE TITLE
"pi-manage create_enckey" command should accept static key by arg 

### ISSUE THREAD

**Issue by brunocascio** [privacyidea/privacyidea#2075]
**Is your feature request related to a problem? Please describe.**
Creates an enckey with a password string set via CLI

**Describe the solution you'd like**
`pi-manage create_enckey --enckey=<key>`

PR:  #2084

**Additional context**

I'm trying to deploy pi with docker swarm. In a multi-host environment, there's no easy way to distribute volumes data, so I'm trying to avoid file persistence. I'm thinking about creating the same enckey for all the instances instead of random bytes (default behavior). Is it possible?

**Comment by brunocascio** [comment]
Solution could be:

```
@manager.command
def create_enckey(enckey=None): # <-- changed here
    """
    If the key of the given configuration does not exist, it will be created
    """
    print()
    filename = app.config.get("PI_ENCFILE")
    if os.path.isfile(filename):
        print("The file \n\t%s\nalready exist. We do not overwrite it!" %
              filename)
        sys.exit(1)
    with open(filename, "wb") as f:
        f.write(DefaultSecurityModule.random(96) if enckey is None else enckey.encode()) # <-- changed here

    print("Encryption key written to %s" % filename)
    os.chmod(filename, 0o400)
    print("The file permission of %s was set to 400!" % filename)
    print("Please ensure, that it is owned by the right user.   ")
```

**Comment by cornelinux** [comment]
Yes, you could do that. You code looks sensible.
But weren't we always told to not put passwords at the command line?
So I would not like putting the encryption key at the command line which will be visible to attackers in the process list.

**Comment by brunocascio** [comment]
Yes, I know 😄. But, If an attacker can access to your process list you could have other serious problems rather than a password😬

I'm just thinking in multi host instances where distributed volumes is not an option. I need at some point the same enckey across instances. Passing the enckey as string is "insecure" but simple and solves the problem. At this point, pi only can run on a single instance or using distributed file systems.

**Comment by cornelinux** [comment]
Hi @brunocascio,
do you have another way to do this? Why do you give up so quickly and closed this issue ;-)

So your multi instance does use the same configuration? The same database?
The same pi.cfg file?
Or are the instances supposed to run  diffrent logical setups?

**Comment by plettich** [comment]
@brunocascio can You pass environment variables to the docker container?

**Comment by brunocascio** [comment]
I closed the issue apparently 😂

> So your multi instance does use the same configuration? The same database?
The same pi.cfg file?
Or are the instances supposed to run diffrent logical setups?

Yes, always the same config because they are deployment replicas.m

**Comment by brunocascio** [comment]
> @brunocascio can You pass environment variables to the docker container?

Hi @plettich, 
Yes, currently I am passing the enckey vía env to the container. Then, I have an entry point which creates the encfile with the env value.

Also I could use `docker secrets` instead

**Comment by brunocascio** [comment]
I've made a PR: #2084
