### ISSUE TITLE
Support for one user signing in to the webui with one of multiple Fido-tokens

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#2092]
Using U2F or WebAuthn to sign in to the webui seems to only work for a single token. If the user has multiple U2F tokens, or WebAuthn tokens, respectively, only whichever token happens to be the first one of its type in the multi-challenge will work. Need to investigate further, marking this as possible bug.

**Comment by cornelinux** [comment]
It looks like as if the *challenge* of the challenge response only contains **one** challenge data, that only works for one of the multiple tokens. 
This might be true for the webui but also for all /validate/check requests.

**Comment by plettich** [comment]
Actually it looks like it is the other way around:
We create a new challenge for every token but only check/sign the first challenge:
https://github.com/privacyidea/privacyidea/blob/07d29ef96f7416acbfc4b469fca7ce0edb3a18c6/privacyidea/static/components/login/factories/webauthn.js#L82
