### ISSUE TITLE
Support filtering in the user's location when signing in through WebAuthn

### ISSUE THREAD

**Issue by jp-hoehmann** [privacyidea/privacyidea#2105]
Since some WebAuthn authenticators support passing their current location, we could implement a policy, that allows to specify where the user needs to be when signing interacting with a service.

Depends #2104 

Also see #3033 Fuzzy Authentication / pre-authentication

**Comment by cornelinux** [comment]
Could be also interesting for non-WebAuthn-Tokens.
We could pass the IP based location in the pre-authentication.
