### ISSUE TITLE
Better separation of audit log from privacyidea*

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2106]
Hi,

python logging may be easily separated using the qualname. However, privacyidea uses the module/class names. Since they all start with "privacyidea.", it is not possible to log the audit to one place and all the rest to a different place (python logging cannot *exclude* qualnames).

To solve this, one could use a custom qualname for the privacyidea audit. I think here:
https://github.com/privacyidea/privacyidea/blob/ea7d9e53d42504288ba3909f7057924fe8d250b0/privacyidea/lib/auditmodules/loggeraudit.py#L62

Best regards,

Henning

**Comment by laclaro** [comment]
I would suggest "pi-audit"

**Comment by cornelinux** [comment]
The qualname should not be *another* *fixed* value.

It can be configured in pi.cfg via
``PI_AUDT_LOGGER_QUALNAME`` and defaults to ``__name__``.
