### ISSUE TITLE
Problematic login with openLDAP if uid is equal mail address

### ISSUE THREAD

**Issue by ettorevi** [privacyidea/privacyidea#211]
Using basic configuration of ldapresolver and having entries like:

dn: uid=alice.cooper@example.com,ou=users,dc=example,dc=com
objectClass: inetOrgPerson
uid: alice.cooper@example.com
mail: alice.cooper@example.com
cn: alice cooper
[...]
users are created, with username alice.cooper@example.com, but it is impossible to login.
It says it cannot find such user in any realm. It seems to me it try to search the user with a filter having uid truncated to alice.cooper without the rest.
The option 
"Use @ sign to split the username and the realm." 
in config is unchecked.
Is it a bug in lib/resolvers/LDAPIdResolver.py ? Is it me doing something silly?
Thanks for your attention
Ettore

**Comment by cornelinux** [comment]
The behaviour for logging in to the Web UI is not really clear at this stage. While you could use the API to authenticate the username "alice.cooper@example.com" the login is not implemented.

Are the users used to login with their email address?

What is the realmname of the user?
You might be able to login with 

<username>@<realm>

i.e. "alice.cooper@example.com@realm"

On the other hand you can define other attibutes of the LDAP object to be used as login attribute.

**Comment by cornelinux** [comment]
It seems quite easy:

Probably the function **split_user** has to be improved.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/user.py#L464

At the moment it splits the element after the last @ to be the realmname.
But it may only be splitted, if this also exists as realm. If it does not exist, the user user@domain has to be searched in the default realm.

Should be straightforward and easy to fix...
