### ISSUE TITLE
After deleting token does not return to user

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2122]
on the current master branch when deleting a token of a user, the dialog stays on the deleted token and does not return to the user.

Reproduce:

* go on user details
* select one of the users tokens -> token detail
* delete token
(The view should return to the user, but it stays on the deleted token)

**Comment by cornelinux** [comment]
The problem arises here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/controllers/tokenDetailController.js#L116
The routeScope does not contain the previousState anymore

**Comment by cornelinux** [comment]
The problem seems to be, that angular-ui-router.js does not emit ``$stateChangeSuccess`` anymore.
The closest it does, seems to be ``$viewContentLoaded``. But it seems this does not contain the previous routes/states anymore.

So we could catch ``$rootScope.$on("$viewContentLoaded")`` but we might be missing some parameters is the thrown event.

**Comment by plettich** [comment]
Working on #830
