### ISSUE TITLE
Remove Support for Python 2.7

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2128]
Keeping the support for Python 2.7 makes the code more and more unmaintainable.
We need to jump through hoops to keep the requirements working, etc.
We should check if and how the main distributions support Python 3 and if we can fade out support for Python 2.

Steps to take:

* [x] remove note in setup.py and requirements.txt
* [x] cleanup code to remove the special code for 2.7. (see `six.PY2`) (@NNLemling ) 
* [x] remove all `future` imports (@plettich )
* [x] rename Regex assertions: https://docs.python.org/3.8/library/unittest.html#deprecated-aliases  (@plettich )
* [x] unicode/("u")  (@jona-samuel )
* [x] six.stringtype (@NNLemling )
* [x] remove all `six` imports (@plettich )
* [x] check if we can remove the different `unicode` functions:
  - `hexlify_and_unicode`
  - `b64encode_and_unicode`
  - `to_unicode`
  - `__unicode__`
* [x] This can also be removed:
  https://github.com/privacyidea/privacyidea/blob/3c9a0e25a304d586d71f0192b0abae2f3ae219df/privacyidea/lib/tokens/totptoken.py#L301
* [x] check for `ImportError` occurrences if they can be removed

**Comment by cornelinux** [comment]
We should even drop official support for python <=3.5.
We should check, if we can already drop this in 3.8.

"We plan to remove the support". Add this to the release note for 3.7.1.

**Comment by cornelinux** [comment]
Will  be removed in 3.9 as communicated to users.

**Comment by plettich** [comment]
I think this is done.
