### ISSUE TITLE
Multi-Challenge: Questionnaire token's support for more than one answers required per challenge

### ISSUE THREAD

**Issue by quynh-axiadids** [privacyidea/privacyidea#2137]
**Is your feature request related to a problem? Please describe.**

The the moment, questionnaire token only prompts for 1 question per challenge, and it will randomize one from the questions configured in that token.

It will be great if questionnaire token can support:
 * Prompts for multiple questions in the token per challenge
 * Requires the user to response with answers for the above prompted questions.

**Describe the solution you'd like**

When the questionnaire token is triggered, based on the number of required answer configured for questionnaire token (new configuration option), the user will be asked that many questions, and will be required to submit the answers for those questions correctly.

This should happen within 1 challenge/response preferably if possible.

**Describe alternatives you've considered**
Alternatively, we are thinking of using multiple questionnaire tokens, with one question each. However, this approach will require diversion in configuration being stored, and also adding more calls to the API.

Best regards,

Quynh Nguyen

**Comment by cornelinux** [comment]
Please specify how you think, this could look like?

How should the challenge text look like?

How should the user enter the response?

*I think the more generic approach would be to allow a challenge response to create new challenges after a response was answered. But the current design does not allow for that. So this would probably only happen in version 4.*

**Comment by quynh-axiadids** [comment]
For the challenge text, I think the current response has already have a format that can extend to support multiple questions in the challenge:
```
[...]
        "messages": [
            "question 2",
            "question 3",
            "question 4"
        ],
        "multi_challenge": [
            {
                "attributes": null,
                "message": "question 2",
                "serial": "QUST0003C855",
                "transaction_id": "14023462515903980394",
                "type": "question"
            },
            {
                "attributes": null,
                "message": "question 3",
                "serial": "QUST0003C855",
                "transaction_id": "04781040133827397452",
                "type": "question"
            },
            {
                "attributes": null,
                "message": "question 4",
                "serial": "QUST0003C855",
                "transaction_id": "05489273070579907514",
                "type": "question"
            }
        ],
        "serial": "QUST0003C855",
        "threadid": 139760752719872,
        "transaction_id": "05489273070579907514",
        "transaction_ids": [
            "14023462515903980394",
            "04781040133827397452",
            "05489273070579907514"
        ],
        "type": "question"
    },
[...]
```
For the user's response, we can submit something like:
```
[...]
"user" : "jdoe"
"multi_challenge" : [
  {
    "message": "question",
    "pass": "myPass",
    "transaction_id": "04781040133827397452"
  },
  {
    "message": "question 3",
    "pass": "myPass3",
    "transaction_id": "05489273070579907514"
  },
  {
     "message": "question 2",
     "pass": "myPass2",
     "transaction_id": "14023462515903980394"
  }
],
[...]
```
I use multiple transaction ids in the example just for demonstration.

I can see that for client such as RADIUS, there maybe a problem with the above suggestion, or this feature request in general. Though, we don't have a RADIUS priority for this feature request.

Above is just my quick thought on your question.

Thank you for looking into this.

Best regards,

**Comment by cornelinux** [comment]
@quynh-axiadids Thanks a for the response.
I mean: How should the text be displayed to the user?

   "What is your mother's maiden name? What is the name of your cat? What is your shoe size?"

What should the user type in?

   "smithhans11/2"?

This is the much bigger question to me.

**Comment by quynh-axiadids** [comment]
Hi @cornelinux,
I do not come up with any specific thought of how the question display and the answer input should be like...
But I think the value of the questions can be very flexible and not necessarily ending with `?` as in your example.
Please let me know if you have any idea in mind?

**Comment by cornelinux** [comment]
We will do this with multi challenge response like the indexed secret token in #2163

**Comment by cornelinux** [comment]
We could rather do this with multi challenge this way, that the questionaire token will ask for Answer A, then for answer C...
And only after a number of answers were given have the user logged in.

**Comment by cornelinux** [comment]
``check_challenge_response`` needs to create new challenges.

We store the number of the question in the ``data`` field in the Challenge.
