### ISSUE TITLE
Organize Event Handler conditions

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2148]
The conditions of event handlers are badly organized in the UI.
We could do this in a similar way like the actions in policies.

We could group conditions or we could at least allow filtering conditions and only view enabled conditions.

**Comment by cornelinux** [comment]
@plettich I am assigning this to you, so that you can pass this to/work with sebastian.

**Comment by NNLemling** [comment]
I created a list how the individual conditions could be grouped. Maybe someone else has suggested changes here?

1. **general**: 
                        client_ip
                        detail_error_message
                        detail_message
                        last_auth
                        result_status
                        result_value

2. **token**: 
                        rollout_state
                        serial
                        token_locked
                        token_validity_period
                        tokeninfo
                        tokenrealm
                        tokenresolver
                        tokentype

3. **user**: 
                        logged_in_user
                        realm
                        resolver
                        token_has_owner
                        token_is_orphaned
                        user_token_number

4. **counter**: 
                         count_auth
                         count_auth_fail
                         count_auth_success
                         failcounter
                         otp_counter
                         counter. 

also we should add a second "Create Event Handler Definition" button in the upper part of the GUI just like we did with the policies to avoid that the user always has to scroll all the way down to create an event.

**Comment by cornelinux** [comment]
Great, sounds good. Here a few comments:

* ``last_auth`` is token specific so I would put this to *token*.
*  I would also put ``token_is_orphaned`` and ``token_has_owner`` to *token*, since it is an aspect of a token

It is a cout idea to have an extra group "counter".

**Comment by NNLemling** [comment]
thanks for the comment. I changed everything and updated the list!
