### ISSUE TITLE
default SMS text format

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2151]
There is a definition for SMS text by Apple for logging in to websites with 2FA:

https://github.com/wicg/sms-one-time-codes

This can of course be configured in privacyIDEA. But maybe we want to make this default, add a button or at least add a note in the documentation.

**Comment by cornelinux** [comment]
We can add this to the documentation or also to the policy description of SMSTEXT.
We should wait for #2684 to be merged.

**Comment by laclaro** [comment]
PR #2700 adds a note about origin-bound one-time codes. However, we seem to not support line breaks in our policies. This is why we cannot easily add a human-readable explanatory text as suggested in https://github.com/wicg/sms-one-time-codes.

**Comment by cornelinux** [comment]
This is interesting. The questions also is, how an SMS Gateway would actually accept a line break.
If it is an HTTPSMSProvider we probably need to urlencode.

See https://stackoverflow.com/a/10601740

Maybe it is enough to add such a hint to the documentation, to use `%0A`?

**Comment by laclaro** [comment]
I added the comment, but I learned, that this will not work, since upon creation of the requests.post object, the data is urlencoded again. so we cannot pass already urlencoded things. I suggest to drop PR #2700 and to think again. iOS does not seem to apply the suggested format anyway.
