### ISSUE TITLE
Cannot enroll U2F token in Chrome

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#2157]
We removed `u2f-api.js` in https://github.com/privacyidea/privacyidea/commit/593812b8e220df92c771d16a868b0ab4be3e37b9, since this was ostensibly no longer needed. Have we made sure this really works? I am not able to enroll a token in Chrome right now, and a quick glance shows, that there is no `window.u2f` either.

**Comment by plettich** [comment]
Well crap! i can confirm this. I'm pretty sure i tested at least chromium for compatibility. I'll check this out.

**Comment by cornelinux** [comment]
I created a brach-3.3 where we can put this.
