### ISSUE TITLE
Temporary authenticating machines

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2169]
Hello,

I'm thinking these days about possible ways to realize 2FA with "headless" protocols such as IMAP. The scenario may work if privacyIDEA handles both 1st and 2nd factor.

The idea is as follows:
1. The user authenticates with his 2nd factor against privacyIDEA.
2. privacyIDEA remembers the user and the client machine from which the request came.
3. The user is able to authenticate without 2nd factor for a limited amount of time at the "headless" service.
4. an event-handler may send an email just before the ticket expires and redirects again to the privacyIDEA 2FA-portal.

This may be related to the existing machine-resolvers feature, setting up some "dynamic" machine resolver?

Please share your thoughts.

Best,

Henning

**Comment by cornelinux** [comment]
Hi @laclaro  

Do you have a dedicated example for this?

Because I wonder how should step **3** work?

The service needs to know that the user authenticated with privacyIDEA. How do you want to adapt the service to do this? If you are capable to adapt the service this way, then you would habe been probably able to adapt it to do 2FA in the first place.

**Comment by laclaro** [comment]
I try to think inside the present logics of privacyIDEA. Maybe it is already possible (but complicated).

The user could have a special token, the "dynamic ticket enabler" which would act more like a policy to enable the dynamic ticket creation. An event handler checks for the token type and creates a spass-token (the actual ticket, we may put a special name like "access ticket"), valid for a limited time and with the requesting host ip or some other identifier in the description field. This is subsequently used to bypass the 2FA from the same host.

**What would be needed?**

  *At the moment enroll action of the event handler does not support validities, I think. Especially one would need a possibility to set a valid time like "now + 2h".

  * Also I'm not sure if there is the requesting ip or some other identifier available. In the header probably. We would have to extract is from there.

**Use case 2**

This scheme could be also used for services which are accessed from inside a VPN (secured with a regular 2FA) to realize a SSO-light for the second factor.

@cornelinux Your comment is correct. How to identify the service, the user should be allowed to use? In the described case the ticket is "global".

**Comment by cornelinux** [comment]
>> This is subsequently used to bypass the 2FA from the same host.

The problem is, that the serivce can not be configured to authenticate against privacyIDEA in the first place!

**Comment by laclaro** [comment]
In think I know what you mean. The service must be privacyIDEA-enabled in some way (which IMAP-servers and such usually are not [yet])

**Comment by cornelinux** [comment]
"yet": Good. You are aiming for world domination. ;-)
