### ISSUE TITLE
Catch realm "priority" error in WebUI

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2171]
Hi!

A missing priority value is not caught by the WebUI, when editing an existing realm (e.g. to add another resolver).

Best,

Henning

**Comment by cornelinux** [comment]
I am not sure if this is somehow a hidden "feature".

i.e. if it might make more sense to actually *require* priorities, when the realm contains more than one resolver - even during the initial realm creation.

I would like to discuss this.

**Comment by laclaro** [comment]
Okay, one could also not use the proposed approach of leaving no priority. Maybe it makes more sense to always require a priority.
Does it make sense to have the same priority for two resolvers in a realm?

If this is not tolerable, one would have to introduce more logics to read the present values on changing and such.
