### ISSUE TITLE
qr_image items float out of the layout

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2175]
The alignment of the qr_image_android and qr_image_ios is not correct and the images will float out of the layout.

The image sizes should be relative should stay inside the boundaries for both wizard and token enrollment.

**Comment by laclaro** [comment]
Since you may enable an unknown number of QR codes to display, a fixed image size is easier to handle.

**Comment by cornelinux** [comment]
Hm, you are right. This looks strange. Not like it looked during implementation...
