### ISSUE TITLE
convenient policy action search over all scopes

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2178]
Current behaviour:
When the scope is selected and the admin searches for an action the actions are filterd.

Additional behaviour:
When the scope is not selected and the admin searches for an action, the list of the scopes is filter to the scopes, that contain actions with this substring. Then the admin can select on one of the found scopes and look further.
If only one scope is left, the scope could be selected automatically and the matching actions would be displayed.

**Comment by plettich** [comment]
Additionally we could add a link/button to open/close all elements of the accordion component, especially if the "Show selected actions only"-button is triggered.

**Comment by laclaro** [comment]
Examining the code in config-policies.details.hml, I think we must think a little about how the feature should work.

Proposition:

Upon clicking on "create new policy"

* No scope is initially selected, the full list of policies is displayed (sorted by scope) with checkboxes activated and the creation button deactivated
* If a scope is selected
    * a policy-creation is possible (button activated)
    * all other scopes are deactivated making cross-scope-selection impossible
* typing "totp" in the search field filters the full list of policies
* ticking a policy 
    * automatically selects the parent scope triggering the safety-measures sketched above

**Comment by laclaro** [comment]
During the implementation of this feature, we could also highlight the search term using the angular module ui-utils as described here
https://angular.de/artikel/mark-highlight-search-results/

**Comment by laclaro** [comment]
If search in privacyIDEA becomes an endpoint of its own like discussed in #2458, it could be useable for this feature too.

**Comment by cornelinux** [comment]
If we already seleced a scope, then we should only search in this scope.

If no scope is selected, we could search in all scopes. But then, wen selecting an action we would define the scope.

**Comment by plettich** [comment]
Actually we already fetch the actions for all scopes when opening/creating a policy.
In
https://github.com/privacyidea/privacyidea/blob/77b05ae3157265432d15473cf625713258e33463/privacyidea/static/components/config/controllers/configControllers.js#L151
the `/policy/defs` endpoint is called without a parameter thus returning all actions for all scopes.

**Comment by NNLemling** [comment]
**Possible Options:**

- Search for all policies, after you have selected a policy, the corresponding scope is automatically selected.
- An additional search field for documentation or policy scope.
- Policy creation is detached from the scope.

**Possible Problems:**

- It is confusing if you can search for all policies without a selected scope and then after selecting a specific policy you can only search in the selected scope.
- Another search field makes the entire configuration overview even more confusing
- Creating a policy that is detached from the scope causes problems with duplicate policy names and possibly policies with a large number of different actions
- The users are used to the current configuration

I would not implement this change at the moment. Should a new UI be built in the future, this issue will help to rethink the implementation for policy creation.

Maybe with a wizard?!🧙‍♂️

**Comment by nilsbehlen** [comment]
will be continued here #4102
