### ISSUE TITLE
WebUI does not send username in totp challenge response

### ISSUE THREAD

**Issue by blsho** [privacyidea/privacyidea#2192]
### Top-level intent

I would like to login to privacyidea with totp token over WebUI in challenge-response way.

### Steps to reproduce

1. Enable totp `challenge_response` in an authentication policy
2. Entroll a totp for a regular user
3. Open a web-broser with PI and enter username/password of the user
4. Enter totp value

### Expected outcome

WebUI should send a POST message to API after 4th step in a following fashion:
```
curl 'https://privacyidea/auth' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json;charset=utf-8' \
  --data '{"username":"user","password":"123456","transaction_id":"01234567890123456789"}'
```
### Actual outcome

It actually sends request with blank username and therefore API returns 401:
```
curl 'https://privacyidea/auth' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json;charset=utf-8' \
  --data '{"username":"","password":"123456","transaction_id":"01234567890123456789"}'
```

### Configuration

* **privacyIDEA version**:  3.3.2

### Log file

N/A

**Comment by plettich** [comment]
Thanks for opening the issue, i can reproduce this behavior here. It is the result of an update of some JS components.
