### ISSUE TITLE
Userlist does not show users if default realm is not accessible

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2197]
Hi,

setup: realm1 (default), realm2, helpdesk-admin to manage userrealm realm2.

In this common case, the userlist is not displayed, since no realm will be set to view.

Desired solution: if the default realm is not accessible, the first accessible realm should be displayed by default in the userlist.

Best,

Henning

**Comment by cornelinux** [comment]
Closing this issue since it is not relevant in nearly all cases.
