### ISSUE TITLE
Policy "email_max_tokens_per_user" is not working

### ISSUE THREAD

**Issue by brunocascio** [privacyidea/privacyidea#2201]
### Top-level intent

What did you try to achieve?

Avoid multiples tokens enrollment for the same user setting up `email_max_tokens_per_user` policy

### Steps to reproduce

1. Go to policies and configure an "enrollment" policy with `email_max_tokens_per_user = 1`  (screenshot attached)
2. Go to events and configure a validate_triggerchallenge event, Token as Handlermodule, and enroll as action (screenshot attached)
3. call /validate/triggerchallenge endpoint with an email 2 times. There are 2 tokens instead of 1. 

### Expected outcome

What do you think, how the system should have worked?

Only one token should be enrolled

### Actual outcome

What did actually happen?

`N` tokens have been enrolled

### Configuration

* **privacyIDEA version**: master
* **Installation method**: github
* **Python version**: 3.7
* **Operating system**: Manjaro
* **Webserver**: development server
* **Token database**: Sqlite

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

![image](https://user-images.githubusercontent.com/2397875/81843161-97b77c80-9523-11ea-943b-8771b750c916.png)

![image](https://user-images.githubusercontent.com/2397875/81843243-b4ec4b00-9523-11ea-8aac-c5e999377100.png)

![image](https://user-images.githubusercontent.com/2397875/81843400-eebd5180-9523-11ea-863b-9c90ff7a05d2.png)

NOTE:

sms policy does not work either. I don't know if I missing something

**Comment by cornelinux** [comment]
This works as designed. 

The policies work on the API level. The triggered events are not called on the API level and thus do not take into account the (most) policies.

If a user only has email tokens (one emailtoken), you can use a condition in the event handler.
If a user can have several different token types, but your event handler should enroll one email token at max, you need to write a script handler. This python script can check all aspects of the user an his tokens and then can act accordingly.

For example scripts see here:
https://github.com/privacyidea/scripts

**Comment by brunocascio** [comment]
Thanks a lot @cornelinux 

Do you recommend call `/token/init` endpoint instead of `init_token()` in order to trigger events and perform some other things from the event handler UI instead?

Something like this:

```python
from privacyidea.lib.token import (get_tokens)
import requests

# Get the list of email tokens for the given user
toks = get_token(tokentype="email", user=user_obj, active=True)
if not toks:
    res = requests.post('/token/init', ...)
    if res.status_code != 200:
         raise Exception('bla bla')
```

**Comment by cornelinux** [comment]
"It depends".

If you need to trigger additional events, you need to call /token/init.
Also note: The REST call is mentioned in the audit log, the library call to ``init_token()`` is not.

If you need to create a *lot* of tokens, init_token() is much faster.
