### ISSUE TITLE
Fix inconsistent enrollment templates

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2208]
Some enrollment templates behave differently in some common functionality, e.g. the `description` form is not always hidden when the user does not have the `setdescription` right.

**Comment by cornelinux** [comment]
Hm, this should have been done in #2173

**Comment by plettich** [comment]
@cornelinux You are right, i guess my branch wasn't up-to-date.
Anyway, does it make sense to add the `description`-form to all token enrollment views? Why should people not be able to set a description for 4eyes-token or question-token?
We could add the `description`-form to the base token enrollment view.

**Comment by cornelinux** [comment]
@plettich sounds sensible to me.
