### ISSUE TITLE
Error "Could not get the userinformation" in log file

### ISSUE THREAD

**Issue by FedeOmoto** [privacyidea/privacyidea#2219]
### Top-level intent

What did you try to achieve?
WEBUI is not displaying **user** column information in `Tokens -> All tokens`.
Also, the WEBUI is not displaying the **Username** in `Token details for OATH**** -> Assigned User`.

### Steps to reproduce

1. In the WEBUI go to `Tokens -> All tokens`, no information is displayed at the **user** column.
2. In the WEBUI go to `Token details for OATH**** -> Assigned User`, no information is displayed in **Username**.

### Expected outcome

What do you think, how the system should have worked?
WEBUI should display the user information.

### Actual outcome

What did actually happen?
An error is logged in the log file:
```
[2020-05-25 18:43:31,475][74911][140538455636608][ERROR][privacyidea.lib.resolvers.SQLIdResolver:353] Could not get the userinformation: DatabaseError('(cx_Oracle.DatabaseError) ORA-00906: missing left parenthesis',)
```

### Configuration

* **privacyIDEA version**: 3.3.1
* **Installation method**: github, PyPI, RHEL package dependencies
* **Python version**: 3.6.9
* **Operating system**: RHEL 7.8
* **Webserver**: NGINX Unit 1.17.0
* **Token database**: Oracle 19c (using SQLAlchemy cx_oracle dialect)

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

Log files attached.
[all_tokens.log](https://github.com/privacyidea/privacyidea/files/4679035/all_tokens.log)
[token_details.log](https://github.com/privacyidea/privacyidea/files/4679036/token_details.log)

**Comment by cornelinux** [comment]
@FedeOmoto Please provide your mapping and configuration of the SQLResolver, so that we can test and reproduce.

**Comment by FedeOmoto** [comment]
> @FedeOmoto Please provide your mapping and configuration of the SQLResolver, so that we can test and reproduce.

Please take a look at the attached files for the SQLResolver configuration.

This is our mapping for the table:
```json
{ "userid" : "id", "user_entity_id" : "id", "username" : "username", "email" : "email", "email_constraint" : "email_constraint", "surname" : "last_name", "givenname" : "first_name", "email_verified" : "email_verified", "enabled" : "enabled", "realm_id" : "realm_id", "created_timestamp" : "created_timestamp"}
```

And this is the table DDL:
```sql
CREATE TABLE IDP_USER_STORAGE.USER_ENTITY (
	ID VARCHAR2(36),
	EMAIL VARCHAR2(255),
	EMAIL_CONSTRAINT VARCHAR2(255),
	EMAIL_VERIFIED NUMBER(1,0) DEFAULT 0 ,
	ENABLED NUMBER(1,0) DEFAULT 0 ,
	FEDERATION_LINK VARCHAR2(255),
	FIRST_NAME NVARCHAR2(255),
	LAST_NAME NVARCHAR2(255),
	REALM_ID VARCHAR2(255),
	USERNAME NVARCHAR2(255),
	CREATED_TIMESTAMP NUMBER(38,0),
	SERVICE_ACCOUNT_CLIENT_LINK VARCHAR2(255),
	NOT_BEFORE NUMBER(22,0) DEFAULT 0 ,
	CONSTRAINT CONSTRAINT_FB PRIMARY KEY (ID),
	CONSTRAINT SYS_C008436 CHECK (ID),
	CONSTRAINT SYS_C008437 CHECK (EMAIL_VERIFIED),
	CONSTRAINT SYS_C008438 CHECK (ENABLED),
	CONSTRAINT SYS_C008856 CHECK (NOT_BEFORE),
	CONSTRAINT UK_DYKN684SL8UP1CRFEI6ECKHD7 UNIQUE (REALM_ID,EMAIL_CONSTRAINT),
	CONSTRAINT UK_RU8TT6T700S9V50BU18WS5HA6 UNIQUE (REALM_ID,USERNAME)
);
```

![image](https://user-images.githubusercontent.com/2894223/83360188-c754ea00-a355-11ea-8c80-02291173440f.png)
![image](https://user-images.githubusercontent.com/2894223/83360195-dc317d80-a355-11ea-9658-7e024551389f.png)
