### ISSUE TITLE
Webui Authenticator App QR code missplaced

### ISSUE THREAD

**Issue by marcohald** [privacyidea/privacyidea#2222]
### Authenticator App QR code missplaced

Show QR Code for iOS and Android side by side.

### Steps to reproduce

1. create webui policy
2. Enable show_android_privacyidea_authenticator and  show_ios_privacyidea_authenticator

### Expected outcome

Qr Codes should show side by side
### Actual outcome
![grafik](https://user-images.githubusercontent.com/10107699/82867696-94f95600-9f2b-11ea-98b5-9a21005d9055.png)

### Configuration

* **privacyIDEA version**: 3.3.3
* **Installation method**: from Ubuntu packages 18.04 Enterprise Repo
* **Python version**: Python 3.6.9 (default, Apr 18 2020, 01:56:04)
* **Operating system**: Ubuntu 18.04.4 LTS
* **Webserver**: Apache2
* **Token database**: MySQL
* **Browser**: Firefox Developer 77.0b8 (64-Bit)

**Comment by marcohald** [comment]
Happens also when just one QR Code is selected
![grafik](https://user-images.githubusercontent.com/10107699/82868457-f79f2180-9f2c-11ea-97b4-03bed06c0f4e.png)

**Comment by plettich** [comment]
Hi, thanks for the report, this was just fixed yesterday in master with #2175 so i close this.
