### ISSUE TITLE
Less prominent translation-missing marker

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2223]
When there are untranslated strings, they are marked with "[MISSING]: ".

The marking should either be less prominent, or we should completely remove it.

This can be done here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/app.js#L103

~~~javascript
 gettextCatalog.debug = false;
~~~~

or

~~~~javascript
  gettextCatalog.debug = false;
  gettextCatalog.debugPrefix = "(en) ";
~~~~

**Comment by plettich** [comment]
We could remove it only for release builds, that way we would still see it during development.
OTOH I am primarily using `en_US` so at least I wouldn't see it.
We should update the translation before the release anyway.

**Comment by cornelinux** [comment]
In pi.cfg we can have a setting like PI_TRANSLATION_WARNING = prefix.
Only if this is set, the warning displayed in the UI.
