### ISSUE TITLE
extend logged_in_user condition

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2234]
Hi,

sometimes one would want to trigger an event for specific users only (e.g. "headless" trigger-admins) or prevent WebUI-based admins to trigger over and over the same events. Currently we can only match the role of the logged_in_user, not a username or a realm.

Solution:
Add conditions for logged_in_user_name and logged_in_user_realm to further condition an event handler.

Best,

Henning

**Comment by cornelinux** [comment]
maybe you can elaborate a bit more on this (in person).
Besides the trigger-admins I do not currently see a lot of use cases.

**Comment by laclaro** [comment]
Indeed the use case are trigger-admins only and this can be also realized by creating an internal resolver and admin realm and use the logged_in_user_realm.

I'm closing this.
