### ISSUE TITLE
Radius server as user resolver?

### ISSUE THREAD

**Issue by yangboyd** [privacyidea/privacyidea#2235]
Why there is no option to add radius server as user resolver?

If I want to authenticate user against radius server, I need to pick user from other resolvers? 
Like DB resolver?

**Comment by cornelinux** [comment]
A RADIUS Server can not **return** users. 
So this can not work with our design. 
Yes, you need the users in another resolver.

**Comment by yangboyd** [comment]
> A RADIUS Server can not **return** users.
> So this can not work with our design.
> Yes, you need the users in another resolver.

Thanks for your reply.
