### ISSUE TITLE
Auditlog with start time and end time

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2254]
Sometime it would come in handy if the audit log contained the start time and the endtime of a request, thus knowing how long it took the request to be processed.

This way it will be easier to identify problems with slow components like slow LDAP connections.

The audit log could also contain the time-to-process (the difference between end and start)
This way we could even filter the audit log for long-running requests, which would also come in handy to track down installation issues.

**Comment by plettich** [comment]
We already have a (start?) time so a column with the duration should suffice.

**Comment by cornelinux** [comment]
I think having both times might be helpful if you want to sort the entires - since there are requests that start later and end earlier.

**Comment by cornelinux** [comment]
I think we could save the endtime *and* the duration. Both might be important values to sort or to search for.

**Comment by cornelinux** [comment]
Also add "startdate" to the logger audit.
Thus there would be "startdate" and "timestamp". So also external logging facilities can calculate the duration.
