### ISSUE TITLE
Hash algo during import of seed files

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2257]
It looks like as if the import of pskc (at least from yubikey personalization tool) does not honor the keylength of the seed.

It should set the hash algo of HOTP or TOTP tokens according to the length of the key or a parameter in the PSKC file (if it exists).

I think the key lenght is honored in a CSV import.

The desired behaviour for "OATH CSV" and "PSCK" should be:

1. If a hashlib is specified in the import file, use this one.
2. Determine the hash algo based on the key length.
3. *completely ignore the token default setting*

This behaviour is explicitly for /token/import endpoint. So it is similar to #1631 but not directly related.

# Todo

* [x] Check and specify the behaviour
* [x] ~~implement ~~
* [x] ~~test~~

**Comment by plettich** [comment]
- Passing the parameter `aladdin_hashlib` overwrites the `hashlib` settings for all token from the import file: [`token.py`](https://github.com/privacyidea/privacyidea/blob/fb3728f0280217ad96f2e6813014c98074436582/privacyidea/lib/token.py#L946)
- PSKC:
  - The hash algorithm should be given in a `<Suite>` element as child of the `<AlgorithmParameters>` element ([RFC6030](https://tools.ietf.org/html/rfc6030#section-4.3.4))
  - [Currently](https://github.com/privacyidea/privacyidea/blob/e24227e6a1d022a6f8db3e9470a25056af4807c9/privacyidea/lib/importotp.py#L507) we do not evaluate this correctly
  - If no hash algorithm is given, it defaults to `sha1`
  - The length of the key is **not** checked
- OATHCSV:
  - Hash algorithm is derived from key length in [`tokenclass.py`](https://github.com/privacyidea/privacyidea/blob/39beeb71ab79c6d869ebaba3b6b4703a449e37b6/privacyidea/lib/tokenclass.py#L1673)
  - Defaults to `sha1` if no key length matches
  - Called from the [parse function](https://github.com/privacyidea/privacyidea/blob/a8aa0c79ac15e773a10dd827b0ed097fa69d2d78/privacyidea/lib/importotp.py#L188)
- YubicoCSV:
  - No hash algorithm is parsed from the import file
  - In case of a `oath-hotp` type, the configured system HOTP hash algorithm is used or `sha1`
  - The `yubikeytoken` class does not need a hash algorithm (hard-coded?)
- SafeNetXML:
  - Default hash algorithm is `sha1` independent of the seed length
  - Unless the seed length is 64, then it set to `sha256`

**Comment by cornelinux** [comment]
@plettich: @timosturm has updated the pskc import. please check for any updates.

The *yubikeytoken* works with AES encryption and decryption, so it has not hashes.
The oath-htop with yubikeys is always sha1 - afaik.

**Comment by cornelinux** [comment]
I think in a first step it is sufficient to actually *document* in detail, how import works.
E.g. It is totally legit to fall back to sha1 in the case of PSKC if not hashalgo is given.

The information can be added here: https://github.com/privacyidea/privacyidea/tree/master/doc/workflows_and_tools/import

We can use styling like:

~~~~rst
..note: The import is implemented..
~~~~

Thus I assign @timosturm to review the code and add the docs.
@timosturm please check during documentation if there is the necessity to change the code.

**Comment by timosturm** [comment]
[RFC6030](https://tools.ietf.org/html/rfc6030#section-4.3.4) defines how a PSKC file should be structured. According to this, the `<Suite>` is an optional element that should be used to define the hash algorithm in the case of OTP. Following the XML Schema defined in [Section 10](https://tools.ietf.org/html/rfc6030#section-10), and more specifically on [Page 43](https://tools.ietf.org/html/rfc6030#page-43), the `<Suite>` element should look like this in the PSKC file:
```
<Suite>sha256</Suite>
```

This means, that the import function does not handle this correctly (as @plettich mentioned):
https://github.com/privacyidea/privacyidea/blob/e24227e6a1d022a6f8db3e9470a25056af4807c9/privacyidea/lib/importotp.py#L507
should read
```
            token["hashlib"] = parameters.suite or "sha1"
```

**Comment by cornelinux** [comment]
The above mentioned summary should be added to the documentation.
