### ISSUE TITLE
Allow empty database in sql resolver connection string

### ISSUE THREAD

**Issue by gallolp** [privacyidea/privacyidea#2271]
### Top-level intent

What did you try to achieve?

I'm trying to configure a SQL resolver with a connection string using a DSN instead of server:port/db.
For example in the main config file this is possible by entering the connection string:

```
SQLALCHEMY_DATABASE_URI = 'oracle+cx_oracle://<user>:<password>@<dsn>'
```

In this case the dsn is then resolved by Oracle Instant client.

This use case might apply to people using ODBC as well.

### Steps to reproduce

1. Go to Config -> Users in the Web UI
2. Add a new sqlresolver
3. Configure Driver, Server, User and Password. Leave Port and Database empty.
4. Test the connection

### Expected outcome

What do you think, how the system should have worked?

The connection should have been successful.

### Actual outcome

What did actually happen?

It failed. In the logs you can see that the connection string contained the empty database converted to string as "None".

You can see this also happens if you leave the user field blank. See the log extract below.

### Configuration

* **privacyIDEA version**: 3.3.1
* **Installation method**: PIP
* **Python version**: 3.6.8
* **Operating system**: RHEL 7.8
* **Webserver**: NGINX Unit 1.17
* **Token database**: Oracle 19

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

```
[2020-06-29 11:37:12,310][77004][139727168707200][INFO][privacyidea.lib.resolvers.SQLIdResolver:657] using the connect string oracle+cx_oracle://<user>:<password>@<server>/None
[2020-06-29 11:47:24,754][77004][139727168707200][INFO][privacyidea.lib.resolvers.SQLIdResolver:657] using the connect string oracle+cx_oracle://None:<password>@<server>/None
```

**Comment by gallolp** [comment]
This is likely because the default value of "" for this fields is not being applied correctly in https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/SQLIdResolver.py#L622

```python
        connect_string = u"{0!s}://{1!s}{2!s}{3!s}{4!s}{5!s}/{6!s}{7!s}".format(param.get("Driver", ""),
                                                   param.get("User", ""),
                                                   password,
                                                   "@" if (param.get("User")
                                                           or
                                                           password) else "",
                                                   param.get("Server", ""),
                                                   port,
                                                   param.get("Database", ""),
                                                   conParams)
```

The default value of "" in dict.get() is applied when the key is not found but in this case is found and mapped to None from the null in the database.

Hinted by this comment in StackOverflow: https://stackoverflow.com/questions/6130768/return-none-if-dictionary-key-is-not-available#comment50464375_6130800

**Comment by plettich** [comment]
This issue actually stems from how oracle handles empty strings: https://stackoverflow.com/questions/203493/why-does-oracle-9i-treat-an-empty-string-as-null
My guess is that we will run into this more often when using oracle so i would prefer a more generic solution on the SQLAlchemy level to check every string type returned from the db. I'll look into this.

**Comment by plettich** [comment]
BTW for testing i put the connect string parameters into the `Database` field of the resolver configuration:
`Database`: `?service_name=XEPDB1&encoding=UTF-8&nencoding=UTF-8`
But i am no oracle admin (far from it...).

**Comment by gallolp** [comment]
Hi @plettich thanks for yout reply.

What you describe is at the database level, similar to what has been addressed in #2218 for example.
This issue tries to address a different problem, one with the connection string builder itself.

When using the oracle instant client files `sqlnet.ora`, `tsnames.ora` or `ldap.ora` you can connect to a database using its DSN or databse alias and the driver will resolve it. See for example https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#net-service-names-for-connection-strings and also this article https://medium.com/@eikonomega/connecting-to-oracle-database-with-cx-oracle-and-ldap-5da7925a305c.
What we are trying to achieve is to call cx_oracle connect with the dsn parameter. That can be done from sqlalchemy with a connect string of the form `oracle+cx_oracle://user:pass@dsn?params`, please see https://docs.sqlalchemy.org/en/13/dialects/oracle.html#dsn-vs-hostname-connections.

For PrivacyIdea's own database it works just fine out of the box because you can write the entire connection string in the configuration file.

For the sqlresolver connections it can be done by using the dsn in the server parameter, as it is correctly the only one marked as required, and leaving the rest blank. And it should work just fine, the problem is in the code itself. The connection string builder intended default value for empty parameters is an empty string ("") however it is converting the Python value None to string ("None") because of the dict.get() method always finding the key with value None. This results in the connection strings you see in the logs above. This issue and associated PR tries to solve the connection string builder issue.

Looking back I see the title of the issue can be misleading.

Please let me know if it makes sense.

**Comment by gallolp** [comment]
@plettich sorry I believe I missundertood you. Are you saying that with other databases (non Oracle) the empty parameters in the form are stored as "" instead of NULL in the RESOLVERCONFIG table?. If that is the case then you are absolutely right and it comes down to the same problem of Oracle treating the empty strings as null and you can ignore my long comment above. Sorry about that. If other databases also store null then this fix applies.

**Comment by plettich** [comment]
@gallolp correct, we read the resolver parameter from the db. There is no impact from Your patch (as far as i can see) so i merged it. As far as i know only oracle behaves this way. There are possibilities to alleviate this by using custom types in SQLAlchemy but this looks like a far more complex undertaking.

**Comment by gallolp** [comment]
@plettich Thank you very much!
