### ISSUE TITLE
Length and Contents of registration code

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2284]
**Is your feature request related to a problem? Please describe.**

The registrationcode contains characters, that are hard to read and differentiate.
In some cases the registrationcode needs to be read and typed.

**Describe the solution you'd like**

Add a policy in scope enrollment and action

* registrationcode_length
* registrationcode_contents

The contents would be passed as ``characters`` keyword argument in generate_password:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/registrationtoken.py#L167

Enrollment policies should be defined in the tokeclass here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/registrationtoken.py#L133

# Some thoughts and discussions

Should we do a decorator, that modifies the actual input?
So should the ``/token/init?type=registractioncode`` actually come with these additional parameters "length" and "contents"?
Or should it be settings on the lib level?

I think adding these parameters to the API and have the decorator overwrite these, make more sense.

**Comment by laclaro** [comment]
If we add the parameters to the API and there is no policy set to overwrite them, one could enroll a very weak registration token with a single number.
Should we prevent this somehow by restricting the minimum length by default or is this okay?

**Comment by cornelinux** [comment]
The policydecorator could, if no policy is set, still set the length to 24 and the contents accordingly.
