### ISSUE TITLE
Browser autocomplete in token assignment username field

### ISSUE THREAD

**Issue by moschlar** [privacyidea/privacyidea#2292]
### Top-level intent

I want to assign a token to a user.

### Steps to reproduce

1. /#!/token/enroll//
2. Begin typing username in form field

### Expected outcome

I should (only) see the user list generated by privacyidea

### Actual outcome

The username autocomplete list from the browser is shown in front of the list of privacyidea.
Pressing escape leads to both lists being closed...

From skimming through https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion it seems to me that the only proper way to prevent this is to rename the form fields to something other than `username`...

### Configuration

* **privacyIDEA version**: 3.3.3
* **Installation method**: PyPI
* **Python version**: 3.7.3
* **Operating system**: Debian 10
* **Webserver**: Nginx/UWSGI
* **Token database**: (MySQL, PostgreSQL, ...) MySQL
* **Browser**: Firefox 77.0

### Screenshot (instead of log file ;-) )

![Screenshot from 2020-07-10 11-52-43](https://user-images.githubusercontent.com/228095/87141811-ec694080-c2a3-11ea-900b-b9b435eeab64.png)

**Comment by moschlar** [comment]
Related, but not sufficient (anymore): #442

**Comment by cornelinux** [comment]
Thanks for bringing this up.
We will look into this.

**Comment by laclaro** [comment]
We may use `autocomplete="new-password"`

**Comment by laclaro** [comment]
There may be other places in the webUI, where we do not want autocompletion. PR #2400 fixes the mentioned one and the token details (e.g. for OTP testing).

@cornelinux Shall we replace all ocurrences of autocomplete="no" by autocomplete="new-password"? Apparently autocomplete="no" is not honored anymore by modern browsers.

**Comment by cornelinux** [comment]
@laclaro The question is, if all ``autocomplete="no"`` fields are actually password fields or recognized "login"-fields.
But, yes, we should look out, if there are further occurrences.

**Comment by laclaro** [comment]
@moschlar Are you feeling like checking #2401?
