### ISSUE TITLE
make the user_obj available in the before-method of /auth

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2303]
At the /auth endpoint, we do not have the "user" available so user-specific event handlers cannot be uses in a self-service scenario at the WebUI.

One specific requirement was to enroll tokens ~~after~~ **before** a successful login at the webui.

Note: It is not necessary, to differentiate different users or usernames, but the user object is needed, so that e.g. the email is available to notify or the user_obj is available to enroll a token to this very user. It is not about *conditions* but about having the user_obj in the context at all.

**Comment by cornelinux** [comment]
Check:

* Which user (userobject) is used in the event handler
* Which one is available after auth req... probably ``logged_in_user``. 

Can we safely use this or not?
What is, if the role is admin, and if this is a local admin or not?

**Comment by cornelinux** [comment]
The requirement was to **enroll token** in **pre events**. 
Why does it work in validate/check? 
So why wouldn't it work in /auth?

**Comment by cornelinux** [comment]
In the /validate/check request in the before-method the user object is set
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/validate.py#L125

This could also happen in the before-method of the auth endpoint here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/auth.py#L90

But this can not easily be done without a logical challenge. Why? What is different?

The validate endpoint is only called by userobjects existing in user resolvers.
The auth endpoint is called by userobjects in existing user resolvers but it is also called by internal admins. I.e. in the before-method we can not know yet, if the user, who tries to authenticate, is an internal admin or a user in the user-resolver.

Imagine there is a user as internal admin called "userA" and if there is a userresolver-user called "userA". Note: Both users can login as long as they have different passwords.
But if you would generate a user object in the before-method, then the following can happen:

The admin "userA" tries to log in. The before-method does not yet know, if this is an internal admin. It find the user in the resolver and triggers a pre-event. The admin is logged in.
THus, an admin would automatically create a token in the original example, each time he logs in.

**Comment by laclaro** [comment]
Is my input still needed? The primary use-case requested was to trigger an event handler before the user actually logs in.

One request I remember was like this: If the user has no token, enroll a challenge-response-capable one and use it for the WebUI login.

**Comment by cornelinux** [comment]
The coding is not a big issue - rather an issue of a few lines of code.
If you have some suggestion for the documentation, in regards to possible side effects, this would be great. Maybe we can discuss this in a direct "chat".

**Comment by cornelinux** [comment]
Suggestion: Write a log message, if there are duplicates of internal admins and resolvers.
This might be problematic, due to the code flow. Check, if we can do this simply if a user_obj is found and quickly check, if a local admin with the same name exists.
