### ISSUE TITLE
Can't set the email address of an Email Token using the /token/set/(serial) endpoint

### ISSUE THREAD

**Issue by FedeOmoto** [privacyidea/privacyidea#2305]
### Top-level intent

What did you try to achieve?
Set the email address of Email Tokens using then **/token/set/(serial)** endpoint.

### Expected outcome

Being able to set the email address of Email Tokens using then **/token/set/(serial)** endpoint.

### Actual outcome

It's currently not possible to set the email address of an Email Token through the **/token/set/(serial)** endpoint.

### Configuration

* **privacyIDEA version**: 3.3.1
* **Installation method**: github, PyPI, RHEL package dependencies
* **Python version**: 3.6.9
* **Operating system**: RHEL 7.8
* **Webserver**: NGINX Unit 1.17.0
* **Token database**: Oracle 19c (using SQLAlchemy cx_oracle dialect)

**Comment by cornelinux** [comment]
Thanks a lot for your idea and pull request.
But the email address of a token is a tokentype specific attribute. Currently there are no endpoints or "set" options for these token specific attributes.

The email address is stored in the tokeninfo.
So if you are only using the API anyways, I recommend that you use the already existing API:

~~~~http
POST /token/info/<serial>/email

value=fedo@maildomain.com
~~~~

See https://privacyidea.readthedocs.io/en/latest/modules/api/token.html#post--token-info-(serial)-(key)

**Comment by cornelinux** [comment]
Closing this for no further feedback.
