### ISSUE TITLE
Boolean options saved as strings in the db might not work as expected

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2310]
Currently we save Eventhandler options in the database as strings (since they can be of several types).
When using boolean options this might lead to a bug since we never check the type.
- i.e. when an option is not set, there is no entry in the database -> `False`
- If the option is enabled, the value `"True"` will be written into the db. This will result in `bool("True")` -> `True`
- If the option is then disabled again, the value `"False"` will be written to the db: `bool("False")` -> `True`

This can be seen in the [`UserNotificationEventHandler`](https://github.com/privacyidea/privacyidea/blob/972b103011ee366982e52b7b7ccadf4d90541f06/privacyidea/lib/eventhandler/usernotification.py#L354).
The `EventHandlerOption` Table already contains a column `Type` which is currently unused.
We could check the action type whenever we use an option and cast accordingly or we can cast once when reading from the db (if we know the type at this point).

**Comment by cornelinux** [comment]
We could use a function, that wraps all event handler actions, checking if this is a boolean action and running it through `is_true`.
This way we do not have to manually check, which action is boolean.
