### ISSUE TITLE
PSKC import does not verify ValueMac of encrypted token secrets

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2312]
In [RFC6030 (PSKC)](https://tools.ietf.org/html/rfc6030#section-6.1.1) a method is described to verify token key data with MACs. We currently [implement](https://github.com/privacyidea/privacyidea/blob/35b705a372d87ffb8e0ccbd81d1765c32e451509/privacyidea/lib/importotp.py#L627) this for export to PSKC-Files but we don't check it when importing the PSKC-File.

TODOs:
- [x] Implement verification of MAC values
- [x] Fix export of tokens / calculation of MAC values on export
- [x] Add parameter to import `validate_mac`:
    - `check_fail_hard` (default) - no import on invalid mac
    - `no_check` - ignore mac on import
    - `check_fail_soft` - only import valid mac
- [x] Add setting to UI

**Comment by cornelinux** [comment]
The import could contain a parameter (in the API and the UI), that tells something like "ignore MAC verification". To make verifying the default and only ignore, if there is a problematic PSKC file.

**Comment by timosturm** [comment]
Output of [`export_pskc`](https://github.com/privacyidea/privacyidea/blob/35b705a372d87ffb8e0ccbd81d1765c32e451509/privacyidea/lib/importotp.py#L696) and [test case](https://github.com/privacyidea/privacyidea/blob/35b705a372d87ffb8e0ccbd81d1765c32e451509/tests/test_lib_importotp.py#L304) are mismatched, the `ValueMac` is not at the same place in the xml. How should that be handled? @cornelinux @plettich 

Example in test:
```
<Data>
                 <Secret>
                     <EncryptedValue>
                         ...
                     </EncryptedValue>
                     <ValueMAC>Su+NvtQfmvfJzF6bmQiJqoLRExc=
                     </ValueMAC>
                 </Secret>
                 ...
             </Data>
```

Output of `export_pskc`:
```
<Data>
                    <Secret>
                         <EncryptedValue>
                             ...
                         </EncryptedValue>
                     </Secret>
                     <ValueMAC>{value_mac}</ValueMAC>
                    ...
                </Data>
```

**Comment by cornelinux** [comment]
According to RFC6030 in chapt 4.1 the ``ValueMAC``  is a child element of secret. 
Thus, our export is wrong. If necessary, please open an issue for fixing the export. Thanks!
