### ISSUE TITLE
Failing with 500 error for Push notification response from authenticator app

### ISSUE THREAD

**Issue by deshmukhmandar** [privacyidea/privacyidea#2313]
Setting up push notification flow

### Steps to reproduce
1. Setup push notification as per the documentation 
2. Able to send challenge to mobile device (android)
3. PI server failing with 500 error for allow response from mobile application

### Expected outcome
Allow response from Mobile application (PI authenticator) should process successfully

### Actual outcome
Failing with 500 error and following error stack. 
  File "/Users/mandar/devcodes/privacyidea/venv/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1382, in _handle_key_loading_error
    raise ValueError("Could not deserialize key [data.")]

Attached log.
(url
[privacyidea.log](https://github.com/privacyidea/privacyidea/files/4998078/privacyidea.log)
)

### Configuration
* **privacyIDEA version**: latest code from GitHub
* **Installation method**: github
* **Python version**: latest
* **Operating system**: Mac
* **Webserver**: Running in dev mode using command ./pi-manage runserver
* **Token database**: default lite database.

### Log file
(url
[privacyidea.log](https://github.com/privacyidea/privacyidea/files/4998078/privacyidea.log)
)

**Comment by plettich** [comment]
Does this error still occur? We changed quite a lot in the push-token code.

**Comment by plettich** [comment]
No feedback, closing this.
