### ISSUE TITLE
Update the docs about yubikey enrollment

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2318]
We should update the docs about yubikey enrollment.
https://privacyidea.readthedocs.io/en/latest/tokens/tokentypes/yubikey.html?highlight=yubikey#using-the-yubikey-personalization-gui

Especially on windows is an easy way to also mass enroll yubikeys with the personalization tool and then import the seed file to privacyIDEA.

We can add this as two alternatives under 6.3.1.25.1.

1. Mass enroll
2. AES single token enroll

To do so, we can use these two screenshots.
![yubikey-personalization-settings](https://user-images.githubusercontent.com/1908620/89386282-255ccf80-d701-11ea-971e-309bf25e8c0e.png)
![yubikey-personalization-windows](https://user-images.githubusercontent.com/1908620/89386286-25f56600-d701-11ea-809a-7fbe2c1fc723.png)

**Comment by plettich** [comment]
We should make sure to support the formats correctly: See #2257

**Comment by cornelinux** [comment]
No problem. Yubikey in HOTP mode is always sha1.

**Comment by cornelinux** [comment]
@laclaro This is somehow a duplicate of #1506.

**Comment by laclaro** [comment]
I created a PR but don't know how to treat the section `Redirect api url to privacyideas /ttype/yubikey`
