### ISSUE TITLE
Unify backend and frontend translation

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2322]
# Is your feature request related to a problem? Please describe.

We have two ways of finding and translating strings.
In the Python code in the backend and in the frontend/angular.

Both parts are translated separatedly and both languages are identified separately.
Thus the server could have another language configured than the browser/frontend.

## Exceptions

We are rasing a lot of exceptions. These exceptions do not contain a translation. This was originally probably done, because the exception is a technical error. However, the text of the exception is contained in the JSON response and could be displayed to user. Should we translate it?
Note: Also original Python exceptions could be contained in the response. These are also not translated and are not translatable.

## Possible solution

It would be great, if the browser would send it's configured language to the backend and the backend would take this into account and pass the response messages according to the language of the browser.

This way, the backend could pass different languages to different browsers!

Currently the browserlanguage is determined by the preferred language settings in the browser. In a second step we could
let the user choose the language.

**Comment by laclaro** [comment]
We may use different approaches to send the language to the backend (parameter, header, endpoint, ...). I suggest to use the standard Accept-Language header like
```
Accept-Language: en,en-US,de;q=0.6
```
privacyIDEA would then interpret this for every request and use the appropriate message language.

**Comment by cornelinux** [comment]
@plettich please check if you really already give the browserlanguage to the server backend.

**Comment by plettich** [comment]
@cornelinux this is done here:
https://github.com/privacyidea/privacyidea/blob/60c0ca076a90e983d03f8d31fed09384a1189581/privacyidea/app.py#L212

**Comment by cornelinux** [comment]
@plettich 
I close this since we have one language.
I opened a new issue #2528 which states it more precisely.
