### ISSUE TITLE
link to privacy statment (GDPR)

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2325]
If privacyIDEA is publically facing the company running privacyIDEA should be able to provide a link for the privacystatement.

This link should be available in the footer of the website availble without the need to login.

The URL should be configurable via policy.

As long as no URL is configured the privacy statement would not be displayed.

* [x] Define policy
* [x] pass config to UI
* [x] enhance HTML template

**Comment by laclaro** [comment]
- add webui policy in policy.py
- add policy value to render_context in login.py
- use this value to display the link in baseline.html
