### ISSUE TITLE
Policy setrealm is not working

### ISSUE THREAD

**Issue by thisisnotacompanyaccount** [privacyidea/privacyidea#2332]
We try to import Active Directory Users as PrivacyIDEA Administrators and followed these steps:

 * Two ldapsresolver
   ** one for normal users (ad_user)
    ** one for administrators (ad_admin)
 * Two realms
   ** ad_user with ad_user and ad_admin as resolvers (set as default)
   ** adminrealm with just ad_admin as resolver

As expected, we've got normal users and admins in our default_ad realm and only administrators in our adminrealm.

Now we want the admins to login without adding @adminrealm and after following [this explanation](https://privacyidea.readthedocs.io/en/latest/policies/authorization.html#setrealm) we've created a policy with the following settings:

 * Name: set_admin_realm
 * Scope: authorization
 * User-Realm: default_ad
 * User-Resolver: ad_admin
 * Action: setrealm: adminrealm

Unfortunatly this policy is not applied at all when the user is logging in thus the admin is logged in as normal user.

### Configuration

* **privacyIDEA version**: PrivacyIDEA 3.3.3
* **Installation method**: Ubuntu Packages
* **Python version**: 3
* **Operating system**: Ubuntu 18.04.4 LTS
* **Webserver**: Apache HTTPD
* **Token database**: PostgreSQL

### Log file

[privacyidea_setadminrealm-censored.log](https://github.com/privacyidea/privacyidea/files/5101790/privacyidea_setadminrealm-censored.log)

**Comment by cornelinux** [comment]
This works as design. The ``setrealm`` policy only works vor ``/validate/check``.

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/validate.py#L207

**Comment by thisisnotacompanyaccount** [comment]
Thank you for your response. Is there something similar possible for logging in via web interface?

**Comment by cornelinux** [comment]
You could check the mangler handlers:
https://privacyidea.readthedocs.io/en/latest/eventhandler/index.html#available-handler-modules
