### ISSUE TITLE
Oracle returns None instead of empty string

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2334]
Oracle databases act differently when it comes to empty or nonexisting values: It returns None instead of an empty string, which leads at several places in the privacyIDEA code to complications.

Cases where the issue comes up
* If no token pin is set, oracle returns None and privacyIDEA tries to check if this pin is encrypted, but is shouldn't.
  https://github.com/privacyidea/privacyidea/blob/4d59eab2941308f742927851e3e4a45eee7ae739/privacyidea/models.py#L411

@plettich had a couple of ideas how we solve this issue most elegantly

**Comment by cornelinux** [comment]
The None-Empty-String problem is already fixed for version 3.4 and the is_pin_enrcypted.
See https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L448

However, it could also occur at other places. 
We should also check, if there is a generic solution or identify remaining occurrances.

**Comment by cornelinux** [comment]
Check for audit search date.

**Comment by plettich** [comment]
Some Oracle related issues:
- [ ] searching for a date in the audit log fails (probably because the cast to varchar does not specify a length)

**Comment by cornelinux** [comment]
* [ ] Check where in the code strings are stored and returned from the DB.

**Comment by plettich** [comment]
There are just too many strings in the db to check.
We can either:
- perform the not-NULL check on every read from a string from the db or
- get our unit-tests run on Oracle.

Most of the functionality works well with Oracle. We just can't predict on which obscure setting it might fail in the future.

**Comment by cornelinux** [comment]
I like the 2nd one - run unittests on oracle.

So I would recommend going for this as a middle range goal and then do more oracle code cleanup based on these results.
