### ISSUE TITLE
First admin policy applies to all admin users

### ISSUE THREAD

**Issue by gallolp** [privacyidea/privacyidea#2338]
### Top-level intent

What did you try to achieve?

Set an admin policy to match a specific internal admin account.

### Steps to reproduce

1. Fresh install
2. Add the first internal admin with `pi-manage admin add admin`
3. Add the second internal admin with `pi-manage admin add service`
4. Create an admin policy to match admin user "service" with the desired actions, for example:

```
{   'action': {   'assign': True,
                      'delete': True,
                      'disable': True,
                      'enable': True,
                      'enrollTOTP': True,
                      'reset': True,
                      'resync': True,
                      'revoke': True,
                      'set': True,
                      'setpin': True,
                      'setrandompin': True,
                      'settokeninfo': True,
                      'tokenlist': True,
                      'tokenrealms': True,
                      'unassign': True
    },
        'active': True,
        'adminrealm': [],
        'adminuser': ['service'],
        'check_all_resolvers': False,
        'client': [],
        'conditions': [],
        'name': 'testAdminPolicy',
        'priority': 1,
        'realm': [],
        'resolver': [],
        'scope': 'admin',
        'time': None,
        'user': []
}
```
5. Login with "admin" and you will see the policy applied even tho it should only match "service"

### Expected outcome

What do you think, how the system should have worked?

User "admin" should be able to do everything.
User "service" should be able only to enroll and work with TOTP tokens.

### Actual outcome

What did actually happen?

Both "admin" and "service" users are restricted to the actions in the policy.

### Configuration

* **privacyIDEA version**: 3.3.3
* **Installation method**: pip
* **Python version**: 3.6.8
* **Operating system**: RHEL 7
* **Webserver**: NGINX Unit
* **Token database**: Oracle 19

### Workaround

Create two policies:

1. One admin policy to match adminuser "admin" and enable all actions
2. One admin policy to match adminuser "service" and enable needed actions

In this case the policies are correctly applied.

**Comment by cornelinux** [comment]
Your expectation is wrong.
And probably your observation is wrong, too.

The policy is most likely **not** applied for the admin user "admin".
But **no** policy is applied for the admin user "admin", so the "admin" has actually **no** rights.
Please check again!
If the "admin" is supposed to have all rights, you need to define a policy for him with all rights.

The workaround you described is actually the designed behaviour, that is described in the 
documentation. Please reread.

**Comment by gallolp** [comment]
@cornelinux I double checked and you are right. I read the [admin policies](https://privacyidea.readthedocs.io/en/latest/policies/admin.html#admin-policies) documentation before posting and found the note "As long as no admin policy is defined all administrators are allowed to do everything.". I thought the default for an admin with no policies was allow all. But it seems with no policies at all the policy engine is like "turned off" and with at least one admin policy active is deny all by default and then apply matching policies.

Sorry for the mistake.

May I suggest the addition of a warning to the documentation?. For policies targeting the local admin accounts (ie. the ones added by pi-manage admin) is easy to get locked out requiring access to the cli. A little note to clarify that if you would like to keep the first superuser account make sure to add the allow all policy before activating policies for other local accounts.

**Comment by cornelinux** [comment]
Hi @gallolp 
I thought we had this explained / warned.
Whatever, please give us a hint, where exectly you would have expected such a warning or where exactly it might have helped you. Then we will luckily add this.

**Comment by gallolp** [comment]
I was thinking of something like: 

> "Please be aware that after enabling your first admin policy all admin users not matching will have no rights. Make sure your currently logged in admin account is covered by the policy."


This is to avoid a scenario where you log in using the local admin and set up a policy for a new super realm (ie. an ldap resolver). Since your local admin is not covered you are locked out from the web ui. And if your ldap admins don't have policy management rights (policywrite, policyread and policydelete actions) then you have to resort to the cli.

![image](https://user-images.githubusercontent.com/25209188/91356489-2647c500-e7c6-11ea-9871-cf1f45f5b309.png)

⬆️ that's what I got for not reading the doc well hehe 😊

**Comment by cornelinux** [comment]
Hi @gallolp ,
thanks, yet.
But **where** did you miss this note. I think we have a lot of information in the docs. And I think we also have this information.

But for me the important question is, how users are using the docs. So where were you reading about admins and policies and where would you have need this note.
Thanks a lot.
