### ISSUE TITLE
parallel user filter searches in UI

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#234]
In the user view filtering for a username in a large directory will result new issued requests, that will start when old requests are not finished.

Thus long-running request1 will overwrite shorter-running request2 with the old results from request1.

If a new request is issued older results should be either dropped or older requests should be canceled.

**Comment by berndnicklas** [comment]
Hello Cornelius,

after migrating a bunch of tokens from LinOTP I realized this bug seems to exist for the tokens view, too. Can you confirm this?

Best regards,

Bernd

**Comment by cornelinux** [comment]
I assume so. But this was not an issue in any setup, yet. 
Since the database (where the tokens are fetched) returns quicker than the LDAP.

**Comment by berndnicklas** [comment]
Possibly it is related to having the database server on a seperate machine, which is not a standard setup included in the privacyIDEA Debian packages. Or possibly I have to look at the (possibly conservative) settings of our database installation. Anyway, the existence of the problem shows, that the behaviour of the Web UI should be changed (e.g. to cope with slow databases or big token tables).

**Comment by cornelinux** [comment]
right.
