### ISSUE TITLE
Isssue Invalid Credentials 401 from server Public

### ISSUE THREAD

**Issue by tainguyenbp** [privacyidea/privacyidea#2341]
**Currently, I am using the PrivacyIDEA to manage centralized ssh key with the image below:**
![image](https://user-images.githubusercontent.com/14048946/90848676-ab327900-e397-11ea-82ed-23c1a4071ae2.png)
**My path and file authen in the /etc/privacyidea/authorizedkeyscommand**
_[Default]
url=https://sshkey.test.com/
admin=admin
password=admin
nosslcheck=False_
**I'm having an issue, I didn't get publickey when run command _**privacyidea-authorizedkeys ubuntu**_, Although, I added keyssh and assign it for server access from server in DC Public with error below:**
_[root@ubuntu ubuntu]# privacyidea-authorizedkeys ubuntu
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'sshkey.test.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Traceback (most recent call last):
  File "/bin/privacyidea-authorizedkeys", line 135, in <module>
    main()
  File "/bin/privacyidea-authorizedkeys", line 111, in main
    no_ssl_check=args.nosslcheck or nosslcheck)
  File "/usr/lib/python2.7/site-packages/privacyideautils/clientutils.py", line 96, in __init__
    self.set_credentials(username, password)
  File "/usr/lib/python2.7/site-packages/privacyideautils/clientutils.py", line 135, in set_credentials
    raise Exception("Invalid Credentials: %s" % r.status_code)
Exception: Invalid Credentials: 401
Error: Invalid Credentials: 401_
**But, the server in DC Local can get publickey with user ubuntu**
[root@server3 ubuntu]# privacyidea-authorizedkeys ubuntu
_/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAhqEYlFQqh+ji7XGMEfcq33+BAgE2o7zhAep+h2/r8hoTJdFzUZrapIUGqVP9X5nqiWDvwU0fHqgSnKGybdbjbUnCO9h9adO6EhY6dFWcUz+wedUh5LvoEMxQdqRLNJfe2Fe9JsusL63z9ZYTz3meL3pfrUwxt6AGczfV/ihvkUfTHX01xUfMUII4cjMOAnWw95kq11dO0rWzZ2dXOjD8LMMnFG5hd3jNRQOJgsbT/klJGMQAzmSMpj87vepr4VKjJVt85vMa8JuesJ2B0jGYtZIPZUlgPwOimizQwBXvTrX5f7M38P65QgvSkxw1W0WQhhJh6uPP8hRjaqWm0WGfow== ubuntu@localhost.localdomain_
**Sorry, my english is not good
Please help me to solve this issue?
I can't fix it**

**Comment by tainguyenbp** [comment]
> Thank you for filing an issue and sharing your observations or ideas. Please be sure to provide as many information as possible to help us working on this issue.
If you tell me what you need, the comment below this issue

**Comment by tainguyenbp** [comment]
Please help me to solve this issue?

**Comment by laclaro** [comment]
For specific requests, please visit https://community.privacyidea.org. Please describe your problem there and what you already read and did trying to solve it.

**Comment by tainguyenbp** [comment]
> For specific requests, please visit https://community.privacyidea.org. Please describe your problem there and what you already read and did trying to solve it.

tks you very much

**Comment by laclaro** [comment]
Since you got in touch with the community, I close this.
