### ISSUE TITLE
Multi-Challenge: Resync Token

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2349]
We could use multi-challenge to resync a token, which is out of sync.

The "problem" is the following:

If the user enters a wrong OTP value, we do not know, if this is a wrong OTP value by a legitimate user with an out-of-sync-token or if it is a guessed value by an attacker.

There are two approaches:

**a)** We need to calculate the next 1000 values to see, if this is a valid OTP value in this time windows. Only if we find a future OTP value, we can ask for a 2nd OTP value.

* We calculate up to 1000 OTP values on each first request.
* An attacker would know, if he guessed the a correct on-of-a-1000 values.

**b)** We could simply **assume** that the wrong OTP value is an OTP value from an out of sync token and immediately ask for the next OTP value.

* We calculage up to 1000 OTP values on each 2nd request.
* We very often would ask for a 2nd OTP value, each time either the user mis-types a value or an attacker mis-guesses a value.

Both scenarios do not look that opimal.

**Comment by laclaro** [comment]
I think a mistyping is more probable, so In b), we could also ask the user if he/she mistyped the OTP like:

"The given OTP 123456 is not valid. In case you mistyped the OTP, please type it correctly. In case the given OTP is correct, please type the next one to resync your token."

To prevent an attacker to DDOS, we may add a logic to count resync attempts and disable tokens after a number of attempts or something the like...

**Comment by cornelinux** [comment]
If autoresync is enabled, we can send whatever challenge text: "....please try the next OTP value...".

This could simply be a new authentication request. (or we need to omit the PIN, if the first auth request was PIN+OTP).

Add a new decorator in `lib/challengeresponsedecorators.py` named like `generic_challenge_response_resync_token`.

If there returned token actually has an `otpc1` set (which indicates, that the first OTP value matched in the sync window), then we can set the challenge mode in the response.
