### ISSUE TITLE
Cbor2 error

### ISSUE THREAD

**Issue by gitTBE** [privacyidea/privacyidea#2363]
Good Morning all,
i performed the installation steps on a ubuntu 20.04.

Once I did the whole thing as a user with SUDO rights, the second time as root.

In both cases I get the following errors with the command: pip install -r requirements.txt or pip install -r tests/requirements.txt
![cbor2_1](https://user-images.githubusercontent.com/69964076/91702174-a2505d00-eb78-11ea-8d8f-007d8fa0f36a.png)
![cbor2_2](https://user-images.githubusercontent.com/69964076/91702173-a2505d00-eb78-11ea-85dc-0bb42941e9b1.png)

What did I miss?

Thanks for your support.

**Comment by plettich** [comment]
Hi, this is a known issue, the cbor2 package which we pinned needs to compile some libraries when installed. If no C/C++ toolchain (gcc) is installed, the installation fails.
If You are installing privacyIDEA directly with pip inside a virtualenv You can first install the most recent `cbor2` package which does not need an extra compile step.
If You install via the `requirements.txt` file, You can download and modify it (`cbor2==5.1.2`). This should work as well.

**Comment by gitTBE** [comment]
Thank you very much for the info. It worked great.
