### ISSUE TITLE
problem with challenge_text_header and multi challenge

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2364]
The policy challenge_test_header causes the challenge text "Please enter a new PIN" in a pin change via validate (#2163) not to be sent to the client.

The policy for the challenge header comes into play as a post policy
https://github.com/privacyidea/privacyidea/blob/ef8f6bdb5541f02238db215cc65e8ecaa595a5e7/privacyidea/api/validate.py#L195

If the policy is set, the message is expected in content -> detail -> messages, but the multichallenge response text happens to be in a field called content -> detail -> message (singular). content is the json-response of the validate/check request.

https://github.com/privacyidea/privacyidea/blob/7ee038a30fad36021ab0bbacbfd05e611ba42680/privacyidea/api/lib/postpolicy.py#L723

Maybe this should be set somewhere in the [challengeresponsedecorators.py](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/challengeresponsedecorators.py).

_If_ there is always only one item in the messages list, we could simply add a line after the message is set in the reply_dict

```python
def _create_pin_reset_challenge(token_obj, message, challenge_data=None):
   ...
    reply_dict["message"] = message
    reply_dict["messages"] = [message]
```

**Comment by cornelinux** [comment]
In the ``_create_pin_reset_challenge`` we do not have the originial ``reply_dict``. 
In a pin change the "messages" in the reply_dict is probably always empty, but probably not in other cases.

I will check and either put it to ``_create_pin_reset_challenge`` or  ``generic_challenge_response_reset_pin``.
