### ISSUE TITLE
Limit audit log view for e.g. 1st level helpdesk

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2372]
Audit log, only show selected columns in audit log and only show selected actions.

This could be helpful for 1st level helpdesk users. They e.g. might only want to take a look at actions like /validate/check and would not be interested in information like "administrator".

Via policy we could limit the view to certain columns and actions.

**Comment by cornelinux** [comment]
A policy could not only allow to disable columns but also resort the columns in the webui.

This would be challenging, since it would not only be the data that is returned by the REST API but also the view in the WebUI.
Maybe in this case, this should be two different policies and two different issues. I.e. the question about "resorting columns" is **out of scope** of this issue.

At the moment the REST API audit endpoint returns s.th. like this:

~~~~
auditdata: [,…]
0: {action: "POST /auth", action_detail: "", administrator: "super", clearance_level: null, client: "::1",…}
action: "POST /auth"
action_detail: ""
administrator: "super"
clearance_level: null
client: "::1"
date: "2020-09-24T10:22:09"
info: "internal admin"
log_level: null
missing_line: "FAIL"
number: 23195
policies: "web,web"
privacyidea_server: "localhost"
realm: "netknights"
resolver: null
serial: null
sig_check: "OK"
success: 1
~~~~

So the policy could lead to that the response e.g. does not contain "loglevel" and "info" and the UI would realize that these data is missing on not display the columns

## Policy config

* scope: admin and user 
* action: hide_audit_columns=sig_check info resolver

These hidden columns would then be removed from the REST response.

**Comment by laclaro** [comment]
- [x] Policy and API done in #2445
- [ ] Hide empty columns in the WebUI
