### ISSUE TITLE
User is displayed the UI dashboard

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2384]
In version 3.4 *sometimes* a normal user is presented the dashboard. It looks like there is a initialization issue.

It can be reproduced as follows:

1. configure a webui dashboard policy for admins.
2. login as admin to the webui.
3. logout
4. login as normal user to the webui - he will see the dashboard.

It does not happen, if the user logs in on a "fresh" browser.

**Comment by laclaro** [comment]
Whenever this happens, the user does only see information on the dashboard, he/she is allowed to (e.g. the number of own tokens).

**Comment by cornelinux** [comment]
It is probably 

      $scope.startRoute = "/dashboard";

in loginController.js. We probably need an ``else`` branch.
