### ISSUE TITLE
Concurrent /token/init requests may result in db deadlock

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2396]
If two /token/init requests are received in parallel, a deadlock can occur which causes privacyIDEA to fail writing tokenowner and tokeninfo data to the database.

The DEBUG trace is here:

https://gist.github.com/laclaro/539d88a8a6d12d67f31c71db10ea209b

Result: The token is created, but no data is written to the tokeninfo or the tokenowner table.

Note, that really concurrent request tend to be rare also in "high-load" systems.

**Comment by cornelinux** [comment]
@laclaro Could you please add some information about the setup? Type of token database, resolver types, SQL Audit in same DB? Thx.

**Comment by laclaro** [comment]
It is a setup of privacyIDEA 3.4 on Ubuntu 18.04
- MySQL Audit Log
- MySQL Internal Resolver (table within database "pi")
- /token/init issued by admin user providing username to assign the token

**Comment by laclaro** [comment]
The exception thrown by the ldap resolver is different:
https://gist.github.com/laclaro/e3cae46c8514fc0ecc6ac419ceb4f0f1

**Comment by laclaro** [comment]
An OpenLDAP system (UCS) responds in the same way as the SQL resolver, described in the first post.

**Comment by cornelinux** [comment]
Also see #1268

**Comment by laclaro** [comment]
I tried to use the code implemented by https://github.com/privacyidea/privacyidea/commit/88d03b1893b01056d5c6f58296e688f7fbb14d66, but without success. The rollback is issued, but the next try seems to run into the same exception.

The exception seems to occur at
https://github.com/privacyidea/privacyidea/blob/d8f86e7284ae179a2f7315cb0489dc5b0f7b2ccf/privacyidea/models.py#L322

**Comment by cornelinux** [comment]
@laclaro Honestly I could not find the line of interest in the long log files. But please check, if #2794 is actually the same and would also solve this issue.
