### ISSUE TITLE
Rework the note about privacyIDEA running in community mode

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2397]
Currently it is not clear to admins that privacyIDEA will start showing the welcome info again, if there is no subscription and the number of users with tokens exceeds 50 users.

The text of the policy only claims: "If this checked, the administrator will not see the welcome dialog anymore."
We should be more specific here and discuss other possibilities like user numbers or easier notifications like the one used for debug mode.

**Comment by laclaro** [comment]
The debug notification is stated here:
https://github.com/privacyidea/privacyidea/blob/a8ad48a52cbc6520420c4eba22ab21bdef13ae27/privacyidea/static/templates/menu.html#L1

**Comment by laclaro** [comment]
I think a banner would be nice. Then we do no have to change the policy text.

Such a banner would be easy to hide with any ad-blocker.

**Comment by cornelinux** [comment]
* no subscription:
  - no hide_welcome: display welcome dialog
  - hide_welcome: hide it ;-)
  - hide_welcome + >50:  only the last dialog of the 3step welcome

* with subscription:
   - valid subscription + no_hide_welcome: try not to show welcome
   - valid subscription + hide_welcome: hide welcome
   - expired or exceeded subscription: show new banner with link to "more info" and to "view subscription".
