### ISSUE TITLE
Choose more secure configuration defaults

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2408]
The configuration for SMTP server, privacyIDEA server or LDAP resolvers default to not using TLS and no certificate verification.
Better defaults or additional documentation may reduce the chance of accidental misconfiguration by the admins.

We have the following occurances:

* [x] Config -> SMTP Server: ``Use TLS``, check it by default.
* [x] Config -> privacyIDEA Server ``Verify the certificate``, check it by default
* [x] Config -> SMS Gateways (HTTP Gateway), default ``Check_SSL`` to "yes".
* ~~Config->User->New LDAP server: already defaults to ``verify TLS``.~~

**Comment by cornelinux** [comment]
Maybe we can also change the default of the API layer or reverse the logic.

**Comment by NNLemling** [comment]
could someone tell me what happend here exactly?

**ng-model="params.tls"
ng-checked="isChecked(params.tls)"**

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/config/views/config.smtp.edit.html#L104

Many Thanks

**Comment by cornelinux** [comment]
~~~~javascript
    $scope.identifier = $stateParams.identifier;
    if ($scope.identifier) {
        // We are editing an existing SMTP Server
        $scope.getSmtpServers($scope.identifier);
    } else {
        // This is a new SMTP Server
        $scope.params = {
            tls: true,
            port: 25
        }
    }
~~~~

**Comment by NNLemling** [comment]
The "CHECK_SSL" set here as "required" so the admin has to deal with it and consciously choose yes / no.
It was decided not to change the API defaults.
