### ISSUE TITLE
Audit object not initialized on login route

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2423]
The Audit object for the current request is not initialized for the login route:
https://github.com/privacyidea/privacyidea/blob/88c36350fb9bded7ea97255e22cea6fac477dee2/privacyidea/webui/login.py#L57

When checking whether remote users are allowed:
https://github.com/privacyidea/privacyidea/blob/4d59eab2941308f742927851e3e4a45eee7ae739/privacyidea/api/lib/prepolicy.py#L1213
the `action_values()` function fails when trying to write to the audit log:
https://github.com/privacyidea/privacyidea/blob/d6fd3f83de5354c762fc1b8110179e1821302041/privacyidea/lib/policy.py#L2366

**Comment by cornelinux** [comment]
I think the audit object was probably not initialized on purpose, to avoid cluttering the audit log as soon as the login form is called (since it is actually not part of the REST API).

So we need to check, how we actually want to deal with that.

**Comment by plettich** [comment]
Correct, `is_remote_user_allowed()` just checks if the policy is set. We can add `write_to_audit_log=False` to the parameters of `action_values()` to avoid the error.
I was thinking that the `audit_object` wasn't initialized on purpose...

**Comment by plettich** [comment]
This was introduced in v3.3

**Comment by cornelinux** [comment]
So the problem exists in 3.3 and 3.4? I am OK with fixing this in 3.4.1.
