### ISSUE TITLE
Allow GET /token list to filter by active tokens

### ISSUE THREAD

**Issue by gallolp** [privacyidea/privacyidea#2424]
It would be helpful to be able to filter the token list by active/inactive tokens.

Example: `GET https://piserver/token/?active=True`

This would reduce the list size for users that have several disabled or otherwise inactive tokens. Also it would allow better token management using the api (similar to what we can do with token janitor on the cli).

The implementation is fairly easy as the current [get_tokens_paginate](https://github.com/privacyidea/privacyidea/blob/3d82e9c8060fe45a25103d0b0240f5888d39afa2/privacyidea/lib/token.py#L426) implementation in the token lib already has an "active" parameter. It is just a matter of exposing it as a query param on GET /token api.

I'm willing to send a PR for your evaluation.

Thank you.

**Comment by cornelinux** [comment]
Thanks a lot for the PR.
You know, that you can actually *sort* in the UI? So that would be an easy way to either see the active or inactive tokens first.

**Comment by gallolp** [comment]
Hi @cornelinux , thanks for your comments and approval. The UI is fine but we are currently handling almost everything via API and were particularly looking for a way to get a user's active tokens for processing and inactive tokens for cleanup/maintenance. This seemed like a nice and easy solution.
