### ISSUE TITLE
disable "Enroll New Token" button

### ISSUE THREAD

**Issue by orest-gulman** [privacyidea/privacyidea#2426]
Hi,
In case of policy which NOT allowing enroll any type of token, the user can see an "Enroll New Token" button in the users deatails.
![image](https://user-images.githubusercontent.com/10500949/94719723-3110ef00-035c-11eb-8084-7fad62d52e6d.png)

**Comment by cornelinux** [comment]
We have a JS function ``checkEnroll()`` which can simply be used to check if there is any enrollment policy and hide the button.

See like
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.html#L21

**Comment by laclaro** [comment]
@NNLemling Sorry, I just realized that you were assigned... :(
