### ISSUE TITLE
Create challege even if message could not be submitted to firebase

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#2438]
Can you check that a challenge is generated for a push token even if privacyidea was not able to submit the message to the firebase service?
This happens if the firebase token of the app has changed, but using push-poll, the app is still able to respond to the challenge without using firebase at all.

**Comment by plettich** [comment]
We raise an error as soon as submitting the message to firebase fails:
https://github.com/privacyidea/privacyidea/blob/cb30ab7bed60edbfe6a4cf3f3cc4e8fb680bc4f5/privacyidea/lib/tokens/pushtoken.py#L731

We could just create and save the challenge in the db before we raise the exception.
