### ISSUE TITLE
argon2 hash too long for authcache column authorization

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2446]
With the new argon2 hashing, introduced by #2413, the hashes may exeed VARCHAR(64) as e.g. in the authcache table in the authorization column.

We have to increase that size.

- [x] Check for the length of the argon2 hashes as used by us - the hash generated by test_06_hash_pepper has 77 characters. We will do VARCHAR(255)
- [x] Check if this affects not only the authcache table
- [ ] Add migration script (-> v3.5)

This bug may cause validate/check requests to fail with exception if the auth cache is enabled.

**Comment by cornelinux** [comment]
The Token PINs and Admin passwords are hashed with argon2. The table comlumsn are 512 and 255 chars and manually and successfully habe been tested with mysql. (So you can check the 2nd checkbox)

The length of the argon hash depends on the parameters like rounds, salt, memory costs, hash length...

But in our scenario it will not get much longer than 80. I would recommend a ``VARCHAR(255)`` for the  ``authentication`` column in the authcache table.
