### ISSUE TITLE
owncloud - Authmodule - specify realm

### ISSUE THREAD

**Issue by Keithsc** [privacyidea/privacyidea#245]
I have the privacyidea owncloud auth module installed it it's working but I can't see where to specify a  Realm so have had to make my owncloud realm the default realm so I am now able to authenticate although it does take a long time (10 seconds +).

We also have a wordpress OTP plugin and it works perfectly with privacyIDEA and is nice and quick so I am assuming the slowness is because of a realm issue. is it searching across all realms, that would explain the slow response times.

Thanks
Keith

**Comment by cornelinux** [comment]
If you do not specify a realm, it only searches the default realm. 
Maybe we can get an idea from privacyidea.log, when the request starts and when it ends to investigate the 10secs.

The realm: You are right. At the moment it is not implemented. I think the configuration could contain an additional entry "realm", which would be added to the poststring.
https://github.com/privacyidea/privacyidea/blob/master/authmodules/ownCloud/user_privacyidea/lib/otp_privacyidea.php#L227

As far as privacyidea is concerned you can also use

    user@realm

to authenticate. But probably this will fail with ownCloud.

**Comment by Keithsc** [comment]
Hi, I did a "tail -f privacyidea.log" and watched the log file as I logged in to owncloud. The log listed my user multiple times and it also logged the SQL connection string multiple times. The last line was "There is no machine with IP=IPAddress('192.168.x.x')

The above happens more or less instantly but I still have to wait about another 10 seconds or so before I get logged into owncloud.  If I unchecked the "Use PrivacyIDEA to authenticate the users" my login times go back to about 1 second.

I also tried logging in with my user@realm but that didn't work.

We have proxies and firewalls between machines and I will have a look at the logs to see I can see anything being blocked and get back in touch.

cheers
Keith

On 26/10/15 12:21, Cornelius Kölbel wrote:

If you do not specify a realm, it only searches the default realm.
Maybe we can get an idea from privacyidea.log, when the request starts and when it ends to investigate the 10secs.

The realm: You are right. At the moment it is not implemented. I think the configuration could contain an additional entry "realm", which would be added to the poststring.
https://github.com/privacyidea/privacyidea/blob/master/authmodules/ownCloud/user_privacyidea/lib/otp_privacyidea.php#L227

As far as privacyidea is concerned you can also use

user@realm


to authenticate. But probably this will fail with ownCloud.

—
Reply to this email directly or view it on GitHub<https://github.com/privacyidea/privacyidea/issues/245#issuecomment-151116185>.

--
Keith Scott Technical Specialist Architecture & Solutions Service NSS Information Technology SBU NHS National Services Scotland Area 074a Gyle Square 1 South Gyle Crescent Edinburgh EH12 9EB T: 0131 275 6000 Please consider the environment before printing this email. NHS National Services Scotland is the common name for the Common Services Agency for the Scottish Health Service. www.nhsnss.org<http://www.nhsnss.org>

********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************

**Comment by cornelinux** [comment]
probably looks alright.
I will add realms to owncloud module and please try again.
Thanks
Cornelius

**Comment by cornelinux** [comment]
I added a totally untested version for adding the realm.
Would you please check this out? https://github.com/privacyidea/privacyidea/tree/master/authmodules/ownCloud

**Comment by Keithsc** [comment]
Hi, Thanks for all the work you've done today.

I've downloaded and installed/setup the new owncloud auth app have changed the default realm in PrivacyIdea and I am able to login !! but it's still pretty slow.

Having said that I am just playing with PrivacyIdea, I only installed it last week and am just seeing how it could fit it in to our infrastructure.  If you can't think of anything easy that might fix this then that would be great but otherwise just forget about it just now and I'll go and check over everything at my end.

Cheers
Keith


On 26/10/15 15:01, Cornelius Kölbel wrote:

I added a totally untested version for adding the realm.
Would you please check this out? https://github.com/privacyidea/privacyidea/tree/master/authmodules/ownCloud

—
Reply to this email directly or view it on GitHub<https://github.com/privacyidea/privacyidea/issues/245#issuecomment-151165963>.

--
Keith Scott Technical Specialist Architecture & Solutions Service NSS Information Technology SBU NHS National Services Scotland Area 074a Gyle Square 1 South Gyle Crescent Edinburgh EH12 9EB T: 0131 275 6000 Please consider the environment before printing this email. NHS National Services Scotland is the common name for the Common Services Agency for the Scottish Health Service. www.nhsnss.org<http://www.nhsnss.org>

********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************

**Comment by Keithsc** [comment]
Hi Again,

I've just noticed the logs in OwnCloud and there's quite a lot of registering backend OC_User_Database entries. ?

Debug   user_privacyidea        registering backend OC_User_Database    2015-10-26T16:18:36+00:00
Debug   user_privacyidea        privacyIDEA is enabled  2015-10-26T16:18:36+00:00
Debug   user_privacyidea        registering backend OC_User_Database    2015-10-26T16:18:34+00:00
Debug   user_privacyidea        privacyIDEA is enabled  2015-10-26T16:18:41+00:00
Debug   user_privacyidea        registering backend OC_User_Database    2015-10-26T16:18:40+00:00
Debug   user_privacyidea        privacyIDEA is enabled  2015-10-26T16:18:40+00:00
Error   PHP     Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0     2015-10-26T16:18:38+00:00
Debug   user_privacyidea        registering backend OC_User_Database    2015-10-26T16:18:38+00:00
Debug   user_privacyidea        privacyIDEA is enabled  2015-10-26T16:18:38+00:00
Debug   user_privacyidea        registering backend OC_User_Database    2015-10-26T16:18:37+00:00
Debug   user_privacyidea        privacyIDEA is enabled  2015-10-26T16:18:37+00:00
Debug   user_privacyidea        registering backend OC_User_Database    2015-10-26T16:18:36+00:00
Debug   user_privacyidea        privacyIDEA is enabled  2015-10-26T16:18:36+00:00




On 26/10/15 15:01, Cornelius Kölbel wrote:

I added a totally untested version for adding the realm.
Would you please check this out? https://github.com/privacyidea/privacyidea/tree/master/authmodules/ownCloud

—
Reply to this email directly or view it on GitHub<https://github.com/privacyidea/privacyidea/issues/245#issuecomment-151165963>.

--
Keith Scott Technical Specialist Architecture & Solutions Service NSS Information Technology SBU NHS National Services Scotland Area 074a Gyle Square 1 South Gyle Crescent Edinburgh EH12 9EB T: 0131 275 6000 Please consider the environment before printing this email. NHS National Services Scotland is the common name for the Common Services Agency for the Scottish Health Service. www.nhsnss.org<http://www.nhsnss.org>

********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************

**Comment by cornelinux** [comment]
Which version of ownCloud are you running?

**Comment by cornelinux** [comment]
I revived my old ownCloud installation and I login within less than a second.

Using
* OwnCloud 8.2
* Yubikey
* privacyIDEA 2.7 on the same network segment

I am not the ownCloud expert, so there might some room for improvements.

But I have only 6 tokens and 5 users in privacyIDEA. The users are located in a flat file.
The users just have the same name like the OC users.

**Comment by Keithsc** [comment]
Hi,

Until an hour ago I had been using version 8.1.3 and I have since upgraded to version 8.2.0.
I had to comment out some lines in /apps/user_privacyidea/lib/otp_privacyidea.php as I was getting Logging issues ? It might be my setup but without commenting out these lines OwnCloud wouldn't load. I think there might have been an api change between versions. I also upgraded my php install to 5.6.14

 #   OC_Log::write('user_privacyidea', 'API: '. $allow_api, OC_Log::DEBUG);
 #   OC_Log::write('user_privacyidea', 'Client Call: '. $client_call, OC_Log::DEBUG);
 #   OC_Log::write('user_privacyidea', 'Authenticating with normal password', OC_Log::DEBUG);

We have about 70 users

PrivacyIDEA = 2.7 ( different network ) (Everything we have is either behind a reverse proxy or had to use a forward proxy)
hotp token (is this sensible) ?
We were about to order some Yubikeys :>)

I am using a sqlresolver and it seems to work fine, I have just created one token for myself.

On 26/10/15 20:18, Cornelius Kölbel wrote:

I revived my old ownCloud installation and I login within less than a second.

Using

 *   OwnCloud 8.2
 *   Yubikey
 *   privacyIDEA 2.7 on the same network segment

I am not the ownCloud expert, so there might some room for improvements.

But I have only 6 tokens and 5 users in privacyIDEA. The users are located in a flat file.
The users just have the same name like the OC users.

—
Reply to this email directly or view it on GitHub<https://github.com/privacyidea/privacyidea/issues/245#issuecomment-151272529>.


********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************

**Comment by cornelinux** [comment]
I already fixed the logging issue.

Is your wordpress, which you connected to privacyidea located "in the same distance" as owncloud?
You could also run a test on the owncloud machine, to check the authentication speed between the owncloud machine and privacyidea:

     curl -v -k 'https://your.privacyidea.server/validate/check?user=yourUser&pass=pin123456'

change the *your.privacyidea.server*, the *yourUser* and *pin123456*.

Use an existing user and the correct OTP value, to get the a successful authentication ("value": true).
Use the user and the token, that takes the 10 secs.

...and see how fast the REST request is.

thx

**Comment by Keithsc** [comment]
Sorry I hadn't realised that you had fixed the logging issue, I have upgraded the app now and it's working without any logging issue.

Below is the output from the curl command. I can't see the time taken in the output but it takes about 1 second to run.

[root@SvrXYZ apps]# curl -v -k 'https://domain.com/validate/check?user=keith@our-realm&pass=072061'
* About to connect() to proxy proxy port 8080 (#0)
*   Trying 192.168.xx.yy... connected
* Connected to proxy (192.168.xx.yy) port 8080 (#0)
* Establish HTTP proxy tunnel to domain.com:443
> CONNECT domain.com:443 HTTP/1.1
> Host: domain.com:443
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Proxy-Connection: Keep-Alive
>
< HTTP/1.0 200 Connection established
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* warning: ignoring value of ssl.verifyhost
* skipping SSL peer certificate verification
* SSL connection using TLS_DHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
* subject: CN=*.domain.com,OU=COMODO SSL Wildcard,OU=Domain Control Validated
* start date: Mar 04 00:00:00 2013 GMT
* expire date: Mar 03 23:59:59 2018 GMT
* common name: *.domain.com
* issuer: CN=COMODO RSA Domain Validation Secure Server CA,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /validate/check?user=keith@our-realm&pass=072061 HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: domain.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Rocket
< Date: Mon, 26 Oct 2015 23:15:05 GMT
< Content-Type: application/json
< Content-Length: 869
< Connection: keep-alive
< Keep-Alive: timeout=600
< Cache-Control: no-cache
<
* Connection #0 to host proxy left intact
* Closing connection #0
{"jsonrpc": "2.0", "signature": "3639546989532257166198020795378995198452607934435089241955760295189622043415727771324590561992020789774729344555428861422160361779804833506128307950582010840
1049663785402562620781602110867004696179455189226013734807271788403864963065957675438133618566929194939851287558344591863299008617417009214249041627886176500621516753052002832402675800925223
2227640427931632600961990165648396753826470510565799610964649744988981188233738261687097990177002347920424788915404166976285255026539349849527871697387705267091373206242178591613599434119888
2147816287953098302874601844550340428758353220959631395384250271021520236818002", "detail": {"message": "matching 1 tokens", "type": "hotp", "serial": "OATH0006DA33"}, "versionnumber": "2.7"
, "version": "privacyIDEA 2.7", "result": {"status": true, "value": true}, "time": 1445901297.84486, "id": 1}[root@SvrXYZ apps]#





On 26/10/15 22:52, Cornelius Kölbel wrote:

Warning: This message contains unverified links which may not be safe.  You should only click links if you are sure they are from a trusted source.


I already fixed the logging issue.

Is your wordpress, which you connected to privacyidea located "in the same distance" as owncloud?
You could also run a test on the owncloud machine, to check the authentication speed between the owncloud machine and privacyidea:

 curl -v -k 'https://your.privacyidea.server/validate/check?user=yourUser&pass=pin123456'


change the your.privacyidea.server, the yourUser and pin123456.

Use an existing user and the correct OTP value, to get the a successful authentication ("value": true).
Use the user and the token, that takes the 10 secs.

...and see how fast the REST request is.

thx

—
Reply to this email directly or view it on GitHub<https://github.com/privacyidea/privacyidea/issues/245#issuecomment-151307364>.


********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************

**Comment by Keithsc** [comment]
Apologies in advance for this mess but it shows the delay that I am seeing....This is my OwnCloud.log file from when I log in to our owncloud server.

{"reqId":"OVET13YBv\/kVj62lk0XM","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA is enabled","level":0,"time":"2015-10-26T23:32:52+00:00","method":"POST","url":"\/"}
{"reqId":"OVET13YBv\/kVj62lk0XM","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"registering backend  OC_User_Database","level":0,"time":"2015-10-26T23:32:52+00:00","method":"POST","url":"\/"}
{"reqId":"OVET13YBv\/kVj62lk0XM","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"API: 1","level":0,"time":"2015-10-26T23:32:52+00:00","method":"POST","url":"\/"}
{"reqId":"OVET13YBv\/kVj62lk0XM","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"Client Call: ","level":0,"time":"2015-10-26T23:32:52+00:00","method":"POST","url":"\/"}
{"reqId":"OVET13YBv\/kVj62lk0XM","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA checkPassword","level":0,"time":"2015-10-26T23:32:52+00:00","method":"POST","url":"\/"}
{"reqId":"OVET13YBv\/kVj62lk0XM","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"calling https:\/\/domain.com\/ for user keith (no)","level":0,"time":"2015-10-26T23:32:52+00:00","method":"POST","url":"\/"}

Long Delay here about 10 seconds ? then........................................

{"reqId":"OVET13YBv\/kVj62lk0XM","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyidea returned 1","level":1,"time":"2015-10-26T23:33:03+00:00","method":"POST","url":"\/"}
{"reqId":"ifGhF0S\/\/q3Ua8OBo3JR","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA is enabled","level":0,"time":"2015-10-26T23:33:03+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"ifGhF0S\/\/q3Ua8OBo3JR","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"registering backend  OC_User_Database","level":0,"time":"2015-10-26T23:33:03+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"uFKBXbWyFn6BCTqj\/1ZU","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA is enabled","level":0,"time":"2015-10-26T23:33:04+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=6b8e97c9670dfc1d590fdfa24359cf21"}
{"reqId":"uFKBXbWyFn6BCTqj\/1ZU","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"registering backend  OC_User_Database","level":0,"time":"2015-10-26T23:33:04+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=6b8e97c9670dfc1d590fdfa24359cf21"}
{"reqId":"nxaI3ylDjDHl7pW2Phrl","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA is enabled","level":0,"time":"2015-10-26T23:33:05+00:00","method":"GET","url":"\/index.php\/avatar\/keith\/128"}
{"reqId":"nxaI3ylDjDHl7pW2Phrl","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"registering backend  OC_User_Database","level":0,"time":"2015-10-26T23:33:05+00:00","method":"GET","url":"\/index.php\/avatar\/keith\/128"}
{"reqId":"jR\/aH2sVbn9IWb4HPxqS","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA is enabled","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/scan.php?force=false&dir=&requesttoken=e32775d50351a6cc242cfd8e4993b9fa245ee50ccc1eed36912a495b33a7f6d4%7CuAIyLnsClOizH8S2%7C656866070144f55773e3bff2466efad760b8747486f3c2bdfa7c982a81d367542ed1d95b605ae7adbfb77a8c2ebac929d0dc2cfc6ca0005c42b18a226dfc312f%3AdZtaWnJN1q"}
{"reqId":"jR\/aH2sVbn9IWb4HPxqS","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"registering backend  OC_User_Database","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/scan.php?force=false&dir=&requesttoken=e32775d50351a6cc242cfd8e4993b9fa245ee50ccc1eed36912a495b33a7f6d4%7CuAIyLnsClOizH8S2%7C656866070144f55773e3bff2466efad760b8747486f3c2bdfa7c982a81d367542ed1d95b605ae7adbfb77a8c2ebac929d0dc2cfc6ca0005c42b18a226dfc312f%3AdZtaWnJN1q"}
{"reqId":"CWP\/UwIHCeFd7dA+SQay","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA is enabled","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/apps\/gallery\/config?extramediatypes=1"}
{"reqId":"CWP\/UwIHCeFd7dA+SQay","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"registering backend  OC_User_Database","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/apps\/gallery\/config?extramediatypes=1"}
{"reqId":"QDq6o2oog+VNkLzTwvTc","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA is enabled","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2F&sort=name&sortdirection=asc"}
{"reqId":"QDq6o2oog+VNkLzTwvTc","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"registering backend  OC_User_Database","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2F&sort=name&sortdirection=asc"}
{"reqId":"CWsdifQBwTLDEkqgMtpx","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA is enabled","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/apps\/files_sharing\/api\/externalShares"}
{"reqId":"CWsdifQBwTLDEkqgMtpx","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"registering backend  OC_User_Database","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/apps\/files_sharing\/api\/externalShares"}
{"reqId":"CFZsFFGDESfkXn4aR7t8","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA is enabled","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2F"}
{"reqId":"CFZsFFGDESfkXn4aR7t8","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"registering backend  OC_User_Database","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2F"}
{"reqId":"oBZijEq3exlNaiV0JHN7","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"privacyIDEA is enabled","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getItemsSharedStatuses&itemType=file"}
{"reqId":"oBZijEq3exlNaiV0JHN7","remoteAddr":"192.168.xx.yy","app":"user_privacyidea","message":"registering backend  OC_User_Database","level":0,"time":"2015-10-26T23:33:06+00:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getItemsSharedStatuses&itemType=file"}

On 26/10/15 22:52, Cornelius Kölbel wrote:

Warning: This message contains unverified links which may not be safe.  You should only click links if you are sure they are from a trusted source.


I already fixed the logging issue.

Is your wordpress, which you connected to privacyidea located "in the same distance" as owncloud?
You could also run a test on the owncloud machine, to check the authentication speed between the owncloud machine and privacyidea:

 curl -v -k 'https://your.privacyidea.server/validate/check?user=yourUser&pass=pin123456'


change the your.privacyidea.server, the yourUser and pin123456.

Use an existing user and the correct OTP value, to get the a successful authentication ("value": true).
Use the user and the token, that takes the 10 secs.

...and see how fast the REST request is.

thx

—
Reply to this email directly or view it on GitHub<https://github.com/privacyidea/privacyidea/issues/245#issuecomment-151307364>.


********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************

**Comment by cornelinux** [comment]
Hi Keith,
obviously you have a proxy on 8080. And it seems that the problem arises here. Do you have the proxy configured on the command line, so that curl uses the proxy or is it some kind of transparent?

Do you see anything in the proxy log?

Maybe it is as simple as this to add a proxy configuration (like http://stackoverflow.com/questions/5211887/how-to-use-curl-via-a-proxy) to the privacyIDEA config in OC.

**Comment by Keithsc** [comment]
Hi,

We can now login to owncloud without the 10 second delay  :>)

We block all outbound connections from our infrastructure and force
people to use our proxies, but it turns out that there was a exception
to this. We allowed outbound http/https traffic to our own public IP's.
This isn't ideal so I have disabled this firewall rule so the proxy has
to be used. Making this change stopped owncloud working with PrivacyIDEA.

We then made some changes to your app to put a proxy into it as you
suggested. We followed the "realm" changes you made yesterday as a
template and were able to use Owncloud and PrivaceIDEA again although
the 10 second issue was still there.

Then we realised that the 10 second problem was happening because curl
has a blank useragent by default and our reverse proxies rate limit
certain dodgy useragents instead of just blocking them. We've put a
useragent into the app and it's working perfectly now.

Thank you for all your help with this.

Regards
Keith



********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************

**Comment by cornelinux** [comment]
Cool!
It would be great if you would issue a pull request.
Or - are you willing to share the proxy-code?

Thanks Cornelius

**Comment by Keithsc** [comment]
Hi Yeh no problem, We're not used to github but will figure how to merge our changes into the project tomorrow.

Cheers
Keith.

On 27/10/15 16:36, Cornelius Kölbel wrote:

Cool!
It would be great if you would issue a pull request.
Or - are you willing to share the proxy-code?

Thanks Cornelius

—
Reply to this email directly or view it on GitHub<https://github.com/privacyidea/privacyidea/issues/245#issuecomment-151561755>.



********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in reliance on its contents:
to do so is strictly prohibited and may be unlawful.

Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland
NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and GSi recipients
NHSmail provides an email address for your career in the NHS and can be accessed anywhere

********************************************************************************************************************
