### ISSUE TITLE
Ability to choose smtp identifier in email enrollment event 

### ISSUE THREAD

**Issue by brunocascio** [privacyidea/privacyidea#2452]
**Is your feature request related to a problem? Please describe.**

We need to set SMTP config per realm due we use multiple brands and we don't want to use the same for example, SMTP sender.

**Describe the solution you'd like**

Add a field in the event framework to override the global configuration from privacyidea config 'email.identifier'

![image](https://user-images.githubusercontent.com/2397875/96319565-6bc68880-0fe6-11eb-8bbf-5e790c0417ce.png)

**Alternative solution**

Use `additional_params` field?

**Additional context**
We're using keycloak as a centralized solution for authentication. We have 2 clients (foo.com and bar.com)
Each client want to send email with their smtp configuration.

**Comment by cornelinux** [comment]
Gahh! You want to use email tokens? Evil! Very specific.
And you think you need to autoenroll these tokens to the users?

The options of the tokenhandler are defined here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/eventhandler/tokenhandler.py#L169

So you could add something like this:
~~~~python
"smtp_server": {
                            "type": "bool",
                            "visibleIf": "tokentype",
                            "visibleValue": "sms",
                            "description": _("The server which will be used to send email-tokens."),
                            "value": smtp_server_list
                        },
~~~~

You could get the "smtp_server_list" from ``lib/smtpserver.py:get_smtpservers()``.

**Comment by Jameru** [comment]
I just made a fairly naive implementation for this feature. If there is any feedback it'd be appreciated :)

**Comment by brunocascio** [comment]
Hey folks @cornelinux @Jameru,

 I think @Jameru's pull request works pretty well for the feature requested.

I'm glad to collaborate if needed :raised_hands:
