### ISSUE TITLE
Cosmetic Error with pi-manage backup

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2454]
Running ``pi-manage backup create`` results in an error with newer versions of mysql.

    mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces

This does no harm, the backup happens anyways.
To remove this error/warning we can use the parameter ``--no-tablespaces`` for the ``mysqldump`` command.

In the pi-manage script we need to add the parameter in the ``mysql-defaults`` file as follows:

~~~~python
def _write_mysql_defaults(filename, username, password):
    """
    Write the defaults_file for mysql commands

    :param filename: THe name of the file
    :param username: The username to connect to the database
    :param password: The password to connect to the database
    :return:
    """
    with open(filename, "w") as f:
        f.write("""[client]
no-tablespaces=True
user={0!s}
password={1!s}""".format(username, password))
~~~~

See https://community.privacyidea.org/t/backup-mysqldump-error/1710

**Comment by laclaro** [comment]
We came across this yesterday https://github.com/NetKnights-GmbH/ubuntu/issues/37

Since it is a generic issue with recent mysql versions, this repo is better suited.
