### ISSUE TITLE
Add direct search to dashboard

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2458]
What would an admin or a helpdesk user do, when he logs in to the privacyIDEA UI? Why or when would he do this?

Probable when an end user has a problem.
So it might be a good idea to add *search shortcuts* **on** the dashboard.

We could directly add a block with one search line for token serial numbers and a search line for usernames.

Basically like this
![image](https://user-images.githubusercontent.com/1908620/96694306-96b73080-1388-11eb-8b93-023319c9ca6f.png)

The admin could then directly jump to this very token or user.

~~~~html
<div class="col-lg-4">
             <div class="panel panel-default">
                 <div class="panel-heading" translate>Users and tokens</div>
                 <div class="panel-body">
                     <div translate>Search for users or tokens</div>
                        <div class="form-group">
                        <label for=""
                                translate>User
                        </label>
                            <input type="text" class="form-control"/>
                        <p class="input-group">
                          <span class="input-group-btn">
                            <button type="button" class="btn btn-default"
                                    ng-click="">
                                Search User
                            </button>
                          </span>
                        </p>
                        </div>
                     <div class="form-group">
                        <label for=""
                                translate>Token
                        </label>
                        <input type="text" class="form-control"/>
                        <p class="input-group">
                          <span class="input-group-btn">
                            <button type="button" class="btn btn-default"
                                    ng-click="">
                                Search Token Serial
                            </button>
                          </span>
                        </p>
                        </div>

                    </div>
                 </div>
           </div>
       </div>
~~~~

**Comment by laclaro** [comment]
We should write some directives for the search blocks.

**Comment by cornelinux** [comment]
Search by typing and issue two requests via ``GET /token`` and ``GET /user``.
Under the search input field the found resulst are displayed similar to the tokenlist view or the user listview.

The search needs to assure that the realm admin only finds tokens and users he is allowed to view.
This might currently be difficult since an empty realm translates currently to the default realm. 
The *new search* then would not provide a realm and thus search in all realms where the admin has access.

**Comment by laclaro** [comment]
# endpoint `GET /search`

It should take parameters **searchtype** (optional) and **query**

The **searchtype** specifies which part of privacyIDEA should be searched. At present this should be either user or token but may be extended to policies, events and all sorts of documentation. If the searchtype is not given, the search will apply the query everywhere.

The results will be returned grouped by searchtype.

```json
        {
          "id": 1,
          "jsonrpc": "2.0",
          "result": {
            "status": true,
            "data": [
              {
                "user": [ { <user1> }, { <user2> } ],
                "token": [ { <token1> }, { <token2> } ],
                "policy": [ { <pol1> }, { <pol2> } ],
                "policy_defs": [...]
                ...
              }
            ]
          },
          "version": "privacyIDEA unknown"
        }
```

The searchtype can also be given in the query itself by e.g. `user:henning`.

Access restrictions by policies would be implemented at the lib layer, so a user search will list only users realms, the querying user is allowed to list.

**Comment by laclaro** [comment]
We will evaluate potential search engines (elasticsearch, lucene, sql indexing, ...) to be used.

**Comment by laclaro** [comment]
Started a wiki page at https://github.com/privacyidea/privacyidea/wiki/concept:-index-search

**Comment by melanger** [comment]
@cornelinux Hi, is this anywhere near implementation? I just need to be able to "find" a user by full username (not really a search), for helpdesk to be able to go to a specific user detail, but currently this is not possible, only by opening a different user detail and modifying the URL directly.

**Comment by nilsbehlen** [comment]
will be continued here #4102
