### ISSUE TITLE
Exception UserError raised results in HTTP Response Code 500

### ISSUE THREAD

**Issue by jeffreykoetsier** [privacyidea/privacyidea#246]
PrivacyIDEA version 2.7 installed with pip virtualenv
Using the LdapUserID Resolver

When validating a non-existing username with the web API an HTTP Code 500 is returned:

`$> curl -# -v 'http://localhost/validate/check?user=test&pass=test' | python -m json.tool`
`* About to connect() to localhost port 80 (#0)`
`*   Trying ::1...`
`* Connected to localhost (::1) port 80 (#0)`
`> GET /validate/check?user=test&pass=test HTTP/1.1`
`> User-Agent: curl/7.29.0`
`> Host: localhost`
`> Accept: */*`
`> `
`< HTTP/1.1 500 INTERNAL SERVER ERROR`
`< Date: Mon, 26 Oct 2015 16:00:50 GMT`
`< Content-Length: 867`
`< Connection: close`
`< Content-Type: application/json`
`< `
` `
`{`
`    "detail": null,`
`    "id": 1,`
`    "jsonrpc": "2.0",`
`    "result": {`
`        "error": {`
`            "code": -500,`
`            "message": "ERR905: The user can not be found in any resolver in this realm!"`
`        },`
`        "status": false`
`    },`
`    "signature": "[data]",`
`    "time": 1445875250.545378,`
`    "version": "privacyIDEA 2.7"`
`}`

Returning an HTTP 500 code has some specific behaviour on certain applications. Two of which I encountered:

**wget**
Does not show any output, unless specifically specified the parameter --content-on-error

**simplesamlphp**
default authentication source tester will show this error message:
"There is an error in the request to this page. The reason was: Valid JSON response, but some internal error occured in PrivacyIDEA server." 

HTTP code 500 indicates an 'internal server error' which really doesn't occur. The server is fine and is able to finish the authentication check. Although the _result_ is negative, doesn't mean the server encountered a failure.

The exceptions raised by PrivacyIDEA code seem to be handled at a 'Flask' level and therefore raising the HTTP code 500.

This does not only happen with an unknown user account, but also when not supplying the correct parameters.

From my point of view these are client related issues. ie given user does not exist or 'user' parameter not specified. And therefore should return an HTTP code  4xx

Besides the HTTP code 500, the PrivacyIDEA log is being filled with full Python Tracebacks for each non-existing user being validated against PrivacyIDEA.

**Comment by cornelinux** [comment]
You are right. 
Thanks for pointing this out.

**Comment by cornelinux** [comment]
PolicyErrors could be "Forbidden" 403

**Comment by cornelinux** [comment]
We might to put it this way:

if an Exception - which is controlled by privacyIDEA (privacyIDEAError) - is raised, then we return a 400.
This is usually the case, when a parameter is missing. When a user can not be found. When the name of a policy contains invalid characters.

If an exception of any third party module is raised (which is not inherited by the privacyIDEAError), then we should return an HTTP 500.

Regarding the tracebacks. These could be put into loglevel "debug".
This way you will always get the error in the logfile. If you want to investigate the error, you can turn on debug and you will get the tracebacks.

What do you think?

**Comment by jeffreykoetsier** [comment]
Sounds as a good approach! 

Tracebacks in debug loglevel is a good idea!
