### ISSUE TITLE
Nightly SQL database tests on MySQL and others

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2477]
We should run our tests also with MySQL and Postgres.

This could be done in a daily/nightly run in CircleCI.

Tests have to be adapted, since currently some tests have hardcoded sqlite databases like some audit tests.

See #2435

**Comment by plettich** [comment]
Running the tests with MySQL requires some rewrite.
I'll re-open this issue to track the fixes.

**Comment by plettich** [comment]
Nightly tests with MySQL/Postgres are running just fine.
Possible TODOs:
- Oracle (Local installation)
- MariaDB
