### ISSUE TITLE
issues when deleting auth_cache entries 

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2481]
If the ``auth_cache`` is enabled, the entry should be deleted if the authentication with the entry does not succeed:
https://github.com/privacyidea/privacyidea/blob/fd7fa754577137cc040be54ee1c33454ee3546f8/privacyidea/lib/authcache.py#L133
There are two possibilities that the entry does not work:
- old style auth_cache entry
- password (hash) mismatch

The ``delete_from_cache()`` function iterates over all matching (username, resolver, realm) ``auth_cache`` entries and deletes the ones where the password (hash) matches:
https://github.com/privacyidea/privacyidea/blob/fd7fa754577137cc040be54ee1c33454ee3546f8/privacyidea/lib/authcache.py#L64
This means that old ``auth_cache`` entries only get deleted when the password matches which usually isn't the case with OTPs.
Also the cache time is not taken into account for the deletion.

**Comment by timosturm** [comment]
What do you mean with 
> This means that old auth_cache entries only get deleted when the password matches which usually isn't the case with OTPs.

https://github.com/privacyidea/privacyidea/blob/fd7fa754577137cc040be54ee1c33454ee3546f8/privacyidea/lib/authcache.py#L66

This implies that those entries get deleted too.

**Comment by timosturm** [comment]
https://github.com/privacyidea/privacyidea/blob/fd7fa754577137cc040be54ee1c33454ee3546f8/privacyidea/lib/authcache.py#L64

This line should be extended by two cases where cache entries can also be deleted:
1. If the current number of authentications is greater or equal than the maximum number of allowed entries
2. If the entry is expired, i.e., if the first authentication was longer ago then entries should be cached
