### ISSUE TITLE
Dashboard: Split authentication requests by "source"

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2483]
Many people talk to privacyIDEA over RADIUS. Many of them have several RADIUS Client configured.

Therefore it might be interesting to split the authentications display in the dashboard by client ip such as

1. Client 1.1.1.1
  - successful: 5
  - unsuccessful: 0
2. Client 2.2.2.2
  - successful: 12
  - unsuccessful: 91
3. Other
  - successful: 55
  - unsuccessful: 0

**Comment by cornelinux** [comment]
This can produce a lot of data and thus clutter the dashboard.
I think this is s.th. that is easier to add when we have a configurable dashboard.

**Comment by laclaro** [comment]
Of course you will need some option to actually split the data if needed.

**Comment by laclaro** [comment]
Similar as for splitting the tokens according to type in the dashboard, we should introduce a policy with a list of clients which are displayed separately. If the policy is not set, do not split at all.

**Comment by cornelinux** [comment]
This might be interesting to see, if users fail to authenticate at netscaler, while they manage to authenticate at SSH, e.g.
So this might be in fact useful. Let's discuss how we can approach this.
