### ISSUE TITLE
setting userrealm effectively disables action ("auditlog_age")

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2501]
I just noticed, that setting a userrealm in my test admin policy with an action `auditlog_age` lifts the effect of that action for the admin user.

That feels incorrect or is this intended?

**Comment by cornelinux** [comment]
If you set a user realm you will probably only see audit entries with this very user realm.
Please do not ask questions by openeing issues.

**Comment by laclaro** [comment]
If the actions "auditlog" and "auditlog_age" is defined in one single policy which is also restricted by userrealm, "auditlog_age" will not be matched since the view of the audit has no userrealm in the request.

# Solution

1. Delete the action "auditlog" from the original admin policy.
2. Create a second admin policy with only the action "auditlog" and set a userrealm(s) to display only there.

# Outcome

- auditlog_age will be matched correctly since it is not restricted
- the auditlog will only contain requests containing the userrealm that you defined.
