### ISSUE TITLE
Different behaviour for /validate/check and /auth endpoints -> policy condition

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2510]
**Is your feature request related to a problem? Please describe.**

In loginmode=privacyIDEA users log in to the webui with their tokens.
This is basically a request against ``/auth`` with the same tokens like they are used in requests against ``/validate/check``.
However, sometimes it is required to have different login logic for these two endpoints, like:

* User is allowed to use EMAIL tokens to login to WebUI (/auth) but not to the VPN (/validate/check)
* User needs to use a PIN when login to WebUI (/auth) but not when login to VPN (/validate/check)

Usually this can be done using the client condition or HTTP headers in the policies. But sometimes this is deemed to complicated.

This sounds like a condition for the specific scopes ``authentication``   and ``authorization``.

**Describe the solution you'd like**

Use client IPs ;-)

**Describe alternatives you've considered**

* Add a condition. But this condition would only hold for two scopes. So suddenly we would have scope dependent conditions. However, we also have scope dependent conditions, if we do tokentypes as conditions! #2590
* ~~Add an extended condition like the *http_header* and *userinfo*. This way it would not be to prominent. However, the user could modify the *http_header* when authenticating against the webui, so this is not really practical!~~

# Concept

In `g.request_headers.environ` we have a lot of environment invormation like the `PATH_INFO` being `validate/check`. This way we could distringuish between `/auth` and `/validate/check`.

![image](https://user-images.githubusercontent.com/1908620/132235140-a5f82717-4467-4c2f-b40e-1d6dfd0563bb.png)

We could add an additional extended condition (to userinfo, token, tokeninfo, http request header) being *HTTP environment*. 
This way we could have an extended condition `PATH_INFO=/validate/check` which would e.g. match the OTPPIN policy only in case of endpoint /validate/check and not /auth.

**Comment by jmozd** [comment]
Not sure if I got your intent fully right, but:

> Add an extended condition like the http_header [...]

actually, I believe I had implemented an according /validate/check distinction this way the last few days and hit #2514 .  I needed different actions using (push) tokens for the same client, always via PAM, depending on the actual application requesting auth/session permissions.

**Comment by cornelinux** [comment]
@jmozd for this what you are mentioning, you can use the http_header.

**Comment by laclaro** [comment]
@cornelinux The need to distinguish between /auth and /validate/check while doind login_mode=privacyIDEA occured to me several times. So I would vote for this feature.

**Comment by cornelinux** [comment]
@jmozd @laclaro After all this is already possible.

In the apache config we can add a header depending on the endpoint:

~~~~
        <Location /auth>
                RequestHeader add PIInfo "auth"
        </Location>

        <Location /validate>
                RequestHeader add PIInfo "validate"
        </Location>
~~~~

This will result in an HTTP header `Piinfo=validate` for `validate/check` and in `Piinfo=auth` for `/auth`.

The extended policy condition can then be set to 

     HTTP Header, Piinfo, validate
