### ISSUE TITLE
add more descriptive tooltip to token when assigning to machine

### ISSUE THREAD

**Issue by jmozd** [privacyidea/privacyidea#2516]
**Is your feature request related to a problem? Please describe.**
When managing a machine, I can add tokens via the "Attach a new token PIP" entry field. While any matching token id is displayed when entering data into the "serial" entry field, the tooltips of the listed tokens only show the token ID, as do the actual list entries.

Having many tokens, it is hard to validate to have hit the proper token just by the id.

**Describe the solution you'd like**
To at least me, it would be helpful if some details of the token, like owning user and its "description" value would also be displayed. This could be implemented as according content of the tokens' tooltips or perhaps directly as a suffix to the according list entry.

**Describe alternatives you've considered**
creating a pop-up selection dialog could be considered the "full notch solution", with the ability to search via serial, user and description.

**Comment by cornelinux** [comment]
This is an interesting idea - also when assigning a token to a user!

**Comment by cornelinux** [comment]
To solve this you need to look deeper into angularJS in the `directive.assigntoken.html`. It is probably a matter of *typeahead*.
