### ISSUE TITLE
use REMOTE_USER for authentication at WebUI

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#252]
To allow for more authentication schemes, we should allow REMOTE_USER for authentication at the WebUI.

We could add "remote_user" to the WebUI policy login_mode.
http://privacyidea.readthedocs.org/en/latest/policies/webui.html#login-mode

A decorater in the before_request (https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/token.py#L96)
could read the REMOTE_USER.

Either we add a new decorator or we modify the decorator @user_required (https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/token.py#L96). 

This allows a user, who was authenticated by basic authentication by the webserver, that set REMOTE_USER, to directly jump to certain points in the WebUI.

**Comment by girgen** [comment]
Sounds great! That would be a great way to support SAML authentication for people administrating users' credentials in privacyidea. Ideally, it would allow users to be automatically created/provisioned if the where authenticated. SAML attributes can be used to set name, email and the likes.

**Comment by cornelinux** [comment]
Interesting.

**What SAML auth module are you using with apache?**

I just found a bitter taste with the basic/digest authentications. privacyIDEA uses the "Authorization" header to pass a JWT token to the REST API.
If I have a webserver config, that requires basic/digest auth this also uses the Authorization header and the webserver will complain.

At the first glance I would have to move the privacyIDEA Authorization header to something else like "PI-Authorization", so that the basic/digest authentication does not fail.

But I do not like to break the API in a version 2.8. Since there at least is the admin client, that uses the Authorization header and there might be other installations out there doing so.

**Comment by cornelinux** [comment]
OK. I am back from my walk in the forest and came up with a new idea...

REMOTE_USER is a cool thing and i will try to implement a backward compatibility.

The privacyIDEA server will do

1. Look for PI-Authorization. If it exist it will do its stuff as usual.

2. Then it will look for Authorization. Old clients or old API implementations may still send the JWT in the Authorization header. So if we can decrypt and decode this as JWT, we do the stuff as usual.

3. If decoding of Authorization fails, we assume, that obviously this is an Authorization header from something like basic auth. Now we start the new stuff.

## New Stuff

1. Get the REMOTE_USER 
2. Try to find the REMOTE_USER in the local admins (optional)
3. Try to find the REMOTE_USER in the default realm and the given realm. 
    To find a user in a non-default realm, the realm needs to be appended with an @ sign.

4. Now comes the tricky part. We need to pass the information of the logged_in_user to the webui.
    (The users role and his rights). The Web UI usually only fetches this information when the calling /auth
    endpoint. So we need to think of something here...

**Comment by cornelinux** [comment]
It looks like I need to have the additional login page to retrieve the privacyIDEA ticket anyway.
If a REMOTE_USER would exist, the login page will look like this:

![bildschirmfoto vom 2015-11-03 12 36 32](https://cloud.githubusercontent.com/assets/1908620/10907109/a091d288-8227-11e5-924b-7f7e97c65a43.png)

**Comment by cornelinux** [comment]
## Adding policy

We could enhance the policy **webui/login_mode** with 

 * REMOTE_USER
 * privacyIDEA+REMOTE_USER
 * userstore+REMOTE_USER

Or we could add an additional policy **webui/remote_user** with the allowed values:

 * only REMOTE_USER
 * REMOTE_USER AND login
 * disable REMOTE_USER

Check out, which is the best solution.

Then add it at https://github.com/privacyidea/privacyidea/blob/master/privacyidea/webui/login.py#L41

**Comment by girgen** [comment]
I use Shibboleth as SP module with apache. (supposedly, it can be made to work with nginx as well with some efforts). 

On the question
> If I have a webserver config, that requires basic/digest auth this also uses the Authorization header and the webserver will complain.
You might set up shibboleth on a different end point, i.e. a differens Location / URL prefix.

**Comment by cornelinux** [comment]
The current code in git will now work authentication issued by the webserver and will use REMOTE_USER. You then can choose to use the REMOTE_USER authentication (this one by shibboleth) to login to privacyIDEA webui.
I.e. if you authenticated via SSO you should be able to setup the mod_shib and use this to login to privacyIDEA without any further credentials.

**Comment by cornelinux** [comment]
Hi @girgen,
I hope this implementation will enable you to use the SP module.

Please note: The validation API /validate/check needs to be excluded from the Apache location access control. Otherwise you will also have to provide a password, when validating a user.

Kind regards
Cornelius
