### ISSUE TITLE
potential type error

### ISSUE THREAD

**Issue by pigeonsoar** [privacyidea/privacyidea#2548]
Hi, I found a potential problem may be caused in the future (It's worked now.)
In [privacyidea/lib/resolvers/SCIMIdResolver.py , line 299](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/SCIMIdResolver.py#L299), function `get_access_token`, you set a default value (`None`) for paramter `client` and `secret`.
Then, if you use `get_access_token()` without arguments in the future, you will get a type error in line 299 as you add a string and `None`.

**Comment by cornelinux** [comment]
Thanks for noting. Imho the interface could be

~~~~
def get_access_token(server=None, client="", secret=""):
~~~~
