### ISSUE TITLE
 Email Token configuration - If TLS support is checked it can not be unchecked

### ISSUE THREAD

**Issue by hobbs123** [privacyidea/privacyidea#255]
TLS activation under Config->Tokens->Email. If TLS support is checked it can not be unchecked.

privacyidea: 2.7
Centos 7.1
mysql
mariadb-devel-5.5.44-1.el7_1.x86_64
mariadb-5.5.44-1.el7_1.x86_64
mariadb-server-5.5.44-1.el7_1.x86_64
mariadb-libs-5.5.44-1.el7_1.x86_64

**Comment by cornelinux** [comment]
Thanks for submitting! This is a duplicate of #254
