### ISSUE TITLE
Enhance diagnostic report tool

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2555]
The `privacyidea-diag` tool could use some enhancements:
- [x] check selinux status on CentOS (and, if enabled, include the system audit-log as well)
- [x] add the apache logs
- [x] add the database structure/current db revision
- [x] add FreeRADIUS configuration
- [x] add apache configuration
- [x] add system status (CPUs, RAM, HD)

**Comment by laclaro** [comment]
watch out, if RHEL OS the according identifier is different from CentOS!
