### ISSUE TITLE
Push via Email

### ISSUE THREAD

**Issue by skug67** [privacyidea/privacyidea#2564]
I was wondering if it might be possible to delink the PUSH token format from Google's Firebase.  If the ios/Android PUSH client listened via IMAP-Idle on a dedicated email account could you maybe get a similar functionality w/o necessarily routing through Google's servers?  This is pure speculation on my part given that I understand very little of what's going on under the hood here -- but just thought it was worth putting out there.  (I know that there is already an email token type, but that involves entering the OTP manually; the idea here would be to access the push-button automation of the PUSH client.  I guess a mid-point compromise would be a slightly different email token type where the email contains a link that can be clicked to complete the authentication process rather than entering the OTP (as in the current email token) or directly authenticating (as in the PUSH client)).

**Comment by cornelinux** [comment]
I like the idea of the clicking on the link. But this is somehow cumbersome when I am at the desktop:

* Go to application A and be told: check your emails
* open the email client and click on the link, which will take me
* to the browertab, where I confirm the authentication.
* finally I have to go back to the original application.

This is a lot of hopping around.

However, we already added a push poll functionality. The authenticator app can poll a privacyIDEA URL to check for challenges, if Firebase does not work. I prefer to go down this road and rather one day allow to de-configure firebase and only use push-poll.

**Comment by skug67** [comment]
Sounds like your polling approach is pretty similar to the IMAP-idle thought that I had (I'm sure it's different under the hood but certainly seems to achieve just about the same results).  Glad to hear it's in the works.

**Comment by cornelinux** [comment]
I am closing this for now.
