### ISSUE TITLE
highlight search term in policy action search

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2577]
While working making the changes for #2574, I found highlighting the search terms in the policy action search would be a big pro. This can be done using angular-internals.

> During the implementation of this feature, we could also highlight the search term using the angular module ui-utils as described here
> https://angular.de/artikel/mark-highlight-search-results/

_Originally posted by @laclaro in https://github.com/privacyidea/privacyidea/issues/2178#issuecomment-759389202_

**Comment by laclaro** [comment]
We deactivated this feature in https://github.com/privacyidea/privacyidea/pull/2756 due to format-issues and a pending check for security vulnerabilities. The feature would be nice to have, so the reactivation would be great.

**Comment by cornelinux** [comment]
We would have to html-escape all descriptions, so that the highlighting will not break the description due to interpretation.

Could be done by changing all relevant descriptions or by a central server functionality.
