### ISSUE TITLE
Do not translate the dateformat in the audit view

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2579]
If you have a non-english browser, the date columns in the audit are displayed as as "local dates". The column filtering works on the non-localized date strings returned by the API.

2021-01-14 10:38:45 (used for filtering) <> 14.1.21 10:44:03 (displayed german)

This makes it very difficult to actually filter the audit for dates, since you do not see what you should type to get a desired result.

I suggest to remove the translation for these strings by _not_ using gettextCatalog.getString here:
https://github.com/privacyidea/privacyidea/blob/5332e345a8ffcea79e0610cb7025775489e63b59/privacyidea/static/components/audit/controllers/auditControllers.js#L33

**Comment by cornelinux** [comment]
I changed the subject of this issue, since it is a somehow important note to be added to the changelog. This will make it more clear, when we compose the changelog for the release.
