### ISSUE TITLE
"not enough values to unpack" in jwt/api_jws.py", line 180

### ISSUE THREAD

**Issue by W11T** [privacyidea/privacyidea#2601]
Trying to save an ldap resolver silently fails.
Messages in privacyidea.log:

```
  File ".../venv/lib64/python3.6/site-packages/jwt/api_jws.py", line 180, in _load
    signing_input, crypto_segment = jwt.rsplit(b'.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

```

privacyIDEA-3.5

**Comment by cornelinux** [comment]
You are missing a bunch of information. How did you install privacyIDEA?
Probably via pip.
The current jwt package is not supported! Install using requirements.txt!
Please follow one of the guides https://privacyidea.readthedocs.io/en/latest/installation/index.html

**Comment by W11T** [comment]
ok, i reran "pip install" as described [here](https://privacyidea.readthedocs.io/en/v3.5/installation/pip.html#pip-install).
Restarted the server via 
`cd .../venv/bin; nohup ./pi-manage runserver &
`
Saving an ldap resolver now leaves messages

`[WARNING][privacyidea.lib.utils:449] the passed key 'resolver' is not a parameter for the machine resolver type 'ldap'
`
test resolver leads to:

```
... [ERROR][privacyidea.app:1892] Exception on /machineresolver/test [POST]
Traceback (most recent call last):
  File ".../venv/lib64/python3.6/site-packages/jwt/api_jws.py", line 180, in _load
    signing_input, crypto_segment = jwt.rsplit(b'.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
...
jwt.exceptions.DecodeError: Not enough segments
```
look like jwt package is in use still.

**Comment by cornelinux** [comment]
You need to install the requirements

~~~~
To achieve a deterministic installation, you can install and pin the installed versions like this:

export PI_VERSION=3.5.1
pip install -r https://raw.githubusercontent.com/privacyidea/privacyidea/v${PI_VERSION}/requirements.txt
pip install git+https://github.com/privacyidea/privacyidea.git@v${PI_VERSION}
~~~~

**Comment by W11T** [comment]
that's exactly what i did.
Just noticed i have two pi-manage:

```
... 58633 ... ./pi-manage
... 58651 ... ./venv/bin/pi-manage

```
I tried ./pi-manage. 
But i still get the jwt-message. (strange - not every time)

**Comment by W11T** [comment]
wait - i'm wrong!
i used 
`export PI_VERSION=3.5
`
Just used 3.5.1 and it looks very different now!
Let me check ...

**Comment by W11T** [comment]
Thank you!
Looks like 3.5.1 fixed my issue.

**Comment by defnull** [comment]
Why does `setup.py` state `"PyJWT>=1.3.0"` if an exact version is needed? `setup.py` and `requirements.txt` should match?

**Comment by plettich** [comment]
@defnull actually `setup.py` and `requirements.txt` do describe different things: https://caremad.io/posts/2013/07/setup-vs-requirement/
That is why we keep the dependencies in `setup.py` *open* (we only specify a minimum version if we know that these don't work).
Unfortunately since several packages recently introduced breaking changes (Flask, PyJWT, ... mostly dropping Python2 support) the installation via `setup.py` leaves the system in a broken state.
But we are working on updating privacyIDEA to use the most recent packages in #2876
