### ISSUE TITLE
Policy to change /token/init to "rollover"

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2613]
Frequently, people would like to only allow one token per user (or per token type). This can be achieved by setting a max_token-type. However, often people would also like to automatically delete the old token whenever the user self-enrolls a new one.

At present, this can only be done using an event-handler script. 

My suggestion would be to implement a policy which brings this functionality to the privacyIDEA core.

- The policy could hold a list of token types to apply it to
- It should only affect user inits
- It should maybe be restricted to software tokens

**Comment by laclaro** [comment]
Can be done with script https://github.com/privacyidea/scripts/pull/6.

**Comment by laclaro** [comment]
Unfortunately, the scripts are not the best solution in some cases. Especially if you would like to restrict the number of tokens per user to 1. If, for instance users enroll their own token (singular) and for some reason the token is deactivated by some admin to lock the user. The user will not be able to enroll a new token.

This works with a pre-event handler, but this is unfortunately not very flexible. E.g. at the moment, pre event handler do not have access to the tokentype to be enrolled.

For the post-event handling script, the max_token restriction cannot be 1 since the user first enrolls a token and the script afterwards deletes all other tokens (e.g. by type).

## Alternatives
To realize the use case of the locked user with a post-event-handler-script, you can set the max_token to 2 and define an event handler, which enrolls a blocker-token on /token/disable by an admin and another which removes it on /token/enable.

**Comment by cornelinux** [comment]
I think it would make more sense to enhance the event handler this way, that also other parameters from the request can be passed to the event handler.
THis way the event hanlder (script handler) would have the information about the to be enrolled tokentype.
This would also help for other scenarios.

**Comment by cornelinux** [comment]
Thoughs from BAM:

* The seed regeneration must not happen with hardware tokens
* Should the regeneration occurr in a wizard?
* How many click should the user do? Regenerate in the token list (less clicks) or in the token details (more clicks)? Or at both locations

**Comment by laclaro** [comment]
On regeneration of a token, we will need to take care of

- token type
- token realms

**Comment by laclaro** [comment]
Buttons to Rollover will be displayed in the token list and the token details.

There might be be also a policy "wizard_token_rollover" which causes the wizard to be always displayed on user login to the WebUI and to rollover the first (and only?) token of the user.

**Comment by laclaro** [comment]
2stepinit will not work, since capturing the input from a modal dialog is not easily possible, see:

https://stackoverflow.com/questions/40583936/angularjs-form-inside-bootstrap-modal-popup

**Comment by plettich** [comment]
> 2stepinit will not work, since capturing the input from a modal dialog is not easily possible, see:
> 
> https://stackoverflow.com/questions/40583936/angularjs-form-inside-bootstrap-modal-popup

We could always switch to the [AngularJS Bootstrap modal](https://angular-ui.github.io/bootstrap/#modal)

**Comment by cornelinux** [comment]
@plettich we are not doing modal anyways! The whole normal design is a flat design for several reasons and @laclaro is about flattening it out.
