### ISSUE TITLE
Need public CentOS7 repository

### ISSUE THREAD

**Issue by npaladin2000** [privacyidea/privacyidea#2617]
**Is your feature request related to a problem? Please describe.**
Trying to install on my company's standard Cent7 build

**Describe the solution you'd like**
The current NetKnights repo is not publicly accessible, we need a publicly accessible one

**Describe alternatives you've considered**
Ubuntu Linux was suggested and rejected

**Comment by cornelinux** [comment]
I am sorry.
The CentOS/RHEL repo is not public.
If you need a public one, you are welcome to create one.

If you need access to the closed REHL repo, contact us at info@netknights.it
