### ISSUE TITLE
Migration skript may fail with oracle

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2618]
The issue occured in a privacyIDEA 3.4.1 installation on CentOS7 with Oracle database.

We should check the upgrade process on Oracle from 3.3.3 to 3.4.1 and to 3.5.1. Especially the upgrade from 3.3.3 to 3.4.1 may not work properly. Check with
- [x] pi-manage db upgrade -d /opt/privacyidea/lib/privacyidea/migrations
- [ ] package upgrade

The error referred to a missing `IS NULL` in the SQL statement.
`sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00908: missing NULL keyword
[SQL: SELECT policy.id AS policy_id FROM policy
WHERE policy.scope = :scope_1 AND policy.active IS 1]
[parameters: {u'scope_1': u'admin'}]
(Background on this error at: http://sqlalche.me/e/4xp6)
 `

**Comment by plettich** [comment]
I checked with an update from 3.3 to 3.4 to 3.5 and from 3.3 to 3.5, both went well and without issues (local PI testserver, Oracle XE 18c, cx-Oracle 7.3.0, Oracle Instantclient 19.6).
However we do not stamp the db version when setting up the database with `pi-manage createdb` thus a call to `pi-manage db upgrade` or `privacyidea-schema-upgrade` starts with the first version of the db and fails.
Stamping the db to the current version after an `pi-manage createdb` should help.

**Comment by laclaro** [comment]
Thank you very much for this clarification.

Does it make sense NOT to stamp the db after it was created by pi-mange createdb? Otherwise we could add this feature to this very command.

**Comment by laclaro** [comment]
@plettich As we stamp the db by default (#2708), I close this issue
