### ISSUE TITLE
Can't install Ubuntu 14.04 LTS packages on Debian 8.2

### ISSUE THREAD

**Issue by the-username** [privacyidea/privacyidea#262]
According to the [installation instructions](https://privacyidea.readthedocs.org/en/latest/installation/debian.html) for Debian Jessie I tried to install PrivacyIDEA on my server using the Ubuntu 14.04 repo. However, this resulted in the following error message:

<i>Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 privacyidea : Depends: python-sqlalchemy (< 0.9) but 0.9.8+dfsg-0.1 is to be installed
               Recommends: python-mysqldb but it is not going to be installed
               Recommends: salt-master but it is not going to be installed
               Recommends: salt-minion but it is not going to be installed
               Recommends: uwsgi but it is not going to be installed
               Recommends: uwsgi-plugin-python but it is not going to be installed</i>

Could you please provide packages for Debian 8.2?

Thank you very much for your help!

**Comment by cornelinux** [comment]
I guess you tried to run:

   apt-get install privacyidea ?

The package "privacyidea" is an old package name which was only used till version 1.5.
The install instruction you referenced, ask you to install "privacyidea-apache2" (you could also install privacyidea-nginx)

If you do not want to install the webserver configuration, which is part of the "-apache2" and "-nginx" meta package, the base package is named "python-privacyidea".

There are efforts to add privacyidea into the next major debian release.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800684

Please drop me a note, if installing "privacyidea-apache2" worked for you.

Kind regards
Cornelius

**Comment by the-username** [comment]
Ah, sorry, you are right.

At first I used this (guide)[https://www.privacyidea.org/doc/current/installation/], but I didn't save it. To provide a helpful link for this bug report, I googled it again but accidentally linked the other version and not the guide I used to install privacyIDEA when I received the error message.

After using this meta-package, everything works fine.
Thank you!
