### ISSUE TITLE
Indicate in response, if an entry field should be displayed in challenge/response

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2624]
The client components/plugin sometimes have a difficult time to evaluate if an entry field should be displayed or not.
This depends on the token type but this also depends on e.g. multi challenge processes like PIN change.

The privacyIDEA server should return the information, if an *entry field* should be displayed.

This can be added to each challenge in the multi_challenge list in the response like

    "display_input": True

**Comment by nilsbehlen** [comment]
this was discussed and implemented in #2719
