### ISSUE TITLE
Yubikey serial is wrong (webauthn)

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#2631]
When enrolling a webauthn token on a yubikey, the serial that is displayed in privacyidea (Yubico U2F EE Serial xxxxxxxx) is not the serial that is printed on the yubikey or shown in the yubikey-manager.
When using multiple yubikeys, there is no way to identify which yubikey to use with which challenge.

**Comment by plettich** [comment]
As discussed offline, this is actually a security feature of WebAuthn to avoid linking profiles to WebAuthn hardware IDs.
However we should check how the WebAuthn API works with multiple connected tokens.

**Comment by cornelinux** [comment]
@plettich I think this is somehow an issue-garbage. At least the topic is wrong. So I am closing it. If really necessary this should be opened with a different topic. Or even better: Check that two yubikeys work.
