### ISSUE TITLE
Enrollment wizard menu entry is shown even if user already has a token assigned

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2632]
If the webui policy `tokenwizard_2nd_token` is unset (users should not be able to use the token wizard if they already have a token enrolled), the `token enrollment wizard` menu entry is still shown in the UI.
The `token_wizard_2nd` variable is send with an empty list from the server but the UI checks for non-existence here:
https://github.com/privacyidea/privacyidea/blob/cd311f443352a049833557f2a87f17a939862092/privacyidea/static/components/token/views/token.html#L30

**Comment by cornelinux** [comment]
Interesting:

     ("user" == "user" and [])

avaluate to ``[]``  and not to ``False``.

**Comment by plettich** [comment]
> Interesting:
> ```
>  ("user" == "user" and [])
> ```
> evaluate to `[]` and not to `False`.

always entertaining: https://www.destroyallsoftware.com/talks/wat
