### ISSUE TITLE
Support TLS v1.3 in LDAP Resolver

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2637]
When verifying TLS in LDAP resolvers, we can choose to force a TLS protocol version, but not v1.3.

- Support TLS v1.3 enforcing
- We may be also able to force a TLS protocol version when NOT verifying the certificate

**Comment by cornelinux** [comment]
The question is, if LDAP3 supports TLS 1.3.
It did obviously not in the past. Check it and if available implement it.

**Comment by laclaro** [comment]
There is no dedicated PROTOCOL_TLSv1_3 in the ssl module. However, we should use PROTOCOL_TLS as default, which is the hightest common protocol version. At present we just fallback to PROTOCOL_TLSv1 if TLS_VERSION is not set in the resolver.

https://github.com/privacyidea/privacyidea/blob/6fc21dc46458240e50c82c1c96c01811775bd757/privacyidea/lib/resolvers/LDAPIdResolver.py#L768

Suggested behavior:

- generally exclude SSLv2 and SSLv3 fallback to use the highest TLS version available
- allow forcing a TLS version starting with TLSv1.0
- WebUI: optionally verify certificate

**Comment by cornelinux** [comment]
We must not exclude SSLv2 and v3. We never know what kind of wired LDAP servers are out there!

**Comment by laclaro** [comment]
SSLv2 is not in the ssl library anymore. SSLv3 can be included as a forcing option.

**Comment by cornelinux** [comment]
@laclaro When a concrete version is selected, what is the difference to "forcing" a version. Till now I assumed that *selecting* a version also "forces" the usage of this version.

**Comment by cornelinux** [comment]
@laclaro Please add in READ_BEFORE_UPDATE for 3.6 the note, that the default changes from 1.2 to 1.3 OR create a migration script, that sets non-set TLS Versions to 1.2 in ldapS-resolvers.

**Comment by cornelinux** [comment]
Unfortunately the concept was documented in the PR. I recall it here:

# Implemented Concept

- TLS v1.3 is now used as a default
- It is also possible to select a specific TLS version if 1.3 is not supported by the LDAP server. The LDAP resolver will always use the configured version.
- Protocols are not negotiated with the LDAP server
- updating from previous versions than 3.6 does the following in the migration script:
  *  set TLS_VERSION to 1.0, which was the old default.
