### ISSUE TITLE
Verify: Does userlist action work for realm admins, if several user realms are specified

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2644]
A realm admin is an administrator who is supposed to manage a dedicated realm.

What is not clear and should be verified is, if the admin action "userlist" works for a realm admin if several user-realms are specified in the policy. Can the realm admin actually see the users in the different realms?

**Comment by laclaro** [comment]
with a configured userlist policy, you can view the existing realms in the dropdown select, but you can only display and manage users in the allowed user realms (also realms set as superuser realms).
