### ISSUE TITLE
Error loading policy templates

### ISSUE THREAD

**Issue by FloMeyer** [privacyidea/privacyidea#2682]
### Top-level intent

When implementing Content Security Policies in a webserver or proxy, the Webui fails to load the privacyIDEA policy-templates from github.

I think it would be a better idea to store the templates locally in the privacyIDEA installation and not to load it from an external source.

### Configuration

* **privacyIDEA version**: 3.5.1

### Log file

![image](https://user-images.githubusercontent.com/2670188/112293141-19268200-8c92-11eb-8649-7018e8e56868.png)

angular.js?v=20210128T103000:13630 Refused to connect to 'https://raw.githubusercontent.com/privacyidea/policy-templates/master/templates/index.json' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval' www.googletagmanager.com fonts.googleapis.com fonts.gstatic.com ajax.googleapis.com www.google-analytics.com connect.facebook.net www.facebook.com data:". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

![image](https://user-images.githubusercontent.com/2670188/112292668-9bfb0d00-8c91-11eb-84b4-321197dba20f.png)

**Comment by cornelinux** [comment]
There is a policy, which you can use to define your own local repository for the templates.

**Comment by plettich** [comment]
Cool, didn't know that. Documentation is here: https://privacyidea.readthedocs.io/en/latest/policies/templates.html#policy-templates

**Comment by FloMeyer** [comment]
Yeah, and i should have read the fucking manual! :D sorry!
