### ISSUE TITLE
Misleading log-message when admin login fails

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2714]
When an admin login fails due to a missing `password` parameter or a wrong password, the result of the `/auth/` request is a correct `"Authentication failure. Wrong credentials"`. But the privacyIDEA log contains the warning `A user 'admin' exists as local admin and as user in your default realm!` which is wrong.
If a `realm` is missing in the request, we set it to the default realm:
https://github.com/privacyidea/privacyidea/blob/895c967935cccb111ce594063cc50cb2a69f1e56/privacyidea/api/auth.py#L236
The warning gets printed if the admin authentication fails and the realm is the default (which is always the case for an internal admin):
https://github.com/privacyidea/privacyidea/blob/895c967935cccb111ce594063cc50cb2a69f1e56/privacyidea/api/auth.py#L312

**Comment by cornelinux** [comment]
"Authentication failure. Wrong credentials" is OK, since we do not want to leak any further information.

So it looks like that we only need to fix the audit log.
