### ISSUE TITLE
WebAuthn token rollout without user specified

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#2749]
Trying to enroll a webauthn token without a user specified results in a 500 internal server error.

Debug log:
File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/tokens/webauthntoken.py", line 924, in get_init_detail
    raise ValueError("Creating a WebAuthn token requires user to be provided")

If the user is necessary (why?) maybe it is possible to show that directly in the WebUI so the rollout can be done correctly.

**Comment by cornelinux** [comment]
It is not clear to me, why a user is actually required. Imho a webauthn token could also work without an assigend user.

**Comment by cornelinux** [comment]
Look at this: https://privacyidea.readthedocs.io/en/latest/modules/lib/tokentypes/webauthn.html

![image](https://user-images.githubusercontent.com/1908620/156593941-282ab651-c9c8-4ed1-aa19-0b5cc75d1641.png)

The documentation actually points out, that we need a user.
