### ISSUE TITLE
sql resolver where clause

### ISSUE THREAD

**Issue by deborahgu** [privacyidea/privacyidea#2752]
(Sorry if this is already in requested features; I searched but didn't see it.)

**Is your feature request related to a problem? Please describe.**

I'd like to be able to use all the possible `WHERE` filter verbs in the SQL ID resolver. Currently missing: `(NOT)? (BETWEEN|IN|<>|!=|<=|>=)`.

I'm trying to filter the list of available users in the SQL resolver by a field which `IS NOT NULL`, but the where clause splitter (`(w_column, w_cond, w_value) = part.split()`) doesn't work with the two-token filter verb `IS NOT`.

**Describe the solution you'd like**

I'd like to be able to use `foobar is not null` in the where clause.

**Describe alternatives you've considered**

I'm currently using `length(foobar) > 0` but that's more database load, and I'm not sure it will work in all cases.

**Additional context**

The code in question is at [IdResolver._append_where_filter](https://github.com/privacyidea/privacyidea/blob/7199be70bbe1ebee908518a8b529ac3637a86ca1/privacyidea/lib/resolvers/SQLIdResolver.py#L272-#L292).

(Ideally I'd _really_ like to be able to do a `join` in the SQL resolver, both for the where clause and to get more fields into the mapping, but based on how the documentation is written I'm guessing that's already on an eventual roadmap.)

Thanks!

**Comment by cornelinux** [comment]
A join is not possible.
SQLAlchemy can not map a joins or views.

Currently I do not see, if or when we will extend the where conditions (especially as mentioned for some reasons  - no views - sometimes DB tables have to be restructured with cron jobs anyways).

But you are free to issue a PR for easier conditions, if you already have identified the location.
