### ISSUE TITLE
Fresh installation fails due to missing module flask._compat

### ISSUE THREAD

**Issue by direvus** [privacyidea/privacyidea#2761]
We are evaluating PrivacyIDEA to replace our LinOTP instance, due to the Python2 EOL.  Unfortunately I haven't had any success in getting PrivacyIDEA installed using the instructions in the docs.  pi-manage fails due to a ModuleNotFoundError trying to import flask._compat in flask_script.

I understand that the flask._compat error is due to Flask-Script being abandoned, and falling out of compatibility with Flask >= 2, per #1211.  However Flask 2 gets pulled in when I install privacyidea with pip.  Currently this breaks pi-manage, so the installation workflow is dead.

Is there a way I can work around this?

Just as an experiment, I tried hacking flask_script/__init__.py to import `text_type` from six instead of flask._compat, which got me past that error but pi-manage still fails with:

```
Traceback (most recent call last):
  File "/root/venv/bin/pi-manage", line 85, in <module>
    from flask_migrate import MigrateCommand
ImportError: cannot import name 'MigrateCommand'
```

### Top-level intent

Install a fresh instance of pi on RHEL 7.9

### Steps to reproduce

1. Launch a RHEL 7.9 instance in AWS
2. Install `python3` from yum
3. Create a new virtual environment with `python3 -m venv`
4. Activate the venv
5. Upgrade pip with `python3 -m pip install --upgrade pip` inside the venv
6. Install privacyidea with `python3 -m pip install privacyidea`
7. (Notice that Flask 2.0.1 has been pulled in, that's not good ...)
8. Try to run `pi-manage create_audit_keys`, it fails.

### Expected outcome

pi-manage should execute successfully.

### Actual outcome

pi-manage failed with a ModuleNotFoundError:

```
# pi-manage create_audit_keys
Traceback (most recent call last):
  File "/root/venv/bin/pi-manage", line 83, in <module>
    from flask_script import Manager, Command, Option
  File "/root/venv/lib64/python3.6/site-packages/flask_script/__init__.py", line 15, in <module>
    from flask._compat import text_type
ModuleNotFoundError: No module named 'flask._compat'
```

### Configuration

* **privacyIDEA version**: 3.5.2 (latest from pip)
* **Installation method**: pip 21.1.2
* **Python version**: python 3.6.8-18.el7
* **Operating system**: RHEL 7.9
* **Webserver**: haven't gotten that far :/
* **Token database**: Postgres

### Log file

N/A

**Comment by cornelinux** [comment]
Between step 5 and 6 you should install all requirements manually.
This way you ensure, that to new versions of requirements do not break things.

We are just updating the docs:
https://github.com/privacyidea/privacyidea/blob/master/doc/installation/pip.rst#deterministic-installation

Alternatively you can 
1. install on Ubuntu LTS (easily done in 2 minutes)
2. get an enterprise SLA with RHEL support.

**Comment by direvus** [comment]
If I could use Ubuntu, I would, believe me.  The use of RHEL is forced on us by the customer.  We'll try the "deterministic" option, thanks for the reply.
