### ISSUE TITLE
Extend Policy Documentation

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2768]
We have a number of undocumented policies. We should add them to the documentation.

# Policies with missing documentation

## admin:
- [x] caconnectordelete
- [x] caconnectorread
- [x] caconnectorwrite
- [x] clienttype
- [x] delete (listed as `remove`)
- [x] fetch_authentication_items
- [x] machinelist
- [x] manage_machine_tokens
- [x] managesubscription
- [x] privacyideaserver_read
- [x] privacyideaserver_write
- [x] radiusserver_read
- [x] radiusserver_write
- [x] reset
- [x] set_hsm_password
- [x] set
- [x] settokeninfo
- [x] spass_otp_pin_contents (These are referenced [here](https://github.com/privacyidea/privacyidea/blob/9094bc5e0f1742af600dc448b07784b7a47ba47d/doc/policies/admin.rst#otp_pin_contents), I see no necessity to explicitly name them, @cornelinux )
- [x] spass_otp_pin_maxlength
- [x] spass_otp_pin_minlength
- [x] statistics_delete
- [x] statistics_read
- [x] tokenrealms
- [x] triggerchallenge (listed as trigger_challenge)
- [x] enroll* (listed as `init`)

## user
- [x] otp_pin_set_random
- [x] spass_otp_pin_contents (These are referenced [here](https://github.com/privacyidea/privacyidea/blob/9094bc5e0f1742af600dc448b07784b7a47ba47d/doc/policies/user.rst#otp_pin_maxlength), I see no necessity to add its own section / @cornelinux)
- [x] spass_otp_pin_maxlength
- [x] spass_otp_pin_minlength
- [x] userlist

## webui
- [x] dialog_no_token
- [x] hide_welcome_info
- [x] privacy_statement_link
- [x] show_seed
- [x] timeout_action
- [x] tokenwizard_2nd_token
- [x] user_details

## enrollment
- [x] appimageurl
- [x] hotp_yubikey_access_code (is not used anymore?, see below)
- [x] push_ssl_verify
- [x] webauthn_challenge_text

## register
- [x] registration_body

## authentication
- [x] push_ssl_verify
- [x] sms_challenge_text, u2f_challenge_text, email_challenge_text
- [x] webauthn_challenge_text

# Documented but not in privacyIDEA anymore

## admin
- [x] init (remove and add enroll section like in user scope documentation)
- [x] manageToken (is called tokenrealms now)
- [x] remove (duplicate of `delete`?)

## enrollment

- [x] yubikey_access_code is not used anymore by the code. Remove all occurrences.

**Comment by cornelinux** [comment]
@laclaro Really? Please be more specific!

**Comment by laclaro** [comment]
```
# get documentation policies
for scope in admin user webui register enrollment authentication authorization; do wget https://privacyidea.readthedocs.io/en/latest/policies/$scope.html -qO- | grep 'h2' | grep -Eo ' </span>.*<a class="headerlink' | sed 's/\( <\/span>\|<a class=\"headerlink\)//g;s/|/\n/g;s/, /\n/g;s/ and /\n/g' | sort | uniq > ${scope}-pol-doc.txt; done
# get api policies
for scope in admin user webui register enrollment authentication authorization; do http http://localhost:5000/policy/defs/$scope authorization:$tok | jq -r '.result.value' > /tmp/${scope}-pol.json;  jq 'keys' /tmp/${scope}-pol.json | awk -F'"' '$0=$2' | sort | uniq > ${scope}-pol-api.txt; done
```

# Policies with missing documentation

## webui
- dialog_no_token
- hide_welcome_info
- privacy_statement_link
- show_seed
- timeout_action
- tokenwizard_2nd_token
- user_details

## admin:
- caconnectordelete
- caconnectorread
- caconnectorwrite
- clienttype
- delete
- fetch_authentication_items
- importtokens
- machinelist
- manage_machine_tokens
- managesubscription
- privacyideaserver_read
- privacyideaserver_write
- radiusserver_read
- radiusserver_write
- reset
- set_hsm_password
- settokeninfo
- spass_otp_pin_contents
- spass_otp_pin_maxlength
- spass_otp_pin_minlength
- statistics_delete
- statistics_read
- tokenrealms
- triggerchallenge (documented as trigger_challenge)
- enroll*

## enrollment
- appimageurl
- encrypt_pin
- hotp_2step_clientsize
- hotp_2step_difficulty
- hotp_2step_serversize
- hotp_force_app_pin
- hotp_yubikey_access_code
- losttoken_PW_contents
- losttoken_PW_length
- losttoken_valid
- push_ssl_verify
- totp_2step_clientsize
- totp_2step_difficulty
- totp_2step_serversize
- totp_force_app_pin
- webauthn_challenge_text

## register
- realm
- registration_body
- requiredemail
- resolver
- smtpconfig

## authentication
- challenge_text_footer
- email_challenge_text
- push_ssl_verify
- sms_challenge_text
- u2f_challenge_text
- webauthn_challenge_text

## user
- assign
- enroll*
- otp_pin_set_random
- spass_otp_pin_contents
- spass_otp_pin_maxlength
- spass_otp_pin_minlength
- userlist


# Documented but not in privacyIDEA anymore

## admin
- checkstatus
- import
- init
- manageToken
- remove

**Comment by laclaro** [comment]
@cornelinux should we delete the `spass_otp_pin_*` policies because we have tokentype as an extended condition?

**Comment by cornelinux** [comment]
The yubikey_access_code / hotp_yubikey_access_code results from the `yubikey_access_code` being defined in the HOTPTokenClass.

It was added in 2016 (pycharm git blame is your friend) and ment to be used by the admin cliend / enrollment client.
