### ISSUE TITLE
Migration from LinOTP fails on NOT NULL constraint on `token.id`

### ISSUE THREAD

**Issue by direvus** [privacyidea/privacyidea#2770]
Attempting to use the privacyidea-migrate-linotp.py script with postgresql+psycopg2 for both the databases:

```
Adding 40 tokens...
Insert token records 0 to 39 ...
Failed to insert chunk: (psycopg2.errors.NotNullViolation) null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (...)

...

(Background on this error at: http://sqlalche.me/e/13/gkpj)
Traceback (most recent call last):
  File "./privacyidea-migrate-linotp.py", line 579, in <module>
    main()
  File "./privacyidea-migrate-linotp.py", line 569, in main
    migrate(config_obj)
  File "./privacyidea-migrate-linotp.py", line 471, in migrate
    token_values[i]["id"] = token_serial_id_map[token_values[i]["serial"]]
KeyError: '...'
```

Looking in the new PrivacyIDEA database (created by `pi-manage createdb`), the table `token` has an `id` column which is set NOT NULL, but has no default value.  The migration script is trying to insert rows into this table, but is not providing a value for `id` fields.

If the `id` column is supposed to contain a synthetic primary key, it should probably be created with the type `serial` or `bigserial` in Postgres.

It turns out that the database does have sequences defined for these `id` columns, but they are not set as the column DEFAULT in the database.  To fix this, you can do the following for each table:

```
ALTER TABLE token ALTER COLUMN id SET DEFAULT nextval('token_seq');
ALTER SEQUENCE token_seq OWNED BY token.id;
```

I went through and set up the column defaults for `token`, `tokenrealm`, `tokenowner` and `tokeninfo`, and then the migration script was able to complete successfully.

**Comment by cornelinux** [comment]
The script is not intended and tested to run with postgres.

**Comment by direvus** [comment]
Yes, I can see that :)  It's pretty close though, we might be able to get it to work perfectly well with Postgres, with just some small tweaks.

I dug a little deeper and noticed that your models.py for the main app declares a `Sequence` for the `id` columns, e.g. `Sequence("token_seq")`, but the models baked in to the migration script are missing this.  It could be as simple as adding those Sequences to the models in the migration script.  I'd be happy to give it a try, and raise a PR if it works.
