### ISSUE TITLE
Push without Firebase. Mobile app error: Must not be null

### ISSUE THREAD

**Issue by imennodenis** [privacyidea/privacyidea#2772]
Hi!

Just updated to PI 3.6 and trying to test Push tokens without Firebase.
I have set _**push_firebase_configuration - poll only**_   in my push enrollment policy.
But when I try to enroll a new push token and scan QR code with iOS application I get an error:
_Must not be null. Please inform the creator of this QR code about the problem._

Am I missing something?

**Comment by cornelinux** [comment]
The code of the app, that handles this is not released in the app stores, yet.
https://github.com/privacyidea/pi-authenticator/commit/713d292b27c08df78959592bba04f45313bc2271

**Comment by imennodenis** [comment]
Thanks for clarification! We will look forward to the new version :)
