### ISSUE TITLE
Audit column 'info' is too short

### ISSUE THREAD

**Issue by direvus** [privacyidea/privacyidea#2773]
### Top-level intent

The column `Audit.info` is declared with type varchar(50), but this is not enough space to contain the messages the application is trying to store in this field.

For example, the mesage "ERR904: The user can not be found in any resolver in this realm!" has 64 characters.

I suggest the size of the field should be increased to at least 100 characters.

### Steps to reproduce

1. Submit a /validate/check request for an unknown user
2. Check the privacyidea log file

### Expected outcome

Application should store audit logs successfully, and return a valid error message for the request.

### Actual outcome

```
[2021-06-09 10:12:51,603][1244][139844274153216][ERROR][privacyidea.lib.auditmodules.sqlaudit:306] exception DataError('(psycopg2.errors.StringDataRightTruncation) value too longfor type character varying(50)\n',)
[2021-06-09 10:12:51,603][1244][139844274153216][ERROR][privacyidea.lib.auditmodules.sqlaudit:307] DATA: {'startdate': datetime.datetime(2021, 6, 9, 10, 12, 49, 848658), 'success': False, 'action_detail': '', 'client': '::1', 'client_user_agent': None, 'privacyidea_server': 'localhost', 'action': 'POST /validate/check', 'info': 'ERR904: The user can not be found in any resolver in this realm!', ...}
```

### Configuration

* **privacyIDEA version**: 3.5
* **Installation method**: pip with venv
* **Python version**: 3.6.8
* **Operating system**: RHEL 7
* **Webserver**: Apache + mod_wsgi
* **Token database**: PostgreSQL

### Log file

Shown above

**Comment by direvus** [comment]
Update: I bumped my local instance up to 100 for this column, but that still wasn't big enough.  I got a failure to create an audit record for a POST /policy/<name> action, it was trying to put the entire policy JSON into the 'info' column, that was 271 characters for a policy with only one action.

**Comment by cornelinux** [comment]
You can modify the length:

https://privacyidea.readthedocs.io/en/latest/audit/index.html?highlight=column_length#table-size

**Comment by direvus** [comment]
It's great that you can modify it, thanks for letting me know.  The default is still wrong though, so why would we leave the column with a broken default length, when it would be easy to fix it?

**Comment by cornelinux** [comment]
Thank you for asking.

> The default is still wrong though

This is *your* point of view in *your* situation. I have been doing this 2FA with such solutions for 11 years now. And there are other situations, where this default is totally right. E.g. there are DBMS that limit the total length of all columns in the table. If one column like "info" is too long, the table will not work at all.

Also, In theory privacyIDEA could write any length to this column. It depends in some API request on what kind and contents of parameters the user passes to privacyIDEA. So it would not even be clear what would be the "correct" length. 200 characters? 2000 Characters? Would you even be able to view 2000 characters in the WebUI?

Longer information can be truncated. Set ``PI_AUDIT_SQL_TRUNCATE = True`` in pi.cfg to do so. (This is automatically set, when installing with packed versions.)
You have the freedom to decide, how much of this info you want to or need to see and configure it accordingly.

To me this sounds like the correct way to handle it.

**Comment by direvus** [comment]
I do appreciate that my situation isn't the same as everybody else's.  But I don't think my situation is especially weird either.  I doubt that I would be the last person to bump into this problem.

2000 characters might not handle every single possible audit record, but we can say for sure that it will handle a lot more records than the 50 character limit will!

Displaying long text fields in the web UI is very solvable.

Are there any use-cases where it is good for PI_AUDIT_SQL_TRUNCATE to be False?  It seems strange to me that this is not switched on by default.  A truncated field is a shame, but a completely missing record can be a very bad problem for an audit log.  If you ever want to use the audit log for forensics, missing records is not acceptable.

**Comment by cornelinux** [comment]
Which part of the docs did you read and which pi.cfg template did you use, then?
I would like to improve this.
Thanks!

**Comment by direvus** [comment]
I believe my starting point was the example shown on the "Config File" chapter of the docs, https://privacyidea.readthedocs.io/en/v3.5/installation/system/inifile.html

**Comment by cornelinux** [comment]
I created a pull request to improve the documentation at this point.
Thank you.

**Comment by skinkie** [comment]
The standard push test "'Please confirm the authentication on your mobile device!'" directly causes into this issues. @cornelinux why not make this type a 'TEXT' instead?
