### ISSUE TITLE
WSGIScriptAlias not working as expected after upgrade to 3.6

### ISSUE THREAD

**Issue by stekalb** [privacyidea/privacyidea#2774]
I upgraded my test instance from 3.5 to 3.6.
I have the following configuration to be able to access pi using root / as well as /privid
I am quite sure it worked with 3.5 and stopped working after upgrade.
```
WSGIScriptAlias /privid      /etc/privacyidea/privacyideaapp.wsgi
WSGIScriptAlias /      /etc/privacyidea/privacyideaapp.wsgi
```
I also tried this settings
```
WSGIScriptAlias /privid      /etc/privacyidea/privacyideaapp2.wsgi
WSGIScriptAlias /      /etc/privacyidea/privacyideaapp.wsgi
```

/etc/privacyidea/privacyideaapp.wsgi
`application = create_app(config_name="production", config_file="/etc/privacyidea/pi.cfg")`
/etc/privacyidea/privacyideaapp2.wsgi
`application = create_app(config_name="production", config_file="/etc/privacyidea/pi.cfg")`

Apache runs into an "internal server error"

> [Thu Jun 10 11:28:23.431010 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142] mod_wsgi (pid=3629): Target WSGI script '/etc/privacyidea/privacyideaapp2.wsgi' cannot be loaded as Python module.
[Thu Jun 10 11:28:23.431071 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142] mod_wsgi (pid=3629): Exception occurred processing WSGI script '/etc/privacyidea/privacyideaapp2.wsgi'.
[Thu Jun 10 11:28:23.436644 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142] Traceback (most recent call last):
[Thu Jun 10 11:28:23.436801 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/etc/privacyidea/privacyideaapp2.wsgi", line 3, in <module>
[Thu Jun 10 11:28:23.436811 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     from privacyidea.app import create_app
[Thu Jun 10 11:28:23.436823 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/app.py", line 34, in <module>
[Thu Jun 10 11:28:23.436830 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     import privacyidea.api.before_after
[Thu Jun 10 11:28:23.436841 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/before_after.py", line 32, in <module>
[Thu Jun 10 11:28:23.436848 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     from ..lib.user import get_user_from_param
[Thu Jun 10 11:28:23.436876 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/user.py", line 56, in <module>
[Thu Jun 10 11:28:23.436886 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     from .resolver import (get_resolver_object,
[Thu Jun 10 11:28:23.436908 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/resolver.py", line 50, in <module>
[Thu Jun 10 11:28:23.436917 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     from .config import (get_resolver_types, get_resolver_classes, get_config_object)
[Thu Jun 10 11:28:23.436927 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/config.py", line 44, in <module>
[Thu Jun 10 11:28:23.436935 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     from ..models import (Config, db, Resolver, Realm, PRIVACYIDEA_TIMESTAMP,
[Thu Jun 10 11:28:23.436945 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/models.py", line 144, in <module>
[Thu Jun 10 11:28:23.436952 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     class Token(MethodsMixin, db.Model):
[Thu Jun 10 11:28:23.436962 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/flask_sqlalchemy/model.py", line 67, in __init__
[Thu Jun 10 11:28:23.436969 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     super(NameMetaMixin, cls).__init__(name, bases, d)
[Thu Jun 10 11:28:23.436979 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/flask_sqlalchemy/model.py", line 121, in __init__
[Thu Jun 10 11:28:23.436987 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     super(BindMetaMixin, cls).__init__(name, bases, d)
[Thu Jun 10 11:28:23.436997 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/api.py", line 76, in __init__
[Thu Jun 10 11:28:23.437004 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     _as_declarative(cls, classname, cls.__dict__)
[Thu Jun 10 11:28:23.437014 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in _as_declarative
[Thu Jun 10 11:28:23.437021 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     _MapperConfig.setup_mapping(cls, classname, dict_)
[Thu Jun 10 11:28:23.437031 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 160, in setup_mapping
[Thu Jun 10 11:28:23.437038 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     cfg_cls(cls_, classname, dict_)
[Thu Jun 10 11:28:23.437048 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 194, in __init__
[Thu Jun 10 11:28:23.437056 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     self._early_mapping()
[Thu Jun 10 11:28:23.437065 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 199, in _early_mapping
[Thu Jun 10 11:28:23.437073 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     self.map()
[Thu Jun 10 11:28:23.437082 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 696, in map
[Thu Jun 10 11:28:23.437090 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     self.cls, self.local_table, **self.mapper_args
[Thu Jun 10 11:28:23.437104 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "<string>", line 2, in mapper
[Thu Jun 10 11:28:23.437115 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "<string>", line 2, in __init__
[Thu Jun 10 11:28:23.437125 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
[Thu Jun 10 11:28:23.437133 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     return fn(*args, **kwargs)
[Thu Jun 10 11:28:23.437143 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 721, in __init__
[Thu Jun 10 11:28:23.437150 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     self._configure_properties()
[Thu Jun 10 11:28:23.437160 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1519, in _configure_properties
[Thu Jun 10 11:28:23.437167 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     column_key, column, init=False, setparent=True
[Thu Jun 10 11:28:23.437177 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1757, in _configure_property
[Thu Jun 10 11:28:23.437184 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     prop = self._property_from_column(key, prop)
[Thu Jun 10 11:28:23.437194 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1870, in _property_from_column
[Thu Jun 10 11:28:23.437201 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     columns = util.to_list(prop)
[Thu Jun 10 11:28:23.437211 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 815, in to_list
[Thu Jun 10 11:28:23.437219 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     if not isinstance(x, collections_abc.Iterable) or isinstance(
[Thu Jun 10 11:28:23.437228 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/abc.py", line 193, in __instancecheck__
[Thu Jun 10 11:28:23.437235 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     return cls.__subclasscheck__(subclass)
[Thu Jun 10 11:28:23.437245 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/abc.py", line 228, in __subclasscheck__
[Thu Jun 10 11:28:23.437252 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     if issubclass(subclass, scls):
[Thu Jun 10 11:28:23.437262 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/abc.py", line 228, in __subclasscheck__
[Thu Jun 10 11:28:23.437269 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     if issubclass(subclass, scls):
[Thu Jun 10 11:28:23.437278 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/abc.py", line 228, in __subclasscheck__
[Thu Jun 10 11:28:23.437285 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     if issubclass(subclass, scls):
[Thu Jun 10 11:28:23.437295 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   [Previous line repeated 1 more time]
[Thu Jun 10 11:28:23.437306 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/usr/lib/python3.6/typing.py", line 1154, in __subclasscheck__
[Thu Jun 10 11:28:23.437316 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     return super().__subclasscheck__(cls)
[Thu Jun 10 11:28:23.437326 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/abc.py", line 228, in __subclasscheck__
[Thu Jun 10 11:28:23.437334 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     if issubclass(subclass, scls):
[Thu Jun 10 11:28:23.437344 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/typing_extensions.py", line 800, in __subclasscheck__
[Thu Jun 10 11:28:23.437351 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     if issubclass(subclass, scls):
[Thu Jun 10 11:28:23.437361 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/typing_extensions.py", line 800, in __subclasscheck__
[Thu Jun 10 11:28:23.437368 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     if issubclass(subclass, scls):
[Thu Jun 10 11:28:23.437378 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/typing_extensions.py", line 800, in __subclasscheck__
[Thu Jun 10 11:28:23.437385 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     if issubclass(subclass, scls):
[Thu Jun 10 11:28:23.437395 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   [Previous line repeated 223 more times]
[Thu Jun 10 11:28:23.437406 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]   File "/opt/privacyidea/lib/python3.6/site-packages/typing_extensions.py", line 784, in __subclasscheck__
[Thu Jun 10 11:28:23.437413 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142]     if sys.version_info[:3] >= (3, 5, 3) or sys.version_info[:3] < (3, 5, 0):
[Thu Jun 10 11:28:23.437435 2021] [wsgi:error] [pid 3629:tid 140030416611072] [remote 172.17.22.20:51142] RecursionError: maximum recursion depth exceeded in comparison

**Comment by cornelinux** [comment]
To my understanding you can not run scriptaliases on "/" and a subdir "/privid".

You can run 

    WSGIScriptAlias /privid1      /etc/privacyidea/privacyideaapp.wsgi
    WSGIScriptAlias /privid2      /etc/privacyidea/privacyideaapp.wsgi

So in myunderstanding this is a misconfiguration of yours.

I also checked this with 3.5.2. Does not work as you configured it.
Since the first WSGIScript runs on "/" it will also try to resolve "privid", which does not exist.
Your main path needs to be different!
