### ISSUE TITLE
admin user may manage tokens of not-allowed-resolver-users

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2778]
# Scenario
- There is one `all-users` realm with multiple user-resolvers, say users1 and users2.
- An admin policy which has conditions on realm `all-users` and resolver `users1`.

# Outcome
- admin users cannot assign tokens to users from resolvers other than `users1`
- admin users can enable/disable, delete or unassign tokens of users from resolver `users2`

# Expected behavior
The admin policy conditioned on the resolver should prevent all actions for tokens assigned to users coming from resolvers other than `users1`.

Those API actions are done via serial, so privacyIDEA does apparently not take the tokenowner into account properly.

**Comment by laclaro** [comment]
PR https://github.com/privacyidea/privacyidea/pull/2779 adds a resolver check for admin action.

There could be a restriction for 
- user listing
- token listing
with a given user from a non-allowed resolver

**Comment by cornelinux** [comment]
Depends on #2810

**Comment by laclaro** [comment]
If a user of an admin acts on a token determined by its serial, we should generally determine the tokenowner

**Comment by cornelinux** [comment]
You mean, if "an admin acts on a token"... ?

**Comment by cornelinux** [comment]
In #2810 I add the resolving of the user, if only a token serial is given.
I.e. the request is enriched with the user object, who is the tokenowner of the token(serial).

This way all policies will match for such user - even if the admin only acts on the token.
Please check, I think this will also close this very issue.
