### ISSUE TITLE
day password token

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2781]
See https://github.com/privacyidea/pi-authenticator/issues/168

We could use the authentication cache to allow the reuse of a "TOTP" token for a complete day.
On the other hand, this might be a bit confusing, since if would be difficult to identify which token was actually configured as a day password, since it is defined in a policy and not within the token itself.

So we might either create a new token type or allow the reuse of the OTP value of the TOTP token within the time window. (via tokeninfo/attribute!)

# possibly use case

The token can be used for guests. For example, you can use it in a hotel for the W-LAN. A new guest gets by checking the PIN for the days he stays a the hotel. This way your W-LAN is safe and the guest still has easy exits.

Another use case could be a mail client. If your mail client can only password authentication, you can use this to change the password for example every week or every day. This way your mail client is more secure but can still be used conveniently.

# New token type

In contrast to TOTP token, this token type would intrinsically accept the same TOTP value throughout the whole day.
The counterpart would be on the privacyIDEA authenticator.

type: DayPasswordToken
config: timestep
special: accept more than once

# Implemantation

* [x] Implement the new token
      - new token class based on totp token
      - adding token to config
* [x]  WebUI
      - create token.enroll and token.enrolled views
      - adding token to tokenControllers.js
* [x] Docu
      - create a daypasswordtoken.rst
      - adding the token to tokentypes.rst
* [x] Write tests for the new token

**Comment by jona-samuel** [comment]
We can base the token on the TOTP token. We only need to change the new token so that the user can configure the period and that the top value can be used more than once.

- [ ] Implementation of the new token
- [ ] Test
- [ ] Documentation
- [ ] UI

**Comment by jona-samuel** [comment]
If we just want a new password every day, we can just use an event handler and don't need a new token.
What is the use case for this token?

**Comment by cornelinux** [comment]
@jona-samuel You need to define the name of the token and policies. TbpTokeClass is a very misleading name.
All over the code we have tokenclasses with long TokenClass names with readable and human understandable name.
We have no cryptic abbreviations! Mind this!

Also, Do not name the token "Time based password". This will be extremely misleading. Everbody will confuse it with a TOTP token, since half of the users actually think, that a TOTP token works this way, that they can enter this value during this timewindow. More than once.

Why did I originally choose "day password"? Since it reflects the use case of the tokenclass better. It is a kind of ticket, a voucher that works for the given amount of time. I.e. it is a different concept and scenario. This must be reflected in the name.

**Comment by cornelinux** [comment]
I would recommend using a different tokentype (not totp) in the QR code URI.
Please check with @nilsbehlen

**Comment by nilsbehlen** [comment]
DOTP?

**Comment by jona-samuel** [comment]
We will name the token daypassword.
For example: otpauth://daypassword/DayPassword0000536F?secret=NW6IT27XNRXOAZEP4GILXB3GCKCANVQR&issuer=privacyIDEA&algorithm=SHA256&digits=6&period=86400
