### ISSUE TITLE
Add a glossary

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2783]
We should add a glossary to the documentation.

There we can define words like *token*, *otp value*, *otp pin*, *time step*.
These might be rather clear to us developers but not to the admins.

We also need to define words, that currently seem to be used in different situations like *multi challenge*.

I think it is not necessary to define IT common words like *LDAP* or *RADIUS*. So we only need to define privacyIDEA specific words or words we defined ourselves.

Some more words and terms we need to not mix up:

* extended attribute mapping -> RADIUS
* extended conditions -> policies

**Comment by laclaro** [comment]
- internal administrator
- opt pin
- otp value
- tokeninfo
- userinfo
- userstore
- audit
- token owner
- machine
- locked token
- revoked token
- orphaned token
- failcount
- userid
- split @ sign
- subscription
- rollout state
- otp key
- seed
- challenge
- multi challenge
- scope
- resolver
- realm
- event
- WebUI
- attribute mapping
-
