### ISSUE TITLE
Search configured policies

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2788]
If you have configured a lot of policies you might wonder, if and how a certain setting is actually set.

"Do we have configured two step enrollment? If so, in which policy?"

A way to search the configured policies would be great.

**Comment by laclaro** [comment]
We can include this feature in the dashboard search #2458

**Comment by cornelinux** [comment]
Just add a `pi-filter` to the column "action" in the policy list view.

**Comment by NNLemling** [comment]
- [ ] remove general search box

- [ ] correction of the table columns
