### ISSUE TITLE
sorted policy output from GET /policy

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2802]
GET /policy delivers unsorted output. It might be nice to have always the same order (alphabetical?)

**Comment by plettich** [comment]
As said in the closed PR: i think this should be done by the front-end. We usually do not have that many policies that the JavaScript sorting would be too slow...

**Comment by cornelinux** [comment]
It seems to be relevant for exporting policies via pi-manage or API.
The default sorting is by priority.

But on the other hand everything works fine in the UI.

One way would also be to only sort in the exporter.

**Comment by cornelinux** [comment]
Can a default sorting in the API be solved by adding a cascading order_by (by scope, by priority) on the database layer?

**Comment by cornelinux** [comment]
Sorting happens by priority.
Curentyl seems not necessary
