### ISSUE TITLE
Restrict the amount of tokeninfo shown to the Helpdesk

### ISSUE THREAD

**Issue by theodor-franke** [privacyidea/privacyidea#2819]
**Is your feature request related to a problem? Please describe.**
We want to have three different levels of access to the PrivacyIDEA WebUI

* normal users -> Selfservice (seeing their own tokens and create tokens for them self)
* Helpdesk Users -> Helpdesk (Seeing all Tokens and users and create/delete/edit ...)
* Admins -> Admin (Change config and see everything)

This is all possible, but our internal privacy-rules say that the Helpdesk should see as little Information as needed to perform the Task. In the Token-info a Helpdeskuser can see the last time a user has logged in or how many times a user logged in. We dont want to show this information to the Helpdeskuser.

**Describe the solution you'd like**
I created a PR #2816 implementing a policy to exclude a list of token-info-fields.

**Comment by cornelinux** [comment]
Thanks a lot.
In the meantime: Do you actually needs this information?
You can also simply remove this info (last_auth and count_auth).

**Comment by theodor-franke** [comment]
That's an option we have not yet considered. But I think that this information is actually pretty Interesting for Debugging reasons in case of Malfunction.

**Comment by laclaro** [comment]
@theodor-franke I reviewed your PR. Please get in touch if you have any questions.

We should add documentation and a simple test later on.

- [ ] add policy and WebUI code
- [ ] Add documentation
- [ ] Add test

**Comment by cornelinux** [comment]
Maybe we should use a positive logic like "list the tokeinfo fields, that a helpdesk user is allowed to see".
