### ISSUE TITLE
Import Policy with pi-manage fails on 3.6 due to an unexpected keyword

### ISSUE THREAD

**Issue by pepun** [privacyidea/privacyidea#2829]
### Import a policy using the pi-manage-Script

When importing a policy, which was exported to a file before, the import fails with

```set_policy() got an unexpected keyword argument 'condition'```

### Steps to reproduce

1. Export a policy to file: 
2. Import the policy: ```pi-manage config import policy -f FILENAME```

### Expected outcome

The policy is imported to the database.

### Actual outcome

The import fails with ```set_policy() got an unexpected keyword argument 'condition'```.

### Cause
In the ```pi-manage```-Skript in the ```_import_conf_policy```-method the keyword for the policy-conditions is 'condition' instead of 'conditions' (missing 's') as it is in the ```set_policy```-Method of the ```policy```-module. I think it just needs to be changed to 'conditions'.

**Comment by cornelinux** [comment]
Thanks @pepun 
Actually it looks like as if it must be

                            conditions=policy.get("conditions"),
