### ISSUE TITLE
privacyidea-token-janitor --orphaned flag needs argument

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2832]
It might be considered unusual that we call

`privacyidea-token-janitor find --orphaned 1`

instead of

`privacyidea-token-janitor find --orphaned`

The required change is small

```python
@manager.option('--orphaned', action='store_true',
                help='Whether the token is an orphaned token.')
```

However, in that case we break all existing cron jobs, so this behavior won't change too quickly.

**Comment by cornelinux** [comment]
This sounds sensible in case of a fresh start, but you will break *backward compatibility*.  All custom scripts, using this parameter will break!

I would rather **add** the lines around 302:

~~~~python
if orphaned in ["0", "False"] and token_obj.is_orphaned():
                continue
~~~~
to be able to find tokens, that are explicitly *not* orphaned. Which is currently not possible and which will not be possible, if we'd change the parameter to expect no value.

**Comment by cornelinux** [comment]
Thanks for pointing this out. So I think this is now a bit more streamlined.
