### ISSUE TITLE
Update 3.3.3 -> 3.6.2

### ISSUE THREAD

**Issue by katgirl** [privacyidea/privacyidea#2844]
A direct update is not possible because the policy.pinode column is required.

Workaroud: 
```
pi-manage db upgrade -d privacyidea/migrations 3ba618f6b820
pi-manage db upgrade -d privacyidea/migrations fa07bd604a75
```

**Comment by plettich** [comment]
Hi @katgirl unfortunately i can't reproduce this issue. How did You do the db upgrade? Did You stamp the db before the upgrade?
Usually the migration script should take care of creating the column during the upgrade.

**Comment by laclaro** [comment]
Might this be related to https://github.com/privacyidea/privacyidea/issues/2618 (db was not stamped).

**Comment by cornelinux** [comment]
I think this is not a development issue but rather an administrative one and as such it should be discussed at https://community.privacyidea.org.
