### ISSUE TITLE
Keep existing PIN with Token roll-over

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2845]
If a PIN policy is set (length, content) the roll-over will fail if no (new) PIN is given in the roll-over page.
Ideally the PIN should stay the same on a roll-over.

**Comment by laclaro** [comment]
I am not so sure if keeping the PIN the same is the ideal way. 
What if PIN policy has changed since the initial enrollment?
Maybe your old device is in doubt to be compromised and you want to move to a new clean one. It might be wise to choose a new PIN.
