### ISSUE TITLE
dropdb doesn't remove "alembic_version" table

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2848]
Since we don't know if or how a new database will be initialized, we should drop the `alembic_version` table as well.
In `pi-manage dropdb` we just call Flask-SQLALchemys `drop_all()` method which does not know anything about the `alembic_version` table:
https://github.com/privacyidea/privacyidea/blob/b4377cab7863671f4276a6e372a727af0b94dac7/pi-manage#L566

- [x] When using `pi-manage dropdb` the `alembic_version` table won't be deleted.

**Comment by NNLemling** [comment]
fixed in 37c3f3b0cbc5d39d6688f71f0c2d88d8b0364443 and 7dd23f5acc0fe51b1940f71402b394b918bbd4a7.
