### ISSUE TITLE
Machines in Policy Conditions

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2851]
Machine resolvers can be used to fetch computers from LDAP/Active Directory. If we could reliably determine the IP-Address from DNS for all the machines in the resolver (#2712), we could also start assigning policies to machine resolvers and therefore to all the client computers in this computer group (#285).

**Comment by cornelinux** [comment]
I think we will get rid of machines in the long run.
The SSH keys and offline tokens will be assigned to virtual groups. #3299 #3300
