### ISSUE TITLE
Default push registration/authenticating endpoint

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#2853]
As of now, the registration endpoint has to be set specifically in the rollout policy. If it is not set, trying to enroll a pushtoken will raise the error that no registration endpoint is specified.
I would suggest to have a default registration url (https://hostname/ttype/push) and only use the policy entry to overwrite it.
Or mark the policy entry as mandatory when creating the push rollout policy.

**Comment by cornelinux** [comment]
I think in most cases the URL that the smartphone is capable of communicating to is another one than the hostname. So in most cases the default will not work.

We also could 
* improve the documentation or
* *display a warning on the push enrollment dialog* similar to email and sms token with a link to policies.
