### ISSUE TITLE
Raise error when the token already has a different owner on token_init

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2860]
If you issue an init request 

`/token/init type=spass serial=MYSPASS pin=123 user=test realm=test`

but the token with serial MYSPASS is already assigned to a different user, the request succeeds, but the assignment will not happen, of course.

We may log a warning to make this behavior transparent.

**Comment by laclaro** [comment]
actually the above request creates a second tokenowner entry. The request should therefore fail in the first place and before we issue db_token.save() in
https://github.com/privacyidea/privacyidea/blob/99d10ff1b3cb27af5c9afe3d3e9dd9d1f076fec0/privacyidea/lib/token.py#L1069

**Comment by cornelinux** [comment]
Indeed it creates a second tokenowner. In the long run this could be the desired behaviour.
