### ISSUE TITLE
Allow to define the contents of a generated pw-token

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2864]
At the moment the pw token has very limited capabilities. You may already enroll a pw token via the api, but you are left with some seed://hexstring password.

I suggest to decouple the password generation (which honors some special contents policy) from the lost token process in
https://github.com/privacyidea/privacyidea/blob/99d10ff1b3cb27af5c9afe3d3e9dd9d1f076fec0/privacyidea/lib/token.py#L1845

I further suggest to return the password like for the registration token with some special field "password".

This change makes the pw token type more useful and may be one of several steps towards application-specific passwords.

**Comment by cornelinux** [comment]
Sounds sensible to me to add an additional password field in the respons.

This way the PW token could also be included in enrollment and notification processes using event handlers.

**Comment by cornelinux** [comment]
The `genkey=1` already creates a random password:

~~~~
% http --verify no POST https://localhost/token/init authorization:$TOK type=pw genkey=1
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: Keep-Alive
Content-Length: 1783
Content-Type: application/json
Date: Tue, 07 Sep 2021 12:50:55 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.41 (Ubuntu)

{
    "detail": {
        "otpkey": {
            "description": "OTP seed",
            "img": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXIAAAFyAQAAAADAX2ykAAACWUlEQVR4nO2bTYrjMBBGX40CvVSgDzBHUW42zM3kG8nLBptvFpIcJ9A03SQmGkoLJ7HfouCjfl0x8Z0z/foWDs4777zzzjvv/Ge8tXOC6byaXQC7zGb1Ymb13qva7/xn51Q/UgaY3yGVFTGfEXNYDMICgB1jj/PP4WfrXgvYJS7YJX6YMlAd+1h7nH8mP52Byd5kl5ewx/mf8qf7G5OBmN8ErCbmY+1x/jl8lJQBkpZaZMHc/FfScrQ9zj+Un8zM7AxV1T8lbKF5reXzsfY4/yC+xufdkHI6Y8BqED8M4u0A89Xsd/6LI0kiFQCClAlSjgvKhP0DSVJ+Nfud/+JUfQGaqlECgqCKDCRJJNd3QJ7ml7GLXN1ZC6QS2oNUNu7V7Hf+i9MFlWqZnLQgFXaX6smu74h8j8+1P+oOS8+/ylGSiuffQfl9fE5qCVcqYQvSeP4dmN/VV/Vn3l1akeXxeVz+pj/aZGz3Qg3NEN1/B+X3gnJNuFo2//X8OzK/a4iahNeuqFfS7r/j8v390fyuPmIOwGwIgowoLOX1pGPscf45fJ01L9s3CeYTyrMZ0znojn+2Pc4/ht/PNzLQiqyy1c/QJlmef0fkd/XVvmruM4/a+hIXPP8Oyd/2v13aa2mV6qSjH9d3TL4qWNp+nXLdz4HqunWd40h7nH8Qv59vpBLaq8FUF3Ku+RePz/8Jnwp1dbINOeKC/v72/atB+U/8t7T6uc8nff48OB9bfySVtfW/qaxml7gNsQ61x/nH8Pf1864hautY7YH775C8+f+7nXfeeeedd/5w/h8VtDC3Y9RVrAAAAABJRU5ErkJggg==",
            "value": "seed://e742adde64adc3260a1b73a18248222bfad4d796"
        },
        "serial": "PW0004F5C8",
        "threadid": 140379145295616
~~~~

Well, the password "e742adde64adc3260a1b73a18248222bfad4d796" looks a bit awkward.

But after all the value of the password is already returned. So we problabyl should rather add **enrollment** policies:

* scope: enrollment
* pw_len: length of the password to be generated
* pw_contents: contents of the password to be generated. (This could contain cns and [....] like with the pins).

**Comment by cornelinux** [comment]
The `genkey` is currently handled completly by the basclass `TokenClass`.

https://github.com/privacyidea/privacyidea/blob/76b272abf56b6b98ada8c7cf3f4256ba0129d17f/privacyidea/lib/tokens/passwordtoken.py#L146

We would have to generate the "otpkey" and pass it to the `TokenClass.update` method.
