### ISSUE TITLE
How to install it correctly

### ISSUE THREAD

**Issue by beepupa** [privacyidea/privacyidea#2866]
I refer to https://privacyidea.readthedocs.io/en/latest/installation/centos.html
But when I run it, it says something wrong
![image](https://user-images.githubusercontent.com/36186038/129330457-7b0e522e-8536-48b2-b996-a7996f7c973c.png)

**Comment by beepupa** [comment]
![image](https://user-images.githubusercontent.com/36186038/129331030-ab30ed50-ad6b-443f-aa1f-9271ae10e52b.png)

This is my configuration file

**Comment by cornelinux** [comment]
Your line 20 sucks! ;-)
