### ISSUE TITLE
privacyidea-diag: Add database schema version to config output

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2873]
The file privacyidea.config should contain the alembic version in a database sections.
This would be the output of

    pi-manage db current -d /opt/privacyidea/lib/privacyidea/migrations

if privacyIDEA is installed in the usual place.

**Comment by cornelinux** [comment]
@NNLemling could this be s.th. for you, since you already worked on privacyidea-daig?

**Comment by NNLemling** [comment]
This is already implemented and should be displayed in the diag_file under "current_db_revision".

```
current_db_revision() {
	log
	log "SECTION: current_db_revision"
	log "============================"
	call_pi_manage db current -d /opt/privacyidea/lib/privacyidea/migrations/ >> "$tempfile"
}
```

**Comment by plettich** [comment]
since this is already implemented, i close this issue.
