### ISSUE TITLE
How make authentication token's validity more than 1 hour.

### ISSUE THREAD

**Issue by xiaochao** [privacyidea/privacyidea#2898]
![image](https://user-images.githubusercontent.com/1953662/136729291-9324293b-bd9f-4cb1-80e0-41b58eb30d49.png)

**Comment by cornelinux** [comment]
The one hour is a fixed value in the code. There are basially two possibilities:

1. We could make the value configurable in pi.cfg, which would be easy doable in a couple of code lines.
2. We could implement a jwt-renew mechnism, which would be more complicated.

**Comment by xiaochao** [comment]
> The one hour is a fixed value in the code. There are basially two possibilities:
> 
> 1. We could make the value configurable in pi.cfg, which would be easy doable in a couple of code lines.
> 2. We could implement a jwt-renew mechnism, which would be more complicated.

Thank you.
