### ISSUE TITLE
Option to set a default value for TOTP OTP length in the web interface

### ISSUE THREAD

**Issue by sh-msh** [privacyidea/privacyidea#2901]
We use TOTP-Tokens. Default OTP length shall be '8', but we need '6' as an option. Currently, default in the web interface is '6'.
We would like to set a default as it is possible for the "Default hashlib".

There is the general DefaultOtpLen setting. We have set this to '8', but it has no effect for the web interface. When enrolling a new token, length '6' is pre-seleced. The admin has to manually select '8' for each token. This is cumbersome and error-prone.

I understand that using policies, I can force a specific length via 'hotp_otplen and totp_otplen'. So I can set 8 but lose the ability to chose 6 when needed. This is not a viable option for us.

One option would be for the DefaultOtpLen to have an effect in the web interface. The configured value shall be preselected. Implementation could look like this:

```
--- a/privacyidea/static/components/token/controllers/tokenControllers.js
+++ b/privacyidea/static/components/token/controllers/tokenControllers.js
@@ -260,6 +260,7 @@ myApp.controller("tokenEnrollController", ["$scope", "TokenFactory", "$timeout",
             // preset TOTP hashlib
             $scope.form.hashlib = $scope.systemDefault['totp.hashlib'] || 'sha1';
             $scope.form.timeStep = parseInt($scope.systemDefault['totp.timeStep'] || '30');
+            $scope.form.otplen = parseInt($scope.systemDefault['DefaultOtpLen'] || '6');
         }
         if ($scope.form.type === "vasco") {
```

Although I am not sure this is the original intention of DefaultOtpLen.

Another option might be to add a default setting here https://privacyidea.readthedocs.io/en/latest/configuration/tokenconfig/totp.html#totp-token-config

Both options would be fine for our use-case.
Other suggestions welcome.

Using: 3.6.2-1focal

**Comment by cornelinux** [comment]
I think this is a generic thing. There are many occasions where you can not select the "preselected" value.
Look at tokentypes, if a user is allowed to enroll three different types of tokens, it is currently not possible to chose one type, that is preselected. (Just saying)

**Comment by cornelinux** [comment]
This is something I only heard once. In all other cases admins force users to specific values, thus easing the life by providing less choices.
I think I would like to not implement this. If in seldom cases this is really necessary, this can also be changed in the html templates  of the webui.
