### ISSUE TITLE
Show phone number in sms-challenge-text

### ISSUE THREAD

**Issue by taker93** [privacyidea/privacyidea#2917]
Hi,

we are working on a login functionality for our software that uses sms-authentication and are facing the "simple" problem, that our customers would like to see the phone number the OTP was sent to. (just three last digits)

Is it already possible to do that with PI?

As far I can see, the lines responsible for the challenge-text are here: https://github.com/privacyidea/privacyidea/blob/08aa910d374c7613cf078f5f447b6166d3c1c7cf/privacyidea/lib/tokens/smstoken.py#L318

But I can't figure out if there are any placeholders that can be used inside challenge-texts. If not it would be great to have that possibility!

**Comment by jona-samuel** [comment]
There is no option in privacyIDEA for this right now

For implementation:
maybe it's a way to implement placeholders to the custom challenge text.
This way you could write a challenge text like 'Please enter the OTP pin sent to the number #phonenumber'

**Comment by cornelinux** [comment]
I think this could be part of a bigger, more generic solution (see #1242 or #2993).
The Challenge text could also contain other information like the serial number or even the challenge itself.

There can be token types, that transport the challenge in a QR code or other image.

The next requirement would most probably be to do multilanguage challenge.

**Comment by jona-samuel** [comment]
I think the best way to get this all, is a function that replaces a placeholder from the challenge text with the entry from the challenge. In this way, we can show QR codes, token numbers or user information customized for the challenge. This way the admin just needs to know the key that is used in the challenge for the info he wants.
