### ISSUE TITLE
Privacyidea dashboard 

### ISSUE THREAD

**Issue by ALI-Mansou** [privacyidea/privacyidea#2931]
i ask if i can change WEB UI of the privacy idea ?

**Comment by cornelinux** [comment]
If you want to customize the web ui, this is described here:
https://privacyidea.readthedocs.io/en/latest/faq/customization.html

Also, in the pi.cfg you can redefine the index.html and load your complete own WebUI.

Please issue questions in regards to the usage of privacyIDEA here:
https://community.privacyidea.org
