### ISSUE TITLE
 configration rlm_perl.ini

### ISSUE THREAD

**Issue by ALI-Mansou** [privacyidea/privacyidea#2933]
hi 
how i can configure Fortinet's VSA in rlm_perl.ini for  add groups to fortinet ?

**Comment by cornelinux** [comment]
Sry. this deals with the development of privacyIDEA. This is no support portal.

**Comment by ALI-Mansou** [comment]
> Sry. this deals with the development of privacyIDEA. This is no support portal.

thanx
