### ISSUE TITLE
Doesn't work with the latest MariaDB

### ISSUE THREAD

**Issue by gregharvey** [privacyidea/privacyidea#2936]
### Top-level intent

Firstly, apologies if you consider this a feature request, but when trying to set things up with MariaDB installation succeeded but I couldn't save any resolvers to the database.

### Steps to reproduce

1. Install privacyIDEA on an EC2 instance at AWS
2. Create a new RDS instance with the latest MariaDB version
3. Install the database as usual with pi-manage
4. Login to the new instance and try to save a resolver (you can't)

### Expected outcome

I'd expect it to just work and save my resolver, as it does with a MySQL 5.7 RDS instance (I haven't yet tried MySQL 8.0 - maybe that will have problems too?)

### Actual outcome

MySQL integrity errors like this:

```
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '0' for key 'PRIMARY'")
```

For more info see the community forum post here: https://community.privacyidea.org/t/cannot-save-ldap-resolver/2231/3

### Configuration

* **privacyIDEA version**: 3.6
* **Installation method**: PyPI
* **Python version**: 3.7.3
* **Operating system**: Debian 10
* **Webserver**: Apache2
* **Token database**: MariaDB 10.5 on AWS RDS

### Log file

```
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '0' for key 'PRIMARY'")
[SQL: INSERT INTO resolverconfig (resolver_id, `Key`, `Value`, `Type`, `Description`) VALUES (%(resolver_id)s, %(Key)s, %(Value)s, %(Type)s, %(Description)s)]
[parameters: {'resolver_id': None, 'Key': 'TIMEOUT', 'Value': '5', 'Type': 'int', 'Description': ''}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

Thanks!

**Comment by plettich** [comment]
Hi @gregharvey 
I could not reproduce this with the latest mariadb (10.6.5) using a docker container. However it could be that AWS does some things differently.
When a new resolver is created, an entry in the database will be saved and the corresponding id returned:
https://github.com/privacyidea/privacyidea/blob/c08154951bb02ddc1794157bd19c7d699d20d5e9/privacyidea/lib/resolver.py#L127
In the following code the resolver config entries are created which, in Your case, throws an error. Somehow the `resolver_id` parameter is `None` which should not happen.
Could You set the privacyIDEA log level to Debug and try to recreate the error? Maybe we can get some more information from the logs.
