### ISSUE TITLE
Prometheus Metrics endpoint

### ISSUE THREAD

**Issue by scbay** [privacyidea/privacyidea#2948]
We are currently evaluating PrivacyIDEA as 2fa authentication solution and also want to scrape monitoring metrics from our prometheus server but we couldn't find any endpoint or exporter yet. We found only the monitoring and statistics modules but they seem not to be sufficient for us.

For our scenario the following metrics (at least) would be helpful:
- health status of the application
- failed/sucessful authentication requests

Thanks for your reply in advance.

**Comment by cornelinux** [comment]
You can compile your own statistics using the event handlers.
See: https://www.privacyidea.org/privacyidea-2-23-pre-events-handling-monitoring-and-statistics/

You can then use the monitoring endpoint to fetch the data you have recorded using the event handlers.
https://privacyidea.readthedocs.io/en/latest/modules/api/monitoring.html

For questions on how to *use* privacyIDEA, please turn to the community forum at https://community.privacyidea.org.
