### ISSUE TITLE
Check the client definition during creation of a policy

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2949]
**Is your feature request related to a problem? Please describe.**

The function [check_ip_in_policy](https://github.com/privacyidea/privacyidea/blob/982329aa684ad096e7836e048d808aaca6ece4b9/privacyidea/lib/utils/__init__.py#L712) verifies if the given client IP is contained in the given IP settings list.
However, if the list contains an invalid IP definition, it raises a 500 Error as expected.

We should use this very same function (check_ip_in_policy) during the creation of a policy, so that we already raise an error during the saving of the policy.

**Describe the solution you'd like**

We should check this on the library level [here](https://github.com/privacyidea/privacyidea/blob/2d240464961dfdc2f1a6560ed99fa051e543c6b7/privacyidea/lib/policy.py#L1338). We can ignore the outcome and simply use the fact, that an invalid definition raises an exception:

~~~~python
    if type(client) == list:
        client = ", ".join(client)
    # It does not matter, which IP we check. An invalid "client" definition will raise an exception
    check_ip_in_policy("127.0.0.1", client.split(","))
~~~~

**Describe alternatives you've considered**

None

**Additional context**

Do not forget the start with some tests in test_api_policy.

**Comment by NNLemling** [comment]
Fixed in 3463c9989fab8a353dc4506449dcce7dcedf8730.
