### ISSUE TITLE
Link Online-Documentation in the WebUI

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#2952]
On the config page of the SMS Gateway
The function to customize the SMS sent to the user ist not clear enough
All the possible tags that can be used should be displayed on this page.

* [ ] #3204

**Comment by NNLemling** [comment]
Todo:
- [ ] some policies are [combined](https://privacyidea.readthedocs.io/en/latest/policies/admin.html#spass-otp-pin-minlength-and-spass-otp-pin-maxlength) in the documentation. This solution does not yet work for these individual cases.

- [ ] Links for Events
- [ ] Links for config page of the SMS Gateway
- [ ] Links for for email templates
