### ISSUE TITLE
script tries to parse the response from the Privacyidea despite the timeout.

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#2958]
Error Message: can not parse response from privacyIDEA.
This error message comes when the script tries to parse the response from the Privacyidea despite the timeout.

**Comment by cornelinux** [comment]
@sepp67 Which script? Can you please provide some more information?

**Comment by plettich** [comment]
This is a FreeRADIUS Plugin issue: https://github.com/privacyidea/FreeRADIUS/issues/58
