### ISSUE TITLE
After upgrade to 3.6.3 users cannot authenticate when they have percent sign in password

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#2985]
User password with a percent sign works on PI 2.23.5 but not on PI 3.6.3.

### Configuration
The Privacyidea radius plugin is not in use in this config.
RHEL 7 with Python 2.7.5.
Centos 7 with Python 2 and 3
Situation appears also with SAML login 

Example of passwords that not works:
123456abc%
%123456abc
123%456abc
123%%456abc
%123%4%5%6abc%

But weirdly, these passwords works:
!@#$^&*()+-;'"abc123
!@#$%^&*()+-;'"abc123

TEST TOKEN function is working for all the passwords
The fail counter did not increase properly, when there is % sign in the password,

**Comment by cornelinux** [comment]
Hi @sepp67 to my unterstanding this is the problem of the calling application, that needs to encode the parameters, right?
So this can be closed as in issue in the server, since it is not.

**Comment by cornelinux** [comment]
@sepp67 We are on 3.7. Can you please check if this is still relevant or if it can be closed?

**Comment by nilsbehlen** [comment]
if this happens again, a new issue can be opened.
