### ISSUE TITLE
Set `max_identifier_length` in SQLAlchemy

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2986]
We need to set `max_identifier_length` in SQLAlchemy to avoid e.g. warning with Oracle:

We’re running PrivacyIDEA 3.6.3 with an httpd web server and Oracle 19c database. Seems every time we perform a database operation such as a user logging in the webUI and browsing around, we get the following error in the httpd error logs

SAWarning: Oracle version () is known to have a maximum identifier length of 128, rather than the historical default of 30. SQLAlchemy 1.4 will use 128 for this database; please set max_identifier_length=128 in create_engine() in order to test the application with this new length, or set to 30 in order to assure that 30 continues to be used. In particular, pay close attention to the behavior of database migrations as dynamically generated names may change. See the section 'Max Identifier Lengths' in the SQLAlchemy Oracle dialect documentation for background.

This is related to #2798

**Comment by cornelinux** [comment]
This can be done via pi.cfg:

~~~~
SQLALCHEMY_ENGINE_OPTIONS = {
    "max_identifier_length": 128
}
~~~~
We might add a note to the documentation or add a default in pi.cfg.

**Comment by NNLemling** [comment]
In the course of this change, we could tackle again #1831.

**Comment by NNLemling** [comment]
After reading a bit into #1831 I'm a little unsure where exactly changes should be made now.

Perhaps the above issue should actually be discussed first before changes are made in many different places.

But maybe I understand something wrong here and changes only have to be made in one specific place.

**Comment by cornelinux** [comment]
#1831 will never be closed ;-)
So I would go for the documentation!
