### ISSUE TITLE
Question on PrivacyIdea Bypass 

### ISSUE THREAD

**Issue by sidantaa** [privacyidea/privacyidea#2989]
Hi!!! I have a question on following case; and I am referring to the windows authentication part and privacy idea credentials providers is installed as a default provider where other local users are not available.
I provided NotokenPin for specific user administrator in Policy where 2FA is bypassed and user is able to login to windows but what will be the solution incase for following:

Case1:

Work From Home Scenario (Privacy idea will not be reachable since it has a private IP); Although i can make it public and give it a try but how can we address the second case below:

Case2:

If user wants to login to his/her PC without network connection; PI will not have any connection. User is completely disconnected from the network.
Note: In AD; although the user is disconnected from network he/she can login until there is cache right?? So, is there any solution in privacy idea too?

**Comment by cornelinux** [comment]
@sidantaa  Please drop your question at https://community.privacyidea.org.
