### ISSUE TITLE
Perl module does not use update FreeRadius  User-Name

### ISSUE THREAD

**Issue by cuph62** [privacyidea/privacyidea#299]
Hello,

In my FreeRadius cfg I have in the authorize section rewrites to suffix the realm for PI,
(user can enter addomain1\user1 or user1@addomain1.net,
In Freeradius 
authorize section I have the following

<pre>
authorize {
        preprocess
        digest
        suffix
        ntdomain
        files
        expiration
        logintime
        #pap
        #postprocess

        switch "%{Realm}" {
        case 'addomain1' {
          update request {
             User-Name := "%{Stripped-User-Name}@addomain1.net"
          }
        }
        case 'addomain2' {
          update request {
             User-Name := "%{Stripped-User-Name}@addomain2.com"
          }
          }
        case 'addomain3' {
          update request {
             User-Name := "%{Stripped-User-Name}@addomain3.org"
          }
        }
        }

        ok
}

authenticate {
        Auth-Type Perl {
        perl
        }

</pre>

However in the perl module 

<pre>
++[files] = ok
++[expiration] = noop
++[logintime] = noop
++switch %{Realm} {
        expand: %{Realm} -> addomain1
++switch %{Realm} {
+++case addomain1 {
++++update request {
        expand: %{Stripped-User-Name}@addomain1.net -> user1@addomain1.net
============================================================
++++} # update request = noop
+++} # case addomain1 = noop
++} # switch %{Realm} = noop
++[ok] = ok
+} # group authorize = ok
Found Auth-Type = Perl
# Executing group from file /etc/freeradius/sites-enabled/privacyidea
+group Perl {
rlm_perl: Config File /etc/privacyidea/rlm_perl.ini found!
rlm_perl: Default URL https://localhost/validate/check
rlm_perl: Looking for config for auth-type Perl
rlm_perl: Auth-Type: Perl
rlm_perl: url: https://localhost/validate/check
rlm_perl: user sent to privacyidea: user1
rlm_perl: realm sent to privacyidea: addomain1
==================================
rlm_perl: resolver sent to privacyidea:
rlm_perl: client sent to privacyidea: 10.231.38.168
rlm_perl: state sent to privacyidea:
rlm_perl: urlparam pass
rlm_perl: urlparam user
rlm_perl: urlparam realm
rlm_perl: urlparam client
rlm_perl: Not verifying SSL certificate!
rlm_perl: privacyIDEA access denied
rlm_perl: return RLM_MODULE_REJECT
rlm_perl: Added pair Stripped-User-Name = user1
rlm_perl: Added pair NAS-IP-Address = 10.231.38.168
rlm_perl: Added pair User-Password = azerty
rlm_perl: Added pair Calling-Station-Id = 01:02:03:04
rlm_perl: Added pair User-Name = user1@addomain1.net
===========================================
rlm_perl: Added pair Realm = addomain1
rlm_perl: Added pair Reply-Message = The user has no tokens assigned
rlm_perl: Added pair Auth-Type = Perl
++[perl] = reject
+} # group Perl = reject
Failed to authenticate the user.

</pre>

Notice:

<pre>
rlm_perl: realm sent to privacyidea: addomain1
==================================
</pre>

while the request was changed:

<pre>
rlm_perl: Added pair User-Name = user1@addomain1.net
</pre>

Perhaps there are other/better options to obtain the same result ?

**Comment by cornelinux** [comment]
So the user logs in as user@domain1.net? 
Do you have different realms in privacyIDEA or only one?

**Comment by cuph62** [comment]
Hi,

user logs in either as:
- addomain1\user 
- or user@addomain1.net

- addomain2\user02
- or user02@addomain2.com

etc...

To enable this, I have configured in freeradius realms for domain1 and domain2 and an update statement to rewrite the username:
     case 'addomain1' {
          update request {
             User-Name := "%{Stripped-User-Name}@addomain1.net"
          }
        }
        case 'addomain2' {
          update request {
             User-Name := "%{Stripped-User-Name}@addomain2.com"
          }

==

I would expect this as request:

rlm_perl: RAD_REQUEST: Stripped-User-Name = user02
rlm_perl: RAD_REQUEST: Realm = addomain2
rlm_perl: RAD_REQUEST: User-Name = user02@addomain2.com
..

bu instead it is this:

rlm_perl: user sent to privacyidea: user02    -----> I would expect "user02@addomain2.com" here

rlm_perl: realm sent to privacyidea: addomain2
...
rlm_perl: Added pair Stripped-User-Name = user1
rlm_perl: Added pair NAS-IP-Address = 10.231.38.168
rlm_perl: Added pair User-Name = user02@addomain2.com

**Comment by cornelinux** [comment]
Well, the privacyIDEA plugin sends the stripped username if it exists. 

https://github.com/privacyidea/FreeRADIUS/blob/master/privacyidea_radius.pm#L278

This behaviour works for other cases, since the FreeRADIUS realm is not always the same as the privacyIDEA realm.

But - as you can see - you may add a "Realm" to the Radius Request,
https://github.com/privacyidea/FreeRADIUS/blob/master/privacyidea_radius.pm#L287

So either use the original User-Name or Stripped-User-Name and Realm.

Kind regards
Cornelius

**Comment by cuph62** [comment]
An enduser can either login with a domain prefix or a dns-suffix, like this -  user02@addomain2.com - addomain2\user02

The Stripped-Username supersedes in your perl-moduleso we always (if we have ntdomain and suffix enabled in freeradius) get: user := "user02"
If I understand correctly, I should define 2 realms in PriviacyIdea  to be able to satisfy both login types ?realm1 = "addomain2" ( for login of addomain2\user02  )realm2 = "addomain2.com" ( for login user02@addomain2.com )
Is that correct ?kind regards,Herman

Date: Fri, 8 Jan 2016 13:01:25 -0800

**Comment by cornelinux** [comment]
But it sounds, as if you only have one user store. The AD "addomain2.com"?

So why so complicated. In this case you only need one realm in privacyIDEA. make it the default realm.
In FreeRADIUS you can strip the realm name - the ntdomain and the FQDN and simply send "user2" to privacyIDEA.

I think for stipping the realm name in FreeRADIUS you do not have to configure anything.

**Comment by cuph62** [comment]
no - not just 1 realm,
we have 5 ADdomains, and because for each domain/realm you can log in with 2 different notations)(user02@addomain2.com and  addomain2\user02 ->  x2 realms ?) in cfr my first example 
        switch "%{Realm}" {
        case 'addomain1' {
          update request {
             User-Name := "%{Stripped-User-Name}@addomain1.net"
          }
        }
        case 'addomain2' {
          update request {
             User-Name := "%{Stripped-User-Name}@addomain2.com"
          }
          }
        case 'addomain3' {
          update request {
             User-Name := "%{Stripped-User-Name}@addomain3.org"
          }
        }
        }
Date: Fri, 8 Jan 2016 14:31:35 -0800

**Comment by cornelinux** [comment]
I do nnot understand what you are telling me.
You have only one realm in privacyIDEA but you have 5 AD Domains.
The one realm in privacyIDEA: has it one AD domain or all 5 AD domains.

What do you want to achieve?

Could it be that you only want one of your 5 AD domains authenticate against privacyidea?

**Comment by cuph62** [comment]
We have 5 ADdomains I also  have defined these 5 domains in PrivacyIdea as realms.

users from domain domain1  can either login as- user01@domain1.netoras- domain1\user01
how to organise this ?
My solution was to rewrite the UserName in FreeRadiusas follows"domain1\user01" ---> update Username to "user01@domain1.net" to 
but rlm_perl from PI apparently did not seem to  use this updated username
(in the meanwhile you showed me that it uses the Stripped-UserName)
While I am now explaining this,I come to the conclusion that I can define both realm"domain1.net" and realm "domain1", both with te same user-resolver.
Is that what you mean ? (cannot test now - will try monday )
Kind regards,Herman

Date: Sat, 9 Jan 2016 02:50:33 -0800

**Comment by cornelinux** [comment]
If you have 5 realms (domain1.com, domain2.com, domain3.com ...) in privacyIDEA, then privacyIDEA expects FreeRADIUS to send the username and the realm to the validation API as parameters "user" and "realm".

Take a look at 
https://github.com/privacyidea/FreeRADIUS/blob/master/privacyidea_radius.pm#L279 and
https://github.com/privacyidea/FreeRADIUS/blob/master/privacyidea_radius.pm#L290.

The privacyidea plugin uses "Stripped-Username" (user) and "Realm" (realm) to send this to the privacyIDEA API.

So "the only" thing you need to do in the FreeRADIUS ulang is to update the RADIUS request like

    domainX\userA -> Stripped-Username=UserA and Realm=domainX.com

and

    userA@domainX.com -> Stripped-Username=UserA and Realm=domainX.com

I would do this in the FreeRADIUS ulang, as you are rather flexible here and this is a "standard FreeRADIUS" task.

Nevertheless this is imho out of scope of the community/open source privacyIDEA system, but rather a FreeRADIUS specific question. From the privacyIDEA standpoint we are clear what needs to be done on the FreeRADIUS side.
Thus I would like to close this issue and take the disucssion somewhere else.

**Comment by cuph62** [comment]
Ok - thanks, this can be closed and perhaps moved to privacyidea-freeradius as informational,

Date: Sat, 9 Jan 2016 09:53:50 -0800
