### ISSUE TITLE
rename "createdb" and "dropdb"

### ISSUE THREAD

**Issue by NNLemling** [privacyidea/privacyidea#2996]
The names `createdb` and `dropdb` are a bit misleading since the actual database must exist before issuing `createdb` and won't be dropped after `dropdb`.

it should be called **create-tables** and **drop-tables**.

_This change proposal was part of #2848._
_Maybe this change should be made as part of #2498._

At least this contains the following tasks:

* [ ] Change pi-manage
* [ ] update documentation
* [ ] update post-scripts in DEB and RPM packages
* [ ] update manual privacyidea-update-script or install scripts

**Comment by cornelinux** [comment]
@plettich @EthemGit Please note the following: renaming the commands would be a breaking API change, so this is s.th. that would require a version 4.0 of privacyIDEA. There are probably an unknown number of installations or custom scripts out there, that use the old naming.
So please proceed as follow: 
We should have both available, the old naming and the new naming. The old naming could also issue a DeprecationWarning and we can remote the old naming in version 4.0  of privacyIDEA.

**Comment by cornelinux** [comment]
Closes by #3310
