### ISSUE TITLE
new token: nitrokey

### ISSUE THREAD

**Issue by privacyidea** [privacyidea/privacyidea#3]
Add crypto stick support. https://www.crypto-stick.com/de
Add support for the OTP part of the crypto stick. Enable the smooth enrollment and OTP 
authentication against privacyIDEA.

(smartcard support? How...?)

**Comment by cornelinux** [comment]
We might want to start with OTP support.

In this case, the admin client should be able to initialize the nitrokey. 
Unfortunately the initialization function is not available in a library, yet. But only in the nitrokey-app.

https://github.com/Nitrokey/nitrokey-app/blob/master/src/device.cpp#L582

Thus we need to extract the code from the nitrokey-app.

**Comment by cornelinux** [comment]
We wait for the issue Nitrokey/nitrokey-app#5 to be resolved.

**Comment by cornelinux** [comment]
Just started with OTP. Nitrokey HOTP support added in privacyideaadm.
