### ISSUE TITLE
install privacyidea on Debian Jessie - troubles if also python-oauthlib installed

### ISSUE THREAD

**Issue by cuph62** [privacyidea/privacyidea#301]
Trying to install privacyidea-apache2 
       apt-get install privacyidea-apache2

which also installs (dependencies):

You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 python-oauthlib : Depends: python-jwt but it is not going to be installed
 python-privacyidea : Depends: python-pyjwt but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

Python packages "python-pywt" and "python-jwt" are different packages in Debian Jessie:

According to debian Jessie:
	Pakket: python-jwt (0.2.1-1+deb8u1)
	Python implementation of JSON Web Token

According to debian Jessie:
	Verwijzigingen voor python-pywt
	Pakket: python-pywt (0.2.2-2)
	Python extension implementing of wavelet transformations

However: in Ubuntu trusty python-pywt contains this package :
ii  python-pyjwt 1.3.0-1trusty1          all                     JSON Web Token implementation in Python

But the Debian-package python-pwt (Jessie)  clashes of course with the python-pyjwt (Trusty- ubuntu) 

To be able to continue, I have changed the dependency of python-oauthlib to
python-pywt and purged python-jwt.

This is informational - we do not need use python-oauthlib, so finally I removed it
( I guess it came installed as depency with another package..)

**Comment by cornelinux** [comment]
Check if we can add "Provides" or "Replaces" in the control file.
https://www.debian.org/doc/debian-policy/ch-controlfields.html
