### ISSUE TITLE
U2F enrolment not working with Chrome

### ISSUE THREAD

**Issue by gregharvey** [privacyidea/privacyidea#3011]
### Top-level intent

Enrol a U2F key with Chrome (well, actually Brave - `[Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit)](https://brave.com/latest/)` - but same difference).

### Steps to reproduce

1. Login to privacyIDEA
2. Enrol token -> U2F
3. Click to enrol
4. You go to the confirmation step but nothing happens! Token doesn't flash.

### Expected outcome

The U2F token flashes so it can be confirmed and enrolment completed.

### Actual outcome

Nada! However **it works fine in Firefox**.

When you load privacyIDEA there is this error in the Chrome console:

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('chrome-extension://kmendfapggjehodndflmmgagdbamhnfd') does not match the recipient window's origin ('null').
(anonymous) @ u2f-api.js?v=20211130T111741:532`

The affected line is:

```javascript
    iframe.contentWindow.postMessage('init', iframeOrigin, [channel.port2]);
```
### Configuration

* **privacyIDEA version**: 3.6
* **Installation method**: PyPI
* **Python version**: 3.7
* **Operating system**: Debian (Buster)
* **Webserver**: Apache2
* **Token database**: MySQL

**Comment by plettich** [comment]
Hi @gregharvey 
there are several issues here:
1. Chrome (and thus Brave) will drop support for U2F (and it seems they already disabled the API): https://www.yubico.com/blog/google-chrome-u2f-api-decommission-what-the-change-means-for-your-users-and-how-to-prepare/
2. You can (re-)enable U2F in Brave via `brave://flags` (enable `Enable the U2F Security Key API` and `Enable a permission prompt for the U2F Security Key API`; this will still show a warning about the dropped support)
3. The WebAuthn/FIDO2 standard "should" support old U2F devices (at least they claim it is backward compatible) however You can not convert an U2F token to a WebAuthn token in privacyIDEA
