### ISSUE TITLE
token-janitor: parsing a timestamp without a timezone fails

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3016]
Using the token-janitor with a date comparison (`--tokeninfo-value-before` or `--tokeninfo-value-after`) fails if the given timestamp does not contain a timezone information.
The `dateutil.parser` does not recognize the given `tzinfo` here:
https://github.com/privacyidea/privacyidea/blob/4ea557be5004feeed957fbee6cd78c1d417cc75f/tools/privacyidea-token-janitor#L179

**Comment by cornelinux** [comment]
Hm, I actually was aware, that we need to provide a timezone at the command line. However, this is a nice extension, that we can skip the tz at the command line.
