### ISSUE TITLE
Image in keyuri

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3019]
We should allow to add an image to the keyuri in the QR Code.
This way, the organization running privacyIDEA can have it's own logo in the authenticator app, if it is supported by the app.

The orignial keyuri spec does not support it.
https://github.com/google/google-authenticator/wiki/Key-Uri-Format

However, it is an extension introduced by FreeOTP:
https://stackoverflow.com/questions/41232168/token-image-in-google-authenticator-or-freeotp

     ...&image=<EncodedURL>

Configured via an `enrollment` policy.

Could be used for HOTP, TOTP and PUSH.

* [ ] Define policy  
  * scope: enrollment
  * action: ....? maybe as a token specific policy? 
  * value: URL to be added to the keyuri
* [ ] Implement policy
* [ ] Decorator during enrollment?
* [ ] Docuemtnation
* [ ] Tests

**Comment by NNLemling** [comment]
Already done in #1228

I tested it again and it works great! :+1:
