### ISSUE TITLE
Inconsistent policy names

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#3024]
The names for policies are somewhat inconsistent. For example in scope=authentication, miscellaneous, there are:
* email_challenge_text
* emailautosend
* passOnNoToken

So there is underscores, camelCase and no convention. Maybe this could be unified. From the first glance, it seems that underscore is used the most.

**Comment by cornelinux** [comment]
In a perfect world you are totally right.
The policy names are keywords. So if we would change this, we would have to write manual migration scripts for all configured policies.
I take this as a low priority.
