### ISSUE TITLE
Allow to explicitly select firebase configuration during the actual enrollment

### ISSUE THREAD

**Issue by skinkie** [privacyidea/privacyidea#3029]
**Is your feature request related to a problem? Please describe.**
When developing I have *your* app on my phone, and my app which has the 'debug' suffix and requires a specific firebase configuration. I would like to enroll push tokens to that app while retaining the default configuration.

**Describe the solution you'd like**
I would like to request the ability to set the enrollment policy (from a list of policies) explicitly overriding the default selection order.

**Describe alternatives you've considered**
It should be possible to define a second realm, and create conditional policies based on realm. That basically requires more setup for ad-hoc tests. I have also considered renaming the debug app.

**Additional context**
Developers, developers, developers...

**Comment by cornelinux** [comment]
I took the liberty to rename the subject of your issue. To my understanding in your case it is about using different firebase configurations (which are actually currently configured in policies, but it is not about selecting generic policies).

FYI: We are about to remove the firebase configuration from the privacyIDEA configuration (or at least the UI).
We will very likely change the App in regards to the push token this way, that the App has a fixed firebase configurtion. Having a dynamic firebase config works somehow on android but causes a lot of problems on iOS.

Thus, configuring firebase will most probably vanish from the UI in the long run and probably move to somehow static configuration files.
