### ISSUE TITLE
proposal: simplify Selfservice for Google enrollment

### ISSUE THREAD

**Issue by cuph62** [privacyidea/privacyidea#303]
The selfservice for a Google TOTP is too complicated I think.
An enduser should be able to just to press a button for a Google Auth token
instead os selecting several technical options:

![pi_googleauthselfservice](https://cloud.githubusercontent.com/assets/13996396/12199978/50471b48-b61c-11e5-8ffb-1654a379de5c.png)

**Comment by cornelinux** [comment]
We should create a policy. This could be in scope enrollment or webui.
It could also a token dependent policy (TOTP, HOTP) in the scope=user.
This policy can define, which settings are allowed for the user:

L = length
T = timestep
H = hash
P = PIN

The action value of the policy can be a combination of LTHP.

**Comment by cornelinux** [comment]
We use the policy scope=user, action=totp_hashlib.
If the totp_hash lib action is set, the drop down box is not displayed.

This way we can hide timestep, otplen and hashlib for TOTP and
otplen and hashlib for HOTP.
