### ISSUE TITLE
Polling or the WebAutn/U2f login flow is not cancelled in WebUI when a different token was used

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3039]
During the WebUI login (`login_mode == privacyIDEA`) when the user has an out-of-band token and/or a WebAuthn/U2F token, the login flow differs. In case of an out-of-band token (Push) the browser polls the privacyIDEA server whether the challenge has been answered. In case of WebAuthn/U2F the browser asks the token for the user-presence.
If the user has multiple tokens and a different token is use to log in, the polling does not stop. Similarly the WebAuthn/U2F request to the HW token is not cancelled.
The polling could be stopped i.e. when the `response` state is left in the UI:
https://github.com/privacyidea/privacyidea/blob/b31c42d5d9ea776196efd3ded9c90234a1557238/privacyidea/static/components/login/states/states.js#L42

**Comment by nilsbehlen** [comment]
this has been fixed a while back (im not searching for the commit tho).
Polling is stopped uniformly on either error or login, independent of token type.
