### ISSUE TITLE
Add preferred client_mode

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3044]
The Challenge in challenge response can contain multiple possible authentications with different token types which result in different [client modes](https://privacyidea.readthedocs.io/en/latest/tokens/authentication_modes.html). [Possible values are interactive, webauthn, u2f, poll](https://github.com/privacyidea/privacyidea/blob/2b075edc8ff0f4f481de4c36411dc648f114ce01/privacyidea/lib/tokenclass.py#L137).

The response should contain an information, which mode should be preferred by a client/plugin.
I.e. a user could trigger challenge response for an `interactive` token and a `poll` token.

The response should contain this information like this:

~~~~json
{
    "detail": {
        "preferred_client_mode": "webauthn",
        "multi_challenge": [
            {
                "client_mode": "webauthn",
                "image": "",
                "message": "Please confirm with your WebAuthn token (Generic WebAuthn Token)",
                "serial": "WAN00023132",
                "transaction_id": "09250011178417540855",
                "type": "webauthn"
            }
        ],
~~~~

The multi_challenge section contains a list of challenge dictionaries.https://github.com/privacyidea/privacyidea/blob/8eeaa9d44999a412f4bc598b2fe54c6d552e6d46/privacyidea/lib/tokenclass.py#L137
So we should put the `preferred_client_mode` in the detail top-level. 
It can contain one value. It can contain the same values like the `client_mode`.

# Backend Implementation

Think about it - it actually does not change the authentication from a server perspective but only how the client/plugin behaves. Should we add a new policy scope for this?

~~* [ ] check if there are other policy actions, that only tell the client what to do.~~

* scope: authentication
* action: preferred_client_mode: type: str
 (https://github.com/privacyidea/privacyidea/blob/8eeaa9d44999a412f4bc598b2fe54c6d552e6d46/privacyidea/lib/tokenclass.py#L137) 

The string can contain a whitespace separated list like "interactive webauthn". The admin needs to write these values manually.
If no policy for the client_mode is set, we use the default `interactive`.
If no `interactive` is contained in multi_challenge, then we do default to `webauthn`.
If not `webauthn` is contained, then we default to `poll`.

@nilsbehlen : Do you always want the preferred client mode.

* [x] Implement the new return value `preferred_client_mode` in the response
* [x] Implement the order of default
* [x] add policy
* [x] test policy
* [x] documentation

**Comment by nilsbehlen** [comment]
We will implement this to override the setting `preferred_token_type` set in each plugin. Eventually, we can remove this in the plugins.

**Comment by cornelinux** [comment]
If in any case the client mode can not be found, the preferred client mode should return the all-time-default `interactive`.
