### ISSUE TITLE
verify-enrollment and 2step-enrollment does not work at the same time

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3045]
In privacyIDEA 3.7 the verify-enrollment was introduced.

The verify-enrollment and the 2step-enrollment does not work at the same time (at least in the tokenwizard).
This is probably an HTML javascript issue with displaying all components.

If verify-enrollment and 2step-enrollment is active at the same time

1. the QR codes is not displayed
2. the entry field for the 2step (client component) is not displayed.

**Comment by plettich** [comment]
Duplicate of #3170
