### ISSUE TITLE
Allow the HttpSMSProvider to send the data as a JSON string

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3056]
Some SMS Provider provide an API which only accepts the content type `application/json`.
Before sending the request, the data can be transformed into a JSON string here:
https://github.com/privacyidea/privacyidea/blob/f770837c683a32b17ae37e398c6319a62f6d89f2/privacyidea/lib/smsprovider/HttpSMSProvider.py#L145

**Comment by cornelinux** [comment]
@jona-samuel Please check, if we also need to set the content-type in `requests`.

**Comment by plettich** [comment]
@jona-samuel is this fixed with #3236?

**Comment by plettich** [comment]
This is fixed with #3251
