### ISSUE TITLE
SMS Authenticate error: AttributeError("'str' object has no attribute 'get'")

### ISSUE THREAD

**Issue by ntaheij** [privacyidea/privacyidea#3074]
### Top-level intent

Authenticate via Firebase SMS.

### Steps to reproduce

1. Use the /validate/check endpoint with only the SMS provider enabled.
2. See response.

### Expected outcome

Sends SMS via Firebase.

### Actual outcome

No response, API gives error.

### Configuration

* **privacyIDEA version**: 3.6.3
* **Installation method**: Ubuntu packages
* **Python version**: 3.8.10
* **Operating system**: Ubuntu 20.04
* **Token database**: MySQL

### Log file
```
[2022-03-30 19:00:24,581][91325][139905556334464][WARNING][privacyidea.lib.tokens.smstoken:354] The PIN was correct, but the SMS could not be sent: AttributeError("'str' object has no attribute 'get'")
```

**Comment by ntaheij** [comment]
Issue has not been fixed in a recent version.

**Comment by plettich** [comment]
Hi @ntaheij 
the FirebaseProvider is only meant to send push notifications to the smartphone app via FCM (Google Firebase). I don't think it can be used to send SMS for an SMS-Token.

**Comment by ntaheij** [comment]
Hi.

Is there any provider available for SMS? I don't really see any documentation on it.

**Comment by plettich** [comment]
> Is there any provider available for SMS? I don't really see any documentation on it.

privacyIDEA does not send SMS itself, it needs an external service or hardware for that. Depending on the configuration of the service/hardware there are several "providers" to connect to these services/hardware:
https://privacyidea.readthedocs.io/en/latest/configuration/sms_gateway_config.html

**Comment by ntaheij** [comment]
Thank you!
