### ISSUE TITLE
How Change Languages

### ISSUE THREAD

**Issue by michaely0418** [privacyidea/privacyidea#3076]
i modified 
/opt/privacyidea/lib/python3.8/site-packages/privacyidea/app.py
![image](https://user-images.githubusercontent.com/46963951/161051848-24030262-e35a-4a0d-9d62-edec00dc1936.png)
/opt/privacyidea/lib/python3.8/site-packages/privacyidea/webui/login.py
![image](https://user-images.githubusercontent.com/46963951/161051922-2f5fd029-675f-446e-98af-ad6342b6bdcb.png)
but I have also tried with several browsers, in all the language settings are zh_Hant and in all of them the pages are shown in English

**Comment by cornelinux** [comment]
I think you should put "zh_Hans/t" in front of "en". Otherwise your browser could be fine with "en".
