### ISSUE TITLE
Add PUSH Token Server - Client Binding

### ISSUE THREAD

**Issue by Happy2C0de** [privacyidea/privacyidea#3078]
First of all, **thanks a lot for this great project!!!** privacyIDEA is simple, stable and absolutely powerful. I really appreciate your work, it's just great. 👍 

**Is your feature request related to a problem? Please describe.**
privacyIDEA version: v3.6.3 (analysed master code as well)

We are experimenting with PUSH tokens using privacyIDEA and everything works. One addition that we are missing is the binding for a given push token challenge between the server and the client (smartphone).

At the moment, the PUSH notification contains the following info:

```json
{
    "nonce": challenge,
    "question": message_on_mobile,
    "serial": serial,
    "title": title,
    "sslverify": sslverify,
    "url": registration_url
}
```
, as well as a signature generated from the values of the above information. This ensures the integrity. See [pushtoken.py#L193](https://github.com/privacyidea/privacyidea/blob/a66bb88c50e8a55118242dac5f38afab251c5164/privacyidea/lib/tokens/pushtoken.py#L193)

The `/validate/triggerchallenge` endpoint which triggers the push token contains a `transaction_id` but it doesn't contain the `nonce` challenge, even though it gets stored in the Challenge table of the database, see [pushtoken.py#L856](https://github.com/privacyidea/privacyidea/blob/a66bb88c50e8a55118242dac5f38afab251c5164/privacyidea/lib/tokens/pushtoken.py#L856))

The problem that we are facing is the fact that we cannot display a verification code to the enduser for security reasons. We would like to show a code (e.g. 6-digit long) on a web page that equals a code that is displayed on the smartphone when verifying the authentication request. This should increase the barrier for just verifying a certain push notification.

Afaik, at the moment it is not possible to obtain a unique code which is bound to the challenge on both sides, server and smartphone. Am I right?

**Describe the solution you'd like**
I see two low hanging fruits for implementing this feature:
1. Add the `transaction_id` to the push notification content. This allows to display the transaction_id (or a part of it) to the user on the smartphone as well as on the web UI. Drawback of this approach is that the signature needs to change because you add an information to the push notification content. Today, all information is part of the signature hash.
2. Add the nonce to the `/validate/polltransaction` endpoint response. This would have the similar link between the server and the smartphone.

**Describe alternatives you've considered**
I thought of using the nonce and the transaction_id directly. But, I didn't find a way to obtain the information on both sides in the current master code.

**Additional context**
None

What is your viewpoint onto this request?

**Comment by nilsbehlen** [comment]
@cornelinux is it possible to have the transaction_id as part of the message? With the serial or username this can be done via <u> or something in the policies.

**Comment by cornelinux** [comment]
@Happy2C0de thank you for your request and your thoughts and detailed description.
However, it is not really clear to us, what problem you actually want to solve?
Could you maybe describe, where you think that there is a problem or an attack vector in the push mechanism?

My assumption is, that you have several web applications that are connected to the same privacyIDEA server and that you want the user to check for which login to which web application he currently received the push notification?
Could you please elaborate on this.

@nilsbehlen nearly everything is possible. But we should not change the app- and push-menachsim with each release but rather go for some stability and enter calmer waters ;-)

**Comment by Happy2C0de** [comment]
Thanks @cornelinux and @nilsbehlen for your feedback!

Exactly, your assumption is correct. We have a use case where you can log in over multiple devices or sessions onto the same system using the same privacyIDEA server as its MFA flow.
Another idea would be to have a single flow where you only have to type your username and then you can authenticate yourself by using the PUSH notification. This is also 2FA because you own the device/token and you bring your biometrics, for example.
Yes, it goes into the direction of the MS number matching, whereby there are various approaches in commercial applications. Some request to type 2-digits (e.g. MS) others only display the code and the user needs to check if the code presented is the same as the one shown in the push notification.

That means you can theoretically obtain a push notification from various sources. I would like to have a unique identifier of the challenge that is present on both sides, the server and the smartphone. This would allow us to display or request an entry an X-digit number that "binds" the session from the browser to the smartphone client. A user will be instructed to only accept a request, if the number match. As far as I know, there is no such identifier queryable on both sides.

Actually, we would like to prevent a user to just accidentally verify a request. The attack vector is exactly this. If an attacker obtained username/password and can trigger push notifications on various systems, we would like to prevent the user from accidentally verifying a push notification what would allow the attacker to gain access onto a certain system.

Thanks for your feedback :)

**Comment by nilsbehlen** [comment]
adding the transaction_id to the message does not change the push mechanism or anything. One could also add the user agent of the request that triggered the push token to the message that is delivered to the phone so the user can verify the service that is trying to authenticate.
Having numbers displayed on both sides, on the other hand, would require code to be added.

**Comment by cornelinux** [comment]
@Happy2C0de So you want the push message to contain the information, **where** the user is trying to authenticate?
You can already do this with different policies for the push text. 

On the other hand we do not plan to implemetn s.th. like the microsoft number matching - I think it is solving a different issue with a wrong solution.

**Comment by Happy2C0de** [comment]
@cornelinux 
No, not from where but from which session. How can a user be assured that a notification is bound to the session he or she just authenticated with e.g. username/password. The second factor would be the push notification. How can the user assure that the notification comes from the given session?

Login procedure:
1. Browser: Access web service via browser
2. Browser: Enter username/password on the login screen
3. Browser: Service triggers push challenge of privacyIDEA to initialise the second factor flow
4. Mobile App: User verifies the push token challenge.

How can a user in step 4 be sure that the challenge comes from the same access request as in step 2?

**Comment by Happy2C0de** [comment]
@cornelinux 
It might be helpful to read this article, and specifically the section `Phishing Pushed-Based MFA`, https://www.linkedin.com/pulse/why-majority-our-mfa-so-phishable-roger-grimes. 

> Turns out end users frequently approve logins that they are not initiating. It is a very common problem in an environment where pushed-based authentication has been implemented. Users are approving malicious logins…many times when the user is not anywhere near their computer.

This is what we would like to address using an appropriate solution.

**Comment by cornelinux** [comment]
> 
Thank you for the four steps. Now I understand your concern.

**Comment by Happy2C0de** [comment]
@cornelinux 
I just found a solution for Variant B). It's not that obvious but it should work.

The firebase message contains the challenge in the `nonce` property. This can be queried using `/token/challenges/{serial}`, where the `challenge` property contains the same value as the nonce.

I think, this way we should be able to have Variant B) in place. 
What do you think?

**Comment by cornelinux** [comment]
@nilsbehlen Lets discuss in the next client meeting if we take some action of close this.
This sounds like the context of MFA Fatigue.

This is connected to #3632
