### ISSUE TITLE
The client ip is not resolved correctly when multiple proxies are involved.

### ISSUE THREAD

**Issue by smoebody** [privacyidea/privacyidea#3080]
### Top-level intent

The client ip is not resolved correctly when multiple proxies are involved.

The Header `X-Forwarded-For` can hold multiple ip addresses if multiple proxies are involved. In my case the Header looks like this:
```
X-Forwarded-For: 192.168.7.6, 10.1.18.12, 10.0.1.6, 10.0.6.171
```
The IP of the Service is `10.12.2.2`

### Steps to reproduce

1. build a setup at least two proxies to the server
2. add the two proxies ip address to the *OverrideAuthorizationClient* form in the settings
3. observe the clients ip in audit-log

### Expected outcome

The real client ip is the first ip from `X-Forwarded-For` header: `192.168.7.6`. I expect to see this ip as client ip in the audit-log, when i add the subnet 10.0.0.0/8 to the *OverrideAuthorizationClient*.

### Actual outcome

The audit log shows the ip `10.0.6.171` as client-ip, regardless whether i add that ip or the subnet to the *OverrideAuthorizationClient*.

### Configuration

* **privacyIDEA version**: 3.6
* **Installation method**: PyPI
* **Python version**: 3.9
* **Operating system**: alpine linux
* **Webserver**: uwsgi/traefik/nginx
* **Token database**: PostgreSQL

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
```
...
DEBUG:privacyidea.lib.config:Entering get_from_config with arguments ('OverrideAuthorizationClient',) and keywords {}
DEBUG:privacyidea.lib.config:Exiting get_from_config with result 10.0.0.0/8
DEBUG:privacyidea.lib.utils:Determining the mapped IP from [IPAddress('10.12.2.5'), IPAddress('10.0.6.171'), IPAddress('10.0.1.6'), IPAddress('10.1.18.12'), IPAddress('192.168.7.6')] given the proxy settings '10.0.0.0/8' ...
DEBUG:privacyidea.lib.utils:Proxy path: (IPNetwork('10.0.0.0/8'), IPNetwork('0.0.0.0/0'))
DEBUG:privacyidea.lib.utils:... setting new candidate for client IP: IPAddress('10.0.6.171')
DEBUG:privacyidea.lib.utils:Determined mapped client IP: IPAddress('10.0.6.171')
...
```

**Comment by cornelinux** [comment]
Please try to configure it this way in Overwrite Client:

10.0.6.171>10.0.1.6>10.1.18.12>192.168.7.0/24

Read here: https://privacyidea.readthedocs.io/en/latest/configuration/system_config.html?highlight=override%20client#override-authorization-client

I assume it is a configuration issue.

 192.168.7.6, 10.1.18.12, 10.0.1.6, 10.0.6.171

**Comment by cornelinux** [comment]
"The IP of the Service is 10.12.2.2"

This is not clear. If this is the direct client to privacyIDEA, you also need to add this in the chain.
