### ISSUE TITLE
make Firebase only depend on service account

### ISSUE THREAD

**Issue by jacekwiczkowski** [privacyidea/privacyidea#3081]
With the new app version, the way Firebase works will be changed.

The old way was, that users had to create their own Firebase instance and specify values, so a connection could be established.

With the new app version, there will only be one Firebase instance, and users will only need to specify their service account

**Comment by cornelinux** [comment]
I am rethinking about this and I am wonderung if we should keep the existing FireBaseProvider intact and add another one, a NetKnightsFirebaseProvider, inherited from the Generic Firebase Provider. This way users could run privacyIDEA server with the generic FirebaseProvider and a fork of the smartphone app.
@jacekwiczkowski We will implement this nicely in our server team. I keep your PR open as a guidance.
