### ISSUE TITLE
Bad error handling in /ttype/<type> endpoint

### ISSUE THREAD

**Issue by Happy2C0de** [privacyidea/privacyidea#3090]
We observed a bad error handling when requesting the `/ttype/<type>` endpoint.

In specific, we faced the following error:
```
[ERROR][privacyidea.app:1892] Exception on /ttype/push"}. [GET]
...
AttributeError: 'NoneType' object has no attribute 'api_endpoint'
```
Actually, we could fix the problem but it would be nice to fix this upstream right away.

### Top-level intent

Access the `/ttype/<type>` endpoint.

### Steps to reproduce

1. Query `/ttype/test` endpoint
2. There will be a NoneType error in the logs.

### Expected outcome

Proper error handling

### Actual outcome

NoneType exception.

### Configuration

* **privacyIDEA version**: v3.6.3
* **Installation method**: (from Ubuntu packages, github, PyPI, ...)
* **Python version**: 3
* **Operating system**: linux
* **Webserver**: apache

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by Happy2C0de** [comment]
@cornelinux 
I found a bug and propose a possible fix for it.

**Comment by cornelinux** [comment]
Hm, I actually wouldn't call it a bug. Since you are issuing wrong parameters to the API.

**Comment by Happy2C0de** [comment]
Yeah, I agree 👍
