### ISSUE TITLE
Auth Policy "passthru" , but rejected by Radius with  "no token assigned"

### ISSUE THREAD

**Issue by cuph62** [privacyidea/privacyidea#310]
Hello,

We would like to allow to pass users that have no token yet when then authenticate with their AD-pwd:

Therefore I am having following policies:

| name            | scope          | action                                                                                                                                                          |
|-----------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| auth2_challenge | authentication | { "passthru": true, "challenge_response": "PW HMAC TOTP", "otppin": "userstore" }                                                                               |
| enroll_google   | enrollment     | { "max_token_per_user": "1", "tokenlabel": "company_<u>@<r>" }                                                                                                  |
| self1_srvc      | user           | { "totp_hashlib": "sha1", "totp_timestep": "30", "auditlog": true, "totp_otplen": "6", "enrollTOTP": true, "totp_force_server_generate": true, "delete": true } |

or

![policy1](https://cloud.githubusercontent.com/assets/13996396/12234331/93ce2c9c-b86c-11e5-92f4-3ead01c4439c.jpg)

However when I try to authenticate a user without token via Radius with the uid/pwd of ADdomain, I am 
getting "reject with msg "no token assigned" :

rlm_perl: privacyIDEA access denied
rlm_perl: return RLM_MODULE_REJECT
[..]

rlm_perl: Added pair Reply-Message = The user has no tokens assigned
rlm_perl: Added pair Auth-Type = Perl
++[perl] = reject
+} # group Perl = reject
Failed to authenticate the user.
Login incorrect: [user@domain.com] (from client wshecu port 0 cli 01:02:03:04)
Sending Access-Reject of id 16 to 10.231.38.168 port 7998
        Reply-Message = "The user has no tokens assigned"

**Comment by cornelinux** [comment]
check the client specs and the realms in your policies!
Also take a look at the audit log!
