### ISSUE TITLE
WEBUI Login with TOTP HOTP or REGISTRATION Token don't work anymore after Upgrade to 3.7

### ISSUE THREAD

**Issue by BaraCoding** [privacyidea/privacyidea#3109]
Hi, 

after an Upgrade from PrivacyIDEA 3.6 to 3.7 the Login on the PrivacyIDEA WebUI don't work anymore with Token from typ TOTP, HOTP and REGISTRATION. There is no field to enter the Token value. Only webauth and push works. 

There were no changes made on the policiys. Only the Update were made. 

Policies:

Name: activate-2FA-for-User-on-WebUI
Scope: webui
Priority: 1
miscellaneous -> login_mode -> privacyIDEA

Name: login-web-ui
Scope: authentication
Priority: 2
miscellaneous -> challenge_response -> TOTP HOTP REGISTRATION
miscellaneous -> otppin -> userstore

Is there eventual a new policy value that we must use for these purpose?

Mfg

**Comment by plettich** [comment]
Hi @BaraCoding
we broke this while adding support for login with Push-token in #2893.
This is fixed in #3082 and will be shipped with v3.7.1 (which is due in a week or so).
