### ISSUE TITLE
International chars (unicode) in pwd always fail when authenticating via FreeRadius

### ISSUE THREAD

**Issue by cuph62** [privacyidea/privacyidea#312]
Hello,

As soon as I have international chars in password, access via Radius is refused:
(Test token on webUI works fine)

in this example pwd is "Azértèçà0"

(1) When using "passthru" I am getting this:
rlm_perl: privacyIDEA access denied
rlm_perl: return RLM_MODULE_REJECT
..
rlm_perl: Added pair User-Password = Az\351rt\350\347\3400194624
rlm_perl: Added pair Stripped-User-Name = user01
rlm_perl: Added pair User-Name = user01@addomain01.net
..
rlm_perl: Added pair Reply-Message = The user has no tokens assigned

(2) When using a TOTP token I am getting this:
rlm_perl: return RLM_MODULE_REJECT
..
rlm_perl: Added pair User-Password = Az\351rt\350\347\3400194624
rlm_perl: Added pair Stripped-User-Name = user01
rlm_perl: Added pair User-Name = user01@addomain01.net
..
rlm_perl: Added pair Reply-Message = wrong otp pin

(Perhaps this should be posted in privacyidea-freeradius,)

kind regards,
Herman

**Comment by cornelinux** [comment]
Welcome to the funny world of encoding!

Try run 

    echo "User-Name=user01@addomain01.net, Password=Azértèçà0194624" | radclient -s 127.0.0.1 auth testing123

and it will presumably work. At least it does for me.

So the question is what happens between your RADIUS client and the FreeRADIUS.
