### ISSUE TITLE
Translate config option in PSKC import

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3129]
When importing PSKC files the admin can choose how to handle erros.

This has to be translateable.

https://github.com/privacyidea/privacyidea/blob/835aa84ba8e017c0460900a0094f57950c641a81/privacyidea/static/components/token/views/token.import.html#L90

**Comment by NNLemling** [comment]
fixed in c628bdd519ddad638d66c248691a948d452b9afc.
