### ISSUE TITLE
Problem with HttpSMSProvider

### ISSUE THREAD

**Issue by salvorapi** [privacyidea/privacyidea#313]
Hi,

I have found a problem with HttpSMSProvider and Ozeki HTTP Gateway. The problem is that when I try to make a GET call to HTTP Gateway parameters are send meanwhile in  query string and in form (I think for POST method).

**Comment by cornelinux** [comment]
Does this result in the SMS being not sent?

Obviously this is the interesting line of code:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/smsprovider/HttpSMSProvider.py#L85

Check if requests.get realy honours "params" and "data".

**Comment by salvorapi** [comment]
Yes,
because Ozeki goes in a strange error (username & password not valid).

The interesting line of code is this: 

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/smsprovider/HttpSMSProvider.py#L93

If I write this code:
```
r = requestor(url, params=parameter,
                      data={},
                      verify=ssl_verify,
                      auth=basic_auth,
                      proxies=proxies)
```


the SMS is sent.

I forgot to say that there is a problem on _check_success function.
If you check at line 132 there is a condition that is not coerent with documention. 

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/smsprovider/HttpSMSProvider.py#L132

For RETURN_SUCCESS documentation say:

_If the text of RETURN_SUCCESS is found in the HTTP response of the gateway privacyIDEA assumes that the SMS was sent successfully._

But the code don't do a contains check but a simple check of the RETURN_SUCCESS text.

If I write this code:
```
if succes in reply:
```

the SMS is sent.

**Comment by cornelinux** [comment]
Thanks for the first correction. I will implement this and you may please check it later.

The 2nd thing with RETURN_SUCCESS - you are half right. The check in line 132 is acutally a "startswith" check. This is, how it was usually used, since most providers return something like:

"OK <email>"

If the provider would return "<emalil> OK" this would be bad.

What does Ozeki return in the body?

**Comment by salvorapi** [comment]
Ozeki return a XML response like this:
```XML
<?xml version="1.0" encoding="utf-8"?>
<response>
<action>sendmessage</action>
<data>
<acceptreport>
<statuscode>0</statuscode>
<statusmessage>Message accepted for delivery</statusmessage>
<messageid>83a130e7-4efb-48ee-a1e8-257fdf217f24</messageid>
<originator>http2sms</originator>
<recipient>0000000000(mobile phone number)</recipient>
<messagetype>SMS:TEXT</messagetype>
<messagedata>
Text of message
</messagedata>
</acceptreport>
</data>
</response>
```

**Comment by cornelinux** [comment]
So in your case you would either check for the substring
"message accepted for delivery" 
or for <statuscode>0</statuscode>

Could be a simple substring check as in the docs or a regular expression.

I think I go with the substring ;-)
This should be ok?

**Comment by salvorapi** [comment]
I think it's fine.

Thank you.

**Comment by cornelinux** [comment]
Thank you!
