### ISSUE TITLE
When using a sqlresolver it would be useful to be able to specify a schema

### ISSUE THREAD

**Issue by cmbyrne** [privacyidea/privacyidea#3130]
SQLSoup looks for the table in the default schema. There is an optional parameter in the entity called schema.  The table I need for user information is not in the default schema. My organization has multiple schemas for different data usaes.  An additional field for schema when creating the sqlResolver or parsing the table name <schema>.<tablename> would be useful.

**Comment by cornelinux** [comment]
@cmbyrne Thank you for your request. You could push this by
* adding a link to the docs and the parameter
* adding a link to code
* giving a hint about a test environment 
The more information you provide, the less effort it is for the developer to add this and the more likely it is, that it will happen. Thanks.

**Comment by cmbyrne** [comment]
@cornelinux ,
I would like  to provide a link to the docs, but they are no longer available on readthedocs.io or bitbucket. 

- That being said the method signature is:

> entity(attr, schema=None)
> Return the named entity from this [SqlSoup](https://www.codepowered.com/manuals/SQLAlchemy-0.6.9-doc/html/orm/extensions/sqlsoup.html#sqlalchemy.ext.sqlsoup.SqlSoup), or create if not present.
> 
> For more generalized mapping, see [map_to()](https://www.codepowered.com/manuals/SQLAlchemy-0.6.9-doc/html/orm/extensions/sqlsoup.html#sqlalchemy.ext.sqlsoup.SqlSoup.map_to).

The code in two places in [SQLIdResolver](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/SQLIdResolver.py) would need to change
- Line 553  in  def loadConfig(self, config):
        self.TABLE = self.db.entity(self.table)
- Line 664 in  def testconnection(cls, param):
       TABLE = db.entity(param.get("Table"))
The simplest change would be tokenize the table parameter on the '.' character, since most/all databases follow the dot notation of _schema.table_ when writing sql. If the split returns two items then the first is the schema and the table is the second, for one item set the schema to None or don't ad that parameter, otherwise report an error.
The test environment would be having the user table in a non-default schema.  Most databases default to public or username. So creating an additional schema  and table would be needed.

**Comment by cornelinux** [comment]
@cmbyrne 
Can you give an example or suggestion how you would like to configure (an thus save) the schema in the resolver configuration?

**Comment by plettich** [comment]
Fixed with #4007
