### ISSUE TITLE
cannot register Apple devices for WebAuthn (Touch ID or Face ID)

### ISSUE THREAD

**Issue by melanger** [privacyidea/privacyidea#3136]
### Top-level intent

What did you try to achieve?

Register iPhone as a WebAuthn token with Touch ID.

### Steps to reproduce

1. Add WebAuthn token
2. use Touch ID

### Expected outcome

Token should be registered.

### Actual outcome

Server error happens, because apple attestation format is not listed in privacyIDEA source code.

### Configuration

* **privacyIDEA version**: 3.7
* **Installation method**: pip
* **Python version**: 3.9
* **Operating system**: does not matter
* **Webserver**: does not matter
* **Token database**: does not matter

webauthn attestation policy set to "direct" (or "indirect")

### Log file

```
Exception on /token/init [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/privacyidea/lib/tokens/webauthn.py", line 1303, in verify
    raise RegistrationRejectedException('Unable to verify attestation statement format.')
privacyidea.lib.tokens.webauthn.RegistrationRejectedException: Unable to verify attestation statement format.
```

**Comment by cornelinux** [comment]
Lately I successfully registered an iPhone with faceID.
I am not sure, if this error occurs due to the webauthn attestation policy. You used "direct"?

@melanger  Please provide your webauthn policy settings.

I know, that we did not implement all possible scenarios of Webauthn (which is I guess technically not possible)
I am changing this to `enhancement`.

**Comment by melanger** [comment]
Yes, as noted above, my attestation policy is direct. It would probably have the same result with indirect.

The fix is to add the attestation type to "registered" types, at least. I have already created a PR for that.

It would be great to support at least the attestation formats defined in the WebAuthn standard (v2 or v3). For example the py_webauthn library implemented all of them including apple, check it out.
