### ISSUE TITLE
Improve privacyidea-diag script for use with nginx

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3146]
Currently the `privacyidea-diag` script only gathers configuration and log file for the apache webserver. We should enable collecting data for nginx as well (and avoid sputtering out errors due to missing apache files).
We should also check if the script is running as `root` to avoid complications and missing files.

Some more ideas for the diag-script:
- [x] add nginx logs if available
- [x] check if script is run as root
- [x] add smtp/privacyIDEA/RADIUS server configuration to the diagnostics
- [x] check for external logging config (and avoid error when the PI logfile doesn't exist)
- [x] check if apache logs exist before appending them
- [x] create different files for system config and privacyIDEA config

**Comment by cornelinux** [comment]
No, I dont't think we should collect for nginx.

**Comment by plettich** [comment]
I'll reopen this issue since there are some more things to fix/update
