### ISSUE TITLE
OTP sent over email or sms remains valid forever

### ISSUE THREAD

**Issue by sagarshah1983** [privacyidea/privacyidea#3161]
### Top-level intent
I am trying to test email OTP expiry with HTTP Resolver in the realm. My understanding is OTP shall be expiring based on Email token OTP validity set up.

### Steps to reproduce

1. Configure SMTP server
2. Set Email Token with validity as 60 seconds
3. Create Realm and set up Http Resolver linking to our API returning user’s email
4. Enroll a token using admin login on web UI and assign to a user
5. Try “Test Token” for the serial token. This triggers an email with OTP
6. Set OTP value and click “Test OTP only” after an hour

### Expected outcome
Test OTP flow should have failed as that was invoked after an hour

### Actual outcome
Test OTP validates the token successfully

### Configuration

* **privacyIDEA version**: master branch (3.7)
* **Installation method**: GitHub Repo setup
* **Python version**:2.7
* **Operating system**: macOS Big Sur
* **Webserver**: 
* **Token database**: Sqlite

### Log file
Log file attached: 
[PI-OTP-EXPIRY.log](https://github.com/privacyidea/privacyidea/files/8781729/PI-OTP-EXPIRY.log)

**Comment by sagarshah1983** [comment]
@cornelinux - This bug needs to be marked is obsolete/incorrect. I realized that I was following wrong method and hitting wrong API to validate OTP. With challenge flow I was able to test it, correctly.

**Comment by cornelinux** [comment]
Works as designed
