### ISSUE TITLE
Multiple calls to the endpoint defined in HTTP Resolver on "Test Token" for email token

### ISSUE THREAD

**Issue by sagarshah1983** [privacyidea/privacyidea#3162]
### Top-level intent
I am trying to test email OTP flow with HTTP Resolver in a realm. 
My understanding is with "Test Token" flow it will find the user by calling the endpoint (defined in HTTP Resolver) once.

### Steps to reproduce

1. Configure SMTP server
2. Create Realm and set up Http Resolver linking to an API returning user’s email (I am using MockServer tool to expose an API and then generate the response with user information, phone, email, etc.)
3. Enroll a token using admin login on web UI and assign to a user
4. Try “Test Token” for the serial token. This triggers an email with OTP

### Expected outcome
Endpoint defined in http resolve should be hit once

### Actual outcome
Endpoint defined in http resolve is being hit multiple times. I noticed it 5 times (from the mockserver logs)

### Configuration

* **privacyIDEA version**: master branch (3.7)
* **Installation method**: GitHub Repo setup
* **Python version**: 2.7
* **Operating system**: macOS Big Sur
* **Webserver**:
* **Token database**: Sqlite

### Log file
Log file attached:
[PI-HTTP-RESOLVER-HITS.log](https://github.com/privacyidea/privacyidea/files/8782030/PI-HTTP-RESOLVER-HITS.log)

**Comment by cornelinux** [comment]
Resolving of users depend on a lot of things. Also on policies and event handlers configured.
This is why privacyIDEA could resolve the user several times during one request. If this is not ok for you, you can use the user cache.
