### ISSUE TITLE
Automatically delete MachineTokenOptions when a MachineToken is deleted

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3165]
When a token is deleted which is bound to a Machine, the corresponding entry in the MachineToken table is deleted as well. But corresponding MachineTokenOptions entries are not deleted thus generating a 500 error since the database constraints are not fulfilled.
We should automatically delete the MachineTokenOptions entries when the corresponding MachineToken entry is removed.

**Comment by cornelinux** [comment]
Closed by #3225
