### ISSUE TITLE
PrivacyIDEA Authenticator 4.0: PUSH does not work in PrivacyIDEA 3.6.2 environment

### ISSUE THREAD

**Issue by bj654** [privacyidea/privacyidea#3177]
Hi
We have so far had a relatively stable PrivacyIDEA environment running version 3.6.2 (mobile 3.1.5) with PUSH tokens working.
On the new version of the mobile application PrivacyIDEA Authenticator 4.0 we get in the logs error:
"error": {
    "code": 403,
    "message": "SenderId mismatch",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "SENDER_ID_MISMATCH"
      }

But if someone is using older version of mobile application , for example 3.1.5 communication with PUSH works correctly
Can someone help?

**Comment by bj654** [comment]
In my opinion I have given enough information above, but of course if you need it please specify

**Comment by ModuCZ** [comment]
+1 same issue

**Comment by jacekwiczkowski** [comment]
Since app version 4.0.0, the Firebase project is hosted by NetKnights. This means that Push will no longer work the way it did before.

There are two possible solutions to this problem

1. to get Push running again, a Firebase configuration from privacyIDEA is needed.

2. update your privacyIDEA server to version 3.7.1 and use poll

**Comment by bj654** [comment]
Thank you.
Can you explain how  to implement point 1:
"to get Push running again, a Firebase configuration from privacyIDEA is needed."

**Comment by jacekwiczkowski** [comment]
take a look at this article. https://www.privacyidea.org/privacyidea-authenticator-4-0-with-push-poll/

**Comment by bj654** [comment]
Thank  You for your support.
We have done the configuration with Poll (without Firebase) for now. Tokens Push started to work. 
A few more questions came up in the new environment that I would appreciate clarification on:
1. Does Push token protection work in the Poll configuration? - I set the policy on the server (push_firebase_app_pin), but the newly made token is not protected. For OTP it works without any problem
2. Is it possible to force server-side protection for existing tokens in PrivacyIdea Authenticator 4.0
3. In PrivacyIdea Authenticator 4.0, when Decline (not Accept) is pressed, is anything sent to PrivacyIdea 3.7.1 server, obviously in Poll configuration?
4. I'm from Poland and by default after installing PrivacyIdea Authenticator 4.0 the Czech language is enabled - a bit inconvenient for regular users. Is it possible to :
- make English by default
- make Polish version, what needs to be done

**Comment by jacekwiczkowski** [comment]
Hello @bj654 

1. locking the push token currently does not work, but will be implemented in the next app version https://github.com/privacyidea/pi-authenticator/issues/251
2. It is not possible to force server side protection for existing tokens. You need to enable the policy 
hotp_force_app_pin & totp_force_app_pin and rollout new tokens. However, you can still lock the tokens in the app, by swiping right and tapping on 'lock'
3. There is no response sent to the Server when Decline is pressed. However this is something we know about and will be implemented in the next app version https://github.com/privacyidea/pi-authenticator/issues/197
4. This is something we need to investigate further, nevertheless the default language should be English, if there is no available translation

**Comment by Happy2C0de** [comment]
Thank you @jacekwiczkowski for your explanation and the blog entry. 👍 

For us, it's important to be able to configure a different Firebase project for Push Tokens for our own applications or to be able to recompile the pi-authenticator with a different Firebase project. The article clarified this.
Thanks a lot for your work and effort!

**Comment by bj654** [comment]
Hello @jacekwiczkowski 
Thank you for all your support
