### ISSUE TITLE
PrivacyIDEA Free version have limits count user?

### ISSUE THREAD

**Issue by arpsyapathy** [privacyidea/privacyidea#3182]
Hi!

Tell me please
PrivacyIDEA Free version have limits count user?
I want use PrivacyIDEA with PrivacyIDEAADFS-Providers

Thank you advance

**Comment by cornelinux** [comment]
The privacyidea server has not.

For the ADFS Plugin you need a subscription file. 
A demo subscription file can be found here: https://github.com/privacyidea/adfs-provider/releases/download/v1.0.1/2022-12-31_Dummy.Customer_privacyIDEA-ADFS.sub
