### ISSUE TITLE
WebUI Templates are broken when running behind a reverse proxy under a subdirectory.

### ISSUE THREAD

**Issue by adamboutcher** [privacyidea/privacyidea#3190]
### Top-level intent

What did you try to achieve?
Run privacyIDEA behind a reverse proxy on a subdirectry e.g. auth.example.com/otp

### Steps to reproduce

1. Create a reverse proxy.
2. Proxy at the subdomain level
3. visit the web page.

### Expected outcome

What do you think, how the system should have worked?
Perfectly working WebUI.

### Actual outcome

What did actually happen?
WebUI was broken.
This is because there is a mix of absolute and relative URLs in the theming/templating. eg /static/css vs static/css

**Comment by adamboutcher** [comment]
I had to work around this issue with nginx subfilters.

```
server {
  server_name auth.example.com;

  location /otp/ {
    allow              all;
    proxy_pass         http://127.0.0.1:8001/;
    sub_filter         "\"/" "\"";
    sub_filter         "\'/" "\'";
    sub_filter_once    off;
  }

}
```

**Comment by adamboutcher** [comment]
Related to #3181 and partially related to #3191.

The ultimate issue is that running PrivacyIDEA under a subdomain proxy wasn't a considered scenario (or not completely tested), so features/support is really wobbly however it's only some minor tweaks required.

**Comment by cornelinux** [comment]
I see.

Your reverse proxy does something like 

    otp.example.com --> example.com/otp

Yes, this is currently not supported.

Running privacyidea and addressing it via 

    example.com/otp

should fully work.

**Comment by adamboutcher** [comment]
You don't detect the path from the browser correctly though and some of the templating system always pulls from the root domain rather than the relative path.
This is also not passed to the email templates.

Even this /[privacyidea](https://github.com/privacyidea/privacyidea/tree/master/privacyidea)/[webui](https://github.com/privacyidea/privacyidea/tree/master/privacyidea/webui)/login.py
```
DEFAULT_THEME = "/static/contrib/css/bootstrap-theme.css"
```

Would always result in example.com/static/contrib...... even if you're attempting to run on the subdomain example.com/otp

Unless I'm missing something from the documentation?

**Comment by adamboutcher** [comment]
> I see.
> 
> Your reverse proxy does something like
> 
> ```
> otp.example.com --> example.com/otp
> ```

No My proxy is literally
```
example.com/otp/ -> piserver.localhost
```
