### ISSUE TITLE
Allow modification of base_url

### ISSUE THREAD

**Issue by adamboutcher** [privacyidea/privacyidea#3191]
**Is your feature request related to a problem? Please describe.**
What are you trying to achieve?
Run PrivacyIDEA behind a reverse Proxy under a subdirectory.

**Describe the solution you'd like**
A way to configure the base_url variable passed to email templates.

**Additional context**
Emails from PrivacyIDEA (including password reset emails) detect the base_url you're using from the server HTTP_HOST, however it doesn't detect if you're running this under a subdirectry, as such the links sent in the emails are incorrect, a method to edit/append to this variable would solve this problem.

**Comment by cornelinux** [comment]
See before.
