### ISSUE TITLE
during authentication, password autofills into the totp input. 

### ISSUE THREAD

**Issue by Firstyear** [privacyidea/privacyidea#3196]
### Top-level intent

During authentication, my password manager became confused by the TOTP prompt, and attempted to enter the password a second time.

### Steps to reproduce

1. Enroll a TOTP via a password manager (keepassxc for example)
2. Logout / Sign in
3. Attempt to complete the TOTP. 

### Expected outcome

TOTP should have been prompted to autofill.

### Actual outcome

The password autofilled to the TOTP input

### Configuration

Unknown - this is via my company portal.

### Log file

Unknown - via company portal

### Extra Details.

A working implementation of this is found on borgbase:

```
<input name="otp" autocomplete="off" id="otp" placeholder="2FA Token" type="text">
```

This setup of the html element allows autocomplete of the TOTP. Contrast this to the input field displayed by privacy idea: 

```
<input name="password" type="password" autocomplete="off" id="password" class="form-control ng-pristine ng-empty ng-invalid ng-invalid-required ng-touched" ng-model="login.password" required="" placeholder="Please confirm with one of these tokens: PIEM0049D6C3 TOTP0037FECA">
```

Note that it says it's a "password" type, which is likely what is confusing my password manager. It should be a type="text" and could even be re-named to otp to help guide the ui flow better to external password managers.

**Comment by Firstyear** [comment]
You shouldn't need to "hide" a TOTP input though. I think this actually makes it harder for users since they can't identify input mistakes, and a TOTP is intentionally shortlived so disclosure is a low risk.

**Comment by plettich** [comment]
> You shouldn't need to "hide" a TOTP input though. I think this actually makes it harder for users since they can't identify input mistakes, and a TOTP is intentionally shortlived so disclosure is a low risk.

Well actually a TOTP should be treated like a password since (at this point) it authenticates the user. I guess it is debatable whether the OTP input should be hidden.
One day we might add one of those little icons to show the password input. Until then You are of course free to customize the HTML templates: https://privacyidea.readthedocs.io/en/latest/faq/customization.html

**Comment by Firstyear** [comment]
That's not what a TOTP is for 🙃 Yes it "authenticates" the user, but so does the password. It's the combination that does the authentication. The point of a TOTP is to protect from bruteforce, password spraying, credential stuffing etc. So the disclosure of a single TOTP does matter because anyone "watching" has 60 seconds to use it, *and* they'd need the password. 

So I think this is still incorrect.
