### ISSUE TITLE
Middle click / open link in tab breaks authentication

### ISSUE THREAD

**Issue by Firstyear** [privacyidea/privacyidea#3197]
### Top-level intent

When listing my tokens, I attempted to view a token in a new tab, and the new tab was logged out.

### Steps to reproduce

1. Log in
2. Open a token in a new tab

### Expected outcome

The new tab was authenticated, and I could see the token.

### Actual outcome

The new tab was logged out. 

### Details

This appears to be an artifact of how PI manages it's authentication (bearer) token. There is a header for PI-Authorisation, which is sent with every request. The application (from the web-inspector ...) appears to be an angular SPA. Looking through the sources, I can see that there is an "AuthFactory", which appears to be a singleton from auth.js. This means that over a tab-boundary, the session state is lost because the authfactory is stored "in memory". The proper was to manage this would be to use the webstorage local storage api's per https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API to allow the session to be shared between tabs, and to persist over a close/re-open event.

**Comment by cornelinux** [comment]
Works as designed.
THe privacyIDEA UI "Session" only works within **one** browser tab.

**Comment by Werkov** [comment]
BTW, I experienced logout also after a mere F5 in a single tab. Is that also per design?

What is the motivation behind this design?

**Comment by cornelinux** [comment]
> BTW, I experienced logout also after a mere F5 in a single tab. Is that also per design?
> 
> What is the motivation behind this design?

Yes. When you hit F5 you restart the web application. And thus you loose your JWT.
This way we do not need session cookies in the client. We do not need to track sessions on the server.
-> Easier code. Lesse code. More rapid development. Less bugs. Higher Security

**Comment by Werkov** [comment]
Thanks (I realize now that the app is just a JS floating volatile in RAM and nothing more, hence this behavior is actually the simpler implementation).

**Comment by Firstyear** [comment]
> Works as designed. THe privacyIDEA UI "Session" only works within **one** browser tab.

This is a bug because it breaks a basic web function (tabs) in a confusing way.

**Comment by hramrach** [comment]
> Works as designed. THe privacyIDEA UI "Session" only works within **one** browser tab.

That's bogus.

You are either logged in or logged out, not logged-in-per-tab.

We have 'incognito' tabs for not sharing sessions across tabs.
