### ISSUE TITLE
Enrolling an ssh public key that does not have the user@host component causes 500

### ISSUE THREAD

**Issue by Firstyear** [privacyidea/privacyidea#3198]
### Top-level intent

Add my ssh key for the form "scheme publickey" that did not contain the "user@host" element. This caused the enrollment to have a server 500 error, but the key was still added (and repeating allows the key to be added multiple times). 

### Steps to reproduce

1. Attempt to add the key as defined

### Expected outcome

Either a proper warning should have been displayed and the key rejected, or the enrollment should have been a success.

### Actual outcome

A 500 error was shown, but the key was also added. Repeating this allows the key to be added multiple times which then requires clean up (so you probably need to also prevent duplicate key addition ...).

**Comment by cornelinux** [comment]
Investigate and solve.

**Comment by NNLemling** [comment]
fixed in 6ddff7f33b7c5f90f37def51ee34135da5891185.
