### ISSUE TITLE
Refresh the page with F5 key cause lost of session

### ISSUE THREAD

**Issue by salvorapi** [privacyidea/privacyidea#320]
Hi,

if you login with admin credentials and next use F5 key for refresh the web page it cause the lost of session and it's necessary to insert again the credentials.

Salvo.

**Comment by cornelinux** [comment]
Hi Salvo,

This is a known behavior. Call it feature or issue.

The privacyidea UI does not use any cookie or credential caching on purpose. It is a single page application that uses token based (JWt) authentication. 
One side effect is, that you do not have to worry about cross site request forgery. In a similar product I was working on earlier we had to do many strange things to avoid CSRF.

Another nice side effect is, that you can login as different users in different tabs of your browser.

What do you need F5 for?

Kind regards 
Cornelius
