### ISSUE TITLE
User with username length 35+ is not found

### ISSUE THREAD

**Issue by Benderinho** [privacyidea/privacyidea#3202]
Configured an ldapresolver, chose userPrincipalName for login name attribute. Users with 35 or more characters in their username are created successfully but some interactions produce error: ERR904: The user can not be found in any resolver in this realm!

Error shows up via API and GUI. Calls to token/?user=i.haveaverylongnamefortestingpurpose@domain.tld produce answer 400 BAD REQUEST and ERR904. Although user/?resolver=users does list the user. Same in GUI, user is shown in Users List, on opening the user, ERR904 is shown in the right upper corner, but the user details are shown.

Reproduced behaviour with privacyidea 3.6.3 and 3.7.1

**Comment by cornelinux** [comment]
* Please provide the audit log for the `GET /token`
* Please provide the privacyidea.log in debug mode for this request.

**Comment by Benderinho** [comment]
I cannot reproduce the issue right now. What did change:
* updated privacyIDEA to v3.7.2
* increased some column sizes in pi.pidea_audit, because there were errors like this in pi.log "exception DataError('(pymysql.err.DataError) (1406, "Data too long for column [...]" :
```
ALTER TABLE pi.pidea_audit MODIFY COLUMN info VARCHAR(100);
ALTER TABLE pi.pidea_audit MODIFY COLUMN user VARCHAR(50);
ALTER TABLE pi.pidea_audit MODIFY COLUMN administrator VARCHAR(50);
```
I will do some additional testing next week.

**Comment by Benderinho** [comment]
I also cannot replicate the issue in privacyIDEA v3.7.1, must have been something strange with my setup or config.
