### ISSUE TITLE
Keycloak User Resolver

### ISSUE THREAD

**Issue by michaelottofits** [privacyidea/privacyidea#3211]
The Keycloak already has an API through which users can be read into PrivacyIdea. The connection should be easy without the additional plugins for the Keycloak.

Advantages:
Simple configuration with the parameters known in Keycloak.
No additional addons needed

**Comment by cornelinux** [comment]
1. privacyIDEA does not **import** users, it **reads** users, usually just-in-time.
2. I do not think, that keycloak is the system to really manage users. At least I have never seen this. And even if you would manage users within keycloak - where are these users actually stored?

I do not see this request to be sensible.

**Comment by michaelottofits** [comment]
It is correct. Users should only be read from Keycloak.
I have already implemented this in the fork https://github.com/michaelottofits/privacyidea/. Issue is only to documentation. Maybe this can be adopted.

**Comment by cornelinux** [comment]
IMHO this is not relevant. All users used by keycloak are located in LDAP or SQL (in the setups I know)

**Comment by yangboyd** [comment]
> 

Hi michaelottofits,
Which keycloak version are you using?

**Comment by yangboyd** [comment]
> It is correct. Users should only be read from Keycloak.
> I have already implemented this in the fork https://github.com/michaelottofits/privacyidea/. Issue is only to documentation. Maybe this can be adopted.
Hi [michaelottofits](https://github.com/michaelottofits),
Which keycloak version are you using?

**Comment by yangboyd** [comment]
> It is correct. Users should only be read from Keycloak.
> I have already implemented this in the fork https://github.com/michaelottofits/privacyidea/. Issue is only to documentation. Maybe this can be adopted.



Hi [michaelottofits](https://github.com/michaelottofits),
Which keycloak version are you using?

**Comment by michaelottofits** [comment]
currently I am still working with version 17.0.0

**Comment by michaelottofits** [comment]
> > It is correct. Users should only be read from Keycloak.
> > I have already implemented this in the fork https://github.com/michaelottofits/privacyidea/. Issue is only to documentation. Maybe this can be adopted.
> 
> Hi [michaelottofits](https://github.com/michaelottofits), Which keycloak version are you using?

currently I am still working with version 17.0.0

**Comment by yangboyd** [comment]
> 

Thanks,
Tested working for keycloak 18 too.

**Comment by yangboyd** [comment]
> > > It is correct. Users should only be read from Keycloak.
> > > I have already implemented this in the fork https://github.com/michaelottofits/privacyidea/. Issue is only to documentation. Maybe this can be adopted.
> > 
> > 
> > Hi [michaelottofits](https://github.com/michaelottofits), Which keycloak version are you using?
> 
> currently I am still working with version 17.0.0

Thanks,
Tested working for keycloak 18 too.

**Comment by michaelottofits** [comment]
> > > > It is correct. Users should only be read from Keycloak.
> > > > I have already implemented this in the fork https://github.com/michaelottofits/privacyidea/. Issue is only to documentation. Maybe this can be adopted.
> > > 
> > > 
> > > Hi [michaelottofits](https://github.com/michaelottofits), Which keycloak version are you using?
> > 
> > 
> > currently I am still working with version 17.0.0
> 
> Thanks, Tested working for keycloak 18 too.

you tested my integration for loading users with my keycloak resolver ?
