### ISSUE TITLE
Change default AD attributes

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3218]
For some reasons in AD the search filter `(objectClass=person)` will also find machines.
This can also be reproduced with a UCS.

Only when changed to `(objectCategory=person)` it will not return machines.

We should change the "Preset AD attribute mapping" to use `objectCategory`.

**Comment by NNLemling** [comment]
fixed in d1db4dd88f42ab01b299ca1049c1cbda3686b6a0.
