### ISSUE TITLE
email event to the user on token return

### ISSUE THREAD

**Issue by katgirl** [privacyidea/privacyidea#3252]
When a token relationship is cancelled, it should be possible to inform the user about it by email.

**Comment by katgirl** [comment]
Yes, sorry. Not cancelled -> unassigned

This was also our first approach

The EventHandler with ```post``` does not work because there is no user left.  
If we change to ```pre``` the EventHandler does not start. 

Our approach was that he does not notice that a manual action was performed there.

**Comment by plettich** [comment]
Which version of privacyIDEA are You running? I could not reproduce this with the current version. Both `pre` and `post` EventHandler send an email to the user.

**Comment by katgirl** [comment]
Prod: 3.6.2
Dev: 3.7.1

**Comment by cornelinux** [comment]
We can not reproduce this. Please try with latest 3.7.3 or provide more information.

**Comment by katgirl** [comment]
![image](https://user-images.githubusercontent.com/1223243/183029844-d3022afd-71c0-455a-a69f-07605a6cfff5.png)

This works:
![image](https://user-images.githubusercontent.com/1223243/183030067-899e8020-c502-4ac0-83c8-be241f5a4110.png)

But this not:
![image](https://user-images.githubusercontent.com/1223243/183030276-53755041-aaa5-4fa6-91cb-991decc2fcf0.png)

we have planned the update for week 33. Unfortunately, we can not update the system without notice.
