### ISSUE TITLE
Support for Shibboleth SP Logout using PI_LOGOUT_REDIRECT_URL

### ISSUE THREAD

**Issue by beckerr-rzht** [privacyidea/privacyidea#3257]
**Is your feature request related to a problem? Please describe.**
I use privacyIDEA together with Shibboleth SP and SAML.
Everything works as desired and `REMOTE_USER` is used.

However, the **logout from privacyIDEA is incomplete**.
Cause is that the Shibboleth SPs **logout URL is not used**.

**Describe the solution you'd like**
After logout from privacyIDEA, the browser should be **redirected to a configurable URL**.
One should be able to specify a `PI_LOGOUT_REDIRECT_URL` to use.

This could look like this in `pi.cfg`:
```
PI_LOGOUT_REDIRECT_URL = '/Shibboleth.sso/Logout?return=/pi/'
```

**Describe alternatives you've considered**
No alternatives as this is the documented way :)

**Additional context**
See "SP Logout URL" at https://docs.shib.ncsu.edu/docs/logout.html

**Comment by cornelinux** [comment]
Do I understand you correctly, that you are logging in at the privacyIDEA with privacyIDEA as a SAML SP?
...and you expect the privacyIDEA Logout button to issue a SAML logout request?

**Comment by cornelinux** [comment]
I think we should put this into a webui policy.

**Comment by beckerr-rzht** [comment]
>  ...and you expect the privacyIDEA Logout button to issue a SAML logout request?

Exactly! That's the behavior that one would expect.

Here is a GIF screen capture of the workflow as it is implemented by my pull request:

![Recording 2022-08-04 at 12 59 04](https://user-images.githubusercontent.com/15359213/182831537-a9e7b015-ba2c-4e1b-ad2f-1261234af1ba.gif)

**Comment by plettich** [comment]
We need to check at login if the authentication came from an SSO provider.
We also need to check if we can add a policy condition for SSO login.

**Comment by cornelinux** [comment]
@plettich says this is done *before* the login. However, this information should be sent to the webui *after* the user has logged in, so that also the realm information is available - similar to policies and rights.

see token_per_page or audit_page_size, which are also sent to the UI *after* the login (delete_customer_user_attribute, logout_time)
