### ISSUE TITLE
Customizable TOTP/HOTP Issuer

### ISSUE THREAD

**Issue by ziQ** [privacyidea/privacyidea#3267]
With several running instances of privacyIDEA, the default issuer "privacyIDEA" becomes confusing. It would be good to have this variable customizable per instance (or per database, allowing multiple HA instances to automatically have the same issuer).

https://github.com/privacyidea/privacyidea/blob/a46bbeddbc32ff299cfd5c602a5178b0d7eb5db2/privacyidea/lib/importotp.py#L711

**Comment by plettich** [comment]
Hi @ziQ 
so You mean the issuer when exporting the tokens in pskc format with the token janitor?
It should be easy to just add a parameter to the token janitor to pass an issuer string to the pskc-export function.

**Comment by ziQ** [comment]
When I use the token enrollment function, I get a QR code containing a URI like this:
otpauth://totp/TOTP0034C497?secret=HSKS7MIRNOX7JSTJBJSSBHZ7AQM5WE2D&period=30&digits=6&issuer=privacyIDEA

This means that each generated token for each privacyIDEA instance that we may run (prod, test, staging, employee-only, community, ...) has the same static `issuer=privacyIDEA` set, which in turn leads to a very confusing list of tokens in Google Authenticator or whichever TOTP app the user uses.

**Comment by plettich** [comment]
Ok, so this is not about the token export.
You probably want an enrollment policy with a `tokenissuer` and/or `tokenlabel` action:
https://privacyidea.readthedocs.io/en/latest/policies/enrollment.html#tokenissuer
