### ISSUE TITLE
Token information is not displayed

### ISSUE THREAD

**Issue by katgirl** [privacyidea/privacyidea#3270]
### Top-level intent
If the token is no longer in the token realm of the user realm, no more token information is displayed.

### Steps to reproduce

1. Add Token to user
2. change token realm (not unassign and new assign) without user realm 

### Expected outcome

Tokeninformation hidden

### Actual outcome

see Tokeninformation

### Configuration

* **privacyIDEA version**:
* **Installation method**:PyPI,
* **Python version**: 3.7.2 (last release)
* **Operating system**: Linux
* **Webserver**: Nginx
* **Token database**: PostgreSQL

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by cornelinux** [comment]
tokeninformation belongs to the token, not to the user.
So if viewing a token is possible, the tokeninformation will also be visable.
