### ISSUE TITLE
Display of multiple token serials in the audit log

### ISSUE THREAD

**Issue by NNLemling** [privacyidea/privacyidea#3285]
It would be nice if multiple token serials could also be displayed in the audit log.

**Comment by NNLemling** [comment]
fixed in 4bd26b740d709d568980cbc6961fa373df6a2b56.

**Comment by plettich** [comment]
> fixed in [4bd26b7](https://github.com/privacyidea/privacyidea/commit/4bd26b740d709d568980cbc6961fa373df6a2b56).

You need to put this in the PR for automatic closing of the issue :-)
