### ISSUE TITLE
Set Images/Icons for each token

### ISSUE THREAD

**Issue by leofuehringer** [privacyidea/privacyidea#3289]
It would be great if it is possible to upload an icon or image for each token.

This would give you a much better overview and you would find the right token faster.

**Comment by cornelinux** [comment]
Do you mean

a) the admin can upload an image for TOTP token types and this image would be used for *all* totp tokens or
b) a user can upload an individual image for his own tokens.

@leofuehringer Please elaborate a bit.
Thanks a lot.

**Comment by leofuehringer** [comment]
I mean b)

You can currently see the login data for e
![demo-colour](https://user-images.githubusercontent.com/13933437/190385593-a1fb2133-3b30-45bf-846b-487c88bf6307.png)
ach token. However, I think a small icons beside each token would give a better overview.

Maybe you could even offer the users ready-made icons. E.g. just different colored circles.
Or users can upload suitable icons themselves. E.g. the logo of the Website...

I hope I expressed myself a little better this time :)

**Comment by plettich** [comment]
Ah, this is for the App.
The App already contains code to display tokens but it is not released yet.
You can add an image URL to the rollout with an [enrollment policy](https://privacyidea.readthedocs.io/en/latest/policies/enrollment.html#appimageurl).
In this case the token image is set by the server enrolling the token (if the server supports it). We should discuss if the user should be able to set an image locally.
Until then You can use the [`tokenissuer`](https://privacyidea.readthedocs.io/en/latest/policies/enrollment.html#tokenissuer) and [`tokenlabel`](https://privacyidea.readthedocs.io/en/latest/policies/enrollment.html#tokenlabel) policies to distinguish between different tokens.

**Comment by cornelinux** [comment]
@plettich I take the liberty of closing this. If you see this otherwise, please reopen.
