### ISSUE TITLE
pidea_audit.privacyidea_server artifically small column

### ISSUE THREAD

**Issue by reardencode** [privacyidea/privacyidea#329]
This column is limited to 20 characters which is a rather silly and arbitrary limit for a server's name.

Locally I've bumped it to 255 on the DB, and that seems to work w/o code change, but probably this should be done by a proper migration.

**Comment by cornelinux** [comment]
The pidea_audit is not handled by the database scheme and thus not part of the DB scheme migration process.
The audit module can be an indiviual module, so in fact you could run your very own audit module.

As a matter of fact I once had a project which was based on Oracle servers. And I think I remember that there was a problem with the length of the column.

How long is the hostname of your servers anyway?

**Comment by reardencode** [comment]
Our privacyidea hostname (as taken from the HTTP headers) is 27 characters.

**Comment by cornelinux** [comment]
Thanks. What database are you running? MySQL/Maria or postgres?

**Comment by reardencode** [comment]
Maria

**Comment by reardencode** [comment]
using the PyMySQL driver

**Comment by cornelinux** [comment]
That was fast! ;-)
Having you adapt the column size does not matter. Since privacyIDEA does not touch your database table if it is already created.
So we could enlarge the column, and if it is to long for other instances, it could be shortened and the code would not bother.

**Comment by reardencode** [comment]
Yeah, that makes sense I think.  The other thing I wondered is if there should be a configured PI_SERVER_NAME that is used for audit logging rather than the HTTP hostname.

We're using a loadbalancer to front PI so both of our servers get the same HTTP hostname, making that information not very useful.

**Comment by reardencode** [comment]
(thanks for the quick response, btw :) )

**Comment by cornelinux** [comment]
OK, RFC1123 says MUST 63 and SHOULD 255.
http://tools.ietf.org/html/rfc1123#page-13

Yes, this field was ment to distinguish the several instances of a cluster. So using something like PI_SERVER_NAME makes sense.

I think something like either config entry and fallback to host.

**Comment by reardencode** [comment]
:+1:

**Comment by cornelinux** [comment]
For clarity I'll choose PI_AUDIT_SERVERNAME ;-)
