### ISSUE TITLE
Implement remaining attestation formats for webauthn

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3294]
The following attestation formats need to be implemented:
- [ ] [`tpm`](https://w3c.github.io/webauthn/#sctn-tpm-attestation)
- [ ] [`android-key`](https://w3c.github.io/webauthn/#sctn-android-key-attestation)
- [ ] [`android-safetynet`](https://w3c.github.io/webauthn/#sctn-android-safetynet-attestation)
- [ ] [`apple`](https://w3c.github.io/webauthn/#sctn-apple-anonymous-attestation)

**Comment by cornelinux** [comment]
Thank you

**Comment by cornelinux** [comment]
At the beginning of the development phase we need to check, if we want to change a webauthn dependency.

**Comment by hex-m** [comment]
Regarding TPM-attestation: If you set attestation to `indirect`, systems with TPM 1.2 can't use the platform authenticator (Windows Hello) anymore.

**Comment by nilsbehlen** [comment]
maybe we should use a library to implement the attestation
