### ISSUE TITLE
LDAP-injection

### ISSUE THREAD

**Issue by ZenSecurity** [privacyidea/privacyidea#330]
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/LDAPIdResolver.py#L298

It possible to inject custom filters into `filter`, which could assist you in:
1) user brute-forcing without knowledge about full login
2) retrieving users AD logins and their data

Need to filter user input data.

**Comment by cornelinux** [comment]
Thanks a lot for the notice.

Looking at line 187: Neither searchfilter nor uidtype nor uid is user input data.
Can you please elaborate on this?

**Comment by ZenSecurity** [comment]
curl -i -s -k  -X 'POST' \
    -H 'Content-Type: application/json;charset=utf-8' \
    --data-binary $'{\"username\":\"*)(sAMAccountName=*\",\"password\":\"\"}' \
    'http://127.0.0.1:5000/auth'

just insert `print filter` and look inside.
Sorry, i have copied wrong string number, look at string 298.

**Comment by cornelinux** [comment]
I am getting wrong credentials. Of course you may get strange filters. If you enter a username like "*", you will get all users, but you also need to look at line 313.

So you are right that this sole line of code might really not be best practice, but I can not reproduce any LDAP listing.
And if you modify the code (like addint print filter) you could also just issue normal ldap requests?

Sorry, I just can not reproduce it and can not see it.

**Comment by ZenSecurity** [comment]
For example, you have account: `v_pupkin`.
You press: "v_p*" and you will have an answer "Found more than one object for Loginname 'v_p*'".
Then you are trying to guess correct mask for username, `v_pupk*`, untill you have "Wrong credentials"

And you will have ldap - query : 
`(&(sAMAccountName=*)(objectClass=person)(sAMAccountName=`v_pupk*`))`
Also you can inject any ldap expression instead of `v_pupk*`

It can helps you to brute-force accounts without any knowledge about real login.

**Comment by cornelinux** [comment]
OK, I understand.

You try to login as

v_p*
v_pu*
v_pupk*
v_pupkin*

an as soon as you get wrong credentials you know, that you hit a valid user name.

Thanks for the explaination.

**Comment by ZenSecurity** [comment]
We can use use `or` expression to help us.
`(&(sAMAccountName=*)(objectClass=person)(sAMAccountName=*)(|(sAMAccountName=v_pupkin*)(sAMAccountName=*)))`

Aren't we ?

**Comment by cornelinux** [comment]
I would like to replace the special characters in the username as described at the bottom of
https://msdn.microsoft.com/en-us/library/aa746475(v=vs.85).aspx
"Special characters"

**Comment by ZenSecurity** [comment]
Thanks!
