### ISSUE TITLE
No release in GitHub for 3.7.3

### ISSUE THREAD

**Issue by dronenb** [privacyidea/privacyidea#3305]
### Top-level intent

What did you try to achieve?
Looked in GitHub for 3.7.3 release and did not see one. There is a tag but not an actual release. If this was intentional please close this issue.

### Steps to reproduce

1. Look in https://github.com/privacyidea/privacyidea/releases
2. No 3.7.3 release

### Expected outcome

What do you think, how the system should have worked?
I think there should be a 3.7.3 release.

### Actual outcome

What did actually happen?
No 3.7.3 release.

### Configuration

* **privacyIDEA version**:
* **Installation method**: (from Ubuntu packages, github, PyPI, ...)
* **Python version**:
* **Operating system**:
* **Webserver**:
* **Token database**: (MySQL, PostgreSQL, ...)

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by cornelinux** [comment]
@dronenb thanks for the heads up. I added this release from the tag.
How are you using it?

**Comment by cornelinux** [comment]
(Closing it, but still curious for your response)

**Comment by dronenb** [comment]
Well, mainly because it seems the other versions have a release and that one did not, and if somebody is looking at the GitHub repository trying to find what the latest version currently is, it is useful to have the most recent release reflect that. I was looking at this repository [here](https://github.com/Khalibre/privacyidea-docker), and they are manually updating their Docker image based off the latest version number, and they have their docker image generated from code from GitHub. Their most recent commit on the repo was after the 3.7.3 release, so I believe that they did not yet realize there was a newer version available since it was not shown on the GitHub releases.

Thank you for your work on PrivacyIdea, it is a very cool piece of software.
