### ISSUE TITLE
remove flask imports from lib

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#331]
There are some flask imports in privacyidea.lib.

We should remove them, to be able to use privacyidea.lib without any reference to flask.

**Comment by cornelinux** [comment]
This probably won't work out.

**Comment by fredreichbier** [comment]
While we probably won't be able to remove all Flask imports from privacyidea.lib, we could try to minimize them: For example, we use `flask.g` for per-request caching. We could define a central function like the following:

<pre>
def get_request_local_context():
    return flask.g
</pre>

and use this function instead of `flask.g` in `privacyidea.lib`.

**Comment by fredreichbier** [comment]
The code cleanup milestone may be a good opportunity to minimize the Flask imports in ``privacyidea.lib``. I think we essentially need an "application context" (shared between threads) and "request-local context" (thread-local) which different responsibilities:
* the application context stores objects like the configuration, the policies, the engine registry, the HSM object, maybe at some point an LDAP server pool?
* the request context stores objects like the request-local configuration snapshot, request-local policy snapshot, the current resolver objects

Like above, I'm not sure if we can completely get rid of Flask imports. But we could avoid to explicitly import Flask names by having two functions
```python
def get_application_local_context():
    return something

def get_request_local_context():
    return flask.g
```
and only using these two functions in ``privacyidea.lib``. We could do this without touching too much existing code.

**Comment by cornelinux** [comment]
The flask dependency was reduced to ``lib/framework.py`` (and one occurrance in the federation handler).
This is as good as we should get. 
In aspect of being able to migrate to a potential other request framework (like bottle ;-) one day, the effort of code changes would be small enough.
