### ISSUE TITLE
Support of sha512 with Google Authenticator

### ISSUE THREAD

**Issue by stephanhendl** [privacyidea/privacyidea#3311]
Meanwhile the Google Authenticator support sha512 as well. So the gray line below the field could be removed.

![image](https://user-images.githubusercontent.com/18658366/192969491-18c3a2c2-d207-4513-a0a4-92c44b800ddf.png)

Regards,
Stephan

**Comment by plettich** [comment]
Hi @stephanhendl i can not reproduce this. The Google Authenticator (5.20R4 on Android) does scan the QR-Code and adds a token but it calculates the wrong values. You can check with the [privacyIDEA Authenticator](https://play.google.com/store/apps/details?id=it.netknights.piauthenticator) which should support all OATH parameter.

**Comment by stephanhendl** [comment]
Hi, @plettich unfortunately you are right. I tried version 6.2208.5677 but chose a wrong key type. So its my fault, sorry.
