### ISSUE TITLE
TypeError('getattr(): attribute name must be string',) with SQL Resolver

### ISSUE THREAD

**Issue by m0urs** [privacyidea/privacyidea#332]
I created SQL resolver for MySQL and the "Test" button shows me the correct number of users. I also can add new users via the privacyIDEA web interface to that SQL database.

However, as soon as I want to list my users in privacyIDEA web interface no users are displayed and in the error log I see this message:

[2016-02-24 11:36:39,023][10987][140055712585472][ERROR][privacyidea.lib.user:626] TypeError('getattr(): attribute name must be string',)

This is my attribute mapping in the resolver:

{ "userid" : "USERID" , "givenname" : "FIRSTNAME" , "surname" : "LASTNAME" , "email" : "EMAIL" , "password" : "PASSWORD" }

And this is my database structure:

	CREATE TABLE `users` (
 `USERID` int(11) NOT NULL AUTO_INCREMENT,
 `EMAIL` varchar(30) NOT NULL,
 `FIRSTNAME` varchar(30) NOT NULL,
 `LASTNAME` varchar(30) NOT NULL,
 `PASSWORD` varchar(30) NOT NULL,
 PRIMARY KEY (`USERID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8

I tried to change all fields to "TEXT" instead of "VARCHAR" and also a USERID with type VARCHAR instead of INT. But I guess I miss something else as the issue is also if I just use one of these fields.

Maybe I understood something wrong here?

**Comment by m0urs** [comment]
Sorry, for posting that here as an issue. Just saw that there is a Google Group for support and I posted it there. I guess that would be better place.

**Comment by cornelinux** [comment]
Thanks for posting and closing.

But we might improvde the documentation and state the keys "userid" and "username" in http://privacyidea.readthedocs.org/en/latest/configuration/useridresolvers.html#sql-resolver as mandatory.
