### ISSUE TITLE
Link to latest stable version in read the docs goes to a page not found error

### ISSUE THREAD

**Issue by Factorization** [privacyidea/privacyidea#3320]
### Top-level intent

Clicking the link for the latest stable version in the documentation on any page other than the welcome page, displays a Page Not Found error:

![image](https://user-images.githubusercontent.com/10674846/193707137-f0dfecc5-3a3e-48cc-8006-a804ac891ee8.png)

Page Not Found error:
![image](https://user-images.githubusercontent.com/10674846/193707163-3a4ee53d-8704-4d2b-9825-61e3ef044116.png)

### Steps to reproduce

1. Go to https://privacyidea.readthedocs.io/en/latest/installation/index.html
2. Click the `Version v3.6.2` link at the top of the page.

### Expected outcome
The correct documentation page should be displayed.

### Actual outcome

A `Page Not Found` error is displayed. Looking at the URL for the page, it appears that it is leaving `latest/` in the URL and it should be removed.
![image](https://user-images.githubusercontent.com/10674846/193707540-f7a9121f-037a-46f9-89d4-f225d54ed1c8.png)

**Comment by cornelinux** [comment]
A lot of dependencies with readthedocs are broken. We can only try to fix this for the future.

**Comment by cornelinux** [comment]
Still, I do not understand or can reproduce your problem.

**Comment by Factorization** [comment]
It looks like it's an issue on the `latest` version of the read the docs - https://privacyidea.readthedocs.io/en/latest/. If you click the link in the warning banner at the top of the page, you get a page can not be displayed. It works fine from the `master` version. The repo's main `README.rst` file links `latest` version, maybe this URL should be switch to point to the `master` version:
![image](https://user-images.githubusercontent.com/10674846/194160234-b6684e7a-4436-479a-b049-3bda166c72bf.png)

**Comment by plettich** [comment]
tracking in #3748
