### ISSUE TITLE
Odoo 2FA module

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#333]
Create an authentication module for odoo to authenticate against privacyIDEA.

This can be done similar to auth_ldap:

https://github.com/odoo/odoo/tree/499c2b8da50fd8ae36919805efb4af18524d7b88/addons/auth_ldap
https://www.odoo.com/apps/modules/9.0/auth_ldap/

**Comment by chris001** [comment]
:+1:

**Comment by cornelinux** [comment]
Thanks for the feedback and thumb up.
At the moment I am not using odoo productivly, yet. I am planning on doing so.
So this issue may take a while.

**Comment by cornelinux** [comment]
I am not using odoo anymore. If anyone wants to jump in on that, I am willing to explain the API.

**Comment by chris001** [comment]
If you could, would you explain the API here, for sure someone will jump on it, I will if I have time available.

**Comment by cornelinux** [comment]
Hi @chris001 

for starters you only need one API call, which is ``validate/check``.
http://privacyidea.readthedocs.io/en/latest/modules/api/validate.html#post--validate-check

For simple push button OTP tokens or a smartphone App like the Google Authenticator the API only takes two parameters:

1. username
2. password

The password *can* either consist of a static *otp pin* and an *otp value* or only be the *otp value*. This depends on how you want to integrate it into odoo and how you configure privacyIDEA:

This means the odoo login simply takes 

1. username
2. static password
3. OTP

# possibility 1

2 and 3 can be concatenated into one field. This way the UI of odoo does not need to be changed.
2+3 are sent as *password* to the privacyidea server.

# possiblity 2

2 and 3 and seperated fields but both values are sent as *password* to privacyidea.

# possibility 3

2 is checked against odoo and only 3 (of course with the username) is sent to the privacyIDEA server.

take a look at this python implementation, which uses ``requests`` for issuing a post request to the ``validate/check`` endpoint.
https://github.com/jeweber/django-privacyidea-auth/blob/master/django_privacyidea_auth/privacyidea_auth.py#L72

It then checks the response for ``value=True``.
https://github.com/jeweber/django-privacyidea-auth/blob/master/django_privacyidea_auth/privacyidea_auth.py#L82

**Comment by chris001** [comment]
A couple of dumb questions, sorry!  1. Is how this works, you register your odoo account login ID in google authenticator, then when it's time to login, you login and pass also to odoo also the google auth PIN, which is essentially a strong hash of the current time (modulo maybe 10 seconds time window forward in time) with the account login ID, reduced to a few digits.  Then odoo verifies the login/password, and passes the PIN to privacyIDEA for it to verify with google auth central server, and privacyIDEA  returns a true/false to odoo, which allows or fails the user login.
2. Can privacyIDEA be installed and run on the save server as odoo, or does it take too much ram/cpu/tcp ports which conflicts with osoo?  Same server would probably be a bad idea from a security perspective eh?

**Comment by cornelinux** [comment]
# 1

No. privacyIDEA manages all assigned tokens of a user. The users are the same users like in odoo. Either because privacyIDEA **reads** the users from the odoo database or both - privacyIDEA and odoo - are reading users from an LDAP.

The google authenticator is ony one possible token type, which can be assigned to a user in privacyIDEA.
Odoo forwards and authentication request to privacyIDEA. odoo does not know anything about the tokens of the user, it gives the controll to privacyIDEA: "hey you may verify if the user can log in".

Odoo and you do not need to bother about any OTP algorithm (your modula assumption) If you are interested anyway, read RFC4226 and RFC6238.

Odoo simply passes *this strage number* the user entered **without any further logic** to privacyIDEA. This is why also the previous django plugin I linked only consists of 10 lines of code... ...and a bit boilerplate.

Yes, privacyIDEA returns a true/false to odoo which tells odoo to either let the user in or not.

# 2

You can install it on the same server. Well it runs as a web service, but you can run privacyIDEA in a subpath. 

You should not use the word PIN, it is misleading. The

**Comment by cornelinux** [comment]
We will not do this.
Use LDAP Proxy.
