### ISSUE TITLE
WebAuthn - Resident Key (login without username)

### ISSUE THREAD

**Issue by Happy2C0de** [privacyidea/privacyidea#3336]
Might also be related to #3033 

### Is your feature request related to a problem? Please describe.
As a user, I would like to login using WebAuthn/FIDO2 without specifying the `user=` option while triggering a challenge. A user identification ahead of the Challenge-Response Flow is not needed. 
This allows a user-friendly login experience by just clicking a button `Sign in using webauthn` with highest security standards.

**Background:**
Today, privacyIDEA server has the following information after a WebAuthn token was enrolled.
* privacyIDEA knows the `serial` of the webauthn token that is assigned to a `user` object
* The `token` object contains the `credentialId` from the enrollment ceremony

Today, a `POST /validate/check?user=xyz&type=webauthn` includes the `allowCredentials` json element, that is actually optional in WebAuthn, see [W3C PublicKeyCredentialRequestOptions](https://www.w3.org/TR/webauthn-2/#dictionary-assertion-options). With binding the WebAuthn Challenge to the user and with it to the `allowCredentials`, privacyIDEA enforces the optional parameter.

**Idea:**
Use the `credentialId` to uncover the `user` during the WebAuthn ChallengeResponse while authenticating. This allows to login by just using WebAuthn and without specifying any additional information like the `user=` option ahead of the challenge creation.

This can be tested using the [webauthn-demo](https://github.com/privacyidea/webauthn-demo). This assumes that a WebAuthn token was successfully enrolled. The demo asks for `user@realm` and `pin`. Actually, with the suggestion described in this issue, one only needs to click a "Sign in" button.

#### Reasoning
This would allow a seamless login experience, similar to the efforts of "Passkey".

Add a button `Sign in with FIDO2/Passkey` what triggers an "anonymous" WebAuthn challenge. Here, anonymous means "not bound" to a user. 
Sign the challenge with a known `credentialId`, and resolve the `user` in the second phase of the Authentication flow.

---

### Describe the solution you'd like
WebAuthn should work without the need to trigger a challenge for a specific `user` or `serial`, because the token is already bound to the `credentialId` delivered in the 2nd step of the authentication flow.

This allows to have seamless integration of WebAuth

---

### Describe alternatives you've considered
Use the `user` or `serial` bound approach that exists. This requires to identify the the user before creating a token challenge.

---

#### Implementation suggestion 

Inspired by [webauthntoken.py#L197](https://github.com/privacyidea/privacyidea/blob/v3.7.3/privacyidea/lib/tokens/webauthntoken.py#L197) but with an "anonymous" challenge.

**Pseudo Procedure:**

* Allow anonymous Challenge creation:
    ```bash
    POST /validate/check?type=webauthn
    # No user & serial specified, but just trigger a webauthn challenge
    ```

* Get "anonymous" WebAuthn challenge:
    ```json
    {
        "detail": {
            "attributes": {
                "hideResponseInput": true,
                "img": "<image URL>",
                "webAuthnSignRequest": {
                    "allowCredentials": [],
                    "challenge": "<nonce>",
                    "rpId": "<relying party ID>",
                    "timeout": 60000,
                    "userVerification": "<user verification requirement>"
                }
            },
            "client_mode": "webauthn",
            "message": "Please confirm with your WebAuthn token",
            "serial": "",
            "transaction_id": "<transaction ID>",
            "type": "webauthn"
        },
        "id": 1,
        "jsonrpc": "2.0",
        "result": {
            "authentication": "CHALLENGE",
            "status": true,
            "value": false
        },
        "version": "<privacyIDEA version>"
    }
    ```
    **Note:** No `allowCredentials` and no `serial`, because it's anonymous. All authenticators might sign the request now.

* User gets prompt to sign the WebAuthnSignRequest & signs the challenge. All users with a passkey from the Relying Party can sign the challenge.
* Send reponse to the privacyIDEA server. Equivalent to [webauthntoken.py#L394](https://github.com/privacyidea/privacyidea/blob/v3.7.3/privacyidea/lib/tokens/webauthntoken.py#L394) without the `user` option
    ```bash
    POST /validate/check HTTP/1.1
    Host: example.com
    Accept: application/json

    transaction_id=<transaction_id>
    credentialid=<id>
    clientdata=<clientDataJSON>
    signaturedata=<signature>
    authenticatordata=<authenticatorData>
    userhandle=<userHandle>
    assertionclientextensions=<assertionClientExtensions>
    ```
* privacyIDEA resolves the `user` & `serial` based on the `credentialid` which is uniquely bound to the token, AND proofs the signature.
* Return HTTP response with `true` AND a user identifier.

**Question:**
I am interested in your opinions on this proposal! What do you think?

**Comment by lhaemmerle** [comment]
We are considering to use PrivacyIdea to support WebAuthN. The proposed feature above is what we are currently missing. Most likely, we will start with passwordless login, for which PrivacyIdea's WebAuthN support seems to be sufficient at the moment. 
However, in the medium term usernameless login is also something we want to support. This proposal would make usernameless login possible as far was I understand. Therefore, it would be good  to know if PI could support this at all and if there maybe are plans to already to support it.

**Comment by cornelinux** [comment]
We need to note, that there are other tokentypes, that would also use a username login.
See https://community.privacyidea.org/t/supporting-discoverable-credentials/2855
like the German "DUO".

**Comment by cornelinux** [comment]
Some interesting resources:

https://fidoalliance.org/implement-passkeys-overview/
https://passkeys.dev/docs/reference/specs/

**Comment by cornelinux** [comment]
> However, in the medium term usernameless login is also something we want to support. This proposal would make usernameless login possible as far was I understand.

The challenge is, that there are many different applications, that are connected to privacyIDEA with a lot of different plugins. Some, where privacyIDEA plugs in, only allow for verifying the 2nd factor and will always ask for username and password in the first step (like ADFS, Credential Provider...) and other allow full control (like simpleSAMLphp). 

@lhaemmerle : Which use case/application do you have?

**Comment by hex-m** [comment]
> Which use case/application do you have?

(I'm not the person who was asked)

To be flexible and to unify the login-experience, we implement single-sign-on (SSO via SAML and OIDC) everywhere and only the identity provider (Shibboleth IDP in our case) talks to PI.

**Comment by lhaemmerle** [comment]
> @lhaemmerle : Which use case/application do you have?

We use the Shibboleth Identity Provider (like most universities running a SAML Identity Provider around the world). In the mean time, we implemented Passkeys support with the [Hanko](https://www.hanko.io/) library. Also because we figured that it would not be easy for Privacy Idea to support usernameless login for architecture/historical reasons.

**Comment by extemporis** [comment]
> > However, in the medium term usernameless login is also something we want to support. This proposal would make usernameless login possible as far was I understand.
> 
> The challenge is, that there are many different applications, that are connected to privacyIDEA with a lot of different plugins. Some, where privacyIDEA plugs in, only allow for verifying the 2nd factor and will always ask for username and password in the first step (like ADFS, Credential Provider...) and other allow full control (like simpleSAMLphp).

We use the official Keycloak provider (with a license) but would like to support an alternative authentication flow without the username/password login form. So it would be nice to get the username via challenge response (?) so that we don't need the first step.

**Comment by nilsbehlen** [comment]
this will be done via passkeys #4024 in 3.11, the "old" webauthn implementation will be discontinued.
