### ISSUE TITLE
Optimize URL-decoding

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3337]
If a remote token is used without checking the pin locally, the password is sent as is to the remote server. A percent sign in the password (and/or user?) will break authentication since it is not properly encoded here:
https://github.com/privacyidea/privacyidea/blob/c08154951bb02ddc1794157bd19c7d699d20d5e9/privacyidea/lib/privacyideaserver.py#L68
`realm`, `resolver`, `serial` and `transaction_id` shouldn't be a problem since they shouldn't contain a percent sign.
Normally, `requests` and `Flask` should take care of the data encoding/decoding when the correct content type (`application/x-www-form-urlencoded`) is set. But since we do an extra decoding step here:
https://github.com/privacyidea/privacyidea/blob/93b7aa9896f3714cab47d9f0d4ce35a5a75fa67b/privacyidea/api/lib/utils.py#L255
we need to encode the data before sending.

**Comment by cornelinux** [comment]
I am not sure if all applications, plugins (3rd party plugins) always handle everything correctly.

So we might add a mapping or a policy to define, for which requests we should do urldecoding and for which one not.

**Comment by plettich** [comment]
> I am not sure if all applications, plugins (3rd party plugins) always handle everything correctly.

The perl LWP module (FreeRADIUS) does it correctly.

> 
> So we might add a mapping or a policy to define, for which requests we should do urldecoding and for which one not.

If we receive a (POST-) request with the content type `application/x-www-form-urlencoded` we must assume, that the sender did the correct encoding and that Flask did take care of the decoding before passing the data to us.
Of course we need to check all plugins/SDKs for the correct behavior.

**Comment by cornelinux** [comment]
> If we receive a (POST-) request with the content type application/x-www-form-urlencoded we must assume,

The requirement to an assumption is the beginning of the downtime ;-)

I am not talking about LWP module or whatsoever.

I am talking about people who develop arbitrary plugins in an uncommon way and maybe send `form-urlendoded` but do not encode.

Having  such a mapping would enable us, if a "customer" uses a broken 3rd party plugin to solve this problem in the server, without touching the untouchable 3rd party plugin.

**Comment by cornelinux** [comment]
Need to rediscuss

**Comment by cornelinux** [comment]
The decoding happens in api/lib/utils.py here:
https://github.com/privacyidea/privacyidea/blob/93b7aa9896f3714cab47d9f0d4ce35a5a75fa67b/privacyidea/api/lib/utils.py#L241

We would have to make all "unquote" calls configurable.

**Comment by plettich** [comment]
We can create a function to check whether unquoting is necessary.
In a first iteration, this function could check the client application of the request. Later we can add unquoting based on IPs or client versions.

**Comment by plettich** [comment]
merged into master in 66d4a7b0
