### ISSUE TITLE
"pi-manage ca create myca" creates directory and files with wrong ownership

### ISSUE THREAD

**Issue by TheTesla** [privacyidea/privacyidea#3340]
### Top-level intent

creating a new local CA

### Steps to reproduce

```bash
cd /etc/privacyidea/CA
pi-manage ca create myca # answer all question with defaults
cd ca
ls -halt 
```

### Expected outcome

The directory ``/etc/privacyidea/CA/ca`` and all files in it should owned by _privacyidea_.

### Actual outcome

The directory ``/etc/privacyidea/CA/ca`` and all files in it are owned by _root_.

### Configuration

* **privacyIDEA 3.6.2**:
* **Installation method**: apt (``add-apt-repository http://lancelot.netknights.it/community/focal/stable``)
* **Python version**: 3.8.10
* **Operating system**: Ubuntu 20.04.3 LTS
* **Webserver**: apache2 (Version: 2.4.41-4ubuntu3.9)
* **Token database**: MySQL

**Comment by cornelinux** [comment]
Honestly, I think this would be too prone to errors.

If you run the command as root, files will be created as root. It is not safe to know, under which user actually the privacyIDEA webapplication will be running.

**Comment by cornelinux** [comment]
@NNLemling We would simply add a warning in the output - "Be sure to set the access rights...".
Similar to what we have in `pi-manage create-enckey...`.
