### ISSUE TITLE
Empty required fields in "Create a new Local CA Connector" moves CA list/edit part to unusable state

### ISSUE THREAD

**Issue by TheTesla** [privacyidea/privacyidea#3342]
### Top-level intent

add new local ca connector

### Steps to reproduce

1. access ``https://mypiinstance.example/#!/config/caconnectors/local`` in browser
2. fill out "Connector name" field or let it empty
3. click "Save CA"

### Expected outcome

Dismiss creation of CA or better: create an inactive/draft CA. The second solution should not be a problem. If the database entries for one CA are incomplete, listing and editing CAs should work. Only the complete configured CAs should be selectable for token creation. 

### Actual outcome

CA is created with required database entries missing. This should not be a problem, but if the database entries for at least one CA is incomplete, listing and editing CAs fails. This happens on web-ui and on pi-manage cli. - This can only be repaired by manually deleting the incomplete CAs from the database.

### Configuration

* **privacyIDEA 3.6.2**:
* **Installation method**: apt (``add-apt-repository http://lancelot.netknights.it/community/focal/stable``)
* **Python version**: 3.8.10
* **Operating system**: Ubuntu 20.04.3 LTS
* **Webserver**: apache2 (Version: 2.4.41-4ubuntu3.9)
* **Token database**: MySQL

**Comment by TheTesla** [comment]
It is complaining about the 'cakey' field.

**Comment by cornelinux** [comment]
Thanks. Interesting. The field is marked as required, but the save-button does not honour the required fields.
