### ISSUE TITLE
The `user_fields` parameter in `GET /token` is not implemented

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3343]
The documentation of the `GET /token` API describes a `user_fields` parameter:
https://privacyidea.readthedocs.io/en/master/modules/api/token.html#get--token-
This parameter is currently not used:
https://github.com/privacyidea/privacyidea/blob/756116fbef9f7790138f54ddb6ff858e76249fa0/privacyidea/api/token.py#L444

We should either update the API docs or implement this feature (if this means the `userinfo` we would need to query every user for all matching tokens).

**Comment by cornelinux** [comment]
This is actually from January 2015. Very originial. It could be that I simply remove this functionality right from the start.
Also I am currently not sure, what to do with that.
