### ISSUE TITLE
Firebase: Remove requirement of app parameters

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#3352]
In the Firebase SMS Gateway, it is still required to enter the parameters that were once needed for the app. Since our app now includes the google-services.json, the server does not need to know these values and should be fine with the access file alone.
=> The only required parameter for the server should be the json config file.

**Comment by cornelinux** [comment]
@nilsbehlen  Wait: What about customized smartphone apps with individual firebase projects. Is this contained in the json config file? Probably not. 
So there should be something like "use default firebase" or "use individual firebase"?

# Todo

* [ ] adapt firebase config
* [ ] adapt config
* [ ] remove unneccessary values from the QR code.

**Comment by nilsbehlen** [comment]
Each custom app will have their firebase info compiled into them, so the server only need the json file (service account).
The app (custom or not) does not need any external info about where it's firebase project is.
