### ISSUE TITLE
Owncloud with JSXC

### ISSUE THREAD

**Issue by Luticus** [privacyidea/privacyidea#336]
This system works pretty well with owncloud except it basically breaks logins for the Javascript XMPP client.  I don't suppose there's a way around this somehow but I thought I'd point this out in case anyone had any ideas.  Really want to use this plugin with my OC but chat is critical to me.

**Comment by cornelinux** [comment]
Owncloud sucks as far as authentication is concerned. In many client scenarios it lets the client cache the credentials instead of getting a session. 
Please file an according but at owncloud!
