### ISSUE TITLE
Self-service policy. Possibility to choose multiple sha algorithm

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3369]
In the self-service policy. It is only possible to choose sha1 OR sha 512 OR sha 525. 
Is it be possible to have the possibility to choose one or two algorithms.
 For example, sha512 and sha 256.

**Comment by cornelinux** [comment]
Come on. Really?

This is ridicolous. If the users are that educated to choose a hash algorithm they can always choose between sha1, sha256 or sha512. 

This is not worth it.
