### ISSUE TITLE
choose crypto module

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#337]
We are using PyCrypto for signing and encryption.

And we are using pysaml2 for the SAML SP.

This only works with pysaml2 <= 4.0.0
Higher pysaml2 modules require pycryptodome, which replaces pycrypto and is not compatible. You can not run pycrypto and pycryptodome in the same environment.

If we switch from pycrypto to pycryptodome, we need to change all the signing and encryption in privacyidea.lib.crypto.

See https://github.com/rohe/pysaml2/issues/304

**Comment by plettich** [comment]
[PyCrypto](https://github.com/dlitz/pycrypto/) is effectively [dead](https://github.com/dlitz/pycrypto#238).
[pycryptodome](https://github.com/Legrandin/pycryptodome) provides a compatibility layer to function as a drop-in replacement for PyCrypto but in our case it does not work out of the box.
pycryptodome can be installed in its own namespace/module as well and thus be installed together with PyCrypto (https://github.com/Legrandin/pycryptodome#pycryptodome).
BTW: meanwhile pysaml2 switched to [pyca/cryptography](https://github.com/pyca/cryptography).

**Comment by cornelinux** [comment]
I have the feeling we should go for cryptography. In my opinion, we do not need a drop-in. We can rewrite our  complete [lib/crypto.py](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/crypto.py). If we wrap nearly everything into our own ``lib/crypto.py`` we can also assure #1212.

**Comment by fredreichbier** [comment]
pyca/cryptography looks cool! But will backwards-compatibility be a problem? (e.g. using pyca/cryptography to verify audit entries signed using pycrypto).

**Comment by cornelinux** [comment]
Of course we should check this. After all, the signed audit entries are RSA signatures. So it *should* not matter, which implementation we will use. (I would be very well puzzled if it would not).

(Hey I can not verify your signed email with my thunderbird, since you sent it with kmail - very unlikely)
(Hey I can not verify your signed email with my kmail, since you sent it with outlook - oups, migh happen ;-)

**Comment by plettich** [comment]
Actually the signature is usually calculated using the non-standard RSA signature, not the RSA-based PKCS1-v1.5 signature scheme.
It should still be possible to calculate the signature using just RSA but we might have to dig deep into the libraries.

**Comment by cornelinux** [comment]
We are already using *pyca/bcrypt* so why not use *pyca/cryptography* +1

**Comment by cornelinux** [comment]
We also need to consider #1212 with this issue.

**Comment by cornelinux** [comment]
@plettich @fredreichbier Should we drop the pkcs11-security-module?
I think noone uses it. It is not a rather sensible way to use assymmetric crypto in the HSM. Everyone would use the aeshsm. So why should we keep badly maintained code, that is not used?

**Comment by plettich** [comment]
I always support removing unused/unmaintained code but i must admit, i have no overview on who is using what. So if @cornelinux says it is unused i am in favor of removing it.

**Comment by fredreichbier** [comment]
Sounds sensible to me, +1 for removing it! :)

**Comment by cornelinux** [comment]
Nice. @plettich would you then please remove this one https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/security/pkcs11.py

(I thought of mor modularity. We might introduce this module one day in its own repo again...)
