### ISSUE TITLE
Token enrolment PIN or Password

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3370]
On the page to enrol a token.

The title of the pin Field is «PIN»
Just under it is written: «Type a password» and «Repeat password»

Could it be possible to unify title and subtitles because some end users are disturbed and don't know what to enter the PIN or the Password.

The solution would be to Display 
PIN
Type a PIN
Repeat PIN

**Comment by cornelinux** [comment]
I understand your point of unifying it.
However, I saw users disturbed this way, that they think they could only use digits in the PIN.

So it might be better to unify it in this way, to write password ;-)

**Comment by cornelinux** [comment]
In the UI we should make the user understand that this could contain alphanumeric and special chars depending on the policies.
I would not only name it PIN!

I still prefer "Type a password". Or this should be something like "Type a PIN or password". It should not be "Type a PIN".

Or we simply close this issue.

@sepp67 What do you think?

**Comment by cornelinux** [comment]
Other people do it this way:

![image](https://user-images.githubusercontent.com/1908620/221346006-b8d75c59-97c4-4ded-b255-fea1dee6377a.png)

This sounds sensible to me.

**Comment by sepp67** [comment]
Yes password/Pin is a good solution. Everybody is understanding that he can put a pin or a password.

**Comment by cornelinux** [comment]
@NNLemling So please change the naming of the Field to PIN/Password.
