### ISSUE TITLE
Preferred client mode in triggerchallenge

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3373]
Hi @nilsbehlen,

do I get this right, that we also need to add the preferred client mode to triggerchallenge calls /well triggerchallenge responses?

If so, we need to add this:

~~~~python
@postpolicy(preferred_client_mode, request=request)
~~~~

here:

https://github.com/privacyidea/privacyidea/blob/951325114a8f58f51875d148d663e0a565c5545f/privacyidea/api/validate.py#L433

(At least I think so)

**Comment by cornelinux** [comment]
@nilsbehlen Are we correct, that we also need to add the preferred_client_mode to the response of triggerchallenge.

**Comment by nilsbehlen** [comment]
Yes, but also when `/validate/check` returns a `multi_challenge`.

**Comment by nilsbehlen** [comment]
So i think it would be best if `preferred_client_mode` was part of `multi_challenge`
