### ISSUE TITLE
Webauthn enrollement not working with PyPI 3.7.4 Version

### ISSUE THREAD

**Issue by mkrenn1** [privacyidea/privacyidea#3377]
### Top-level intent
Enroll a webauthn token after upgrade to 3.7.4 via PyPI. 

This is not working for me as i get a Javascript Error.

undefined / Failed to execute 'create' on 'CredentialsContainer': Failed to read the 'publicKey' property from 'CredentialCreationOptions': Failed to read the 'pubKeyCredParams' property from 'PublicKeyCredentialCreationOptions': Required member is undefined.

undefined / CredentialsContainer.create: Missing required 'pubKeyCredParams' member of PublicKeyCredentialCreationOptions.

As far as i can tell, the PyPI package contains the wrong commit of webauthn-client and pubKeyCredParams Property is not set to anything anymore, as webAuthnRegisterRequest.pubKeyCredAlgorithms is not set via the pyhton application.

Commit to webauthn-client:
https://github.com/privacyidea/webauthn-client/commit/37911536e79b969be01a0fbd40fe80bb9ef6b424#

### Steps to reproduce

1.  Download PIP package of privacyIDEA
2. Unpack and search for String pubKeyCredAlgorithms in files.

Alternative:
1. Setup privacyIDEA and try to enroll a Webauthn token.
2. Look at the enrollment request and error messages.

### Expected outcome

Start the User Agent Webauthn enrollment process.

### Actual outcome

Javascript error about the missing Property for Webauthn enrollemnt request.

### Configuration

* **privacyIDEA version**:  3.7.4
* **Installation method**:  PyPI
* **Python version**: 
* **Operating system**: 
* **Webserver**:  
* **Token database**:

**Comment by cornelinux** [comment]
You are right. The reference to the webauthn client is to new!
You need to use the older one from 3.7.

**Comment by cornelinux** [comment]
We do not plan to fix this in 3.7 pypi.
We are about to release 3.8 in a couple of days, it will be fixed in the new version.
