### ISSUE TITLE
yubikeytoken: can't use pam_yubico - authentication fails

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#338]
When using pam_yubico there are some restriction on the token initialization:
We need to use 6 bytes as prefix, nothing else will work. mass_enroll
should just handle that right, and the webui should check that.

After that authentication still fails, because we don't find the right token in /ttype/yubikey.

My investigations showed, that we store the (internal) uid in the tokeninfo table, but we can't
get back from the prefix to the uid (and from there to the serial number or the token).

The following patch stores the prefix instead of the uid when enrolling a yubikey token in the webui:

--- yubikeytoken.py.orig        2016-03-08 21:09:14.669076518 +0100
+++ yubikeytoken.py     2016-03-08 22:25:26.508837984 +0100
@@ -248,14 +249,14 @@
 
         tokenid = self.get_tokeninfo("yubikey.tokenid")
         if not tokenid:
-            log.debug("Got no tokenid for %r. Setting to %r." % (serial, uid))
-            tokenid = uid
+            log.debug("Got no tokenid for %r. Setting to %r." % (serial, yubi_prefix))
+            tokenid = yubi_prefix
             self.add_tokeninfo("yubikey.tokenid", tokenid)
 
-        if tokenid != uid:
+        if tokenid != yubi_prefix:
             # wrong token!
             log.warning("The wrong token was presented for %r. Got %r, expected %r."
-                        % (serial, uid, tokenid))
+                        % (serial, yubi_prefix, tokenid))
             return -2

Now we'll at least have a chance to get further, but this is something for another day.

**Comment by jh23453** [comment]
Draft patch:
--- yubikeytoken.py.orig        2016-03-08 21:09:14.669076518 +0100
+++ yubikeytoken.py     2016-03-10 00:03:35.966945237 +0100
@@ -252,6 +252,11 @@
             tokenid = uid
             self.add_tokeninfo("yubikey.tokenid", tokenid)
 
+        prefix = self.get_tokeninfo("yubikey.prefix")
+        if not prefix:
+            log.debug("Got no prefix for %r. Setting to %r." % (serial, yubi_prefix))
+            self.add_tokeninfo("yubikey.prefix", yubi_prefix)
+
         if tokenid != uid:
             # wrong token!
             log.warning("The wrong token was presented for %r. Got %r, expected %r."
@@ -379,29 +384,23 @@
         res = False
 
         token_list = []
+        token_candidate_list = []
 
         # strip the yubico OTP and the PIN
-        modhex_serial = passw[:-32][-16:]
-        try:
-            serialnum = "UBAM" + modhex_decode(modhex_serial)
-        except TypeError as exx:  # pragma: no cover
-            log.error("Failed to convert serialnumber: %r" % exx)
-            return res, opt
-
-        # build list of possible yubikey tokens
-        serials = [serialnum]
-        for i in range(1, 3):
-            serials.append("%s_%s" % (serialnum, i))
+        prefix = passw[:-32][-16:]
 
         from privacyidea.lib.token import get_tokens
         from privacyidea.lib.token import check_token_list
-        for serial in serials:
-            tokenobject_list = get_tokens(serial=serial)                                                                                                                                    
-            token_list.extend(tokenobject_list)                                                                                                                                             
+                                                                                                                                                                                            
+        token_candidate_list = get_tokens(tokentype='yubikey')                                                                                                                              
+        for tokenobject in token_candidate_list:                                                                                                                                            
+            token_prefix = tokenobject.get_tokeninfo("yubikey.prefix")                                                                                                                      
+            if prefix == token_prefix:                                                                                                                                                      
+                token_list.append(tokenobject)                                                                                                                                              
                                                                                                                                                                                             
         if not token_list:
-            opt['action_detail'] = ("The serial %s could not be found!" %
-                                    serialnum)
+            opt['action_detail'] = ("The prefix %s could not be found!" %
+                                    prefix)
             return res, opt
 
         (res, opt) = check_token_list(token_list, passw)

**Comment by jh23453** [comment]
I got pam_yubico to work with the right entry in ~/.yubico/authorized_yubikeys (user:prefix)

**Comment by cornelinux** [comment]
The cli now sends the prefix in the parameter yubikey.prefix. We need to set this in the update function in the yubikey token as token info.

**Comment by cornelinux** [comment]
Hi Jochen,

I think this was fixed by adapting your pull request and merging it.
Thanks a lot

Cornelius
