### ISSUE TITLE
2.7 and 3.6 not supported on ubuntu-latest in github tests

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3386]
Github seems to have changed "ubuntu-latest" to 22.04.
See: https://github.com/privacyidea/privacyidea/blob/master/.github/workflows/python.yml#L19

Thus our tests for 2.7 adn 3.6 fail, since these versions are not available for 22.04.
So we either need to revert to 20.04 or we need to run 3.6/2.7 explicitly on 20.04 and all other on 22.04.

**Comment by plettich** [comment]
We can just switch to 20.04 completely until we remove support for Python 2.7 and 3.6.
Python 3.11 and 3.12 will also run on 20.04

**Comment by jona-samuel** [comment]
I got this error:
Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
in Python 3.6 test
https://github.com/privacyidea/privacyidea/actions/runs/3647243322/jobs/6159244754
