### ISSUE TITLE
disabling one token, avoids authentication with the 2nd token

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#339]
policy: scope=authentication, action: **otppin=userstore**

The user has two tokens. One of the two tokens is disabled.
The authentication of the user fails with the reason: token disabled.

As both tokens are using the same OTP PIN (a.k.a. the userstore password) both tokens should be checked. The disabled token should be ignored and the active token should be checked. The authentication with the active token should be possible

**Comment by berndnicklas** [comment]
Hello,

back from vacation I had a chance to take a closer look at the problem:

- The login failure is only raised by revoked tokens, not by disabled tokens.
- Also, the failure is only raised using the self-service-login. The validation api itself works without problems.
- A single revoked user token leads to the error message ```"Authentication failed. ERR1007: This action is not possible, since the token is locked"```, no matter the user has additional active tokens or just this single revoked token and passthru authentication enabled.

privacyIDEA version: 2.11 and 2.10
scope: authentication
action: {u'passthru': True, u'otppin': u'userstore'}

Can anyone reproduce this problem?

Best regards,

Bernd

**Comment by cornelinux** [comment]
Hello Bernd,

thank you for being so persisting. 
I can confirm the following:

I tested with otppin=token.
If the user has a locked token he can not login to self service anymore. In my case he also can not authenticate via the API, which makes sense to me, since it is the same code.
This happens even if the active token and the locked token have **different** OTP PINs.

Thanks a lot 
Cornelius
