### ISSUE TITLE
Objects can not be named "." and ".."

### ISSUE THREAD

**Issue by maxbeth** [privacyidea/privacyidea#3409]
version: master branch
If i create a policy with "." or ".." the networkprotocol  throw an error
 "POST /policy/ HTTP/1.1" 405 -  Method not allowed

The frontend shows "Keine valide JSON-Antwort vom privacyIDEA Servers erhalten."

The names "." and ".." should be banned

**Comment by cornelinux** [comment]
I am not sure about how would be the nicest way to cope with that.
Or simply provide a better note for a 405 error.

The problem is with all endpoints, that use the name of the object as part of the URL.

Could be we should adhere to the concept of shit-in-shit out. I like that! ;-)

**Comment by cornelinux** [comment]
We can add this to the pattern regex.

**Comment by jona-samuel** [comment]
I changed the pattern regex. The webUI will no longer accept names that start whit ".".
