### ISSUE TITLE
reload triggers multiple retrieval

### ISSUE THREAD

**Issue by maxbeth** [privacyidea/privacyidea#3421]
version: master
In the privacyidea/static/components/config/states/states.js some controllers are registered several times.
Therefore the reload function (left next to the logout) or init trigger some controller more then once
 eventController
 eventDetailController
 periodicTaskController
 periodicTaskDetailController
 privacyideaServerController
 radiusServerController
 smsgatewayController
 smtpServerController
 tokengroupController

**Comment by cornelinux** [comment]
You mean like here?

~~~~
.state('config.events', {
                    url: "/events",
                    templateUrl: configpath + "config.events.html" + versioningSuffixProviderProvider.$get().$get(),
                    controller: "eventController"
                })
.state('config.events.list', {
                    url: "/list",
                    templateUrl: configpath + "config.events.list.html" + versioningSuffixProviderProvider.$get().$get(),
                    controller: "eventController"
                })
~~~~

In AngularJS this is neccessary to define, which controller is responsible for which state.
So I currently see no easy way around it at first glance.
