### ISSUE TITLE
0 user objects found

### ISSUE THREAD

**Issue by borschoff** [privacyidea/privacyidea#343]
Hello Cornelius!

Can LDAPresolver import users from "Base DN" like "**CN=Group**,OU=groups,DC=beta,DC=alfa"?
When i use Base DN: "**OU=Group**,OU=groups,DC=beta,DC=alfa" it's ok. And if i use **CN=Group** resolver cant import users.

What i've done wrong?
Should I use special user\search filter or other options?

Please, help.

**Comment by cornelinux** [comment]
This is an interesting question, which probably is better located on the google group:

https://groups.google.com/forum/#!forum/privacyidea

The point is, that probably CN=Group,OU=groups,DC=beta,DC=alfa of yours is an LDAP group object. I.e. this is not a container or OU, that contains user objects.

The users in your CN=Group are attributes to this group object.

No, privacyIDEA can not read those users.

As this looks like Active Directory and not like OpenLDAP you probably have another chance: THe uses you want to find obviously contain the attribute

   memberOf="CN=Group,OU=groups,DC=beta,DC=alfa

Check this out! And then you can create an LDAP userfilter and find all the users in this very group.

**Comment by borschoff** [comment]
Thank you for response!
I have started new thread in https://groups.google.com/forum/#!forum/privacyidea
