### ISSUE TITLE
Challenge Response handling at /auth endpoint not consistent

### ISSUE THREAD

**Issue by lukasmatusiewicz** [privacyidea/privacyidea#3436]
Hi,
we are trying to implement 2fa in smartcard-client which is using `POST /auth` endpoint to authenticate in privacyIDEA.

Scenario: The user is sending just a PIN without OTP and awaits, that privacyIDEA will ask for the OTP in the next step.
Response: The server triggers the challenges and asks for OTP in the message, but at the same time it encounters an error: 4031.

The PI response looks as follows:

~~~~json

 "detail": { 
       "client_mode": "interactive", 
       "loginmode": "privacyIDEA", 
        "message": "please enter otp: ", 
        "messages": [ "please enter otp: " ], 
        "multi_challenge": [ 
                      { "client_mode": "interactive", "message": "please enter otp: ", "serial": "OATH00159D24", "transaction_id": "13606...996141", "type": "hotp" } ], 
           "serial": "OATH0...9D24", 
             "threadid": 13999...8608, 
             "transaction_id": "136062...90996141", 
             "transaction_ids": [ "136062...0996141" ], 
              "type": "hotp" }, 
"id": 1, 
"jsonrpc": "2.0", 
"result": { 
       "error": { "code": 4031, "message": "Authentication failure. Wrong credentials" }, 
       "status": false },`
~~~~

https://github.com/privacyidea/smartcard-client-windows/issues/6

**Comment by plettich** [comment]
Actually, challenge-response works with the `/auth` endpoint quite well. Just ignore the error and send the OTP value with a second `/auth` request and the the `transaction_id`.
The Problem is, that we throw an error if we do not have a proper authentication at the end of the `/auth` request.
There is already an old issue open: #1192

**Comment by plettich** [comment]
The UI needs to be updated for the changed `/auth` response:
Most of the code in the whole error handling function 
https://github.com/privacyidea/privacyidea/blob/13565489141f81b61e8b9803df9358741d9269f0/privacyidea/static/components/login/controllers/loginControllers.js#L241
needs to go into the regular response handling here:
https://github.com/privacyidea/privacyidea/blob/13565489141f81b61e8b9803df9358741d9269f0/privacyidea/static/components/login/controllers/loginControllers.js#L236
Only the *show error message* code should remain in the error handler:
https://github.com/privacyidea/privacyidea/blob/13565489141f81b61e8b9803df9358741d9269f0/privacyidea/static/components/login/controllers/loginControllers.js#L356

**Comment by cornelinux** [comment]
Ideally the /auth endpoint and /validate/check endpoint would behave similar.

FYI: The current behaviour of the /validate/check endpoint is:

If the challenge is answered with a wrong OTP value, but the challenge is still valid, we send the return:

~~~~json
    "detail": {
        "message": "Response did not match the challenge.",
        "serial": "OATH00982F86",
        "threadid": 140410094376768,
        "type": "hotp"
    },
    "id": 2,
    "jsonrpc": "2.0",
    "result": {
        "authentication": "REJECT",
        "status": true,
        "value": false
    },
~~~~

See `result->authentication: REJECT`. The application itself needs to know, that it is in a challenge state. 

However, if the challenge has *exired* and the client still sends the same requestion like:

    http --verify no POST https://localhost:5000/validate/check user=paula pass=12312 transaction_id=10320324977315713974

we get the same result, the same `message` and the same `"authentication": "REJECT"`. This is sine the client claims with the transaction_id that it wants to anwer a challenge (which does not exist anymore).

This is the current behaviour `/valdiate/check`. I currently do not want to do a design decision to *change* this behaviour of the server.

So the question is, if the login should revert to the first login step, anyways.
