### ISSUE TITLE
/auth request with missing password parameter results in an internal server error

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3438]
When calling the `/auth` endpoint without providing a `password` parameter (which isn't required, since the authentication can also be done by the webserver) results in a 500 internal server error.
The missing parameter is passed through until it fails here:
https://github.com/privacyidea/privacyidea/blob/fd4888ee9a76ea3c2f15425f9e55d5c06c95d4c5/privacyidea/lib/utils/__init__.py#L1289-L1288

We should check, where we can test the parameter and fail gracefully without breaking existing login scenarios.

**Comment by cornelinux** [comment]
Since the password-parameter is not required, this password could be "None".

There are different ways to handle this and currently it is not straightforward, how we would want to do this.

1. check if password is required, but missing
2. Password or "", to ensure that a None password is handled as an empty string.

**Comment by plettich** [comment]
We should check for a missing `password` parameter here:
https://github.com/privacyidea/privacyidea/blob/49f64d01b2bffeacabeac721a405d46d9a62725d/privacyidea/api/auth.py#L310
At this point the external authentication and the internal admin authentication are already done.

**Comment by jona-samuel** [comment]
@plettich This will change the result if someone tries to log in with the wrong remote user. At this point, he gets the messing "Authentication failure. Wrong credentials", the error code: 4031 and the status code 401.
After the changes, he will get the message "ERR905: Missing parameter: 'password'", the error code 905 and the status code 400.

**Comment by plettich** [comment]
You should not change the first `getParam()` here:
https://github.com/privacyidea/privacyidea/blob/49f64d01b2bffeacabeac721a405d46d9a62725d/privacyidea/api/auth.py#L218
instead add another `getParam()` (this time with `optional=False`) here:
https://github.com/privacyidea/privacyidea/blob/49f64d01b2bffeacabeac721a405d46d9a62725d/privacyidea/api/auth.py#L303
At this point a password is required. We could also check for `if not password` here but `getParam()` already throws the correct error with an appropriate message.

**Comment by jona-samuel** [comment]
This is exactly what I've done, but this has the machined side effects. You can see the difference in the changed tests in the pull request. #3572

**Comment by jona-samuel** [comment]
We got a problem with the challenge-response token because there is no given password in the second challenge. So we have to find another point to check for the existence of a password.
