### ISSUE TITLE
2 possible image fields in the challenge

### ISSUE THREAD

**Issue by lukasmatusiewicz** [privacyidea/privacyidea#3445]
Hi,

as I see, the server response has 2 image fields. One is called `image` (new, to show the QR Code) and another called `img`, which can contain any image assigned to the given challenge.

Can you consider using only one field for both of these? That will make our work easier and cleaner. And though, by token enrollment, we don't need to show any other image than this QR Code. E.g.: `if "qrcode" is not empty -> replace the "img"`

Or maybe I miss something?

**Comment by cornelinux** [comment]
You are right, sometimes there is the tag "img" (old) and then the tag "image"  (new).
But these are in quite different situations.

If a "normal" /token/init/ enrollment is used, the tag is "img" for very old historical reasons.

If the enrollment via /validate/check happens, the challenge data contains an "image" tag according to #2993.

But to my understanding, these should never happen at the same time.
Or am I missing something?

**Comment by lukasmatusiewicz** [comment]
It seems, that the "img" tag can be used to store an icon for the challenge. E.g.:
`"\"img\": \"static/img/FIDO-U2F-Security-Key-444x444.png\",\n"`

**Comment by plettich** [comment]
We could rename the `img`  entry to something like `icon` but i would prefer not to rename the `image` entry since this could break existing processes.

**Comment by lukasmatusiewicz** [comment]
It looks like the image is not contained in the multichallenge section: https://github.com/privacyidea/privacyidea/issues/2993

**Comment by lukasmatusiewicz** [comment]
Ok. I've tested that and the `image` tag is there in the challenge.

Summary:
`img` is an old tag that should be ignored.
`image` contains a proper "dataimage" for the challenge. It is prepared to forward not only a QR Code, but also an icon, or any other image to show in UI.
