### ISSUE TITLE
Add webauthn to preferred_client_mode

### ISSUE THREAD

**Issue by jona-samuel** [privacyidea/privacyidea#3459]
Webauthn is missing in preferred_client_mode.

Also, we have to check the list of client_modes in the documentation

**Comment by cornelinux** [comment]
This is contained.
https://github.com/privacyidea/privacyidea/blob/d166281ce3fc226242952be9384814d78fa0d3c2/privacyidea/lib/policy.py#L207https://github.com/privacyidea/privacyidea/blob/d166281ce3fc226242952be9384814d78fa0d3c2/privacyidea/lib/policy.py#L207

Please clarify if and which problem exist.

**Comment by lukasmatusiewicz** [comment]
Yeah, I have tested it and it works fine. Webauthn too. Closing this one.
