### ISSUE TITLE
yubicotoken: sign the request sent to yubico 

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#346]
From my reading of the code we do not sign the request.
The signing is implemented in my patch to yubikeytoken.py, it should be
possible to use something similar here or refactore to use the same function.
The signing goes here (line 160):
156             nonce = binascii.hexlify(os.urandom(20))
157             p = {'nonce': nonce,
158                  'otp': anOtpVal,
159                  'id': apiId}
160 
161             try:
162                 r = requests.post(YUBICO_URL,

Here we check the signature from yubico - and use code similar to what is in yubikeytoken.py.
I think it would be helpful to have a function usable for both token:

179                     for elem in elements:
180                         elem = elem.strip('\n')
181                         if elem and elem[:2] != "h=":
182                             hash_elements.append(elem)
183 
184                     hash_input = '&'.join(sorted(hash_elements))
185                     hashed_data = binascii.b2a_base64(hmac.new(
186                                                                binascii.a2b_base64(apiKey),
187                                                                hash_input,
188                                                                sha1).digest())[:-1]
189 
190                     if hashed_data != return_hash:
191                         log.error("The hash of the return from the Yubico "
192                                   "Cloud server does not match the data!")

**Comment by cornelinux** [comment]
To me it sounds you do not want to sign the request but you want to verify the signature/hash of the response? Which also makes more sense to me? ...or both?

We could move the function
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/yubikeytoken.py#L312
from being a static class function to a top level function in the module.

Then we could import the function into yubicotoken.py.

Is this the way you think about it?

**Comment by jh23453** [comment]
Cornelius Kölbel <notifications@github.com> writes:

> To me it sounds you do not want to sign the request but you want to
> verify the signature/hash of the response? Which also makes more sense
> to me? ...or both?

Sign the request and verify the signature.
>
> We could move the function
> https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/yubikeytoken.py#L312
> from being a static class function to a top level function in the module.
>
> Then we could import the function into yubicotoken.py.
>
> Is this the way you think about it?

Yes, something like that.

Jochen

-- 
The only problem with troubleshooting is that the trouble shoots back.
