### ISSUE TITLE
Make LDAP server pooling strategy configurable

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3461]
Currently when creating a new LDAP server pool the pooling strategy is Round-Robin:
https://github.com/privacyidea/privacyidea/blob/f707149f42805ad34df56beb1e02168db6577758/privacyidea/lib/resolvers/LDAPIdResolver.py#L933
We could make this configurable:
https://ldap3.readthedocs.io/en/latest/server.html#server-pool

**Comment by cornelinux** [comment]
This would be an additional value in the ldap resolver config.

We could make the dropdown only visible, if the server URI actually contains a comma, which means there is more than one server.
