### ISSUE TITLE
Response from the server in html doc form

### ISSUE THREAD

**Issue by lukasmatusiewicz** [privacyidea/privacyidea#3463]
Sometimes, if the privacyIDEA server is overloaded, the response contains an HTML data and looks as follows:

![grafik](https://user-images.githubusercontent.com/77617779/212674721-ef942e50-557a-4cd9-a5d5-c5542a0718c6.png)

That form of the response doesn't meet the JSON format requirements and causes the following JsonSyntaxException:

` ERROR [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (executor-thread-37) PrivacyIDEA Client: : com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $`

We can try to handle it in the above-proposed way (`Use JsonReader.setLenient(true) to accept malformed JSON`), but probably it won't look good in the UI, and it's pretty hard to reproduce this exception to test it in real.

Is it possible to handle this problem on the server side..? If not, I'll look closely to find a clue on the client side.

**Comment by plettich** [comment]
This looks like a failure of the webserver itself, there is probably nothing we can do in privacyIDEA.
Each request to the API should be checked if the return code is `200` before doing anything with the received data.
(Except of course the `/auth` request... See #3436 :-))
It is always a good idea to check the privacyIDEA and httpd server logs for more information on why the error occurred.
