### ISSUE TITLE
PI_VASCO_LIBRARY Error message in the log

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3470]
When the Vasco library is not installed, there is often an error message in the logs
[5205][140608434493184][INFO][privacyidea.lib.tokens.vasco:56] PI_VASCO_LIBRARY option is not set, functionality disabled

Is it possible to disable this error message when the Vasco token is not used ?

Kind regards
sebastien

**Comment by cornelinux** [comment]
Interesting idea.
I understand this this message is annoying.

**Comment by plettich** [comment]
Just changing the log message to "debug" should be enough
