### ISSUE TITLE
Enrol a registration token when an email or phone number is updated by the user.

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3491]
The function ¨verify email¨ in keycloack, generates a link that is sent via SMS or E-mail to the user when he is login in for the first time or when he changes his e-mail or phone number.

https://www.keycloak.org/docs/latest/server_admin/#con-required-actions_server_administration_guide
Look at: Defining actions required at login --> verify email

Is it possible that the Privacyidea server is sending a token Via SMS or E-mail to a user when he changes his e-mail or phone number ?

**Comment by cornelinux** [comment]
In privacyIDEA you can not change the phone number or email address of a token.
If the user has a new phone number, then within privacyIDEA a new token needs to be enrolled.

If this is a token with `dynamic_phone` we fetch the phone number from e.g. AD. But if the phone number is managed in AD, it is the task of AD.

@basvandervlies What is the original intent and scenario here?

**Comment by basvandervlies** [comment]
Hi @cornelinux,

  Is not about privacyidea but a suggestion for the privacyidea keycloak plugin and the Keycloak Authentication. If you look under https://<keycloak_server>nl/admin/master/console/#/master/authentication/required-actions. You see list of 
Required Actions that can be set on an user. eg:
 * Very Email
 * Configure OTP (is keycloak OTP)
 * Update Password
 * ...

When I read it it was more appropriate to add a required Action: "Configure Privaccyidea TOTP". When this is set a token must be enrolled and if successful the action is deleted. Now it is part of the Authentication workflow.

Now what  SURF wants/suggests is an "Privacyidea Verify Mobile" action that creates a registration token and send this to the mobile number that is also available in privacyidea via our openldap cluster.  The user enters the response and if successful the registration token is deleted and the required action will be removed from the user.

The actions are set by our tools. we already do this for verify email. When the email has been changed an keycloak action  is set.  When the user  authenticate against keycloak server the new email addres is being checked .  We want the same setup for mobile numbers. 

Hope this explains what we want.

**Comment by cornelinux** [comment]
@basvandervlies 
If I understand this correctly. this is all possible with event handlers in the privacyidea server.
By privacyIDEA design concepts this special feature should not be implemented in any plugin.
This issue can be closed.
