### ISSUE TITLE
multiselect policies in webUI

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3493]
Since we now have a multiselect in policies, we could adapt some policies like

* challenge_response
* ...

That already take a list of e.g. tokentypes.
Since the multiselect and the existing policy both save this as a whitespace separated list, this should simply be an adaption of the policy definition here:
https://github.com/privacyidea/privacyidea/blob/d166281ce3fc226242952be9384814d78fa0d3c2/privacyidea/lib/policy.py#L2237

To generate the list of tokenclasses for the multiselect we could use a check of the class attribute "mode" to see if this can be a challene response token.

**Comment by NNLemling** [comment]
~~~ python    
def challenge_response_wrapper(*args, **kwds):
        options = kwds.get("options", {})
        g = options.get("g")
        token = args[0]
        passw = args[1]
        clientip = options.get("clientip")
        user_object = kwds.get("user", User())
        if g:
            policy_object = g.policy_object
            allowed_tokentypes = policy_object.get_action_values(
                action=ACTION.CHALLENGERESPONSE,
                scope=SCOPE.AUTH,
                realm=user_object.realm,
                user=user_object.login,
                client=clientip)
            log.debug("Found these allowed tokentypes: %s" % allowed_tokentypes)

            # allowed_tokentypes is a list of actions from several policies. I
            # could look like this:
            # ["tiqr hotp totp", "tiqr motp"]
            # We need to create a upper case list of pure tokentypes.
            token_list = " ".join(allowed_tokentypes)
            token_list = token_list.split(" ")
            # uniquify
            token_list = list(set(token_list))

**Comment by plettich** [comment]
Actually we nee need to support policy actions written with capital letters to avoid breaking old installations.
The idea would be to change the entries in `allowed_tokentypes_dict` to lower case [here](https://github.com/privacyidea/privacyidea/blob/d6a63494b2894290adff39a4aa6f82df7fe7be43/privacyidea/lib/policydecorators.py#L127).
Also the loop [here](https://github.com/privacyidea/privacyidea/blob/d6a63494b2894290adff39a4aa6f82df7fe7be43/privacyidea/lib/policydecorators.py#L126) is not necessary.
