### ISSUE TITLE
Policy conditions on token breaks with non object

### ISSUE THREAD

**Issue by katgirl** [privacyidea/privacyidea#3494]
We would like to test whether tokens already exist or not. 
Then we found the condition. 
https://privacyidea.readthedocs.io/en/latest/policies/conditions.html

Unfortunately we didn't get any further, because the condition token aborts with the note that no object exists.

What exactly this is I can not judge. However, it would be nice to be able to check this.

To explain: We would like to use this to enable two logins on the same userrealm. 

Rollout Initial-Token
```
{ 'action': { 'default_tokentype': 'tan',
                                    'login_mode': 'userstore',
                                    'tokenwizard': True},
                      'active': True,
                      'adminrealm': [],
                      'adminuser': [],
                      'check_all_resolvers': False,
                      'client': [],
                      'conditions': [('token', '', '!equals', '', True)],
                      'name': 'initial-token',
                      'pinode': [],
                      'priority': 4,
                      'realm': ['students'],
                      'resolver': ['students-users'],
                      'scope': 'webui',
                      'time': ''
                      'user': []},
```
Default login
```
{ 'action': { 'login_mode': 'privacyIDEA'},
                      ``active'': True,
                      'adminrealm': [],
                      'adminuser': [],
                      'check_all_resolvers': False,
                      'client': [],
                      'conditions': [('token', '', 'equals', '', True)],
                      'name': 'default,
                      'pinode': [],
                      'priority': 3,
                      'realm': ['students'],
                      'resolver': ['students-users'],
                      'scope': 'webui',
                      'time': ''
                      'user': []},
```

**Comment by cornelinux** [comment]
What do you want to achieve?
I think this question might be better on the community forum at https://community.privacyidea.org.

You are misunderstanding the extended policies.
You conditions do not make sense.

The policy action "loginmode" can not work with a token condition, since at this point no token information is avilable.

So again the question is, what do you want to achieve, but this would better be located at the forum.

**Comment by katgirl** [comment]
Thank you, I tried to set in the forum. Currently I am still waiting for the release.
