### ISSUE TITLE
MS CA serial number in privacyidea

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#3498]
Certs that are enrolled via the MS CA are assigned a separate privacyidea serial which does not match the serial that the CA assigned for the cert.
It might be good to have the CA serial visible on the token info page or to use the serial that was assigned by the CA in privacyidea too.

**Comment by cornelinux** [comment]
OK, you are right. We have currently the requestID in the tokeninfo, not the serial number. Anyway @nilsbehlen your use case would be interesting.

**Comment by nilsbehlen** [comment]
I do not have a particular use case currently. I was just thinking that it is hard to match the the cert on a device with the corresponding token in privacyidea, especially if there are multiple certs on a device. Likewise, in the smartcard client, communication with privacyidea is required to make that match because the device will only give us the cert for each slot and not the privacyidea token serial.
But this was only an idea.

**Comment by nilsbehlen** [comment]
we can get the serial out of the certificate, as it is done in the revocation with the ms ca connector.
