### ISSUE TITLE
Enhance GET /token/ API for filtering for enrolled rollout_states

### ISSUE THREAD

**Issue by camelusferus** [privacyidea/privacyidea#3517]
### Top-level intent

When you're using ``verify_enrollment`` policies for tokens (e.g. TOTP), you might check the GET ``/token/`` API endpoint with the ``rollout_state`` filter when integrating, so only when the user has verified tokens you'll prompt him for the second factor. If you then have other token types (e.g. here HOTP), which don't have this policies, you have no option to check via the GET ``/token/`` API endpoint and filter only for enrolled tokens.

The [glossary in the docs](https://privacyidea.readthedocs.io/en/master/glossary/index.html?highlight=rollout_state#term-Rollout-State) states that sometimes the rollout state can be empty despite being in an enrolled state, but the API doesn't follow this logic.

### Steps to reproduce

1. Issue a enrollment policy with the ``verify_enrollment`` parameter set to ``totp``
2. Enroll 3 tokens to an user (previously without tokens):
   - a TOTP one, which you verify
   - a TOTP one, which you don't verify
   - a HOTP one (which you can't verify, as no policy is set)
3. Query the ``/token/`` API call for the user, with the ``rollout_state`` filter set to ``enrolled``

![screenshot from PI](https://user-images.githubusercontent.com/45562862/217603021-686c573e-9f22-4d00-a08f-a522314d8058.png)

### Expected outcome

A response with the the verified TOTP and the HOTP token.

### Actual outcome

A response only  with the the verified TOTP token.

### Configuration

* **privacyIDEA version**: 3.8
* **Installation method**: PyPI
* **Python version**: 3.9.2
* **Operating system**: Debian GNU/Linux 11
* **Webserver**: the testing one (a uWSGI) included with pi-manage
* **Token database**: SQLite

**Comment by cornelinux** [comment]
Your expectation is wrong.

If you filter for "enro", you will only get tokens with the value "enrolled". Not with an empty value.
You could use event handlers to set the rollout_state.

**Comment by cornelinux** [comment]
The filter is an ordinary text filter. 

So it is counter intuitive to return objects with an empty string when search for a certain string.

Suggestion from @plettich: You could create an event handler that set the rollout_state after the HOTP token was sucessfully used for the first time.

If you are fine with that, you are welcome to close this issue. :-)

**Comment by camelusferus** [comment]
My expectation of the internals might be wrong, but from an integration aspect (which I would this endpoint for) I want to know, which token I can offer the user to authenticate with, any while playing with the api I wasn't able to filter for a empty value in the ``rollout_state``, nor for both the empty and ``enrolled`` value.

Thanks for the suggestion with the event handler. That's new to me, I'll take a look, and probably make it work.

Beside that, I would keep this open as a feature request (and with low priority), if that's fine with you, as the logic seems a bit off for me.

**Comment by cornelinux** [comment]
It is for privacyIDEA to decide, which token can be used for authentication. Is is not to decide for any plugin.

The behaviour of the FU Berlin Shibboleth plugin is wrong.

**Comment by camelusferus** [comment]
privacyIDEA should decide which tokens are useable for authentications, but in the end the user (and therefore the integration) should decide which token (from the available ones) he want's to use for the authentication. Thus I would use the ``/token/`` API endpoint.

If I use the ``/validate/triggerchallenge`` endpoint instead of the ``/token/`` one, and the user has a token with some 'push-iness' registered (like a text message), then every time he tries to authenticate, a text is being sent, which is costly for the operator, and annoying for the user, when only used as a backup.
