### ISSUE TITLE
Date: - line in e-mails is not compatible to RFC2822

### ISSUE THREAD

**Issue by mgisbers** [privacyidea/privacyidea#352]
All e-mails from privacyidea don't have a correct Date: - line:

`Date: Tue Mar 29 10:53:46 2016`

This date is generated using `strftime("%c")` which doesn't create RFC2822 compatible dates like:

`Date: Tue, 29 Mar 2016 13:41:12 +0200`

[Python 2 Documentation](https://docs.python.org/2/library/time.html) lists an example how to format RFC2882 Date:-lines.

```
>>> from time import gmtime, strftime
>>> strftime("%a, %d %b %Y %H:%M:%S +0000", gmtime())
'Thu, 28 Jun 2001 14:17:15 +0000'
```

**Comment by cornelinux** [comment]
We should change this and use MIMEText

from email.mime.text import MIMEText

like in privacyideaadm:
https://github.com/privacyidea/privacyideaadm/blob/master/scripts/privacyidea#L249
