### ISSUE TITLE
U2F enrollment in Chrome / Edge not working

### ISSUE THREAD

**Issue by belfhi** [privacyidea/privacyidea#3528]
### Top-level intent
I tried to enroll a u2f token with a yubikey in privacyidea 
using chrome and the 

### Steps to reproduce

1. Start token enrollment of token type u2f
2. wait for blinking yubikey
3. token stuck in 'clientwait'

### Expected outcome

A promt should show up asking to confirm with the device
and then token enrollement is completed by touching the yubikey.

### Actual outcome

Nothing happens. 

In Firefox everything works as expected and the token can be enrolled.
Testing an already enrolled u2f token in chrome also doesn't work.

WebAuthN Tokens work as expected.

### Configuration

* **privacyIDEA version**: 3.8.1
* **Installation method**: PyPI
* **Python version**: 3.10.10
* **Operating system**: debian bullseye
* **Webserver**: nginx
* **Token database**: PostgreSQL

### Log file

There are no errors in `/etc/privacyidea/privacyidea.log`.
The only error showing up is when an enrolled u2f token is used in chrome (w/ keycloak provider)

```
Error while signing U2FSignRequest: ReferenceError: $ is not defined
```

**Comment by plettich** [comment]
I can confirm this behaviour on chromium, however Chrome did deprecate plain U2F support: https://developer.chrome.com/blog/deps-rems-95/#deprecate-u2f-api-cryptotoken
Usually U2F-only tokens should still work using the WebAuthn API (the WebAuthn Token in privacyIDEA).
@belfhi  can You confirm that the rollout as a WebAuthn token works?

**Comment by belfhi** [comment]
Hi @plettich 
I did not know that such a deprecation existed!
Yes, WebAuthN works as expected. So probably not a bug in PrivacyIDEA. 
Since WebAuthN seems to be better supported in other platforms anyway this can probably be closed 😅
