### ISSUE TITLE
filter behaviour in user view

### ISSUE THREAD

**Issue by amboris** [privacyidea/privacyidea#3543]
### Top-level intent
in my optinion this is a bug but since i am just a small fish i have not insight to the configuration and logs.

What did you try to achieve?
to have the filter reset when clicking on (all user)/users button on admin interface.

### Steps to reproduce

1. use filter to search for a specific user
2. click user to be on specific user interface
3. click on users to go back to the list of all users

### Expected outcome

What do you think, how the system should have worked?
reset of all filters and see all users

### Actual outcome

What did actually happen?
filter is still aktiv but the filter field is empty and you only get the list of filtered user

current workaround: you need to click on token then on users to reset the filter

**Comment by plettich** [comment]
Hi @amboris i can confirm this (unwanted) behaviour. Somehow we don't reset the filter value when leaving the user-list view.

**Comment by cornelinux** [comment]
I think I remember other people to actually exepct that filters are not lost and it could be that it is implemented on pupose. Please let us check this, before rushing at conclusions.

**Comment by plettich** [comment]
> I think I remember other people to actually exepct that filters are not lost and it could be that it is implemented on pupose. Please let us check this, before rushing at conclusions.

But then it should at least be possible to reset the filter.

**Comment by amboris** [comment]
I agree with plettich. If the filter should remain the parameters should also remain in the filter field and by emptying the filter field it should reset but as it is now you have a filter applied but an empty filter field... which makes it impossible to reset except for tedious workaround.

**Comment by cornelinux** [comment]
I think it might be also interesting to actually *keep* the filter - only we would need to display it in the filter field.
So imagine an admin is searching for a certain user... was it fritz or franz... and searches for "fr..." he would keep the reduced list of the users and could check all found users, without the need to over and over enter the filter.
