### ISSUE TITLE
Check if tables already exist in pi-manage

### ISSUE THREAD

**Issue by kkalev** [privacyidea/privacyidea#3552]
We have created a Docker image of PrivacyIdea

* The Dockerfile instructions setup packages and configuration
* The docker entrypoint runs `pi-manage` with relevant options to customize our setup and expose a wsgi port

When using sqlite it is quite easy to determine if the `data.sqlite` file already exists or we need to call `pi-manage create_tables`.

Unfortunately, there is no easy way to do the same and determine if the tables already exist with MariaDB. It would be really helpful if:
* pi-manage had an option to check if the tables already exist (exit 0 if they do or 1 otherwise) or if
* pi-manage had an additional option in the `create_tables` option to only perform the task if the tables do not already exist.

Thank you for a great product!

**Comment by cornelinux** [comment]
I am not sure, if this would be the task of `pi-manage` directly.

**Comment by kkalev** [comment]
If there is a simple workaround I would be happy to know about it.

Using `pi-manage` has the advantage of not having to worry about the database schema. We could install the mysql client and run a simple SQL query on the database but that would mean adding specific database schema knowledge in the docker entrypoint. As things are right now we have a very convenient layer of abstraction by using various `pi-manage` commands and letting privacyidea worry about the specifics.

In any case, we are more than welcome to suggestions. We are basically describing our ideal situation, given how we have structured the image and its operations so far (and our desired level of abstraction).

**Comment by plettich** [comment]
The `create_tables` command in `pi-manage` does not overwrite existing data. If the tables already exist, it does nothing.
So it should be safe to run run `pi-manage create_tables --stamp` on an existing database (tested with MySQL/MariaDB).
To check if the database is already initialized, You can run `pi-manage db current` which should print out the current stamp (always stamp the database to the current version when creating it). Unfortunately this does **not** fail, if the database is not initialized (it silently does nothing).

**Comment by kkalev** [comment]
Thanks, since `pi-manage create_tables --stamp` is safe to run even if the tables already exist this closes any issues. It might be a good idea for the help message to state this as well.

Appreciate your help!
