### ISSUE TITLE
Rollout via challenge-response does not use label policy

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#3557]
(Might already be reported, didn't find it while looking)
When doing enrollment via challenge-response, the label of the token is not customized by the policy i set for token label.
Maybe this problem is also present for other types of policies related to token rollout.

**Comment by cornelinux** [comment]
Hi @nilsbehlen 
we fixed this in #3478.
@pablo-knight please update 31 and check again.

**Comment by pablo-knight** [comment]
@nilsbehlen 
Updated from 3.8.1dev1 to 3.8.1 stable
