### ISSUE TITLE
return more information in "permissions" in auth/ response

### ISSUE THREAD

**Issue by katgirl** [privacyidea/privacyidea#3560]
**Is your feature request related to a problem? Please describe.**

When logging in via the API, you get the permissions back. Unfortunately, the permission how many tokens a user may have is missing.

**Describe the solution you'd like**

We have our own WebUI and would like to show the user a hint in the token overview that he has reached his maximum number of tokens and then block the further issue of tokens. 
This way the user only gets the error message when he rolls out more tokens.

**Comment by cornelinux** [comment]
How many tokens a user may have is not a permission in this sense.
There is a lot of policy logic, that is not returned as "permission".

I you would add this to the permissions, you would a an awful lot of other stuff.

In case your webui uses a service account, you could your the `GET /policy/` call to determine this.

If you can not do this you could try to do some event handler voodoo to add this information in a POST event handler.
