### ISSUE TITLE
Ruining pi-manage backup error when database port is defined

### ISSUE THREAD

**Issue by mr-ssd** [privacyidea/privacyidea#3570]
### Top-level intent

What did you try to achieve?
Create backup from `pi-manage backup create` should run successfully when the database port is defined in  ***SQLALCHEMY_DATABASE_URI***
### Steps to reproduce

1. In pi.cfg define ***SQLALCHEMY_DATABASE_URI*** with database port e.g. `SQLALCHEMY_DATABASE_URI = "pymysql://privacyidea:privacyidea@privacyidea-db:3306/privacyidea"`
2. Run `pi-manage backup create`

### Expected outcome

What do you think, how the system should have worked?
Backup should create successfully

### Actual outcome

What did actually happen?
There is an error with message `mysqldump: Got error: 2005: "Unknown MySQL server host 'privacyidea-db:3306' (-2)" when trying to connect`

### Configuration
SQLALCHEMY_DATABASE_URI = "pymysql://privacyidea:privacyidea@privacyidea-db:3306/privacyidea"

* **privacyIDEA version**: 3.8.1
* **Installation method**: PyPI (from Ubuntu packages, github, PyPI, ...)
* **Python version**: 3.8.16
* **Operating system**: Debian 11
* **Webserver**: 
* **Token database**:  MySQL (MySQL, PostgreSQL, ...)

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by plettich** [comment]
I can confirm this behaviour, we should have used [`urllib.parse`](https://docs.python.org/3.8/library/urllib.parse.html#url-parsing) for splitting the database uri.
