### ISSUE TITLE
Event Handler triggers unexpectedly

### ISSUE THREAD

**Issue by lhaselauer** [privacyidea/privacyidea#3574]
### Top-level intent

I tried to send a notification whenever a user uses a "spass" token to login.

### Steps to reproduce

1. Create a new event handler

- Event: validate_check
- Handler module: UserNotification
- Position: post
- Condition: tokentype=spass

2. Login with a wrong password

### Expected outcome

The event should only trigger if the event includes a token of the selected type

### Actual outcome

Additionally to the desired use case, the event triggers if no token is used (e.g. wrong password)

### Configuration

* **privacyIDEA version**: 3.8.1
* **Installation method**: RHEL Repo
* **Python version**: 3.6.8
* **Operating system**: RHEL 8
* **Webserver**: Apache
* **Token database**: MySQL

### Additional remarks

The documentation for [Event Handler Conditions](https://privacyidea.readthedocs.io/en/latest/eventhandler/index.html#conditions) mentions this behaviour, but only for four specific fields. _tokentype_ is not among them.

If this (IMO confusing) behaviour is desired, please include it in the documentation.

**Comment by cornelinux** [comment]
The system behaves correct if the user only has one spass token.
In this case the condition also match, if the password is wrong.

To only trigger, if the login with a spass token was successful, you need to add the condition `result_vale=true`.

**Comment by cornelinux** [comment]
The sensible approve would be to add a comment to the read before update, if the audit log schema was changed.

* check in which cases the audit log and add a comment.
* add a generic comment
