### ISSUE TITLE
Post Request don't have a ThreadID

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3578]
Hello

In the Audit Log there is a ThreadID only for GET Requests, but not for POST Requests.

Example of a Post request:
http --verify no POST https://sever_IP/validate/check user=hannes3 pass=PIN_AND_TOKEN
 No ThreadID in the audit log.

Thank you.

Sebastien

**Comment by plettich** [comment]
I can confirm this, the `thread_id` is missing for all `validate` endpoints:
https://github.com/privacyidea/privacyidea/blob/49f64d01b2bffeacabeac721a405d46d9a62725d/privacyidea/api/validate.py#L146

**Comment by cornelinux** [comment]
Right, if we have a before-all we should put it here!

**Comment by plettich** [comment]
So basically each [Flask Blueprint](https://flask.palletsprojects.com/en/1.1.x/blueprints/#blueprints) (an API endpoint) can have a function which runs before the actual request is run. These functions are registered with the [`before_request`](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Blueprint.before_request) decorator.
We currently have four main `before_request` functions:
https://github.com/privacyidea/privacyidea/blob/bffc54f23d1444706bbb343101b283127954be6e/privacyidea/api/before_after.py#L150
https://github.com/privacyidea/privacyidea/blob/bffc54f23d1444706bbb343101b283127954be6e/privacyidea/api/auth.py#L88
https://github.com/privacyidea/privacyidea/blob/bffc54f23d1444706bbb343101b283127954be6e/privacyidea/api/validate.py#L125
https://github.com/privacyidea/privacyidea/blob/bffc54f23d1444706bbb343101b283127954be6e/privacyidea/api/ttype.py#L57

We should create a single `before_request` function (or reuse the [`before_app_request` handler](https://github.com/privacyidea/privacyidea/blob/bffc54f23d1444706bbb343101b283127954be6e/privacyidea/api/before_after.py#L87)) which contains all the common functionality like:
- create and initialize the audit object
- create (and initialize) other common objects (policies, events, client ip, ...)
- fetch the parameters
- ...
