### ISSUE TITLE
privacyidea server in the audit log is wrong on privacyidea HA scenario

### ISSUE THREAD

**Issue by claudiosoprano** [privacyidea/privacyidea#3589]
### Steps to reproduce

1. Install two privacyidea server that connect to the same external mysql server (cluster or not)
2. define the PI_NODE and PI_NODES variable
3. don't define the PI_AUDIT_SERVERNAME

### Expected outcome

From documentation i would see the PI_NODE name under the column privacyidea_server on the audit log, instead i see the "common name"of the webserver used to Load Balancing the two privacyidea nodes
 
### Actual outcome

i see the "common name"of the webserver used to Load Balancing the two privacyidea nodes

### Configuration

* **privacyIDEA version**: 3.8.1
* **Installation method**: from Ubuntu packages
* **Python version**:  3.10
* **Operating system**: Ubuntu 22.04
* **Webserver**: Apache 2.4
* **Token database**: MySQL galera cluster

### Log file

let me know if you need the log file, but nothing is there 

### Fix

I fixed the problem defining PI_AUDIT_SERVERNAME to the PI_NODE value, now the privacyidea server in the audit log is correct.

**Comment by claudiosoprano** [comment]
Expected outcome
From documentation if PI_NODE is defined, the PI_AUDIT_SERVERNAME will be set at that value, so i would see that name under the column privacyidea_server on the audit log, instead i see the "common name"of the webserver used to Load Balancing the two privacyidea nodes

**Comment by cornelinux** [comment]
We need to check if the docs are wrong or we need to fix the code.

**Comment by NNLemling** [comment]
I can confirm the behavior.

Normally this should happen here:

**Comment by cornelinux** [comment]
Order.

PI_AUDIT_SERVERNAME
if not available PI_NODE
if not available requests.host

**Comment by cornelinux** [comment]
@NNLemling Needs to be adapted in the docs.
