### ISSUE TITLE
Token enrollment or assignment audit log bug

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#359]
I was trying to figure out what does audit log contain when a user is being assigned with a token because I need to track(and notify) a user when someone enroll and bind a token with him.
And here is what I discovered:
If I go to all users, filter user needed and then on the page
https://<pi-server>/#/user/details/<realm><user>
I click "Enroll new token", enroll it, in audit log for this user I see pretty much everything I expect - admin, token serial and user itself:
![screenshot_2](https://cloud.githubusercontent.com/assets/2293660/14243564/0bb99d84-fa5f-11e5-88f1-5cdcfe0872ba.png)

But if I first enroll a token, then, after the enrollment, I bind it to a user, I cannot see in audit logs what user I bound a token to:
![screenshot_1](https://cloud.githubusercontent.com/assets/2293660/14243567/0f9a7568-fa5f-11e5-9258-bfc271876a93.png)

Is it expected behavior? For me it seems useless to have an audit log entry for "assign" action if you can't see what user the token had been assigned to.

**Comment by cornelinux** [comment]
This is right. The username is missing.

In fact there are also missing some other values with the token-endpoint.
