### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3593]
Currently the tests fail with Python 3.11 since the function [`inspect.formatargspec()`](https://docs.python.org/3.10/library/inspect.html#inspect.formatargspec) was removed (deprecated since Python 3.5). The proposed `signature()` method behaves differently so we have to check how to get the tests running again.

Also the deprecated `flask-script` uses the removed `inspect.getargspec()` so we need to push for #2498

**Comment by EchedeyLR** [comment]
I am currently affected by this issue as well.

Is it possible to enforce the use of Python 3.11?

It is the blocking for a current deployment sadly :c

**Comment by plettich** [comment]
Hi @EchedeyLR 
while we are working on supporting Python 3.11 properly in the next release, here is a workaround if You are willing to patch the 3rd-party code:
https://community.privacyidea.org/t/python-3-11-support/3115

**Comment by plettich** [comment]
Done in #3917

**Comment by EchedelleLR** [comment]
Issues seems to still happen after using Python 3.11 #4108
