### ISSUE TITLE
Feature request. User e-mail notifications.

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#360]
Hello!
Please consider adding a feature of email notification to a user about certain kind of activities in regards to his account and his tokens.
Why is it needed:
Imagine organization with:
general users
HelpDesk admins with limited admin rights
superuser(OTP administrators) admins with full rights.
If someone of either HelpDesk or superuser enroll a token and bind it to a user, the user will not be aware that someone(helpdesk staff for instance) potentially could use his name to authorize on services. We'll not consider superadmins here as they can even go directly to the database and do whatever they need, if needed. We only care about other limited admins as Help Desk who have enough rights to enroll a token and assign it to a user(it's their job).
You already have a mail-server configuration in PI
You already have e-mail being gathered by every user(in case of LDAP resolver).
What would be a very good option - is to notify a user if something happened to tokens assigned to him - assign, disable, remove...etc

Also having additional admin policy such as 
"set_mail_server"
and webui(or something else) policy such as
"mailserver_for_notifications:<list_of_pre_defined_servers>" 
is necessary. In this case option 
"set_mail_server"
would be enabled for superuser and disabled for limited admins as helpdesk.

**Comment by cornelinux** [comment]
In fact we could notify any token operation. Think of a **generic** solution.

We could use the centrally defined mailservers.

...and create a new policy, that defines

1. for which actions a notification should be sent
2. via which mailserver the notification should be sent

hm, sounds a bit bigger. Sounds like a new policy scope....

**Comment by kolosovski** [comment]
This would be definitely better and more extendable

**Comment by cornelinux** [comment]
We probably need to move this to a later release. 
I think it is not cool to do a user notification.

It is much cooler to do a common event handling. See https://github.com/privacyidea/privacyidea/wiki/concept%3A-event-handling

**Comment by kolosovski** [comment]
Looks nice and flexible

**Comment by cornelinux** [comment]
The draft code can already send nice emails:

> Hello Cornelius,
> 
> the administrator super@ performed the action
> /token/init on your token OATH00368D3C.
> 
> To check your tokens you may login to the Web UI:
> http://localhost:5000/
>

**Comment by kolosovski** [comment]
Great news!! Thank you for the update

**Comment by cornelinux** [comment]
I think I am done for the first version:

Please take a look at this branch:
    https://github.com/privacyidea/privacyidea/tree/360_event_handler

and read this doc and *try to understand* ;-)
https://github.com/privacyidea/privacyidea/blob/360_event_handler/doc/eventhandler/index.rst
https://github.com/privacyidea/privacyidea/blob/360_event_handler/doc/eventhandler/usernotification.rst

**Comment by kolosovski** [comment]
From the documentation you've provided seems even better than expected. I'll play with it after it is released. By the way, is it expected in 2.12 release? When it is planned to come out?

**Comment by cornelinux** [comment]
Always be ready to be surprised! ;-)
At first there is only the UserNotification. But new modules can extend the functionality really cool.
It will be in 2.12. 
By the way: I just uploaded 2.12dev2 to the ppa devel repo.
Looks like it is already built:
https://launchpad.net/~privacyidea/+archive/ubuntu/privacyidea-dev/+packages

**Comment by kolosovski** [comment]
Thank you for the hint! just installed in a sandbox and tested notifications. Looks very nice, but I noticed strance behavior... If you configure an event handler like this
![image](https://cloud.githubusercontent.com/assets/2293660/15155469/3f259332-16eb-11e6-812c-85d185f1739e.png)
it will only send e-mail actions on 
/token/assign
and 
/token/init 
events
nothing on token_unassign.. Perhaps it even should not as after un-assignment PI probably has no idea who to send the event.
So maybe if that true it'd be good to review other actions and either exclude them from actions list or  make these actions operable :)
But anyways, it works as needed, I just talking about potential bug

**Comment by kolosovski** [comment]
> the administrator admin@ performed the action /token/assign on your token OATH00006E9F.
1) Beginning of the sentence should be in upeer case
2) admin@ - I didn't configured a superuser realm here yet so maybe you'd consult - if I have a superuser realm and use it instead of built-it users, will it be present in the message like "sergey@superuser" or just "sergey@"? Because if "sergey@superuser" - maybe it isn't the best option to announce super user realm name to a whole company ? :)

And when 2.12 is going to be released? For installation in production

**Comment by cornelinux** [comment]
Look at the milestone for release date. may 24th.

**Comment by cornelinux** [comment]
Am Dienstag, den 10.05.2016, 10:14 -0700 schrieb Sergey Kolosovski:
> Thank you for the hint! just installed in a sandbox and tested
> notifications. Looks very nice, but I noticed strance behavior... If
> you configure an event handler like this
> image
> it will only send e-mail actions on 
> /token/assign
> and 
> /token/init 
> events
> nothing on token_unassign.. Perhaps it even should not as after
> un-assignment PI probably has no idea who to send the event.
> So maybe if that true it'd be good to review other actions and either
> exclude them from actions list or make these actions operable :)
> But anyways, it works as needed, I just talking about potential bug

No bug.
Logical behaviour.

By the way: I very much recommend considering getting an SLA for your
company.
https://netknights.it/en/leistungen/service-level-agreements/

**Comment by cornelinux** [comment]
Am Dienstag, den 10.05.2016, 10:28 -0700 schrieb Sergey Kolosovski:
>         the administrator admin@ performed the action /token/assign on
>         your token OATH00006E9F.
>         1) Beginning of the sentence should be in upeer case

this is not the beginning of the sentence. The beginning of the sentence
is

"Hello Sergey" ;-)

But one day this might be configurable.

>         2) admin@ - I didn't configured a superuser realm here yet so
>         maybe you'd consult - if I have a superuser realm and use it
>         instead of built-it users, will it be present in the message
>         like "sergey@superuser" or just "sergey@"? Because if
>         "sergey@superuser" - maybe it isn't the best option to
>         announce super user realm name to a whole company ? :)
>         
Do you want the user to control admins or not.
There is always the possibility to not use it.
You do not want to do security be obscurity.

But one day the email might be configurable.
Open for pull requests...

**Comment by kolosovski** [comment]
Thank you for the release day. I also found it here on github.

> No bug.
Logical behaviour.

If the logic is to send an a notification when a certain event occurs but the notification isn't being sent upon raising the event, where is the logic ? :)

> By the way: I very much recommend considering getting an SLA for your
company.
https://netknights.it/en/leistungen/service-level-agreements/

It is already in the process of procurement. Should be finished from day to day..

> this is not the beginning of the sentence. The beginning of the sentence
is
"Hello Sergey" ;-)

I also thought about it and therefore removed this comment via edit button before you answered, although as you answered, I've searched through the web and discovered that it is common to use capital letter after greeting and comma in emails written in English(moreover all the examples found were with a capital letter), BUT on somewhere on a forum I read that Germans use small letter after the comma.

**Comment by cornelinux** [comment]
Hello Sergey,

**T**his looks strange to me. Maybe since I am also not a native speaker. I think there will be the possibility to configure an individual email template. Then you could even send mails like:

    Cornelius.
    This sentence starts just as I wish to...

OK. I guess I know which company to assign you to.

As far as the logic is concerned... From a code standpoint the behaviour is logical and not unexpected. From a human point of view, each human being has its own expectations and other definitions of logic.
I completely understand your usecase!
But no worry. When doing *UserNotification* the *unassign* would be a pre-event. Note: When doing other type of event handlings the *unassign* might *not* be a pre-event.
The necissity for pre-event was already considered, but not implemented:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/event.py#L56

Kind regards
Cornelius
