### ISSUE TITLE
Unclear Policy/API description

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3609]
The documentation of the [`/token/description`](https://privacyidea.readthedocs.io/en/latest/modules/api/token.html#post--token-description-(serial)) endpoint describes, that it can be used by a user or admin. This is only true for the admin if no admin policies are set.
There is only a user policy for [`setdescription`](https://privacyidea.readthedocs.io/en/latest/policies/user.html#setdescription). The admin usually uses the [`/token/set`](https://privacyidea.readthedocs.io/en/latest/modules/api/token.html#post--token-set-(serial)) endpoint.
We should either add a `setdescription` admin policy or update the documentation of the endpoint.

**Comment by cornelinux** [comment]
The historical background is, that there was a request, that a user should only be able to set a description and not use the whole /token/set endpoint.

It might be good, that "admins" like helpdesk users, could also be policified this way, that the would only be allowed to set the description.

A logical behaviour would be:

* Add an admin policy "setdescription".
* An admin (or user) would be allowed to use the endpoint /token/description if he had the "setdescription" or the generic "set" policy. Thus: Adding a setdescription for admis makes sense.
