### ISSUE TITLE
Fail counter on the Users view

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3612]
Could it be possible to add the fail counter on the user's View (where all the users are listed)
Users are managed on this view. So it would be more practical if the fail counter was also visible on this page.
Thank you

**Comment by stephanhendl** [comment]
I would appreciate this feature!

**Comment by stephanhendl** [comment]
> Would it be helpful if we could filter for the user-id in the token-list view?

Yes, indeed, this would be very helpful.

**Comment by stephanhendl** [comment]
In November 2022 I've put a feature request #3379 for that purpose already but unfortunately it was closed by @cornelinux without any comment.

**Comment by cornelinux** [comment]
@stephanhendl  I closed it, since it is not possible in a sensible way. (I am tempted to close this, again ;)
@sepp67 What is your actual use case? What is the situation, in which the admin goes to the UI?
