### ISSUE TITLE
Failed token in the audit log are not pulled in the audit log

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3617]
Hello

If the user has multiple tokens and fails to authenticate, the serial number of the tokens are not pulled in the audit log.

Thank you.

**Comment by plettich** [comment]
By the way, we already have multiple token serials in the audit log when using challenge response: https://github.com/privacyidea/privacyidea/issues/3285

**Comment by sepp67** [comment]
yes we can close it

**Comment by plettich** [comment]
I vote for keeping it. We do have a list of failed tokens for which the PIN matches so we can add them to the audit log. It is a probably a low prio though.
