### ISSUE TITLE
Problem with realm change on a token page

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#362]
Hello Cornelius.
There's a quite unexpected behavior of PI interface while a user tries to change realm of a token.
Every test have been conducted while connected under admin scope account with full privileges on page
https://<pi fqdn>/#/token/details/<token serial>
Here are few cases how it looks like and how to reproduce:
1)
The token currently in realm_a
I want it to be in realm_b
to do so in "Realms", after Clicking "Edit" I remove checkbox from realm_a and put it on realm_b and click "Save realms"
after this I see both realms on the page. I also checked database
`SELECT a.id, a.description, a.serial, a.resolver, a.user_id, c.name FROM token a, tokenrealm b, realm c WHERE ((a.id = b.token_id) AND (b.realm_id = c.id) AND (a.description='test HD token'));`
and there are also two realms of the token. Moreover under "Assgined User" fields "Username" and "Realm" become blank.
Then when I ckick "Edit" near realms I also see both realms checked. Ok, I uncheck realm_a again, click "Save realms" but in user interface I still see both realms, in mysql also both realms seen attached to the token
If I click "Unassign user" choose realm_a then enter user name, click "assign user" I see only realm_a in realm list of the token as well as in the mysql.
2)
I noticed that click on the realm name ("Realms" list of the page) also opens edit realm mode. In this case changing realm is much easier. It works almost as expected, but there's no realm checked by a checkbox when you click on a realm name.

It is reproduced in all browsers.

**Comment by kolosovski** [comment]
The user to which the test token is assigned present in both resolvers of both realms

**Comment by cornelinux** [comment]
You can not remove the realm of the user to which the token is currently assigned.

To privacyIDEA the user@REALM_A is another user than user@REALM_B.

The correct way is to

1. unassign the token
2. remove the realm from the token if necessary
3. assign the token to the new user.

**Comment by kolosovski** [comment]
Sorry if I explained not so clear
But I'm not trying remove realm of a user.
I have a user which  can be found in two realms. One realm for managing his own tokens, another - for managing other users tokens.
This user has a token assigned in realm_a. How to move this token to realm_b? I suppose the way that I described above - just change a checkbox from realm_a to realm_b, right? When I do this the PI behavior is unpredicted as I described above.

Here are another questions going from described above:
 - Can a token be assigned to two realms?
 - Is it correct, that to change realm of a token a user should click on the realm name itself instead of on the Edit button in front of realm names?

**Comment by cornelinux** [comment]
I understood it.

But as I explained: To privacyIDEA this is not one user but two users. THis is why you have to unassign the user an assign the new user again!

A token can be located in two realms. But see my expanatition above.
A user can not change the realm of a token only an admin can.

No the admin can edit the realm by clicking on the edit button. But the admin can not remove the realm of the assigned user!!!!!

**Comment by kolosovski** [comment]
Okay, If I get you right, I(as an admin) can change realm of a token if it is not assigned to anyone. Right?
Well, I unassigned the test token from a user. Now is not linked with anyone.
Then I'm trying to perform the same thing - move token from realm_a(where the token is currently belongs to) to realm_b. 
To do so I press the "edit" button on "Realms" row of a token page.
Only realm_a is currently selected with checkbox.
I remove checkbox in front of realm_a and put it in front of realm_b and press "save realms".
Result - I have the token appeared in two realms - realm_a and realm_be. Is it normal?

Okay, I supposed that maybe I need first remove realms from the token, save changes, then click Edit again and assign it to another realm. But this doesn't work either. After removing checkboxes in front of realm names and pressing Save, I still have realm_a assigned to the token. No warnings, no errors - nothing. Is that expected?
What am I doing wrong?

**Comment by cornelinux** [comment]
The realm edit is independent of the assigned user.
This would be the behaviour. When unchecking a check box and saving the realms the unchecked realm should not be set anymore.
You are right - it is not.
Looking at the REST request the UI still issues all realms.

Thanks a lot for this observation.
I will create a new issue, to avoid confusion with the user-changing, which is definitively not a supported feature.
Thanks again, 
Cornelius

**Comment by kolosovski** [comment]
Thank you very much for the fix. I tested it and now is much better! However, there are still two questions regarding this token manage page:
 - Could you clarify why a token has an option to be in two realms? What cases are possible of using such tokens? Because a token can be used only while assigned to a user, but user can be only in one certain realm.. Or as you said, for PI there're two users - SomeUser@realm_a and SomeUser@realm_b. If that true why both these "users" can't be assigned with the same token which has two realms - realm_a and realm_b? If the described is'n possible as well, why the interface suggests to chose one or more realm instead of jsut one?
 - on the https://<server_name>/#/token/details/<token_serial> page on the same row "Realms" you still can click on a realm name to open edit realm mode. Don't know if it maybe special feature, but other editable options don't behave this way. just insignificant observation 

Sorry if it's not so clear for me with the concept regarding realms, I really read the docs many times to have clear understanding.. But sometimes you don't know whether it is a bug or an undocumented by-design behavior..

**Comment by cornelinux** [comment]
This is because of administrators can handle different realms. An administrator may only be allowed to handle tokens in realmA another admin only to handle tokens in realmB.

If a token is in realmA and realmB, both admins will be able to see this token.
