### ISSUE TITLE
Documentation: Wrong use of "your" and "you're" and other gramatical errors

### ISSUE THREAD

**Issue by gryffus** [privacyidea/privacyidea#3661]
Hello, 

here: https://privacyidea.readthedocs.io/en/v3.8.1/policies/authentication.html#preferred-client-mode

In "7.3.34. preferred_client_mode", there is sentence:

"For example: this is you’re list: “interactive, webauthn, poll, u2f” and in you’re multi challenge are a webauthn and u2f token, than you’re client will automatically show you the login for a webauthn token."

I don't think there has to be more to be said :)

**Comment by gryffus** [comment]
Also, in example shown next to the configuration option, it shows that you should separate challenges by whitespace. However in documentation (link above), it shows, that you should separate challenges by a comma.

**Comment by cornelinux** [comment]
Policy values need to be separated by whitespaces.

**Comment by plettich** [comment]
> @jona-samuel @NNLemling Usually policy values need to be separated by whitespaces. Is this different in this policy?

They are separated by white-spaces as well (comma does **not** work). But we are separating the entries in the policy itself (not when extracting the action values, thus the parameter `allow_white_space_in_action=True`) to keep the order of the elements.
