### ISSUE TITLE
Install PI on an existing server with vHosts

### ISSUE THREAD

**Issue by zkvvoob** [privacyidea/privacyidea#367]
Hello,

I have a Ubuntu 14.04/Apache2 server with ISPConfig installed and several vhosts, some of them already with SSL certificates, all running smoothly. Earlier today I tried installing privacyIDEA following the official documentation (http://privacyidea.readthedocs.org/en/latest/installation/ubuntu.html). However, when the installation finished, all my websites (including ISPConfig) were no longer available or giving SSL errors.

Could anyone help me with pointers what I should do in order to get privacyIDEA installed without screwing with my existing setup and, if possible, to make its web interface available only on the local network?

Thanks in advance!

**Comment by cornelinux** [comment]
Hi @zkvvoob ,

thanks for using privacyidea. Such a request should be better taken to the google group as it is concerned with installation / integration. 
https://groups.google.com/forum/#!forum/privacyidea
Please join this google group / mailing list.

Anyway. Installing the package privacyidea-apache2 also installs the complete apache configuration and making privacyidea the only running system on the machine. This is the most common setup and this we have this meta-package privacyidea-apache2.

If you have already other services on the machine, or if you want to run privacyidea in a different way, if you want to use another database you can simply install the package python-privacyidea.
Then you will have to setup
1. the database manually and
2. the webservice providing privacyidea.

But you can also decide were you want to run privacyidea.
I recommend running privacyidea in a sub directory (or an instance directory).
http://privacyidea.readthedocs.org/en/latest/installation/system/wsgiscript.html#running-apache-instances

Kind regards
Cornelius
