### ISSUE TITLE
Error 904 is still shown with policy Action login_mode: privacyIDEA 

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3672]
privacyidea 3.8
ubuntu 20

Since 3.7 the error message :´ERR904: The user can not be found in any resolver in this realm!¨ is deactivated when you enter a wrong username.

But this is still true if you have a policy :
Scope webui
Action login_mode: privacyIDEA 

if you have a policy:
Scope webui
login_mode: userstore 
Then the error (ERR904: The user can not be found in any resolver in this realm!)  Is deactivated.

Kind regards
Sebastien

**Comment by cornelinux** [comment]
Expected outcome: We should get the same error: Wrong Credentials.
