### ISSUE TITLE
Some authorization policy actions do not work with multichallenge

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3681]
The policies only check the base entries in the `detail` section of the response but ignore a possible `multi_challenge` entry.
This is true for:
- [ ] [`check_tokeninfo()`](https://github.com/privacyidea/privacyidea/blob/a9efe9141759ed3b0fdd3041ad296ebf154fdfe0/privacyidea/api/lib/postpolicy.py#L258)
- [ ] [`check_tokentype()`](https://github.com/privacyidea/privacyidea/blob/a9efe9141759ed3b0fdd3041ad296ebf154fdfe0/privacyidea/api/lib/postpolicy.py#L202)
- [ ] [`check_serial()`](https://github.com/privacyidea/privacyidea/blob/a9efe9141759ed3b0fdd3041ad296ebf154fdfe0/privacyidea/api/lib/postpolicy.py#L228)
- [ ] ...

See also #2719

**Comment by cornelinux** [comment]
Check the effort for fetching serials from either `detail` or `multi_challenge`.

**Comment by cornelinux** [comment]
Well, well. The question is, how we expect things to work. This is not clear.

All these `check_...` policies actually are *authorization* policies and are ment to do the authentication and *after* a token was successfully used to deny the access.

So actually things work as designed.

If a use triggers a multi challenge with HOTP, TOTP and SMS token and then decides to use HOTP to finalize the authentication, the *authorization* policy tells him, that he is not allowed to use HOTP. 

The question is, how a **design change** is supposed to look like!

This is obviously again related to the major topic #3695.

**Comment by cornelinux** [comment]
All mentioned policy actions work as designed and documented.
Not triggering certain tokentypes or tokeninfo is a different matter and shall be worked on in a different issue (linked).
Therefor I am closing this one.
I am removing the milestone, so that we do not think we fixed it.
