### ISSUE TITLE
Empty responses result in "400 Bad Request"

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3682]
Our [default response class](https://github.com/privacyidea/privacyidea/blob/a9efe9141759ed3b0fdd3041ad296ebf154fdfe0/privacyidea/app.py#L75) sets the content-type of the response to `application/json` but when the response does not contain any data (like an [`OPTIONS` request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS)), the [`sign_response()`](https://github.com/privacyidea/privacyidea/blob/a9efe9141759ed3b0fdd3041ad296ebf154fdfe0/privacyidea/api/lib/postpolicy.py#L183) function tries to read the data (as JSON) anyway and the exception is raised.

We can check in the `sign_response()` function if we have any data at all and if not, just send an empty JSON object as a result (since we can't easily change the content-type of the response anymore).

**Comment by cornelinux** [comment]
Who sends OPTINOS requests?
Why do we want so support this?
Should we block this?

**Comment by plettich** [comment]
> Who sends `OPTIONS` requests? 

Clients which are configured to use CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS)

> Why do we want so support this?

Flask enables the `OPTIONS` method by default: https://flask.palletsprojects.com/en/1.1.x/api/#view-function-options
We could disable this for each blueprint though.

> Should we block this? 

It seems to be common to allow the `OOPTIONS` method: https://security.stackexchange.com/questions/138567/why-should-the-options-method-not-be-allowed-on-an-http-server
However we currently do not have any CORS support.
And we should at least respond with a `405 METHOD NOT ALLOWED` instead of a `500 Internal Server Error`

> Which endpoint?

All enpoints.

**Comment by cornelinux** [comment]
Can we do a 405 as a short term solution and work on other aspects in the future?

**Comment by nilsbehlen** [comment]
since we wont do anything right now anyway, we can close this and just upgrade flask.
