### ISSUE TITLE
adding user information to email token enrollment view

### ISSUE THREAD

**Issue by bpnx** [privacyidea/privacyidea#3688]
**Is your feature request related to a problem? Please describe.**

During an email token enrollment I'd like to show to the user the email address the email token will be sent to

**Describe the solution you'd like**

Have  the user information data on the token enrollment view

**Additional context**

The email token could be sent to a secondary email address, that maybe a user could not remember; showing it to him is a simple
check to help avoid errors

For privacyIDEA developers. Describe and document the development plans:

# Implementation

I've modified (a copy in /etc/privacyidea/customization of ) the files
- components/token/controllers/tokenControllers.js (controller tokenController)
- components/token/views/token.enroll.email.html (to show a message to the user)

**Comment by cornelinux** [comment]
I would add this to the `tokencontroller.js`.

~~~~
    $scope.getUserDetails = function () {
        UserFactory.getUserDetails({}, function (data) {
            $scope.User = data.result.value[0];
        });
    };
    $scope.getUserDetails();
~~~~
As you(?) described [here](https://community.privacyidea.org/t/show-dynamic-email-to-user/3038/3)

This way user data is available in the enrollment scope and can be used individually for customization.

**Comment by bpnx** [comment]
Hello, yes, it was me. I was figuring out how to create a pull request (I never did this before), but I see you already did
Thank you
