### ISSUE TITLE
Issue with token enroll

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#370]
Hello Cornelius!
Recently I noticed unexpected behavior of my PI installation when I logged in into user scope and going to enroll a token. When I click on "Enroll token" button it throws me to log in page although the system isn't log me out, look at the screenshot:
![screenshot_1](https://cloud.githubusercontent.com/assets/2293660/14439644/d792683e-0034-11e6-82aa-a955fbfa6f2d.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/2293660/14439654/ea750c54-0034-11e6-920a-989a38e2c87b.png)
the red API query "radiusserver/" returns 401 status code and this JSON:

`
{
  "jsonrpc": "2.0",
  "signature": "23606431802570839952804449968867699022247681558397496156174028091090879769040867892302396371796244889450117777803753856262865177398440784556733767542049994154954728332764387498736135571938274108335019489406315907468292662029251177634347011496082246343904629662782206362457992835363758741520294308825267210026375028257321134414902991714389304807112989147069673755670684253276814406980646944955289430358851982607500795549012679994368707245422831765343588884517025452276179109967536838775376745587463855800567468727740783194288596878657916957324265450326329889394196256477609094237606541666043276225222877542217324196009",
  "detail": null,
  "version": "privacyIDEA 2.11",
  "result": {
    "status": false,
    "error": {
      "message": "You do not have the necessary role (['admin']) to access this resource!",
      "code": -401
    }
  },
  "time": 1460402621.451246,
  "id": 1
}
`

First thoughts was something is broken by me but I just made a fresh VM and PI installation, configured an LDAP resolver and admin user and tried to reproduce(the screenshots have been made from the sandbox). Don't have anything else configured, even policies.
Maybe it wants some policy to be configured relating a radius server? Although formerly it risen an red alert about this kind of misconfigs.. Could you please check on your side?

**Comment by cornelinux** [comment]
I can confirm this being a bug.
The token enrollment calls

    GET /radiuserver

to be able to choose, which radius server to enroll.

The user must be able to retrieve the list of configured radius servers.

Thanks for pointing this out!

**Comment by kolosovski** [comment]
Thank you very much for quick resolution!
I've tested and can confirm that it's working now

**Comment by cornelinux** [comment]
thanks for your report!
