### ISSUE TITLE
Maintenance mode (read-only)

### ISSUE THREAD

**Issue by hex-m** [privacyidea/privacyidea#3740]
## The Problem

The necessary maintenance-downtime is too long.

### Our architecture
* `server1` - privacyIDEA + mariaDB
* `server2` - privacyIDEA + mariaDB
* users/systems reach the service via a virtual IP which points to server1 during normal operation

### How we currently update (privacyIDEA or the operating system):
1. apply updates on `server2`
2. stop privacyIDEA on `server1`
3. copy DB to `server2`
4. update schema if necessary
5. start privacyIDEA on `server2`
6. assign virtual IP to `server2`
7. apply updates on `server1`
8. stop privacyIDEA on `server2`
9. copy DB back to `server1`
10. start privacyIDEA on `server1`
11. assign virtual IP to `server1`

This procedure means that our users cannot log-in for about 2 x 30 seconds.

## Proposed solution

We could lower the downtime to a few seconds like this:
1. enable maintenance mode in privacyIDEA (no DB writes but logins still work) on `server1` and `server2`
2. copy DB to `server2`
3. assign virtual IP to `server2`
4. apply updates on `server1`
5. assign virtual IP to `server1`
6. disable maintenance mode and update schema if necessary
7. apply update on `server2`

While registering new tokens would fail when maintenance-mode is active, the downtime for the login-process would be down to "basically zero".

## Considered alternatives

We could enable read-only mode on the database side, but we assume privacyIDEA would not react gracefully to that.

**Comment by cornelinux** [comment]
Your update process is unneccessarily complicated.

The whole copy-the-DB-thing is not necessary!

Also you suggestion does not work out. privacyIDEA can not to authentication requests without being able to write to the database.

Basically the usual update process looks like this:

1. update nodeA - you may deactivate nodeA during this one. During this process the DB schema gets updated on all node.s
2. take nodeA up and take nodeB down.
3. Update nodeB.

We can not implement your requested maintenance mode.
