### ISSUE TITLE
Check Yubikey OTP length before validating

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3746]
According to the docs the Yubikey OTP is always 44 chars long (https://developers.yubico.com/OTP/OTPs_Explained.html).
We can check the length of the given OTP before  doing any further validation (this is also true for HOTP/TOTP/Email/SMS token).
That way we can identify possible broken input before getting cryptic errors like "CRC checksum failed".

**Comment by cornelinux** [comment]
Additional to all OTP values, where we know, how long the otp value should be, we could...

- with the yubi OTP also check for lowercase / force lowercase
- catch the CRC checksum and return "invalid OTP value".

**Comment by plettich** [comment]
I have created a little test for different errors from [`check_otp()`](https://gist.github.com/plettich/d156931d0b0d439a252b17613a8d33f9):
https://gist.github.com/plettich/d156931d0b0d439a252b17613a8d33f9
Basically we can prevent some of the errors by:
1. convert the `anOtpVal` to lower case at the beginning of the function.
2. check for the proper length of the otp value (and log it before returning a result < 0). This gives at least a hint that there are characters missing or added and not the *CRC Checksum failed*
3. add a log message when `modhex_decode()` fails (due to a wrong character in the otp value

We have no way of telling a user what is wrong because we do not interpret the return value:
https://github.com/privacyidea/privacyidea/blob/a1b187f59ba5900ad7b7424fa4a99ece6215243e/privacyidea/lib/token.py#L2030-L2035

**Comment by jona-samuel** [comment]
should we implement this for totp, hotp, SMS and email too?
