### ISSUE TITLE
Description too long causes 500 internal server error

### ISSUE THREAD

**Issue by belfhi** [privacyidea/privacyidea#3747]
### Validate Token description length

If a token is enrolled with a description with over 80 Characters, the enrollment fails.
In my logs I can see:
```
sqlalchemy.exc.DataError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(80)
```

### Steps to reproduce

1. Enroll token with description > 80 chars
2. see 500 Internal Server Error
3. Token not enrolled

### Expected outcome

Either the description should be truncated and the token should be enrolled 
or the user should see an error that explains what went wrong.

### Actual outcome

Token is not enrolled, user sees an error in the UI.

### Configuration

* **privacyIDEA version**: 3.8.1
* **Installation method**: Ubuntu packages
* **Python version**: 3.10
* **Operating system**: Ubuntu 22
* **Webserver**: Apache httpd
* **Token database**:  PostgreSQL / psycopg2

**Comment by nilsbehlen** [comment]
add a contraint to 80 chars in the UI.

**Comment by cornelinux** [comment]
@belfhi How long was the description you wanted to add?
What are you writing in the description and why?
Maybe it makes sense to make the description field longer and not only check the length.

**Comment by belfhi** [comment]
I don't remember @cornelinux , the user wanted to add a _very_ long description to their token. It was unnecessarily long, I would say, but apparently the input wasn't validated and resulted in errors.

**Comment by jona-samuel** [comment]
https://github.com/privacyidea/privacyidea/pull/3980
