### ISSUE TITLE
Improve the error message when polling for deleted token

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#3762]
If the app polls for a token that has been removed in privacyidea, the response is
```
{
    "detail": null,
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "error": {
            "code": 10,
            "message": "ERR10: Could not verify signature!"
        },
        "status": false
    },
    "time": 1695130335.6046495,
    "version": "privacyIDEA 3.9.dev3",
    "signature": "rsa_sha256_pss:"
}
```
which does not accurately describe the problem. 
Ideally, the app displays the error message without having to do any "thinking". Also, in this case it would be good to have the requested serial repeated in the error message so the user knows which token does not exist anymore. Something like:
`The token PIPU00000 does not exist!`

**Comment by cornelinux** [comment]
@nilsbehlen Does the token not exist or is there no challenge for this token.
Please specifiy the API endpoint you were calling.

**Comment by nilsbehlen** [comment]
The token had been deleted and the endpoint for polling push requests is `/ttype/push`

**Comment by plettich** [comment]
According to the comments we did this to avoid information disclosure:
https://github.com/privacyidea/privacyidea/blob/900b7250e41ff5a5eecfe89cd3f274a8f9df7595/privacyidea/lib/tokens/pushtoken.py#L717

**Comment by cornelinux** [comment]
@nilsbehlen As @plettich mentioned we return this on purpose to avoid an enumeration of serial numbers.

So in our opinion the API behaves in a sensible way and returnes the logical response from an API- and security- standpoint.

If the Smartphone App actually *has* a token with a serial number (which the privacyIDEA server can not know, if the token was deleted), then the App should change the response accordingly.

The App "knows" that the token originially existed on the given privacyIDEA server.
Only the App can understand that the token does not exist anymore (if we assume the timestamp is correct).
So the App should change message displayed to the user:

- "The token does not exist anymore"
- "Error fetching Token info".
- "Could not verify signature. A possible reason might be, that the token does not exist anymore on the server"

We will then close this issue.
