### ISSUE TITLE
Failing resolver is blocking the entire realm

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3766]
**Situation**
Ticket 3755
A realm with several resolvers.

**Issue**
When one of the resolvers has no more a valid certificate, it is all the realm that is impacted. The privacyidea server is writing an error 500 in the logs and the entire realm is blocked.

**Feature request**
Could it be possible that the privacyidea server is going through all the resolvers of a realm even if one has not a validate certificate,

**Comment by cornelinux** [comment]
@sepp67 Do you have a log file or traceback?

**Comment by sepp67** [comment]
Yes, I have a log file in the ticket 3755

**Comment by cornelinux** [comment]
It very much looks like this is a configuration issue.
If a resolver is configured to resolv and the PI_LDAP_POOLING_LOOP_TIMEOUT is not set, it can feel like Blocking. But in fact it is simply trying to resolve.

I would the close this issue.

**Comment by cornelinux** [comment]
Added note in ticket.
