### ISSUE TITLE
bug with a token serial and URL on /#/token/lost/ page

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#377]
Hello Cornelius!
Here is a small bug, on the
/#/token/lost/ page
when you mark a token as lost you get a page generated temporary password.
Here "lost" and token serial are concatenated together without a white space, therefore the token serial URL is wrong as well
![screenshot_1](https://cloud.githubusercontent.com/assets/2293660/14638015/cda627c0-063d-11e6-8df7-c684190de0cc.png)

**Comment by kolosovski** [comment]
Sorry for the wrong report. :((  It is appeared to be a feature

**Comment by cornelinux** [comment]
Anyway, we could add a link to "lostOATH0041EFD4", so that it is more apearant and will lead to the token details...

**Comment by cornelinux** [comment]
As a matter of fact, it is already done:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.lost.html#L36
