### ISSUE TITLE
%' is not properly decoded by the Privacyidea server

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3770]
Using credential provider 3.4.0
Using Privacyidea 3.8 or 3.9
Ticket 3554

When there is a % in the password of the user, Authentication failed.
If the % is at the beginning or the end of the password, the authentication is successful.

The issue on the side of the credential provider is fixed since the 3.4
https://github.com/privacyidea/privacyidea-credential-provider/releases/tag/v3.4.0
_Fixed a bug where the '%' was not properly encoded when communicating with Privacyidea.

So it must be the decoding of the password on the side of the server that goes wrong

**Comment by cornelinux** [comment]
Add the Credential Provider here:

https://github.com/privacyidea/privacyidea/blob/6b85c6047c7fe7355c01962de8b06532a6548811/privacyidea/api/lib/utils.py#L26-L25
