### ISSUE TITLE
System config checkboxes always show disabled state

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#378]
Hello,

in my privacyIDEA instance (version 2.11.1) I experience the following problem:

Login into WebUI -> Choose Config tab [-> System tab]

In System Config I only enable

- Use @ sign to split the username and the realm.  Increase the failcounter if the wrong PIN was entered.
- Increase the failcounter if the wrong PIN was entered.

Then I save the config. The config is properly saved in database, see:

```
privacyidea=# select * from config;
             Key              |           Value            |  Type  | Description 
------------------------------+----------------------------+--------+-------------
 DefaultChallengeValidityTime | 120                        | None   | None
 DefaultOtpLen                | 6                          | None   | None
 AutoResync                   | false                      | None   | None
 splitAtSign                  | true                       | None   | None
 DefaultSyncWindow            | 1000                       | None   | None
 UiLoginDisplayHelpButton     | false                      | None   | None
 DefaultCountWindow           | 10                         | None   | None
 DefaultMaxFailCount          | 50                         | None   | None
 UiLoginDisplayRealmBox       | false                      | None   | None
 ReturnSamlAttributes         | false                      | None   | None
 PrependPin                   | false                      | public | None
 IncFailCountOnFalsePin       | true                       | None   | None
 OverrideAuthorizationClient  |                            | None   | None
 __timestamp__                | 2016-04-19 14:46:01.414257 |        | 
(14 rows)
```

Leave Config tab, e.g. choose Tokens tab, and then again choose Config tab. In the System Config now all configuration checkboxes seem to be disabled, while the first two checkboxes should be enabled. This behaviour also remains after logging out and logging in again.

In the Web Browser, the retrieved JSON-RPC-Result seems to be OK, so it seems to be a display issue in WebUI:

```
{
    "jsonrpc": "2.0",
    "signature": "15089554128232974882766933492965387840033238793931933492013946069511037738031596700910020500824694609458026544524220685126580565945127348584275232164512976686896221258665090195468112393278757693199534365724017307098258857369677021791324922979919264512665441344647652010703655680306852416959636578887618705204266760869412101548655089046949167238775023600067192284721100475451725213217271271218254823046161469045228062228747710517050807376921143719605783375115841686296089879147526518590097537966530025696941259652177344747614779584085917984213281524322578445090550328526581162223563203373081643657875841591632647776705",
    "versionnumber": "2.11.1",
    "version": "privacyIDEA 2.11.1",
    "result": {
        "status": true,
        "value": {
            "DefaultChallengeValidityTime": "120",
            "AutoResync": "false",
            "splitAtSign": "true",
            "DefaultSyncWindow": "1000",
            "UiLoginDisplayRealmBox": "false",
            "UiLoginDisplayHelpButton": "false",
            "__timestamp__": "2016-04-19 13:33:18.675331",
            "DefaultCountWindow": "10",
            "DefaultMaxFailCount": "50",
            "IncFailCountOnFalsePin": "true",
            "ReturnSamlAttributes": "false",
            "PrependPin": "false",
            "OverrideAuthorizationClient": "172.25.1.4",
            "DefaultOtpLen": "6"
        }
    },
    "time": 1461065778.186598,
    "id": 1
}
```

Can anybody else reproduce this?

Best regards,

Bernd

**Comment by berndnicklas** [comment]
Of course, if I save the form again without re-enabling, all checkbox values are set to disabled (false) in database.

**Comment by cornelinux** [comment]
What data are you running?
PostgreSQL?

Different databases store binary values in different formats. Yours is "true". Obviously the webui does not like this:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/config/views/config.system.html#L66

Right:
https://github.com/privacyidea/privacyidea/blob/d2d72134328f8eb44443a8ccd829fbf2890835b8/privacyidea/static/components/login/controllers/loginControllers.js#L121

This should probably be [true, 1, "1", "True", "true", "TRUE"]...

**Comment by berndnicklas** [comment]
Yes, it's PostgreSQL. Your suggested change to

`
return [true, 1, '1', 'True', 'true', 'TRUE'].indexOf(val) > -1;
`

fixes the problem!
