### ISSUE TITLE
Policy authentication bug in 3.9

### ISSUE THREAD

**Issue by ctosae** [privacyidea/privacyidea#3790]
After upgrading from 3.8.1 to 3.9 the `policy -> authentication -> passthru` **is not working**

```
# echo "User-Name = xxx, User-Password =xxx" | radclient -sx localhost:1812 auth xxx
Sent Access-Request Id 185 from 0.0.0.0:42733 to 127.0.0.1:1812 length 46
        User-Name = "xxx"
        User-Password = "xxx"
        Cleartext-Password = "xxx"
Received Access-Reject Id 185 from 127.0.0.1:1812 to 127.0.0.1:42733 length 53
        Reply-Message = "The user has no tokens assigned"
(0) -: Expected Access-Accept got Access-Reject
Packet summary:
        Accepted      : 0
        Rejected      : 1
        Lost          : 0
        Passed filter : 0
        Failed filter : 1
```

After rollback (VM snapshot)
```
# echo "User-Name = xxx, User-Password = xxxx" | radclient -sx localhost:1812 auth xxx
Sent Access-Request Id 225 from 0.0.0.0:54408 to 127.0.0.1:1812 length 48
        User-Name = "xxx"
        User-Password = "xxx"
        Cleartext-Password = "xxx"
Received Access-Accept Id 225 from 127.0.0.1:1812 to 127.0.0.1:54408 length 48
        Reply-Message = "privacyIDEA access granted"
Packet summary:
        Accepted      : 1
        Rejected      : 0
        Lost          : 0
        Passed filter : 1
        Failed filter : 0
```

**Comment by ctosae** [comment]
> Thank you for filing an issue and sharing your observations or ideas. Please be sure to provide as much information as possible to help us to work on this issue.

When I don't want to assign a token, validation must take place via password (in local realm):

_Reply-Message = "privacyIDEA access granted"_

with the upgrade this no longer works (even if passthru is enabled):

_Reply-Message = "The user has no tokens assigned"_

**Comment by plettich** [comment]
Hi @ctosae 
could You try to ask the API directly?
`curl -d "user=<user>" -d "pass=<password>" http://localhost:1812/validate/check`
You should get something like:
```
  "detail": {
    "message": "against userstore due to 'passthru'",
    "threadid": 140399037761344
  },
  "id": 2,
  "jsonrpc": "2.0",
  "result": {
    "authentication": "ACCEPT",
    "status": true,
    "value": true
  },
```

**Comment by ctosae** [comment]
@plettich thanks for asking

1812 is the Radius port (UDP) usable with radclient 

Here the web commands (pre-upgrare, upgrade, post-upgrade):

```
# curl -k -d "user=xxx" -d "pass=xxx" https://localhost/validate/check`

"detail":{
"message":"against userstore due to 'xxx_authentication'",
"threadid":139938323842624
},
"id":2,
"jsonrpc":"2.0",
"result":{
"authentication":"ACCEPT",
"status":true,
"value":true
},
"time":1698402028.4214945,
"version":"privacyIDEA 3.8.1",
...
```

```
# apt update; apt install privacyidea privacyidea-apache2 -y

[..]
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled
Module rewrite already enabled

             _                    _______  _______
   ___  ____(_)  _____ _______ __/  _/ _ \/ __/ _ |
  / _ \/ __/ / |/ / _ `/ __/ // // // // / _// __ |
 / .__/_/ /_/|___/\_,_/\__/\_, /___/____/___/_/ |_|
/_/                       /___/
                                               v3.9


The file
        /etc/privacyidea/enckey
already exist. We do not overwrite it!

             _                    _______  _______
   ___  ____(_)  _____ _______ __/  _/ _ \/ __/ _ |
  / _ \/ __/ / |/ / _ `/ __/ // // // // / _// __ |
 / .__/_/ /_/|___/\_,_/\__/\_, /___/____/___/_/ |_|
/_/                       /___/
                                               v3.9

<SQLAlchemy engine=mysql+pymysql://pi:***@localhost/pi?charset=utf8>

             _                    _______  _______
[..]
```

```
# curl -k -d "user=xxx" -d "pass=xxx" https://localhost/validate/check

{
"detail":{
"message":"The user has no tokens assigned",
"threadid":140537173894720
},
"id":2,
"jsonrpc":"2.0",
"result":{
"authentication":"REJECT",
"status":true,
"value":false
},
"time":1698402130.8997238,
"version":"privacyIDEA 3.9",
"versionnumber":"3.9",
...```

**Comment by ctosae** [comment]
Note. you can also see versions pre and post upgrade

**Comment by cornelinux** [comment]
Please check your policies.
Also check in the audit log, which policy actually matches in the /validate/check request.

You are looking at the last link in the chain. 
I suspect, that you have a somehow more complex policy setting, which results in the observed behaviour, which would not be hat passthru does not work anymore, but that your policy does not **match** anymore.

**Comment by ctosae** [comment]
Hey @cornelinux how are you?
I've been using privacyIDEA since the first versions.
The problem only appeared with this update.
The same policy is always matched:
![image](https://github.com/privacyidea/privacyidea/assets/75297085/711a6d77-fc77-4870-8176-e04ff1404bf2)

**Comment by ctosae** [comment]
And here the policy. There is only one "auth" with the realm:

![image](https://github.com/privacyidea/privacyidea/assets/75297085/c0f6165b-a74b-4d9e-a1ec-c917eb33d77c)

with action:

`otppin=tokenpin, passthru=userstore, reset_all_user_tokens`

**Comment by cornelinux** [comment]
@plettich Please check if the otppin=tokenpin creates an unwanted side effect

**Comment by plettich** [comment]
@cornelinux The `otppin=tokenpin` does not affect the `passthru` policy. It is checked after the `passthru` policy is handled.

@ctosae Could You check in the privacyIDEA logs if the user actually successfully authenticated against the userstore?

**Comment by ctosae** [comment]
@cornelinux @plettich i found the issue!
After this migration, privacyIDEA is no longer validating local users with passwords with :   _ ! $
Changing it with the same one (Users->Realm->User->Change user->Password) starts working again
The skip format has probably been changed (like \$ etc..)

**Comment by plettich** [comment]
@ctosae which user resolver do You use? Database (which kind of db)?
There shouldn't have been any changes in how the passwords are formatted except for the `%` sign since we use percent-encoded (url-encoded) parameters.

**Comment by ctosae** [comment]
I'm using the standard mysql (apt install).
```
# mysql -V
mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))
```

```
# cat /etc/privacyidea/pi.cfg | grep sql
#SQLALCHEMY_DATABASE_URI = 'sqlite:////etc/privacyidea/data.sqlite'
#PI_AUDIT_MODULE = 'privacyidea.lib.auditmodules.sqlaudit'
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://pi:xxxxx@localhost/pi'
```

**Comment by plettich** [comment]
@ctosae And which user resolver? Where are the users (and passwords) stored? Just to rule out that we somehow broke the password checking.

**Comment by plettich** [comment]
Hi @ctosae it looks like Your password hash does not conform to the given password hashing standard (`{SSHA}` has a max salt size of 16 bytes).
In v3.8 we used a more relaxed version of the hashing function which was replaced in v3.9 with the (strict) version from the `passlib` package.
We are going to enable the relaxed version again in v3.9.1 to allow verification with these hashes again.
Do You know how/when the given password was set?

**Comment by ctosae** [comment]
@plettich thanks for checking.
I don't remember if I used version 3.8.1 to create that user.
Before this I was using 2.11.x
Now that we understand the issue I could reset passwords that don't have tokens (there are few) all other users use tokens

**Comment by ctosae** [comment]
Tested 3.9.1 and it's working!
Thanks
