### ISSUE TITLE
Only 10 users listed in the UI, although the database has more

### ISSUE THREAD

**Issue by AndreC10002** [privacyidea/privacyidea#3791]
Our setup is very simple, PrivacyIDEA 3.9 configured to use a local SQLite database, only one realm and the UI is accessible through Apache with WSGI. The problem is the "Users" tab only shows 10 users, although the database has more than that. The "total users" count is always 10, no matter how many there are, and the list of users only shows 10 of them, ordered by id. We only have one realm, so it is not a matter of users in a different realm.

We were previously running PrivacyIDEA 3.7 when the bug was found, upgrading to the latest (3.9) didn't fix it.

Thank you.

**Comment by plettich** [comment]
Hi @AndreC10002 
could it be that the Limit for getting users from the database is set to 10?
![user_limit](https://github.com/privacyidea/privacyidea/assets/37443810/1da4ebf0-b98b-43f8-af0d-1ef5eedc769f)

**Comment by plettich** [comment]
Just FYI, the limit does not impact the authentication of a single user. It just to reduce load on a big database.
