### ISSUE TITLE
Verify enroll is generating a second TAN list

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3809]
privacyidea 3.8.1
ubuntu 20
Customer: 3858

If we roll out a TAN or a PPR list via the PI GUI, the following happens:

- A TAN list is displayed including the dialog box for entering the verification TAN.
- I save the TAN list and enter the first TAN in the dialog box.
- The TAN is accepted, the token is also successfully set to: enrolled_state = enrolled.
- 
- BUT: now I am shown a completely new TAN list that does not match the first.
This new TAN list is then also the valid list that I have to use for authentication.

![BBA2](https://github.com/privacyidea/privacyidea/assets/95854213/125ad326-296a-4c5e-a906-56b9fec34342)

**Comment by cornelinux** [comment]
@sepp67  How do you policies look like? Why would you verify-enroll a TAN list?

**Comment by cornelinux** [comment]
Verify-ernoll is not implemented in tantoken.

**Comment by plettich** [comment]
Merged into master
