### ISSUE TITLE
New structure for tokenjanitor

### ISSUE THREAD

**Issue by jona-samuel** [privacyidea/privacyidea#3820]
After the update from flask we can use nesting of click.group for a new structure of the tokenjanitor and for implementation of #3736.
For more details on the new structure please look here: https://github.com/privacyidea/privacyidea/wiki/concept:-Migrate-to-click-framework

**Comment by jona-samuel** [comment]
We can also implement #1653

**Comment by nilsbehlen** [comment]
this has no additional information for #3955, so it is closed.
