### ISSUE TITLE
changing realm of a token that has a user assigned is breaking it

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3821]
privacyidea 3.9.1
ubuntu 20

On the web interface, changing the realm of a token that still has a user asigned, breaks this token.
![realm1](https://github.com/privacyidea/privacyidea/assets/95854213/212aac6d-f2cc-4a8a-839b-c92862ee2175)
The token is still shown as active on the tokens view, but it is in fact disabled. No action on the token is then possible.
![realm3](https://github.com/privacyidea/privacyidea/assets/95854213/8a2d7c29-d6c2-42b9-b23c-11e378b81ea4)

The only thing that is then possible is to delete it with the token janitor.
![realm2](https://github.com/privacyidea/privacyidea/assets/95854213/b6270ecc-e73e-4fa7-ba3f-90d43130731c)

You need first to unassign a token. Then you can change the realm.
On the web interface, it shouldn't be possible to change the realm of a token that still has a user assigned.

Kind regards

seabastien

**Comment by cornelinux** [comment]
@sepp67 What do you suggest as expected behaviour?

**Comment by sepp67** [comment]
I suggest that the button ¨Edit¨ to change the realm is inactive when the token has a user assigned.

**Comment by plettich** [comment]
We could try to disable/hide the checkbox for the realm of the assigned user to avoid manipulating it.
However we should also take a look what the API does in this case to avoid misconfiguration.

**Comment by nilsbehlen** [comment]
this has been done via #3986. The realm of the user can not be removed in the webui.
