### ISSUE TITLE
Migration for external Audit DB

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3824]
In case the audit log is send to a different database using `PI_AUDIT_SQL_URI`, possible migrations of the audit table will not be applied.
We should check for the existence of that configuration in the `pi.cfg` and either apply the migrations to the external table as well (need to check how to use a different db in alembic) or  give a note to the user to apply the changes themselves.

**Comment by cornelinux** [comment]
@plettich Which CC is it?

**Comment by plettich** [comment]
@cornelinux 

> @plettich Which CC is it?

You can search for the issue number in the ticketing system. I try to avoid posting internal data here.

**Comment by cornelinux** [comment]
We add docs:

* in the description within pi.cfg
* in the READ-BEFORE-UPDATE
   * a generic comment
   * comments in the upgrade steps, where the audit log schema was changed
