### ISSUE TITLE
Push EMail

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3826]
With the PUSH token we deliver an authentication request to the user. By clicking yes and sending this yes to the privacyIDEA server, this authenitcation request is valid in the privacyIDEA server.

We could use this building blocks to create an Email Token, that sends a link in an email to the user.
Clicking the link would mark the authentication request as valid in the privacyIDEA server. The same workflow like with push tokens could continue. 

Plus side: The user would not have to enter anything.

Down side: Besides security this could be confusing with all the windows: 
1. User tries to e.g. login in browser window A with keycloak.
2. User has to open his email client and click ths link which would...
3. ...open a browser window B...
4. Then he would have to manually return to browser window A.

**Comment by nilsbehlen** [comment]
The window handling becomes complicated and annyoing so we wont do that for now.
