### ISSUE TITLE
Indexed Secret: challenge can ask for same position multiple times

### ISSUE THREAD

**Issue by aburch** [privacyidea/privacyidea#3832]
https://github.com/privacyidea/privacyidea/blob/6e070ad5ef528820bca1c8b70f4c20e38ad8cc65/privacyidea/lib/tokens/indexedsecrettoken.py#L220

This chooses `position_count` positions, but allows choosing the same positions several times (drawing with replacement).
A challenge should probably consist of `position_count` *different* positions.
As this reduces the knowledge an attacker needs to successfully pass the challenge, it is probably security relevant as well.

It might also be user-friendly to sort the requested positions by their index.

**Comment by cornelinux** [comment]
This is an old topic.
We are not planning to do this.

**Comment by plettich** [comment]
Just FYI: the other issue was #3829 
This token-type was a contract work with these specifications, that is why we don't plan to change this.
