### ISSUE TITLE
Is there a feature that cause token to only scanned on one device? like hotp totp or even push token

### ISSUE THREAD

**Issue by svampire7** [privacyidea/privacyidea#3840]
I want this feature to mitigate user add a token in multiple devices and only use one device as source of truth

is it possible?

**Comment by svampire7** [comment]
I tried to make scan of qr token or any other token to be possible only in one mobile device.

when you scan a qr code it will be scan and multiple device and enrollment process.

I think the qr code needs a connection to privacyidea server in order to check if the device is already registrated

**Comment by plettich** [comment]
You can use 2-Step enrollment to prevent multiple enrollment of the same token:
https://privacyidea.readthedocs.io/en/v3.9/workflows_and_tools/2step/index.html
Basically the app generates part of the secret during rollout which then has to be entered in the server to complete the rollout.
As far as i know this currently only works with the privacyIDEA App.
You should get an error if the token is already enrolled (same for the Push-Token).

**Comment by cornelinux** [comment]
I take the liberty in closing this, since this can be achieved by using the privacyIDEA authenticator aus plettich said.
