### ISSUE TITLE
Problem with LDAP resolver('utf8' codec can't decode byte 0xd6 in position 0)

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#385]
Hello Cornelius!
Hope you're doing well!
I'd faced problem with my LDAP(AD) resolver after tried to change UID Type from "DN" to "ObjectGUID". When I installed PI, "DN"  was value by default of UID Type in AD preset, but now we've realized that we need to have the absolute User ID in the PI database, because if user moves between containers in AD or if it would be renamed(in case of marriage or divorce) someone will need to re-bind all the user's tokens to the new name.. Having ObjectGUID(which now PI proposes as a default value) as a user ID would solve the issue. SO after I changed "DN" to "ObjectGUID" in one of my resolver and navigated to
/#/user/list
selected the corresponding realm which resolver we had just changed, I got the red message
![image](https://cloud.githubusercontent.com/assets/2293660/14784224/1f7ee988-0afd-11e6-9b05-0539bb5eb55e.png)
The privacyidea.log shows the following exception:
https://gist.github.com/kolosovski/e6609b32e66d3ebb58b11f14d0ee7383

Unfortunately I can't just paste here the whole contents of the log file as in debug mode it contains quite a lot private user information, so maybe you could take a look at the problem and request additional info if needed or request some tests to perform which could help you to find the cause?

PI ver is 2.11
AD is running on Win 2012

**Comment by cornelinux** [comment]
Yes. In get_users there is something that can not be decoded.

  File "/usr/lib/python2.7/dist-packages/privacyidea/api/user.py", line 104, in get_users
    return send_result(users)

The byte 0xd6 exspect certain bytes after it - the continuation byte. So what is the next byte behind the 0xd6? It seems to be invalid for any reason.

**Comment by kolosovski** [comment]
In PI log by searching for xd6 char I've found this user ID:
"\xd6,-V@\x03'J\x85<\x88\x8c|\xdf.\\"
it appeared like
PROTOCOL:SEARCH response entry <{'dn': '...some DN...', 'attributes': {'telephoneNumber': [u'...some telephone...'], 'sAMAccountName': [u'...some name...'], 'mobile': [u'...some telephone...'], 'objectGUID': ["\xd6,-V@\x03'J\x85<\x88\x8c|\xdf.\\"], 

Found this userlist: [{'username': u'...some name...', 'surname': u'...some name...', 'mobile': [u'...some telephone...'], 'editable': False, 'userid': "\xd6,-V@\x03'J\x85<\x88\x8c|\xdf.\\", 

Exiting get_user_list with result [{'username': u'...some name...', 'surname': u'...some name...', 'mobile': [u'...some telephone...'], 'editable': False, 'userid': "\xd6,-V@\x03'J\x85<\x88\x8c|\xdf.\\", 

in fact this user in AD has the following ObjectGUID:
{562D2CD6-0340-4A27-853C-888C7CDF2E5C}

**Comment by cornelinux** [comment]
which version of privacyIDEA are you running?

Your userids should not look like the binary string "\xd6,-V@\x03'J\x85<\x88\x8c|\xdf.\" but like 562D2CD6-0340-4A27-853C-888C7CDF2E5

**Comment by kolosovski** [comment]
As I mentioned above, I run privacyIDEA version 2.11

**Comment by cornelinux** [comment]
As mentioned the LDAP-Resolver should return the readable GUID like "039b36ef-e7c0-42f3-9bf9-ca6a6c0d4d77".

So something might be wired here in your setup which causes the wrong behaviour in this line:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/LDAPIdResolver.py#L425

What is your case sensitive UIDType?

**Comment by kolosovski** [comment]
> What is your case sensitive UIDType?
you mean the setting "UID Type" from the resolver configuration page? It is equal "ObjectGUID"

You are right.... It was my fault :( I've doublechecked and the correct attribute name is **o**bjectGUID. After changing to it the user list loads just fine.
So maybe you'll find a place in your todo list to improve the code to validate the input in LDAP resolver settings and notify a user if there's no such attribute, if it is possible.. I could save people few hours :)
And this may be closed. Thank you very much for the hint!

**Comment by cornelinux** [comment]
Hm, I could. But this is no word processor. It is a highly technical administrative tool, not to be used without the understanding of the underlying processes,
... following the principle shit it shit out. ;-)

Anyways, glad it worked out! I'll add at least a note on this.

**Comment by kolosovski** [comment]
you're right, it's not a word processor :)
but when a user sees alert "'utf8' codec can't decode byte 0xd6 in position 0: invalid continuation byte" I don't know what it should guess :). Even if it is an information for developer, developer successively can see it in the log.. I just talking about maybe it could be more informative in alerts :)


But unfortunately the problem isn't completely gone.
Yesterday I checked that user list displays well and didn't even suppose that there may be further issues. The issue is  - now, after changing "UID Type" to objectGUID, when I enroll a new token and assign it to a user in a realm which consists of an LDAP resolver(with objectGUID) it displays like:
![image](https://cloud.githubusercontent.com/assets/2293660/14819526/3b10c1fc-0bcb-11e6-8b5b-8f2c163583bd.png)

in audit logs there's no exceptions but:

[2016-04-26 15:47:55,940][2501][140704858150848][DEBUG][privacyidea.lib.user:118] Entering get_username with arguments (u'd29e9cdd-980a-4718-8eca-e7033bdfd35f', u'AD') and keywords {}
[2016-04-26 15:47:57,252][2501][140704858150848][DEBUG][privacyidea.lib.user:129] Exiting get_username with result 

The token list also doesn't contain username
![image](https://cloud.githubusercontent.com/assets/2293660/14819852/b1319c52-0bcc-11e6-877e-b97feb419de9.png)
But if I navigate to the user, PI lists the token:


To make sure it isn't a set-up issue I set-up PI 2.11 in sandbox VM, fresh, created new and the only one resolver and realm and one token, tried to link it to an AD user. The same result...
What could be the problem with?

**Comment by cornelinux** [comment]
Probably your LDAP resolver is misconfigured at another spot. Please double check your configuration.

**Comment by kolosovski** [comment]
The problem was in outdated LDAPIdResolver.py (of release 2.11) code..
I replaced it with the one from master and it works as expected now

**Comment by cornelinux** [comment]
Thank you for being persistent!

The method getUserInfo is responsible for returning user information for a userid (in this case the objectGUID). 
The display string must be reformatted to the binary representation:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/LDAPIdResolver.py#L294

If it is not, than the user object will not be found.

**Comment by kolosovski** [comment]
Yes, this is exactly the place where I ended up with debugging and analyzing the code.
It appeared that my LDAPIdResolver.py getUserInfo generated this query string:
```
(&(&(sAMAccountName=*)(objectClass=person))(objectGUID=d29e9cdd-980a-4718-8eca-e7033bdfd35f))
```
which didn't dive any result(both debug and tcpdump are evidence)
but the new one generates this query:
```
(&(&(sAMAccountName=*)(objectClass=person))(objectGUID=dd:9c:9e:d2:0a:98:18:47:8e:ca:e7:03:3b:df:d3:5f))
```
which does the job pretty well!
