### ISSUE TITLE
requirement.txt is disorder

### ISSUE THREAD

**Issue by cinjoseph** [privacyidea/privacyidea#386]
there are so many depedence pkgs arg out-of-order. so, there are a lot of errors occor when I run pip install -r requirement.txt, please check the requirement's order.

**Comment by cornelinux** [comment]
what do you mean with out-of-order/disorder?

can you please be more specific?

**Comment by cinjoseph** [comment]
because，i was in chain, we were separated. for example, if i want to install bcrypt==1.1.0, but it depends on cffi==0.8.6, but cffi==0.8.6 is under the bcrypt==1.1.0. so it would get cffi auto on pipy.python.org when i install bcrypt==1.1.0. but we can't access pipy.python.org......so, the installation failed. 
can you understand my poor english?  or can anyone speak chinese?

**Comment by cinjoseph** [comment]
I have resolved this problem, just  add file  ~/.pydistutils.cfg , designated the source of pip/setup.py
