### ISSUE TITLE
Error when installing privacyIDEA 3.9.2 with an MariaDB Galera Cluster

### ISSUE THREAD

**Issue by lefe8** [privacyidea/privacyidea#3863]
### Top-level intent

I've tried installing privacyIDEA 3.9.2, which comes with SQLAlchemy 1.4, with a MariaDB Galera cluster as a token database. An error, which I've described below, occurred and the installation did not succeed.

### Steps to reproduce

1. Set up a database with the current long-term versions MariaDB 10.11 and Galera 26.4.
2. Install privacyIDEA 3.9.2 from PyPI on a fresh Ubuntu 22.04 server.
3. Run the command "pi-manage create_tables" inside the virtual environment.

### Expected outcome

The tables should be initialized.

### Actual outcome

You'll get the error message from the "Error" section and the table creation will fail.

### Further scenarios

I've also tested the following additional scenarios during error handling:

privacyIDEA 3.8.1. + MariaDB Single Node: Succeeded
privacyIDEA 3.8.1. + MariaDB Galera Cluster: Succeeded

privacyIDEA 3.9.2. + MariaDB Single Node: Succeeded
privacyIDEA 3.9.2. + MariaDB Galera Cluster: Failed

### Configuration

* **privacyIDEA version**: 3.9.2
* **Installation method**: PyPI
* **Python version**: 3.10
* **Operating system**: Ubuntu 22.04
* **Webserver**: Apache HTTP
* **Token database**: MariaDB Galera Cluster

### Error

pymysql.err.NotSupportedError:(1235, "This version of MariaDB doesn't yet support 'CACHE without INCREMENT BY 0 in Galera Cluster'")

### Assumption

It appears that SQLAlchemy 1.4 reports that the database supports sequences because of the "mariadb" dialect. This is true in theory, but Galera does not yet support this. It seems as if the "dialect_supports_sequences()" function is missing a check as to whether replication with Galera is being used.

Here's a search for the function I mentioned:
https://github.com/search?q=repo%3Aprivacyidea%2Fprivacyidea%20dialect_supports_sequences&type=code

At this point in the code, it appears that this has already been thought of:
https://github.com/privacyidea/privacyidea/blob/9d8b5e5fff5bfe47f5e0b15c465802126220bc5d/migrations/versions/5cb310101a1f_.py#L29

**Comment by plettich** [comment]
I can confirm this issue. We are working on a fix.

**Comment by plettich** [comment]
> MariaDB in a Galera config requires INCREMENT BY 0 (see [here](https://github.com/MariaDB/server/blob/fe07ac31b12088b49db58a1ecae0ea5fd1f0c678/sql/sql_table.cc#L4834)).
> 
> For now, you could add increment=0 as an option to every Sequence in privacyidea/models.py and it would be able to create the database.

Unfortunately this breaks the PostgreSQL support since Postgres doesn't like an increment of 0.

I think the best way forward is to use the [Identity](https://docs.sqlalchemy.org/en/14/core/defaults.html#sqlalchemy.schema.Identity) construct which is provided by SQLAlchemy 1.4. Preliminary tests show that it works for MySQL, MariaDB and PostgreSQL as well as Galera-Cluster.
We still have to check how this affects a database migration from a previous version.

**Comment by plettich** [comment]
Closed with #3910
