### ISSUE TITLE
Username aliases

### ISSUE THREAD

**Issue by rf152** [privacyidea/privacyidea#387]
Not a bug, but a feature request.

It would be useful to be able to have a method to translate username aliases to usernames. So, for example, if my username is jbloggs, and I want to authenticate using admin_jbloggs.

This is useful for systems where you have a separate admin and user level access done on usernames, but want to back it off to the same backend user.

If you can point me in a direction then I'm happy to have a go at implementing this.

**Comment by cornelinux** [comment]
You could use different realms.

The user jbloggs is in the default realm. Now define a second realm "admin",  than contains the same user.

Authenticating with "jbloggs" will take you to the normal user. Authenticating with "jbloggs@admin" will be the administrative account. Using remote tokens you can even use the same physical tokens for both accounts.

**Comment by rf152** [comment]
Indeed, that does work, but when using the system for a large number of users, who are not able to / interested in creating remote tokens for all of their TOTP tokens, it would become unworkable.

I've managed to work it in code, by manually editing LDAPIdResolver.py, adding a 

```python
if ret[:6] == 'admin_':
	ret = ret[6:]
```

Which notices and then strips out the admin_, however any time I do an update I will have to re-implement.

**Comment by cornelinux** [comment]
Hi Richard,

very cool, that you digged into it and found a place to implement.
But I hope you realize that his is not the way we would do thin is privacyIDEA ;-)
It is hard coded, bad practice, will break if there is a user, with the original username *admin_bear*.

So you have your users manage their tokens themselves?
And you expect them to either use *usernamA* oder *usernameB*?
You expect a lot from them...

Let me rethink this. You application is not capable of a sensible authorization management.

Your users are managed within LDAP, openldap or Active Directory. So why suddenly start to "manage" users in privacyIDEA by adding a second useraccount *admin_username*?

Wait! Each user also has an admin account? And each user can login into your application either as user or as admin? And decide this on her own?

I really like to understand your real requirement here...

Kind regards
Cornelius

**Comment by cornelinux** [comment]
Hi Richard,

hm. I totally forget about 30% of the features reguarly.

I think "mangle" is the thing you are looking for:

http://privacyidea.readthedocs.org/en/latest/policies/authentication.html?highlight=mangle#mangle

Kind regards
Cornelius

**Comment by cornelinux** [comment]
When you are done, you can add your example here:

https://github.com/privacyidea/privacyidea/blob/master/doc/policies/authentication.rst#mangle

**Comment by rf152** [comment]
Hi Cornelius

Totally agree that's not the way to do it - as you say, if a username has admin_ before it, it'll break the system, was just saying that was the only way I'd managed to get it to work!

The exact requirements is actually around Check Point management and using generic users for VPN. It's quite specific, I realise!

Because of the way it handles user authentication, you have to have a different username for administrative accounts and VPN users. There exists only one user in the LDAP backend (it's MS AD), but there needs to be two separate usernames available for Check Point to use.

So if logging into the VPN, the user will use "jbloggs"
And if logging into the Check Point administrative system, they will use "admin_jbloggs"
But both users should go back to the AD user jbloggs (and use the same token, etc).

I will have a look at mangle and see if that achieves the same thing!

Thanks,
Richard
