### ISSUE TITLE
Remote token does not set local_checkpin when set to 0

### ISSUE THREAD

**Issue by rf152** [privacyidea/privacyidea#388]
When creating a new token, leaving the local_checkpin as 0 does not create the entry in the database.

This then causes a "TypeError: int() argument must be a string or a number, not 'NoneType'" error when trying to authenticate

**Comment by cornelinux** [comment]
Booleans, and integers are often treated in different ways by different databases. (0, '0', False, false...)
What database are you using?

**Comment by rf152** [comment]
MySQL

Looking at the table, the parameter and value doesn't exist in the table. When I put it in manually (with an INSERT), then it works absolutely fine.

Looks like it's just not getting INSERTed when the token gets created.

**Comment by cornelinux** [comment]
The parameter is not passed by the web ui.
