### ISSUE TITLE
dpkg: error processing package privacyidea-apache2 (--configure)

### ISSUE THREAD

**Issue by BJimmyraja** [privacyidea/privacyidea#3880]
### Top-level intent

What did you try to achieve?

### Steps to reproduce

1. I tried manually install the package  with : http://lancelot.netknights.it/community/jammy/stable/pool/main/p/privacyidea/privacyidea_3.8-1jammy_amd64.deb
2. then run the command sudo dpkg -i [package-name].deb
3.  apt install privacyidea-apache2

### Expected outcome

running the privacyidea application

### Actual outcome

dpkg: error processing package privacyidea-apache2 (--configure)

### Configuration

* **privacyIDEA version**:
* **Installation method**: (from Ubuntu packages, github, PyPI, ...)
* **Python version**:
* **Operating system**:
* **Webserver**:
* **Token database**: (MySQL, PostgreSQL, ...)

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by pablo-knight** [comment]
Hallo BJimmyraja,

please follow the installation guide on:
https://privacyidea.readthedocs.io/en/latest/installation/ubuntu.html

dpkg don't solve Dependencies!!
