### ISSUE TITLE
E: The repository 'http://lancelot.netknights.it/community/bionic/stable focal Release' does not have a Release file.

### ISSUE THREAD

**Issue by BJimmyraja** [privacyidea/privacyidea#3881]
### Top-level intent

What did you try to achieve?

### Steps to reproduce

1.
2.
3.

### Expected outcome

What do you think, how the system should have worked?

### Actual outcome

What did actually happen?

### Configuration

* **privacyIDEA version**:
* **Installation method**: (from Ubuntu packages, github, PyPI, ...)
* **Python version**:
* **Operating system**:
* **Webserver**:
* **Token database**: (MySQL, PostgreSQL, ...)

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by pablo-knight** [comment]
Hello BJimmyraja,

I'm guessing that you did a do-update-release and did not customize the repo link after the OS upgarde.

Your repo link:

`http://lancelot.netknights.it/community/bionic/stable focal`

should look like this if an operating system upgrade from Ubuntu 18 (bionic) to Ubuntu 20 (focal) was done.

`http://lancelot.netknights.it/community/focal/stable focal`


More info see installation guide:
https://privacyidea.readthedocs.io/en/latest/installation/ubuntu.html
