### ISSUE TITLE
login_text in webui policy is not applied

### ISSUE THREAD

**Issue by gerdesj** [privacyidea/privacyidea#3896]
I've just noticed that the login_text policy is no longer applied.  It shows "

- One webui scoped policy with a priority of 1
- Action -> miscellaneous -> login_text: checkbox is ticked and some text is entered in the textbox
- Tested with private browsing mode
- Current PI version: 3.9.2
- Ubuntu 22.04 VM (jammy)
- Install source: deb [signed-by=/usr/share/keyrings/netknights.gpg] http://lancelot.netknights.it/community/jammy/stable jammy main
- Everything updated and rebooted

This worked in the past and according to our Changelog we started out with 3.9.1.

I have tried unticking, saving, logging out and in, re-ticking, adding the text and logging out. No joy.

**Comment by plettich** [comment]
Hi @gerdesj i can not reproduce this. The login text is properly displayed. Did You reload the browser-tab? The text gets pulled in on fresh (re-)load of the page, after that it isn't changed.

**Comment by gerdesj** [comment]
I've tried multiple browser and their private mode and another two computers that have never seen our PI.  I'll (re)double check the policies, given you can't reproduce.  There must be something odd on my instance.

Thank you for your time.

**Comment by cornelinux** [comment]
@gerdesj How does your policy look like in detail? Note, that the login text can not e.g. handle realms, users and resolvers for reasons.

**Comment by gerdesj** [comment]
> @gerdesj How does your policy look like in detail? Note, that the login text can not e.g. handle realms, users and resolvers for reasons.

It is two simple plain text words.  I've just tried removing it and adding in something random - no change. 

I'm now looking to see where form-signin-heading gets piLoginText from ...

**Comment by gerdesj** [comment]
I've checked what the action column for the policy looks like in the database and login_text is set correctly and changes when I update the policy in the web UI.  I changed the token_page_size and user_page_size in the web UI and that took effect.

**Comment by plettich** [comment]
Hi  @gerdesj Do You use a customized `index.html`? The login text gets injected into the `index.html` before it is send to the browser.
Can You verify that there is something like
```html
<input type=hidden id="LOGIN_TEXT" value="the login text">
```
in the `index.html` sent from the server?

**Comment by gerdesj** [comment]
I have not customized index.html.  The main part of it looks like this on disc - /opt/privacyidea/lib/python3.10/site-packages/privacyidea/static/templates/index.html:
```

<input type=hidden id=REMOTE_USER value="{{ remote_user }}">
...
<input type=hidden id="LOGIN_TEXT" value="{{ login_text }}">
...
<input type=hidden id=PI_TRANSLATION_WARNING value="{{ translation_warning }}">

```
and that includes the input you mention.  I see the same in dev tools in my browser.

**Comment by plettich** [comment]
> and that includes the input you mention. I see the same in dev tools in my browser.

So when viewing the main page in the dev-tools there is a line `<input id="LOGIN_TEXT" type=hidden value="Your custom text">`?
But the custom text is not displayed? 
We use JavaScript to extract the custom text and insert it here:
https://github.com/privacyidea/privacyidea/blob/5f8be0f7b21ba6a542e83e3f9ecf4229a9c0eaa5/privacyidea/static/components/login/views/login.html#L50-L53
It looks like the variable `piLoginText` is not initialized properly here:
https://github.com/privacyidea/privacyidea/blob/5f8be0f7b21ba6a542e83e3f9ecf4229a9c0eaa5/privacyidea/static/components/login/controllers/loginControllers.js#L70-L71
Do You have any messages in the the dev-tools console?

**Comment by gerdesj** [comment]
The only messages in the console are:

```
InstallTrigger is deprecated and will be removed in the future. constants.js:50:14
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.
```

I'm not an expert with dev tools 8)  I have found loginControllers.js?v=20240112T233317 in the sources tab in dev tools.  That code is on line 76-77 here and not 70-71 as within your comment.

**Comment by beckerr-rzht** [comment]
I have the same problem and played around a little in source code.
This dirty hack "fixes" the problem and ensures that "login_text" is displayed.

`./lib/python3.8/site-packages/privacyidea/webui/login.py:161`
```python
    login_text = Match.action_only(g, action=ACTION.LOGIN_TEXT, scope=SCOPE.WEBUI) \
        .action_values(unique=True, allow_white_space_in_action=True, write_to_audit_log=False)
#    if len(login_text) and list(login_text)[0] and sub_state not in [1, 2]:
#        login_text = list(login_text)[0]
#    else:
#        login_text = ""
    login_text = list(login_text.keys())[0]
```
But beware, this hack is not a solution. At best, it helps to localize the cause of the problem!

The problem seems to be related to `Match.action_only` and in particular whether a dict or an array is returned.

**Comment by beckerr-rzht** [comment]
I have the same problem and therefore looked at the source code:
```python
# ./lib/python3.8/site-packages/privacyidea/webui/login.py:161
    login_text = Match.action_only(g, action=ACTION.LOGIN_TEXT, scope=SCOPE.WEBUI) \
        .action_values(unique=True, allow_white_space_in_action=True, write_to_audit_log=False)
    if len(login_text) and list(login_text)[0] and sub_state not in [1, 2]:
        login_text = list(login_text)[0]
    else:
        login_text = ""
```
`login_text` is apparently only set if `sub_state` has neither the value `1` nor the value `2`.

`sub_state` is defined here using `subscription_status()`:
```python
# ./lib/python3.8/site-packages/privacyidea/webui/login.py:143
   sub_state = subscription_status()
```
And `subscription_status()` is this:
```python
# ./lib/python3.8/site-packages/privacyidea/lib/subscriptions.py:93
def subscription_status(component="privacyidea", tokentype=None):
    """
    Return the status of the subscription

    0: Token count <= 50
    1: Token count > 50, no subscription at all
    2: subscription expired
    3: subscription OK

    :return: subscription state
    """
...
```
#### Conclusion

`login_text` can only be used if there are less than 50 tokens or if there is an active subscription.

**Comment by gerdesj** [comment]
> I have the same problem and therefore looked at the source code:

...

> #### Conclusion
> 
> `login_text` can only be used if there are less than 50 tokens or if there is an active subscription.

Well spotted.  I have a fix and I think we can safely mark this issue as: "working as intended".
