### ISSUE TITLE
Support autoenrollment via SMS

### ISSUE THREAD

**Issue by splashx** [privacyidea/privacyidea#391]
[Trackback:](https://github.com/privacyidea/privacyidea/blob/c709e2058cf3f089a727e014f069e80b5e934676/doc/faq/rollout-strategies.rst#id1) 

Considering printing and mailing could take a long time, a fast-tracked option via SMS or email could be supported.

Proposal: 
A first-time user who exists in privacyidea user store or in a external user store (e.g. LDAP) visits the webgui and is welcomed with username/password form (this means there is no REMOTE_USER header set).
The user enters its username and password and if: 
A) The user is successfully authenticated against the userstore, the browser is redirected to a page where the user must enter a SMS code. Meaning: Privacyidea should generate a one-time SMS token for this user (or a SMS token with a validity of a few minutes - since time-based token validity is already implemented). If the SMS otp is successfully authenticated, the user is authorized to proceed to the webgui (for enrollment).
If the SMS fails, the user is denied access (maybe allow N more attempt, N<=3)

Checks: if one of " mobile" / "phone" or "email" attribute is set for the user (if not, another error message should be displayed - "There is no mobile number set for user %u, please contact the identity manager").

B) The user is not successfully authenticated against the userstore,  the webpage should display a "Login failed against backend user store, check your username  / password". 

This is not the same as enrolling a SMS token because ultimately the user should not have a SMS token available to perform logins - but only the default token + allowed tokens (which may or may not include SMS). Also, SMS token auto-assignment [asks the user](https://github.com/privacyidea/privacyidea/blob/c709e2058cf3f089a727e014f069e80b5e934676/doc/configuration/tokens/sms.rst) for a mobile number (which, in this case, should not be necessary because this should be already set in the userstore).  

This could be an option under the scope "enrollment" and aciton "autoenrollment" with values "email" and "sms" (the email part could even use part of the code from [register](https://github.com/privacyidea/privacyidea/blob/c709e2058cf3f089a727e014f069e80b5e934676/doc/policies/register.rst)).

Thoughts?

**Comment by cornelinux** [comment]
What do you want to achieve?
You want the user to have an SMS token?
And you want the user to authenticate with this SMS token to the WebUI?

This is already possible.
You can create a script to enroll an sms token to all users.
Now every user has an SMS token. Configure the policy to require auth in WebUI against privacyIDEA.
done.

**Comment by splashx** [comment]
Not quite (SMS token for all users). 

Think of a scenario where users must have, for operational purpose, TOTP. No other kinda of token (for daily operations). 
But you want to enroll the user with a 2FA method - not only password.
The user should be able to e.g authenticate with password, if successful that would trigger an SMS token creation, assignment and submission of a OTP to the users mobile. With that the user can login to the webgui and enroll TOPT. 


Since privacyidea doesn't have an automatic trigger for creation and assignment one-time SMS token, I'm using another software+radius to accomplish this. 
I'm currently using privacyidea with the following policies to accomplish this: 
- authentication: radius, privacyidea
- webgui: default totp

**Comment by cornelinux** [comment]
You can use the client IP in the authorization policy to allow TOTP for operational use and SMS for login to the webui.

You can also restrict the max_usage of a token (to 1)

Well, in fact than the user would have a token and would not get the reduced enrollment wizard view.

**Comment by cornelinux** [comment]
Event: User logs in
Condition: User has not token
Action: privacyidea sends a registration code via SMS.

To me this looks like a case for event handling in #360.

So I guess I close this issue.
@splashx Please give any additional comment to get a cool event handling thingy.

**Comment by splashx** [comment]
@cornelinux you nailed it. Event handling would cover that use case 👍 
Essentially, in this use case we can auto-generate tokens and send the OTP to the user using an already  known information (e.g. email address, mobile phone number). 
This is typically what IdM systems will push to LDAP  when a new user joins an enterprise - name, surname, email address, physical address, mobile number - the user will already have a pgp key or s/mime certificate - in this case we even have information to encrypt the email containing the OTP (brainstorming ahead, surely a minor feature).

**Comment by cornelinux** [comment]
Only challenge remains, that if an SMS token would be autogenerated, the user would possess a token. I.e. if he logs in he will not get the reduced enrollment wizard.

**Comment by splashx** [comment]
**Option A:** Tokens should have a "property" field maybe: tokens which are auto-generated should be marked internally as "autogenerated". 
That way if the reduced enrollment wizard is set on a webgui policy, when processing the policy we should consider only those tokens which were not autogenerated (that would mean the auto wizard [description](http://privacyidea.readthedocs.io/en/latest/policies/webui.html#tokenwizard) would change to (change in bold):

> "If this policy is set and the user has no tokens **(excluding autogenerated ones)**, then the user will only see an easy token wizard to enroll his first token. If the user has enrolled his first token and he logs in to the web UI, he will see the normal view."

**Option B:** Another approach is to threat autogenerated tokens as ephemeral tokens - they should be created on the fly then immediately purged (unassigned + deleted) using the standard functions (so it can be audited). That's probably easier to implement and cleaner.

Thoughts?

**Comment by yangboyd** [comment]
> Event: User logs in
> Condition: User has not token
> Action: privacyidea sends a registration code via SMS.
> 
> To me this looks like a case for event handling in #360.
> 
> So I guess I close this issue.
> @splashx Please give any additional comment to get a cool event handling thingy.

Hi Cornelinux, 

How to choose this action "Action: privacyidea sends a registration code via SMS." in the action editor?

There is action about enroll a sms token. What is the action to trigger SMS challenge?
