### ISSUE TITLE
Bug report - token description

### ISSUE THREAD

**Issue by h-meier** [privacyidea/privacyidea#3944]
If you enter a string that is too long in the "Description" field of an email token, an error is generated in the UI. However, the token is created without a description. This creation is not visible at first glance. One think that no email token has been created, but in fact it has been created.

The frontend (and of course the backend) should therefore at least perform an input validation.
Errorlog and a screenshot attached.

![token-error(1)](https://github.com/privacyidea/privacyidea/assets/164146074/5ccd53a7-c07f-45e9-8faf-bb5174463613)

[pi_log.log](https://github.com/privacyidea/privacyidea/files/15345999/pi_log.log)

**Comment by cornelinux** [comment]
@h-meier could you please look into the privacyidea.log and the apache error log to provide some more insights on the cause?

**Comment by nilsbehlen** [comment]
see #3747

**Comment by h-meier** [comment]
> @h-meier could you please look into the privacyidea.log and the apache error log to provide some more insights on the cause?

@nilsbehlen Nils was faster than me. Do you still need the logs? Guess not.

**Comment by nilsbehlen** [comment]
@h-meier the other issue has the information so its alright ;)
