### ISSUE TITLE
Use OverrideAuthorizationClient setting (or policy field) for validating proxy requests

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#395]
Actually the client's `request.remote_addr` is not validated against the `OverrideAuthorizationClient` white-list setting, which allows any client to act as a proxy client and therefore to spoof the `g.client_ip` via `request.access_route`. In fact, the `OverrideAuthorizationClient` setting is not used at all.

There should be a mechanism, e.g. via
- the central `OverrideAuthorizationClient` setting or
- a seperate policy setting (e.g. similar to the IP address and subnet filter in the policies)

that guarantees, that IP spoofing is only allowed for allowed proxy clients.

I am not sure, which option would be the best. Any opinions?

**Comment by cornelinux** [comment]
Binding it to the policies might get a bit complicated.

The easiest way would be to simply impement the system wider setting.

But I think there is an interesting alternative. We could define which client IP (proxy) is allowed to replace which new client IPs. I.e.

proxy: 192.168.0.1: is allowed to set client IPs to:
   10.0.1.0/16

proxy: 192.168.1.2: is allowed to set client IPs to:
   0.0.0.0./0

**Comment by cornelinux** [comment]
We could enhance the logic of the system settings overrideClient:

   10.0.0.5/24>192.168.0.0/24

This would allow clients in the subnet 10.0.0.5/24 to replace their IP address to any IP in the subnet 192.168.0.0/24.

This has some special cases:

 *  omitting the subnet mask would mean /32 a single host
 *  omitting the IP after the ">" and the ">" sign would mean: allow replace to everything.

**Comment by cornelinux** [comment]
In the before request we set the client IP in the g object:

    g.client_ip = request.access_route[0] if request.access_route else \
             request.remote_addr

In this event we need to check for OverrideAuthorizationClient and the parameter "client" needs to be evaluated, if the originial client IP matches OverrideAuthClient.

**Comment by cornelinux** [comment]
What should we do, if a client issues a API Request with a *client* parameter (tries to rewrite client_ip) although it is not allowed to. Should we fail with an exception or should we just not rewrite but log this incident as warning to the log file?

**Comment by berndnicklas** [comment]
Thanks a lot!

**Comment by berndnicklas** [comment]
Beeing back from vacation and testing the new OverrideAuthorizationClient functionality it seems the validation seems to be not working (or there is something terrible I am overlooking in my test configuration). With the following settings
`1.2.3.4`
or
`1.2.3.4 > 0.0.0.0/0`
I can successfully override the client IP address via X-Forwarded-For header field from any client with any client IP address, e.g. via

`curl --header 'X-Forwarded-For: 4.3.2.1' 'https://test-server/validate/check?realm=test&user=test&pass=test'`

Am I missing something? Can you reproduce this?

**Comment by cornelinux** [comment]
Please take a look at the get_client_ip function in lib/utils.py
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/utils.py#L429
The request.access_route should contain your X-Forwarded-For. You should debug through this.
In my case g.client_ip gets set to 4.3.2.1

I can not reproduce this, since you do not tell me your outcome!? Maybe your expectation is not right?

**Comment by berndnicklas** [comment]
Ah, I just realized 

```
    client_ip = request.access_route[0] if request.access_route else \
        request.remote_addr
```

reflects the old functionality which did not check the client's IP address and always set the first element of request.access_route as client_ip.

Since the "X-Forwarded-For" HTTP Header field reflected in request.access_route is the HTTP-way of setting the original client's IP address (exactly like `client` variable in privacyIDEA), it possibly should be something like this:

```
    client_ip = request.remote_addr
```

and

```
    mapped_ip = request.access_route[0] if request.access_route else \
        request.all_data.get("client")
```

**Comment by berndnicklas** [comment]
See pull request #495

**Comment by cornelinux** [comment]
OK, I understand there was a misunderstanding. I was not aware, that the X-Forwarded-For aka access_route should also be checked against the allowed clientsmap.
There is something wrong with the pull request. I probably will close the pull request and fix it.
