### ISSUE TITLE
Feature request to display the same error message when the user is not found in the resolver.

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3954]
When a user is not found in the resolver, the error message on the webGUI, the CP, the audit log and the Log are not the same.

On the webGui the error message is :wrong credentials.
For security reasons, it could be better to keep this standard error message.
![webgui-wrong-cred](https://github.com/privacyidea/privacyidea/assets/95854213/3c3a0dd3-12c7-4b0e-a872-00e0d100712d)

But it would improve the debugging if the error message in the audit log, the Logs and with CP were the same
![audit log error](https://github.com/privacyidea/privacyidea/assets/95854213/25c7d0f1-7e60-44d8-8d69-964120b9a7df)

Error message in the Logs
[2024-05-28 14:52:35,604][3215][140690995328768][DEBUG][privacyidea.lib.user:268] user 'hannes4' not found in resolver 'myfirstresolver'

Error message when login with the CP
![cp-erro904](https://github.com/privacyidea/privacyidea/assets/95854213/f10863dc-f849-4bcd-a429-73208774de43)
[2024-05-28 14:59:06,810][3215][140691003721472][DEBUG][privacyidea.lib.auditmodules.base:176] Entering log with arguments (<privacyidea.lib.auditmodules.sqlaudit.Audit object at 0x7ff521504040>, {'info': 'ERR904: The user can not be found in any resolver in this realm!'}) and keywords {}

**Comment by cornelinux** [comment]
For security reasons it is the best to use "Wrong Credentials".  That is set.
There must not be any information disclosure about a user existing or not.

It is also set, that the error message in the log is "user can not be found in any resolver".
The error message of the CP however, must be changed to "Wrong Credentials" to avoid information disclosure in the CP.
@sepp67 please open an issue with the credential provider.

**Comment by nilsbehlen** [comment]
The credential provider just displays the message it gets from privacyidea. I think it should stay that way. Privacyidea should respond with "wrong credentials" so applications can just display that message.
If we are to avoid information disclosure, we need to change what the api returns in this error case.
