### ISSUE TITLE
Import of TANs for TAN-token might break length check

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3956]
With #3746 we  introduce a generic length check for different token types.
If the TAN-token generates the TANs, it adheres to the given `otplen` parameter but if it is initialized with given TANs (like with a CSV import), it sets the `otplen` of the token to the length of the first value, regardless of the other values:
https://github.com/privacyidea/privacyidea/blob/0d29427d123d2006d29659071a133ef815d5b316/privacyidea/lib/tokens/tantoken.py#L139

Using a TAN with a different length will fail due to the length check.
It is unclear to me if this is a Problem but it could be confusing for someone generating the TANs externally.

We could either disable the OTP length check for TAN tokens or check the length of all given TANs during initialization.

**Comment by cornelinux** [comment]
@plettich  Is this really about imported TANS with different length?

Who imports tans with different length? TANs are not ment to have different length. If s.o. needs some password lists with different length, this would definitively be a new token type.

Please consider closing this issue.

**Comment by plettich** [comment]
> Who imports tans with different length? TANs are not ment to have different length. If s.o. needs some password lists with different length, this would definitively be a new token type.
> 
My thoughts as well :-)
So now we can claim this as a known issue...
