### ISSUE TITLE
SMS verify enrollment ignores `smstext` policy

### ISSUE THREAD

**Issue by QcFe** [privacyidea/privacyidea#3971]
When using the `verify_enrollment` _enrollment_ policy with SMS token type, the `smstext` _authentication_ policy is ignored.

I tried to dig a bit within the code and found out in `lib/tokens/smstoken.py` in `prepare_verify_enrollment` function, the challenge is created without an `options` object. Such object is used then in `_get_sms_text` function to get the text from the policy. Inside there the existence of `g` parameter is checked in `options` but since no `options` is provided, that check will fail in case of enrol verification and the `smstext` policy won't be evaluated. 

I don't know what to do at this point, doing the verification myself by enabling the token, triggering the challenge and disabling it right after doesn't seem a particularly smart solution...

I'm willing to make a PR if there's any meaningful way to make this work, but I'm not extremely proficient in python and I'm not sure from where I could take that `g`...

I'm using PI v3.9.3.

**Comment by plettich** [comment]
Hi @QcFe 
i can confirm this issue.
We probably just need to create an `option` dictionary here:
https://github.com/privacyidea/privacyidea/blob/3c819ef7cbf989821b1ba65fee7a0c6e484dbbda/privacyidea/api/lib/postpolicy.py#L966
with the entries `g` and `user` and pass it down to `tokenobj.prepare_verify_enrollment()`.
However we need to change the signature of `prepare_verify_enrollment()` to accept an `option` parameter.

**Comment by cornelinux** [comment]
Might be similar to  #3976 #3928 #3883 #3884
