### ISSUE TITLE
base-path

### ISSUE THREAD

**Issue by privacyidea** [privacyidea/privacyidea#4]
It should be possible to run privacyIDEA not only at root (like
/manage/
/admin/show/

but also on an additional base path like
/base/manage
/base/admin/show

**Comment by cornelinux** [comment]
We can run different instances by configuring apache like this:

        # We can run several instances on different paths with different configurations
        WSGIScriptAlias /instance0      /home/cornelius/src/privacyidea/deploy/privacyideaapp0.wsgi
        WSGIScriptAlias /instance1      /home/cornelius/src/privacyidea/deploy/privacyideaapp1.wsgi
        WSGIScriptAlias /instance2      /home/cornelius/src/privacyidea/deploy/privacyideaapp2.wsgi
        WSGIScriptAlias /instance3      /home/cornelius/src/privacyidea/deploy/privacyideaapp3.wsgi

The app determines the base_path like /instance0.
Each wsgi script can contain another configuration file, thus running different databases and setups.
