### ISSUE TITLE
Event Handler ignores token conditions with validate_check

### ISSUE THREAD

**Issue by sheckandar** [privacyidea/privacyidea#4017]
### Top-level intent

What did you try to achieve?

Trigger a user notification only when a push token is requested. All other token types should be ignored. If no token exist for a user fail the conditions  test and do not send a notification.

### Steps to reproduce

1. Create a post event handler for validate_check
2. Set condition to serial {"serial":"PIPU*"} 
3. Configure email notification

### Expected outcome

Emails should only be sent when a token serial starts with PIPU 

### Actual outcome

Emails are sent on all events where there is no token serial present, causing a flood of notifications.

### Configuration

* **privacyIDEA version**: 3.9.3
* **Installation method**: Used CentOS install method (virtenv and PIP)
* **Python version**: 3.9.19
* **Operating system**: Alma Linux 8.10
* **Webserver**: Apache 2.4.37
* **Token database**: MySQL

### Log file
No errors found in the log. The event handler seems to be triggered unconditionally, ignoring all conditions for tokens

**Comment by sheckandar** [comment]
Not a bug. Found documentation about this.

Closing.

**Comment by plettich** [comment]
Hi @sheckandar 

> Not a bug. Found documentation about this.

Which part of the documentation was not clear on this? Maybe we can further improve the documentation to make things clearer.

**Comment by sheckandar** [comment]
I don't think its the documentation.

I just assumed that if there is no match then a _false_ result would be returned. This is the first time I see a _true_ result returned when there is no match.

I think it was just my mindset on what to expect.
