### ISSUE TITLE
WebUI: Search bar to search for anything

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#4047]
It would be nice to have search bar on the starting page in the webui, or at the top, that allows to search for everything, like:
token, user, policies, audit entries, ...

While this information could be aggregated with existing endpoints, that solution is probably bad because it is not optimized for this use case. So we need a new endpoint for that. The data format however, should not be different from the existing data that can be queried and the view on that data (webui) can stay the same aswell.
=> Each result type of the search (token, user, policy, audit, ...) has its own section in the result view which displays the data like it is already done in the dedicated views in the webui.

* [ ] Make a mock up to get an idea of what the goal could look like
* [ ] Define new endpoint: What data should be searchable?
* [ ] Implement new endpoint
* [ ] Test new endpoint (and new functions)
* [ ] Implement in WebUI, using new endpoint
* [ ] Documentation

Bad Mockup: This does not really have the style of the webui so it just shows how the results can be structured
![everythingsearch mockup](https://github.com/user-attachments/assets/fa9a1a25-a515-461d-beb6-a3c375a7e3ff)

**Comment by plettich** [comment]
There were some discussions about a global search here: #2458

**Comment by nilsbehlen** [comment]
will be continued here #4102
