### ISSUE TITLE
policy to disable PIN+OTP check, do only pin check

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#4051]
This is a problem of clients that only have 1 input field available (looking at you radius). Input can be either the password/pin or that+OTP. Privacyidea does not know what the input is, so it tries for both, which in combination with otppin=userstore (AD) leads to an excessive amount of failed tries in case the password is wrong.
Since this is a problem of the client, we can try to improve the failure behavior by adding a policy (which can then be bound ONLY to the user-agent of such clients) that lets admins configure how that input from a single field is to be used, so that only one of the options is tried.

The policy could be: `pin_check_only`
If enabled and matching, this:
https://github.com/privacyidea/privacyidea/blob/807919d81f77e69887240ddebfce0acae07b6e0c/privacyidea/lib/token.py#L2342
should not be done anymore.
The policy match should be done outside of `check_token_list` and be passed in `options`.
Also make sure that responses to challenges are unaffected by this (currently do not know if that is the case)

OTP PIN check is done here:
[privacyidea/lib/policydecorators.py:569](https://github.com/privacyidea/privacyidea/blob/662774047d37fdfe335fcf523892eff11ca5f881/privacyidea/lib/policydecorators.py#L569)

**Comment by cornelinux** [comment]
Hm, I do not understand "Input can be either the password/pin or that+OTP."

In my understanding there is only one login, that leads to success.
Or is this a client, that *can* to challenge request, which would be triggered by only entering the PIN first?
