### ISSUE TITLE
Strong cryptography to check subscriptions is at odds with the GPL. 

### ISSUE THREAD

**Issue by AphidGit** [privacyidea/privacyidea#4060]
Isn't actively refusing authentication requests at odds with this program being open source under the GPL? Specifically: This section: 

> “Installation Information” for a User Product means any methods, procedures, authorization keys, or other information required to install and execute modified versions of a covered work in that User Product from a modified version of its Corresponding Source. The information must suffice to ensure that the continued functioning of the modified object code is in no case prevented or interfered with solely because modification has been made. 

If I 'modify' my source to add user X+1, an authorization key to do so is missing because the signature check on the subscription will fail. AFAICT, You are _required,_ to provide instructions to mediate this by the above language. The entire point of a digital signature is that _any_ modification will break the functionality, that's pretty clear. But how it interacts with EUCD-6, DMCA1201a and similar laws is troublesome. I've _never_ seen a GPL licensed program with antifeatures like this, because the entire point of the license is to prevent that from happening, to prevent a developer from exercising (semi-effective) _control._ over the users after the fact. 

In fact, GPLv3 specifically added extra language to deal with this private law by copyright adhesion paragraph, to attempt to stop the author from exercising it over code written under this license. Technically, it would be interesting to see/read what kind of precedent could be set if someone were to openly forge a subscription file. Can you? The fact that the answer may well depend on what the Judge had for breakfast with the world's insane copyright laws should really be enough to _not_ do this in GPL software, ever. Yes, [section 3](https://www.gnu.org/licenses/gpl-3.0.html#section3) exists, but yet... Would you file a DMCA if someone forked your repository and cleaned out all the 'subscription' code? 

Because here's what this amounts to: There's a DRM system into copyleft software by adding the antifeature to block access when there are more than X amount of accounts via a digital signature, even if the code is open. Systems a lot more banal than yours have been ruled to be a 'trusted protection module', a 'digital lock', a 'functionality restricting access to a work' or such. These rules are _exceptionally_ broad. The fact that it's trivially easy to hack around the secret does not absolve the would-be "pirate".

Anyone can fork this and remove the checking code, and that seems like the best way forward. It'll make the program faster as a bonus, because it doesn't have to read a signature file and do an extra RSA operation with every request. But better yet, how about not wading into a legal quagmire and dragging your users under by just not having such restrictions at all? They're not a useful feature, and you may just have broken your own license by not providing the necessary information or tools to generate the key. A simple `generate_subscription_key.py --input mylicense.sub` would suffice. Also see [GPL3 draft process, DRM](https://gplv3.fsf.org/drm-dd2.html/ ) and [Tivoization](https://en.wikipedia.org/wiki/Tivoization),

**Comment by cornelinux** [comment]
Can you please elaborate on your situation, what you are doing and what problem you are experiencing?
I do not understand: 

    "If I 'modify' my source to add user X+1,"
