### ISSUE TITLE
TOTP code acts as a HOTP code and can only be validated once

### ISSUE THREAD

**Issue by dioss-Machiel** [privacyidea/privacyidea#4064]
### Top-level intent

We use privacyidea with TOTP tokens, these tokens are valid for 30 sec
We use these TOTP tokens in multiple places, authentication with these tokens may happen multiple times within the 30 sec timeframe
We call the privacy idea API to validate the token validity (https://privacyidea/validate/check)

We notice that the first time the check is called the token validates fine
The second time the check is called with the same code, within the 30 sec validity period, we get this:

`{"detail": {"message": "wrong otp value. previous otp used again", "otplen": 6, "serial": "TOTP00283945", "threadid": 140639856335744, "type": "totp"}, "id": 2, "jsonrpc": "2.0", "result": {"authentication": "REJECT", "status": true, "value": false}`

The logs show this:

`[2024-09-03 12:11:08.455][WARNING] a previous OTP value was used again! former tokencounter: 57511940, presented counter 57511940
[2024-09-03 12:11:08.455][WARNING] a previous OTP value was used again! former tokencounter: 57511940, presented counter 57511940
[2024-09-03 12:11:08.477][INFO] Previous OTP used again. Serial TOTP00283945 with counter 57511940.
[2024-09-03 12:11:08.477][INFO] Previous OTP used again. Serial TOTP00283945 with counter 57511940.`

I have investigated this further in the source code and I believe this is a bug.

The first log message "a previous OTP value was used again" comes from "totptoken.py" (https://github.com/privacyidea/privacyidea/blob/fc171c9df01a5b7f63c4d9d63f12fe92767b0bb8/privacyidea/lib/tokens/totptoken.py#L340), which seems fine (altough I don't consider it a warning, re-use of TOTP codes within the timeframe seems reasonable)

The second log entry "Previous OTP used again. Serial TOTP00283945 with counter 57511940" comes from the method "is_previous_otp" (https://github.com/privacyidea/privacyidea/blob/fc171c9df01a5b7f63c4d9d63f12fe92767b0bb8/privacyidea/lib/tokens/hotptoken.py#L480C9-L480C24) in "hotptoken.py", this happens because totptoken inherits from hotptoken. 

This is where I consider the bug to be located, I think "totptoken" should define its own "is_previous_otp" and always return false.
Is this correct or am I missing something?

### Steps to reproduce

1. Create user with TOTP token
2. Validate TOTP token via API -> OK
3. Validate same TOTP token via API -> REJECT

### Expected outcome

Multiple validations with the TOTP token within the validity period are considered "OK"

### Actual outcome

After the first validation the TOTP code can no longer be used and you need to wait untill the TOTP token expires (max 30 sec) before you can authenticate again

**Comment by jona-samuel** [comment]
The totp token works as intended. It is a one-time password so you can use it just one time. But if you want a totp where you can use the pin more than once, you can use the daypassword-token or the auth-cache.

**Comment by dioss-Machiel** [comment]
I didn't know about the auth-cache, that does solve our issue, thanks a lot for the quick response!
