### ISSUE TITLE
Unable to Save SMS Gateway Configuration and Options Section Input Failure

### ISSUE THREAD

**Issue by medtemo** [privacyidea/privacyidea#4068]
### Top-level intent

What did you try to achieve?
Add SMS Gateway
### Steps to reproduce

1. Create SMS gateway with HttpSMSProvider profile

### Expected outcome

What do you think, how the system should have worked?
Adding SMS gateway successfully

### Actual outcome
What did actually happen?
After saving the SMS Gateway settings, the configuration seems to be saved successfully. However, upon navigating to other sections and then returning to the SMS Gateway settings, the newly created gateway becomes unreadable or inaccessible.

Additionally, the Options section does not accept any new entries, preventing configuring settings within this section. 

### Configuration

* **privacyIDEA version 3.10:
* **Installation method**: from Ubuntu packages
* **Python version**: python3
* **Operating system**: Ubuntu 22.04.2 LTS
* **Webserver**: 
* **Token database**: MySQL

**Comment by nilsbehlen** [comment]
Hi, you need to press refresh (top right corner) and they will show.
This will be fixed in 3.10.1

**Comment by nilsbehlen** [comment]
So this is only a UI problem, which was probably introduced after removing duplicate controller loads.
