### ISSUE TITLE
Send PUSH QR Code Image via UserNotification Handler

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#4069]
**Is your feature request related to a problem? Please describe.**

I would like to send the QR Code of the Push-Token enrollment via the UserNotification handler.

**Describe the solution you'd like**

The current tag `{googleurl_img}` only sends the QR code of an enrolled HOTP or TOTP token.
We could add a new tag like `{qrcode}` which will send either QR Code (HOTP, TOTP, Push) or also use the existing tag.

**Describe alternatives you've considered**

The alternative is only to send a registration code and lead the user to the selfservice portal to enroll a PUSH token.

**Additional context**

The QR image of the PUSH token is in a different location in the JSON response. So the notification handler needs to parse this and replace the new tag.

**Comment by nilsbehlen** [comment]
maybe add a tag for the time to live of the qr code aswell.
