### ISSUE TITLE
Return OTP-Length on successful validation with OTP token via REST-API

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#407]
**Use case**

We run an authentication proxy server (LDAP proxy) in front of PrivacyIDEA, that after successfully authenticating the user against PrivacyIDEA server also authenticates the user against LDAP server and proxies LDAP searches to the LDAP directory.

To authenticate the user against our LDAP server we have to either use a seperate proxy user or to extract the user's password from the combined password+otp string.

The simplest solution would be using a seperate proxy user (with security drawbacks) or to extract the user's password via simple heuristics over the PrivacyIDEA validation result (regex over the json response detail.type and detail.serial) (neither very generic, nor very flexible). We tried both cases but in the long-term we are interested in a more generic solution.

**Possible solutions**

1. Let /validate/check API endpoint return something like detail.otp_length on successful validation of otp token (some implementation work in PrivacyIDEA)
2. Instead of /validate API endpoint our ldap proxy server could use the /auth API endpoint, on success get the json web token and request the user token's otp length (some implementation work in our ldap proxy server)

Since the use case is possibly interesting for other users too, possibly the 1st solution would be a good idea. Any opinions?

**Comment by cornelinux** [comment]
In case of 1st solution you would also need the information if the PIN is prepended or appended.

The serial and tokentype is added here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L1942

You could also add the OTP length like

    reply_dict["otplen"] = pin_matching_token_list[0].token.otplen

**Comment by cornelinux** [comment]
As the prepend pin or postpend pin is a system wide setting, we do not return this value. This will probably never change in an installation.
