### ISSUE TITLE
Show token url in token wizard

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#4074]
The token wizard does not show the URL when the token is enrolled, unlike the normal WebUI.
Add the text with URL below the QR Code.

**Comment by cornelinux** [comment]
The tokenwizard was ment to be dead easy and simple.
You can configure additional ui and above and below the displayed QR code.
Why would you want to change the default behaviour? I would recommend to not change this.

See the configuration options:
https://privacyidea.readthedocs.io/en/latest/faq/customization.html#tokenwizard
I.e. if s.o. wants the URL he can configure this!

**Comment by nilsbehlen** [comment]
The customization does not work, it is is commented here
https://github.com/privacyidea/privacyidea/blob/662774047d37fdfe335fcf523892eff11ca5f881/privacyidea/webui/login.py#L96
and does not load the additional htmls.

I can revert the changes, i do not care.
