### ISSUE TITLE
Feature request. Hide passwords in debug logs

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#408]
Hello Cornelius.
There's a very bad behavior of the application when you turn on debug level in logging.cfg or pi.cfg.
The problem is - it simply stores user passwords in clear text in logs. The passwords appear in events during logging-in to the web interface, like this:
[2016-05-23 12:20:44,392][4645][140451460134848][DEBUG][privacyidea.lib.user:118] Entering check_password with arguments (User(login=u'***someuser***', realm=u'***somerealm***', resolver=u'***someresolver***'), u'***user_password***') and keywords {}

This potentially allows anyone who has access to PI server and with appropriate privileges to view the log to know literally all userstore users passwords.

May it be changed somehow to hide passwords?
Like in this example where this is already done:
[2016-05-23 12:20:44,420][4645][140451460134848][DEBUG][privacyidea.lib.crypto:131] Exiting decryptPassword with result HIDDEN

**Comment by cornelinux** [comment]
There is no configuration switch to do this. Except turing of debug log.

I agree you do not want to see passwords there. 
But from a developer point of view it is important to see passwords when debugging.

**Comment by kolosovski** [comment]
I agree that while developing it's important to have everything in clear text. But is it really necessary to show passwords in production releases? This is a very very risky thing for my point of view. Of course, turning off debug level "solves" the problem, but on another side - turning ON debugs makes PI a handy tool for gathering user passwords.

I could count many cases in which this sensitive data may leak with definite circumstances.. For an easy example - netknights support asks for a debug log to solve a problem, or some software which tracks admin activity on the PI server records everything what is in console, and at least knowledge of some super-privileged user password by a PI admin is a breach.

I also clearly understand that this is open source software working on interpreted language as Python and it's not a big deal to(even if passwords are hidden) modify the code to unhide them, but in this case it is intentional hack and lead to another major consequences for this person.

At the moment I don't want to advertise this "feature" for others because this could lead to unpredictable reaction from some people when we almost finished our migration.
Hope you understand our apprehension :)
With best wishes,
Sergey

**Comment by cornelinux** [comment]
Thanks for your points. I would like to turn this into a feature for 2.12.1.

But honestly it might not be simple to fine all occurences. Especially since we can not know, which information, that the administrator enters, is sensible.

Anyway, you are welcome to add any occurences via a direct email.

**Comment by cornelinux** [comment]
I would like to add a config entry in pi.cfg like SHOW_PASSWORDS_IN_DEBUG. So this has explicitly to be turned on. Not only during development it is sometime important to know those.

There could be a warning in the webUI, that privacyIDEA is running in debug mode with passwords turned on.

Kind regards
Cornelius

**Comment by kolosovski** [comment]
Thank you, this is much better than before :)
So as far as I understood just after upgrade PI will hide passwords by default without any additional configuration. But if an administrator needs to debug and view entered passwords in debug logs he needs to use PI_LOGLEVEL = 9 option, right?

**Comment by kolosovski** [comment]
And in this case the notification in Web UI will apperar

**Comment by cornelinux** [comment]
right.
