### ISSUE TITLE
U2F enrolment - YubiKey Bio Series

### ISSUE THREAD

**Issue by AlgunaPseudo** [privacyidea/privacyidea#4099]
Hello, I have hosted PrivacyIDEA on an LXD container. I'm using USB/IP to be able to reach the YubiKey connected to my workstation from my LXD.

I made sure that the bus was correctly set up with `lsbusb` (package **usbutils**) :

```bash
$ lsusb
Bus 003 Device 002: ID 1050:0402 Yubico.com Yubikey 4/5 U2F
```

Also that the USB device was correctly detected as a YubiKey with `ykman` (**yubikey-manager** package):

```bash
$ ykman list
YubiKey BIO (FIDO Edition) (5.5.6) [FIDO] Serial: 17263033
```

And if ever I wanted to make sure that interactions with the fingerprint reader were detected from the LXD, I configured my first fingerprint from the LXD with `ykman` :

```bash
$ ykman fido fingerprints add toto
Enter your PIN:
Press your fingerprint against the sensor now...
4 more scans needed.
Press your fingerprint against the sensor now...
3 more scans needed.
Press your fingerprint against the sensor now...
2 more scans needed.
Press your fingerprint against the sensor now...
1 more scans needed.
Press your fingerprint against the sensor now...
Capture complete.
```

I'm using the YubiKey Bio Series (which has a fingerprint reader).

My problem is with its enrolment on PrivacyIDEA. I've created a U2F token (activated on the YubiKey side) and in order to validate enrolment, I have to remove and reconnect the key OR interact with the fingerprint reader. Except that my fingerprint isn't detected and I'm not even asked for it (the LED doesn't flash).

Does PrivacyIDEA support this model? Since it doesn't have a standard button. Do you have any suggestions for solving my problem?

Thanks in advance for the help .

**Comment by plettich** [comment]
Hi @AlgunaPseudo 
first i am not really sure about the setup. The browser, which is doing the enrollment needs access to the token, not the privacyIDEA server.
Second, it looks like browsers don't support u2f anymore. Doe is work if You enroll it as a webAuthn-token? As long as there are no strict requirements, they should be compatible.

**Comment by nilsbehlen** [comment]
if you have a problem with using webauthn instead of u2f, please open a new issue.
