### ISSUE TITLE
OTP error /validate/check [POST]

### ISSUE THREAD

**Issue by princetin97** [privacyidea/privacyidea#4103]
Hi guys,
I am having some issues in authenticator with OTP.
I create OTP for new users but when authenticating it shows error, but old users still work normally.

**Log in UI show:** 

500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Log in /var/log/privacyidea/privacyidea.log:**

[2024-10-07 11:15:57,211][1223][140321173296896][ERROR][privacyidea.app:1891] Exception on /validate/check [POST]
Traceback (most recent call last):
File “/opt/privacyidea/lib/python3.8/site-packages/flask/app.py”, line 2447, in wsgi_app
response = self.full_dispatch_request()
File “/opt/privacyidea/lib/python3.8/site-packages/flask/app.py”, line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File “/opt/privacyidea/lib/python3.8/site-packages/flask/app.py”, line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File “/opt/privacyidea/lib/python3.8/site-packages/flask/_compat.py”, line 39, in reraise
raise value
File “/opt/privacyidea/lib/python3.8/site-packages/flask/app.py”, line 1950, in full_dispatch_request
rv = self.dispatch_request()
File “/opt/privacyidea/lib/python3.8/site-packages/flask/app.py”, line 1936, in dispatch_request
return self.view_functionsrule.endpoint
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py”, line 109, in policy_wrapper
response = wrapped_function(*args, **kwds)
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py”, line 109, in policy_wrapper
response = wrapped_function(*args, **kwds)
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py”, line 109, in policy_wrapper
response = wrapped_function(*args, **kwds)
[Previous line repeated 8 more times]
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/decorators.py”, line 41, in function_wrapper
response = wrapped_function(*args, **kwds)
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py”, line 155, in policy_wrapper
return wrapped_function(*args, **kwds)
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py”, line 155, in policy_wrapper
return wrapped_function(*args, **kwds)
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py”, line 155, in policy_wrapper
return wrapped_function(*args, **kwds)
[Previous line repeated 5 more times]
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/decorators.py”, line 100, in check_user_or_serial_in_request_wrapper
f_result = func(*args, **kwds)
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/subscriptions.py”, line 338, in check_subscription_wrapper
f_result = func(*args, **kwds)
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py”, line 155, in policy_wrapper
return wrapped_function(*args, **kwds)
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/event.py”, line 116, in event_wrapper
if event_handler.check_condition(options=options):
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/eventhandler/base.py”, line 593, in check_condition
if not compare_generic_condition(cond,
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/utils/init.py”, line 911, in compare_generic_condition
res = compare_value_value(key_method(key), comparator, value)
File “/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/utils/init.py”, line 882, in compare_value_value
return value1 < value2
TypeError: ‘<’ not supported between instances of ‘NoneType’ and ‘str’

I hope to receive your support. Thanks!!

**Comment by cornelinux** [comment]
Duplicate: https://community.privacyidea.org/t/otp-error-validation/3641/3
