### ISSUE TITLE
Oracle ORA-02261: such unique or primary key already exists in the table

### ISSUE THREAD

**Issue by KnizP** [privacyidea/privacyidea#4105]
### Top-level intent

Create tables in oracle

### Steps to reproduce

pi-manage create_tables

will create some tables: but ends with error

![image](https://github.com/user-attachments/assets/499d85d5-cf43-44e6-a535-ee309c9dd6e2)

### Expected outcome

Tables created

### Actual outcome

sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-02261: such unique or primary key already exists in the table
Help: https://docs.oracle.com/error-help/db/ora-02261/
[SQL: 
CREATE TABLE tokencontainerrealm (
	container_id INTEGER NOT NULL, 
	realm_id INTEGER NOT NULL, 
	PRIMARY KEY (container_id, realm_id), 
	UNIQUE (container_id, realm_id), 
	FOREIGN KEY(container_id) REFERENCES tokencontainer (id), 
	FOREIGN KEY(realm_id) REFERENCES realm (id)
)

]

(Background on this error at: https://sqlalche.me/e/14/4xp6)

Problem is that with 	UNIQUE (container_id, realm_id), 
So i have created table manualy like:

CREATE TABLE tokencontainerrealm (
	container_id INTEGER NOT NULL, 
	realm_id INTEGER NOT NULL, 
	PRIMARY KEY (container_id, realm_id), 
	FOREIGN KEY(container_id) REFERENCES tokencontainer (id), 
	FOREIGN KEY(realm_id) REFERENCES realm (id)
);

And 
pi-manage create_tables is done.

But when i run app
i get:
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00908: missing NULL keyword
Help: https://docs.oracle.com/error-help/db/ora-00908/
[SQL: SELECT count(*) AS count_1 
FROM (SELECT token.id AS token_id, token.description AS token_description, token.serial AS token_serial, token.tokentype AS token_tokentype, token.user_pin AS token_user_pin, token.user_pin_iv AS token_user_pin_iv, token.so_pin AS token_so_pin, token.so_pin_iv AS token_so_pin_iv, token.pin_seed AS token_pin_seed, token.otplen AS token_otplen, token.pin_hash AS token_pin_hash, token.key_enc AS token_key_enc, token.key_iv AS token_key_iv, token.maxfail AS token_maxfail, token.active AS token_active, token.revoked AS token_revoked, token.locked AS token_locked, token.failcount AS token_failcount, token.count AS token_count, token.count_window AS token_count_window, token.sync_window AS token_sync_window, token.rollout_state AS token_rollout_state 
FROM token LEFT OUTER JOIN tokenowner ON token.id = tokenowner.token_id 
WHERE tokenowner.id IS NOT NULL AND token.active IS 1) anon_1]

and here problem is that with token.active IS 1 ... oracle doesnt know it. I think it should be: token.active = 1
I think problem is in:
```
    sql_query = _create_token_query(tokentype=tokentype, token_type_list=token_type_list, realm=realm,
                                    assigned=assigned, user=user,
                                    serial_exact=serial, serial_wildcard=serial_wildcard, serial_list=serial_list,
                                    active=active, resolver=resolver,
                                    rollout_state=rollout_state,
                                    revoked=revoked, locked=locked,
                                    tokeninfo=tokeninfo, maxfail=maxfail, all_nodes=all_nodes)
```

### Configuration

* **privacyIDEA version**: 3.10
* **Installation method**: (from Ubuntu packages)
* **Python version**: 3.10.12
* **Operating system**: ubuntu-22.04.5-live-server-amd64
* **Webserver**: privacyidea-nginx
* **Token database**: (cx_oracle 8.3.0) instantclient-basic-linux.x64-23.4.0.24.05 
* Only change in pi.cfg
* SQLALCHEMY_DATABASE_URI = 'oracle+cx_oracle://omg:omgomg@hostname:1521/SID'

### Log file

[2024-10-11 07:28:21,814][7958][140078789902336][DEBUG][privacyidea.app:252] Could not determine UUID from config: badly formed hexadecimal UUID string
[2024-10-11 07:28:21,815][7958][140078789902336][DEBUG][privacyidea.app:259] Could not determine UUID from file '/etc/privacyidea/uuid.txt': [Errno 2] No such file or directory: '/etc/privacyidea/uuid.txt'
[2024-10-11 07:28:21,815][7958][140078789902336][DEBUG][privacyidea.app:281] Current UUID: 'b1c030b6-bbc7-41a4-9328-02649fc31714'
[2024-10-11 07:28:22,289][7958][140078789902336][DEBUG][privacyidea.app:294] Reading application from the static folder /opt/privacyidea/lib/python3.10/site-packages/privacyidea/static and the template folder static/templates/

**Comment by jelinaunger** [comment]
* The unique constraint in the tokencontainerrealm table can be removed, as the primary keys already ensure unique rows. (https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#many-to-many)

* The token query uses the sql alchemy `is_()` operator function to compare boolean values (columns: active, revoked, locked). 
  SQLAlchemy docs:
  > Normally, IS is generated automatically when comparing to a value of None, which resolves to NULL. However, explicit usage of IS may be desirable if comparing to boolean values on certain platforms.

  However, Oracle (< version 23.c) does not support the IS operator for boolean values. Instead, `=` must be used.

* The rollout state is also included in the token query if the input consists only of `**`. Oracle won't match this to tokens with NULL for the rollout state. Hence, the token list won't show any token without a rollout state set.
  -> We need to check the input parameter and skip it if it only consists out of stars, similar to other query parameters.
