### ISSUE TITLE
add module to support suitecrm 7.6.3

### ISSUE THREAD

**Issue by chris001** [privacyidea/privacyidea#411]
Would be nice to add 2FA login via privacyidea with a suitecrm module or connector, which are compatible with the well known sugarcrm 6.5 API

**Comment by cornelinux** [comment]
If SuiteCRM provides a decent authentication API and does not suck at this like the totally overrated ownCloud, this is nor problem.

Just stick to the API doc http://privacyidea.readthedocs.io/en/latest/modules/api/validate.html and implement the call to /validate/check.

Then this is the whole secret https://github.com/privacyidea/privacyidea/blob/master/authmodules/TYPO3/privacyidea/Classes/PrivacyideaAuth.php#L45

You can create a new sub directory in authmodules/ or we can also start a new repository.

**Comment by cornelinux** [comment]
This can be acomplished using the ldap proxy.
https://netknights.it/en/two-factor-authentication-with-privacyidea-ldap-proxy/

**Comment by chris001** [comment]
Authenticating with the privacyidea ldap-proxy looks really great @cornelinux 
SuiteCRM / SugarCRM also supports SAML authentication and SAML2.

**Comment by cornelinux** [comment]
Yes, I know about SAML.
We simply needed a good example to get started with the LDAP proxy :-)
