### ISSUE TITLE
Push enrollment polling does not stop after leaving the site

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#4124]
### Top-level intent

What did you try to achieve?
Nothing, just stumbled upon this

### Steps to reproduce

1. Start to enroll push token
2. Instead of scanning the qr, leave the site

### Expected outcome

The webui does not poll for the rollout any more.

### Actual outcome

What did actually happen?
it does keep polling

**Comment by plettich** [comment]
There is also some unnecessary polling going on when using 2step enrollment: #4091 
I don't now if these are related.
