### ISSUE TITLE
Privacyidea diag script is no more valid in 3.10

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#4145]
The script privacyidea-diag is no more functional since the update of 3.9
it is throwing some error message sbecause the scrip still uses the old pi-mange commandos.

![privacyidea-diag](https://github.com/user-attachments/assets/26ec4432-b203-4ce7-bf8d-6f8254bb96e8)

![privacyidea-diag](https://github.com/user-attachments/assets/1ac4cffb-f572-4db6-b506-290eee1cd18f)

Kind regards
Sebastien

**Comment by nilsbehlen** [comment]
@plettich is this solved by #4144? If yes please close this issue.

**Comment by plettich** [comment]
> @plettich is this solved by #4144? If yes please close this issue.

Yes, it is fixed. GitHub does not close the issues automatically since they are not merged into master yet.
