### ISSUE TITLE
max token with enroll via multi challenge

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#4146]
the policies max_active_token and max_token are not considered when enroll_via_multichallenge is used

**Comment by plettich** [comment]
The `autoassign` policy makes use of the functionality of these policies instead of decorating an API endpoint:
https://github.com/privacyidea/privacyidea/blob/f2a09c16de38ad4299a4db7d9d6245a3706f2b89/privacyidea/api/lib/postpolicy.py#L761

**Comment by henrik-falk** [comment]
https://github.com/privacyidea/privacyidea/tree/4146/policies_enroll_via_multi_challenge
