### ISSUE TITLE
ubuntu 14.04 installation missing package python-pyjwt

### ISSUE THREAD

**Issue by visual4** [privacyidea/privacyidea#415]
The following steps lead to a missing dependency for python-pyjwt on Ubuntu 14.04.4 Server
- fresh VM with 14.04.4 Server
- add-apt-repository ppa:privacyidea/privacyidea
- apt-get update
- apt-get install python-privacyidea privacyideaadm

same for privacyidea-apache2 or privacyidea-nginx packages

apt-cache search privacyidea gives back the following information:

```
privacyidea - two-factor authentication system e.g. for OTP devices
privacyideaadm - admin client for privacyIDEA
privacyidea-radius - FreeRADIUS module for privacyIDEA, OTP authentication
privacyidea-all - two-factor authenticaion system. This is a metapackage to install everything
privacyidea-otrs - OTRS module for privacyIDEA, OTP authentication
privacyidea-nginx - 2FA system. This is a meta package to install privacyidea with nginx
privacyidea-simplesamlphp - SimpleSAMLphp module for privacyIDEA to do two factor authentication
python-privacyidea - two-factor authentication system e.g. for OTP devices
privacyidea-apache2 - 2FA system. This is a meta package to install privacyidea with apache2
privacyidea-pam - PAM module for privacyIDEA, OTP authentication
privacyidea-apache-client - Auth Module for Apache Server to authenticate with OTP
privacyidea-mysql - 2FA system. privacyIDEA application and MySQL configuration
```

python-pyjwt will not install on Ubuntu, python-pywt will, but this one does not resolve the dependency.

Cheers,
Björn

**Comment by cornelinux** [comment]
What do you see with

apt-cache policy python-pyjwt

?

**Comment by visual4** [comment]
```
root@privacyIdea:/home/visual4# apt-cache policy python-pyjwt
python-pyjwt:
  Installiert:           (keine)
  Installationskandidat: (keine)
  Versionstabelle:
```

**Comment by visual4** [comment]
I just realized that pyjwt and pywt are completely different packages as stated in #301 so my comment on python-pywt installation has no relevance.

**Comment by cornelinux** [comment]
I played around with the repository lately but I think i did not touch the productive one. pyjwt is missing. I will readd it.

**Comment by visual4** [comment]
thanks, great news
Cheers,
Björn

**Comment by cornelinux** [comment]
Now it is available again.
Thanks for posting this issue.
Please confirm your installation.

**Comment by visual4** [comment]
perfect, it's getting through. I'll report success after final configuration and installation

**Comment by cornelinux** [comment]
thx.
configuration is another concern
