### ISSUE TITLE
Tokentype condition does not (consistently?) work for token_init pre-event-handler

### ISSUE THREAD

**Issue by samir-at-netknights** [privacyidea/privacyidea#4153]
### Top-level intent
I tried creating an event handler which sets a static/generic pin for a certain tokentype. Meaning each new token of that type gets the same pin.

### Steps to reproduce
1. Create a new event handler.
- Event: `token_init`
- Module: `RequestMangler`
- Position: `pre`
- Condition: set `token.tokentype` to `totp`
- Action: `parameter` to `pin` and `value` to e.g. `testpw`
2. Create a new token (e.g. HOTP token) without setting a token pin.

### Expected outcome
The HOTP token does not have a token pin.

### Actual outcome
The HOTP token has the pin 'testpin.'
Also see: [pin_confusion.webm](https://github.com/user-attachments/assets/c09ba185-727f-4311-9f23-bc43020ff804)

### Configuration

* **privacyIDEA version**: 3.10.1
* **Installation method**: Ubuntu packages
* **Python version**: 3.12.3
* **Operating system**: Ubuntu 24.04.1 LTS
* **Webserver**: Apache2
* **Token database**: mysql

### Log file
Debug log of the token creation (I've redacted the domain): [privacyidea_scrubbed.log](https://github.com/user-attachments/files/17829128/privacyidea_scrubbed.log)

**Comment by cornelinux** [comment]
The token condition refers to the used token in the request.

In the pre state, there does not exist a token. So the condition is void.

I would recommend using a post-event handler.

**Comment by samir-at-netknights** [comment]
Alright, thanks!
The current text in the documentation is:
> The action is only triggered if the token in this event is of the given type. This way the administrator can design workflows for enrolling and re-enrolling tokens. E.g. the tokentype can be a registration token and the registration code can be easily and automatically sent to the user.

https://privacyidea.readthedocs.io/en/v3.10/eventhandler/index.html#conditions
Do you think modifying it like this:
> The action is only triggered if the token in this event is of the given type. This way the administrator can design workflows for enrolling and re-enrolling tokens. E.g. the tokentype can be a registration token and the registration code can be easily and automatically sent to the user.

makes sense :slightly_smiling_face:? If so, I'll create a

**Comment by samir-at-netknights** [comment]
> In the pre state, there does not exist a token. So the condition is void.

That's good to know. I've created a PR to add a short sentence to the documentation which points that out: #4162. Just as an idea :smile:.
> I would recommend using a post-event handler.

Thanks, that's what I did (with a script handler). It worked!
