### ISSUE TITLE
Web UI URL

### ISSUE THREAD

**Issue by sciclunandre** [privacyidea/privacyidea#416]
How can I set/change the Web UI URL? I installed privacyidea with python on raspberry pi. Thank you.

**Comment by cornelinux** [comment]
Can you be more precise? 
What do you mean, when you want to change the web UI URL?
The webUI simply runs were the REST API runs.
Thanks a lot.

**Comment by sciclunandre** [comment]
In order to acces the web ui, I go to 127.0.0.1 on the raspberry pi. I am also running owncloud on the raspberry pi. I don't wish to use the 127.0.0.1, what can I do? Apologies for not being that technical and specific, I am new to this. Thank you.

**Comment by cornelinux** [comment]
Oh, you mentioned the devils word!
You can run privacyIDEA in other "subdirectories".
http://privacyidea.readthedocs.io/en/latest/installation/system/wsgiscript.html#running-apache-instances

This is what a great software looks like.
So you should be able to do this with owncloud, too?
