### ISSUE TITLE
SQLIdResolver doesn't understand ownCloud hash "1|$2y$10$..."

### ISSUE THREAD

**Issue by evanstoner** [privacyidea/privacyidea#417]
I'm working on getting ownCloud integration working as described in https://www.howtoforge.com/tutorial/two-factor-authentication-with-owncloud/

I was seeing "Wrong credentials" error when logging in to privacyIDEA with the ownCloud account, but what I've found is that the format of the password hashes in ownCloud (at least in 9.0.2) doesn't match any of the existing checks in SQLIdResolver -- which the resolver doesn't handle well (I added `else: log.warn("Unrecognized hash format!")` at https://github.com/privacyidea/privacyidea/blob/v2.12/privacyidea/lib/resolvers/SQLIdResolver.py#L375 which is getting hit).

My password hashes in the oc_users table begin with `1|$2y$10$` (see https://github.com/owncloud/core/blob/v9.0.2/lib/private/security/hasher.php#L78). That's the ownCloud hashing version followed by standard PHP bcrypt

I think the lines that need attention in SQLIdResolver for this version of blowfish are 240 and 358. I'm not sure how to handle the version prepending; this is probably more general than SQLIdResolver. Maybe some substring logic during attribute mapping?

**Comment by cornelinux** [comment]
Sorry. Misclicked.

**Comment by cornelinux** [comment]
please state this issue here:
https://github.com/owncloud/core
