### ISSUE TITLE
Error in deploy/crontab/privacyidea

### ISSUE THREAD

**Issue by gbrusick** [privacyidea/privacyidea#4171]
### Top-level intent

Some changes in the code changed the arguments syntax of privacyidea-cron but didn't change the crontab file for deployments resulting in the cron not beeing run on versions >= 3.10
The arguments are wrong in the crontab file and in the documentation
argument is now `run-scheduled` instead of `run_scheduled`

### Steps to reproduce

1. run the command as entered in the file: `sudo` -u privacyidea /opt/privacyidea/bin/privacyidea-cron run_scheduled -c`

### Expected outcome

The cron should run correctly

### Actual outcome

```
Usage: privacyidea-cron [OPTIONS] COMMAND [ARGS]...
Try 'privacyidea-cron -h' for help.

Error: No such command 'run_scheduled'.
```

### Configuration

* **privacyIDEA version**: 3.10 and 3.10.1
* **Installation method**: Ubuntu packages
* **Python version**: 3.8.10
* **Operating system**: Ubuntu
* **Webserver**: Apache
* **Token database**: MariaDB

**Comment by plettich** [comment]
@gbrusick good catch, click seems to automatically convert underscores to spaces.
