### ISSUE TITLE
Missing setup key within Enroll a new token screen

### ISSUE THREAD

**Issue by OndraHo** [privacyidea/privacyidea#4182]
**Is your feature request related to a problem? Please describe.**
*Steps*
 user clicks on Enroll token -> fill in some description etc -> click enroll token -> screen "Enroll a new token"  -> no key available for enrollment without scanning QR code

What are you trying to achieve?
ability to enroll a new token even without camera

**Describe the solution you'd like**
add also a setup key for google auth mobile app

- addition of key for Google Authenticator app (and also probably others) to the screen

**Comment by plettich** [comment]
Hi @OndraHo i removed the boilerplate text for the feature request, i hope that is ok.

In the screen with the QR-code, after enrolling the token, there is a small link with an URI which should open a corresponding authenticator app (if registered in the system).
Alternatively the web-ui policy [`show_seed`](https://privacyidea.readthedocs.io/en/v3.10/policies/webui.html#show-seed) enables displaying the token key during rollout (You must re-login to the web-ui for the policy to take effect).
![PI_token_enroll_secret](https://github.com/user-attachments/assets/be1bc12b-7d20-4acf-bb4a-06c00af71f86)

**Comment by OndraHo** [comment]
My bad, thank you for your support. Closing this issue
