### ISSUE TITLE
port 5001 is also used by Synology DSM

### ISSUE THREAD

**Issue by ariedeleen** [privacyidea/privacyidea#420]
Used the Privacyidea docker container instructions from https://www.privacyidea.org/downloads/
I wanted to install it on a Synology NAS that also supports docker.
But got an error that port 5001 already was in use? And it is, because this is the default Disk Station Manager port address.
Can I use another local port != 5001 lets say 5003.

**Comment by cornelinux** [comment]
Please note, that the docke image is really outdated. This is still privacyidea 1.X.
But still, you can do this.

Look at the startscript. It runs a "paster" command. You can add a port to this command.

But I would recommend taking a look at the current 2.X version.
