### ISSUE TITLE
Possibility to disable OTP PIN in enrollment policy

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#439]
Since we only use userstore for OTP-PIN, we are missing an option to disable the OTP PIN in the enrollment policy. Also, if the PIN is disabled, the WebUI should not ask for a PIN in the token enrollment dialog.

**Comment by cornelinux** [comment]
Basically you are right. This is not quite simple - especially for administrative enrollment.
The logic - if the PIN should be displayed or not - gets quite complicated. As this also depends on the user, the administrator is selecting. 

For user enrollment this is easier, since this is clear directly after the user logged in.

**Comment by cornelinux** [comment]
There might be two possibilities:

1. Only for role *user*: Do **not** display the PIN entry, if policies only allow otppin=userstore and otppin=none. Or display the PIN entry, if there is either at *least* *one* policy otppin=tokenpin or *no* policy with otppin. (independent of the clientIP)

2. Add an additional policy action in scope webui.  :-/

**Comment by cornelinux** [comment]
**bummer** we already have the policy scope=user, action=setpin! We use this one.
It could however be, that the user needs to authenticate with OTP PIN but is not allowed to set the otp pin, since either the admin set the OTP PIN or the PIN was set automatically.

**Comment by cornelinux** [comment]
Hm. The functionality till now is, that the missing right "setpin" disallows the user to set the PIN later, but it does NOT disallow the user to set the PIN during enrollment of a token.
Thus, disabling the PIN dialog element, if "setpin" is not set, would change the current functionality.
Maybe we add another user-policy "enrollpin", which would mean: "set the pin during enrollment".

**Comment by berndnicklas** [comment]
> Maybe we add another user-policy "enrollpin", which would mean: "set the pin during enrollment".

This would allow enough granularity/flexibility for both using token pin or userstore password.
