### ISSUE TITLE
Add new event "token locked". Feature request

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#440]
At the moment there are several events which are related to actions performed **by an administrator** on a token. It would be a very useful feature if a user could get notified when his token is locked by some reason, for example fail counter exceeded. Because in practice we have a lot of cases when tokens are being locked, users don't know about it, keep trying... With notifications these things would be solved much better and most by themselves, I believe.

**Comment by cornelinux** [comment]
Good idea.
But the token being locked is not an **event**. It is a **result**.
So the notification should be bound to the **event** *authenticate* or */validate/check*.

The notification **action** will only be triggered under a certain **condition** (the token being locked).

**Comment by cornelinux** [comment]
We could evaluate the response-detail like:

    "detail": {"pin_change": true,
                  "next_pin_change": "07/07/16 16:43",
                  "serial": "PISP00095EC9",
                  "type": "spass",
                  "message": "matching 1 tokens, Token is disabled",
                  "otplen": 6}

and send, in case of a failed authentication request the detail.message as email or SMS.

I.e. we could let the admin choose in the event config, which of the values he like to add.

The condition would be: Authentication failed.

Then the user would be informed by email/sms, if he or an intruder fails to authenticate and he could see the reason.

@kolosovski How does this sound?

**Comment by kolosovski** [comment]
Sounds good, but I'd allow admin to define own email/sms body as it is in current version instead of just taking text from detail.message.

**Comment by cornelinux** [comment]
:-) of course!

**Comment by cornelinux** [comment]
**TODO**

* save conditions
* load conditions on even handler load
* use conditions :-)

**Comment by cornelinux** [comment]
Emails about failed authentications can now be sent to the user.

**TODO** Add checking of locking state of the token. We can use the details of the response and add condition:

    "token_locked": {
                "type": "str",
                "desc": _("Check if the max failcounter of the token is "
                          "reached."),
                "value": ("True", "False")
            }
