### ISSUE TITLE
Ability to limit certain tokens to specific NAS IPs

### ISSUE THREAD

**Issue by rf152** [privacyidea/privacyidea#441]
Don't know if it's possible currently, or possible to implement, but the ability to specify tokens that are usable against certain devices, but not others.

So, for example, to have the ability to have a SPass token, but to limit the token to uses on specific client devices (passed through from RADIUS via the NAS-IP?), allowing a user to log into, for example, non-production switches with a simple password, but require a TOTP token for production devices?

**Comment by cornelinux** [comment]
Thanks for the suggestion.
Yes. this is already possible.
http://privacyidea.readthedocs.io/en/latest/policies/authorization.html

The NAS-IP (RADIUS client) will be forwarded in the upcoming release 2.13.
http://privacyidea.readthedocs.io/en/latest/configuration/system_config.html#override-authorization-client

**Comment by rf152** [comment]
Hi Cornelius

Another quick one - is it possible to use boolean not for tokentype. So rather than having to specify an authorization policy for every client, I could just have on that says "Token Type is **not** SPass"?

**Comment by cornelinux** [comment]
You do not need several policies. You can add a list of tokentypes in the tokentype action of the one policy.

**Comment by rf152** [comment]
I understand that, but if I wanted to globally disable SPass, except for a single host, would it not be easier to put in a specific policy that says "Allow SPass for host 10.20.30.40", and then have a second policy that says "Deny SPass for everything"?

Or is there another way, being able to globally disabling a specific token type, and only enabling for specific hosts?

**Comment by cornelinux** [comment]
No. Feel free to issue a pull request or get a payed feature request. ;-)
