### ISSUE TITLE
Browser shows autocomplete listbox in front of a token's user assignment list

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#442]
Hello,

while assigning tokens to users in the WebUI token dialog, Firefox and possibly other browsers show their built-in autocomplete listbox in front of the user assignment list below the user input field (if autocomplete information is available). If so, it is impossible to choose a user for the token.

A solution would be to set autocomplete="off" for the corresponding HTML form.

Possibly there are other forms with the same problem, but I am currently not aware of it.

Best regards,

Bernd

**Comment by berndnicklas** [comment]
Ok, this also happens while enrolling new tokens and trying to assign a user.

**Comment by berndnicklas** [comment]
This could also happen in the serial field of the user detail dialog.

**Comment by cornelinux** [comment]
THanks for the note.
Would you like to issue a pull request?
(Although it will very likely not make it into 2.13, which will be released tomorrow)

**Comment by berndnicklas** [comment]
This could take some time, since I am actually flooded with paperworks and soon I'll be on summer vacations. But it's not urgent.
