### ISSUE TITLE
How can I add a new user to AD when I use ldapresolver?

### ISSUE THREAD

**Issue by cinjoseph** [privacyidea/privacyidea#443]
in version 2.12, it's a new amazing function~ I can add new user when i using ldapresolver~~ 
but it's failed when I tring to add user to AD

errors:

_while parsing a block mapping in "<unicode string>", line 1, column 1: "userid" : "username", "username ... ^ expected <block end>, but found ',' in "<unicode string>", line 1, column 22: "userid" : "username", "username" : "username", "surn ... ^_

so , how can I add user to Activy Directory?~ 

or it do not support Activy Directory well?

**Comment by cornelinux** [comment]
Hm, lets put it this way. This is work in progress. @wheldom01 worked on this a lot.

But the problem with adding a user to LDAP or AD is at least:

* at which place/OU should the user be created?
* In which groups should the user be created?

The user object in AD is much more complex than we use or handle the user in privacyIDEA. So there are many open questions. 
But I think it should "somehow"(TM) work to create a user. So I will look into it. 

But you may see from my comments: 
*It might be better to create a user from within Active Directory if you are in fact also using the AD. 
If you are using the users only with privacyIDEA you should consider setting up an SQL resolver.*

**Comment by wheldom01** [comment]
I have this working with openLDAP, unfortunately I don't have access to AD so I haven't been able to test that.

I agree with @cornelinux this is still very much work in progress. I would like to do further develop on this functionality, unfortunately at the moment I don't have much time available :( 

I would also add to the list of requirements to sucessfully add a user to AD:
-  The admin user account must have write access to the relevant place/OU
-  The correct objectClasses must be added to the User

Are you able to provide your LDAP resolver configuration? I may be able to provide pointers to a possible configuration error?

**Comment by wheldom01** [comment]
I've spent a couple of hours looking into this over the last couple of evenings and adding users to AD currently will not work I'm afraid.
On a slightly more positive note, I have written some additional code to allow the addition of extra LDAP attributes to a user account on account creation.
For example it is possible to add attributes such as uidNumber, gidNumber, homeDirectory etc. which may be required depending upon what objectClasses have been specified for new users.

**Comment by cornelinux** [comment]
Well, I think we have this covered in #445.
