### ISSUE TITLE
Token auto-assignment does not return otplen

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#444]
On auto-assignment the REST-API /validate/check endpoint actually returns the following information:

{"jsonrpc": "2.0", "signature": "...", "detail": {"message": "Token assigned to user via Autoassignment", "type": "...", "serial": "..."}, "versionnumber": "unknown", "version": "privacyIDEA unknown", "result": {"status": true, "value": true}, "time": 1467285732.441007, "id": 1}

While the type and serial fields are returned, the otplen field is missing. So here possibly some work is needed.

**Comment by cornelinux** [comment]
This can be fixed togeather with #446. The token object is available anyway, so we can also add the otplen.
