### ISSUE TITLE
More verbose logging of token assignment, auto-assignment and un-assignment in audit log

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#445]
Currently the audit log misses important information while assigning, auto-assigning and un-assigning tokens. 

Administrators assigning tokens to other users or unassigning tokens from other users: In the audit log it is perfectly clear, which admin has assigned or unassigned a token, but it is not clear, which user was assigned or unassigned in this action.
 A solution would be e.g.

 - Re-use user field in admin actions to fill in the user of the token processed by the admin, or
 - Re-use info field to fill in a conrete message string like "Token assigned to user <username>" or "Token unassigned from former user <username>"

**Comment by cornelinux** [comment]
I split the issue into two. Copied the autoassignment to #446.

**Comment by cornelinux** [comment]
I think the user is simply missing!

**Comment by cornelinux** [comment]
Oh, in fact in case of assigning this is simply a bug!

In case of unassigning this is the question: You do not unassign the user but the token. The API contains the serial number of the token to unassign. 
We could however determine the previous username. But you can still determine the username yourself. By viewing the history of the token.

So the question is, how you are using the audit log.

**Comment by berndnicklas** [comment]
Thanks!
