### ISSUE TITLE
error messages in /var/log/apache2/error.log

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#452]
Last week I upgraded to 2.13 (ubuntu packages on 14.04), and I got today:

[Mon Jul 04 06:50:56.146387 2016] [ssl:warn] [pid 24186] AH01909: RSA certificate configured for localhost:443 does NOT include an ID which matches the server name
[Mon Jul 04 06:50:56.146782 2016] [mpm_prefork:notice] [pid 24186] AH00163: Apache/2.4.7 (Ubuntu) mod_auth_kerb/5.4 PHP/5.5.9-1ubuntu4.17 OpenSSL/1.0.1f mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Mon Jul 04 06:50:56.146790 2016] [core:notice] [pid 24186] AH00094: Command line: '/usr/sbin/apache2'
[Mon Jul 04 18:38:36.451661 2016] [:error] [pid 22950] /usr/lib/python2.7/dist-packages/privacyidea/models.py:1944: SAWarning: Unicode column received non-unicode default value.
[Mon Jul 04 18:38:36.451679 2016] [:error] [pid 22950]   default="/etc/privacyidea/dictionary")
[Mon Jul 04 18:38:36.633497 2016] [:error] [pid 22950] No handlers could be found for logger "privacyidea.lib.stats"
[Mon Jul 04 18:38:36.797524 2016] [:error] [pid 22950] The configuration name is: production
[Mon Jul 04 18:38:36.797555 2016] [:error] [pid 22950] Additional configuration can be read from the file /etc/privacyidea/pi.cfg
[Mon Jul 04 18:38:36.803335 2016] [:error] [pid 22950] Reading Logging settings from /etc/privacyidea/logging.cfg
[Mon Jul 04 18:38:37.000630 2016] [:error] [pid 22950] /usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:459: SAWarning: Unicode type received non-unicode bind param value
[Mon Jul 04 18:38:37.000644 2016] [:error] [pid 22950]   param.append(processors[key](compiled_params[key]))
[Mon Jul 04 20:12:10.892740 2016] [:error] [pid 22950] /usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:324: Warning: Data truncated for column 'client' at row 1
[Mon Jul 04 20:12:10.892756 2016] [:error] [pid 22950]   cursor.execute(statement, parameters)

At 18:38 and 20:12 I authenticated for VPN access. Any further logs I can provide?

**Comment by cornelinux** [comment]
These is stdout/stderr from the wsgi process/sqlalchemy which does no harm. 
This was almost always there. 
Do you experience any problems?

**Comment by jh23453** [comment]
Cornelius Kölbel <notifications@github.com> writes:

> These is stdout/stderr from the wsgi process/sqlalchemy which does no harm. 
> This was almost always there. 
> Do you experience any problems?

No, right now I don't see any problems in the webui or while
authenticating.

-- 
The only problem with troubleshooting is that the trouble shoots back.
