### ISSUE TITLE
Enhancements to adding users to LDAP

### ISSUE THREAD

**Issue by wheldom01** [privacyidea/privacyidea#455]
I would very much like to add the following enhancements to privacyIDEA:
1. - The ability to add ldap attribute/value pairs that are not mapped to privacyIDEA user attributes. The driver for this feature is being able to add attributes that are specified as mandatory for a objectClass i.e The posixAccount objectClass requires several that are not/will probably not be mapped to privacyIDEA user attributes (uidNumber, gidNumber etc...)
2. - The ability to use one of the above ldap attribute/value pairs in the DN i.e: 
     dn: uidNumber=1001,o=test,dc=uk
3. - Support for adding users to ActiveDirectory

**Comment by wheldom01** [comment]
The following patch would enable the functionality described in point 1 above for the REST interface, which I believe was/is already intended/expected behaviour.

```
diff --git a/privacyidea/lib/resolvers/LDAPIdResolver.py b/privacyidea/lib/resolvers/LDAPIdResolver.py
index ea79fdf..70706b0 100644
--- a/privacyidea/lib/resolvers/LDAPIdResolver.py
+++ b/privacyidea/lib/resolvers/LDAPIdResolver.py
@@ -748,6 +748,8 @@ class IdResolver (UserIdResolver):
                         ldap_attributes[self.map.get(fieldname)] = pw_hash
                 else:
                     ldap_attributes[self.map.get(fieldname)] = value
+            else:
+                ldap_attributes[fieldname] = value

         return ldap_attributes
```

**Comment by cornelinux** [comment]
I would like to handle this in a more abstract way. I.e. creation of users in any case with any resolver type.

So the toplevel requirement probably is to add information to users when creating the user, that is not mapped or can not be mapped.

1. Can attributes be part of the normal user mapping?
2. If not, we need to distiguish between
    * resolver settings, i.e. fixed attributes for each user or
    * user settings, i.e. additional attributes that are needed to create a user, but that privacyidea does not need to work with this user. Such attributes would be variable for each user. I.e. when the user is created the admin needs to enter these attributes, but these attributes do not need to be mapped.

**Comment by wheldom01** [comment]
I agree the same functionality for all resolvers where practical/relevant is a good way forward.

Can I suggest the the two methods in item 2 should not be mutually exclusive, I can see senarios where both options could make the administrators life easier/more flexible.

**Comment by wheldom01** [comment]
Having thought about this a little more, the admin having created a user with additional attributes, should they then be able to edit those additional attributes via privacyIDEA?

**Comment by wheldom01** [comment]
>Can attributes be part of the normal user mapping?

Currently for the LDAP resolver adding additional attributes to the normal user mapping and supplying those attributes and their values to the REST interface, will add them to the directory with no changes to the existing code required.

**Comment by wheldom01** [comment]
This process is pushing me towards suggesting that updating the user.add and user.details views to be dynamically generated depending upon the information in the user mapping, would produce a good generic solution for all resolvers.

I'm interested to know what you think of such a solution?

**Comment by cornelinux** [comment]
...I need some time to think about it. I will take a walk in the forest, tomorrow ;-)

**Comment by cornelinux** [comment]
# Attributes

## The resolver method

The user views need to be dynamically created. The user.add needs to add entries dynamically, if the resolver defines, that adding a user also requires additional attributes. 
This is done often in privacyIDEA, in the policies... and last time in the smsproviders.
The SMS provider has a method parameters
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/smsprovider/HttpSMSProvider.py#L188
which returns the parameters it takes and also which kind of these should be.

The resolver could also have such a method like "user_add_attributes", which would return

 * fixed attribute
 * valiable attribute
    * attribute type
    * allowed values
    * required [bool]

## The UI part

The UI is created based on these defined attributes...
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/config/views/config.smsgateway.edit.html#L48

# Hook or Callback

I also like the idea about the hook or callback, you mentioned earlier.
privacyIDEA already has such a functionality. The Event Handler Framework.
Each REST API call (can) have a registered event
See https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/token.py#L229

Then actions with handler modules can be bound to those events.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/eventhandler/usernotification.py#L126

This way we even get more *Identity-Management-ty*. When a user is added it makes sense to be flexible to add new actions (either before [not yet implemente] or after [implemented]).
I.e. if the user is created, yes we can add attributes, but we might also like to
  * notify the user via SMS about his new account
  * print a letter to be sent to the new user
  * trigger creation of local accounts on other systems
  * trigger the booking of his company car...

...we might even take this from the issue to the wiki, to be able to write a bit more of a concept... :-)

**Comment by wheldom01** [comment]
I've just submitted a pull request #464 which dynamically creates the input fields for the add.user form, to see if this looks anything like you envisaged in your previous comment.

It has a temporary/hacky inline style to quickly show that form checking is working, which will require removing, but seems to work nicely otherwise.

**Comment by cornelinux** [comment]
Opened a simpler issue #1822 and close this one.
