### ISSUE TITLE
Let user edit "description" field in selfservice portal

### ISSUE THREAD

**Issue by mimugmail** [privacyidea/privacyidea#461]
Hi,

I'd like to edit the description field in the selfservice portal for a token. 
Currently only admin can edit this field but I don't see any security reason why not to let the user set it, if enrollHOTP is set within selfservice1.

Thanks
Michael

**Comment by cornelinux** [comment]
Hm, this is simply not implemented. At the moment I do not see a good reason to implement this.
If it was implemented I would recommend to use a new field to distinguish between the description set by the administrator and the description set by the user.
The description is a note for the administrator. So the user should not overwrite this.

Or: The administrator could get a complete Textedit field to write down his diary regarding this token...

**Comment by cornelinux** [comment]
Oh, we can not do this that easily.

Setting the description is an admin event (@admin_required decorator).
We would have to change the API and the Policy settings...

We will probably close this issue for now.

**Comment by cornelinux** [comment]
Close this. We would have to provide different means for the user.
