### ISSUE TITLE
Log handler message

### ISSUE THREAD

**Issue by hugoboos** [privacyidea/privacyidea#462]
Hi,

When I use `pi-manage`, I see the following message in the output:

`No handlers could be found for logger "privacyidea.lib.stats"`.

How can I solve that?

**Comment by cornelinux** [comment]
You may ignore this. 
Or does it cause an error?

**Comment by hugoboos** [comment]
I does not cause an error. But I see it appearing in the server logs and when I run `pi-manage`.
When I see an message like that it indicated that something is missing or not correctly configured.

Do I need to add an log handler for that?

**Comment by cornelinux** [comment]
Honestly I have no idea.
I should use the same logger, since it is no different to e.g. privacyidea.lib.user
Obviously it arises from this line:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/stats.py#L30

**Comment by hugoboos** [comment]
I can look into this. But when I try to setup my development environment I get the following error:
`venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py:1152: SAWarning: Unicode column 'None' has non-unicode default value '/etc/privacyidea/dictionary' specified.`.
I followed the steps as described in the readme, running on OSX.

**Comment by cornelinux** [comment]
This is no error. But a warning. It also appears when setting it up successdully.

**Comment by splashx** [comment]
Actually, the exit code in a shell environment (e.g. `bash`) is >0, which triggers "fail"/"error" in several configuration management systems.
```
root@testmachine:~# PYTHONWARNINGS="ignore" pi-manage policy create -f policy.dict policy fake fake
No handlers could be found for logger "privacyidea.lib.stats"
/usr/local/lib/python2.7/dist-packages/privacyidea/app.py:58: ExtDeprecationWarning: Importing flask.ext.migrate is deprecated, use flask_migrate instead.
  from flask.ext.migrate import Migrate
/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '

             _                    _______  _______
   ___  ____(_)  _____ _______ __/  _/ _ \/ __/ _ |
  / _ \/ __/ / |/ / _ `/ __/ // // // // / _// __ |
 / .__/_/ /_/|___/\_,_/\__/\_, /___/____/___/_/ |_|
/_/                       /___/
   
Found scope 'user' in file, will use that instead of 'fake'.
Found action in file: '['totp_hashlib=sha1', 'totp_otplen=6', 'resync', 'enrollTOTP', 'totp_timestep=30']', will use that instead of: 'fake'.
root@testmachine:~# echo $?
10
```

The result is not a fail, though - the policy does show up correctly e.g. in the WebUI.

**Comment by cornelinux** [comment]
@splashx  Thanks a lot for pointing this out.
This is a different issue. Can you please open another issue?
