### ISSUE TITLE
global python-sphinx required to build the documentation

### ISSUE THREAD

**Issue by omarkohl** [privacyidea/privacyidea#467]
```
make html
```
fails with the following error message:

```
reading sources... [ 61%] modules/lib/apipolicy
Exception occurred:
  File "/home/.../venv/local/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
```

After commenting out the following line in both *privacyidea/api/lib/prepolicy.py* and *privacyidea/api/lib/postpolicy.py* it works:
```python
from flask import g, current_app
```

In case it is relevant this was tested with following packages and with the current **master** of privacyidea:
```
Flask==0.11.1
Sphinx==1.4.5
sphinxcontrib-httpdomain==1.5.0
```

**Comment by cornelinux** [comment]
I am running the make in the python virtual environment.
I.e. setup a virtualenv, enter virtual env, and the run make html...

**Comment by omarkohl** [comment]
> I.e. setup a virtualenv, enter virtual env, and the run make html...

same here :-)

**Comment by cornelinux** [comment]
Hm, I have 

    Flask==0.10.1

in my virtualenv.

Try setup virtualenv with

     pip install -r requirements.txt

If you comment out these lines, the doc might compile but privacyIDEA will probably not run anymore...

**Comment by omarkohl** [comment]
Leaving the Makefile untouched (issue #468) and installing **sudo apt-get install python-sphinx** makes this issue go away.

In some way the global Sphinx is being used even though you are supposed to be in a venv. I don't know if it is worth investigating this... it is strange though.

> If you comment out these lines, the doc might compile but privacyIDEA will probably not run anymore...

Sure. That was just to trace the issue. Not meant as a permanent fix.

**Comment by cornelinux** [comment]
Thanks a lot for the insight. 
At the moment I choose not to investigate it ;-)

**Comment by cornelinux** [comment]
Hm, in fact it is something else. After 

   apt-get remove python-sphinx sphinx-common

the documentation still builds fine on my machine...

**Comment by omarkohl** [comment]
I was no longer able to reproduce the issue with global/locally installed Sphinx. I was probably tired when I wrote that ;-)

The real issue seems to be a "fix" introduced in Sphinx 1.4.5 https://github.com/sphinx-doc/sphinx/pull/2731

Citing @bobh66:
> This change was released in 1.4.5 and appears to cause exceptions when generating HTML docs for code that uses Flask. The "if name in obj.dict" causes a RuntimeError from flask/globals.py because there is no active Flask context. Putting this inside a try-except block catches the Flask error and allows the doc generation to succeed.

There is an open pull request https://github.com/sphinx-doc/sphinx/pull/2778 so presumably this will be fixed in Sphinx 1.4.6

Until it is fixed another workaround (other than using Sphinx < 1.4.5) is to change **doc/modules/lib/apipolicy.rst** so that those members are excluded:

```
Pre Policies
~~~~~~~~~~~~

.. automodule:: privacyidea.api.lib.prepolicy
   :members:
   :undoc-members:
   :exclude-members: current_app, g

Post Policies
~~~~~~~~~~~~~

.. automodule:: privacyidea.api.lib.postpolicy
   :members:
   :undoc-members:
   :exclude-members: current_app, g
```

**Comment by cornelinux** [comment]
If it works for you, please issue a pull request! :-)

**Comment by omarkohl** [comment]
I think it makes most sense to just wait for Sphinx 1.4.6 . Until then everybody just has to make sure to use `Sphinx != 1.4.5` :-)

But if you think the workaround is useful I can also submit a pull request.
