### ISSUE TITLE
Consider setting SPHINXBUILD to 'sphinx-build' in doc/Makefile

### ISSUE THREAD

**Issue by omarkohl** [privacyidea/privacyidea#468]
Minor suggestion: Consider setting the SPHINXBUILD variable in doc/Makefile to:
```
SPHINXBUILD   = sphinx-build
```
by default instead of:
```
SPHINXBUILD   = python /usr/bin/sphinx-build
```
to simplify the life of contributors who don't have Sphinx installed system wide.

I'm willing to do a pull request to fix this if you agree that it should be done. I'm assuming it is like this because it makes *your* life easier (which is fair enough) ;-)

**Comment by cornelinux** [comment]
I never thought about this. Hm,
in fact my sphinx-build is located here...

    /home/cornelius/src/privacyidea/venv/bin/sphinx-build

(see my other comment about the virtualenv)

**Comment by cornelinux** [comment]
this is all strange. But please issue a pull request.
I checked this on my side. It will still build fine with your fix when I remove the deb packages python-sphinx and sphinx-common.
