### ISSUE TITLE
failcounter with several tokens

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#471]
A user has several tokens and the otppin=none is set.

Every authentication request that does not provide a valid OTP-value will increase the failcounter of all tokens!

Then the user authenticates with one of the tokens. The failcounter of this very token is reset. But all others stay and will probably increase to maxfail making these tokens inusable.

**Suggestion** In case of otppin=None, we should be able to disable the incfailcount?

**Comment by cornelinux** [comment]
The failcounter is increased at these two positions:

https://github.com/privacyidea/privacyidea/blob/dd262a3e2ea4f99ad863a12c7a97f12b4f32f8ff/privacyidea/lib/token.py#L2033

in this case we could NOT increase the failcounter, if otppin=none.

https://github.com/privacyidea/privacyidea/blob/dd262a3e2ea4f99ad863a12c7a97f12b4f32f8ff/privacyidea/lib/token.py#L2054

**Comment by simvirus** [comment]
<<Suggestion In case of otppin=None, we should be able to disable the incfailcount?>>
I'm not sure if it's a right choice.
Although it is not simple, an attacker can "brute-force" OTP request waiting for the fate coincides with its fake OTP.

**Comment by simvirus** [comment]
One update...
The problem is present also if:

- otppin=tokenpin
- some token are without PIN

Catch the setting otppin=none is not resolutive in this case.

**Comment by cornelinux** [comment]
We can not distinguish between tokens with and without PIN.
So the question is, what should happen, with the failcounter, if a successful authentication occurs - right?

To cope with the failcounter in other ways, you could:

set the maxfail to 1000 (or any other "high" value) and then reset the failcounter every days using a script on the database.

**We could however reset the failcounter of all tokens of a user, if the user authenticates successfully with ANY token.**

**Comment by simvirus** [comment]
First option is good, but not perfect for me (set maxfail to 1000 for example and reset every day)

Reset the failcounter of all tokens of a user, if the user authenticates successfully with ANY token, will be the best solution! 

Thanks

**Comment by berndnicklas** [comment]
> We could however reset the failcounter of all tokens of a user, if the user authenticates successfully with ANY token.

I think this should not be the default way, since - if the user has multiple tokens - it's impossible then to detect the abuse of a single token.

**Comment by simvirus** [comment]
> I think this should not be the default way, since - if the user has multiple tokens - it's impossible then to detect the abuse of a single token.

...but keeping a low maxfail (example 10 instead of the option with 1000) will preserve the security...

**Comment by cornelinux** [comment]
@simvirus Great. Then we will do the nd way.

@berndnicklas It will not be the default setting. We would either add a system setting OR - I already thought about moving this to the policies. Also add the **incFailCounterOnFalsePin** in the policies. Then we could add a policy to **increaseOnFalsePin** and **resetFailCountOnAnySuccessfullAuthentication**. ...well, I would think of another name ;-)

So if anyone of you comes up with a cool name, shoot!

**Comment by cornelinux** [comment]
# Policy
scope: authentication
**reset_failcounter_all_tokens**

**Comment by simvirus** [comment]
>cornelinux self-assigned this 21 hours ago

:100: 

And sorry for delay for a label feedback.... It's perfect!

**Comment by cornelinux** [comment]
Oh thanks. And I learned the tag 100!

**Comment by simvirus** [comment]
Note: In case of multiple realm and same user the reset bust be run only for that realm involved (not all realm)

**Comment by cornelinux** [comment]
Multiple realm would mean different user.
The realm is a component of the user object.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/user.py#L82
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L2017
