### ISSUE TITLE
bdist_wheel for cryptography ... error

### ISSUE THREAD

**Issue by nobicycle** [privacyidea/privacyidea#472]
Hi,
Afler git cloning I am following these instructions:
```
virtualenv2 venv
source venv/bin/activate
pip2 install -r requirements.txt

```
Please see attached build log.

[log.zip](https://github.com/privacyidea/privacyidea/files/375187/log.zip)

Best wishes and thanks for privacyidea.

##
Linux localhost.localdomain 4.6.2-1-MANJARO #1 SMP PREEMPT Wed Jun 8 11:00:08 UTC 2016 x86_64 GNU/Linux

**Comment by cornelinux** [comment]
<pre>
    creating build/temp.linux-x86_64-2.7/src/cryptography/hazmat
    creating build/temp.linux-x86_64-2.7/src/cryptography/hazmat/bindings
    creating build/temp.linux-x86_64-2.7/src/cryptography/hazmat/bindings/__pycache__
    gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/usr/include/python2.7 -c src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c -o build/temp.linux-x86_64-2.7/src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.o
    src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:476:6: error: conflicting types for ‘BIO_new_mem_buf’
     BIO *BIO_new_mem_buf(void *, int);
          ^~~~~~~~~~~~~~~
    In file included from /usr/include/openssl/asn1.h:65:0,
                     from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:197:
    /usr/include/openssl/bio.h:692:6: note: previous declaration of ‘BIO_new_mem_buf’ was here
     BIO *BIO_new_mem_buf(const void *buf, int len);
          ^~~~~~~~~~~~~~~
    src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:1955:15: error: ‘SSLv2_method’ redeclared as different kind of symbol
     SSL_METHOD* (*SSLv2_method)(void) = NULL;
                   ^~~~~~~~~~~~
    In file included from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:294:0:
    /usr/include/openssl/ssl.h:2349:19: note: previous declaration of ‘SSLv2_method’ was here
     const SSL_METHOD *SSLv2_method(void); /* SSLv2 */
                       ^~~~~~~~~~~~
    src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:1956:15: error: ‘SSLv2_client_method’ redeclared as different kind of symbol
     SSL_METHOD* (*SSLv2_client_method)(void) = NULL;
                   ^~~~~~~~~~~~~~~~~~~
    In file included from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:294:0:
    /usr/include/openssl/ssl.h:2351:19: note: previous declaration of ‘SSLv2_client_method’ was here
     const SSL_METHOD *SSLv2_client_method(void); /* SSLv2 */
                       ^~~~~~~~~~~~~~~~~~~
    src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:1957:15: error: ‘SSLv2_server_method’ redeclared as different kind of symbol
     SSL_METHOD* (*SSLv2_server_method)(void) = NULL;
                   ^~~~~~~~~~~~~~~~~~~
    In file included from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:294:0:
    /usr/include/openssl/ssl.h:2350:19: note: previous declaration of ‘SSLv2_server_method’ was here
     const SSL_METHOD *SSLv2_server_method(void); /* SSLv2 */
                       ^~~~~~~~~~~~~~~~~~~
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/archives/Security/privacyidea-git/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nbCUx0/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-UCmNg8-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/archives/Security/privacyidea-git/venv/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-nbCUx0/cryptography/
</pre>

Can you tell which distribution you are installing on?

**Comment by nobicycle** [comment]
Hi cornelinux,

It is Manjaro, which is Arch Linux with a few extras.

**Comment by cornelinux** [comment]
The requirements.txt contains the stuff that is in my development environment. Also additional packages which are not needed for normal operations.

In it there is cryptography=0.8.2. You are running a cutting edge system.
The error occurs during cffi, C foreign function interface.
My suspicion is, that the cryptography python module is too old for your system.
Please install it like this:
http://privacyidea.readthedocs.io/en/latest/installation/pip.html

Or change the requirements.txt to contain
cryptography>=0.8.2

**Comment by nobicycle** [comment]
Hi cornelinux

The following command from http://privacyidea.readthedocs.io/en/latest/installation/pip.html
`pip2 install privacyidea (into /opt) 
`worked without errorr

Is the  Github main page https://github.com/privacyidea/privacyidea
`pip2 install -r requirements.txt
` a mistake?

Thanks for your help.

**Comment by cornelinux** [comment]
a bit inaccurate... Thx
Cornelius
