### ISSUE TITLE
Question: Is a replacement of RSA Tokens possible?

### ISSUE THREAD

**Issue by DuckY1987** [privacyidea/privacyidea#475]
Hello,

i was looking through the documentation and the howto's and i couldn't quite figure out if i can replace SecureID tokens in my scenario.

We have a fortigate Firewall and as fortinet has there own tokens they will never integrate google authenticator as two factor authentication for ssl vpn users.

Following Scenario: the firewall authenticates now Users against the RSA Authentication Server, its a Simple Radius query, so is it possible to use privacyidea as a radius server to serve this queries and replace the hardware/software-tokens with TOTP?

Thanks in advance.

**Comment by cornelinux** [comment]
yes. of course it is. 
You should join the google group.
