### ISSUE TITLE
can privacyidea send qrcode to user when admin enroll a new top?

### ISSUE THREAD

**Issue by cinjoseph** [privacyidea/privacyidea#476]
I want to send the qrcode to user via email when enroll a new token for him . but I didn't find the config in policy about this. 
dose privacyidea support this feature? if not , do you have plan to do about this ?

**Comment by cornelinux** [comment]
Of course this is not supported, since it is probably HIGHLY INSECURE :-) (if the email is not encrypted)
We can start to discuss this and you could get this as payed extension. 
Or you could take a look at the event handler framework and implement a handler by yourself.

**Comment by cinjoseph** [comment]
Thanks Verymuch cornelinux~
