### ISSUE TITLE
RPM spec file

### ISSUE THREAD

**Issue by hugoboos** [privacyidea/privacyidea#477]
Hi,

We got privacyIDEA running in production now. To get there we've created our own RPM spec file. Including custom SELinux policies. We're willing to share that with you. Are you open for that?

**Comment by cornelinux** [comment]
Hi,
thanks a lot!
I am always intterested in everything! But I need to point out, that there are already spec files for RHEL/CENTOS7 and an RPM repository provided by my company for our support customers:

If you like to improve this, take a look here:
https://github.com/NetKnights-GmbH/centos7

If you would like to get a professional SLA, which is also beyond packaging the software, take a look here:
https://netknights.it/en/leistungen/service-level-agreements/
https://netknights.it/en/additional-service-privacyidea-support-customers-centos-7-repository/

**Comment by angystardust** [comment]
@hugoboos I'm really interested in the custom SELinux policy you wrote.
Can you share it with me, please?

**Comment by hugoboos** [comment]
We've use instruct uwsgi to put the socket in `/var/run` with this config:

```
socket = /var/run/privacyidea/privacyidea.sock
chown-socket = privacyidea:privacyidea
chmod-socket = 660
```

Then the files for the SELinux module. The `privacyidea.if` is an empty file.

```
# privacyidea.fc
/var/run/privacyidea(/.*)?		gen_context(system_u:object_r:httpd_var_run_t,s0)
```

```
# privacyidea.te
policy_module(privacyidea, 1.0.0)

gen_require(`
  type httpd_var_run_t;
')

# Give the privacyIDEA socket the correct label,
# so that processes with the httpd_t label
# can read and write to it
init_daemon_run_dir(httpd_var_run_t, "privacyidea")
```

**Comment by bobthomson70** [comment]
Hi, do you have a corresponding client side SE Linux policy? I've got AD + PI OTP authentication working but it fails when SE Linux is Enforcing - 
`
Aug  2 07:19:34 ssvc-r-01-001 sshd: privacyidea_pam: ('Connection aborted.', error(13, 'Permission denied'))
Aug  2 07:20:31 ssvc-r-01-001 sshd: Traceback (most recent call last):#012  File "/usr/local/sbin/privacyidea_pam.py", line 278, in pam_sm_authenticate#012    rval = Auth.authenticate(pamh.authtok)#012  File "/usr/local/sbin/privacyidea_pam.py", line 115, in authenticate#012    json_response = self.make_request(data)#012  File "/usr/local/sbin/privacyidea_pam.py", line 89, in make_request#012    headers=headers, verify=self.sslverify)#012  File "/lib/python2.7/site-packages/requests/api.py", line 108, in post#012    return request('post', url, data=data, json=json, **kwargs)#012  File "/lib/python2.7/site-packages/requests/api.py", line 50, in request#012    response = session.request(method=method, url=url, **kwargs)#012  File "/lib/python2.7/site-packages/requests/sessions.py", line 464, in request#012    resp = self.send(prep, **send_kwargs)#012  File "/lib/python2.7/site-packages/requests/sessions.py", line 576, in send#012    r = adapter.send(request, **kwargs)#012  File "/lib/python2.7/site-packages/requests/adapters.py", line 415, in send#012    raise ConnectionError(err, request=request)#012ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))
Aug  2 07:20:31 ssvc-r-01-001 sshd: privacyidea_pam: ('Connection aborted.', error(13, 'Permission denied'))
`

**Comment by plettich** [comment]
I don't have much experience with SELinux but it looks like the pam_python module is not allowed to create a socket or outbound connection.
You could disable SELinux for PAM completely (something like `$ setsebool -P pam_console_disable_trans on`) or add an appropriate SELinux rule to allow the connection.

**Comment by bobthomson70** [comment]
Hi, thanks - I figured it out with the help of some useful links, it comes down to adding a module for this Type Enforcement rule -
`#============= sshd_t ==============
allow sshd_t commplex_main_port_t:tcp_socket name_connect;`

**Comment by bobthomson70** [comment]
Find the disallowed operation in /var/log/audit/audit.log in this case ‘name_connect’:

type=AVC msg=audit(1533200224.781:1418): avc:  denied  { name_connect } for  pid=10293 comm="sshd" dest=5000 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:commplex_main_port_t:s0 tclass=tcp_socket

Use audit2why to confirm the problem:

grep sshd /var/log/audit/audit.log | grep name_connect | audit2why

Create a Type Enforcement file to see what the fix is:

grep sshd /var/log/audit/audit.log | grep name_connect | audit2allow privacyideaclient > /root/privacyideaclient.te

Use audit2allow to generate a policy file -
grep sshd /var/log/audit/audit.log | grep name_connect | audit2allow -M privacyideaclient```

(Manually) import the policy file - this role performs this step on the client side.

semodule -i privacyideaclient.pp

Useful links:

https://wiki.centos.org/HowTos/SELinux#gathering-audit-logs-in-permissive
https://tag1consulting.com/blog/stop-disabling-selinux
