### ISSUE TITLE
eMail tokens are not send, email configuration is correct, testmail arrived

### ISSUE THREAD

**Issue by DuckY1987** [privacyidea/privacyidea#480]
As mentioned the email configurtion is working, i don't see anything in the log itself. The eMail token is created but the user doesn't get an email.

**Comment by cornelinux** [comment]
Please increase debug log and take a look at it.
It is also a good idea to take a look at the email servers log!

**Comment by DuckY1987** [comment]
Sure i had a look in my mailserver log, but the last connection was from my testmail. Additionally i dont find anything till i switch to debug, and then i get a whole load of outbut, should i look after some specific word/string? exception etc?

**Comment by cornelinux** [comment]
OK,   step back. This might be a pebkac ;)

How does your email token look like?
What are you doing?
What is happening?
What do you expect to happen.?

**Comment by DuckY1987** [comment]
Sure thing:

--> Token --> Enroll Token --> eMail Token --> Then i tried:

With just email address and without user binding. With userbinding and auto-fill of the email, with and without pin.  I tried a different user&email address. I have just one realm and one resolver configured. The token gets in any case created the only thing what i noticed there is in the audit log a "Fail" in the missing line column.

29.7.16 13:38:50	GET /token/	1		PIEM0000F23E		admin			x.x.x.x	realm: ['*']	OK	FAIL	

I expect that the eMail token is mailed to the specified user.

**Comment by cornelinux** [comment]
Well,  your expectation is wrong.
http://privacyidea.readthedocs.io/en/latest/configuration/tokens/email.html

The email token delivers an otp value via email to the user during authentication.

**Comment by DuckY1987** [comment]
Okay, that explains a lot, i wanted to use it like a one time skratch code, in the case somebody deleted his TOTP token.

**Comment by cornelinux** [comment]
There is the losttoken functionality for this!Search the online doc.The help desk can provide the authentication code via manual means.
Kind regards Cornelius 


Cornelius Kölbel +49 151 2960 1417
NetKnights GmbHHttp://NetKnights. It
+49 561 3166 797

-------- Ursprüngliche Nachricht --------Von: DuckY1987 <notifications@github.com> Datum: 29.07.16  13:56  (GMT+01:00) An: privacyidea/privacyidea <privacyidea@noreply.github.com> Cc: Cornelius Kölbel <cornelius.koelbel@netknights.it>, State change <state_change@noreply.github.com> Betreff: Re: [privacyidea/privacyidea] eMail tokens are not send, email configuration is correct, testmail arrived (#480) 
Okay, that explains a lot, i wanted to use it like a one time skratch code, in the case somebody deleted his TOTP token.

**Comment by ntmoin** [comment]
![image](https://user-images.githubusercontent.com/98025657/150732644-9cfd1a50-41d0-47f9-bc1c-09de2e10e310.png)
Trying to send token over mail but finally no mail at all. It (PrivacyIDEA) seems it doesn't trigger mail at all. Normally ecoh test mail works well from PrivacyIDEA server.

**Comment by cornelinux** [comment]
@ntmoin configure your mailserver! Read the docs.
Works for a lot of installations for tens of thousands of users.

https://privacyidea.readthedocs.io/en/latest/configuration/smtpserver_config.html

https://privacyidea.readthedocs.io/en/latest/configuration/tokenconfig/email.html

**Comment by plettich** [comment]
Hi @ntmoin 
this issue was closed 5 Years ago.
Please take a look at the privacyIDEA log and maybe increase the log-level to DEBUG.
If there are problems with the configuration please ask at the community forum:
https://community.privacyidea.org

**Comment by ntmoin** [comment]
![image](https://user-images.githubusercontent.com/98025657/150917619-c7992c5c-3aee-4b99-ae82-a4bff0527ee0.png)
![image](https://user-images.githubusercontent.com/98025657/150917636-24c8d6b7-07ef-4fd5-b301-0bf6b70248af.png)
=====
Jan 24 12:10:20 pi postfix/pickup[23649]: 5C80F1C0759: uid=0 from=<root@pi.mydomain.com>
Jan 24 12:10:20 pi postfix/cleanup[23659]: 5C80F1C0759: message-id=<20220124061020.5C80F1C0759@pi.meghnabank.com.bd>
Jan 24 12:10:20 pi postfix/qmgr[23650]: 5C80F1C0759: from=<root@pi.mydomain.com>, size=406, nrcpt=1 (queue active)
Jan 24 12:10:20 pi postfix/smtp[23663]: 5C80F1C0759: to=<xxx@mydomain.com>, relay=172.x.x.x[172.x.x.x]:25, delay=0.15, delays=0.04/0.04/0.02/0.06, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 7C38914C1E08)
Jan 24 12:10:20 pi postfix/qmgr[23650]: 5C80F1C0759: removed
=====
Note: pi = PrivacyIDEA (server)

Hi Cornelinux & Plettich,
Good day and thank you so much for responding me. First of all I am so sorry to recall this so old and resolved issue again once. Please know that I have configured mail and SMTP integrations early. Even my test mails and mail settings all are okay from PrivacyIDEA to the SMTP relay server. Additionally MTA (postfix) is running in PrivacyIDEA server and set to relay to remote SMTP server. Mail setting and flow everything fine.

Though I am not sure yet I doubt it needs any policy or not to trigger email from PrivacyIDEA.
