### ISSUE TITLE
execfile() don's make sense

### ISSUE THREAD

**Issue by superlc320** [privacyidea/privacyidea#482]
In privacyidea/tools/privacyidea-fix-access-rights file

    PI_ENCFILE = None
    PI_AUDIT_KEY_PRIVATE = None
    # READ the configs
    execfile(file)

after execfile(file),
the PI_ENCFILE and PI_AUDIT_KEY_PRIVATE are also None

Can anyone explain it? Thank you~

**Comment by cornelinux** [comment]
You need to specify a config file with the parameter -f.
The config file needs to contain these variables.

**Comment by cornelinux** [comment]
You need to specify the config file with the -f parameter.

Either you did not specify the file, or the file does not contain the above mentioned variables.

**Comment by superlc320** [comment]
Actually I specify the pi.cfg file，and I'm sure the file contain the two variables.

**Comment by superlc320** [comment]
A small test as follow:
file:  pi.cfg

    strA = 'This is string A'
    strB = 'This is string B'

file: test1.py

    strA = None
    strB = None
    execfile('pi.cfg')
    print strA
    print strB

python test1.py 
can get the correct answer:

    This is string A
    This is string B

file: test2.py

    def myFunction():
        strA = None
        strB = None
        execfile('pi.cfg')
        print strA
        print strB

    myFunction()

python test2.py 
gets the wrong answer:

    None
    None

and the test2.py is similar to the privacyidea/tools/privacyidea-fix-access-rights file

**Comment by cornelinux** [comment]
Thanks a lot. I can confirm this. Some changes to locals() probably broke this functionality.
Worked beforeTM ;-)
