### ISSUE TITLE
HTTPprovider prefix number error

### ISSUE THREAD

**Issue by borschoff** [privacyidea/privacyidea#483]
Hello Cornelius!

If recipient number set with prefix like  +7 , HTTPprovider generate incorrect response:
`GET /get.ashx?sender=NAME&text=800613&type=message&login=123456&password=123456&recipient=%2B7********** HTTP/1.1`

Workaround like "set recipient number without prefix like "+"" don't applicable.
Is it posible, to set in HTTPprovider config, to ignore  prefix  "+"?

Thank you.

**Comment by cornelinux** [comment]
Do you mean the service does not accept the urlencoded "+", which translates to %2B?
The urlencoding is done by the underlying requests library.
So either you should ask to get the service fixed or try to use a POST request.

There is no chance in *not* urlencoding the "+".

Or you need to change your phone number to e.g. 007....

**Comment by borschoff** [comment]
> Do you mean the service does not accept the urlencoded "+", which translates to %2B?
Yes.

> So either you should ask to get the service fixed or try to use a POST request.
This is not service problem, but we will ask them. Also with POST request the same issue.

> Or you need to change your phone number to e.g. 007....
This change will produce more problems for another services.

Temprory workaround:
Insert phone numbers manualy.

**Comment by cornelinux** [comment]
I checked this lately. The urlencoding is performed by the unterlying requests library.
However, I did not experience +-problems with other services.

the requests library allows avoiding urlencoding for POST form requests, but not for GET requests.
So are you able to do a POST request?

**Comment by cornelinux** [comment]
Closed due to missing response and not aplicable.
We can not disable the urlencoding! Which would cause to high a securiy issue.
