### ISSUE TITLE
Machine LDAP resolver, hardcoded hostname key attribute

### ISSUE THREAD

**Issue by splattner** [privacyidea/privacyidea#485]
I try to use the LDAP Machine resolver. 

My config looks like:

> Machine ID attribute: cn
> search filter: (objectClass=computer)
> hostname attribute: cn
> ip address attribute: aRecord

Testing the connection seems fine, the message show me that there are 4 machine objects.

On the machine page I don't see any machine objects and in the log I get:

```
[2016-08-10 15:15:18,765][5655][140268073686976][ERROR][privacyidea.lib.machines.ldap:176] Error during fetching LDAP objects: KeyError('hostname',)
[2016-08-10 15:15:18,766][5655][140268073686976][ERROR][privacyidea.lib.machines.ldap:176] Error during fetching LDAP objects: KeyError('hostname',)
[2016-08-10 15:15:18,766][5655][140268073686976][ERROR][privacyidea.lib.machines.ldap:176] Error during fetching LDAP objects: KeyError('hostname',)
[2016-08-10 15:15:18,766][5655][140268073686976][ERROR][privacyidea.lib.machines.ldap:176] Error during fetching LDAP objects: KeyError('hostname',)
```

looking at the [get_machines](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/machines/ldap.py#L115) function in 
I see on line [173](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/machines/ldap.py#L173) that you use 

`hosnmae=machine['hostname']`

and a few lines before you build the machine array with:

```
                    for k, v in attributes.items():
                        key = self.reverse_map.get(k)
                        if key:
                            if type(v) == list:
                                machine[key] = v[0]
                            else:
                                machine[key] = v
```

to me its seems that you use the ldap attribute you get from the search to build the machine array. But in my LDAP Directory, there is no hostname attribute, it is `cn` as defined before. 

Shouln't you use the `hostname_attribute` similar as you do it with `machineid`?

```
                    if self.id_attribute.lower() == "dn":
                        machine['machineid'] = dn
                    else:
                        machine['machineid'] = self._get_uid(attributes)
```

**Comment by cornelinux** [comment]
Thanks a lot for looking into this. But the hostname attribute is not hard coded.

You can set it with the HOSTNAMEATTRIBUTE. See:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/machines/ldap.py#L231
It is requested in the WebUI.

You may be referring to the reverse map
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/machines/ldap.py#L236
But this is ok. This maps the the LDAP attribute to privacyIDEA's internal identifier "hostname".

Probably the problem arises, since the "machine id" has the same attribute "cn".

In this case the reversmap
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/machines/ldap.py#L236
would look like:

    self.reverse_map = {"aRecord": "ip",
                                "cn": "hostname",
                                "cn": "id"}

In this case the reverse_map is reduced to

     {"aRecord": "ip",
      "cn": "id"}

When the machine object is built from the returned LDAP object, it will use the aRecord as ip, cn as id and... ...no hostname. -> None.

Are we on the same page here?

**Comment by cornelinux** [comment]
OK. You think we should get rid of the reverse_map?

**Comment by splattner** [comment]
this might be the problem, the double use of `cn`. I will check this and also my Pull Request #486 and then recheck if there are some changed necessary or if its just a problem in my config.

thx for your feedback

**Comment by cornelinux** [comment]
thx for your issue and the PR...

**Comment by splattner** [comment]
ok, I see now what you did there with the reverse_map. I try to use it again, I think its nicer, but I need to check what happens when to attributes have the same value (as I had with cn...)

But non the less, I think there is a problem with the substring matching. I think because I changed substring to False in https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/machine.py#L75 the test were failing.
I changed it, because I had troube with it, similar problem in #484 

I will further investigate this today, I try to come up with a solution that is working (or close the PR if no changes are needed)

**Comment by cornelinux** [comment]
It would be ok for me to get rid of the reverse_map. We could still find a general solution that allows same attributes.

**Comment by splattner** [comment]
I removed the reverse_map so far, but I have a problem with the tests, I think one of them is wrong.

But first of all:

in the `_create_ldap_filter` is there a reason why you don't add the a machine_id filter in the "not any" section? Only in the "any" section..
with that its not possible to filter for a machine_id, but thats what you do in the `def test_05_get_single_machine(self)` Test.
For me this does not make sense, one explanation could be that you cannot make a filter for dn because dn is not an [actual attribute](http://www.openldap.org/lists/openldap-software/200503/msg00520.html)

Again in `test_05_get_single_machine(self)` you wanna test for a single machine by giving a filter (machine_id="cn=machine1,ou=example,o=test"), but this filter is not set in the create_ldap_filter and the result are all 3 machine object. In the test you just get the first one, and so the test passes, altought it does not really give this specified machine.

Do you agree?

So I guess we need a way to create a correct filter if the id_attribute is the dn.
I'm trying this now
