### ISSUE TITLE
SMS auto-enrolment for User-resolver

### ISSUE THREAD

**Issue by borschoff** [privacyidea/privacyidea#487]
Hello Cornelius!

Is it posible, to make SMS auto-enrolment for specific user-resolver?

**Comment by cornelinux** [comment]
Can you please be more specific?

**Comment by borschoff** [comment]
I'll do my best =)

I have LDAP-resolver with users (AD group), who must authenticate by OTP sending via SMS.
I don't want to give them permission for selfservice in PI. Every user in ths AD group have phonenumber in profile. 

So how i can make SMS tokens autoenrolment?

**Comment by cornelinux** [comment]
You can do this easily.
Use the API to iterate the users, check if the user has no token, enroll an SMS token. done.
You may run this in a cron job.

http://privacyidea.readthedocs.io/en/latest/modules/api/token.html#post--token-init

**Comment by borschoff** [comment]
Hello Cornelius.

Could you give example of any workable script that itteract with API?

**Comment by cornelinux** [comment]
Either take a look at privacyideaadm, which is located in another repostory.
Or you can look at pi-manage script, or take a look in the tools directory here. E.g. the script privacyidea-get-serial is not working on the API, but on the libraries. Such a script needs to be run on the privacyIDEA machine as "root".

**Comment by borschoff** [comment]
Ok, i found it ... how to set phone number for token?

```
privacyidea  token init --user user1 --pin 1234 --type sms
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:732: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
Namespace(admin='administrator', adminrealm='', description='command line enrolled', etng=False, func=<function inittoken at 0x7f9dafc6e398>, nosslcheck=True, otpkey=None, password='privatePipi', pin='1234', serial=None, type='sms', url='https://localhost', user='pavelkomy')
Traceback (most recent call last):
  File "/usr/bin/privacyidea", line 1482, in <module>
    main()
  File "/usr/bin/privacyidea", line 1476, in main
    args.func(args, client)
  File "/usr/bin/privacyidea", line 402, in inittoken
    resp = client.inittoken(param)
  File "/usr/lib/python2.7/dist-packages/privacyideautils/clientutils.py", line 159, in inittoken
    return self.post('/token/init', param)
  File "/usr/lib/python2.7/dist-packages/privacyideautils/clientutils.py", line 144, in post
    return self._send_response(r)
  File "/usr/lib/python2.7/dist-packages/privacyideautils/clientutils.py", line 101, in _send_response
    description=r.text)
privacyideautils.clientutils.PrivacyIDEAClientError: u'ERR400: {"jsonrpc": "2.0", "signature": "62897572........................970124493", "detail": null, "version": "privacyIDEA 2.10.2", "result": {"status": false, "error": {"message": "ERR905: Missing parameter: \'phone\'", "code": 905}}, "time": 1472123444.239024, "id": 1}'

```

**Comment by cornelinux** [comment]
This is not the API, this is the command line client! It does not set phone numbers.
The CLI uses the API. Look in the script.
This is the REST API you are looking for:
http://privacyidea.readthedocs.io/en/latest/modules/api/token.html#post--token-init

But as mentioned you might want to use the library level to do this.
(look in the other mentioned script)

In case you are German speaking and located in the northern part of Germany you may attend a workshop "hacking privacyIDEA" in septamber.
http://www.kilux.de/index.php?seite=programm.html&untermenu=Besucher-Info#280

You are also welcome to assign NetKnights to create such a script for you.

Kind regards
Cornelius
