### ISSUE TITLE
Aladdin/SafeNet HW token not sync

### ISSUE THREAD

**Issue by borschoff** [privacyidea/privacyidea#488]
Hello Cornelius!

I have SafeNet etoken pass,  HOTP token.
After  inporting SafeNet etoken pass XML, i've try to Resynk Token in Token details, but it is not sucsesfull.

privacyIDEA is  v2.10.2.
xml file contain this strings:
```
<?xml version="1.0" encoding="utf-8"?>
<Tokens>
<Token serial="123456789012">
    <CaseModel>5</CaseModel>
    <Model>517</Model>
    <ProductionDate>11/03/2008</ProductionDate>
    <ProductName>eTPass 6.0</ProductName>
    <Applications>
      <Application ConnectorID="{a61c4073-2fc8-4170-99d1-9f5b70a2cec6}">
        <Seed>NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</Seed>
        <MovingFactor>1</MovingFactor>
      </Application>
    </Applications>
  </Token>
</Tokens>
```

Seed contain 48 digits, so it is not sha1 or sha256, correct? Should i use another hashlib?
Should i use "Seek" parameter any where?

**Comment by cornelinux** [comment]
48 hex digits would be 24bytes -> 192 bits. SHA-192? This sounds really strange...
