### ISSUE TITLE
Can't enable HSM

### ISSUE THREAD

**Issue by SherifNagy** [privacyidea/privacyidea#490]
Hello,

Currently I am not able to get HSM module to be ready, whenever I run

privacyidea -U <yourserver> --admin=<youradmin> securitymodule  --module=default

I get 

usage: privacyidea [-h] [-U URL] [-a ADMIN] [-r ADMINREALM] [-p PASSWORD] [-v]
                   [--nosslcheck]
                   {user,audit,token,machine,securitymodule,config,realm,resolver}
                   ...
privacyidea: error: unrecognized arguments: --module=default

Of course I add my correct server and admin username ... any idea ? 

I have those packages installed 

privacyidea-apache2   2.14-1trusty
privacyideaadm            2.13-1

Regards,
Sherif

**Comment by cornelinux** [comment]
For any questions, please use the privacyIDEA google group.
Run 

     securitymodule --help

to see the valid options.

**Comment by SherifNagy** [comment]
Great thanks :) !
