### ISSUE TITLE
Issue after upgrade 2.10.2 to 2.14

### ISSUE THREAD

**Issue by borschoff** [privacyidea/privacyidea#491]
Trying upgrade PI from  2.10.2 to 2.14, on Debian Jessy.
PI instaled and updating from repo:
`deb http://ppa.launchpad.net/privacyidea/privacyidea/ubuntu trusty main`

After update PI notify about error:
`(ProgrammingError) (1146, "Table 'pi.eventhandler' doesn't exist") 'SELECT eventhandler.id AS eventhandler_id, eventhandler.ordering AS eventhandler_ordering, eventhandler.event AS eventhandler_event, eventhandler.handlermodule AS eventhandler_handlermodule, eventhandler.`condition` AS eventhandler_condition, eventhandler.action AS eventhandler_action \nFROM eventhandler ORDER BY eventhandler.ordering' ()`

Should i use `pi-manage db upgrade` or somethink?
Need  backup DB before upgrade and then restore DB after upgrade?

**Comment by cornelinux** [comment]
yes.

**Comment by borschoff** [comment]
Could you be more specific?
I should use this order?
1. Backup DB
2. Upgrade package
3. Upgrade DB
4. restore DB

**Comment by cornelinux** [comment]
It is always good to backup the DB.
Of course you need to update the package before updating the database schema.

See the database schema update here.
http://privacyidea.readthedocs.io/en/latest/installation/upgrade.html#basic-pip-upgrade-process

No need to restore the database.
