### ISSUE TITLE
Error During update on Ubuntu 14.04

### ISSUE THREAD

**Issue by tceydeliler** [privacyidea/privacyidea#501]
Please think about and cover the following questions:

# Versions

privacyIDEA:
Installation method:
- [ ] from source / github
- [ ] in virtualenv
- [ ] Debian
- [x ] Ubuntu
- more details:
OS: Ubuntu 14.04
Webserver:
Apache2
# What did you try to do?
Update my Ubuntu server

Problem : When I try to run apt-get update && apt-get upgrade, I get this log:
admin@pidkmp:~$ sudo dpkg --configure -a
Setting up privacyidea-apache2 (2.14-1trusty) ...
useradd: user 'privacyidea' already exists
Module wsgi already enabled
Module headers already enabled
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled
Enabling site privacyidea.
To activate the new configuration, you need to run:
  service apache2 reload
ln: failed to create symbolic link ‘/etc/ssl/certs/privacyidea-bundle.crt’: File exists
ln: failed to create symbolic link ‘/etc/ssl/private/privacyidea.key’: File exists
/var/lib/dpkg/info/privacyidea-apache2.postinst: 32: /var/lib/dpkg/info/privacyidea-apache2.postinst: pi-manage: not found
/var/lib/dpkg/info/privacyidea-apache2.postinst: 33: /var/lib/dpkg/info/privacyidea-apache2.postinst: pi-manage: not found
/var/lib/dpkg/info/privacyidea-apache2.postinst: 34: /var/lib/dpkg/info/privacyidea-apache2.postinst: pi-manage: not found
 * Restarting web server apache2                                                                                      AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
                                                                                                               [ OK ]
/var/lib/dpkg/info/privacyidea-apache2.postinst: 109: /var/lib/dpkg/info/privacyidea-apache2.postinst: pi-manage: not found

Don't know  any squggestion about it.

**Comment by cornelinux** [comment]
privacyidea 2.15 comes with a new dependency.
Please run

     apt-get dist-upgrade
