### ISSUE TITLE
EventHandlerModule AdminNotification

### ISSUE THREAD

**Issue by simvirus** [privacyidea/privacyidea#511]
Is it possible to introduce **AdminNotification** in "Events" ?

For example it could be useful when a user lock his token (failed counter) and send an email to admin.

Regards
---
Sim

**Comment by cornelinux** [comment]
Which admin would you notify?
privacyIDEA can know a lot of token admins: internal admins and admins in administrative realms. Which one would you notify?

**Comment by simvirus** [comment]
Interesting question...
In my setup I've two admins created by "pi-manager".
These admins haven't email added (only username and password)
In my setup the best solution can be use one of these (setting its email) or use a new filed (example Config->System Config->"Notify email"), but you can choose for me...
Regards

**Comment by cornelinux** [comment]
We will be able to use the following recipients.

## Todo:
* ~~tokenowner~~
* ~~list of email addresses~~
* ~~logged in user~~
* ~~internal admin~~
* all users in an admin realm

**Comment by simvirus** [comment]
Happy!
Thanks Cornelius 👍 
I will test this features when 2.16 will be in RC
