### ISSUE TITLE
Hide admin navigation items if user permissions missing

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#512]
It would be great, to have admin navigation items hidden, if the permissions of the admin are missing, e.g.:

- Show user nav item only if userlist action is permitted
- Show token nav item only if tokenlist action is permitted (new: tokenlist action, see #465)
- Show machines nav item only if machinelist action is permitted
- Show config nav item only if configlist action is permitted

**Comment by cornelinux** [comment]
I am not sure, if this is easily possible. Since e.g. there are many different config actions. And the actions being configs, do not have an attribute like "this is a config action". Thus, this can be either done in an probably ugly manner, or the config definition has to be redone.

**Comment by berndnicklas** [comment]
I am speaking here only of the top level navigation items (user, token, machines, config). Perhaps we should discuss this in a phone call tomorrow. If someone is not allowed to list user, tokens, machines and configurations, these navigation items should be hidden (not for security, just for a lean and clear admin UI).

**Comment by cornelinux** [comment]
This can be very complex. As the the actions are not grouped together. I.e. to hide the top level menu *token* e.g., the admin must not have a long list of actions. 

Actions in lib/policy.py would have to be grouped togeather, so that the code could check if there is any action in the group "token acitons".

            ACTION.ASSIGN: {'type': 'bool',
                            'desc': _(
                                'Admin is allowed to assign a token to a '
                                'user.'),
                            'group': 'token'}

In contrast to user actions:

            ACTION.USERLIST: {'type': 'bool',
                              'desc': _(
                                  'Admin is allowed to view the list of the '
                                  'users.')},

**Comment by cornelinux** [comment]
Some of the actions might work like machines, since this is a simple policy.
We will check which one will work out simply and which one need a "group" defined.

**Comment by cornelinux** [comment]
Some policies will allow actions in several menus like "assign token". You can assign a token to a user and a user to a token.

Thus we could define it like this:

    ACTION.ASSIGN: {'type': 'bool',
                            'desc': _(
                                'Admin is allowed to assign a token to a '
                                'user.'),
                            'enables_menu': ["user", "token"]},

We could define a menu class:

    class MENU(object):
        USER = "usermenu"
        TOKEN = "tokenmenu"
        MACHIEN = "machinemenu"...

The **PolicyClass** could be extended with a method 

    def get_allowed_menus(admin=None, adminrealm=None, client_ip=None)


The endpoint /auth would return a list of visible menus, which could then be used with ng-show/ng-hide.
