### ISSUE TITLE
For new registration tokens, allow sending the OTP value via e-mail to the token user

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#514]
For new registration tokens it would be great to allow sending the OTP value via e-mail to the token user.

This could be implemented
- either via token enrollment dialog and a checkbox
- and/or via the event framework.

I think, the event framework would be the right place for this, it just needs a condition to make sure the token type is a registration token and a template variable {registrationcode} to fill in the registration code into the template text.

**Comment by cornelinux** [comment]
Add this to event handler framework. The registration code must be added as tag.
An event for UserNotification can be added to "enrollment" depending on the tokenype *registration*.

Scenario: User gets notified with his registration code, after the admin created a registration token for him.

**Comment by cornelinux** [comment]
In the do method we can use the options.get("response"). The response with the registrationcode looks like this:

<pre>
{
  "detail": {
    "otpkey": {
      "description": "OTP seed",
      "img": "data:image/png;base64,iVBORw0KGgpqC9deskAAAAASUVORK5CYII=",
      "value": "seed://MbjZ9vblssB1bCLHymZ140Ch"
    },
    "registrationcode": "MbjZ9vblssB1bCLHymZ140Ch",
    "serial": "REG0000D941",
    "threadid": 140026682251136
  },
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "status": true,
    "value": true
  },
  "time": 1476260810.628829,
  "version": "privacyIDEA 2.16.dev1",
  "versionnumber": "2.16.dev1"
}
</pre>

**Comment by cornelinux** [comment]
If we add the registration tag to the possible tags, this is done. This task is also contained in #515, so we closes this here.
