### ISSUE TITLE
In event framework implement additional conditions and template variables

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#515]
In the event framework it would be great to have the additional conditions

- tokentype = regex
- serialnumber = regex
- tokenrealm = regex

and the additional template variables

- {registrationcode},
- {tokenrealm}, 
- {tokenuser}

available.

**Comment by cornelinux** [comment]
At the moment each Event Module implements such filters on its own.
What is your use case here?

**Comment by berndnicklas** [comment]
Use case is to automatically send (1) registration codes (see #514) and (2) more detailed token information to the token user, after creating or assigning the tokens.

**Comment by cornelinux** [comment]
So this would be in the existing EventHandler "UserNotification".

**Comment by cornelinux** [comment]
A possible scenario here is: after a user is assigned a hardware token, he should be notified, that the token is assigned and ready to be used.

**Comment by cornelinux** [comment]
@berndnicklas what do you want with tokenuser? Do you want the loginname, the surname or the givenname?

There is already  the tag {user} which is filled with the "givenname" of the token owner.

     user=user.info.get("givenname")

**Comment by cornelinux** [comment]
imho using regex for tokentype and tokenrealm makes no sense. Either I will do an exact matching or a multiselect dropdown.

**Comment by cornelinux** [comment]
# TODO

* serialnumber as condition with regexp
* tags for 
  * {registrationcode},
  * {tokenrealm},
  * {tokenuser}

**Comment by berndnicklas** [comment]
- Multi-select is great; exact matching would be too limited.
- Since we have different user realms we want to inform users about their newly created/assigned/activated tokens about the exact token meta information, e.g. givenname (here: user), serial or registration code, username@realm (here called by myself: tokenuser@tokenrealm, e.g. smith@staff)

**Comment by cornelinux** [comment]
Well, multi select is an exact matching on each realm or tokentype. I.e. if you add a new tokentype or realm, you would need to update the event definition. But I gues you do not do this on a daily basis.

So "tokenuser" is the loginname. And the tokenrealm is in fact the user's realm.

**Comment by berndnicklas** [comment]
Yes.

**Comment by cornelinux** [comment]
![registration-token](https://cloud.githubusercontent.com/assets/1908620/19314689/58626aa8-909b-11e6-9b42-dd39af70895f.png)

**Comment by berndnicklas** [comment]
Nice ;-) Thanks!

**Comment by cornelinux** [comment]
It looks like this:
https://www.youtube.com/watch?v=ja1VeNYVxuM
