### ISSUE TITLE
Show/hide realms in login dialog

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#517]
For realms in login dialog it would be great to show/hide them, e.g. via an additional "visible" or "hidden" option for realms in the realm configuration.

**Comment by cornelinux** [comment]
Displaying a realm dropdown is already possible in the policy scope=webui, action=realm_dropdown.

The problem is, that you can not know, which realms to show and which one not. (Unless you add this to the realm def, which
1. in my opinion makes no sense (I need to know your use case) and
2. the DB model does not allow at the moment.

As you do not know, which realm is going to login, this is a bit difficult.

Please check, if this policy fits your needs.

**Comment by berndnicklas** [comment]
I am aware of the realm_dropdown action. Our use case is to hide all administrative realms while only showing ordinary user realms, since the most users will be ordinary users and administrative users easily could add their realm via the user@realm string.

**Comment by berndnicklas** [comment]
Of course I also see the problem of higher complexity here. Another solution would be to install different instances for users and admins, while removing admin realms in the configuration files of the instances for ordinary users. Yet another solution would be to override the JSON request. Or to modify the source code. Or possibly you could just hide all admin realms in login dialog, which would require all admins to login via user@realm string.

**Comment by cornelinux** [comment]
OK, I understand the requirement.

This does not seem consistent to me. In another issue you say, your admins do not need to be confused, so lets remove some entries and ease their lives. But at this point you are making the live of the admins more difficult ;-)

**Comment by cornelinux** [comment]
We can change the realm dropdown action in the scope webui from *bool* to *text* containing a list of realm, which should be displayed.

**Comment by berndnicklas** [comment]
Hello Cornelius,

after your last change in the realm drop down list (empty field added) there seems to be a problem with multiple empty fields (in our installation 2-3) showing there. It seems that in some cases (e.g. clicking multiple times on empty fields) there are empty fields added and removed.

Best regards,

Bernd

**Comment by cornelinux** [comment]
At the beginning there will be two empty fields. One is the default-if-nothing-selected-field (which I can not add or remove) and the other one is the empty entry.

As soon as you select any entry, the default-if-nothing-selected-field is removed from the select. This is a default select functionality.

**Comment by berndnicklas** [comment]
![realm-drop-down-list](https://cloud.githubusercontent.com/assets/4263918/20259584/01933002-aa56-11e6-9ea5-6d5e4123142e.png)

I did not look into the code... This (sometimes) happens when clicking multiple times on empty fields (Chrome, Firefox). Since two or three empty fields on log-in are not very intuitive for the users, I think we should either go back to the former behavior (one empty field by default, which hides if some field was selected) or have a general rework of the realm field (e.g. an ordinary input field showing "Realm" by default and while focused showing a dropdown-menu with selectable realms, like in user assignment dialog). I think the second option would be better.

**Comment by cornelinux** [comment]
easy easy! 
How does your policy look like?

**Comment by berndnicklas** [comment]
{ "realm_dropdown": "staff students hrz" }

**Comment by cornelinux** [comment]
Indeed. If you click on the first empty entry, you get 3 empty entries.
When clicking on another than the first entry, you have two. Can confirm this.
