### ISSUE TITLE
ProgrammingError while filtering audit log by success

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#518]
# Versions

privacyIDEA installation method:
- [x] from source / github (version from august, 8)
- [ ] in virtualenv
- [x] Debian --> Jessie
- [ ] Ubuntu

Database:
- [x] PostgreSQL

# What did you try to do?
Filter audit log by success, e.g. by "1" (=success).

# What outcome did you expect?
Only show successful actions.

# What outcome did you experience?
ProgrammingError

# Log file
(ProgrammingError) operator does not exist: integer ~~ unknown LINE 4: WHERE pidea_audit.success LIKE '%1%' AND pidea_audit.action ... ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. 'SELECT count(*) AS count_1 \nFROM (SELECT pidea_audit.id AS pidea_audit_id \nFROM pidea_audit \nWHERE pidea_audit.success LIKE %(success_1)s AND pidea_audit.action LIKE %(action_1)s) AS anon_1' {'success_1': u'%1%', 'action_1': u'%/validate%'}

Can anybody reproduce this? Could this be related with the PostgreSQL database we are using?

Best regards,

Bernd

**Comment by cornelinux** [comment]
Touché.
The "success" column is an integer column containing 1 or 0.
The statement filters for "%1%" --- a string. This works well with mysql, which obviously performes a type conversion.

Which postgres dialect are you using? E.g. your SQLAlchmey_URL?

**Comment by berndnicklas** [comment]
Just "postgresql://..." which should be the same like "postgresql+psycopg2://...", right?

**Comment by cornelinux** [comment]
I think it depends on which sub-dialect you have installed.
http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html

Another dialect might be able to automatically transform this (if the database does not).

But propably we might need to fix this...
