### ISSUE TITLE
2.15: Proxy not allowed to set IP

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#520]
Installation method:
- [ ] Ubuntu
Webserver: Apache

# What did you try to do?
When authenticating a token I now get:
[2016-10-11 06:44:20,434][20036][139633224001280][WARNING][privacyidea.lib.utils:439] Proxy fd23:e163:19f7:1234:222:4dff:fe7c:d76a not allowed to set IP to fd23:e163:19f7:1234:222:4dff:fe7c:d76a.

# What outcome did you expect?
Since both IPs are the same, I didn't expect that message at all.

**Comment by cornelinux** [comment]
Does your authentication request contain a *client* parameter? The client parameter requires the "Override Authorization Clients" to be set. (Even if setting the same IP)

**Comment by jh23453** [comment]
Cornelius Kölbel <notifications@github.com> writes:

> Does your authentication request contain a *client* parameter? The
> client parameter requires the "Override Authorization Clients" to be
> set. (Even if setting the same IP)

As far as I can see: no. The debug log from pam_yubico:
[../pam_yubico.c:pam_sm_authenticate(1027)] ykclient url used:
https://athene.jochen.org/ttype/yubikey?id=23453&nonce=vxetbzdgizylnzpuyjlewgvwbiiaxvfu&otp=vvcthnnefrinkbrkgeiigccvtnddrdnvnuikkdgjujcl&h=PGNrkym%2B9EMPGDmQ2NlZLFR%2FdLI%3D

-- 
The only problem with troubleshooting is that the trouble shoots back.

**Comment by cornelinux** [comment]
Looking at the code you somehow have for one reason a ``request.access_route``. Usually this is set, when the request is sent through a proxy. So the question is, how ykclient works internally.
Thus you get a ``mapped_ip`` set:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/utils.py#L431

Please simply try to add your IP address as allowed for *override authorization client*:
http://privacyidea.readthedocs.io/en/latest/configuration/system_config.html#override-authorization-client

**Comment by cornelinux** [comment]
@jh23453 Do I get it right, that you are just "complaining" about the warning message?

**Comment by jh23453** [comment]
Cornelius Kölbel <notifications@github.com> writes:

> @jh23453 Do I get it right, that you are just "complaining" about the warning message?

Yes :-)  I'll try to look into it some more, but I consider it not
critical, just mildly annoying. And likely one reason might be using
IPv6.

Jochen

-- 
The only problem with troubleshooting is that the trouble shoots back.

**Comment by cornelinux** [comment]
OK, avoiding the warning message is not problem. Will merge the fix-branch...
