### ISSUE TITLE
In event framework implement event names and disable/enable option

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#522]
While playing with the event framework last month I realized that - from a usability point of view - it is a little clumsy to use, because every event definition is named by a number and there is no possibility to deactivate/activate event definitions. Better would be something similar to the policy framework.

What do you think about it?

**Comment by cornelinux** [comment]
Well, we can hide the number. Instead of a name there is a description... I am not sure if the policy framework is great having no ID ;-)

But activating/deactivating an event definition is a good idea!

**Comment by cornelinux** [comment]
hm, oh there is no description at the moment.
So I guess we should 

* add a description
* add enable/disable

**Comment by cornelinux** [comment]
### TODO

* Add fields "name" and "active" to UI
* Use field "active" in event handling. (i.e. only get active events, when evaluating events)
