### ISSUE TITLE
Disabled mail/sms tokens cause challenge not being sent when authenticating

### ISSUE THREAD

**Issue by lindenaar** [privacyidea/privacyidea#524]
It seems that when selecting a token to send out an OTP, the algorithm ignores whether a token has been disabled. It complains that multiple tokens to create a challenge were found, even though only one is active.

# Versions
  - privacyIDEA: 2.14 and 2.15 (observed this behaviour in both versions)
  - Installation method: pip in virtualenv on Python 2.7
  - OS: OS X Server (OS X 10.11 - El Capitan + OS X Server )
  - Webserver: Apache/2.4.18 + mod_wsgi

# What did you try to do?
I setup an e-mail and an SMS token for a user, one token is active and the other token is disabled (so that the user can switch easily). When I try to authenticate with only the userid and a password to trigger an OTP to be send (over the HTTP /validate/check interface), this results in a failure because "Multiple tokens to create a challenge found!". The JSON received in this case is:

~~~
DEBUG - result: {
    "jsonrpc": "2.0",
    "time": 1476800976.251272,
    "detail": {
        "message": "Multiple tokens to create a challenge found!",
        "threadid": 199145998205056
    },
    "versionnumber": "2.15",
    "version": "privacyIDEA 2.15",
    "result": {
        "status": true,
        "value": false
    },
    "signature": ".....",
    "id": 1
}
~~~

# What outcome did you expect?
I would expect the system to ignore disabled tokens and send out the challenge for the only active token.

# What outcome did you experience?
The system gives an error and does not send and OTP. This users has multiple tokens (a mix of SMS/eMail/TOTP/HOTP/Yubico tokens) and all the other tokens work (so the problem is not the password).

it does not matter whether the SMS or the E-mail token is disabled. When I remove the disabled (either the SMS or the E-mail) token, the challenge is sent (so the challenge tokens themselves work).

Any suggestions how to fix this (or does this require a code fix0?

Thanks!

regards,

Frederik

**Comment by cornelinux** [comment]
Thanks for reporting this. I will have a look at it. Might need a fix in the code.

**Comment by cornelinux** [comment]
This happens in the function check_token_list.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L1877

This takes a list of tokens and checks if the PIN and OTP matches. The function is called from check_user_pass. We could there however only find active tokens of the user. But we find all tokens of the user, to be able to give messages like "your token is locked".
This would happen here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L1984

But this is the reason - in case of challenge-response - the challenge_request_token_list will contain two tokens of the user, which are matching challenge response tokens, which are issuing a request. The active and the inactive on.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L2051
(In contrast the challenge_response_token_list contain the token, which would contain a valid response to a previous C/R request)

At the moment we do not check if any of these tokens in the list is inactive. Thus we need to reduce the list to only active tokens.
