### ISSUE TITLE
SQL-error: "Data too long for column 'info' at row 1"

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#525]
privacyIDEA 2.15, Ubuntu 16.10
Webserver: apache

# What did you try to do?
I've changed my privacyidea configuration to allow one IPv6 client to overwrite the client.
I've found the following SQL error in privacyidea.log:
DataError: (pymysql.err.DataError) (1406, u"Data too long for column 'info' at row 1") [SQL: u'INSERT INTO pidea_audit (date, signature, action, success, serial, token_type, user, realm, administrator, action_detail, info, privacyidea_server, client, loglevel, clearance_level) VALUES (%(date)s, %(signature)s, %(action)s, %(success)s, %(serial)s, %(token_type)s, %(user)s, %(realm)s, %(administrator)s, %(action_detail)s, %(info)s, %(privacyidea_server)s, %(client)s, %(loglevel)s, %(clearance_level)s)'] [parameters: {'info': 'email.port=25,...OverrideAuthorizationClient=127.0.0.1,127.0.1.1,192.168.30.111 fd23:e163:19f7:1234:382d:17e5:2a0e:2f20, ', 'administrator': u'jochen', 'realm': None, 'success': 1, 'privacyidea_server': 'athene.jochen.org', 'loglevel': None, 'action_detail': '', 'token_type': None, 'action': 'POST /system/setConfig', 'client': 'fd23:e163:19f7:1234:382d:17e5:2a0e:2f20', 'user': '', 'clearance_level': None, 'signature': '', 'date': datetime.datetime(2016, 10, 18, 19, 28, 46, 126425), 'serial': None}]

[Some stuff replaced with "..."]

I guess that the field info in table pidea_audit is too small:
mysql> describe pidea_audit;                                                                                                                                            
+--------------------+--------------+------+-----+---------+----------------+
| Field              | Type         | Null | Key | Default | Extra          |
+--------------------+--------------+------+-----+---------+----------------+
...
| info               | varchar(50)  | YES  |     | NULL    |                |

**Comment by cornelinux** [comment]
I guess the configuration is saved?

Is this log entry missing completely?

**Comment by jh23453** [comment]
Am 2016-10-18 22:43, schrieb Cornelius Kölbel:
> I guess the configuration is saved?

Yes, the configuration had been saved.

> Is this log entry missing completely?

I'll check when I get back from work - I didn't check.

Jochen

-- 
The only problem with troubleshooting is that the trouble shoots back.

**Comment by cornelinux** [comment]
OK, I reproduced this. The audit entry is not written. I am not happy with enlarging all fields per se. This can result in a database table that is to big for some database types.

You could *not* use the mysql STRICT mode.

Or we could truncate the fields in the code to the length of the columns. This sounds quite relieable to me. But if you would enlarge the fields in the database, the code would strip to entry to 50 anyways.

What do you think?

**Comment by jh23453** [comment]
Am 2016-10-19 10:03, schrieb Cornelius Kölbel:
> OK, I reproduced this. The audit entry is not written. I am not happy
> with enlarging all fields per se. This can result in a database table
> that is to big for some database types.

And the pidea_audit table will grow quite fast with usage. Even on my
small system there are lots of entries.

> You could _not_ use the mysql STRICT mode.

I prefer to run whatever comes with the packages out of the box.

> Or we could truncate the fields in the code to the length of the
> columns. This sounds quite relieable to me. But if you would enlarge
> the fields in the database, the code would strip to entry to 50
> anyways.
> 
> What do you think?

My most important goal is to not get spurious error message in the log.
For my usecase truncation of field info before running the insert SQL 
command
would be fine.  So just something like substr(info,1,50) would be ok.
Most of the time we know the length (e.g. IPv6 addresses) and can
enlarge the field. Here the length seems to be not really restricted,
so let's truncate it.

I can see other usecases where a "diff" of the changed options would
be useful or required, but I'd defer that until a user really needs it.

Jochen

-- 
The only problem with troubleshooting is that the trouble shoots back.

**Comment by cornelinux** [comment]
The columns "action_details" and "info" are supposed to give more information about events that occured. E.g. what did the administrator change in fact. 
Thus we might loose some information, which I do not know who uses it at all.
But the real problem is, that many databases restrict the size of a row. And all columns in sum may only be e.g. 2048 bytes! (I had this problem with oracle once).

As far as the number of rows is concerned, you should rotatet the audit log:
http://privacyidea.readthedocs.io/en/latest/audit/index.html?highlight=rotate%20audit

**Comment by jh23453** [comment]
Am 2016-10-19 11:41, schrieb Cornelius Kölbel:
> But the real problem is, that many databases restrict the size of a
> row. And all columns in sum may only be e.g. 2048 bytes! (I had this
> problem with oracle once).

That should be fixed since ages - SAP used to hit database limits years 
ago,
but I haven't seen something like that in the last years...

> As far as the number of rows is concerned, you should rotatet the
> audit log:
> http://privacyidea.readthedocs.io/en/latest/audit/index.html?highlight=rotate%20audit

That's something I missed until now.  Would you like me to open an issue 
and
prepare a cron configuration at least for Ubuntu installations?

Jochen

-- 
The only problem with troubleshooting is that the trouble shoots back.

**Comment by cornelinux** [comment]
Yes, you are welcome to do so!
All configuration goes into the packages privacyidea-apache2 and privacyidea-nginx.

**Comment by cornelinux** [comment]
One note about rotating. I was thinking of using gevent to rotate the auditlog.
See #504.
This way it could be located within the privacyIDEA code and we even would not need an external cron.

**Comment by cornelinux** [comment]
Some users might enlarge their database tables to fit the values. I am hesitant to strip the entries to a fixed length. Since in this case we would also strip e.g. the info field to 50, although the user enlarged the info field to 300.
We coulld add a parameter to pi.cfg, which says 

    PI_TRUNCATE_AUDIT_ENTRIES = True

@jh23453 What do you think?

**Comment by jh23453** [comment]
Yes, that's fine.

**Comment by cornelinux** [comment]
OK, it will be

    PI_AUDIT_SQL_TRUNCATE = True
