### ISSUE TITLE
token handler

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#532]
We could add another EventHandler `TokenHandler` which could have the following actions.
# Actions

- ~~delete token~~
- ~~disable token~~
- ~~enable token~~
- ~~enroll token~~
- ~~set token options (description, validity...)~~
- ~~set token realm~~
- ~~unassign~~
## Options

We need to determine, either the `serial number` or the `user` to get the tokens on which these actions will be performed.

# Conditions

* ~~user has &lt;num&gt; tokens~~
* ~~user logged in~~
* ~~admin logged in~~
* ~~tokentype~~
* ~~token locked~~
* ~~token has no owner~~
* ~~token is orphaned~~

# Todo

* add user to init-action 
  * user from request
  * token owner from token in request. (But if the token is deleted, the token does not exist anymore and we can not determine the tokenowner! :-/

**Comment by cornelinux** [comment]
By adding a **init** action we could create a new registration token for a user, as soon as the last token of the user is deleted.

The notification event could then directly send the new registration token to the user :-)

**Comment by berndnicklas** [comment]
Also interesting would be to set token specific attributes, e.g. the description field or the validity time of the token.

**Comment by cornelinux** [comment]
Hi @berndnicklas ,

can you provide some more specifics on your requirements? Setting the token description to a fixed value?

Setting the validity time maybe to 
* currnet time + (some hours / days)
* fixed date

Thx
Cornelius

**Comment by berndnicklas** [comment]
> > can you provide some more specifics on your requirements? Setting the token description to a fixed value?
> 
> Setting the validity time maybe to
> 
> - currnet time + (some hours / days)
> - fixed date

Description: Four our use case, a fixed value would be OK.
Validity time: I think, current time + (minutes / hours / days) would be great. I don't know, if a fixed date would make that much sense here.

**Comment by cornelinux** [comment]
OK, thanks.
I think there could be also a group of part time workers, where it could be interesting to have a fixed ending.
Or an enrollment scenario with a fixed starting point. So I think we will do both:

* set validity period
  * start:
    * fixed     [date]
    * relative [num of days]
  * end:
    * fixed     [date]
    * relative [num of days]
