### ISSUE TITLE
ldap resolver error

### ISSUE THREAD

**Issue by PayneMax** [privacyidea/privacyidea#535]
I made fresh installation with PIP on debian server. When I try to set AD resolver I get this error  [ERROR][privacyidea.lib.user:628] AttributeError("'module' object has no attribute 'POOLING_STRATEGY_ROUND_ROBIN'",)

Any idea what can be wrong?
Thanks for help
Miro

**Comment by cornelinux** [comment]
Yes. The ldap3 module > 2.0.7 dropped this constant. You can install

   pip install ldap3==1.4.0

See 
https://github.com/privacyidea/privacyidea/commit/877375c127a41c2d970f7b925faae0f781adc6d5

**Comment by PayneMax** [comment]
Thanks a lot Cornelinux, it is working now
