### ISSUE TITLE
Filtered Auditlog not downloadable

### ISSUE THREAD

**Issue by mimugmail** [privacyidea/privacyidea#539]
Please think about and cover the following questions:

# Versions
2.15

privacyIDEA:
Installation method:
- [X ] from source / github
- [X] in virtualenv
- [X] Debian
- [ ] Ubuntu
- more details:
OS: Debian 8
Webserver: Apache

# What did you try to do?
Go to Auditlog, do some filtering, download as CSV

# What outcome did you expect?
A CSV with only the filtered lines

# What outcome did you experience?
A CSV with all entries

# Log file

**Turn on debug level and take a look at the privacyidea.log!**
**If appropriate, attach the log file.**

**Comment by cornelinux** [comment]
The UI is not precise about this or misleading. Initially the export as CSV is an export of the complete auditlog - intentionally.

We could use 

    self._create_filter

in the csv export function to do so.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/auditmodules/sqlaudit.py#L410
