### ISSUE TITLE
WebUI: Fix and extend print design for paper token

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#540]
Print design for paper tokens needs to be fixed. After choosing to print the otp list only plain html is shown and printed. According to the [code documentation](https://github.com/privacyidea/privacyidea/blob/cc5fd2569b69fb514315d369b89e20e9a35b9a8e/privacyidea/static/components/token/controllers/tokenControllers.js#L421) this could be related with https sites.

Also, additional information could be included into the view:
- a page header with policy defined tokenissuer and tokenlabel (both currently only used for hotp/totp tokens).
- a page footer with a description how to use these one time passwords, e.g. `One time passwords must be used in sequence (one by one). Used one time passwords should be crossed out.` or in German `Einmalpassworte sind der Reihe nach zu verwenden (eines nach dem anderen). Bereits verwendete Passworte sollten gestrichen werden.`

**Comment by cornelinux** [comment]
The Paper token works as designed ;-)
May be broken by design.

We need to check, if it is possible to use a template.
The template then can contain tags like {tokenowner}, {serial}...

**Comment by cornelinux** [comment]
Could use python reportlab?
Or just create a more flexible/nice HTML page, which can then be printed (as pdf)

**Comment by berndnicklas** [comment]
The temporary HTML/CSS browser tab solution is good. Reportlab/PyPDF would be indeed a security issue.

**Comment by cornelinux** [comment]
# TODO

* Create a policy enrollment, "paper-token-count" (default 100)
* eventHandler condition: OTP-counter >= 90, OTP-counter == 100...
* CSS beautify
* Explanaition: Use OTP values in the right order. Scratch them off.

**Comment by cornelinux** [comment]
@berndnicklas 
We now have an extra papertoken.css. Please take a look at the styling, since I am not the big graphics guy. Thx.
