### ISSUE TITLE
Information hiding for audit log

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#541]
It should be possible to selectively hide some information from audit log (especially from ordinary user/self-service audit log), e.g. whole columns
- client IP address
- privacyidea server
- administrator
or also e.g. by log entry filter
- e.g. only show actions containing "^POST /validate/check$" or "^POST /auth$"

**Comment by cornelinux** [comment]
You can hide the complete audit log for the user!

But you want to hide either

1. complete columns
2. or complete entries (defined maybe by a filter)

**Comment by cornelinux** [comment]
Maximum age of log entries displayed:
A configuration parameter (in pi.cfg) could define, how old the maximum values, that are displayed in the UI/REST may be.

**Comment by cornelinux** [comment]
Hi @berndnicklas 

I think it might be OK to not add this limit to pi.cfg but as a policy.
Usually settings in pi.cfg are chosen to be more of a system setting and a security feature. Settings in pi.cfg can not be changed by the token-super-admin. I.e. even the token admin with the highest priviledge can *not* disable auditing. This way even he can be "monitored".

This *maximum age* setting is ment just for displaying entries. There is no way of mangling or compromizing the audit data. Thus I think it is better to puth it into a policy.
We already have the "auditlog" policy in the scopes "user" and "admin", which allows the users or admins to view the auditlog at all. 
I think this is the right place to put the maximum age policy, which only lists the entries of the last x days, y month or z years.

**Comment by cornelinux** [comment]
Add action **auditlog_age** to the scopes **user** and **audit**.

The age can be specified with the identifiers "d" (day) "m" (month) and "y" (year).

**Comment by berndnicklas** [comment]
> We already have the "auditlog" policy in the scopes "user" and "admin", which allows the users or admins to view the auditlog at all.
> I think this is the right place to put the maximum age policy, which only lists the entries of the last x days, y month or z years.

Great! Having at least n minutes and n hours would be also great, if some organization wants to restrict the audit log to a very short time. In some organizations you have very strict work councils that possibly want to limit such logs very hard (e.g. only 30m for short time support/debugging purposes).

**Comment by cornelinux** [comment]
Admins can download the audit log as csv. The complete auditlog. I will add a policy do allow/deny the download of the audit log for admins.

**Comment by cornelinux** [comment]
Please take a look at the feature branch 541/limit_audit_log. This will allow you to set the audit log age.
Please note, that you need admin policies set!

policy:

    scope: admin
    action: auditlog_age=2d

to limit audit log to 2 days.

**Comment by cornelinux** [comment]
## TODO
* Admins can download the audit log as csv. The complete auditlog. I will add a policy do allow/deny the download of the audit log for admins.
* fix maximum number of audit entries in case of timelimit
