### ISSUE TITLE
Add resolver information to audit log

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#542]
Resolver information should be added in the audit log.

The user information gets written to audit log at this central position. At this point we would be able to determine the resolver of the user.

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/before_after.py#L135

Nevertheless, there are some challenges to take care of, if this should be added to the SQLAuditModule:

* The database schema needs to be extended. This is a bit difficult, since at the moment there is not automatic process of updating the SQLAudit Schema. The database table is created here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/auditmodules/sqlaudit.py#L185

* Do we want to add resolver to the view? We need to adapt the static templates.

**Comment by cornelinux** [comment]
The commit 74fe247 adds the *resolver* to the audit log dictionary.
Now every audit module could also use and log the *resolver*. 
At the moment the sqlaudit module does not use it.

We would have to:

* extend DB schema
* add it to the LogEntry in finalize_log.

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/auditmodules/sqlaudit.py#L106
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/auditmodules/sqlaudit.py#L278

**Comment by berndnicklas** [comment]
Hello Cornelius,

with commit https://github.com/privacyidea/privacyidea/commit/74fe247cf096244eb1b98713434e5d051fad17d7 I experience locking problems in PostgreSQL database server, which - while requesting the audit log several times (e.g. not with the first request, but with the second) - results in timeouts of Nginx web server for all privacyidea instances connected to the database server. 

It seems the ALTER TABLE statement is run one or more times and blocks all other SQL queries until uwsgi process is killed.

pg_top list of active postgresql processes
... postgres  20    0  640M   13M sleep   0:00  0.00%  0.00% postgres: privacyidea privacyidea ... ALTER TABLE waiting                                                  
... postgres  20    0  647M   14M run     0:00  0.00%  0.00% postgres: postgres postgres [local] idle          

```
Locks held by procpid ... (process with pidea_audit ALTER TABLE statement):

  | database    | table | type                | granted
--+-------------+-------+---------------------+--------
1 | privacyidea |       | ExclusiveLock       | t      
2 | privacyidea |       | AccessExclusiveLock | f      
```

```
Locks held by procpid ... (process with pidea_audit log query, idle):

  | database    | table | type            | granted
--+-------------+-------+-----------------+--------
1 | privacyidea |       | ExclusiveLock   | t      
2 | privacyidea |       | AccessShareLock | t      
3 | privacyidea |       | AccessShareLock | t      
```

```
Tue Nov 22 17:39:53 2016 - *** HARAKIRI ON WORKER 2 (pid: ..., try: 1) ***
Tue Nov 22 17:39:53 2016 - HARAKIRI !!! worker 2 status !!!
Tue Nov 22 17:39:53 2016 - HARAKIRI [core 0] ... - GET /audit/?action=**&action_detail=**&administrator=**&client=**&date=**&info=**&page=5&page_size=10&privacyidea_server=**&realm=**&resolver=**&serial=**&sortorder=desc&success=**&tokentype=**&user=** since 1479832732
Tue Nov 22 17:39:53 2016 - HARAKIRI !!! end of worker 2 status !!!
Tue Nov 22 17:39:54 2016 - DAMN ! worker 2 (pid: ...) died, killed by signal 9 :( trying respawn ...
```

Can you reproduce this in one of your test installations?

Best regards,

Bernd

**Comment by berndnicklas** [comment]
Leaving the https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/auditmodules/sqlaudit.py#L191 solves the problem (of course then no schema upgrade is done; I did it manually before installation, by the way).

**Comment by cornelinux** [comment]
I think we need to rethink this.Could add pidea_audit to schema.Thus easier update.
Most people are running audit in the token dB anyway. no extra DB ... although it could be run in any external database. ..


-------- Ursprüngliche Nachricht --------Von: berndnicklas <notifications@github.com> Datum: 22.11.16  17:54  (GMT+01:00) An: privacyidea/privacyidea <privacyidea@noreply.github.com> Cc: Cornelius Kölbel <cornelius.koelbel@netknights.it>, State change <state_change@noreply.github.com> Betreff: Re: [privacyidea/privacyidea] Add resolver information to audit log (#542) 
Leaving the https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/auditmodules/sqlaudit.py#L191 solves the problem (of course then no schema upgrade is done; I did it manually before installation, by the way).
