### ISSUE TITLE
Add Reply-To field to SMTP server definition

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#544]
It would be great to have a Reply-To field in SMTP server definition, which we could use for our support e-mail address.

The concrete scenario:
- We want to send S/MIME-signed confirmation E-Mails (automatically signed by local MTA filter) from a server e-mail address, that's dedicated for sending signed e-mails and does not answer e-mails.
- We want users to reply to another, central support e-mail address, that does not use S/MIME signatures or encryption and is directly connected to our support ticket system.

**Comment by cornelinux** [comment]
This is in the notification event handler?

The central SMTP server definition is also used for e.g. sending of SMS/Email-Token. Hm. This could make sense, too.

So I would add a reply-to in the central SMTP def **and** in the Notification option!

What do you think?
