### ISSUE TITLE
Selecting a validity_period not working as expected

### ISSUE THREAD

**Issue by MaRRiK74** [privacyidea/privacyidea#548]
-Using Version2.15

When choosing a validity_period_start & validity_period_end while selecting 18-nov will result in:

validity_period_start: 17/11/16 23:00  
validity_period_end: 17/11/16 23:00 

Better would be:
validity_period_start: 18/11/16 0:01  
validity_period_end: 18/11/16 23:59

**Comment by cornelinux** [comment]
this is a known issue #239
