### ISSUE TITLE
On editing existing event handler definitions, some existing conditions are removed

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#551]
# Versions

privacyIDEA: trunk

Installation method:

- from source / github
- Debian

Webserver:

- nginx
- uwsgi

# What did you try to do?

I tried to edit an existing event handler definition (HandlerModule: UserNotification) in web ui.

# What outcome did you expect?

Display and save all formerly existing and unmodified conditions as is.

# What outcome did you experience?

On showing the handler definition, existing conditions of type

`token_locked == ...` 

or 

`result_value == ...` 

are removed, which after saving leads to unintended behaviour (e.g. send Token-Locked-E-Mails for all users that try to authenticate via /check/validate).

**Comment by cornelinux** [comment]
What database are you running?

The token_locked and result_value should save a value like "True". 
Can you please state the contents of the database table "eventhandlercondition" for the key "token_locked"?

**Comment by berndnicklas** [comment]
PostgreSQL.

```
privacyidea=# select * from eventhandler where id=9;
 id | ordering |     event      |  handlermodule   | condition |  action  
----+----------+----------------+------------------+-----------+----------
  9 |        0 | validate_check | UserNotification |           | sendmail
(1 row)
```

```
privacyidea=# select * from eventhandlercondition where eventhandler_id=9;
 id | eventhandler_id |     Key      |          Value          | comparator 
----+-----------------+--------------+-------------------------+------------
 14 |               9 | tokenrealm   | a,b,c,d,e,f,g           | equal
 15 |               9 | token_locked | True                    | equal
 30 |               9 | result_value | True                    | equal
 16 |               9 | tokentype    | yubikey,paper,totp,hotp | equal
(4 rows)
```

So, at least, the values are saved ;-)

**Comment by berndnicklas** [comment]
Of course, this is before saving the handler definition a second time in the web ui.

**Comment by cornelinux** [comment]
OK, and after saving the handler definition the database column Value is empty for token_locked?

This would mean, that we only have a UI issue here. Good.

**Comment by cornelinux** [comment]
I can confirm the the normal select boxes are broken. Funny thing. The more complicated multiselects work fine :-)
The value is not set correctly. Somewhere in the javascript the values are lost. need to investigate this.

**Comment by cornelinux** [comment]
Hi @berndnicklas ,

I think this is fixed, now. At least I verified this in my setup.
If possible, please confirm.

**Comment by berndnicklas** [comment]
It's fixed, thanks!
