### ISSUE TITLE
Here is an alternative SMS Gateway using Twilio API

### ISSUE THREAD

**Issue by gyp5y** [privacyidea/privacyidea#554]
I've made an additional SMS Gateway module. It uses Twilio REST API client (https://github.com/twilio/twilio-python/tree/next-gen)
It would be nice to see it in next releases.

[TwilioSMSProvider.py.zip](https://github.com/privacyidea/privacyidea/files/606591/TwilioSMSProvider.py.zip)

**Comment by cornelinux** [comment]
Cool. Thanks a lot!
Can you create a pull request?
Otherwise I will check and merge the zip.

**Comment by gyp5y** [comment]
I don't know how to add twilio-python to dependencies. I've patched installed version so I can't commit it. Merge zip and add deps if you can. Thanks.

**Comment by cornelinux** [comment]
As python-twillo is not contained in a standard distribution repository and I do not want to package and maintain it, I would recomment a conditional import. Thus if the administrator installs this package manually, he is able to use twillo.

**Comment by cornelinux** [comment]
After looking into the twilio API and the code it does occur to me, that the twilio API can as well be addressed with the normal HTTP SMS Provider.
https://www.twilio.com/docs/api/rest/sending-messages
We add some documentation.

**Comment by irishgeoffny** [comment]
You can look at a very good [twilio alternative](http://textita.com) textita
http://textita.com
