### ISSUE TITLE
IP limits in policies

### ISSUE THREAD

**Issue by gyp5y** [privacyidea/privacyidea#555]
There's no way to make "not" rules or exclude subnets.
So if I need to make two policies for "inner" and "outer" clients - it's impossible.
As a sample:
First policy should include internal subnets 10.9.0.0/16 and 10.10.0.0/16 and IP xxx.xxx.xxx.xxx
Second policy should match all excepting those who matched with a first policy + 192.168.0.0/16
I think a best way to solve it is to use some king of boolean expressions like "10.9.0.0/16 and 10.10.0.0/16 and not 192.168.0.0/16"

**Comment by cornelinux** [comment]
You can exclude clients and exclude subnets.

http://privacyidea.readthedocs.io/en/latest/modules/lib/policy.html?highlight=client#client

**Comment by gyp5y** [comment]
It's not clear that I should do 0.0.0.0/0, !192.168.0.0/16 to exclude subnet from all possible IPs. But it's working so you're right.
