### ISSUE TITLE
webui ldapresolver checkbox bug

### ISSUE THREAD

**Issue by quynhnng** [privacyidea/privacyidea#563]
privacyIDEA: 2.16
Installation method: from source / github
OS: redhat
Webserver: nginx
----
When using the Configs>Users>Edit Ldap Resolvers tab, the check box for "No anonymous referral chasing" and "Edit user store" does not seem to display the correct value (checked or nochecked), and always show unchecked if the last modification is made through the webUI.

I debug a little and see that the value of `$scope.params.NOREFERRALS` and `$scope.params.EDITABLE` is `"true"` or `"false"`, and not `"1"` or `"0"` if the last modification is done through the webui. Thus, the result of this line is always false in static/components/config/controllers/configControllers.js:

`$scope.params.NOREFERRALS = ($scope.params.NOREFERRALS == "1");`
`$scope.params.EDITABLE = ($scope.params.EDITABLE == "1");`

Same with /static/components/config/controllers/ldapMachineResolverController.js.

Can you please confirm?

**Comment by cornelinux** [comment]
I guess you are using postgresql as token database? I can not confirm this with mysql and sqlite. The databases save a boolean value in a string column differently.
So I think we should use a javascript function like

      function isTrue(value) {
          return ["1", "true", true, "True"].indexOf(value) > -1;
      }

This way we can set 

    $scope.params.NOREFERRALS = isTrue($scope.params.NOREFERRALS);

**Comment by cornelinux** [comment]
@quynhnng, can you please check, if it works for your setup, now?

**Comment by quynhnng** [comment]
@cornelinux It looks good now.
Thank you.

**Comment by cornelinux** [comment]
great. Thanks for the feedback!
