### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by KarenTovmasian** [privacyidea/privacyidea#568]
Please think about and cover the following questions:

# Versions

privacyIDEA: 2.13-2

Installation method:

- from source / github Y

## more details: 

OS: CentOS Linux release 7.2.1511 (Core) 

Webserver: nginx

Tokendatabase: MySQL

# What did you try to do?
I try to investigate how i do logrotation
# What outcome did you expect?
a settings file for log rotation
# What outcome did you experience?
This is what i see in /var/log/privacyidea

# ls -l | head

total 729040

-rw-r-----. 1 privacyidea privacyidea     0 Dec  7 14:00 privacyidea.log

-rw-r-----. 1 privacyidea privacyidea     0 Dec  4 04:00 privacyidea.log-20160731.gz-20160807.gz

-rw-r-----. 1 privacyidea privacyidea     0 Dec  4 04:00 privacyidea.log-20160731.gz-20160807.gz-20160814.gz-20160821.gz

-rw-r-----. 1 privacyidea privacyidea     0 Dec  4 04:00 privacyidea.log-20160731.gz-20160807.gz-20160814.gz-20160821.gz-20160828.gz-20160904.gz

-rw-r-----. 1 privacyidea privacyidea     0 Dec  4 04:00 privacyidea.log-20160731.gz-20160807.gz-20160814.gz-20160821.gz-20160828.gz-20160904.gz-20160911.gz-20160918.gz

-rw-r-----. 1 privacyidea privacyidea     0 Dec  4 04:00 privacyidea.log-20160731.gz-20160807.gz-20160814.gz-20160821.gz-20160828.gz-20160904.gz-20160911.gz-20160918.gz-20160925.gz-20161002.gz

-rw-r-----. 1 privacyidea privacyidea     0 Dec  4 04:00 privacyidea.log-20160731.gz-20160807.gz-20160814.gz-20160821.gz-20160828.gz-20160904.gz-20160911.gz-20160918.gz-20160925.gz-20161002.gz-20161009.gz

-rw-r-----. 1 privacyidea privacyidea     0 Dec  4 04:00 privacyidea.log-20160731.gz-20160807.gz-20160814.gz-20160821.gz-20160828.gz-20160904.gz-20160911.gz-20160918.gz-20160925.gz-20161002.gz-20161009.gz-20161016.gz

-rw-r-----. 1 privacyidea privacyidea     0 Dec  4 04:00 privacyidea.log-20160731.gz-20160807.gz-20160814.gz-20160821.gz-20160828.gz-20160904.gz-20160911.gz-20160918.gz-20160925.gz-20161002.gz-20161009.gz-20161016.gz-20161023.gz
# Log file
no logs needed on this case
**Turn on debug level and take a look at the privacyidea.log!**
**If appropriate, attach the log file.**

**Comment by cornelinux** [comment]
Do you have a log config file in place?
/etc/privacyidea/logging.cfg

**Comment by cornelinux** [comment]
can not reproduce without any user input.
