### ISSUE TITLE
Add a busy indicator to the UI

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#569]
This issue was split from #567

Have some kind of UI spinning icon or some kind indication that it is "busy" waiting for an answer when looking up users in the WebUI. (When a list of users takes 10 to 20s to return results it is not clear if no users are found or if the system is still waiting for an answer).

I would add a generic indicator. We could also spin or flash the logo.

**Comment by cornelinux** [comment]
@sam-axiadids @quynhnng 
Once the UI had such a thingy.
During the redesign to angularJS it seem to me more responsive.
I would like to add a busy indicator globally. What do you think?
We could put it at the top (which is usually always visible (not on smartphone))

![busy-spinner](https://cloud.githubusercontent.com/assets/1908620/21138673/66a5c7a8-c12f-11e6-8257-4b4189f116de.png)

**Comment by cornelinux** [comment]
The question is, how this can be implemented without producing to many redundant code.

We could save a central state, if there is still a request running/pending. We could increase a counter per startet request and decrease it per finished request. If the counter is 0, no request is pending and the spinner does not need to spin.

Problem 1: The increasing and decreasing could easily lead to out-of-sync. Then the spinner does not stop spinning
Problem 2: We would have to add code to *every* request in the factories. :-/

**Comment by cornelinux** [comment]
At the moment it is not clear, how this should be implemented.

**Comment by sam-axiadids** [comment]
Thanks Cornelius - we will see if someone in my team can take a stab at it and provide feedback or pull request

**Comment by quoc-axiadids** [comment]
@cornelinux 
71919cc

**Comment by sam-axiadids** [comment]
HI Cornelius,

Please let us know what you think of https://github.com/privacyidea/privacyidea/commit/71919ccd15c6cd87bf896c38fdcc238cc860415e

Thanks

**Comment by cornelinux** [comment]
Closed by PR #593
