### ISSUE TITLE
SMS Gateway definition: Options collide with fixed options/parameters like USERNAME <-> username

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#570]
If an SMS gateway definition is save with basic authentication (USERNAME, PASSWORD) it will always overwrite parameters/options with the same name, even if these are lower case.

Check is we should do this case sensitive.

**Comment by cornelinux** [comment]
This can not be reproduced in the debug environment with an sqlite database.
This can be reproduced in a "productive" application with MySQL database.
The code does not contain any ".lower()" function.

**Comment by blinkiz** [comment]
My SMS gateway provider wants username and password in lowercase. When writing options for this, privacyidea is converting this to uppercase.
No basic authentication, just normal GET.

GET https://aaa.fiberdirekt.net/smsgateway
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "status": true,
        "value": [
            {
                "description": "",
                "id": 1,
                "name": "fortytwo SMS HTTP API",
                "options": {
                    "CHECK_SSL": "yes",
                    "HTTP_METHOD": "GET",
                    "PASSWORD": "5454545454",
                    "RETURN_FAIL": "",
                    "RETURN_SUCCESS": "1,",
                    "TIMEOUT": "5",
                    "URL": "https://imghttp.fortytwotele.com/api/current/send/message.php",
                    "USERNAME": "username",
                    "from": "fromme",
                    "message": "Your OTP is {otp}",
                    "route": "G1",
                    "to": "{phone}"
                },
                "providermodule": "privacyidea.lib.smsprovider.HttpSMSProvider.HttpSMSProvider"
            }
        ]
    },
    "time": 1490274771.293155,
    "version": "privacyIDEA 2.18.1",
    "versionnumber": "2.18.1"
}
Workaround is to go into database "pi" and edit these two.
select * from smsgatewayoption;
Delete right row..
delete from smsgatewayoption where id=1
delete from smsgatewayoption where id=8
insert into smsgatewayoption values (8,"password","5454545454",NULL,1);

**Comment by cornelinux** [comment]
we have a smsgatewayoption.type for a while, which will differentiate between options and parameters.
