### ISSUE TITLE
On validate_check event (notification handler), testing token_locked == true prevents tokens from beeing locked

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#575]
# Versions

privacyIDEA: 2.17dev

Installation method:

- from source / github
- Debian
- NGINX / UWSGI
- PostgreSQL

# What did you try to do? / What outcome did you experience?

Setting up an notification event for validate_check event with a check for token_locked == true a notification is successfully sent, but the token is not locked. The fail counter is correctly raised to max fail.

# What outcome did you expect?

Token should be locked. Or should this be done via Token handler and "disable" action?

**Comment by berndnicklas** [comment]
By the way, it seems, that on validate_check events we have as {serial} a comma seperated list of all existing tokens. Is this by design?

**Comment by cornelinux** [comment]
The *Notification Handler* only sends notifications. I.e. "token_locked == True" is a condition. THus, it checks, IF the token is locked (i.e. the max fail counter is reached) and then it sends the notification.

If you want to disable a token, you need the *token handler*

If there are more serials, the notification handler compiles a list - yes.

**Comment by berndnicklas** [comment]
Problem is, the token objects won't be locked:

```
{ 
  "locked": false, ... 
  "tokentype": "totp", ... 
  "maxfail": 100, 
  "failcount": 100, ... 
  "active": true, ... 
  "revoked": false ...
}
```

I am sure, that the locking has worked sometime before. I'm not sure whether this is related to the defined event or a general problem. I'll try it with disabled event.

**Comment by berndnicklas** [comment]
Ok, the tokens won't be locked, even with the above mentioned event disabled.

**Comment by cornelinux** [comment]
I think we are confusing some things here.

The event **condition** "token_locked" in fact checks if the max_failcount is reached. 

The event **action** "disable" in the token handler means that after all conditions are met, the attribute "active" of a token is set to false.

Please also note, that events are evaluated **after** the request.

There is an internal token-parameter/token-state "locked" (DB column) which has another meaning.
http://privacyidea.readthedocs.io/en/latest/policies/admin.html#revoke
So the wording might be a bit confusing here. Hey, but there needs to be some place for consulting ;-)

**Comment by berndnicklas** [comment]
Ok, it's the wording that confuzzled me ;-) I expected a token which is "locked" (fail count == max fail count) by perspective of event handler to be "locked" in the token DB too. So, the solution for me is, to define an additional event to disable the token. Thanks!

**Comment by cornelinux** [comment]
Fine. 
But still - the disables token is not locked. And it has not reachted the max-fail-counter.

There are several attributes of a token, which are also different states:
* active / disabled
* DB-locked (can not be used ever again)
* mail-failcounter reachted (called "locked" in the event conditions)

In all three states a token can not be used for authentication anymore.
