### ISSUE TITLE
Some JavaScript triggered requests use wrong API URIs and produce HTTP 301 redirects

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#576]
At least these URIs are affected:

- /application instead of /application/
- /user instead of /user/
- /token instead of /token/

Possibly there are more.

# Versions

privacyIDEA: 2.17dev

Installation method:

- from source / github
- Debian
- NGINX / UWSGI
- PostgreSQL

**Comment by cornelinux** [comment]
Isn't it great, that there are 301's? ;-)

I know that from a REST standpoint, the request

    GET /token/

should return a list of tokens, which is indicated by the trailing slash.
But we could also have the server respond to */token* and to */token/* - since there is no difference between those two.
What do you think?

**Comment by berndnicklas** [comment]
I think we should follow the REST standard with trailing slash (if there are no important arguments against it). This has e.g. the advantage, that possible web server location rules can be created more easyly (eg. if we consider /token/ and /tokentype/).

The 301s are a good thing if it comes to reminding customers and developers to using the right API endpoint ;-) In our case, behind a web portal proxy server, the 301 redirect reply actually delivers the location of the workers, which are not directly accessible, which leads to "API down" messages for the portal user. I know, there are ways to change that (overriding the host request header or replacing the location response header) and I will change the setup that way. But of course, one way is to use the right API endpoint in the first place ;-)

**Comment by cornelinux** [comment]
OK. All API request *should* be encapsulated in the factories of the corresponding components:
https://github.com/privacyidea/privacyidea/tree/master/privacyidea/static/components

If you could _easily_ provide a list of the URL (like running a grep 301 over the log file) this would be great.

**Comment by berndnicklas** [comment]
From the logs in December it's only the three above mentioned URLs. You can trigger the 301s by viewing a token in the token view (not the token list) and by searching a user to assign to that token.

**Comment by berndnicklas** [comment]
Currently I can reproduce this in web ui only for /application and /user endpoint, not for the /token endpoint.

**Comment by cornelinux** [comment]
I identified only one location in the current master branch, this is the /application/ endpoint.

getUsers uses a trainling slash
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/user/factories/user.js#L41

and getTokens does also:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/factories/token.js#L100

If you please can be more precise about, when the 301 occurs...

**Comment by berndnicklas** [comment]
Searched for it, for the /user/ endpoint it seems to be in directives.js:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/directives/controllers/directives.js#L105

For the /token/ and the /machine/ endpoint it seems to be there too.

**Comment by berndnicklas** [comment]
Also, in user.js there's a HTTP PUT request without trailing slash:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/user/factories/user.js#L59

**Comment by cornelinux** [comment]
The directives is right. These do not use the factories.

From a REST standpoint the PUT request, which updates the user shoud not contain a trailing "/".
We should rather change these definitions:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/user.py#L137
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/user.py#L179

**Comment by berndnicklas** [comment]
For single elements there seems to be a consensus to have no trailing slash.

For collections there seems to be _no_ consensus about whether to have a trailing slash or not, but it's consensus to stick to one of them or having both ;-)

In the end this is not about trailing slash, but about the 301s in the web client.

**Comment by cornelinux** [comment]
right. thanks.
