### ISSUE TITLE
policy: group items in the user policy

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#582]
Right now the items seem more or less unsorted. I think it's better to group them, maybe like that:

- general tokel options
  * enroll
  * revoke
  * resync
  * unassign
...
- token types for enrollment
  * enrollTOTP
  * enrollHOTP
  * enroll...
...
- Token specific options
  * totp* options
  * hotp* options
...
- global options
  * password_reset
  * update_user
  * userlist
...

What do you think?

And  motp_webprovision should likely be renamed to enroll_motp,

**Comment by cornelinux** [comment]
The *motp_webprovision* was ment to provide a QR code for enrolling an motp token. This is not a normal feature of motp. This is why it was put into an addition policy -> *enrollMOTP* lets you enroll it via the base32 encoded secret. *webprovision* lets you enroll it via QR code. But obviously the policy is not used anymore, anyway.

**Comment by cornelinux** [comment]
Hi @jh23453 
I implemented accordions which are created depending on the policy group in ``lib/policy.py``.

Please take a look at it and if you have any additional suggestions for the group, please drop a note.

I know, some German translations are missing...

**Comment by jh23453** [comment]
Hi Cornelius,

Cornelius Kölbel <notifications@github.com> writes:

> I implemented accordions which are created depending on the policy group in ``lib/policy.py``.
>
> Please take a look at it and if you have any additional suggestions for the group, please drop a note.

The diff looks ok to me, I'll probably have a look at the running
system once there is a new -dev release.

I noticed in privacyidea/lib/policy.py line 1585 that you added three spaces:
[after "https:", after ".com/", and after "-templates"]

ACTION.POLICYTEMPLATEURL: {
                'type': 'str',
                'desc': _("The URL of a repository, where the policy "
                          "templates can be found.  (Default "
                          "https: //raw.githubusercontent.com/ privacyidea/"
                          "policy-templates /master/templates/)")
},

Jochen

-- 
The only problem with troubleshooting is that the trouble shoots back.

**Comment by cornelinux** [comment]
Yes. The URL will not break in the policy view. This leads to an ugly broken layout...

**Comment by jh23453** [comment]
Hallo Cornelius,

Cornelius Kölbel <notifications@github.com> writes:

> I implemented accordions which are created depending on the policy group in ``lib/policy.py``.
>
> Please take a look at it and if you have any additional suggestions for the group, please drop a note.

Sieht gut aus :-)

Jochen
