### ISSUE TITLE
Token serial collision with growth of token table

### ISSUE THREAD

**Issue by salvorapi** [privacyidea/privacyidea#583]
# Versions
privacyIDEA: 2.14-1trusty
Installation method: Ubuntu
OS: Ubuntu
Tokendatabase: MySQL

# Problem

In lib/token.py there is the function `gen_serial` that generate the new serial number .
The method for build the serial is based on formula:

_<token_prefix><total_token_count><random_substring>_

with 

_random_substring= random_hex_string[0:len(total_token_count) - 8]_

But, when token table growth from 1k, 10k, 100k the probability of token collision increase and multiple request (5-10 user in the same time) of new token collide.

Moreover, if you reach the number of 1M of token it's possible to create only one token for request (no parallel create).

# Question

The length of random string or the total length of serial can be included in global config?

Thank you.

Salvo.

**Comment by cornelinux** [comment]
Hi Salvo,
how many users and tokens are you running? Did you experience the problem? 
Since there should also be a function, that checks, if this "randomly" created serial number already exists. This is already contained in the gen_serial function:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L825

**Comment by cornelinux** [comment]
OK, do you have some suggestions?

**Comment by salvorapi** [comment]
I propose to use a configuration for choose what kind of function use to generate serial numbers.
Default remain the current function.
Another method to generate token can be a time-based function like do the unix `date +%s`  command.

Salvo.

**Comment by cornelinux** [comment]
We could also add the threadid to the serial number.
This way different (concurrent) threads wound collide.
