### ISSUE TITLE
Group mapping for SQL resolver?

### ISSUE THREAD

**Issue by andyboeh** [privacyidea/privacyidea#584]
I'm using privacyidea's SQL resolver to fetch user data from a SQL database. I would like to include group mapping in SAML auth responses, as it is already possible for LDAP (https://github.com/privacyidea/privacyidea/commit/d6fe070ca7aaf04263164fa1c35b1fc644749db5). Would it be possible to extend the SQL resolver with further variables like it was done for the LDAP resolver?

**Comment by andyboeh** [comment]
Sorry, this already works. The documentation was misleading as it gives LDAP as an example and then only talks about LDAP.
However, the simplesamlphp module does not support further attributes, I'll open an issue there.

**Comment by cornelinux** [comment]
It supports these additional attributes if you set the attribute mapping right.

**Comment by cornelinux** [comment]
You are welcome to open an issue to improve the documentation! ;-)
