### ISSUE TITLE
SQL Passwords should be stored in the same hashing algorithm as used before

### ISSUE THREAD

**Issue by andyboeh** [privacyidea/privacyidea#589]
Resetting the password for a SqlIdResolver always creates a SSHA256 hash, which breaks password compatibility. 

A possible solution would be to check the type of the existing password and create a similar hash. Alternatively, there could be a configuration option.

**Comment by cornelinux** [comment]
You are right. As a matter of fact setting the passwords was rather ment for smaller installations, where (SQL) users should be managed within privacyIDEA (and only privacyIDEA).
This is why at the moment it stores passwords in only this one way.

**Comment by cornelinux** [comment]
Ich changed the topic of this issue, so that it easier for me to recognize.

**Comment by cornelinux** [comment]
We added the possibility to specify in the resolver, using which hash algo the password should be stored.
Since I assume that one sql resolver connects to a table, which has all the same password hash types, the resolver can hold the hash type.
Thus we close this issue.
