### ISSUE TITLE
privacyIDEA installation with MariaDB: Wrong sequence number

### ISSUE THREAD

**Issue by splashx** [privacyidea/privacyidea#598]
# Versions

privacyIDEA: 2.17

Installation method:
- Ubuntu 

## more details: 

OS: Ubuntu Xenial

Webserver: Apache

Tokendatabase: MariaDB (`Server version: 10.1.20-MariaDB-1~xenial mariadb.org binary distribution`)

# What did you try to do?

Installed mariadb via apt-get in serverA.
Installed privacyidea-apache2 and administrarion tools, changed configuration file to use serverA as backend DB, created db and admin account (using pi-manage).
Accessed the privacyidea web interface with admin username and password.

# What outcome did you expect?

Sometimes it works without a problem, sometimes it works but it throws the following message on browser (red bubble):
```
2 (pymysql.err.InternalError) Packet sequence number wrong - got 0 expected 1 [SQL: u'SELECT resolver.id AS resolver_id, resolver.name AS resolver_name, resolver.rtype AS resolver_rtype, resolverconfig_1.id AS resolverconfig_1_id, resolverconfig_1.resolver_id AS resolverconfig_1_resolver_id, resolverconfig_1.`Key` AS `resolverconfig_1_Key`, resolverconfig_1.`Value` AS `resolverconfig_1_Value`, resolverconfig_1.`Type` AS `resolverconfig_1_Type`, resolverconfig_1.`Description` AS `resolverconfig_1_Description` \nFROM resolver LEFT OUTER JOIN resolverconfig AS resolverconfig_1 ON resolver.id = resolverconfig_1.resolver_id']
```

# What outcome did you experience?

Login without any error messages.

After googling around, I found:
https://github.com/PyMySQL/PyMySQL/issues/425
https://github.com/PyMySQL/PyMySQL/issues/422

all pointing to a possible implementation / library use issue.

**Comment by cornelinux** [comment]
You are talking of "serverA". Are you trying to do redundancy?
Ubuntu 14.04 or 16.04?
Which version of pymysql are you using?

(Besides, you could also always use the mysql driver)

**Comment by splashx** [comment]
Ubuntu Xenial, so 16.04.

We first found this problem while using a Galera MariaDB cluster.
To isolate the problem, we spawned one single MariaDB instance (apt-get install mariadb-server) - I just tagged it as serverA to illustrate privacyIDEA is not running in it - and a fresh install of privacyIDEA. 

In pi.cfg we use the MySQL driver (mysql://user:paswd@dbhost/db)

Meanwhile I'll tweak some DB settings and run some more tests

**Comment by splashx** [comment]
I believe it's related to this issue:
https://github.com/PyMySQL/PyMySQL/issues/526

Ubuntu Xenial ships with pymysql 0.7.2 - after `pip install` and running with 0.7.9 the issue hasn't shown up yet.

**Comment by cornelinux** [comment]
I adapted the topic of this issue, since there is no "default" about your setup - it might be a "standard" but no default. There are many enterprise customers running a redundant setup successfully. So I suspect that there is something wrong with your HA configuration. Providing consultancy, support or debugging for such setups is out of scope here.
However, if you manage to find any not yet know bug - I am really curious.

**Comment by splashx** [comment]
Again, there is no HA configuration here - I was able to reproduce it using 1 privacyidea server and 1 mariadb instance (no cluster). I also had a gut feeling this wasn't related to privacyIDEA but with the underlying libraries, so I'll close it for now - for others coming here, try upgrading to pymysql 0.7.9 (don't run it on ubuntu dist-version 0.7.2)

**Comment by cornelinux** [comment]
To my knowldedge the ubuntu packages run with the ``mysql`` driver. So it should be no issue at all. But thanks for pointing out the possible flaw in ``pymysql``.

**Comment by splashx** [comment]
No problem - I've edited and included the `pi.cfg` (no worries about the secrets, the machine doesn't even exist anymore)
