### ISSUE TITLE
DB connection on webGUI is not checked if active / timed out

### ISSUE THREAD

**Issue by splashx** [privacyidea/privacyidea#601]
# Versions

privacyIDEA: 2.17 @ Ubuntu Xenial installed via apt

## more details: 

OS: Ubuntu Xenial 

Webserver: Apache2

Tokendatabase: MariaDB (with default settings)

# What did you try to do?

Visit the web GUI, enter user name and password, log in, logout.
Don't close the browser/tab. 
Wait ~60s (because that's the `wait_timeout` set in the backend DB)
Enter username and password
Login

# What outcome did you expect?

The user should log in 

# What outcome did you experience?

privayIDEA GUI throws
![screen shot 2017-01-16 at 10 20 45](https://cloud.githubusercontent.com/assets/1154133/21977383/3b8dd774-dbd6-11e6-96ee-5b322f76e6d3.png)

# Log file [@gist](https://gist.githubusercontent.com/splashx/37d2cec6a330fc1a180f3c848a20a8a0/raw/e3fe6e7eeb8a80cf83049fa8f2460215b2b68f78/privacyidea-webgui-timeout)

Based on our tests, it appears the app assumes that if the GUI is available, the connection to DB is opened and alive. But that is only true when:
- The user visits the web GUI and clicks "Log In" within the `wait_timeout` time set in DB
OR
- If the web GUI is already loaded and displayed, the DB connection timed out BUT there was another visit in the webGUI in the mean time - by the same user in a different browser or not or a totally different user (this  triggers the DB connection to be reestablished - effectively renewing the DB connection)

As a quick workaround we have increased the `wait_timeout` value in the MariaDB side to several hours and the problem went away (that way we effectively increase the chances the DB connection will be up when a user has left the browser opened and will try to login several minutes after the webgui was loaded)

Ideally the app should check if the connection still lives (and reestablish if not) immediately after the user clicks "Log in"?

**Comment by cornelinux** [comment]
Please note that pymysql is not the default installation type with the xenial packages. Things may be different here.
Also you may know, that privacyIDEA uses the flask sqlalchemy package. Thus privacyIDEA does not control any DB session lifetime.
You may use the config parameters SQLALCHEMY_POOL_SIZE, SQLALCHEMY_POOL_TIMEOUT, 
SQLALCHEMY_POOL_RECYCLE to optimize database connection.
http://flask-sqlalchemy.pocoo.org/2.1/config/

**Comment by splashx** [comment]
> Please note that pymysql is not the default installation type with the xenial packages. Things may be different here.

I'm not sure what to read from this. What's the default installation "type" with xenial packages then? 
The environment where this issue popped was installed with:
```
apt-get install privacyideaadm \ 
python-privacyidea  \
privacyidea-apache2 \
privacyidea-radius
```

And:
```
# apt show -a python-privacyidea
Package: python-privacyidea
Version: 2.17-1xenial
Priority: optional
Section: python
Maintainer: Cornelius Kölbel <cornelius@privacyidea.org>
Installed-Size: 6,341 kB
Depends: python (>= 2.7) | python-argparse, python-alembic, python-bs4, python-cffi, 
python-configobj, python-crypto, python-docutils, python-ecdsa, python-flask, 
python-flask-migrate, python-flask-script, python-flask-sqlalchemy, python-funcparserlib, 
python-gnupg, python-itsdangerous, python-jinja2, python-jwt, python-ldap3, python-lxml, 
python-mako, python-markupsafe, python-netaddr, python-passlib, python-pil, 
python-pyasn1, python-pycparser, python-pygments, python-pymysql, python-pyrad, 
python-qrcode, python-requests, python-sqlalchemy, python-sqlsoup, python-usb, 
python-werkzeug, python-yaml, python:any (<< 2.8), python:any (>= 2.7.5-5~), 
python-pandas, python-matplotlib, python-openssl
```

There was no extra configuration to change the library to be used, so this is pretty much the default while using apt-get.

**Comment by splashx** [comment]
Update: after changing to `mysql+mysqldb://` the same problem occurs (with a different library reference of course):

![screen shot 2017-01-16 at 14 29 33](https://cloud.githubusercontent.com/assets/1154133/21984846/405354f6-dbf8-11e6-8f9f-b194e7f89317.png)

**Comment by cornelinux** [comment]
It might be since you are using mariadb instead of mysql-server and mariadb comes with other default settings the mysql-server.

The timeouts on server side and client side need to fit.

Please take a look at the above mentioned link to flask sqlalchemy.

With the mysql-server we have this experiences:

Set SQLALCHEMY_POOL_TIMEOUT (client side) to a lower value than wait_timeout on the server side.
SQLALCHEMY_POOL_RECYCLE can be set to wait_timeout/2.

You need to set these values in pi.cfg and restart apache2.
