### ISSUE TITLE
Using Event Handler with action "enroll" fails to set the user phone or email while initializing token

### ISSUE THREAD

**Issue by splashx** [privacyidea/privacyidea#603]
# Versions

privacyIDEA: 2.17

Installation method: Ubuntu 16.04 via apt

## more details: 

Webserver: apache2

Tokendatabase: MariaDB

# What did you try to do?

While testing ways to perform auto-enrollment of users via SMS, I've:
- configured a LDAP resolver for users (it works, as I'm able to see the user base when visiting "Users" in privacyIDEA). 
- privacyIDEA identifies and lists the following attributes "username, surname, givenname, email, phone, mobile"
- Since in the LDAP database there is no "phone" attribute - only mobile, the internal "phone" field for privacyidea was mapped to LDAP mobile attribute, using the following `Attribute Mapping` in the resolvers setup (note the mapping `"phone" : "mobile"`):
`{ "username": "uid", "phone" : "mobile", "mobile" : "mobile", "email" : "mail", "surname" : "sn", "givenname" : "givenName" }`
- Set up one `Policy` as follows:
```
scope: authentication	
action: { "passthru": "userstore", "otppin": "none", "smsautosend": true }
realm: my_realm
resolver: my_ldap_resolver
```
- Set up one `Event Handler` as follows:
```
Events: `[ "validate_check" ]`	
Handlermodule: `Token`	
Conditions: {"result_value":"True", "user_token_number":"0"}
Action: enroll	
Options: { "realm": "default", "tokentype": "sms", "user": "1" }
```

Then I issued:
https://privacyidea/validate/check?user=<userinLDAP>&pass=<password>

# What outcome did you expect?

I expected the SMS token to be created and after a second request, the token to be used.

# What outcome did you experience?

I've got the message: `ERR905: Missing parameter: 'phone'`

```
{
  "jsonrpc": "2.0",
  "signature": "......",
  "detail": null,
  "version": "privacyIDEA 2.17",
  "result": {
    "status": false,
    "error": {
      "message": "ERR905: Missing parameter: 'phone'",
      "code": 905
    }
  },
  "time": ....,
  "id": 1
}
```

When logging in as admin, I'm able to see the token **is** indeed created and **is** assigned to the user, however there is no phone number set. 
If I create the SMS token manually by letting privacyIDEA auto-populate the user field, the phone number gets populated automatically and the SMS token works.

I've also tried using SMTP Server, the message changes to `ERR905: Missing parameter: 'email'`

**Comment by cornelinux** [comment]
Please note your wording which make this sound like a bug.
Maybe you should first ask how things work. 
The event handler does not "fail" to set the phone number. This feature is simply not supported.
Thank you.

**Comment by splashx** [comment]
I've changed the wording and added a question at the bottom. 
However because the way things behaved it indeed looked like a bug - sorry for jumping the horses then.

It is however not clear how one could benefit from this **action** at this stage (creating a SMS token with missing properties?) so I suggest adding the current behavior to the docs (I can submit a MR later)? and add the expected behavior as a feature for upcoming releases maybe?

**Comment by cornelinux** [comment]
Different token types need different parameters to be created. You are right. Thus not all tokentypes can be created in the event handler. ...maybe never due to parameters.

But please file an issue as feature request and also explain your scenario! I am always very eager to get scenarios, because:

1. either the scenario can be covered in a different way or
2. several scenarios can sum up to a more generic feature. (guess how the event handler came to life) ;-)

And of course: You are also free to issue a pull request.

You may see recent heavy discussions and activities here. These are either contributing members of the community or paying customers.

I am sorry for again pointing out, that this is no support cahnnel.

**Comment by splashx** [comment]
> Different token types need different parameters to be created. You are right. Thus not all tokentypes can be created in the event handler. ...maybe never due to parameters.

After you mentioned it's not supported (which I wrongly assumed it was) I dug up the code and [noticed](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/eventhandler/tokenhandler.py#L262-L265) params are not there. 

To be honest I don't actually understand why the params are not populated (not technically speaking, but logically): if something like this is created:
![screen shot 2017-01-18 at 15 58 03](https://cloud.githubusercontent.com/assets/1154133/22068956/f6b1d548-dd96-11e6-9d52-b4060e7b4ea7.png)

in the current version this will always throw an `ERR905: Missing parameter: 'phone'`. Maybe the option `Assign token to user in request or tokenowner.` should be grayed out or rephrased?

Currently automatic enroll of `sms` or `email` tokens works at some extend - token is assigned to the user but the token can't be used.
Technically:
1.  it's missing a lookup method of user properties (phone, mail) based on token type (currently supported types in`init` is `sms` and `email`, so a switch block should do?).
1. issue [token update](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/smstoken.py#L228) with parameters from step 1

> And of course: You are also free to issue a pull request.

I will work on some code and PR

> I am sorry for again pointing out, that this is no support cahnnel.

I completely understand that - I limit myself to open issues here only if I think it's a bug or a feature request. 
The scenario is actually not new - to some extend it reflects #391. 

Best regards

**Comment by cornelinux** [comment]
Please explain your scenario!
Thanks a lot

**Comment by splashx** [comment]
Sure.

The scenario:
*  Users already exists in the userstore
*  In the userstore, *all* users have a mobile number registered
 * They know their username and password (it was delivered to them via email / SMS by some system in the past)
* Users should have only TOTP (for daily operations)
* privacyIDEA has read-only access to this userstore, ergo it can authenticate the user 
* privacyIDEA sits behind a VPN concentrator, in a internal network
* The user sits in front of the VPN concentrator, e.g. the internet
* The VPN server is configured to use privacyIDEA (via RADIUS) - 2FA requirement
* The privacyIDEA configuration for the VPN concentrator requires 2fa (no passthru allowed)
* SMS token is allowed only for the first-time vpn authentication, first-time privacyIDEA authentication

Those above are given (hard-requirements).

"Expected" flow for when user has no token at all:

1. User attempts to authenticate against the VPN concentrator, entering only username and password
1. VPN concentrator forwards the authentication via RADIUS to privacyIDEA
1. privacyIDEA validates username/password; if successful 
1. privacyIDEA checks if the user has tokens enrolled
1. if not,
   1. enroll token to user 
   1. assign the SMS token to user 
   1. sends an OTP code
1. User tries again the authentication now entering username and otp (or password+otp, details)
1. User successful authenticates against VPN
1. User visits privacyIDEA webGUI
1. User enters username and password
1. User receives OTP via SMS (using the above created token)
1. privacyIDEA prompts user to enter OTP
1. Use enters otp code into privacyIDEA wegui login page
1. User is authenticated and can enroll TOTP


I was able to replicate it all, except that 5.ii  had to be done manually (because of the `ERR905: Missing parameter: 'phone'` issue)
Everything else works.

**Comment by cornelinux** [comment]
I think your workflow design is to complicated. You should consider using the ``registration`` token and also to run some cronjobs.

In your workflow the user has to authenticate
1. only with password
2. then with password and SMS
3. then with password and code from app.

In most cases the user might not like this.

If you are interested in a smoother enrollment process, please drop me a note to my email address.
