### ISSUE TITLE
Separated privacyIDEA UI

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#605]
# Requirement

Install privacyIDEA UI Part. This server does not have a database connection and does not process requests. In just provides the UI. The system forwards the requests to a backend privacyIDEA system.

# Abstract idea

We avoid implementing an extra UI system. privacyIDEA can be installed in a normal way. It can be configured to only work as UI and forward requests to a full blown privacyIDEA.

# Possible design

We could use this: http://flask.pocoo.org/docs/0.12/api/#flask.Flask.before_request

If ``before_request`` returns anything else than *None*, the request handling is directly returned.
This way we can skip the complete processing in this flask app.

In a ``before_request`` we can issue a request to the backend system. 
We need to forward the parameters and also headers from the ``request.environ`` like the ``HTTP_PI_AUTHORIZATION``.

We probably should also forward a ``client`` parameter.

The backend system can process the request and returns the JSON result to the UI system. The UI system has to pass this response directly to the requesting client.

#2725

**Comment by foot3print** [comment]
Aha! My colleague just asked me about this. The backend Privacyidea System can be isolated from the UI Server! This will be a great as I need this requirement for our infrastructure. Users will then be able to access the UI on a public machine and forward requests to the more secured Console only machine.

**Comment by darthmdh** [comment]
Would you extend this to say you could, in the UI, select a backend instance and hence have just one UI to manage multiple privacyidea backends?  You could use something like protocolbuffers to transmit data securely between the UI and the backend.

**Comment by cornelinux** [comment]
# Idea of separated UI

The idea of separating the UI is to improve security. The privacyIDEA server with the database can be located in a secured network segement. The UI can be accassable from an untrusted network (a.k.a. "the internet).

The UI will only provide limited functionalites. Thus it will be less vulnarable to possible bugs or misconfigured policies.

In addition a web application firewall can be located between the UI and the privacyIDEA server and thus control on HTTP level allowed requests.

# multiple UIs

You could however again run several UIs on one machine/IP, by putting the UIs in sub-paths just like you can do with privacyIDEA.

@darthmdh  But I wonder what your scenario is? At the moment I think this will be no "management console" to manage a farm of privacyIDEA servers...?

**Comment by cornelinux** [comment]
You may want to take a look at #711. 
http://privacyidea.readthedocs.io/en/latest/eventhandler/federationhandler.html

This could also be a start for this, we would only have to forward the authorization header for other calls than ``/validate/check``.

Then we would have the same effect: A perimeter privacyIDEA machine, that holds no actual token or user data. It would only have the *federation* event handler. Requests would be forwarded to the internal privacyIDEA machine. A web application firewall could do additional traffic control between the perimenter and the internal machine.

**Comment by darthmdh** [comment]
@cornelinux ah nice, #711  is exactly where my thoughts were headed.  Thanks again!

**Comment by cornelinux** [comment]
First simple step is to be able to provide a different [index.html](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/webui/login.py#L186).
This could pull up complete different templates and javascript framework.

The index.html could be configured in ``pi.cfg``.
