### ISSUE TITLE
[feature] pi-manage policy create from file 

### ISSUE THREAD

**Issue by splashx** [privacyidea/privacyidea#612]
This is not a bug but a feature request.

As pi-manage support creating resolvers from file, it would be interesting to support creating policies from file.

Design:
- The same json format sent via API, but in a file

The user issues:
`pi-manage policy create <policy_name> <filename>"

The filename should be a valid json file and could should like this:
```
{
  "action": [
    "emailtext=This is a test"
  ],
  "scope": "authentication",
  "realm": [
    "localsql"
  ],
  "resolver": [
    "localusers"
  ],
  "user": "",
  "active": true,
  "check_all_resolvers": false,
  "client": "",
  "time": "",
  "adminrealm": []
}
```

# Versions

privacyIDEA: 2.17

# Suggestion

`./pi-manage policy create_from_file policy1test /my_policy_dir/policy1test.json`

# Expect:

Creation of a policy containing the settings from policy.test

I've already implemented it and I'll submit a PR for evaluation.

**Comment by cornelinux** [comment]
Good idea. You handled this in pull request #613 
Please see my comments there.

**Comment by cornelinux** [comment]
This was closed in this merge
https://github.com/privacyidea/privacyidea/commit/5eb00c0cf13962ab25fbab98c92ee180f47eb4ed
