### ISSUE TITLE
privacyIDEA Smartphone App

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#627]
See the wiki for more details.
https://github.com/privacyidea/privacyidea/wiki/concept:-SmartphoneApp
Comments are welcome.

**Comment by eheydrick** [comment]
👍 Would be great to have Google Prompt style push buttons in the app.

**Comment by cornelinux** [comment]
> Would be great to have Google Prompt style push buttons in the app.

What is Google Prompt style push buttons?

**Comment by eheydrick** [comment]
https://gsuiteupdates.googleblog.com/2016/06/new-settings-for-2-step-verification.html. Alternative to TOTP or tokens to login to Google.

**Comment by cornelinux** [comment]
OK. Easy. Something like TiQR but only is the auth request pushed to the phone. I understand. Thanks for the input.

**Comment by cornelinux** [comment]
I added the API specification for enrollment in the Wiki.
https://github.com/privacyidea/privacyidea/wiki/concept:-SmartphoneApp#api-specification

**Comment by cornelinux** [comment]
At the moment I am not sure, if and how we should define a token type to be allowed to use the *2stepinit* rollout.

At the moment the nice thing is, that the base tokenclass implements this behaviour for "all" tokens (Especially HOTP, TOTP). If we set a attribute of the tokenclass, should the base tokenclass NOT be allowed to do this? Then we can not test easily.
If the base tokenclass IS allowed to do so, we would have to *disallow* certain inherited tokenclasses explicitly.

**Comment by cornelinux** [comment]
**TODO**: Add top level documentation for the API.
