### ISSUE TITLE
Token Assignment Date, First use and Last Use Dates

### ISSUE THREAD

**Issue by sam-axiadids** [privacyidea/privacyidea#628]
Hi Cornelius, this is an enhancement request.

For reporting purposes we would like to be able to pull from the privacyidea database a status of all tokens, who each token is assigned to and especially when it was assigned/enrolled, and when/if it was first and last used.

Since Audit events don't provide a a good point in time reporting status we would like to have this information in the DB so that we without having to do lookups or correlations with audit events and require the whole history to get an accurate report.

What do you think of adding key date information in a database on a per token basis?

For example:
- Enrollment Date
- First successful use Date 
- Last successful use Date

As always we are happy to take a stab at this and submit a pull request.
Thanks

**Comment by cornelinux** [comment]
Hi Sam,

the tokeninfo is probably a good place for this. The Token Base Class has a method ``add_tokeninfo`` to add such stuff.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokenclass.py#L268

The last authentication is already added in the key ``last_auth``.

    last_auth: 2017-02-17 08:29:38.540988

We could also add a tokeninfo ``first_auth``. Check if it does not exist, if not, set it.

Also an ``enrollment_date`` could be added. The enrollment_date could be added, each time the *token/init* is performed.

**Comment by cornelinux** [comment]
Hm, I just realized I do not want to implement this! ...this way.

We are almost there using the token event handler. You can in fact use the token event handler to set the ``tokeninfo`` with any key. E.g. like ``first_auth``. Only problem is, at the moment we can only set fixed values. Easy solution would be to allow setting of a time stamp or other valies like:

   {{timestamp}}
   {{current_date}}
   {{user}}

Then you can define a handler:

* tokenhandler, 
   * event: validate_check, 
   * condition: count_auth < 1,
   * action: set_tokeninfo, key=first_auth, value={{current_time}}.

to set the first_auth attribute of the token.

And to set the ``enrollment_date`` do

* tokenhandler
   * event: token_init
   * condition ./.
   * action: set_tokeninfo, key=enrollment_date, value={{current_time}}

Oh, I like this so much! :-)
