### ISSUE TITLE
Token Type is not available for Logging/Auditing for Assignment events

### ISSUE THREAD

**Issue by sam-axiadids** [privacyidea/privacyidea#629]
Hi Cornelius, another enhancement request.

Audit events don't seem to have the token type attribute populated when tokens are assigned. This is an information we would like to have in our audit logs. 

Was there a good reason for not having it? What do you think adding it?

Thanks

**Comment by cornelinux** [comment]
No there is not.
Hm, the tokentype might often not be logged. The best place to add it is here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/before_after.py#L124
Get the type for the serial (Which will cause a DB request!) 

and add the type to the log:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/before_after.py#L137

**Comment by cornelinux** [comment]
We add this conditionally to ``before_after``.
Thus the tokentype will always be added if a "serial" is contained in the request.

Please check, if this works our for you.
