### ISSUE TITLE
Installation error on CentOS

### ISSUE THREAD

**Issue by lidfgab** [privacyidea/privacyidea#635]
I'm trying to install  privacyidea on centos 1503 and 1611, strict following the Centos guide on the  privacyidea website
I got the below error when pip install -r requirements.txt

Downloading/unpacking Werkzeug==0.10.4 (from -r requirements.txt (line 70))
  Downloading Werkzeug-0.10.4.tar.gz (1.1MB): 1.1MB downloaded
  Running setup.py egg_info for package Werkzeug

    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes'
    warning: no previously-included files matching '*.py[cdo]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking cryptography>=1.3.4 (from pyOpenSSL==16.1.0->-r requirements.txt (line 47))
  Downloading cryptography-1.7.2.tar.gz (420kB): 420kB downloaded
  Running setup.py egg_info for package cryptography

    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking setuptools>=11.3 (from cryptography>=1.3.4->pyOpenSSL==16.1.0->-r requirements.txt (line 47))
  Downloading setuptools-34.2.0.zip (621kB): 621kB downloaded
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /opt/privacyIDEA/build/setuptools
Traceback (most recent call last):
  File "/opt/privacyIDEA/bin/pip", line 9, in <module>
    load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
  File "/opt/privacyIDEA/lib/python2.7/site-packages/pip/__init__.py", line 148, in main
    return command.main(args[1:], options)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/pip/basecommand.py", line 169, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
(privacyIDEA)[root@svlvotpssp0037 privacyIDEA]#

can you tell me how can I solve this?

**Comment by cornelinux** [comment]
This is something I stumbled upon today, also!
I think this is due to old AGE of the pip version on CentOS.
You could update pip, but I am not sure, yet, about the side effects.

Before running pip install requirements or privacyidea run:

    pip install six
    pip install packaging
    pip install appdirs

**Comment by lidfgab** [comment]
Hi，
after add the three packages, I got the follow error:

Downloading/unpacking Werkzeug==0.10.4 (from -r requirements.txt (line 70))
  Downloading Werkzeug-0.10.4.tar.gz (1.1MB): 1.1MB downloaded
  Running setup.py egg_info for package Werkzeug
    
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes'
    warning: no previously-included files matching '*.py[cdo]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking cryptography>=1.3.4 (from pyOpenSSL==16.1.0->-r requirements.txt (line 47))
  Downloading cryptography-1.7.2.tar.gz (420kB): 420kB downloaded
  Running setup.py egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking setuptools>=11.3 (from cryptography>=1.3.4->pyOpenSSL==16.1.0->-r requirements.txt (line 47))
  Downloading setuptools-34.3.1.zip (622kB): 622kB downloaded
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /opt/privacyIDEA/build/setuptools
Traceback (most recent call last):
  File "/opt/privacyIDEA/bin/pip", line 9, in <module>
    load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
  File "/opt/privacyIDEA/lib/python2.7/site-packages/pip/__init__.py", line 148, in main
    return command.main(args[1:], options)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/pip/basecommand.py", line 169, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)

**Comment by lidfgab** [comment]
Hi cornelinux,
The problem in my last comment may cause by network problem, after many times retry, the problem resloved

**Comment by lidfgab** [comment]
One more question,
I want to input  tokenissuer in Chinese, but after I save the policy, the character will be ??，does your program support utf8? or I just need to make the database support utf8?

**Comment by cornelinux** [comment]
Could you please open a new issue and elaborate on your last comment?
Thanks!
