### ISSUE TITLE
LDAP/TLS: default to verify TLS certificates against CA

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#639]
Hello,

when testing 2.18dev3 I thought about the following possible changes to the LDAP resolver:

1. When adding an LDAP resolver with an ldaps:-URI we probably should default to "verify TLS".
At least would it would require an admin action to get less secure connects.

2. When I understand ldap documentation at http://ldap3.readthedocs.io/ssltls.html correctly, 
we could get away without a ca.crt file and use the system cert store:

```
When defining the Tls object you have the following additional parameters available:

    ca_cert_file: the usual link to the certification authority chain of certificates
    ca_cert_path: a link to a path containing the certification authorities certificates (reashed, as expected by OpenSSL)
    ca_cert_data: CA certificate data stored in memory

if you leave all these parameter to None the SSLContext will use the system wide certificate store (ssl path on linux, CA stores on Windows)
```
My server has the required ca certs in the system store, so cert verification would "just work".

3. When using an ldap: URI, can we check, whether the server supports STARTTLS and default to yes if it does? 

4. If we use STARTTLS, we should also default to "verify TLS".

What do you think?

**Comment by cornelinux** [comment]
# Default verify TLS

I would agree to default to verify TLS, so that the admin has to unselect it.
At the moment the default behaviour provides better update compatibility. So for me at the moment it is more important that installations, which simply update keep on working without admin interference and will not run into ldap errors.

But we could change the default setting for new resolvers in the next version (> 2.18)

# System Cert Store

There was something odd with the system cert store. I do not remember the reason...
In the past my experiences with the system certstore with ``python-ldap`` where not that positive. Maybe ``ldap3`` does it better.

Plus: I thought it more convenient for the administrator to name a CA cert or a cert bundle than think about where the system cert store is located, which varies a bit between distributions.

Anyway: If you want to follow the system cert store idea, we should create a second issue, to keep the *default* *settings* and the *cert* *store* in different issues.

**Comment by jh23453** [comment]
Cornelius Kölbel <notifications@github.com> writes:

> # Default verify TLS
>
> I would agree to default to verify TLS, so that the admin has to unselect it.
> At the moment the default behaviour provides better update
> compatibility. So for me at the moment it is more important that
> installations, which simply update keep on working without admin
> interference and will not run into ldap errors.
>
> But we could change the default setting for new resolvers in the next version (> 2.18)

And let's document that the admin can/should check the resolver after
the upgrade to 2.18. e.g. in the NEWS.Debian file and in the upgrade
documentation/README.

> # System Cert Store
>
> There was something odd with the system cert store. I do not remember the reason...
> In the past my experiences with the system certstore with
> ``python-ldap`` where not that positive. Maybe ``ldap3`` does it
> better.
>
> Plus: I thought it more convenient for the administrator to name a CA
> cert or a cert bundle than think about where the system cert store is
> located, which varies a bit between distributions.

I'm in the process of moving from my old local CA to FreeIPA, so it is
useful to have both CA certs available and have the software use the
right one. Otherwise I have to change a server certificate and must also
change all connections to that server at the same time - quite hard :-)

> Anyway: If you want to follow the system cert store idea, we should
> create a second issue, to keep the *default* *settings* and the *cert*
> *store* in different issues.

Yes, I'll create a new issue.

Jochen

**Comment by cornelinux** [comment]
> I'm in the process of moving from my old local CA to FreeIPA, so it is
> useful to have both CA certs available and have the software use the
> right one. Otherwise I have to change a server certificate and must also
> change all connections to that server at the same time - quite hard :-)

At the moment you can also specify a cert bundle, containing *both* (or multiple) CA files!

**Comment by jh23453** [comment]
Ah, on Debian/Ubuntu /etc/ssl/certs/ca-certificates.crt is the cert bundle from
the system cert store. On RedHat/CentOS it seems to be /etc/ssl/certs/ca-bundle.crt.
I guess that would be a useful default.

At least on my system it validates both certificates from my old CA and FreeIPA's CA.

**Comment by cornelinux** [comment]
You see, so which default should we set? 

We might add a *helptext* with *onclick* which fills the input entry:

> Here you can enter the CA file or a CA bundle file, which contains the CA certificate, that signed the SSL certificate of the LDAP server. This could be something like "/etc/ssl/certs/ca-certificates.pem"(onclick) or "/etc/ssl/certs/ca-bundle.pem"(onclick).

This would work, but it is not a common UI design in privacyIDEA at the moment...

**Comment by jh23453** [comment]
Let's keep the issue to track the default change to "verfiy TLS cert".
