### ISSUE TITLE
UTF8 support

### ISSUE THREAD

**Issue by lidfgab** [privacyidea/privacyidea#645]
I install lastest privacyidea in CentOS 1611
to enable tokenissuer Field Chinese support, I create database using UTF8
echo 'create database privacyidea DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;' | mysql -u root -p
it seems everything working fine till now, but in privacyidea debug mode, I find the logs like this:
 /opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:235: SAWarning: Unicode type received non-unicode bind param value '__timestamp__'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))

Will this cause any problem?

**Comment by cornelinux** [comment]
It simply says, that the field in the database is a unicode field. But a non-unicode value is written to it.
It will not cause any problem.
