### ISSUE TITLE
tokenlabel Field  

### ISSUE THREAD

**Issue by lidfgab** [privacyidea/privacyidea#646]
Now I'm using tokenlabel Field like this: 
"tokenlabel": "\<u\>@\<r\>\<s\>" 
Is it possible to use Given Name and Family Name in this Field?

**Comment by cornelinux** [comment]
No, it is not possible.

**Comment by cornelinux** [comment]
we will add a string format mechanism.

You will be able to use {username}, {realm}, {serial}, {givenname} and {surname}
