### ISSUE TITLE
/validate/check should return XML

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#647]
All validate endpoints should be capable of returning XML.

this could be done by adding a parameter like

 return=XML

**Comment by sbidy** [comment]
The feature request can be put aside. 

A possible solution is to parse the json into a xml at the client side.

**Comment by cornelinux** [comment]
thx for the update.

**Comment by cornelinux** [comment]
This is not needed for the ADFS plugin anymore.
