### ISSUE TITLE
Challenge-response successful validation response takes wrong serial number

### ISSUE THREAD

**Issue by quynh-axiadids** [privacyidea/privacyidea#649]
# Versions

privacyIDEA: 2.17

Installation method:

- from source / github

## more details: 

OS: Amazon Linux

Webserver: nginx

Tokendatabase: PostgreSQL

======

Hi @cornelinux,

There seems to be a problem with the chosen token for a successful validation among the Challenge-Response tokens.

How to reproduced it:
1. Enroll more than 2 Challenge-Response token-type token for a user (for example, Email tokens A and B)
2. Send an Access-Request with PIN of token B
3. Receive a Access-Challenge with **"TrustedUser-OTP-Serial" is token B**, and a State
4. Send a Access-Request with the challenge string and the received State for token B
5. Receive a Access-Granted with **"TrustedUser-OTP-Serial" is token A** and the **audit log recorded token A** serial number for the /validate/check.

Please refer the log in the code block at the end of the comment, you can see that the serial number are different in the Access-Challenge, and the Access-Granted.

I think the reason is due to the way PrivacyIDEA handles challenge-response token list: it doe not pass along the serial number associated with the challenge transaction_id, but instead use the first challenge-response token in the found challenge-response token list for a user.

It is not critical and does not affect any functionality, but just gives a little misleading for the audit log. We should either give the correct serial number of the challenge transaction_id, or simply keep the serial number blank to avoid misleading.

```
[root@test]$ echo "User-Name=penny, User-Password=112233" | radclient -sx localhost auth testing123
Sent Access-Request Id 210 from 0.0.0.0:44306 to 127.0.0.1:1812 length 45
	User-Name = "penny"
	User-Password = "112233"
	Cleartext-Password = "112233"
Received Access-Challenge Id 210 from 127.0.0.1:1812 to 0.0.0.0:0 length 93
	Reply-Message = "Enter the OTP from the Email:"
	TrustedUser-OTP-Serial = "PIEM00015F6F"
	State = 0x3033363030313933363231363936393835313135
(0) -: Expected Access-Accept got Access-Challenge
Packet summary:
	Accepted      : 0
	Rejected      : 0
	Lost          : 0
	Passed filter : 0
	Failed filter : 1
[root@test]$ echo "User-Name=penny, User-Password=655321, State=0x3033363030313933363231363936393835313135" | radclient -sx localhost auth testing123
Sent Access-Request Id 7 from 0.0.0.0:56422 to 127.0.0.1:1812 length 67
	User-Name = "penny"
	User-Password = "655321"
	State = 0x3033363030313933363231363936393835313135
	Cleartext-Password = "655321"
Received Access-Accept Id 7 from 127.0.0.1:1812 to 0.0.0.0:0 length 56
	Reply-Message = "access granted"
	TrustedUser-OTP-Serial = "PIEM00007CE0"
Packet summary:
	Accepted      : 1
	Rejected      : 0
	Lost          : 0
	Passed filter : 1
	Failed filter : 0
```

**Comment by cornelinux** [comment]
The **state**/**transaction_id** is linked to the token/serial number. So it should find the correction token-serial in step 5.
Will look into this.

**Comment by cornelinux** [comment]
This is linked to #654. We will check and probably fix this when reworking this issue.

**Comment by cornelinux** [comment]
@sam-axiadids I assume token A and token B have different PINs?

I assume so - otherwise this would be covered by the test case in #654 

I will add a test case with two C/R tokens with different PINs.
