### ISSUE TITLE
EventHandler: Missing Attribute Error.

### ISSUE THREAD

**Issue by quoc-axiadids** [privacyidea/privacyidea#652]
Please think about and cover the following questions:

Versions

privacyIDEA: 2.18

Installation method:

from source / github
more details:

OS: Amazon Linux

Webserver:

Tokendatabase: PostgreSQL

====

Hi @cornelinux,

Related Issue: [628](https://github.com/privacyidea/privacyidea/issues/628)

We are in the progress of testing 2.18 migration.

We are currently attempting to handle token/init, to store enrollment_date information for a token in the tokeninfo table. However, we receive this error:

`packages/privacyidea/lib/event.py", line 81, in event_wrapper event_audit = getAudit(self.g.audit_object.config) AttributeError: 'Audit' object has no attribute 'config'`

I confirmed that the self.g.audit_object does not have the attribute config.

Here are the steps to reproduce:
1. Create eventhandler for token/init, with the following information:
- tokenhandler
  - event: token/init
  - condition: ./.
  - action: set_tokeninfo, key=enrollment_date, value={{current_time}}
2. Enroll a token

Afterwards, check the tokeninfo table in the database or the webui information regarding that token.

I am looking forward to your input.

Thank you.

**Comment by quynh-axiadids** [comment]
@quoc-axiadids  and @cornelinux,
Apparently, we are using our customized audit module and Audit object does not have config attribute.
The default sqlaudit module Audit object does have a config attribute.
We can close this ticket as it is obsolete.

Thank you.

**Comment by cornelinux** [comment]
Thanks @quoc-axiadids 
I leave it up to @quynh-axiadids to close the ticket.
