### ISSUE TITLE
Support for multiple C/R tokens with same PIN

### ISSUE THREAD

**Issue by sam-axiadids** [privacyidea/privacyidea#654]
We are hitting a PrivacyIDEA limitation where authentication doesn't work if a user has multiple ChallengeResponse based Tokens with the same PIN.

We believe the limitation is represented there:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L2089

A user can only have one such token (unless they have different PINs). 
For example if a user has multiple emails or sms tokens (with the same PIN) authentication will not work. 

As discussed by email this is tricky. We have some ideas on how to address this issue in different ways, but it will require core code changes. Before we take a stab at it I wanted to check with you if you had a recommendation on how you would like to see this addressed or if there is an easier way to deal with this.

Thanks!

**Comment by cornelinux** [comment]
Some first thoughs to work on.

# Triggering Authentication

Triggering authentication means that the user has proven to have the first factor - knows the password. In this case we probably only should return *one* transaction_id, which could act as the handle "hey the user already sent his password".

The challenge table could somehow store this transaction_id and - in contrast to now - the list of tokens, for which the first authentication step worked.

# Email and SMS

## Sending first response

The first response would only contain **one** transaction_id, which makes it simpler for the authenticating application to perform the second step.

If there is more than one token (Email and/or SMS) triggered: privacyIDEA could send all matching emails and all matching SMS. privacyIDEA would have to remember the transaction_id in conjunction with all matching serial numbers of the triggered tokens.

privacyIDEA's first response would contain the single *transaction_id* and...
...the challenge messages. Well, each of the triggered tokens would create a different challenge message like
* "Email sent succesfully"
* "Please check your phone for SMS"
But after all, the action the user has to take, is the same: Grabbing a device, reading the sent OTP value and entering it in the second dialog.

So we could compile a list challenge messages, or we could create a new message like
"check any of your devices...".

In fact even the application could decide, what to display to the user.

## Sending 2nd response

The user could return any OTP value from an SMS, Email and privacyIDEA would check the challenges-table with the *transaction_id*, get a list of tokens and check these tokens, which one created the OTP value.

# TiQR or any cryptographic token

If a cryptographic challenge response token is involved, things get more complicated. The challenge will be a cryprographic challenge and some component needs to decide, what to do, like: the application needs to decide, which challenge to display. 

What about combinations of crypto C/R and Email/SMS...

**TODO**

**Comment by sam-axiadids** [comment]
Thank Cornelius for looking in this this!

I think this is going in the right direction. 

I didn't think indeed that there could be different type of messages to be returned for multiple type of C/R devices. It might make sense to have a default configuration message when more than one C/R device type is involved as you proposed.

The one thing that I'm less sure about in the proposed design is splitting /validate/check into two separate calls /validate/triggerchallenge and /validate/check. (unless I missed something?)

Doing 2 calls to /validate/check (the second with transaction_id) as we are doing today seems to make more sense to us, requires less changes and already works with Radius and common radius clients (SSH / PAM for example - including in Challenge Response mode)

The rest of the design makes sense. 
Let us know how you would like to proceed next and if we can help. 

Thanks,

**Comment by cornelinux** [comment]
Hi Sam,
No problem.
There are two ways for challenge/response:

1. trigger challenge via ``/validate/check`` with pin a.k.a. password and then sending the response with ``/validate/check`` and the response. This is the old way as it used to be it will sill be available.

2. In one of the later version the ``/validate/triggerchallenge`` was added, if the application does ask the user for a PIN a.k.a. password. This is an alternative, administrative way to trigger the challenge. The response will be sent via ``/validate/check``.

So there is sill way **1** which you are used too.

**Comment by sam-axiadids** [comment]
Great! Sorry I didn't realize that. Then we are good with the proposal! 
Thanks

**Comment by sam-axiadids** [comment]
Hi Cornelius & team do we have an estimate on when this could be implemented? 

I'm happy to have someone in my team work on it if you want to provide some guidance on how you would prefer it to be addressed. Thanks

**Comment by cornelinux** [comment]
Hi Sam. It is part of release 2.19 which is scheduled for May 25th.
I think we will start working on it next week or the week after. 
We can start with some details on the Spec/API and list the places to modify.

**Comment by cornelinux** [comment]
# Implementation

## Database

The ``transaction_id`` proves, that the user has sent the correct first factor. One ``transaction_id`` can belong to several challenges during one authentication process.

We could have two tables with transaction_ids and challenges. But this seems to complicated and not necessary.
We can simply remove the *unique* flag from the ``transaction_id`` and thus store  several entries in the table ``challenge`` like:

transaction ID | challenge | serial 
-------------------|---------------|--------
transaction_id_A | challenge 1 |  serial 1
transaction_id_A | challenge 2 | serial 2
transaction_id_A | challenge 3 | serial 3

This way the authentication process "A" creates one transaction ID but several entries and challenges. One per token that matches.
