### ISSUE TITLE
Reduce number of LDAP connections per authentication request

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#664]
Let's assume privacyIDEA is configured with a LDAP user resolver and a ``otppin=userstore`` policy. When processing an incoming authentication request, privacyIDEA then establishes several connections to the LDAP backend. We can check this if we [configure logging for the ldap3 module](https://gist.github.com/fredreichbier/2ce6e3278ccdfcf5fbe4e1b5ef7cf414) and send one request to `/validate/check`:
<pre>
$ grep "start BIND operation" privacyidea.log
2017-03-23 13:11:25,398 DEBUG BASIC:start BIND operation via <...>
2017-03-23 13:11:26,073 DEBUG BASIC:start BIND operation via <...>
2017-03-23 13:11:26,740 DEBUG BASIC:start BIND operation via <...>
2017-03-23 13:11:27,065 DEBUG BASIC:start BIND operation via <...></pre>

The first three connections use the service account credentials, the last one uses the credentials of the authentication request.

The LDAP ID resolver caches the user information for ``CACHE_TIMEOUT`` seconds, i.e. authentication requests of the same user during that timeframe only trigger *one* LDAP connection (using the user credentials).

Nevertheless, we can try to minimize the number of LDAP connections. This could be done, e.g., by instantiating the LDAP ID resolver only once per request.

**Comment by cornelinux** [comment]
Hi @fredreichbier 
we closed #655 and merge #669. Do we still need to go further?
(We might need an issue for user caching. But we should open a new one).
I would suggest to close this one.

**Comment by fredreichbier** [comment]
Sounds good to me!
