### ISSUE TITLE
Evaluate zapier

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#673]
For external automation we could add zapier.com to our event handler framework.

**Comment by chris001** [comment]
Zapier.com is a paid service to sync data between two business apps using their REST interfaces.  Wouldn't external automation simply involve having PI expose a public REST interface?

**Comment by cornelinux** [comment]
Hi @chris001, Usually privacyIDEA is run on premise in the backend and not exposed to the internet.
This is why I would rather use an zapier API to trigger actions on other services - to my understanding.

E.g. in privacyIDEA an authentication device is enrolled to a user. And than something else would be triggered by some external service. I think, by using zapier, it might be easier to address a lot of different services?

**Comment by chris001** [comment]
You mean PI would generate an event any time something happens in its database, and transmit that event to anywhere as a notification or whatever.  I'd be concerned about security, what if the traffic with zapier.com is eavesdropped by unfriendly actors?  It probably is indeed wiretapped because they are a hub for so much sensitive data traffic.

**Comment by cornelinux** [comment]
I do not understand your concern. Can you elaborate on this? May be we do not know our each other's systems well enough.

**Comment by cornelinux** [comment]
privacyIDEA can trigger actions in case of certain events. The administrator can define, which actions to trigger based on which conditions in case of which event.

E.g. there are user notifications, that a user or an administrator will be notified by privacyIDEA. E.g. if the administrator performed a certain action on the user object, the user will be notified. This notification does not contain any "sensible" information.

I have not seen the zapier API, but now I was thinking, that we could perform certain calls to the zapier API to trigger any action on a registered Applicatoin. Of course privacyIDEA would authenticate to the zapier API with a certain account and credential. But then it could have zapier contact e.g. Twitter, to send a certain tweet or dropbox to upload a file to dropbox.

Is this, how the zapier API works? I would expect so.
Can you point me to the right documentation?

**Comment by chris001** [comment]
That's about right.  https://zapier.com/developer/documentation/v2/

I'd say look also at Talend - it's open source and a free community version is available - fully java based and integrates with almost everything.

Trying to think of scenarios where OTP type notifications would need to be transmitted outside of the PI server.  Maybe to a network operations management dashboard, which would be a view of a database of notifications received.

Why would it send notification to twitter? "@PrivacyIDEA would like to publicly thank @ JoeSmith for logging into his account on the Springfield Urology Clinic, using a secure One Time Password. Your test results are secure!"
