### ISSUE TITLE
Latency for Flask Endpoints

### ISSUE THREAD

**Issue by quoc-axiadids** [privacyidea/privacyidea#674]
Please think about and cover the following questions:

# Versions
privacyIDEA: 2.18
Installation method:
- from source / github ?
## more details: 
OS: Amazon Linux
Webserver: uwsgi/nginx
Tokendatabase: PostgreSQL

Hello Cornelius,

We are noticing latency when there is a large amount of tokens in the database. I believe it is a long runtime when getting the tokentype for auditing events. Some events have the serial number as **, and the logic to get the tokentype runs too long.

https://github.com/privacyidea/privacyidea/blob/branch-2.18/privacyidea/api/before_after.py#L127

The following function call contains two timely for-loops in the event of large amounts of tokens in the database.
- Query all tokens in the database to create token instances
  - https://github.com/privacyidea/privacyidea/blob/branch-2.18/privacyidea/lib/token.py#L327
- Getting the tokentype of the last token object
  - https://github.com/privacyidea/privacyidea/blob/branch-2.18/privacyidea/lib/token.py#L448

The following line create a SQL Query of the Token database, and loops through all the serial numbers create token objects. Once the token objects are created, another loop initiates to go through all the tokens and get the last objects tokentype.

Here are some results of time taken to load  I did.
3,000  tokens => 8-9s
5,000  tokens => 12-14s
10,000 tokens => 30-34s

I replaced the function call with a string for to observe the performance and loading the token/list took less then 2s for 10 tokens.
`tokentype = 'hotp'`

I am looking forward to your input.

Thank you.

**Comment by quoc-axiadids** [comment]
A cleaner fix I have for this issue is change the if-condition

`if serial or serial != '**':`

or if the serial does not need to be "**", then we can check the value before the if-condition:

`serial = None if "**" in serial else getParam(request.all_data, "serial")`

**Comment by cornelinux** [comment]
This sounds good to me. Thanks a lot for pointing this out. The "**" comes from the audit log or searches for tokens.

    if serial and not (serial.startswith("*") and serial.endswith("*"))

would make sense. But a search like "\*A\*" could in fact return one single token.

So I think your suggestion sounds very good. Would you commit a PR?
