### ISSUE TITLE
privacyIDEA should be able to run on python 3

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#676]
In regards to dependent packages, we might look at this.

https://medium.com/@anthonypjshaw/oh-no-this-package-is-python-2-only-8e6316f9a02

**Comment by fredreichbier** [comment]
Just read that the next RHEL major release [will deprecate Python 2](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.5_release_notes/chap-red_hat_enterprise_linux-7.5_release_notes-deprecated_functionality), also, Python 2.7 will go end-of-life in 2020. If we want to start looking into this: the above page links an [interesting porting guide](https://portingguide.readthedocs.io/en/latest/).

**Comment by plettich** [comment]
I started a [Wiki page](https://github.com/privacyidea/privacyidea/wiki/python3)

**Comment by plettich** [comment]
Further steps for making privacyIDEA compatible with Python 2 and Python 3
* [ ] migrate tests to Python 3
  * [ ] migrate database testcases
  * [ ] migrate crypo library testcases
  * [ ] migrate other lib-level testcases
  * [ ] migrate API testcases
* [ ] migrate tools and plugins
* [ ] refactor crypto interfaces
