### ISSUE TITLE
Clean up tokens, purge tokens

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#677]
Hello,

I wanted to ask for a long time, what do you think about “cleaning jobs” in PrivacyIdea.
The points are:

- at the moment there are no exact distinguish between hardware tokens and software tokens. The difference is – Hardware tokens you better **not delete**, because it’d be hard to recover. Software tokens  are like disposable, you may delete them as you are not need them anymore. The only way for now is to distinguish PI software tokens by SN pattern(OATH.*, TOTP.*)

- Old unassigned **software** tokens probably need to be removed from the system to “clean out the system”. Currently I’m doing this via my custom script manually once a few months. But maybe you had some thoughts on implementing such option either to web ui or pi-manage/privacyidea console programs

- Tokens which are assigned to dismissed employees(objectguid from database isn’t resolvable to username in LDAP) are also need to be unassigned. Hardware tokens then will be re-used and software ones then will be removed by something from point 2 above. This is also currently done by my script but this solution isn’t enterprise solution, I don’t really like it

These tasks would be wise to perform as cron jobs, but maybe also think about having them configured in web ui somewhere as a single entry point for policies configuration.

**Comment by cornelinux** [comment]
I think we need to identify conditions, when tokens should be deleted.

# Conditions

Possible conditions could be:

* Token was not used for a certain time. For this the token has the ``tokeninfo`` field ``last_auth``. 
* Token is not assigned?
* The user, to whom the token is assigned, does not exist. ("orphaned" tokens)
* Token failcounter exceeded?

# Actions

Possible actions could be:

* Delete the token (e.g. in case of software tokens)
* unassign the token (e.g. in case of hardware tokens)

# Thoughts

To me this reminds me of the token event handler. The difference is
* that we do not know, **what** should trigger the action and
* this has to be performed on all tokens.

Performing such tasks on all tokens (especially orphaned tokens) is very time consuming. In case of orphaned tokens we need to do an LDAP request for **every** assigned token, to determine, if the user still exists!

See orphaned tokens: 
https://github.com/privacyidea/privacyidea/blob/c0dfb3f99921dd9079c258d127543a3099f81c18/privacyidea/lib/eventhandler/base.py#L50

**Comment by cornelinux** [comment]
See https://github.com/privacyidea/privacyidea/blob/master/tools/privacyidea-get-unused-tokens

**Comment by cornelinux** [comment]
We will implement this as an extra script in the tools directory.  This way we have no performance impact.

Developing this script is independent from the normal release cycle.

**Comment by cornelinux** [comment]
> at the moment there are no exact distinguish between hardware tokens and software tokens. The difference is – Hardware tokens you better not delete, because it’d be hard to recover. Software tokens are like disposable, you may delete them as you are not need them anymore. The only way for now is to distinguish PI software tokens by SN pattern(OATH., TOTP.)

@kolosovski  You could use the event handle and set additional tokeinfo during enrollment. If you "know" that you enroll TOTP as software tokens, you could set the condition to type=TOTP and to a ``set tokeninfo`` ``key=hwtype``, ``value=soft`` and in case of enrolling yubikeys or importing key fobs ``key=hwtyp``, ``value=hard``.

**Comment by kolosovski** [comment]
Thank you for suggestion
