### ISSUE TITLE
REST-API: Filtering token description does not work

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#679]
# Versions

privacyIDEA: 2.18.1 and former versions

## more details: 

Tokendatabase: PostgreSQL

# What did you try to do?

Let's have a list with tokens in our token database. The token descriptions e.g. contain "YubiKey Token", "App Token", "Paper Token". 

Filter the token list by description e.g. for "YubiKey Token" or "yubikey" or "Token" or "token" via WebUI/REST-API.

# What outcome did you expect?

Only get tokens returned, that match the description filter, either case-sensitive, or even better, case-insensitive.

# What outcome did you experience?

If we filter the token list by description for "YubiKey Token" or "yubikey" or "Token" or "token" via WebUI/REST-API, all tokens are returned.

There seems to be a bug in the filter logic in

https://github.com/privacyidea/privacyidea/blob/639d36b86d29d6a500fb0cb650105938328356df/privacyidea/lib/token.py#L152-L161

possibly due to copy-and-pasting the preceding if-statement for tokentype filtering.

I'll submit a pull request in a few minutes.

**Comment by cornelinux** [comment]
Closed by your pull request. Thanks a lot! :1st_place_medal:
