### ISSUE TITLE
Feature request: Email OTP template

### ISSUE THREAD

**Issue by rthill** [privacyidea/privacyidea#684]
At the moment the email body send to the user is very limited, no multiline and no templates, just like for a text message where it is ok to have single line text. In email OTP messages I could imagine having multiline text as emailtext or even templates.

I have tried to break lines using \n and json list as emailtext: ["Test line 1", "Text line 2"]

**Comment by cornelinux** [comment]
You are right. This could be done similar to the ``notification handler``, where we can define the body and also the if it is *plain* or *html*.

# Problem A: Policy

The email text is part of a policy. The "action" in the policy do not allow such complicated configuration.
We *could* add email templates (in a database table) and then change the policy to select one of these templates.

The templates could contain:

* template subject
* template body
* (mailserver to use)
* plain/html

# Problem B: Security

I do not really encourage to send emails, as this is everything else than secure. 
So as I am not convinced by this concept, my personal prio is veeery low for this. ;-)
Nevertheless: I think *A* is a sensible approach.
But not till something increases my personal priority.

**Comment by klinux** [comment]
There any update about that feature?

**Comment by cornelinux** [comment]
No. Personal priority has not been increased, yet.
Maybe you can tell a bit more about your use case?
And why and what you want to send? (As you are not the original poster, you might shed some new light on this)

**Comment by klinux** [comment]
We need to format an email with the user's otp, today we only change
emailtext and subjecttext in the policy, but we cannot format the text, i
tried \n\r too, so, we can't format message body of email, only a single
line text.

A email template will be very important feature in my opinion of course :).

Att.
Kleber

2017-12-15 19:01 GMT-02:00 Cornelius Kölbel <notifications@github.com>:

**Comment by cornelinux** [comment]
Why do you need to? How should your email look like?

You can replace ``<otp>`` and ``<serial>``.

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/emailtoken.py#L363

**Comment by klinux** [comment]
We need format email that is send to user, like that:



*Hi,*


*Here is your otp code: 564458*
*Thank you*

That is impossible to break lines today, I know I can replace <otp>, but We
cannot break lines to format an email more legible!.

T

Att.
Kleber


2017-12-19 19:37 GMT-02:00 Cornelius Kölbel <notifications@github.com>:

**Comment by klinux** [comment]
We need format email that is send to user, like that: 

*Hi, 
Here is your otp code: 564458 
Thank you* 

That is impossible to break lines today, I know I can replace <otp>, but we cannot break lines to format an email more legible!. 

Today the email is sended in only one line, like that: *Hi Here is your otp code: 564458. Thank you* \

Att. Kleber

**Comment by rthill** [comment]
A simple template processor like Jinja2 would do the job. Users could
implement whatever text or html with as much information they want.
Personally, I would require to add a footer with legal information and
contact support phone and email address. Not sure if it could be possible
to greet like:

Dear <firstName> <lastName>,
...

Regards,
Raoul

**Comment by cornelinux** [comment]
I think we are getting closer here.

@rthill @klinux you told me that you need a template and that you need a template, because you need line breaks. But I still do not know, why you need line breaks. Why should your email look like:

<em>
Hi Raoul Hill,

your totally secure one time password, which was sent to you over an unencryted media, is:
123456

Disclaimer: Please do not print this email. Save the environment.
If this email was not ment for you - since you are the hacker -  please inform the sender and destroy this email!
</em>

I would like to understand your "why", so that I get an idea of the bigger picture. This might finally increase the priority of this. Well, there are also other ways to increase the priority.

>  Why do you need line breaks, html and a footer?

In regards to jinja: Yes there are a lot of possibilities to do templates. But as I pointed out initially the problem is that this is a simple policy, that does not allow such long texts. I.e. we would need to add extra data schema for templates and so on and so on. And currently the priority is to low, to justify the enhancement in the database schema.
As mentioned, priorities are volatile and can change one day.

Thanks a lot for any additional input.

**Comment by rthill** [comment]
I do not agree that it is sent over unencrypted media when using a known
infrastructure with TLS enabled.

BTW, I would need this as users are not as techie as we are. Having the
possibility to add additional text will help to guide people, especially
when switching to privacyIdea from an old legacy system or when
implementing new stuff. It will save us lots of training hours.

Raoul

**Comment by cornelinux** [comment]
Hi Roul,
thanks a lot. Makes perfectly sense.
Kind regards
Cornelius

**Comment by cornelinux** [comment]
https://www.youtube.com/watch?v=g8IVI0sZ6F8

After some internal discussion we might do it this way. 
In the action "emailtext" we could provide the URI to a local template file.
This way we keep this encapsulated in the email token code, to not mess with the policy structure and do not need to enhance the DB schema.

**Comment by rthill** [comment]
Thanks!

**Comment by klinux** [comment]
Thank you!!!

**Comment by cornelinux** [comment]
Hm. I do not know of any of this. We do not use the html email so excessively. At least not with CSS.
You should take a look at the source code of the email.

This might be more of a user problem / configuration issue. So you might consider posting this at https://community.privacyidea.org.

**Comment by fredreichbier** [comment]
A problem with inline CSS might be that we use Python ``{}`` format strings to fill in tags (like ``{otp}``), which clashes with CSS syntax like ``body { ... }``. You could try to work around that using double curly braces ``body {{ ... }}``.
