### ISSUE TITLE
Additional Options on Testing Resolvers

### ISSUE THREAD

**Issue by quoc-axiadids** [privacyidea/privacyidea#688]
Please think about and cover the following questions:

# Versions
privacyIDEA: 2.18
Installation method:
- from source / github ?
## more details: 
OS: Amazon Linux
Webserver: uwsgi/nginx
Tokendatabase: PostgreSQL

Hello Cornelius.

The current Test LDAP Resolver function will get every user within the directory. The test becomes slow when the directory has a large amount of users. An additional option would be to test the LDAP base on the size limit specified when configuring the LDAP resolver.

This could be an extra button side-by-side to test with size limit. This approach will clutter the button group.

Another approach is to have a checkbox/radio right under the "Size Limit" configuration in LDAP Resolver, that displays "Test with Size Limit". Then when an administrator or user clicks on the button, it will test based on the Size Limit. Untick the configuration and it will test the entire LDAP.

Let us know what you think about this approach.

**Comment by cornelinux** [comment]
Hi @quoc-axiadids 
I understand your need. If someone is not that familiar with LDAP he will need "some tests" to configure the system right and if he has to wait a few seconds after each button press this can be annoying.

I think adding another button is nevertheless better than adding a check box. A second button with the label "quick resolver test" is more intuitive. The old button could be "full resolver test".

The quick test could pass a sizelimit of 1, the full resolver test none.
The testconnection classmethod needs to use this passed sizelimit (it does not do this at the moment)

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/LDAPIdResolver.py#L785

**Comment by quoc-axiadids** [comment]
There is an issue we see when doing the full test on configuration.

The current test connection method does not use a size limit so it attempts to get the entire directory.

The browser client timeouts waiting for the response from testing the connection and displays ".. OTP Systems Unavailable. API Unreachable". I believe this is in the angular $http having a default timeout of 120 seconds.

If this is the reasons, then an approach could be to set a Promise to ensure that the "full resolver" test connection will ensure that a response is returned to the client.

**Comment by quoc-axiadids** [comment]
@cornelinux My apologizes, after some more testing with different sized directories. The issue is not with angular. It is actually due to the nginx waiting for a response from uwsgi and timing out..

**Comment by quoc-axiadids** [comment]
@cornelinux 

What do you think about having `ng-click="testResolver()` pass a value as a parameter either 0 for full resolver test, or 1 for single user test.
*0 will conduct a "full" test
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/config/views/config.resolvers.ldap.html#L265

Here we will capture the parameter and do something along the lines of:
`var params = $scope.params;`
`params.TESTSIZE = test_size;`
`ConfigFactory.testResolver(params, function (data) {`
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/config/views/config.resolvers.ldap.html#L265

Then in the backend we appropriately get the TESTSIZE from the params, and use that in the testconnection method.

OR

we could write another method for testResolver for the quick test, say "quickTestResolver()"?

**Comment by cornelinux** [comment]
I think adding parameter to ``testResolver`` sounds good.
If you add a "1" parameter to do a quick test, we could call testconnection with a sizelimit=1.

I would rather user params.SIZELIMIT than parameter params.TESTSIZE.

**Comment by quoc-axiadids** [comment]
@cornelinux 

Regarding the commit, so we are no longer allow a "Full" Test on the resolver? The original button will not use the specified size limit in the configurations.

**Comment by cornelinux** [comment]
? If I hit the originial button I get 3000 users. I.e. I get all users ("full").
Or maybe we have a misunderstanding here?

**Comment by quoc-axiadids** [comment]
Perhaps a misunderstanding.
The "full" test should return the entire amount of users within an LDAP, or does it base off the SIZELIMIT specified in the configuration?

I have 1000 users in my LDAP. When I hit the original button I get 100 users (My SIZELIMIT config is 100). When I change the SIZELIMIT in the UI configurations to 50, I will be returned with 50.

**Comment by cornelinux** [comment]
Hm, @quoc-axiadids you are right.
The change had the side effect that now the test uses the sizelimit from the configuration.
https://github.com/privacyidea/privacyidea/commit/ebc9963360e6ae42feb61fb34d483d737d833375#diff-03e4a9d860872d36e2b3381d1a0e9831R792
Originially the sizelimit was completly ignored. 
Do you recommend the full user number? What is your experience here?

**Comment by cornelinux** [comment]
If we need the full number of users, we could add something like:
https://github.com/privacyidea/privacyidea/commit/ebc9963360e6ae42feb61fb34d483d737d833375#diff-744d4962638fc4685ef0007e35191058R907

     else {
         params["SIZELIMIT"] = "";
     }

**Comment by quoc-axiadids** [comment]
@cornelinux 

I like having a 'quick' and 'full' alternative for testing. It's easily understandable for someone who is not familiar with LDAP configuring the settings.

If we were to test just base on the SIZELIMIT in the configurations, then we would not need a quick test because the user can adjust the size for testing.

**Comment by cornelinux** [comment]
OK, thx. I will change this accordingly to "full" again.
