### ISSUE TITLE
Make privacyidea-token-janitor able to clean up expired tokens

### ISSUE THREAD

**Issue by jean-gui** [privacyidea/privacyidea#692]
Could privacyidea-token-janitor be improved to remove tokens after their validity_period_time is over?

**Comment by cornelinux** [comment]
We already can match tokeninfo values. We could also match the ``validity_period_end``. 

  --tokeninfo-value TOKENINFO_VALUE
                        The tokeninfo key to match
  --tokeninfo-key TOKENINFO_KEY
                        The tokeninfo key to match

But the regular expression does not work to compare datetimes. 
So we rather should add the functionality to compare dates in ``TOKENINFO_VALUE``. This way we would be more flexible for the future.

**Comment by cornelinux** [comment]
...we try to add this to 2.19

**Comment by cornelinux** [comment]
--tokeninfo-key=validity_period_end --tokeninfo-value="2017-02-10" \\ 
          --compare=[bigger|smaller|older|newer]

--tokeninfo-key=validity_period_end --tokeninfo-value="2017-02-10"

This way we could compare dates an integer.

**Comment by fredreichbier** [comment]
It would be nice to do comparisons on integer as well as datetime values. However, the token info table does not store the value type. I think it would be a good idea to add several command line options:

For integers:
<pre>
--tokeninfo-value-greater-than=5
--tokeninfo-value-less-than=6
</pre>

For datetimes:
<pre>
--tokeninfo-value-after="2017-04-27T11:25:44+0000"
--tokeninfo-value-before="2017-04-27T11:25:44+0000"
</pre>

Writing the command may be a bit tedious then, but at least it's explicit.
