### ISSUE TITLE
Missing challenge response screen in lockscreen?

### ISSUE THREAD

**Issue by splashx** [privacyidea/privacyidea#702]
Please think about and cover the following questions:

# Versions

privacyIDEA: 2.18.1

Installation method:

- from github

## more details: 

OS: Ubuntu 16.04.2

Webserver: Apache

Tokendatabase: MariaDB

# Context 

In this environment the user is allowed to perform the first login without a token (`passthrough: datastore`) and after the first login a SMS token is created automatically. 

# What did you try to do?

Going to log into PI and enroll a TOTP .. but I logged into PI (turn back and talk to colleague - lol), wait for lockscreen to come up and the screen locked.

# What outcome did you expect?

The password prompt to come up (it did), enter the password and get the SMS otp (it arrived).
Enter the SMS otp in the challenge-response screen (it is not there)

# What outcome did you experience?

The user was prompted to enter the password again.

# Workaround @2.19

As a workaround I have changed the webui police to `logout` (instead of the default `lockscreen`).

**Comment by cornelinux** [comment]
That's right. CHallenge response is not supported in lock screen.

**Comment by cornelinux** [comment]
During normal login in case of challenge response the ``state``  is changed to ``response``. 

In case of a locked screen, the state is not changed. The user is still in the same state an will return to this state after unlocking. Thus handling the C/R must occur in the modal dialog.

Currently, if the user uses a C/R token, the user is redirected to the ``response`` state - still with the overlay of the locked screen.

If the correct PIN is entered in the lock screen then the ``loginController::authenticate`` is called. in the ``error function`` the state is switched to "response".
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/login/controllers/loginControllers.js#L193
At this point we need to check if we are at **login** or at **unlock**.
In case of **login** we can indeed go to the ``state`` "response". 
In case of **unlock** we need to change the contents of the modal lock-dialog.

See ``loginController::unlock_first``. In ``unlock_first`` and ``login_first`` we could set something like

* $scope.authenticate_mode = "login"
* $scope.authenticate_mode = "unlock"

The lock dialog is defined here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/dialogs/views/dialog.lock.html
