### ISSUE TITLE
Tokenenrollment wizard does not apply to super (admin) realm

### ISSUE THREAD

**Issue by foot3print** [privacyidea/privacyidea#705]
## Setup
Ubuntu 16
Privacyidea 2.18
Apache2
MySQL
LDAP Userstore
OTPPIN= userstore PW
Users authenticate against Privacyidea Server

## What did you try to do?
Tokenenrollment Wizard for admin realm
- created auth policy added: action=passthru for specific user='adminuser' in user-realm='adminrealm'

## What outcome did you expect?
The Tokenenrollment wizard should prompt after the first authentication of 'adminuser' with his PW

## What outcome did you experience?
- After authenticating with adminuser and backend PW, no Tokenenrollment Wizard is prompted.
- I also have another auth policy, but only for normal users under user-realm='userrealm' and the tokenenrollment wizard is shown after the authentication.

The tokenenrollment wizard seem to only apply to non-super realms.

Regards,

**Comment by cornelinux** [comment]
This is correct. This is a feature. No enrollmentwizard for admins.
I think they should know how to use the interface ;-)
