### ISSUE TITLE
transaction_id on second POST auth empty

### ISSUE THREAD

**Issue by foot3print** [privacyidea/privacyidea#708]
## Setup
privacyidea 2.18.1
ubuntu 16 xenial
apache2
userstore = mysql

Hi privacyidea Team! As part of an outsource team for an external project implementing 2FA (had to mention- for the record) , a colleague stumbled upon a possible small bug with regards to the challenge/response through the WebUI of the system. This is related to this: https://community.privacyidea.org/t/second-authentication-must-not-fail/442

## What did you try to do?
- Authenticated against Privacyidea using the WebUI.
- Challenge/Response was triggered after first authentication.
- Intentionally entered an incorrect OTP value. - Returned "Authentication Failure"
- Re-entered the correct OTP value. - Still ended with Failure.

## What outcome did you expect?
- Entering the correct value after an invalid one results to a successful authentication.
 
## What outcome did you experience?
- After debugging and based on the comments of @cornelinux, the second POST auth was indeed sent without transaction_id (empty).
#NOTE - I tried using the previously returned transaction_id and the correct OTP value and did a POST auth again which resulted to a successful authentication.

Regards,

**Comment by cornelinux** [comment]
@foot3print If possible please take a look if it suites your scenario. We tested successfully with TOTP token and challenge response.
