### ISSUE TITLE
Question - Microsoft Authenticator

### ISSUE THREAD

**Issue by markusza** [privacyidea/privacyidea#709]
Hi,

Just a question. Would it be possible to get Microsoft Authenticator (mobile APP) working? Or is it more a incompatibility from the App vendor side? 

I have installed and tested, but can't seem to authenticate. (Google Authenticator works)

Thanks

**Comment by cornelinux** [comment]
Please provide some more information about the microsoft authenticator. I do not know it.
Add a link to the enrollment process of this app.

**Comment by cornelinux** [comment]
I took a look at the microsoft authenticator, installed it and now I probably know your problem.
It is microsoft. It sucks. You should file a bug report at this app.

The M$ authenticator scans HOTP tokens QR codes but treats it as TOTP tokens. This will never work.
So obivously it only supports TOTP.

**Comment by cornelinux** [comment]
@markusza please consult https://community.privacyidea.org in the future. 

Thanks a lot 
Cornelius

**Comment by markusza** [comment]
@cornelinux Haha, yeah it sucks. A corporate was using it already and I hoped we could use it. Thanks, will use the community.
