### ISSUE TITLE
Idea/Feature request: Registration token as challenge/response

### ISSUE THREAD

**Issue by foot3print** [privacyidea/privacyidea#714]
## Setup
Ubuntu 16
privacyIDEA 2.19
mySQL
Policy: WebUI auth against privacyIDEA

# What did you try to do?
- Use/enable the registration token as OTP for challenge/response authentication.
The pupose of this is to require users within the domain to mail the admin first for a registration token which will be used by the user/s for their first login via the WebUI. The newly generated 'registration' token will then be sent through the EventHandler -> User Notification -> Email of the User. The advantage of this is that users will always do two-factor authentication instead of allowing users to have 'passthru'.

Regards,

**Comment by cornelinux** [comment]
You can already do this.
The admin can in fact enroll a registration token and the user can use it as described.
You do not have to configure "passthru".

Maybe you need some consultancy for setting up workflows? NetKnights provides those:
https://netknights.it/en/leistungen/one-time-services/

**Comment by foot3print** [comment]
@cornelinux 

The idea is to get the 'https://piserver.domain.com/#/response' window just like other tokens such as totp,hotp,sms after the first authentication (username+userstorePW) instead of entering the userstorePW+registration_code in the Password box of the login page. Sorry for insisting on this. Ill try to convince the ups to maybe purchase a support contingent.

Regards,

**Comment by cornelinux** [comment]
I think I do not understand it.
You should be able to do this, if you configure the registration token as C/R token.
But maybe we need to dive into more detail.
Getting a contingent to discuss your needs in full detail might be a good idea.
Kind regards
Cornelius

**Comment by foot3print** [comment]
Still waiting for the reply from ups ;-) We are using otppin=userstore (ldap). Ive configured the tokentype 'registration' in the authentication policy as one of the challenge_response = 'sms hotp totp registration' but the system still does not do challenge/response like its supposed to. It only authenticates successfully if I do the usual password+registrationcode
e.g.
username: user001
password: S3cret{registrationcode} -- success! No Challenge/Response?

username: user001
password: S3cret -- failed authentication

PS. Still waiting for ups. But thanks for your patience!

Regards,
