### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by rthill** [privacyidea/privacyidea#715]
Currently it is a bit annoying when unlocking privacyIdea and you are on a list like the tokens list. To refresh the list you have to navigate away and apply filters again to get actual results.

My proposal would be to get a refresh button to reload lists including the actual filter. From an UX point of view I could imagine having a refresh button near the currently logged-in user button or on top of the list, for example before the total tokens counter.

Cheers,
Raoul

**Comment by cornelinux** [comment]
Thanks for the request and the suggestion about the location.
The refresh button might also be in the main template (for all pages)

**Comment by rthill** [comment]
Yes, sure, this is what I meant with logged-in button, having a refresh for every page.                                                                                                                                                                        Raoul                                                                                                                                                                            From: notifications@github.comSent: June 1, 2017 1:26 PMTo: privacyidea@noreply.github.comReply-to: reply@reply.github.comCc: raoul.thill@gmail.com; author@noreply.github.comSubject: Re: [privacyidea/privacyidea] Feature request: Refresh button (#715)  Thanks for the request and the suggestion about the location.
The refresh button might also be in the main template (for all pages)

**Comment by cornelinux** [comment]
Reload function per state

**Comment by fredreichbier** [comment]
I looked into this -- 560ec83 implements a simple refresh button which looks like this (while refreshing): 
![refresh button](http://i.imgur.com/J3WUDCI.png)

It looks a bit weird because there are two spinners now, but I couldn't think of a better way, so I'm open to suggestions! :)
The only problem is that the filters are still lost when refreshing. I'll see if I can fix this.

**Comment by cornelinux** [comment]
We could hide the refresh button while loading. Thus either the loading-spinner would be visible or the refresh button.

Can states overwrite the "reload" method? So that different states/views know which filters to take into account?

**Comment by fredreichbier** [comment]
> Can states overwrite the "reload" method? So that different states/views know which filters to take into account?

``reload`` just calls ``$state.reload()``, which is provided by [ui-router](https://ui-router.github.io/ng1/docs/0.2.14/index.html#/api/ui.router.state.$state). This seems to completely reload the current state and filters are lost. Sadly I don't know enough angular yet to know if we can tell angular and ui-router to remember the filters :-)

However, someone on StackOverflow gave the hint to use ``sessionStorage`` to persist values over reloads. I implemented this for filters in 11b25d6: Now, the filter values are persisted over refreshes, and they also persist when the user enters a filter in the user list view, navigates away and comes back. But I guess the solution isn't very angular-y. I'll keep looking for a better way.
