### ISSUE TITLE
Enhance Notification Handler to write information to a file in spool directory

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#717]
The enrollment tab for HOTP and TOTP token could provide a letter template, when the QR Code is enrolled.

A policy could define the template file.
The template file could read contact data from the user source.
The created QR Code letter should be editable.

**Comment by cornelinux** [comment]
Usually this does not need to be a manual process, but it is rather automated.

And in this case the script event handler could be used to send data to a printing center after enrollment of a HOTP/TOTP token.

**Comment by cornelinux** [comment]
We could however enhance the ``UserNotification Hander`` to also write files to disk.

Using an html template file.

The handler would have to be enhanced with data from the "detail" section. Thus we could add the *otpkey* in the printer file.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/eventhandler/usernotification.py#L280

We could add the QR code like this:
<pre>
"""
Your qr code is

&lt;div class=center&gt;
{detail[googleurl][img]
&lt;/div&gt;
""".format(detail=detail)
</pre>

**Comment by cornelinux** [comment]
This would work without any policies.

The notification handler would be enhanced like this:

~~~~python
actions = {"writeletter": { "filename":
                                             {"type": "str",
                                              "required": True,
                                              "description": _("can contain tags")},
                                     "body": {"type": "text",
                                                  "required": True,
                                                  "description": _("can contain tags")},
                                },
~~~~

Any other process could fetch this pin-letter or QR-Code letter.

**Comment by cornelinux** [comment]
Relates to #1138

**Comment by fredreichbier** [comment]
In addition to "sendsms", "sendemail", this could be a third action in the notifcation handler "savefile".

We would still have a body, that defines the file. The body could contain html or csv with the usual tags.

Each event writes a new file with a temporary/random file name.

Additional options:
* Spool directory

**Comment by cornelinux** [comment]
We have a functionality in the email auth policy. https://privacyidea.readthedocs.io/en/latest/policies/authentication.html?highlight=file%3A%2F#emailtext that allows to specify a file template.
But I think this is only due to the fact, that the policy action field is so limited.

On the other hand in the NotificationHander in the action "sendemail" we have the "body", that is not read from a file but from the event handler definition. The [event handler option](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L1880) and thus the file template is 2000 bytes long.
I think this is enough and to make it working in the same way like the email, I would simply put the template into a body like with "sendemail".

~~~~python
 actions = {"sendmail": {....},
                  "sendsms": {...},
                  "savefile": {"template": {"type": "text",
                                         "required": True,
                                         "description": _("Template of the file with python tags")},
                                     "spooldirectory": {"type": "str"},
                                     "filename_prefix": {str},
                                     "filename_suffix": {str},
~~~~

**Comment by cornelinux** [comment]
I will not use a template file!
If it is necessary to create files that are much bigger than the 2K in the database for the text template,
the file written could very well be simply a csv file and another system level parser could generate bigger files in a second step.
