### ISSUE TITLE
multiple U2F tokens for a user and login to webui

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#722]
# What did you try to do?
I have multiple U2F tokens registered for my user (one for each of the two laptops
I use most of the time). Both tokens are registered in privacyidey and enrolled to my user.

When loggin in to the webui, I provide the password from the userstore (according to
my policy) and privacyidea challenges me for one of the tokens. Using that token
to complete the authentication works - the other token does not work. 

If I disable the "working" token, privacyidea challenges me with the other token
and authentication works.

# What outcome did you expect?
I did expect that I could complete the authentication with either token. The system
might provide a list of tokens, or just learn from the response which token I used.

# Configuration
* privacyIDEA Version: 2.19 from ppa
## more details: 
* OS: Ubuntu 16.04
* Webserver: apache
* Tokendatabase: MySQL

My first guess was an error in webui, but I guess the first error happens when constructing
the multi_challenge.  This is (redacted and reformatted) from a call to /validate/check:
[This was for only one active token, so I've removed it]

From my reading of static/components/login/controllers/loginControllers.js I'm not sure multi_challenge will work anyway.

**Comment by jh23453** [comment]
My testcase is broken, this was with only one token.. It looks much better:

    {
    "detail": {
        "attributes": {
            "hideResponseInput": true,
            "img": "static/css/FIDO-U2F-Security-Key-444x444.png",
            "u2fSignRequest": {
                "appId": "https://pi.example.org/ttype/u2f",
                "challenge": "...challenge2...",
                "keyHandle": "...keyhandle2...",
                "version": "U2F_V2"
            }
        },
        "message": "Please confirm with your U2F token (Yubico U2F EE Serial 1123359309/U2F4017813)",
        "multi_challenge": [
            {
                "attributes": {
                    "hideResponseInput": true,
                    "img": "static/css/FIDO-U2F-Security-Key-444x444.png",
                    "u2fSignRequest": {
                        "appId": "https://pi.example.org/ttype/u2f",
                        "challenge": "...challenge1...",
                        "keyHandle": "...keyhandle1...",
                        "version": "U2F_V2"
                    }
                },
                "serial": "U2F03638840_jkellner",
                "transaction_id": "10209913273978107360"
            },
            {
                "attributes": {
                    "hideResponseInput": true,
                    "img": "static/css/FIDO-U2F-Security-Key-444x444.png",
                    "u2fSignRequest": {
                        "appId": "https://pi.example.org/ttype/u2f",
                        "challenge": "...challenge2...",
                        "keyHandle": "...keyhandle2...",
                        "version": "U2F_V2"
                    }
                },
                "serial": "U2F04017813_jkellner",
                "transaction_id": "09794416291340541656"
            }
        ],
        "serial": "U2F04017813_jkellner",
        "threadid": 140389286082304,
        "transaction_id": "09794416291340541656"
    },
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "status": true,
        "value": false
    },
    "signature": "...lotsofnumbers...",
    "time": 1496956561.989809,
    "version": "privacyIDEA 2.19",
    "versionnumber": "2.19"
    }

So, multi_challenge has both tokens, but "details" has the last token infos - and that token works.
My guess now is that we validate against "details" instead of "multi_challenge"- But that's for
another day.

**Comment by jh23453** [comment]
I'm playing with ./static/components/login/controllers/loginControllers.js and can parse the multi_challenge response. As we see from the example above the transaction_id values are different for the two challenges.

In  api/validate.py we have this comment:

    .. note:: All challenge response tokens have the same transaction_id in
       this case.

Is this only valid for different token types? Or should the example above also have the same transaction_id?

Later in loginControllers.js we have:

                $scope.transactionid = error.detail["transaction_id"];
    ...
                    U2fFactory.sign_request(error, $scope.login.username,
                        $scope.transactionid, $scope.do_login_stuff);

Here we probably need to find the "correct" transaction_id if they really should be different.
Or do I miss something?

**Comment by jh23453** [comment]
That's my WIP patch - right now I get a BAD REQUEST...

```
--- privacyidea/static/components/login/controllers/loginControllers.js.orig    2017-06-11 22:39:13.106125273 +0200
+++ privacyidea/static/components/login/controllers/loginControllers.js 2017-06-16 22:25:43.030805718 +0200
@@ -194,6 +194,16 @@
                     "Authentication. You" +
                     " are not completely authenticated, yet."),
                     {type: "warning", ttl:5000});
+
+                if (error.detail && error.detail.multi_challenge) {
+                    console.log("multi challenge");
+                    error.detail.message = 'Please confirm with one of these tokens:'
+                    for (var i in error.detail.multi_challenge) {
+                        console.log("multi challenge serial: " + error.detail.multi_challenge[i].serial);
+                        error.detail.message = error.detail.message + ' ' + error.detail.multi_challenge[i].serial;
+                    }
+                }
+
                 $scope.challenge_message = error.detail.message;
                 $scope.transactionid = error.detail["transaction_id"];
                 $scope.image = error.detail.attributes.img;
--- privacyidea/static/components/login/factories/u2f.js.orig   2017-06-16 22:27:51.179183249 +0200
+++ privacyidea/static/components/login/factories/u2f.js        2017-06-16 22:40:03.405339423 +0200
@@ -51,6 +51,14 @@
                 sign_request: function (data, username, transactionid,
                                         login_callback) {
                     var signRequests = [data.detail.attributes.u2fSignRequest];
+                    if (data.detail.multi_challenge) {
+                        console.log("sign_request: multi challenge");
+                        var signRequests = [data.detail.attributes.u2fSignRequest];
+                        for (var i in data.detail.multi_challenge) {
+                           console.log("multi challenge u2f: " + data.detail.multi_challenge[i].serial);
+                           signRequests[i] = data.detail.multi_challenge[i].attributes.u2fSignRequest;
+                        }
+                    }
                     u2f.sign(signRequests, function (result) {
                         inform.clear();                                                                                                                                
                         if (result.errorCode > 0) {                                                                                                                    ```

**Comment by jh23453** [comment]
Ok, here's the third part. When we get into u2ftoken.py / check_otp with the first U2F token, but the users has used the second one, we bailed out the a ValidateError exception and did not check the second or more token. So we return just an error and tokenclass.py / check_challenge_response will try the next token.

```
diff --git a/privacyidea/lib/tokens/u2ftoken.py b/privacyidea/lib/tokens/u2ftoken.py                                                                                    
index 768a45b..e1948ae 100644                                                                                                                                           
--- a/privacyidea/lib/tokens/u2ftoken.py                                                                                                                                
+++ b/privacyidea/lib/tokens/u2ftoken.py                                                                                                                                
@@ -450,8 +450,7 @@ class U2fTokenClass(TokenClass):                                                                                                                    
             clientdata_dict = json.loads(clientdata)                                                                                                                   
             client_challenge = clientdata_dict.get("challenge")                                                                                                        
             if challenge_url != client_challenge:                                                                                                                      
-                raise ValidateError("Challenge mismatch. The U2F key did not "                                                                                         
-                                    "send the original challenge.")                                                                                                    
+                return ret                                                                                                                                             
             if clientdata_dict.get("typ") != "navigator.id.getAssertion":                                                                                              
                 raise ValidateError("Incorrect navigator.id")                                                                                                          
             #client_origin = clientdata_dict.get("origin")                                                                                                             ```

**Comment by cornelinux** [comment]
Just to add my observations. If the user has two U2F tokens with the same OTP PIN (or userstore PW), then two challenges are created with different transaction_ids:

<pre>
mysql> select * from challenge;
+----+----------------------+------+------------------------------------------------------------------+---------+-------------+---------------------+---------------------+----------------+-----------+
| id | transaction_id       | data | challenge                                                        | session | serial      | timestamp           | expiration          | received_count | otp_valid |
+----+----------------------+------+------------------------------------------------------------------+---------+-------------+---------------------+---------------------+----------------+-----------+
| 24 | 06665850986801076564 |      | d887faab17a38ee48cb37b2204b5d24a4fc0fbc1b19de0e7fc0c2b3c1a899c7d |         | U2F00024E7B | 2017-07-12 08:58:22 | 2017-07-12 09:00:22 |              0 |         0 |
| 25 | 02868445584815062327 |      | d7fbc8127525f54fe38082bb1b0c43153151b8e1569561b561c92ab776fad5a8 |         | U2F00039248 | 2017-07-12 08:58:22 | 2017-07-12 09:00:22 |              0 |         0 |
+----+----------------------+------+------------------------------------------------------------------+---------+-------------+---------------------+---------------------+----------------+-----------+
2 rows in set (0,00 sec)
</pre>

The WebUI asks the User for one _very_ token. @jh23453 you can see this, if you add a description to the token. The description will be displayed in the UI Login dialog.

# TODO

* [ ] **Verify** if it is correct that two different transaction_ids are created. How is this with other tokens?

* [ ] **Check** if it would be possible to check both challenges in the server code. (Maybe this would even work out of the box, if both challenges had the same transaction_id!?

**Comment by jh23453** [comment]
Hello Cornelius,

in stock privacyidea the two challenges get different transaction_id, which is wrong.
Tokens other than U2F seem to get this right.

I've proposed a fix in https://github.com/privacyidea/privacyidea/pull/725/commits/fbb7c51344ca694f4c3475a0adfa5baa48e1359b

```
commit fbb7c51344ca694f4c3475a0adfa5baa48e1359b
Author: Jochen Hein <jochen@jochen.org>
Date:   Sat Jun 17 07:10:05 2017 +0200

    fix transaction_id for multi_challenge requests
    
    In create_challenge we get transactionid=None when adding the first
    challenge and generate one. The caller gets the transaction ID back
    and hands it back for the next/subsequent tokens for the same
    request.
    
    When adding the challenge in the database we always used
    transaction_id=None, so multiple U2F tokens get different
    transacrion_ids for a single request.
    
    Use transaction_id=transactionid, so we have None for the first
    and use the generated transaction ID for the other tokens.

diff --git a/privacyidea/lib/tokens/u2ftoken.py b/privacyidea/lib/tokens/u2ftoken.py
index a3ee306..768a45b 100644
--- a/privacyidea/lib/tokens/u2ftoken.py
+++ b/privacyidea/lib/tokens/u2ftoken.py
@@ -403,7 +403,7 @@ class U2fTokenClass(TokenClass):
         challenge = geturandom(32)
         # Create the challenge in the database
         db_challenge = Challenge(self.token.serial,
-                                 transaction_id=None,
+                                 transaction_id=transactionid,
                                  challenge=binascii.hexlify(challenge),
                                  data=None,
                                  session=options.get("session"),
```

It works much better with the same transaction_id identical, but there are more changes needed.
Please have a loot at the other patch in the pull request.

Multiple U2F tokens work fine for me with the two patches applied.

**Comment by cornelinux** [comment]
Hi @jh23453 you are right. The base class ``TokenClass``  also passes the transactionid.

So fbb7c51 looks totally fine.

I will take a look at 14f0804703e855c653ac690a59b5bba680e79a72
