### ISSUE TITLE
Using hash algorihm (via policy) during TOTP/HOTP token enrollment

### ISSUE THREAD

**Issue by rmalchow** [privacyidea/privacyidea#723]
# What did you try to do?

enroll a client-generated TOTP token with an explicit hashing algorithm (SHA1 in this case) that did not match the configured policy.

# What outcome did you expect?

i expected to get an error message describing that the requested hashing algorithm does not match the configured policy.

# What outcome did you experience?

the token was created with the hashing algorithm from the policy (silently overriding my request)

# Configuration

* privacyIDEA Version: 2.18.1

**Comment by cornelinux** [comment]
Thanks for reporting. 
Did you enroll as administrator or as user?

**Comment by rmalchow** [comment]
i am not entirely sure. i think admin? however, we didn't use the admin ui, we used the "simple" ui and modified the ajax request. eventually, we would like to only talk to the API in most cases. like i said: this is neither anywhere near being a big bug nor is a huge problem for us. i just think a consistent validation with the appropriate error messages would be an improvement to the API

**Comment by cornelinux** [comment]
So if you are talking to the API this is the expected behaviour, that the policy overrules the chosen hash algo.

Or do you expect, that enrollment fails, if the user specifies a hash algo, that is not "allowed"?

What is the "simple" UI?
Can you provide a screen shot?

**Comment by rmalchow** [comment]
yes, i would expect the call to fail.

**Comment by cornelinux** [comment]
OK, I understand. But this would not be the behaviour in other cases. 
If there are policies, which overrule certain user settings, the user settings are ignored.
Like when using ``genkey`` and ``otpkey``.

What sounds sensible to me is, to not present the user all the hash algo in the **UI**, if there is a policy. This is why I was asking, if you remeber *where* it happened.

**Comment by cornelinux** [comment]
**Example:**

A ``user``-policy sets ``totp.hashlib`` to "sha256".

When the user logs in and enrolls TOTP-Tokens the UI let the user still choose the hashlib.

* [ ] The UI should not display the totp.hashlib, since it is specified in the policy.

The init-request is sent to the server with ``totp.hashlib=sha1``.
The token is enrolled with sha1.
* [ ] The token should be enrolled with sha256, even if the request sends a sha1

**Comment by cornelinux** [comment]
Added a test to verify bullet point 2 and 3 in test_api_token.py
