### ISSUE TITLE
Event creation via API is not idempotent

### ISSUE THREAD

**Issue by splashx** [privacyidea/privacyidea#727]
# What did you try to do?

The following Event creation via API call run `n` times `n >1`:

```
curl 'http://127.0.0.1:5000/event' \
-XPOST \
-H 'Content-Type: application/json' \
-H 'Referer: http://127.0.0.1:5000/' \
-H 'Accept: application/json, text/plain, */*' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4' \
-H 'Origin: http://127.0.0.1:5000' \
-H 'PI-Authorization: <too-long-to-paste> \
--data-binary '{"action":"enroll","active":true,"condition":"","conditions":{"realm":"localsql","result_value":"True","user_token_number":"0"},"event":"validate_check","handlermodule":"Token","id":"","name":"pannet_autoenrollsmstoken","options":{"realm":"localsql","tokentype":"sms","user":true},"ordering":0,"option.realm":"localsql","option.tokentype":"sms","option.user":true}'
```

*Note* that no value for `id` has been given.

# What outcome did you expect?

Before reading the source code :trollface: :
Expect to see only one event in the WebGUI > `Config` > `Events` section.

# What outcome did you experience?

There are `n` repeated events configured with the same properties (`id` differs)

# Configuration

* privacyIDEA Version: 2.19

* Installation method: from source

## more details: 

* OS: Ubuntu

* Webserver: Apache2

* Tokendatabase: MariaDB

# Comments

`Events` could follow the idempotency logic used in `Policies`: if a policy with the same name exists, update it - if not, create it.
After reading the source code I understood `Events` don't use `name` for uniqueness (but `id` and that is generated internally) - even though `name` is a parameter in the `/event` API call, its value actually ends up  in `description` (really just _metadata_).

This behaviour for `Events` breaks the logic of other API endpoints (like `/resolver`, `/policy`, etc) where names are unique and can be predefined by the user - therefore we can rely in the "update if exists, otherwise create logic".

The current behaviour of `Events` is, well, not cool because we can't define a final state of the configuration (breaking support towards state-driven configuration management systems, e.g. ansible).

**Comment by cornelinux** [comment]
Interesting. I was wondering when the first one would complain about this. ;-)
Nevertheless you can get the id of the event and update this very event definition by the id.

**Comment by splashx** [comment]
.. but one needs to get all events, iterate and look for a match by `name` (which is not unique 🙈 ) and get the id 😢 

The other behaviour is much better and nicer - not to mention having different behaviours among modules well, breaks consistency across the software...

**Comment by cornelinux** [comment]
I somehow would like to close this issue. This is something to take into account in the long run, if we uniquify events and policies. However - I am missing the issue number to reference it.
But currently (without redesigning events and policies) I do not see the need for action.
