### ISSUE TITLE
Revoking certificates doesn't work when serial starts with "0"

### ISSUE THREAD

**Issue by mimugmail** [privacyidea/privacyidea#737]
Creating a fresh CA a serial start with 0, creating some more it goes up to e.g. "0D".
Revoking such a certificate ends with the error, that file "D.pem" cannot be found. It seems the trailing 0 will be ignored.

Creating more and more certificates until you reach 11 is ATM my workaround.

All current versions affected.

**Comment by cornelinux** [comment]
OK, this was due to an error in converting the integer serial number to hex.
