### ISSUE TITLE
Provide ability to specify hashing algorithm for passwords in sql resolvers

### ISSUE THREAD

**Issue by eubyte** [privacyidea/privacyidea#745]
Is it possible to specify a default hashing algorithm when creating a new sql resolver, or set it on a per-user basis when adding new users via WebUI. Thank you!

**Comment by cornelinux** [comment]
No, it is not.
The password is saved as ``{SSHA256}``.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/SQLIdResolver.py#L725

**Comment by cornelinux** [comment]
We could add an additional config field to the sqlresolver like:

    hash algo for new users:

I think we should not misuse the user mapping, since it is no usermapping in this sense.

Then hashing algos could be entered like

* ssha256
* sha256
* ....

(The once we support here)
