### ISSUE TITLE
retrieve TOTP seed and / or provide a way to test for token only

### ISSUE THREAD

**Issue by rmalchow** [privacyidea/privacyidea#759]
# What did you try to do?

We're building some functionality with Privacy Idea  as on of the components. Usually, I want PW+OTP, except in some special situations (specifically, a password reset in another system) where I would like to verify the correctness of at least one token for a user

# What outcome did you expect?

i would very much appreciate if i could retrieve the seeds for the tokens(not so nice), or, and this would be a lot nicer, to have a call such as:

      /token/test

     user - username
     realm - realm 
     otp - the current otp value
     otppin - if set 

and a result like this

    {
	"signature": "[...]",
	[...]
	"result": {
		"status": true,
		"value": {
                        "serial" : "SERIAL_OF_MATCHING",
			"success": true,
			"offset" : 32 .   <---- might as well, while we're at it
		}
	},
	[...]
    }

.... does this make sense for you?

**Comment by cornelinux** [comment]
We do not return secrets light-hearted.

But you can use /validate/check with a authentication policy depending on the client IP. So some applications/clientIPs would use ``otpppin=userstore`` and others could use ``otppin=none``.

But for you it might be more interesting to use ``/validate/check`` with the option ``otponly=1``.

See the API documentation: http://privacyidea.readthedocs.io/en/latest/modules/api/validate.html#post--validate-check

**Comment by rmalchow** [comment]
i completely agree with handing out secrets. and, yes, i guess this would work ... tiny caveat is this  "Only used with the parameter serial."  so i assume 

`[...]?user=hund&optonly=1&pass=123456` 

will not work? 

i will need to check if this ok. maybe a user has more than one token ... so i would have to retrieve the list of tokens using an admin account, then try them one by one ... worst case would be that this slows things down a little ...

**Comment by cornelinux** [comment]
Yes, it only works with ``serial``.
https://github.com/privacyidea/privacyidea/blob/f73fac2ee77d72c0ff107f69c85e833b177e8063/privacyidea/api/validate.py#L293

We use the "otppin" to identify the token. Otherwise we would have to add additional logic to iterate through all tokens.
