### ISSUE TITLE
privacy idea accepts incorrectly formatted secrets on "/token/init"  then fails on "/validate/check"

### ISSUE THREAD

**Issue by rmalchow** [privacyidea/privacyidea#764]
# What did you try to do?

i enrolled a new token (created outside of privacyidea) via /token/init with a secret in base32 like this:

5XXPFKZTBYDSZISR252SIOT6BFTLJSH3

the token was accepted and is visible in the UI exactly as i created it, but when i call    /validate/check  for that token, i get the error message

`"Non-hexadecimal digit found"
`
this was rather unexpected :)

# What outcome did you expect?

either enrollment should fail with an appropriate message about OR the check call should work. also, i couldn't find any documentation on the required format ... that would have been nice. i am now guessing something hexadecimal ... :/ 

# Configuration

* privacyIDEA Version: 2.1.19

**Comment by rmalchow** [comment]
the naive approach of just encoding the bytes from the secret into he didn't work ... and the UI expects exactly 12 digits as "otpkey"?

**Comment by cornelinux** [comment]
This complies to the principle *shit-in-shit-later-out*. ;-)

The token initialization simply is missing a data input validation.
The *otpkey* is written to the database in the baseclass

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokenclass.py#L519

But when the *otpkey* is read the ``TOTPtokenclass`` assumes, that it is hex encoded.

So maybe a tokenclass should have a otpkey-validation-method. For HOTP and TOTP it would be verify if it is hex.
But still you will be able to put sensless data into it like a hexstring-length which does not fit the used hash algorithm...

I do not think that it is related to #707.

**Comment by cornelinux** [comment]
You must do it like this:

    key_bin = base64.b32decode("5XXPFKZTBYDSZISR252SIOT6BFTLJSH3")
    key_hex = binascii.hexlify(key_bin)

Now you can pass key_hex in the parameter otpkey.

**Comment by rmalchow** [comment]
haha. yes, ok. i also found out the right encoding in the meantime. validation would have been very helpful. the UI apparently does some stuff - because the button gets disabled whenever there is non-hexadecimal key material in the input field.

for people from the java world, the conversion is:

```
import org.apache.commons.codec.binary.Base32;  // commons-codec
import org.apache.commons.codec.binary.Hex; // commons-codec

Base32 b32 = new Base32();
Hex h = new Hex();
			
byte[] secretBytes = b32.decode(base32encodedSecret);
String hexSecret = new String(h.encode(secretBytes));
```

the connection to #707  was about the error i encountered when i tried to use the UI to figure out the encoding.

**Comment by cornelinux** [comment]
I close this issue, since the UI does not allow non-hex characters anymore.
