### ISSUE TITLE
PI_LOGCONFIG does not work as expected, old-style logfile is still required

### ISSUE THREAD

**Issue by chgarling** [privacyidea/privacyidea#765]
# What did you try to do?
I tried to use PI_LOGCONFIG instead of PI_LOGFILE and PI_LOGLEVEL to have a more fine graduated logging. I only configured PI_LOGCONFIG and removed the two others from pi.cfg.

# What outcome did you expect?
Logging as configured in logging.conf, no need for the old-style logfile /opt/privacyidea/privacyidea.log.

What do you think, how the system should have worked?
It should only use PI_LOGCONFIG and ignore PI_LOGFILE and PI_LOGLEVEL.

# What outcome did you experience?
The logging.conf as configured in PI_LOGCONFIG was used, also the old-style logfile /opt/privacyidea/privacyidea.log was required for privacyIDEA to work. Without that file an error 503 will be served. If I create the file /opt/privacyidea/privacyidea.log it will also be used with loglevel debug and privacyIDEA works again.

What did acutally happen?
Logging is redundant, debug log will be written without need of that.

# Configuration

* privacyIDEA Version: 2.19.1

* Installation method:
  CentOS 7 virtuelenv, manual pip installation

## more details: 

* OS: CentOS 7

* Webserver: Apache 2.4

* Tokendatabase: MySQL

**Comment by cornelinux** [comment]
How does the file PI_LOGCONFIG look like and what does the apache Error log say?

**Comment by chgarling** [comment]
Good Morning Cornelius,

I found a name mismatch in my config when I was selecting the information to answer your question. It was logging.cfg (configuration) vs. logging.conf (filename). As I fixed this there is no more need for the old-style config file /opt/privacyidea/privacyidea.log.

Configuration now looks like this:

`~ # grep LOG pi.cfg 
PI_LOGCONFIG = '/etc/privacyidea/logging.cfg'`

`~ # cat logging.cfg 
[formatters]
keys=detail

[handlers]
keys=file,mail

[formatter_detail]
class=privacyidea.lib.log.SecureFormatter
format=[%(asctime)s][%(process)d][%(thread)d][%(levelname)s][%(name)s:%(lineno)d] %(message)s

[handler_mail]
class=logging.handlers.SMTPHandler
level=ERROR
formatter=detail
args=('localhost', 'privacyidea@example.com', ['c.garling@example.com'], 'PI Error')

[handler_file]
# Rollover the logfile at midnight
class=logging.handlers.RotatingFileHandler
backupCount=14
maxBytes=10000000
formatter=detail
level=INFO
args=('/var/log/privacyidea/privacyidea.log',)

[loggers]
keys=root,privacyidea

[logger_privacyidea]
handlers=file,mail
qualname=privacyidea
level=INFO

[logger_root]
level=ERROR
handlers=file`

The logging itself looks good now. But when I log in privacyIDEA still tells me DEBUG mode is enabled, but its not in logging.cfg as you can see. Do I have to set PI_LOGLEVEL additionally?

Regards, Christian

**Comment by cornelinux** [comment]
Good to hear this!

In regards to the log level and the warning in the UI, I see that the UI only uses the configuration setting "PI_LOGLEVEL". If you remove it from the pi.cfg, the default is used, which is defined here:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/config.py#L67

Hm, we changed this to "DEBUG", once. So yes, please add

     PI_LOGLEVEL = logging.info

in pi.cfg simply to remove this warning.

The additional logging, when you use a logging config file can be this complecated, that we can not easily display such a warning in the webui.

**Comment by cornelinux** [comment]
@chgarling so can we close this?

**Comment by chgarling** [comment]
@cornelinux, what do you think about the behavior of PI_LOGLEVEL in case PI_LOGCONFIG will be used? I think it would be more intuitive if the default level is not debug, so you can use only PI_LOGCONFIG at all without the need to set PI_LOGLEVEL to suppress the warning in the webui.

**Comment by cornelinux** [comment]
You are right. But setting the PI_LOGLEVEL will help you at the moment.

**TODO** Change loglevel in config.py for "production" to "INFO".
