### ISSUE TITLE
Actual Device IP is not logged when hitting url /ttype/<ttype>

### ISSUE THREAD

**Issue by lavesh-axiadids** [privacyidea/privacyidea#772]
Hi,

When hitting the URL /ttype/<ttype>, IP of the proxy is getting logged in audit logs, instead of actual device ip.

Client ip is got by making call to **lib/utils.py/get_client_ip** function. In this function, check for request blueprint is there. ( _request.blueprint in ["validate_blueprint", "jwtauth"]_)

Currently, if request.blueprint is either "validate_blueprint" or "jwtauth" then only actual device ip is found.

For /ttype/<ttype> request if "ttype_blueprint" is also added to that array, actual device ip can be found or logged.

Thanks,

**Comment by laveshkgupta** [comment]
Hi,

I have created a patch for the fix. Cornelius please have a look if this is the desired way for fixing this issue

[772.txt](https://github.com/privacyidea/privacyidea/files/1269718/772.txt)

Thanks

**Comment by fredreichbier** [comment]
Thank you for the patch! Could you open a Pull Request for this? This makes processing easier for us.

**Comment by cornelinux** [comment]
Closed by #781

**Comment by lavesh-axiadids** [comment]
Hi Cornelinux,

This is fixed by #782   https://github.com/privacyidea/privacyidea/pull/782

not #781
