### ISSUE TITLE
/ttype/<ttype> getting logged instead of /ttype/email in audit logs

### ISSUE THREAD

**Issue by lavesh-axiadids** [privacyidea/privacyidea#773]
Hi,

When making `/ttype/<ttype>` request, in audit logs, for action `/ttype/<ttype>` is getting logged. It is happening due to _"action": "{0!s} {1!s}".format(request.method, request.url_rule)_
`request.method = get and
request.url_rule = /ttype/<ttype>`

Is it possible to log URL as **/ttype/email** which is the actual value of tokentype (`<ttype>`) when making the call

Thanks,

**Comment by laveshkgupta** [comment]
Hi,

I have created a patch for the fix. Cornelius please have a look if this is the desired way for fixing this issue

[773.txt](https://github.com/privacyidea/privacyidea/files/1269712/773.txt)

Thanks

**Comment by fredreichbier** [comment]
Hi, thank you for the issue and the patch! Could you please open a pull request with your changes? This makes the review easier for us.

**Comment by cornelinux** [comment]
@lavesh-axiadids It would be great if you would create a pull request for this issue and #772. This way you are also logged as the real contributor of your code, which we appreciate a lot!
Thanks

**Comment by cornelinux** [comment]
Second thought:

There are similar URL, which would get logged this way, if the URL contains a parameter.
Like

     DELETE /token/OATH123456

In this case the audit log also contains 

     DELETE /token/<serial>

But it also contains the ``serial`` number in the info section of the audit entry.

@fredreichbier I am wondering, if we should be consistent in this case and also log ``/ttype/<type>`` but add the *tokentype* to the audit info...?

**Comment by lavesh-axiadids** [comment]
I created a local branch "773" in my system. Made the changes in local branch and committed them.When I pushed them to remote I am getting a 403 error using my credentials


After this I tried to generate a pull request with following command and output

`git request-pull 773 https://github.com/privacyidea/privacyidea master
The following changes since commit 8ba5cc2b74f9b6c621cd91fa37c3da2f479a9c36:

  Catch exceptions in token-janitor (2017-09-10 13:25:00 +0200)

are available in the git repository at:

  https://github.com/privacyidea/privacyidea master

for you to fetch changes up to 01447e4af196a8a25d0a7f2782843492cb5e8e49:

  Add more audit config parameters (2017-09-11 10:52:05 +0200)

----------------------------------------------------------------
Cornelius Kölbel (1):
      Add more audit config parameters

 doc/installation/system/inifile.rst | 24 ++++++++++++++++++++++++
 1 file changed, 24 insertions(+)
`
Please let me know how can I create a pull request instead of just posting a patch

**Comment by cornelinux** [comment]
Usually github has some nice documentation on all this stuff.

The interesting thing is, that your forked github repo has an upstream note:

    cat .git/config
    [remote "upstream"]
	url = https://github.com/privacyidea/privacyidea.git
	fetch = +refs/heads/*:refs/remotes/upstream/*

The thing is, that you should update your local repo with the changes of the upstream repo first, solve conflicts, and then push to your repo again and create (or update) the pull request.

Synching upstream is a  good source to read:

https://help.github.com/articles/syncing-a-fork/

After this you can push to your own repo https://github.com/lavesh-axiadids/privacyidea and create the pull request.

**Comment by fredreichbier** [comment]
Hmm yes, if I'm not overlooking any drawbacks here, I think it would be nice to preserve consistency and have ``/ttype/<ttype>`` logged as "action", with the actual token type located given in the ``type`` column.

**Comment by lavesh-axiadids** [comment]
Hi Cornelius,

In this section of code

g.audit_object.log({"success": 1,
                    "user": user.login,
                    "realm": user.realm,
                    "serial": serial,
                    "tokentype": ttype})

You are using ‘tokentype’, but in db column name is ‘token_type’. If you change above to 

g.audit_object.log({"success": 1,
                    "user": user.login,
                    "realm": user.realm,
                    "serial": serial,
                    "token_type": ttype})

Then token type will be seen in audit logs. Currently, token type in audit logs does not show anything, it is blank.

**Comment by cornelinux** [comment]
@lavesh-axiadids you are right! Thanks a lot!

**Comment by cornelinux** [comment]
Closed by cfef8aca3c961c6fbb2cc46e0274a5c9a6d46863
