### ISSUE TITLE
Manage PGP Keys on Nitrokeys

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#791]
We could use the privacyideaadm tool to enroll PGP keys on Nitrokeys or Yubikeys.

We need a new token type PGP key - probably similar to the ssh keys.
Or we could use the ssh key?

Should we also be able to store the private key like with x509 certificates?

**Comment by cornelinux** [comment]
We can use ``gpg2 --card-edit`` and pexpect:

<pre>
import pexpect
child = pexpect.spawn("gpg2 --card-edit")
child.expect("gpg/card>")
child.sendline("list")
child.expect("gpg/card>")
r = child.before
child.sendline("quit")
print r
</pre>

**Comment by jans23** [comment]
I don't know the details of your key types but the difference of this case to normal soft SSH keys is little. Perhaps SSH key may be sufficient.

After generating a new key you want to export it as a SSH key: `gpg2 --export-ssh-key 12345678 >> ~/authorized_keys` where 12345678 is the subkey ID.
See also [our documentation](https://www.nitrokey.com/documentation/applications#p:nitrokey-pro&os:linux&a:ssh-for-server-administration) for more information.

**Comment by jans23** [comment]
An example how to control scdaemon (as an alternative to scraping GPG) is [here](https://github.com/gpg/gpa/blob/0a78795146661234070681737b3e08228616441f/src/cm-openpgp.c).

**Comment by cornelinux** [comment]
@jans23 Thanks a lot. These are 1700 lines of code - so roughly a tenth of privacyidea. Can you give a hint about line numbers? The complete file does not contain the string "scdaemon".

**Comment by szszszsz** [comment]
I have found it - see this Niibe's implementation in Gnuk's toolset:
https://github.com/Nitrokey/nitrokey-start-firmware/blob/gnuk1.2-regnual-fix/tool/gpg_agent.py
Perhaps this would be useful to you.

**Comment by jans23** [comment]
To use Nitrokey with OpenSSH, keys on the device can be generated with a single command:
`openpgp-tool --verify CHV3 --pin 12345678 --gen-key 3`
