### ISSUE TITLE
Improve customization

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#795]
The administrator should be able to improve the customization:

# What

* ~~Logo (we already do this)~~
* ~~CSS (we already do this)~~
* Links in the Footer (Dokumentation, Support...)
* Links in the right menu (Dokumentation, Support...)

# How

Customization could be done via:

* policies - this way we could also  show different menus to different user groups or different client IPs, since the conditions of policies apply.
* simple files
* configs in pi.cfg
* ...

**Comment by cornelinux** [comment]
We should also allow for a wider view, to use more of the screen to avoid scrolling.

**Comment by fredreichbier** [comment]
If we simply want to make it possible to customize portions of the static HTML (i.e. everything in ``privacyidea/static/templates/``), we could make use of Jinja's [template inheritance](http://jinja.pocoo.org/docs/2.9/templates/#template-inheritance):
We could, for example, define a block with a default content in our ``index.html``:
```jinja
<html>
...
{% block footer %}
our footer
{% endblock %}
...
</html>
```

And then allow users to define an template ``customized_index.html``:

```jinja
{% extends "index.html" %}
{% block footer %}
customized footer
{% block footer %}
```

**Comment by cornelinux** [comment]
We could use policies to replace the "templates/menu.html" in the index.html
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/templates/index.html

and also the footer.

**Comment by cornelinux** [comment]
# Policies

We will define this policy:

* scope=webui
* action=custom_menu (text) -> a relative file name like custom-template/my-menu.html

* scope=webui
* action=custum_baseline (text) -> a relative file name like custom-template/my-baseline.html

As these policies are read _before_ the user logs in, the policies can be time and IP dependent but not user dependant.

Add reading the policies here:
https://github.com/privacyidea/privacyidea/blob/795/customize/privacyidea/webui/login.py#L110
