### ISSUE TITLE
2step enrollment with privacyidea authenticator

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#797]
The two step enrollment has to work with the privacyIDEA authenticator.

See 
* https://github.com/privacyidea/privacyidea-authenticator/issues/4 
* https://github.com/privacyidea/privacyidea-authenticator/issues/5

These things have to be done on the server side:

1. Implement the better key generation function based of pbkdf2
2. Create testvectors for the key generation, so that we can have tests on server side and on app side
3. Allow to choose 2step enrolment in enrollment ui. In case of 2step enrollment the enrollment ui needs to display an entry field (for the nonce) in addition to the QR code.
4. Add configuration option for 
   * information to be put into the QR code (?pin=true, ?2step=true)
   * if at all/how and when to use 2step. So that not the admin or use can choose to enroll 2step but a policy will define this.
   The config options are probably best defined in an enrollment policy.

**Comment by cornelinux** [comment]
The Token baseclass defines a simple method to create the OTP seed from the server component and the client component.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokenclass.py#L1573

The HOTPTokenClass, which is also the parent class for TOTP could overwrite this method with pbkdf2.

# TODO

* define test vectors.

**Comment by cornelinux** [comment]
To configure the

* rounds
* length of client part
* optional length of server part

(length of generated secret depends on the chosen HMAC algorithm.)

These values can be configured in a policy: scope=enrollment, and actions like ``2step_rounds``, ``2step_...``.

These values are added to /token/init via decorators like the ``init_tokenlabel`` or other enrollment policy decorators.

The function generate_google_url in lib/apps.py needs to use these values somehow.

**Comment by cornelinux** [comment]
We should do tokenspecific policies for HOTP and TOTP.

# Scope Enrollment

action: twostep_diff =
action: twostep_client =
action: twostep_server =

# Scope User and Admin


action: two_step: [allow, force, none]

Could look like this:

<pre>
SCOPE.USER: {
                       'two_step': {
                           'type': 'str',
                           'value': ["allow", "force", "none"],
                           'desc': _('Enable two-step token enrollment via the privacyIDEA '
                                     'authenticator app.')},
                       'hotp_hashlib': {'type': 'str',
                                        'value': ["sha1",
                                                  "sha256",
                                                  "sha512"],
                                        'desc': desc_self1},
                       'hotp_otplen': {'type': 'int',
                                       'value': [6, 8],
                                       'desc': desc_self2},
                       'hotp_force_server_generate': {'type': 'bool',
                                                      'desc': _("Force the key to "
                                                                "be generated on "
                                                                "the server.")}
                   }
</pre>

If set to `'None``,  the checkbox would not be displayed in the UI enrollment dialog.
Also: if set to None the 2step parameters must be deleted from the API call.

**Comment by fredreichbier** [comment]
Hm, or do we want to keep the ``TWOSTEP_SERVERSIZE``, ``TWOSTEP_CLIENTSIZE`` and ``TWOSTEP_DIFFICULTY`` actions in ``lib/policy.py``? Could it cause problems if we define them two times (once in the hotp token, once in the totp token)?

**Comment by cornelinux** [comment]
We will have two policies:
``hotp_2step_server_size`` and ``totp_2step_server_size``.

From a modularity perspective I think this is fine. If we one day have another tokentype like *smartcard* this might also be enrolled in two steps, but these steps may have different aspects and different parameters. Such a tokentype will not make use of a "serversize" but of quite different parameters.

So I am voting for putting these parameters into the hotp/totp tokenclass.

**Comment by fredreichbier** [comment]
Ah right, I forgot about the tokentype prefixes. I think separate parameters are fine then 😎

**Comment by fredreichbier** [comment]
I moved the 2step policies to the HOTP class in 80a2482 (will add them to TOTP once we have a final design here).

I'm not too happy with the ``twostep_enrollment`` function though -- it is really complex as it needs to handle both ``/token/init`` requests that occur during a two-step enrollment:
* We need the token type to fetch the correct policies. In the first request, the token type is supplied via the URL (and defaults to HOTP). In the second request, a serial is provided and we need to look up the type of the referenced token.
* In the first request, we need to pass ``2stepinit`` in ``request.all_data``. In the second request, we need to remove it from ``request.all_data`` (because ``TokenClass.update`` crashes otherwise).
* It also needs to differentiate between the admin and the user role (and I'm not sure if I got this correctly) in order to fetch the correct policy.
... maybe we can find a way to make the function more understandable.

I also have some open questions which I added as TODOs to the code.

**Comment by fredreichbier** [comment]
Open questions:

* What algorithm to use?
  * PBKDF2
    * (+) proper key derivation function, key + salt size can be chosen, 
    * (-) can be implemented pretty easily with GPUs, ASICs, ...
  * bcrypt.  
    * (+) not suitable for GPUs
    * (-) not primarily a key derivation function, fixed key size of 184 bit, fixed client component size of 128 bit, server component only considered up to first NULL byte, limit for server component (can be mitigated by hashing the server component)
* How to transport parameters in QR code url?

**Comment by cornelinux** [comment]
In a first step we will use pbkdf2, since this is another use case then password hashing.

**Comment by fredreichbier** [comment]
@nilsbehlen and I noticed a problem with base32 padding:
base32 encodes groups of 5 bytes into 8 characters. Padding is added if the input length is not divisible by 5:
e.g. suppose 4 bytes checksum + 12 bytes client part (= 16 bytes)
```python
>>> b32encode('='*16)
'HU6T2PJ5HU6T2PJ5HU6T2PJ5HU======'
```
It's probably not nice if the user has to enter six `=` characters. Two ways to mitigate this:
* Strip the `=` before displaying them to the user. As we know on the server side how many bytes we expect, we can re-add the `=` characters before b32decoding.
* Choose the checksum + phone part length such that their sum is divisible by 5 (at the cost of flexibility).

**Comment by cornelinux** [comment]
I recommend stripping the "=" and readding them before decoding on the server side.

**Comment by fredreichbier** [comment]
We will add a new parameter ``otpkeyformat`` to ``/token/init``:
* Its default value is ``hex``
* Value ``base32check`` causes the passed ``otpkey`` to be interpreted in the format specified above

**Comment by fredreichbier** [comment]
The current state in PR #853 and the [797/2step-2](https://github.com/privacyidea/privacyidea/tree/797/2step-2) branch has the following open issues:

* Implement for TOTP
* Pick suitable default number of PBKDF2 rounds (10000 is too small)
* WebUI: Fix conflict between otpkey=... and 2stepinit=1
* Client-side (requires JS SHA1 and Base32) or server-side (requires API endpoint) checksum validation?
* We should add some documentation on the flow and the new otpkeyformat feature

**Comment by cornelinux** [comment]
# TODO

* TOTP
* User Input after 2nd step
* Validation of user input (API endpoint)

**Comment by fredreichbier** [comment]
I just noticed: We can force the server to generate the client secret!

```
$ http POST 'http://localhost:5000/token/init' authorization:$TOKEN 2stepinit=1                           
$ http POST 'http://localhost:5000/token/init' authorization:$TOKEN genkey=1 keysize=8 serial=OATH00019595
```

... should we forbid this?

**Comment by cornelinux** [comment]
Ah ok, the first request creates a token object with OATH00019595 and the second request recreates the token?

Would the second request recreate the server component and still wait for the client?

I think a request like 

    http POST token/init genkey=1 2step=1 serial=OATH1234

should regenerate the server part of this very token. But this is my thinking, which we need to discuss.

**Comment by fredreichbier** [comment]
Ah no, the token is not recreated. Rather, the second request works as follows: ``genkey=1`` and ``keysize=8`` tell the server to generate a random OTP key of 8 bytes. As the token's rollout state is ``clientwait``, the server interprets this very generated OTP key as the client secret and performs the second step of the 2step enrollment. We then obtain a fully enrolled token.

I agree that there should be a possibility to regenerate the server component without deleting the token.

**Comment by cornelinux** [comment]
What relevance has this with the Web UI workflow?

What are we missing besides the TOTP token?

**Comment by cornelinux** [comment]
I am just implementing 2step for totp

**Comment by cornelinux** [comment]
2step enrollment could be improved for many aspects but currently we use this working setup.
Enhancements might follow in future versions.
