### ISSUE TITLE
User will be successfully authenticated without OTP in case of two enrolled spass token

### ISSUE THREAD

**Issue by chgarling** [privacyidea/privacyidea#803]
Hi Cornelius,

I experienced a potentially bug, in case a user has two or more spass token assigned. I have a testuser with multiple hotp token assigned for testing purposes. Because of an existing event everytime a hotp is assigned, a spass token is assigned too. So he had 3 hotp and 3 spass token.

We found out that authentication without second factor succeeds in this case. If I reduce the assigned number of spass token two one, the OTP is required for authentication.

Actually I am running version 2.19.1.

Regards, Christian

**Comment by cornelinux** [comment]
How does your PIN policy look like? If the user provides the right PIN of the SPASS token, of course he can authenticate.

**Comment by chgarling** [comment]
Hi @cornelinux,
I have these policies:
- hotp and totp token are allowed from anywhere
- spass token are only allowed from certain ip addresses
- passthru is enabled for users without any token assigned, only allowed from certain ip addresses

Steps to reproduce:
1. no token is assigned to the user, passthru rule matches, login from foreign networks are disallowed
2. hotp token is assigned, login from foreign networks succeeds with second factor, but not without
3. one spass token is assigned, login from foreign networks succeeds with second factor, but not without
4. a second spass token is assigned, login from foreign networks succeeds with and without second factor

**Comment by cornelinux** [comment]
I think this is the way the system is designed. there might be a misunderstanding and we should take a look at your policies.

**Comment by cornelinux** [comment]
fixed in 2f1357412f9bfeae8e7e0c8a9e54175960e7d87d
