### ISSUE TITLE
Can not scroll

### ISSUE THREAD

**Issue by admover** [privacyidea/privacyidea#806]
# What did you try to do?

In /token/details page, I can not scroll it.

# What outcome did you expect?

scroll 

# What outcome did you experience?

no scroll

# Configuration

* privacyIDEA Version: 2.20

* Installation method: Yum
  (from source, github, virtualenv, ubuntu packages...)

## more details: 

* OS: CentOS7

* Webserver: apache

* Tokendatabase: (like MySQL, PostgreSQL, ...) Mysql

# Log file

**Turn on debug level and take a look at the privacyidea.log!**
**If appropriate, attach the log file.**

**Comment by cornelinux** [comment]
To my under

**Comment by cornelinux** [comment]
Is fixed in 2.20.1

**Comment by admover** [comment]
In 2.20.1, I still can not scroll

**Comment by cornelinux** [comment]
You are right. I was wrong. The commit https://github.com/privacyidea/privacyidea/commit/ea11bc86b07eda031c4ecd733860bc5b2fe61514 fixes it.

It happended when navigating to "token" tab.
Well, this does not seem to happen, if there is a subscription file present. bummer.
