### ISSUE TITLE
Create TOTP Token via REST and move to other REALM

### ISSUE THREAD

**Issue by m7four** [privacyidea/privacyidea#809]
Hello,

we have dealt with the registration key and wanted to make the registration via an extra realm. After the user has registered, a TOTP token should be created, which is moved to another REALM!
We were found in events! We have created an event that responds to token_init, and assigns another realm to the token!

`
Event: [ "token_init" ] 
Handlermodule: Token
Condition: {"realm":"registration","token_has_owner":"True","tokentype":"totp"} 
Action: set tokenrealm
Option: { "description": "", "only_realm": "1", "realm": "it-schmid" } 
`

This didn't work correctly, however, an additional realm was always entered.
In the token overview, but then no user was recognizable only the ID of the user!

We were able to fix the problem by looking at the source code and adding or changing the following in privacyidea/lib/eventhandler/tokenhandler.py with it!

We have changed line 245 from 

`only_realm = handler_options.get("only_realm")`

to:

`only_realm = not bool(eval(handler_options.get("only_realm")))`

the variable "only_realm" was not used anywhere else

then we changed line 250 from

`set_realms(serial, [realm], add=True)`

to 

`set_realms(serial, [realm], add=only_realm)`

and used the variable only_realm with it

We are not sure if this is in the sense of the inventor, but then it worked correctly from our point of view.

We are currently using the current 2.20!

**Comment by cornelinux** [comment]
Sounds good to me.
I would change the naming a bit:

    only_realm = bool(handler_options.get("only_realm"))

The the variable name reflects what is in it.

Then:

    set_realms(serial, [realm], add=not only_realm)

Thanks a lot for bringing this up!
Do you want to do a pull request?

**Comment by cornelinux** [comment]
This was fixed in 54ce28a3d0a68b5dba0c843903263888e422c679
