### ISSUE TITLE
Deleting nonexistent event results in error 500

### ISSUE THREAD

**Issue by michalmedvecky** [privacyidea/privacyidea#817]
# What did you try to do?

Delete nonexistent event using api throws error 500

`curl -H "PI-Authorization: redacted" -XDELETE https://otp.mydomain.com/event/259`

# What outcome did you expect?

200, or some reasonable code - no 500 Internal server error

# What outcome did you experience?

What did acutally happen?

```
{"jsonrpc": "2.0", "signature": "redacted", "detail": null, "version": "privacyIDEA 2.19", "result": {"status": false, "error": {"message": "'NoneType' object has no attribute 'delete'", "code": -500}}, "time": 1508967071.924255, "id": 1}
```

# Configuration

* privacyIDEA Version:

2.19

* Installation method:

github

**Comment by cornelinux** [comment]
I am sorry. This is reasonable. The server was supposed to perform a task, that resulted in an internal exception.

This is a feature, that the server in the REST API responds with different HTTP Codes.

**Comment by michalmedvecky** [comment]
Well deleting for example non-existing token results in http error 200 (== OK) and reports "0" deleted tokens. 

HTTP error 500 literally means "Internal server error", I am not expecting any software reporting 500 under regular conditions. It always means something is broken.

**Comment by cornelinux** [comment]
Point taken in regards to deleting tokens.

But I see it a bit different in regards to "something is broken".

> 500: The server encountered an unexpected condition which prevented it from fulfilling the request.

http://www.restapitutorial.com/httpstatuscodes.html

We try to use the status code in a REST sensible way. And therefor we also return 40x and 50x errors.

**Comment by michalmedvecky** [comment]
Touché. I don't consider non-existent object, that is internal to remote software (PI) an unexpected condition. Unexpected condition would be uncatched/unknown error in DB connection, or reading/writing from/to backend storage or so.

**Comment by p53** [comment]
it should return 404

**Comment by fredreichbier** [comment]
I've submitted #1310 for review. This PR modifies the library level such that ``ResourceNotFoundError``s are thrown at a lot of locations, and the API translates these errors to HTTP 404 responses. This modifies API behavior at quite some places, especially for the ``/token/`` endpoints. But I think this should make the API more robust. I'm happy about any comments :-)
