### ISSUE TITLE
more sophisticated RADIUS forwarding

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#819]
The forwarding policy could be a bit more sophisticated like:

* Adding several RADIUS servers and doing a round robin.
* Configuring timeouts
* ... attributes? ...

**Comment by cornelinux** [comment]
See https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/radiusserver.py#L91
we could set ``retries`` and ``timeout`` of the radius client: http://pyrad.readthedocs.io/en/latest/api/client.html

We could also add additional AVPs to the AUth Request, (see http://pyrad.readthedocs.io/en/latest/api/packet.html#pyrad.packet.Packet.AddAttribute)
but there is currently no round robin.

**Comment by cornelinux** [comment]
To allow for round robin we could simply add a comma separated list in the RADIUS server definition.

**Comment by cornelinux** [comment]
The topics round robin and AVP need to be specified more deeply.
Round robin could be covered by pyrad.

**Comment by m4druga** [comment]
It would be nice that the PrivacyIdea could pass to the Radius Server the attributes User-Name and NAS-IP-Address with the same value that received from the client. Or have some way to manipulate the content that will be sent to the radius server with a policy like a outgoing mungle policy.

Client -> PrivacyIDEA

18:27:57.585430 IP (tos 0x0, ttl 64, id 26993, offset 0, flags [none], proto UDP (17), length 125)
    client.36323 > privacyidea.radius: [udp sum ok] RADIUS, length: 97
    Access-Request (1), id: 0x7f, Authenticator: 9bfd1c791d74183462d69c165e400def
      User-Name Attribute (1), length: 29, Value: user@realm
      User-Password Attribute (2), length: 18, Value:
      NAS-IP-Address Attribute (4), length: 6, Value: 192.168.1.12
      NAS-Port Attribute (5), length: 6, Value: 0
      Message-Authenticator Attribute (80), length: 18, Value: .G..l.)..(.4....


PrivacyIDEA -> RADIUS Server

18:48:41.152259 IP (tos 0x0, ttl 64, id 17976, offset 0, flags [DF], proto UDP (17), length 96)
    privacyidea.60576 > radius_server.radius: [bad udp cksum 0x1fb8 -> 0x62b2!] RADIUS, length: 68
    Access-Request (1), id: 0x03, Authenticator: ca58769b86d53fb393c13dfd64db390d
      NAS-Identifier Attribute (32), length: 13, Value: privacyIDEA
      User-Name Attribute (1), length: 17, Value: user@realm
      User-Password Attribute (2), length: 18, Value:
      NAS-IP-Address Attribute (4), length: 6, Value: 192.168.1.12

**Comment by cornelinux** [comment]
Actually the flow is different, this is why we might not understand each other in the first place!

Client -> FreeRADIUS -> privacyIDEA -> old RADIUS

So privacyIDEA can not *see* any RADIUS attributes!
privacyIDEA only sees the HTTP request it receives from the rlm perl module.
This can however contain a "client" attribute, which would be the NAS-IP-Address
(see https://github.com/privacyidea/FreeRADIUS/blob/f5d2e0f8637c6d233a9a4fd97f1ad666d340b75b/privacyidea_radius.pm#L328)

Which *realm* should privacyIDEA forward to the *old RADIUS*?
If could only be the realm, which gets involved in privacyIDEA itself, since it does not know of the FreeRADIUS realm. It can be the same named realm, but it could also be another one.

So if we forward the *realm* to the *old RADIUS* you have to take care in FreeRADIUS and privacyIDEA that it has the same name as the realm in the *old RADIUS*.

Please comment on the realm!

**Comment by m4druga** [comment]
You are right! The realm must be the same name in FreeRADIUS, privacyIDEA and in the old RADIUS if the PrivacyIdea just forward the same content to the old RADIUS. it will work for us. 
For something more sophisticated I thinket in an outgoing mungle policy.

**Comment by cornelinux** [comment]
Closing in favour of #2587 and #2588
