### ISSUE TITLE
Investigate scrollbar in WebUI

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#823]
We need to rework the scrollbar in the WebUI.

In the login window, we have a scrollbar, although it would not be necessary.

Also in several dialogs after submitting the view does not scroll up. (Also due to the fact that the scrollbar is too large/long).

**Comment by fredreichbier** [comment]
Also, I still have the problem that scrolling is impossible sometimes (but the problem disappears if I add the ``hide_welcome`` policy)

**Comment by cornelinux** [comment]
Please try to note, when it happens,

* from which page
* change to what page

**Comment by fredreichbier** [comment]
I reproduced it as follows:
* log in
* click through the welcome dialog, ending with a click on "Dive in!"
* click Users tab, click on a user
* click "Enroll new token"
* I cannot scroll in the resulting token enrollment dialog

If I add the ``hide_welcome`` policy, this does not happen anymore.
Interestingly, I have to open a new browser window after adding the policy -- if I just log out and in again in the same browser window, the above effect still happens.

**Comment by cornelinux** [comment]
The over-long vertial scrollbar obviously happens due to the hidden about dialog and other dialogs.

**Comment by cornelinux** [comment]
For some strange reason the classes ``html.ng-scope`` and ``body.ng-scope`` are set to a fixed height of 2000 pixels... :-(
