### ISSUE TITLE
Update angular.js

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#830]
We should update angular.js.
If we update e.g. to 1.6.6 we need at least:

* update angular.js
* update in static/contrib/js/ngmodules/ 
  * angular-animate.js
  * angular-resource.js
  * angular-route.js
  * angular-ui-router.js

The ``$http.get`` and ``.post`` do not support ``.success()`` anymore. Now it is called ``.then()``.

And there might be a lot other changes.

**Comment by plettich** [comment]
TODO:
- [ ] update `READ_BEFORE_UPDATE.md` for possible changes in templates.

**Comment by plettich** [comment]
The update of the angular-ui-router package broke the reload button and the return to the token list after deleting a token.
The [`$stateChangeSuccess`](https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events) event is replaced by transition hooks.

**Comment by plettich** [comment]
I think we covered all the issues here regarding the update of the UI components. I'll close this now and if something doesn't work, we can open a new issue to work on that.
