### ISSUE TITLE
Rotating of audit log based on multiple conditions

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#833]
Dear developers.
We like the tendency in improving audit logging and the rotate feature.
I'd like to propose the idea for further improvement if you decide it is rational.

I read the issue about the rotate introduction https://github.com/privacyidea/privacyidea/issues/780

The way rotate configuration is described there is:
~~~yaml
- ("POST /token/init.*", 3650) # Save creation and deletion of tokens for 10 years
- ("DELETE /token/.*", 3650) 
- ("POST /validate.*", 1825) # Save authentication REQUESTS for 5 years
- ("GET /validate.*", 1825) # Save authentication REQUESTS for 5 years
- ("POST .*", 720) # Save all POST Reqeusts for 25 months
- ("DELETE .*", 1825) # Save all DELETE Requests for 5 years
- ("GET .*", 30)  # only save GET requests for 30 years
- (".*", 182) # Everything else for half a year
~~~

And here is the idea:
I’d do the YAML as a list of dictionaries instead of list of lists..
It’s just personal opinion, for me this would look and read nicer:
~~~yaml
---
- find: POST /token/init.*
  rotate: 3650
- find: DELETE /token/.*
  rotate: 3650
- find: POST /validate.*
  rotate: 1825
- find: GET /validate.*
  rotate: 1825
- find: POST .*
  rotate: 750
- find: DELETE .*
  rotate: 1825
- find: GET .*
  rotate: 30
- find: .*
  rotate: 180
~~~
…or similar…

Also how do you think, someone else would need to search and rotate based on username as well?
For example I’d rotate records for username “monitoring-account” and action “POST /validate/check” just within 7d period because it’s monitoring system and here’s a lot of such logs..
We could even add another fields to match.
In that case YAML could look like this:
~~~yaml
---
- find:
    action: POST /validate/check
    user: monitoring-account
    rotate: 7
- find: 
    action: POST /token/init
    rotate: 0 # don't rotate
- find: 
    action: POST /validate/check
    resolver: otp-users
    rotate: 1825
~~~
with variable amount of keys, but at least one should be specified. Multiple fields should be matched as logical AND

The var names, structure and everything else is obviously a subject for adjustments and change.,.

**Comment by cornelinux** [comment]
Thanks a lot. This is the privacyIDEA mind set to achieve the highest flexibility.

We should try to keep up the backward compatibility and allow the old list of lists and a new list of dicts.

**Comment by kolosovski** [comment]
> We should try to keep up the backward compatibility and allow the old list of lists and a new list of dicts.
This meant to act like improvement before the release of the old list of lists and before anyone knows about it and start using.  Probably making them both operational somehow is quite over-complicated and late to implement.

**Comment by cornelinux** [comment]
Oh, you are right! pi-manage rotate with the ``--config yaml`` option is not part of 2.20 release. Great, so you are right, we can simply switch the file format... :-)
Thanks for the note!

**Comment by cornelinux** [comment]
@kolosovski  We could drop the binding to action and simply filter for all sql columns. The only preserved keyword would be ``rotate``.

~~~yaml
- administrator: super
  rotate: 7
~~~
would rotate entries of the administrator *super* within 7 days.

~~~yaml
- action: "% /validate/%"
  client: 127.0.0.1
  rotate: 7
- action: "% /validate/%"
  user: nagiosuser
  rotate: 1
- action: "% /validate/%"
  rotate: 30
~~~
would delete all validate requests from localhost older than 7 days and all other validate requests older than 30 days. The entries of the user *nagiosuser* would only be kept for one day.

I like this approach, this is extremely easy and straighforward in the implementation.

Unfortunately the problem with this approach is, that you can not have a *catch-all* rule, which rotates everything else.
If you would add a rule at the bottom

~~~yaml
- action: "% /validate/%"
  client: 127.0.0.1
  rotate: 7
- action: "% /validate/%"
  user: nagiosuser
  rotate: 1
- action: "% /validate/%"
  rotate: 30
- rotate: 2
~~~

This would in the end delete **all** entries that are older than 2 days. (The problem arises, that with the previous approach with binding to the ``action`` we had an outer action-loop, which we can break as soon as we found a matching rule. In this approach we have no outer loop, which we can break)

The question is, if we need a *catch-all*. In this approach the ordering of the rules is not relevant.

**Comment by cornelinux** [comment]
note to myself: Working on local branch 833/rotate

**Comment by kolosovski** [comment]
Yes, indeed, this is very interesting question..
having this approach
~~~
- action: "% /validate/%"
  client: 127.0.0.1
  rotate: 7
- action: "% /validate/%"
  user: nagiosuser
  rotate: 1
- action: "% /validate/%"
  rotate: 30
~~~
we just iterate through this list and make db query to remove rows _where action like ... and user like ..._
So if we had in the list an item with only rotate key 
~~~
- rotate: 2
~~~
it would wipe out wipe out all the logs which are older that 2d.

and also if you'd have such config:
~~~
- action: "% /validate/%"
  user: nagiosuser
  rotate: 30
- action: "% /validate/%"
  rotate: 7
~~~
the system would keep only 7d logs for ALL the  /validate/ calls despite you specified that you want to leave 30d of /validate calls by nagiosuser.

So idk if it's even technically feasible. Because if we want have ACL-like behavior - check each log item against the config and exit first match, we need to iterate the whole audit log for comparing each entry with each of the config list item and this is probably too expensive and irrational resource-wise.

**Comment by cornelinux** [comment]
I Think the problem arises because we define, what we want to delete an not what we want to keep.

Need to do more thinking.

**Comment by cornelinux** [comment]
**I think from a logical point of view what we really want is.**

We have a ruleset, which might look like this:

~~~yaml
- action: "% /validate/%"
  client: 127.0.0.1
  rotate: 7
- action: "% /validate/%"
  user: nagiosuser
  rotate: 2
- action: "% /validate/%"
  rotate: 1
- action: "%%"
  rotate: 2
~~~
We would take a look at the first audit entry and find the first matching rule in the ruleset.

The request from user ``nagiosuser`` matches the second rule and would be deleted after 2 days. No matter of being deleted or not the logic would bail out of the ruleset and we would investigate the next audit entry.

The next audit entry could be a request from localhost and would only be deleted, if older than 7 days - it matches the first rule in the ruleset. Bail out.

Go to the next audit entry would be  some other validate/check request and be deleted after one day - matches 3rd rule.

The next audit entry would be anything else and would match the last rule. It would be deleted after 2 days.

So the preferred logic would be to evaluate each audit entry in regards to the ruleset. @kolosovski: please confirm!

As a result we indeed would have to interate through the audit entries to decide on each audit entry, if it should be deleted. 
Which would result in a lot of single SQL delete commands.

**Comment by cornelinux** [comment]
I just implemented a draft.

This. Is. So. Slow. :-(
