### ISSUE TITLE
Catch 50x HTTP errors in webui and display an error message accordingly to the user

### ISSUE THREAD

**Issue by michalmedvecky** [privacyidea/privacyidea#836]
# What did you try to do?

Log in to PI using password+SMS token with incorrectly configured gateway.

# What outcome did you expect?

Message the user that login failed or something went wrong.

# What outcome did you experience?

After a while of spinning the wheel, PI falls back to login screen.

# Configuration

* privacyIDEA Version: 2.19

* Installation method: github

**Comment by cornelinux** [comment]
So you are trying to login with challenge response and you are issuing the OTP pin at the first step?

Can you please tell, how the response looks like?
Open Developer Mode in your browser and take a look at the network traffic.

Thanks a lot

**Comment by michalmedvecky** [comment]
I just:

- enter username and password (no pin involved)
- submit
- I expect sms token entry dialog to be opened, but the wheel only spins and then returns to original login window (with no extra message)

What kind of traffic do you need for issue replication?

**Comment by cornelinux** [comment]
You are entering the password - so you have a policy ``otppin=userstore``?

I think this is ok. I will be able to configure a faulty SMS config ;-)

**Comment by cornelinux** [comment]
Hm, I am doing an SMS token and get wrong credentials.

Can you please take a look at the ``/auth`` request and tell me the response.

**Comment by michalmedvecky** [comment]
This is what I get:

<img width="933" alt="screen shot 2017-11-01 at 17 58 34" src="https://user-images.githubusercontent.com/12493312/32286664-80ebac1a-bf2e-11e7-9d40-a1644e643516.png">

**Comment by michalmedvecky** [comment]
Just to clarify, by "wrongly configured" I mean #835 

You can use correctly configured sms gateway but filter out the connectivity to it (`-j DROP`).

**Comment by cornelinux** [comment]
Are you running nginx? You get no response? 

Then you should adapt your timeout of the sms gateway to meet your nginx config.

**Comment by michalmedvecky** [comment]
I'm running apache. `TIMEOUT` to sms gateway is set to `2` and nothing changed.

**Comment by cornelinux** [comment]
THanks! So I guess we simply need to cathc the 504. Thus this seems to be a generic problem.
I will change the topic of this issue accordingly

**Comment by michalmedvecky** [comment]
Yeah, I think the TIMEOUT parameter is ignored. See https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/smsprovider/HttpSMSProvider.py#L111-L121 - there is no timeout parameter to `requests.post`

**Comment by cornelinux** [comment]
...intersting. Who wrote this?,-)

**Comment by michalmedvecky** [comment]
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/smsprovider/HttpSMSProvider.py#L6-L17

**Comment by cornelinux** [comment]
...need to talk to this guy.

**Comment by michalmedvecky** [comment]
Try e-mailing him ...  :-p

**Comment by cornelinux** [comment]
...look at that!
Can you see, if this fits your needs?

**Comment by michalmedvecky** [comment]
yeah, now shows `Authentication failed. Wrong credentials`. Not sure about the default value of `3` but that's up to you

**Comment by plettich** [comment]
I would say this one is fixed. Closing it.
