### ISSUE TITLE
Offline Refill

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#839]
The client should try to refill its OTP offline database while there are still hashed OTP values left. 

After successful local authentication  the client can contact privacyidea with *necessary* information.
Privacyidea can respond with a failed authentication request but also return new hashed OTP values.

**Comment by cornelinux** [comment]
# Contact privacyIDEA

the client could contact privacyidea via the usual ``/validate/check`` endpoint. This might increase the complete logic of the validate check request.
We could also introduce a new endpoint like ``/validate/offlinerefill``. The client simply **knows**, that it needs to call this endpoint after a successful local authentication.

# Necessary information

The client could pass this necessary information:

1. The password, which the user entered, potentielly being ``OTP PIN + OTP VALUE``.
    This way privacyIDEA gets the password of the user, to salt and hash the new OTP values and
    it gets an old OTP value, which it can check in the past.

2. An **authorizaton token**, that was handed by privacyIDEA to the client earlier.
    The old OTP value and the password could also be captured by a shoulder surfer.
    So we need to pass an additional component, which is no knowledge. It is not known to the user
    and it was never typed in the keyboard. So a shoulder surfer can not know this component.

3. serial number of the token.

## Authorization token

The authorization token could be refereshed on each refill request. It could consist of:

* The last counter of the handed OTP value
* The username
* The password
* A salt
* The tokens secret key.

E.g. we could use the 

    HMAC-SHAx(secret-key, last counter + username + password + salt)

**Comment by cornelinux** [comment]
![offline-refill](https://user-images.githubusercontent.com/1908620/34114968-7d127500-e414-11e7-8007-b17995c65582.png)

**Comment by renini** [comment]
:+1:

**Comment by cornelinux** [comment]
The authorization token for refill should not be stored in plain text in the privacyIDEA server database.

We can save "salt" in the unencrypted tokeninfo field, but we need to incorporate the secret key of the token.

    import hashlib, binascii
    binascii.hexlify(hashlib.pbkdf2_hmac('sha512', 'otpseed', 'salt-from-tokeninfo', 100000))

Alternatively we can simply create a random string as authorization token and save it encrypted in the tokeninfo field. (I think I prefer this one)

**Comment by cornelinux** [comment]
# API

From a matter of REST aspect we might add the endpoint ``/validate/offlinerefill`` as GET request. 
But this might expose the parameters in the URI in the log file.

## Parameters

``password`` this is the current password that the user entered.

``refilltoken`` this is the authorization token, that was sent in the initial request. 

``serial`` this is the serial number of the token.

## Response

It will respond with

* the list of **hashed OTP values**, that the client again will save to the local database.

* a new **refilltoken**, that the client will also save in the database.

## Encryption

We could encrypt the refill token with each password.

So the client would have a list of

1. counter
2. hashed(password / otp)
3. refill token encrypted with (password /otp)

Thus is the user enters password/otp the client can 
1. hash it an compare
2. use it to decrypt the refilltoken

# Library
