### ISSUE TITLE
"add_user_in_response" doesn’t work with postgresql resolver

### ISSUE THREAD

**Issue by m4druga** [privacyidea/privacyidea#848]
The API REST output does not list the mapped attributes of the users when the resolver is postgresql. I tested with ldap, sqlite and mysql, only with postgres does not work.

Postgresql Schema:

```
create table users (
id serial PRIMARY KEY, 
user_login varchar(60), 
user_pass varchar(128), 
arbor varchar(20));
```

Resolver mapping:
````
{ "userid" : "id", "username" : "user_login", "password" : "user_pass", "arbor" : "arbor" }
````
REST API out:
````
jsonrpc | "2.0"
-- | --
signature | "7731616632463479464438912734206489137269171492031946760431270678919323976990618588172584678253601009142107212313084745155142283022286181338985456761821854436305348797114188589692220434179469993439182513647564104800557802916574349009914369001470007578317916071218684532691662045079133412717235923891656098636476825506037869755082999408770628476802134391164649788811479034054230128392597140684664270563982619022326495760095704404000533715667939335160804241791386991515239115179679838121822529853751321074093533196924265468013271496071945782270080234764913289514949224236097467480119943329271711635384532687905040065603"
detail |  
user |  
password | ""
threadid | 140287596562304
message | "matching 1 tokens"
type | "remote"
serial | "PIRE0003FA58"
otplen | 6
versionnumber | "unknown"
version | "privacyIDEA unknown"
result |  
status | true
value | true
time | 1510680002.638309
id | 1
````

**Comment by cornelinux** [comment]
Please specify you resolver, especially the postgres driver you are using!

**Comment by m4druga** [comment]
I'm using psycopg2 == 2.6. I configured the resolver and I can edit the user attributes and add new users, but this information is not displayed in the REST API output.

![captura de tela de 2017-11-16 11-56-04](https://user-images.githubusercontent.com/8932000/32900150-ec9a7c10-cad3-11e7-8b7d-ee4f7edcd67e.png)
![captura de tela de 2017-11-16 11-55-21](https://user-images.githubusercontent.com/8932000/32900151-ecb7781a-cad3-11e7-9b19-11963f05f077.png)

**Comment by m4druga** [comment]
Error Log: [2017-11-16 16:04:17,937][11193][140372112050048][ERROR][privacyidea.lib.resolvers.SQLIdResolver:204] Could not get the userinformation: ProgrammingError("(psycopg2.ProgrammingError) operator does not exist: bigint ~~ unknown\nLINE 3: WHERE users.id LIKE '1'\n                       ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.\n",)

**Comment by m4druga** [comment]
https://github.com/privacyidea/privacyidea/pull/851

**Comment by cornelinux** [comment]
First I was thinking about catching the exception and trying a second conditions that does not use ``like`` but use ``==`` instead. But wait: Does your user database have any other unique column?

Maybe you can simply choose another UID, to work around this problem?
