### ISSUE TITLE
Firefox 57: U2F token not recognized?

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#860]
# What did you try to do?

I'm running Privacyidea on Ubuntu 16.04 and have registered multiple U2F tokens.
With Firefox < 57 and Chromium I can use my U2F tokens to authenticate in the
privacyidea WebUI.

After upgrading to Firefox 57 I still get asked to press the button on my yubikey,
but the key is not blinking. 

If I try to register a new U2F key, I get a request to insert the key/press the button,
but no blinking led on the yubikey.

I used the U2F addon in Firefox < 57, but that doesn't work anymore.
I have the following configuration:

security.webauth.u2f;true
security.webauth.webauthn;true
security.webauth.webauthn_enable_softtoken;false
security.webauth.webauthn_enable_usbtoken;true

According to  https://bugzilla.mozilla.org/show_bug.cgi?id=1065729 it should work,
but I guess we miss something. Yubico' testpage workes for me.

* privacyIDEA Version: 2.20.1 from PPA

* Webserver: Apache

* Tokendatabase: MySQL

# Log file
There are no errors in privacyidea.log.

**Comment by cornelinux** [comment]
We can check, which javascript library the yuibco test page uses.

Can you see any errors in the browser console?

**Comment by jh23453** [comment]
The yubico testpage is https://demo.yubico.com/u2f

They are using https://demo.yubico.com/js/u2f-api.js, which seems to be newer than what we are using.

I've tried replacing privacyidea's u2f-api.js, but no success.
I've seen no errors in the Firefox console.

So, I still don't have an idea where to look further.

**Comment by jh23453** [comment]
In https://www.yubico.com/2017/11/how-to-navigate-fido-u2f-in-firefox-quantum/ there is a hint, that something in the firefox implementation is incomplete:

> For example, Mozilla did not fully implement the FIDO AppID and Facet Specification. Some sites supporting FIDO U2F have made accommodations for the incompleteness of Firefox’s implementation, but some have not.

I have't seen more details :-(

**Comment by cornelinux** [comment]
Unfortunately I can only confirm, that it does not work with firefox quantum version 58.
I even get some console errors from u2f-api.js. But these might also be due to some add ons.

Referring to the article by Yubico - I would be very unhappy working around the AppId/Facets functionality.
