### ISSUE TITLE
UUIDs instead of Strings for userid and username

### ISSUE THREAD

**Issue by dergraf** [privacyidea/privacyidea#862]
# What did you try to do?

I want to setup the SQLResolver to resolve `userid` and `username` which are Postgres UUID instead of the required VARCHAR type.
The SqlAlchemy `.like` syntax used throughout the `SQLIdResolver.py` code obviously doesn't work well with UUIDs. 
I got it working to some extent by patching up those `.like`s with ` == ` but I'd prefer a more general solution.
Moreover it looks like the size of UUIDs doesn't play nicely with the `VARCHAR(20)` in the audit log. 

# Configuration

* privacyIDEA Version: 2.20.1

* Installation method: pip (inside docker)

## more details: 

* OS: Debian Jessie (Dockerized)

* Webserver: uwsgi

* Tokendatabase: PostgreSQL

Do you have a simple solution for this, or should we think about changing the SQLIdResolver?

**Comment by dergraf** [comment]
I also tried to use an SQL View which returns type-casted rows, but SQLAlchemy complained about the non-existing Primary Key on the View. Otherwise such a solution would work for me!

**Comment by cornelinux** [comment]
I think there is no simple solution.
Which postgres driver are you using?

**Comment by dergraf** [comment]
Driver is Psycopg2
Postgres 9.10
