### ISSUE TITLE
CheckSubscription: LDAP Proxy is recognized as privacyIDEA

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#872]
The LDAP proxy sends a ``User-Agent: privacyIDEA LDAP Proxy`` header. As privacyIDEA splits only processes ``ua_str.split()[0]`` ([see here](https://github.com/privacyidea/privacyidea/blob/bea29ae3c64effd04ac1a123312f02f6191dc8df/privacyidea/lib/subscriptions.py#L326)), the LDAP Proxy is treated as if it were privacyIDEA core:
```bash
╰─$ http --verify=no 'https://pxprivacyidea.local/validate/check' user=user111 pass=pin111 User-Agent:"privacyIDEA LDAP Proxy"
HTTP/1.1 500 INTERNAL SERVER ERROR
Connection: close
Content-Length: 887
Content-Type: application/json
Date: Thu, 14 Dec 2017 14:38:23 GMT
Server: Apache/2.4.18 (Ubuntu)

{
    "detail": null,
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "error": {
            "code": -500,
            "message": "SubscriptionError('No subscription for your client.', application=privacyIDEA)"
        },
        "status": false
    },
    "signature": "21794682275716348537594155850695014832427901722945126177032362187632056908312652472104723768992108955992436339054040096818722514224688210463178763241995762289300165631645869950763038798897247255496674397237692399472921363282236199714147936587678393916263182431269812606018185072337812708861950102983641837072644355092172246250338543454409538627560972773437278312842036657481952629092256559425259961983305385206514076272560974400432195509752258587705952654094734626958905640198847858347780107652162117620448213664098072068560647285080157022608032163725458060617125792872654997628709315369867530852922178210046256165852",
    "time": 1513262303.403338,
    "version": "privacyIDEA 2.21.dev2"
}
```

Note that ``SubscriptionError('No subscription for your client.', application=privacyIDEA)`` tells us that privacyIDEA checks the token numbers for the  ``privacyIDEA`` application, not ``privacyIDEA LDAP Proxy``.

We could resolve this by processing the whole user agent (i.e. not splitting it) or by changing the LDAP proxy user agent to something like ``privacyIDEA-LDAP-Proxy``.

**Comment by cornelinux** [comment]
I think we should change it to ``privacyIDEA-LDAP-Proxy``. Otherwise we will run into other problems.
Need to change it here 
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/subscriptions.py#L68
and here
https://github.com/NetKnights-GmbH/privacyidea-ldap-proxy/blob/master/pi_ldapproxy/proxy.py#L63

**Comment by cornelinux** [comment]
@fredreichbier please change this in the ldap proxy ;-)
