### ISSUE TITLE
New SMPP SMS provider

### ISSUE THREAD

**Issue by yurlov-alexander** [privacyidea/privacyidea#878]
# Why SMPP SMS provider is necessary for me?

I need to send SMS via own sms center. I can use chain http provider + http-smpp gate (kannel), but it is not easy, service depend from additional daemon .

# Solution

I develop my own SMS provider, it works for me. I think, sharing it may be useful.

# Requirements

SMS provider requires **smpplib**, so you need install it via pip

Regards,
Alexander

**Comment by cornelinux** [comment]
I am not sure if we should use ``smpplib`` or ``smpplib2``. All smpp code is realy old. It might be no problem, since it is only wrapper code. But nevertheless it feels a bit awkward.

I created a feature-branch 878/smpp_provider.

**Comment by fredreichbier** [comment]
Thank you @yurlov-alexander for your contribution!
I had a look at the feature branch: In the long run, we need to think about the handling of non-ASCII messages. Right now, the SMPP provider breaks in that case, even though SMPP seems to have *some* support for Unicode (i.e. UCS2)?
