### ISSUE TITLE
Granular access controller for admin accounts.

### ISSUE THREAD

**Issue by justin-p** [privacyidea/privacyidea#883]
granular access controller for admins accounts would be great.

In our case, the first line support/service desk should probably never need to touch any of the settings under 'config'. An account that is just limited to enroll and delete tokens would be ideal in our situation, as of right now I don't see a way to configure this.

**Comment by cornelinux** [comment]
http://privacyidea.readthedocs.io

This is even now more granular than you would imagine.
If you have any further question stop by at https://community.privacyidea.org

If you are unclear about anything you can also get consultancy and an SLA from NetKnights https://netknights.it.

**Comment by justin-p** [comment]
Hi,
Yeah, I should have RTFM. Got everything setup.
