### ISSUE TITLE
LDAP Resolver: STARTTLS fails with PyASN1 error

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#885]
I'm using privacyIDEA d006f7edbb35c686d530d03a258e75f1a7553c8e. Setting up a LDAP Resolver connecting to AD with STARTTLS, "Test Connection" displays the following error:
```
PyAsn1Error('Attempted "__nonzero__" operation on ASN.1 schema object',)
```
Doesn't matter whether I check "Verify TLS" or not.

Interestingly, the exact same configuration works perfectly on my privacyIDEA 2.21 on Ubuntu. This seems to be related to the pyasn1 version: Locally, I'm running pyasn1 0.4.2. On Ubuntu, I have python-pyasn1 0.1.9 installed. If I manually downgrade my pyasn1 to 0.1.9 locally, the exact same configuration works.

So, this is probably no issue for our Debian-based deployments, but our virtualenv-based deployments might have this problem.

**Comment by fredreichbier** [comment]
Reading [this comment](https://github.com/etingof/pyasn1/issues/111#issuecomment-346872713), it seems like our ``requirements.txt`` provokes an unholy combination of a too-new pyasn1 and a too-old ldap3. Indeed, our requirements.txt installs ``ldap3==2.1.1``, whereas ldap3 2.4 was released in November and includes some pyasn1 fixes (according to the [changelog](http://ldap3.readthedocs.io/changelog.html)).

**Comment by cornelinux** [comment]
I would like to upgrade ldap3 to 2.4.
But we need to check if this would run with pyasn 0.1.9.

What do you think?

**Comment by fredreichbier** [comment]
Turns out this is unrelated to our TLS enhancements, I just reproduced this bug on 2.21 (locally). I *think* our 2.21 virtualenv installs have the same problem, but I still need to verify that.

According to the ldap3 changelog, ldap3 2.4 should support pyasn1 0.1.9, but I'll verify that as well :)

I think overall it would be nicer if we could pin specific versions in requirements.txt -- this would prevent things breaking without us noticing :)

**Comment by fredreichbier** [comment]
Our virtualenv-based 2.20.1 CentOS package does *not* have this problem because it runs ldap3 2.3:
```
(privacyidea)[fred@centos-pi privacyidea]$ rpm -q privacyidea-server
privacyidea-server-2.20.1-2.el7.centos.x86_64
(privacyidea)[fred@centos-pi privacyidea]$ pip freeze | grep -e pyasn1 -e ldap3
ldap3==2.3
pyasn1==0.3.7
```

**Comment by cornelinux** [comment]
as we spoke this only needs to be fixed in the ``requirments.txt``.

**Comment by cornelinux** [comment]
@fredreichbier  Look here:

https://github.com/cannatag/ldap3/issues/449
