### ISSUE TITLE
Add more user details in auth response

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#893]
The user-detail policy returns user details.

http://privacyidea.readthedocs.io/en/latest/policies/authorization.html#add-user-in-response

In addition to 

    "detail": {
        "user": {
            "username": "cornelius",
            "givenname": "Cornelius",
            "surname": "Kölbel",

we could add a further branch with the ``resolver``-name and ``realm``-name.

    "detail": {
        "user-resolver": <resolvername>,
        "user-realm": <realmname>

This could be triggered by the same policy.

@fredreichbier Or do you think we need an additional policy?

**Comment by fredreichbier** [comment]
Hmm yeah, spontaneously, I would think that implementing this via an additional policy would be more consistent?

**Comment by cornelinux** [comment]
Yes, there migh be scenarios, where we might to tell the ``user-resolver`` but we do not want to "disclose" the user's phone number... etc.

**Comment by cornelinux** [comment]
OK, I add an extra policy. This makes sense. But I would add the policy to the same decorator, since the policies ``ADD_USER`` and ``ADD_RESOLVER`` are always at the same place / always decorate the same function...

**Comment by cornelinux** [comment]
can be used with #896
