### ISSUE TITLE
Vasco Failcounter

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#899]
The vasco blob has its own internal failcounter.

We want to use the privacyIDEA own failcounter and not the vasco failcounter.
But the vasco blob failcounter could somehow make the otp verification fail. So we need to reset the vasco failcouter.

Authentication should fail, because the privacyIDEA failcounter is exceeded. The vasco failecounter should be ignored.

@fredreichbier I think we even should mark this as prio high. Because this might make authentication "suddenly" break.

**Comment by cornelinux** [comment]
The Vasco Failcounter can be accessed via:
ERROR_COUNT by AAL2GetTokenInfoEx or AAL2GetTokenProperty

**Comment by fredreichbier** [comment]
I think the Failcounter feature is disabled on the VASCO side, as we set the [IThreshold parameter to 0](https://github.com/privacyidea/privacyidea/pull/897/files#diff-a82505e9fa7eb94f6e1207e2a0babc15R168).

But we have one remaining problem on the privacyIDEA side: We write back a new OTP key at each authentication attempt, which (by default) resets the failcounter. Consequently, the privacyIDEA failcounter is currently useless, as it is at most 1.

**Comment by cornelinux** [comment]
I think this is ok
If otp authentication with a token is successful the failcounter is reset anyway. For every tokentype.

**Comment by cornelinux** [comment]
So we need to 
1. read the fail counter and save it to ``old_fail``
2. call the vasco auth, that also rewrites the otpkey (which internally resets the failcounter)
3. set the fail counter to ``old_fail`` if auth was not successfull

**Comment by fredreichbier** [comment]
@cornelinux What do you think about the solution here in 967c445189bd6667cac7e2a2103f7efcc323c72b?

**Comment by cornelinux** [comment]
This is the way to go. I was not aware of, that we have the parameter!

**Comment by cornelinux** [comment]
So we can close this issue?
