### ISSUE TITLE
Tokens serial in the admin-ui does not reflect the real VASCO serial

### ISSUE THREAD

**Issue by renini** [privacyidea/privacyidea#909]
First of all good work on the ability to import and verify against vasco tokens. 👍 

I did play around with the **Enroll a new token** feature and managed to import a Vasco token blob and verify OTP's to it succesfully. 

But from a managebility and administrative standpoint its not very usefull at the moment.
In most situations an admin would ask or check the physical (or virtual) serialnumbers of a token and assign or unassign that serialnumber to a user. 

But the serialnumber currently gets a ?**random**? serial prefixed by **VASC**. 

So for example i've imported 2 blobs, and they can be find in the gui as serial **VASC00003A02** and **VASC0001AA7D**. But the real serialnumbers are for example **VES0052649** and **1452400141** (10 characters). Making it near impossible to pinpoint to these exact tokens. Especially if there are a few thousand of them. 

Is it possible to change the serialnumber to something like **VA$RealVascoSerialNumber$** while importing the blobs? This would still make it a length of 12 chars that the field currently seems to use. 
Or if the field length is does not need to stick to 12 chars, **VASC$RealVascoSerialNumber$** will more identifying it as a VASCO token, making it 14 chars in total.

**Comment by renini** [comment]
This seems related to #901 as well

**Comment by cornelinux** [comment]
You are right. We use the generic admin UI enrollment which acutally creates a new serial number for all tokentypes. This is also reflected in the consistancy of the REST API.

But you are also right, that it *might* be nice to have read the serial number from the blob.

**BUT**: The currently consistant behaviour is, that enrolling a token from the UI will *create* a new token. If we read in this case the serial number from the blob, we would drop this consistant behaviour.  Enrolling a second vasco type token with the same blob, would overwrite the existing token, although the current consistant behaviour is, that a new token will be created.

I assume the UI enrollment only for testing purposes. Is it that important?
