### ISSUE TITLE
tune up migration script

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#914]
The migration script ``privacyidea-migrate-linotp.py`` runs slow for a big number of tokens.

We need to identify the problem (maybe due to tokeninfo, resolvers and realms) and speed it up.
@fredreichbier I would like to discuss this.

Things that can be done are:

1. Check if it is better to first **read** all information from the old database to a dictionary, before writing the new database.

1. add a parameter to simply ignore all tokeninfo or only migrate certain tokeninfo field.
    https://github.com/privacyidea/privacyidea/blob/master/tools/privacyidea-migrate-linotp.py#L200
    https://github.com/privacyidea/privacyidea/blob/master/tools/privacyidea-migrate-linotp.py#L227

1. skip resolver and realm definitions. In contrast we could configure resolvers and realms in the
   destination privacyIDEA server and add a mapping to the script, that maps old resolvers to new resolvers and old realm names to new realmnames.

**Comment by fredreichbier** [comment]
I had a quick look at the code and I think point (1) seems like a good a idea which can already bring a nice speedup. For example, if I read the code correctly, [this line](https://github.com/privacyidea/privacyidea/blob/master/tools/privacyidea-migrate-linotp.py#L225) executes an INSERT for every migrated token. We should probably aggregate the new tokens and bulk-insert them.

**Comment by cornelinux** [comment]
OK, the bulk operation seem to work with the ORM.
http://docs.sqlalchemy.org/en/rel_1_0/orm/persistence_techniques.html#bulk-operations

So we would have to rewrite from using the table statements like 

    token_table.insert.values()

to using the ORM with ``Token`` database classes.

    session.bulk_save_objects([Token(), Token(), Token()])

We still would need to check, how we could write tokeninfos for those token objects into the tokeninfo table.

**Comment by fredreichbier** [comment]
There might even be a way to get a similar effect without using the ORM by wrapping all token and token info INSERTs into one transaction. I can have a look into this later.

**Comment by fredreichbier** [comment]
[This example](http://docs.sqlalchemy.org/en/latest/faq/performance.html#i-m-inserting-400-000-rows-with-the-orm-and-it-s-really-slow) is probably interesting. There, they use:
```python
    engine.execute(
        Customer.__table__.insert(),
        [{"name": 'NAME ' + str(i)} for i in xrange(n)]
    )
```

**Comment by cornelinux** [comment]
Here is a mysqldump of 12.000 Tokens in the linotp token database. 

[linotp-token-table.txt](https://github.com/privacyidea/privacyidea/files/1706908/linotp-token-table.txt)

**Comment by cornelinux** [comment]
Some migration tests:

tokens | tokeninfo | realms | resolvers | time 
--- | --- | --- | --- | ---
| Y | N  | N | N | 40 secs | 
| Y | Y | N | N | 80 secs | 

The realm assignment of the tokens was not migrated, yet!

**Comment by cornelinux** [comment]
The problem is, we loose the assigement if we do NOT fill the table "tokenrealm".

**Comment by fredreichbier** [comment]
With a458207 applied, importing 12000 tokens (token + tokeninfo) goes down from 30s to 2s on my system. Maybe that's already enough?

**Comment by cornelinux** [comment]
I like this!
I will export the resolvers and realms and check with this patch!

**Comment by cornelinux** [comment]
This is lighning fast. But acutally we have a small problem: 

This only works with an empty token database, as we also import the the ``id`` into the ``token`` table.
It might be necessary to import into a database with existing tokens. Then the ``id`` would have to be rewritten. 

I will check this.
