### ISSUE TITLE
Mail content sent by email token is rendered as attachment

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#915]
As [reported by icarroll](https://community.privacyidea.org/t/commas-and-newlines-in-otp-email/634/3?u=fredreichbier), mails sent by the email token functionality are rendered as attachments. This is only an issue on the current master.

The problem probably lies in the email MIME type, which is wrongly set to ``"text/text/html"`` because of the line [here](https://github.com/privacyidea/privacyidea/blob/6b4beecf12523e9da93880bd49b954b48a1d4c2b/privacyidea/lib/tokens/emailtoken.py#L408). This is because ``"text/html"`` is passed to the Python MIMEText class, which prepends ``text/`` to the passed string -- so we end up with ``text/text/html``.

If I change the string in the line referenced above to ``"html"``, the emails are correctly rendered as HTML mails.

However, do we actually want to send HTML-only mails by default? Or should we send a plain/html multipart email as [here](https://docs.python.org/2.7/library/email-examples.html#id4)?

**Comment by cornelinux** [comment]
The enhanced email-token-mail-send uses one template file.

I we use multipart, I think we would need to two template files - a plan and an html.

I think if someone uses the template, it is ok to have html?

**Comment by fredreichbier** [comment]
Hm, no idea :) According to a [2011 Stackoverflow answer](https://stackoverflow.com/questions/5787185/is-it-sensible-to-send-html-only-email-these-days), HTML-only are not a good idea due to spam filters :/

Correct me if I'm mistaken, but to me it seems like we're also sending a text/html mail if the template feature is not used?

**Comment by cornelinux** [comment]
Yes. This line you mentioned sends the mail.
https://github.com/privacyidea/privacyidea/blob/6b4beecf12523e9da93880bd49b954b48a1d4c2b/privacyidea/lib/tokens/emailtoken.py#L408

No matter if it is a plain policy or if it is the template.
