### ISSUE TITLE
Also support mysql+pymysql for database backups

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#916]
# What did you try to do?
pi-manage backup create

Please provide your top level intent!
Please provide steps to reproduce!

# What outcome did you expect?
backup in /var/lib/privacyidea/backups

What do you think, how the system should have worked?

# What outcome did you experience?
error unknown sql mysql+pymsql

What did acutally happen?

# Configuration

* privacyIDEA Version:
2.18/19/20/21
* Installation method:
  (from source, github, virtualenv, ubuntu packages...)
pip

## more details: 

* OS: ubuntu 16.04.3

* Webserver: apache

* Tokendatabase: MySQL

# Log file

**Turn on debug level and take a look at the privacyidea.log!**
**If appropriate, attach the log file.**

**Comment by cornelinux** [comment]
You are using a not supported database driver schema.
Only "mysql" and "pymysql" are supported. "mysql+pymysql" is not.

Take a look here: 
https://github.com/privacyidea/privacyidea/blob/master/pi-manage#L234

You might simply enhance the line like:

      elif sqltype in ["mysql", "pymysql", "mysql+pymysql"]:

and check if this works for you?
