### ISSUE TITLE
Enroll token from user details: Username empty

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#918]
In some installations we observed, that when enrolling a token from the user details view, the field ``username`` is empty, although it should be prefilled with the user.

Currently I can not reproduce this on my installations. We have to observe this. If this happens on a system, we should 

1. take a look at the URL, it should look like: ``http://localhost:5000/#/token/enroll/realm/username``.
2. take a look at the Network traffic, if any reqeuest fails.

**Comment by cornelinux** [comment]
This seems to be a timing issue.

I a slow connection to AD I saw that
1. the username field is filled.
2. then the realm field is updated and with the update of the realm field the username field is nulled.

So we might need to remove this logic.

**Comment by fredreichbier** [comment]
Just for the record: I reproduced this by having just one realm and by adding an artificial ``time.sleep(2)`` to ``get_realms_api``.
