### ISSUE TITLE
Allow user to set TOTP Description

### ISSUE THREAD

**Issue by TaylorAtTempus** [privacyidea/privacyidea#928]
Currently, when creating a TOTP token, there is no prompt to enter a description.  This prevents the end user from ever entering a description, since the description field is read only in the token details.  When I log in as an admin I can view and modify the description through token details.   

Would this be something that can be standardized across token types (or for my purposes simply added to the TOTP token type)?
Currently the following token types allow specifying a description upon creation:

- EMail
- SMS
- SSH Public Key

To resolve this, even being to add the description one-time when creating the token would be sufficient, but being able to add it while creating the token and allow users to edit it in the token itself would be ideal.

# Configuration

* privacyIDEA Version: 2.20

* Installation method: Ubuntu packages

## more details: 

* OS: Ubuntu 16.04

* Webserver: Apache

* Tokendatabase: MySQL

**Comment by cornelinux** [comment]
I think such question was asked before.

The user can not set the description on an API level.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/token.py#L667
The description is set via ``/token/set``. THis API is limited to administrators, since this API can also be used for a lot of other stuff like changing the syncwindow.

If we want the user to be able to set the token description, we need to add a new API endpoint and a new policy.

**Comment by TaylorAtTempus** [comment]
End users currently have the ability to specify a description for an SMS token within the PrivacyIDEA application as follows:
Using the PrivacyIDEA application:
If an end user creates an SMS token they can specify a description
![image](https://user-images.githubusercontent.com/33267374/36262188-b27a66f0-1234-11e8-9542-e027712da54a.png)
If they create a TOTP token, they cannot specify a description
![image](https://user-images.githubusercontent.com/33267374/36262218-c9ceb1d0-1234-11e8-87b0-a2f23f8563c9.png)

As an admin, I can edit the Description field for either token type, but end users do not have any ability to specify a Description for a TOTP token.

**Comment by cornelinux** [comment]
So it would be enough to add a field for the description in the enrollment dialog for TOTP/HOTP like at here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.totp.html#L41

and here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.hotp.html#L27

as it is done here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.sms.html#L25

Would you be able to change the html template and create a pull request?
