### ISSUE TITLE
Validity time of api key as parameter

### ISSUE THREAD

**Issue by klinux** [privacyidea/privacyidea#931]
There is any chance to create a parameter for the command:

> $ pi-manage api createtoken -r admin

something like

> $ pi-manage api createtoken -r admin -exp 120

The option to set the expiration time, is more flexible rather than edit pi-manage file to change value.

Thank you.

**Comment by cornelinux** [comment]
Congratulations, you are probably the first to use the API key :-)

This can be easily done in this function.

https://github.com/privacyidea/privacyidea/blob/master/pi-manage#L953

We simply need to add a paramter like

    def createtoken(role=ROLE.ADMIN, days=365):

Would you like to issue a pull request?

**Comment by klinux** [comment]
I seen that you marked this request as enhancement inside the new version 2.22.

Thank you so much!!! :-)
