### ISSUE TITLE
Database reencryption

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#940]
It might be interesting to allow reencrypting the database.

This could be necessary 
* during/before or after migration (see #914)
* or when switching to an HSM
* or when thinking that the encryption key was copromized
* ...

# Approach

Basically there are two different approaches:

1. re-encrypt in the **existing** database
2. re-encrypt into a **new** database

Also we need to take into account, if we only want to re-encrypt the tokendata or also the configuration data. (I suggest the later)

## Re-encrypt in existing database

We probably can not do this online, since it is difficult to know, which data already has been re-encrypted. So if the re-encryption process would walk through thousands of tokens, an authentication request on the later tokens (which has not been reencrypted) does not know, if to read the seeds with the old or with the new encrpytion key.

## Re-encrypt into new database

Re-encrypting into a new database could be an online process. The old database (from which the data is read) could stay online. Well - the counters then might change during the re-encryption process. They would be increased in the old database, while they are still the old values in the new database.

**Comment by cornelinux** [comment]
# Re-import into new encrypted database

we have the possibility to export tokens:

    privacyidea-token-janitor find --action export > token.xml

Exporting (and decrypting) 12.000 tokens takes ~ 1 minute.

This exported XML file could be imported into a new HSM-encrypted database.

**Comment by cornelinux** [comment]
@fredreichbier I think we closed this, didn't we?

**Comment by fredreichbier** [comment]
I think so! A remaining question is whether we can speed up the PSKC import process, but I guess we could discuss that in a new issue.

**Comment by cornelinux** [comment]
RIght. THanks.
