### ISSUE TITLE
Email Token validation check api don't return valid_until  

### ISSUE THREAD

**Issue by klinux** [privacyidea/privacyidea#946]
When we use the Email token /validation/check api, the result of challenge has not the valid_until attribute.

Email Token response
```
{
    "jsonrpc": "2.0",
    "signature": "23925829983283939...",
    "detail": {
        "multi_challenge": [
            {
                "attributes": {
                    "state": null
                },
                "serial": "be9d623b-a7af-4eb1-8ebd-a74abef839ab",
                "transaction_id": "00100808267047909883"
            }
        ],
        "threadid": 139862418716416,
        "attributes": {
            "state": null
        },
        "message": "Enter the OTP from the Email:",
        "serial": "be9d623b-a7af-4eb1-8ebd-a74abef839ab",
        "transaction_id": "00100808267047909883"
    },
    "versionnumber": "2.21.4",
    "version": "privacyIDEA 2.21.4",
    "result": {
        "status": true,
        "value": false
    },
    "time": 1519308563.715886,
    "id": 1
}
```
SMS Token response
```
{
    "jsonrpc": "2.0",
    "signature": "200341928065452...",
    "detail": {
        "multi_challenge": [
            {
                "attributes": {
                    "valid_until": "2018-02-22 11:26:29.188675",
                    "state": null
                },
                "serial": "dc96fff3-14ee-487c-9278-3f7a687bd99d",
                "transaction_id": "07693633112437876699"
            }
        ],
        "threadid": 139862418716416,
        "attributes": {
            "valid_until": "2018-02-22 11:26:29.188675",
            "state": null
        },
        "message": "Enter the OTP from the SMS:",
        "serial": "dc96fff3-14ee-487c-9278-3f7a687bd99d",
        "transaction_id": "07693633112437876699"
    },
    "versionnumber": "2.21.4",
    "version": "privacyIDEA 2.21.4",
    "result": {
        "status": true,
        "value": false
    },
    "time": 1519308989.307912,
    "id": 1
}
```
Is this a bug or is the behavior expected?

Thank you.

**Comment by cornelinux** [comment]
Good question. I do not know anyone who acutally uses this return value...
This is the validity date of the challenge.
Here in the SMS:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/smstoken.py#L301

This would be the place in the Email where to modify the ``return_message``:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/emailtoken.py#L264
The ``validity`` is however available.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/emailtoken.py#L241

Just to clarify, both tokens behave as expected, that the challange is valid for a certain time.
Only difference is, that the SMS token passes this information to the calling client.
But acutally no calling client I know uses this information ;-)

**Comment by klinux** [comment]
I use this information, I need to inform the user the otp time validity, I created a patch to print this attribute on the email token too.

emailtoken.py

```
@log_with(log)
 def create_challenge(self, transactionid=None, options=None):
...
   expiry_date = datetime.datetime.now() + \
                                    datetime.timedelta(seconds=validity)
   attributes['valid_until'] = "{0!s}".format(expiry_date)
   return success, return_message, transactionid, attributes
```

**Comment by cornelinux** [comment]
Perfect. If you need this I am happy to receive your pull request. 

After all, you spotted this inconsitancy, you fixed it, so I am happy to have you add the code and get the credits!
