### ISSUE TITLE
Statistics and dashboard

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#951]
Use RRDTool for data in time series.

https://oss.oetiker.ch/rrdtool/prog/rrdpython.en.html

We can do timeseries over:

* successfull authentications (all or per user, serial, resolver, realm)
* failed authentications (all or per user, serial, resolver, realm)
* API calls (all or per user)
* users, who issued calls
* ...

**Comment by cornelinux** [comment]
rrdtool is based on counters. To provide the necessary counters in the most flexible way, we can add an event handler module *counter*.
This can write/increase counters to a ``counter`` database. The even definition can trigger on any event with any condition. The counter is written with an arbitrary name to the database.

The rrdtool cronjob can read the counters and create the stats and time series.

**Comment by cornelinux** [comment]
Basically we could already create counters using the script handler.

We could increase the counters like this:

    UPDATE Counters SET counter_value = counter_value + 1 WHERE counter_name=....;

The schema would look like this:

    __tablename__ = "counter"
    counter_name = db.Column(db.Unicode(120),
                                                  primary_key=True,
                                                  nullable=False)
    counter_value = db.Column(db.Integer, default=0)

The **counter event handler** would simply have one action with on option:

* action: increase_counter
* option: counter_name

**Comment by cornelinux** [comment]
As an alternative we can run the rrdtool and also combine the analytics with grafana. https://grafana.com/

**Comment by cornelinux** [comment]
We might want to provide the counter values via a REST API like:

    GET /statistics/counters

Well, there is already

    GET /audit/statistics

I would like to avoid to have this at too many places.
Maybe we should move /audit/statistics to /statistics/audit.
Then we could have /statistics/audit, /statistics/counters...

**Comment by cornelinux** [comment]
Such elemets could be displayed on a dashboard.

Take a look at:
http://iarouse.com/dist-flatify/v3.1/#!/dashboard

**Comment by cornelinux** [comment]
if we are going for *chartjs* instead of *rrdtool* we could have a cronjob, that reads the counters and saves the differences in a constant time stept. There would be no need for the dependency to the rrdtool.

**Comment by cornelinux** [comment]
# Statistics endpoints

What kind of API would we need? We should gather everything under one ``/statistics``.

    GET /statistics/counter

To deal with conversion rules and define what data should be collected and processed in e.g. cron job.

    POST /statistics/rule
    GET /statistics/rule

To deal with a dashboard, to define, which graphs should be displayed on a dashboard:

    POST /statistics/dashboard
    GET /statistics/dashboard

# Policies

**ideally either every admin can define his own dashboard or the superuser defines the dashboard for helpdesk users.** So we need to enhance the policies.

**Comment by fredreichbier** [comment]
I only skimmed over this for now (of course we can talk this out in detail), but I was wondering: The argument against using rrdtool is that using it to create graphs server-side is not flexible and inefficient. However, if we don't use rrdtool at all, it seems to me that we would have to re-implement a lot of rrdtool's data processing (i.e. transforming counters into datasets). Maybe it would be a good compromise to use rrdtool server-side for data processing, but not for chart generation, and use client-side chartjs to generate graphs from the data rrdtool generates?

**Comment by cornelinux** [comment]
> Maybe it would be a good compromise to use rrdtool server-side for data processing, but not for chart generation, and use client-side chartjs to generate graphs from the data rrdtool generates?

I also thought of this. But unfortunately there seems no easy way to actually **read** the rrdtool data. You could read it as "normal" XML file, but ``rrdtool`` or the ``rrdtool module`` does not provide an easy way to read it into any python data structure.

**Comment by fredreichbier** [comment]
An interesting rrdtool alternative is [Graphite](http://graphiteapp.org/), which is a server that accepts measurements, stores them in a time-series database ([whisper](http://graphite.readthedocs.io/en/latest/whisper.html), written in Python) and provides a dashboard to analyze the data. There is a pretty interesting [list of tools related to time-series databases](http://graphite.readthedocs.io/en/latest/tools.html) in the documentation.

Graphite looks cool, but is a bit overkill for our use case. Our planned lightweight and easy-to-use statistics dashboard directly integrated with privacyIDEA is a better fit for that.
However, once we have SQL snapshots as in #1028, we could also add a cron runner which pushes data to a Graphite server, so power users could also use Graphite to analyze the same data!

**Comment by cornelinux** [comment]
Yes, I think this is the way to go:

1. Add our own stats to the dashboard for quick and easy use and
2. allow mechanism, plugins, crons whatsoever to connect to other enterprise stats/monitoring tools.

**Comment by splashx** [comment]
Prometheus has become the "de-facto" place to deal with time-series data. We can see how privacyidea exporting this data in a kv format could help teams to integrate virtually any kv-time-series based tool only by probing the pi API.
Example:

a)
- have a (prom) exporter which gets the statistics from privacyidea via REST API 
- expose the metrics in a port (where prom would connect and retrieve it)

b) pi could also listen directly and export the metrics

The problem with b is we pi have to chose which format to support.

**Comment by cornelinux** [comment]
Here is a nice writeup about the questions you need to ask yourself and the step to create a new dashboard. https://linpack-for-tableau.com/news/steps-design-cockpit/

**Comment by NuvandaPV** [comment]
Since this is likely to require adding new libraries (for visualization, etc.), we should add front-end package management first.

**Comment by NuvandaPV** [comment]
depends #1886

**Comment by cornelinux** [comment]
# Further ideads for the dashboard

* [ ] The dashboard could allow shortcuts to actions like "enroll specific tokentype":

**Comment by cornelinux** [comment]
I am closing this, since this issue contains to many deprecated information.
