### ISSUE TITLE
Ask before deleting hardware tokens

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#954]
Deleting a hardware token might be much more problematic than deleting a software token.
A hardware token was imported via a seed file. In certain cases you might not find the seed file again.

Recently we added the tokenkind (hardware, software, virtual).
We could use this, to determine if a token can be deleted or not.

# Abstraction

The tokenkind is a tokeninfo field.
We could add tokeninfo field requirements to token policies. 
Certain actions on tokens then would only be allowed on the corresponding value of the tokeninfo.

**Comment by cornelinux** [comment]
This is a special case of #1618

**Comment by maxbeth** [comment]
What is a better way to change the userdialog?
1. Change "delete token" from the userdialog to unbind and only a unused token can be deleted
2. remove the delete button if it a hardwaredevice
3. the delete only disable and unbind the device from a user

or a policy that only disabled hardware can be deleted.
