### ISSUE TITLE
Overlay issue in privacyIDEA 2.21

### ISSUE THREAD

**Issue by ali-axiadids** [privacyidea/privacyidea#955]
Platform: Amazon Linux
Database: PostgreSQL 9.5
privacyIDEA version: 2.21
Browsers: Chrome Version 64.0.3282.186 (Official Build) (64-bit) and FireFox 58.0.2 (64 bit)

Steps to reproduce:

1- Log in to privacyIDEA web portal
2- Enroll HOTP token (or TOTP)
3- Set validity in Extended attributes section
4- Additionally, re-adjusting the page window causes the header and footer to cover the body

Please see screenshot for additional information.

![errors](https://user-images.githubusercontent.com/35825556/36813146-7f6fc3dc-1c88-11e8-954d-84c6074b7d09.png)

**Comment by cornelinux** [comment]
This occurs when the browser is set to a size, when the top most menu creates a line break but the responsive design does not yet hide the menu in the hamburger item.

**Comment by NuvandaPV** [comment]
I think the nicest way to fix this, would be to hide the labels for the navbar at the top, if the device is too large for the mobile navigation, but too small to fit the full desktop navigation (i.e. less then 1024px) – something like this:

![localhost_(iPad) (2)](https://user-images.githubusercontent.com/13070524/64854550-2767fc80-d61e-11e9-92f9-eaa17f0a7cbd.png)

@cornelinux what do you think?

**Comment by cornelinux** [comment]
cool!

**Comment by NuvandaPV** [comment]
Fixed #1852
