### ISSUE TITLE
Error 404, angularjs fields aren't resvoled

### ISSUE THREAD

**Issue by maxbeth** [privacyidea/privacyidea#963]
i used v2.21.4 and in my access.logs are some errors
Server ubuntu16.4 LTS / Apache / installation from launchpad
Webseite http://localhost -> the logindialog
GET /{{ instanceUrl }}/static/css/{{ piLogo }}
GET /{{ image }}

**Comment by fredreichbier** [comment]
Thanks for the bug report @maxbeth! I reproduced this locally. The reason is probably that we are using ``src=`` and ``href=`` instead of [ng-src and ng-href](https://stackoverflow.com/questions/34796697/angularjs-can-produce-a-404-error-when-using-variable-for-image/34796740) at some places.

**Comment by fredreichbier** [comment]
Fixed by #1006
