### ISSUE TITLE
block login for certain time after failed login attempt

### ISSUE THREAD

**Issue by simvirus** [privacyidea/privacyidea#964]
The **failcounter_exceeded** is really interesting (thank you for it!) but why not "enable" a default brute force mitigation?
Extending the failcounter_exceeded to each failed attempt, it will be necessary to wait for the configurated time after the last attempt.
Thank you!

**Comment by cornelinux** [comment]
I do not understand this. 
If the failcount reaches the maximum a login is not possible anymore.

**Comment by simvirus** [comment]
Sure, but if the "Clear failcounter after minutes" is set, after this time a brute force with a "random PIN" can get the access.
After the "Clear failcounter after minutes" someone can start again a brute force.
Extending the time of  failcounter_exceeded an attacker will have to wait again for the time set for each attempt

**Comment by cornelinux** [comment]
> Sure, but if the "Clear failcounter after minutes" is set, after this time a brute force with a "random PIN" can get the access.

No. A random PIN will get no access. 

> After the "Clear failcounter after minutes" someone can start again a brute force.

This is right. But also the real user could actully login again.
Protecting against brute force and enabling the user to login are two sides of one coin.

> Extending the time of failcounter_exceeded an attacker will have to wait again for the time set for each attempt
Right. But so will have the real user.

As said it is always a tradeoff between protecting against brute force and and allowing the attacker to block the account due to too tight security settings.

After all: None of our bigger users requested such thing, this is why I currently see no necissity for this. So obviously resetting the failcounter after a certain amount of time is acutally enough.

But finally I understand your idea and I will leave this open as an idea with low prio.

**Comment by simvirus** [comment]
> No. A random PIN will get no access.

Sure, I know! ... "random PIN" could get access, sorry for the imprecision.

> This is right. But also the real user could actully login again.
> Protecting against brute force and enabling the user to login are two sides of one coin.
> As said it is always a tradeoff between protecting against brute force and and allowing the attacker to block the account due to too tight security settings.

Setting a low time for "Clear failcounter after minutes" (example 2 min.) could be a good compromise between security and waiting

> After all: None of our bigger users requested such thing, this is why I currently see no necissity for this. 

Maybe they did not think about it...
It's simple to implement (update the value already set) but very effective in my opinion.

> But finally I understand your idea and I will leave this open as an idea with low prio.

Thank you!

**Comment by cornelinux** [comment]
I think you might be misinterpreting the usage of the tokeninfo ``failcounter_exceeded``. It is used to **reset** the failcounter, not to **block** authentication.
But I might also not be able to wrap my head around this today...

**Comment by simvirus** [comment]
Are you sure?
I try to explain to you:

- **failcounter_exceeded** used with:
  - "increase the failcounter if the wrong PIN was entered"
  - "Clear failcounter after minutes"
  - maxfail value

Example:

Token info:

- failcounter_exceeded: 2018-03-07T13:23+0100 
- maxfail = Fail counter

Right PIN: "matching 1 tokens, Failcounter exceeded"
And now after "Clear failcounter after minutes" from "failcounter_exceeded" PI reply to a right PIN:  "matching 1 tokens"

**Comment by cornelinux** [comment]
The tokeninfo field "failcounter_exceeded" is tested to actually **reset** the fail counter after X minutes.

It is set here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokenclass.py#L783

And it is reset, if the timeout time is over:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokenclass.py#L1059

You might achieve your desired scenario easily, but it turn around the programatically logic by 180 degrees.
And to be honst, currently I think this would be a rather annoying feature if users would have to wait another 30 sesc or minutes to try to authenticate again. To my experience users are often to puzzled, they will forget their PIN, they will forget the OTP value or shuffle both. Thus it could take a user several minutes to login.
