### ISSUE TITLE
Event "validate_check" / "UserNotification" does not work anymore

### ISSUE THREAD

**Issue by simvirus** [privacyidea/privacyidea#965]
With privacyIDEA (current version 2.21.4) the event "validate_check" / "UserNotification" does not work anymore.

Note: Send Test Email from SMTP server work correctly.

Here the Event Handler:

INSERT INTO `eventhandler` (`id`, `ordering`, `event`, `handlermodule`, `condition`, `action`, `name`, `active`) VALUES
(1, 0, 'validate_check', 'UserNotification', '', 'sendmail', 'Token locked', 0);

INSERT INTO `eventhandlercondition` (`id`, `eventhandler_id`, `Key`, `Value`, `comparator`) VALUES
(1, 1, 'token_locked', 'True', 'equal');

INSERT INTO `eventhandleroption` (`id`, `eventhandler_id`, `Key`, `Value`, `Type`, `Description`) VALUES
(1, 1, 'body', 'Token "{username} : {userrealm}" locked (max failcounter)\n\n{username} | {userrealm} | {tokentype} | {serial}', '', ''),
(2, 1, 'emailconfig', 'SMTP-Server', '', ''),
(3, 1, 'To', 'email', '', ''),
(4, 1, 'reply_to', '', '', ''),
(5, 1, 'To email', 'admin@xxxx', '', ''),
(6, 1, 'subject', 'Token locked!', '', '');

**Comment by fredreichbier** [comment]
In the first statement you pasted, it looks like the event handler is set to inactive (as ``action`` is set to ``0``). Could that be the case?

Apart from that, could you have a look for useful information and warnings in privacyidea.log?

**Comment by simvirus** [comment]
You are right!
I ignored that symbol... thank you!

![immagine](https://user-images.githubusercontent.com/11424273/37030983-47a47d76-213d-11e8-88db-cecc0c6173b9.png)
