### ISSUE TITLE
Warning: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by wraezor** [privacyidea/privacyidea#967]
Installed privacyIDEA v2.21.4 from PyPi.  Running the createdb command (DB version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1)

```
# pi-manage createdb

             _                    _______  _______
   ___  ____(_)  _____ _______ __/  _/ _ \/ __/ _ |
  / _ \/ __/ / |/ / _ `/ __/ // // // // / _// __ |
 / .__/_/ /_/|___/\_,_/\__/\_, /___/____/___/_/ |_|
/_/                       /___/
   
<SQLAlchemy engine=pymysql://privacyidea:***@localhost/privacyidea>
/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py:165: Warning: (1071, 'Specified key was too long; max key length is 767 bytes')
  result = self._query(query)
```
Database was created with utf8 collation (not utf8mb4).  I also tried both python-mysqldb and pymysqldb connectors and got the same error minus pathing differences.  I wasn't able to get any further detail as to which table this was.

Is this a database design issue or something with version compatibility?  Is this safe to ignore?

**Comment by cornelinux** [comment]
I do not know. You probably provided not enough information.

**Comment by cornelinux** [comment]
If it stems from the unique statements, there are several tables with unique identifiers, which however are all max 255:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L759
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L794
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L889
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L1760
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L1906
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L2050
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L2098

**Comment by renini** [comment]
I actually had the same issue with mariadb-server 10.1 (Debian stable). It has to do with the default of using utf8mb4 format, where column length of 255 actually needs 1020 bytes as length. 
255*4=1020. Where utf8 would have been 765 bytes (255*3).

This is fixed in mariadb-server 10.2 (and mysql 5.7.7) by having innodb_large_prefix=on and ROW_FORMAT=DYNAMIC configurable and as default.

**Comment by wraezor** [comment]
I thought I provided all the information relevant/requested.

# What did you try to do?
I am trying to create the initial privacyIDEA database.  After installation of privacyIDEA as well as pymysql, I setup the config file connection string and other details.

I then ran pi-manage createdb

# What outcome did you expect?

The database creation script to run without errors or warnings.

# What outcome did you experience?

I got a warning about key length.

```
<SQLAlchemy engine=pymysql://privacyidea:***@localhost/privacyidea>
/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py:165: Warning: (1071, 'Specified key was too long; max key length is 767 bytes')
  result = self._query(query)
```

# Configuration

* privacyIDEA Version: v2.21.4
* Installation method: PyPi

## more details: 

* OS: Debian 9.3
* Webserver: Not applicable
* Tokendatabase: MariaDB v10.1.26-MariaDB-0+deb9u1

# Log file

I turned on debug logging in the pi.cfg

PI_LOGFILE = '/var/log/privacyidea/privacyidea.log'
PI_LOGLEVEL = 10

But I do not see any debug level entries from the pi-manage createdb script.  I only get debug when I later run the server.  Nothing is printed during the createdb script running.

**Comment by renini** [comment]
What i did to fix this on debian stable:

- install mariadb-server 10.2 from https://downloads.mariadb.org
- install privacyIDEA and make sure all tables get created without errors
- mysqldump the newly created database-
- check the dump and make sure all tables have: 
   ) ROW_FORMAT=DYNAMIC ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
- remove mariadb-server 10.2
- install mariadb-server 10.1 from debian stable again
- configure mariadb, with innodb_large_prefix=on and  innodb_file_format=Barracuda, for example:
cat /etc/mysql/conf.d/maxkeylengthfix.cnf
[mysqld]
innodb_large_prefix=on
innodb_file_format=Barracuda
- import the mysqldump again

**Comment by renini** [comment]
if the privacyidea create database layout script for mysql would have ROW_FORMAT=DYNAMIC, then only innodb_large_prefix=on innodb_file_format=Barracuda needs to be configured before installing privacyidea.

i couldn't really find where to set this in the code, so i opted for the 10.2 upgrade and dumping it....

**Comment by renini** [comment]
i came across this https://stackoverflow.com/questions/45999430/how-to-set-innodb-storage-format-in-sqlalchemy
but i'm not sure where this can be set in the privacyidea source, @cornelinux maybe you can set this default for mysql/mariadb installations?

**Comment by wraezor** [comment]
Thanks for the helpful details renini.  I may do exactly what you've suggested with the backup & restore.

**Comment by cornelinux** [comment]
@renini thanks for the clarification. @wraezor thanks for the structured information.

> but i'm not sure where this can be set in the privacyidea source, @cornelinux maybe you can set this default for mysql/mariadb installations?

We are using declarative schema definition like this:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L750

So this would have to be adapted like:

<pre>
class Realm(TimestampMethodsMixin, db.Model):
    """
    The realm table contains the defined realms. User Resolvers can be
    grouped to realms. This very table contains just contains the names of
    the realms. The linking to resolvers is stored in the table "resolverrealm".
    """
    __tablename__ = 'realm'
    __table_args__ = {
        'mysql_row_format': 'DYNAMIC'
    }
    id = db.Column(db.Integer, Sequence("realm_seq"), primary_key=True,
                   nullable=False)
    name = db.Column(db.Unicode(255), default=u'',
                     unique=True, nullable=False)
    default = db.Column(db.Boolean(), default=False)
    option = db.Column(db.Unicode(40), default=u'')
</pre>

in all tables where a unique unicode of length 255 would be used.

@renini can you confirm this?

**Comment by renini** [comment]
@cornelinux i think its better to just set the DYNAMIC row format on every table. 
Or atleast that is what i did.
