### ISSUE TITLE
table usercache grows

### ISSUE THREAD

**Issue by maxbeth** [privacyidea/privacyidea#975]
I tested with v2.21.4
i have one user with two tokens and each radius login produce a new entry in the usercache. 
|   1 | gast     | deflocal | 1000    | 2018-03-02 19:11:33 |
|   2 | gast     | deflocal | 1000    | 2018-03-02 19:12:52 |
....
| 198 | gast     | deflocal | 1000    | 2018-03-08 21:25:30 |
| 199 | gast     | deflocal | 1000    | 2018-03-08 21:37:52 |
| 200 | gast     | deflocal | 1000    | 2018-03-08 21:45:56 |

**Comment by cornelinux** [comment]
This is the intended behaviour.
Please read http://privacyidea.readthedocs.io/en/latest/configuration/useridresolvers.html?highlight=usercache#user-cache in regards to expiry and cleanup.

I assume you have added something like 60 seconds.
