### ISSUE TITLE
pi-filter linebreaks / ui-responsive

### ISSUE THREAD

**Issue by maxbeth** [privacyidea/privacyidea#976]
the pi-filter breaks sometime the line and jump back if the filter is active. See the picture
![pi-filter](https://user-images.githubusercontent.com/13170364/37198896-c1c2c036-2377-11e8-9f0e-5ad64c5e1936.png)

on github maxbeth/privacyidea Branch ui-responsive i changed this behaviour and also changed the Bootstrap to container-responsive

**Comment by maxbeth** [comment]
i create a custom-ui.css file with a style "th.pifilter" and assigned to all pi-filter th elements.
Branch 976/ui-layout

**Comment by plettich** [comment]
@cornelinux please check if this issue still exists

**Comment by cornelinux** [comment]
This thing is 5 years old. I can not reproduce this.
@maxbeth does the problem still exist?

**Comment by maxbeth** [comment]
Hello.it was solved.Regards.
-------- Ursprüngliche Nachricht --------Von: Cornelius Kölbel ***@***.***> Datum: 18.03.23  07:28  (GMT+01:00) An: privacyidea/privacyidea ***@***.***> Cc: "M. Maraun" ***@***.***>, Mention ***@***.***> Betreff: Re: [privacyidea/privacyidea] pi-filter linebreaks / ui-responsive
  (#976) 
This thing is 5 years old. I can not reproduce this.
@maxbeth does the problem still exist?
