### ISSUE TITLE
Increase the width of the tables/UI

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#987]
The width of the layout of the complete ui could be increased by changing this line:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/templates/index.html#L7

to use the ``class=container-responsive``.

However, it would make sense to allow increasing the overall width either by configuration or CSS.
In the later case, we would have to add e.g. and ``id`` to the div tag, so that the css can address this.

**Comment by NuvandaPV** [comment]
Depends #989

**Comment by NuvandaPV** [comment]
The width can now be easily set using custom CSS (in fact that is the example used in the documentation). Should we also set a greater width as the default?
