### ISSUE TITLE
Add customize CSS

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#989]
Although there is some description about customizing the theme (http://privacyidea.readthedocs.io/en/latest/faq/customization.html?highlight=customization), it is far from being perfect.
Often you only want to do a small change to the CSS and not change the complete theme.

We should think of a way to easily enhance CSS, like only adding:

```css
.container {
    width: 95%;
} 
```

We probably should take a similar approach like here: http://privacyidea.readthedocs.io/en/latest/workflows_and_tools/enrollment_wizard/index.html?highlight=PI_CUSTOMIZATION#customization

like: If the path ``/pi/mydesign/css/`` contains a file ``custom.css`` include it as stylesheet.

This way we could make small changes and take the original code and style intact.

@maxbeth: what do you think?

**Comment by NuvandaPV** [comment]
fixed #1778
