### ISSUE TITLE
Cron runner

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#992]
We need to be able to define recurring tasks every minute, 5 minutes,  hour...

This can be used to
* process statistics counters (#990)
* rotate audit
* clean-up user cache
* measure other counters based on sql statements
   (Like count all not assigned hardware tokens #986

Such cron definitions would consist of

* time to repeat the task
* condition
* module to handle the task

This could be implemented in a similar modular way like the event handler.

**Comment by fredreichbier** [comment]
So, we would essentially create a "periodic job runner" -- maybe it would be worth a try to look if we can re-use modules like [apscheduler](http://apscheduler.readthedocs.io/en/latest/index.html).

**Comment by cornelinux** [comment]
Yes. Currently I do not know, if we need to implement it on our own, since we might need a certain flexible concept. But looking into what is available makes full sense.

**Comment by splashx** [comment]
Please mind that some folks are using N nodes of privacyidea in active-active mode for horizontal scaling, therefore this architecture relevant because only one node should pick up a cron task to run.

**Comment by cornelinux** [comment]
@splashx thanks for this information!

I might be even interesting, to tell the cron task, which node shoud run it - maybe identified by the hostname or some node id.

Some tasks (like backups to files) might be interesting to run on both nodes. Maybe not at the same time but at different times.

So a cron definition, could also contain the information on which node (list of nodes) this task should run.

**Comment by cornelinux** [comment]
# Cron Runner

The cron runner can run different jobs in privacyIDEA. It is triggered via the systems crontab.

Modules to specify the task to be performed can be defined.

In this issue we should do the following:

1. Create the running **script**, that is called in /etc/crontab
2. Define the **database table**. Administrators will define which jobs should run
   - **lib** and **API** for creating these entries and edit these entries.
3. Create the **base class** for cron *runner modules*.

**Comment by p53** [comment]
hmm it would be best to avoid /etc/crontab -> to avoid dependencies on OS and have self-contained app. eg. create some process which would do the task and use e.g. zeromq timers?

**Comment by cornelinux** [comment]
@p53 thanks for your input. It might also be good to not rely on another 3rd party software component like zeromq. Other software like OTRS or ownCloud/Nextcloud also facilitate cron jobs.
I am also not sure, where the container thingy is going to. Imho, currently there is no sense in running privacyIDEA in a container - and honestly I would not recommend this for the next years as I would prefer a more dedicated separation for a security appliance.

(Disclaimer: I once had a little role in a project facilitating a huge stack our of ZeroMQ (or was it Rabbit), Redis, MongoDB... To me it seemed that a complex stack, that it was hardly possible to get things done - although all current hypewords at this time were used! ;-)

Nevertheless I would be happy if you could elaborate a bit more on this. We will have an internal meeting tomorrow and this would be valuable input! Thanks again!

**Comment by cornelinux** [comment]
Currently we identified the following tasks to be performed by the CronRunner, resulting in the following CronRunnerModules:

* TokenJanitor (no extra DB table necessary)
* AuditLog Rotation (no extra DB table necessary)
* UserCache cleanup (no extra DB table)
* SimpleStatistics (we need an extra DB table!)
* EventCounter (no extra DB table)

![20180619_132536](https://user-images.githubusercontent.com/1908620/41594902-4a6983b4-73c5-11e8-8383-f3cde3b709e8.png)

# DB Model

We need a DB table that stores the configuration as defined by the admin in the UI: ``cronrunner``.

We need a table to store the options of each cronrunner definition: ``cronrunner_option``.

In addition, we need a table, so that the running script can remember, which definition was actually run: ``cronrunner_last_run``.

In contrast to the event handlers we do not explicitly use conditions!

## cronrunner

Columns:

* ``time``, when to run the task
* ``pi-node``, on which node in a privacyIDEA HA setup this task should be run
* ``name``, the name of this definition
* ``class``, the name of the cron runner module.

## cronrunner_option

Each entry in the ``cronrunner`` table can have several options, which are stored in this table:

* ``cronrunner_id``, reference to the definition
* ``key``, the name of the option. These options are defined by the cron runner class module. Could be something like ``not_assigned_hw_token``.
* ``value`` to the key. Could be something like ``True`` or a list of tokentypes ``HOTP TOTP``.

## cronrunner_last_run

The running script needs to know, when a task was run for the last time, so it can decide based on the column ``time``, if the task needs to be run now. But we do not store this time in the table ``cronrunner``, since the last-run-time is a volatile value, while the entries in the table ``cronrunner`` are configuration values.

* ``name`` or ``cronrunner_id``
* ``last_time``
* ``PI-Node``

We also save the privacyIDEA node. It could be, that a task should be run on both PI nodes, and is already run on node A, but not yet run on node B.

# Base Class

The Runnder Class defines the available options and does to acutal work.
So the baseclass has the following look:

~~~~python
class BaseCronRunner(object):

    @property
    def options():
        return {}

    def run():
        return None
~~~~

The property  ``options`` returns a dictionary, that defines the available options and which parameters are used or allowed by the options (like bool or string). This would be similar to the ``actions`` property of an event handler.

**Comment by p53** [comment]
take a look:
https://apscheduler.readthedocs.org/en/latest/
http://celery.readthedocs.org/en/latest/userguide/periodic-tasks.html
just note: we are going to build pi docker image and try to run it in kubernetes cluster in next 2-3months...

**Comment by p53** [comment]
by the way, thanks for invitation :) but i don't have time window for joining, at least  not now

**Comment by fredreichbier** [comment]
Hi @p53, thanks for your input! For now, we decided to go the route of a runner script which gets invoked by the system crontab due to the following reasons:
* More involved solutions like Celery are probably overkill for us right now. Correct me if I'm wrong, but I think they require an additional worker daemon and are mainly useful for one-off tasks that should be handled by some workers (though they also support periodic tasks, as you mentioned). As we only consider a few periodic tasks for now, the worker daemon would just idle most of the time. So I think for most users it makes sense to have a system cronjob invoking our runner script every X minutes (or even hours).
* Once we have that runner script, it can be easily extended to a cron-like daemon for users who do not want to involve the system crontab at all.
Does that sound sensible to you?

**Comment by cornelinux** [comment]
In addition our goal is to provide a solution, that is self contained and simple and thus will work for 90% of the users. Using only a 3rd party system would be overkill for those scenarios.

However, we strive to be still flexible enought, so that we also allow those 3rd party systems - but we avoid to make them mandatory.

**Comment by cornelinux** [comment]
@p53 In regards to containers you could look at it like this:

You have privacyIDEA Webserver running in container A.
You have a database running in container B. privacyIDEA stores the token data, but also the periodic tasks in the database in container B. Now you can use the defined periodic tasks just as you wish to.

We for example - for ease of use - will have a cron runner. You could have a cron daemon running in container C. This would read the periodic tasks from the database in container B. But you could have any other kind of daemon, proprietary system or whatsoever to read the periodirc tasks from container B and execute the tasks in container C. So your suggestions can still be implemented one day as an alternative to our cronrunner. 
Note: There is no need at all to use or setup a cron runner. privacyIDEA will just run fine without it.

**Comment by p53** [comment]
above setup works, i have it like that with php apps
one important note, what if you would like to run e.g. those SMS retries in 30 seconds interval, cron doesn't support this, maybe some other 3-rd party thing yes, but not cron, then is question what if user will have problem with 3-rd party solution X with your cronrunner script, will you support it, how you will test it?
another thing - you said that you want to have self-contained solution (or 12-factor app), but using external binary like cron (it can have bugs out of your control, altough cron is quite stable soft) isnt self-contained app, this means restarting cron when app path changes or env vars change, cron or cron startup script could be buggy, not returning proper status etc..., it introduces more complexity to app management
celery is quite complex yes and probably overkill yes (in my previous work they used celery, but they had more MQ stuff in soft)

**Comment by cornelinux** [comment]
@fredreichbier I would like to close this now but open some issues for the following periodic tasks:

* TokenJanitor (no extra DB table necessary)
* AuditLog Rotation (no extra DB table necessary)
* UserCache cleanup (no extra DB table)

Which have nothing to do with statistics or monitoring, but with tasks...

**Comment by cornelinux** [comment]
* Yes,
* stderr would be written to the cron.log - right? 
* hm. Error handling. Always the most difficult. We could define how often it should be tried. We could write a notification to... whoever. Then the task could be run manually or be fixed... (Just some quick ideas)

**Comment by fredreichbier** [comment]
I've added some fixes to the cron runner here: https://github.com/privacyidea/privacyidea/tree/992/cron-runner-fixes
This adds a ``-c`` flag, which turns off stdout and only writes to stderr in case of an error. Do you think that would be suitable for running it in the crontab?

Regarding error handling: I agree that it's pretty difficult :-) Unfortunately, implementing retries would require model changes (and I'm not sure if we want to do that for 2.23 now). Apart from keeping the current behavior, what we could do without changes to the model: We could make ``privacyidea-cron`` deactivate any periodic task that has failed (in addition to writing to stderr). An admin that somehow monitors the system cron would notice that (but wouldn't get spammed with error messages every five minutes).

**Comment by cornelinux** [comment]
Adding -c is nice. No matter how we call it in the crontab.

In regards to error handling: I am not sure if we want to deactivate the task. Imagine a daily running task. On Monday it fails, since maybe a network resource is missing. But the network resource is back on Tuesday, so it would be great, if the task would run on Tuesday again.

So I would have the admin choose, if a failing task should be deactivated or should simply be tried to run next time.

It would be great if the admin could choose on a per-task level. 
But we can also have the admin choose in the first step with a command line parameter in the privacyidea-cron.

**Comment by cornelinux** [comment]
You added ``-c``.
Close this meta ticket?

**Comment by fredreichbier** [comment]
Sounds OK to me -- should we open a new ticket for error handling in the cron runner then?

**Comment by cornelinux** [comment]
Yes. 
There will be other things, too. These can not be all handled in this issue.
