### ISSUE TITLE
SMS Provider handling with new token enrollment

### ISSUE THREAD

**Issue by wraezor** [privacyidea/privacyidea#993]
# What did you try to do?

I am trying to enroll a new SMS token through the web UI.  I login as Admin, navigate to the "Enroll token" option, choose "SMS" and fill in the phone number and user fields.  The token is successfully created and assigned.  The token even works properly for SMS challenge/response.

# What outcome did you expect?

If anything, I would have expected the token to reference the SMS SMTP Provider since that is the only gateway I have configured in the system.  (It is also chosen in the SMS token settings).  I have a single SMS Gateway setup, that is an SMTP gateway.

Why is there references to an HTTP SMS provider?  I have never set one up.

# What outcome did you experience?

If I look at the properties of the SMS token, I see the see it listed with

> sms.Provider: privacyidea.lib.smsprovider.Ht...

This is confirmed in the database.
```
MariaDB [(none)]> select * from privacyidea.tokeninfo where token_id = 23 and tokeninfo.Key = 'sms.Provider';
+-----+--------------+-------------------------------------------------------------+------+-------------+----------+
| id  | Key          | Value                                                       | Type | Description | token_id |
+-----+--------------+-------------------------------------------------------------+------+-------------+----------+
| 120 | sms.Provider | privacyidea.lib.smsprovider.HttpSMSProvider.HttpSMSProvider |      |             |       23 |
+-----+--------------+-------------------------------------------------------------+------+-------------+----------+
```

All SMS tokens are generated with that sms.Provider set.  This only happens as Admin.  If I enroll as an end user, there is no sms.Provider set for that token. (But I do get the warning "For SMS tokens to work properly you need to set the SMS Token Config!" on the enroll page.)

# Configuration

* privacyIDEA Version: 2.21.4
* Installation method: pip

## more details: 

* OS: Debian 9.4
* Webserver: Apache 2.4.25
* Tokendatabase: MariaDB 10.1.26

# Log file
I have a attached a (hopefully sanitized) debug log.
[privacyidea.log](https://github.com/privacyidea/privacyidea/files/1849601/privacyidea.log)

**Comment by cornelinux** [comment]
@wraezor I assume your SMS token works properly? Can you please confirm?

To my understanding the ``sms.Provider`` in the tokeninfo is a deprecated value, which we should already have removed. It is created by the UI but it is not used anyways.
